### ISSUE TITLE
Parallel installs don't work

### ISSUE THREAD

**Issue by l0ud3st** [nextcloud-snap/nextcloud-snap#1010]
Issue on updating parallel installed snap via hook cause of fix set Service name "nextcloud.apache".
But the Parallel installed Snap Service Name depends on snap instance name set on installation:

snap install nextcloud nextcloud_1 = nextcloud_1.apache

**Comment by kyrofa** [comment]
Hmm, this sounds like a snapd bug, it should probably be remapping those internally. Mind reporting this on https://forum.snapcraft.io/ ?

**Comment by l0ud3st** [comment]
done:
https://forum.snapcraft.io/t/run-configure-hook-of-nextcloud-1-snap-run-hook-configure-error-error-running-snapctl-unknown-service-nextcloud-apache/11422?u=l0ud3st

**Comment by l0ud3st** [comment]
Is there any way to fix this temporarily? I cant change the configure file cause of read only mount.

**Comment by kyrofa** [comment]
*shrug* we've both read that thread. They made some silly decisions when implementing parallel installs, and I don't suggest using them until they fix it. Why _are_ you using them, by the way?
