### ISSUE TITLE
re-enabling nextcloud service reset the datadirectory path!

### ISSUE THREAD

**Issue by SiaNariman** [nextcloud-snap/nextcloud-snap#1018]
Hi, 
Changig the data store doesn't work any more as described [here](https://github.com/nextcloud/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition) . After enable the nextcloud the `datadirectory `path inside config.php reset it self to the default.

### Ubuntu server 18.4.2
**Nexcloud version 15.0.8**

Regards

**Comment by kyrofa** [comment]
I can't duplicate this. Any chance you reverted, which would indeed change the config?
