### ISSUE TITLE
error： The Internet can't connect to Nextcloud，but Intranet can connect to nextcloud

### ISSUE THREAD

**Issue by yoooloo16** [nextcloud-snap/nextcloud-snap#1023]
Nextcloud, my internal network and 80 ports can connect to Nextcloud, the Internet can not connect to Nextcloud, I query 80 ports on Ubuntu 18.04, no listening, I want to know where Apache 2.4 config is located? How to modify it?

**Comment by yoooloo16** [comment]
jiashan@jiashan:~$ netstat -an|grep 80
tcp6       0      0 :::80                   :::*                    LISTEN     
tcp6       0      0 192.168.20.12:80        192.168.20.3:61130      TIME_WAIT  
tcp6       0      0 192.168.20.12:80        192.168.20.3:61143      FIN_WAIT2  
tcp6       0      0 192.168.20.12:80        192.168.20.3:61116      TIME_WAIT

**Comment by yoooloo16** [comment]
I changed the port to 81 so that the Internet could connect to the next cloud, but I wanted to use port 80.

**Comment by yoooloo16** [comment]
array (
      'path' => '/snap/nextcloud/current/htdocs/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/var/snap/nextcloud/current/nextcloud/extra-apps',
      'url' => '/extra-apps',
      'writable' => true,
    ),
  ),
  'supportedDatabases' =>
  array (
    0 => 'mysql',
  ),
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => '/tmp/sockets/redis.sock',
    'port' => 0,
  ),
  'instanceid' => 'oclr5hhe0qey',
  'passwordsalt' => '+0t6lUvZ/u708YCjk2SCBVgWvkzrkP',
  'secret' => 'kVsMNCwtRJw0Uir3l81sJ5chpHvTbB872V/a+3mYGqlAaMbZ',
  'trusted_domains' =>
  array (
    0 => '192.168.20.12',
    1 => '183.249.242.69',
    2 => 'yun.jscig.com',
  ),
  'datadirectory' => '/var/snap/nextcloud/common/nextcloud/data',
  'dbtype' => 'mysql',
  'version' => '15.0.8.1',
  'overwrite.cli.url' => 'http://192.168.20.12',
"/var/snap/nextcloud/current/nextcloud/config/config.php" 51L, 1342C                     36,22         3

**Comment by kyrofa** [comment]
So it works if you use port 81, but not 80? It's possible your ISP may be blocking port 80, then.

**Comment by jeroen7s** [comment]
try enabling https and using port 443 exclusively for access via the internet
https:// urls should always use 443, and that has a lower chance of being blocked by ISP's
