### ISSUE TITLE
No /data Dir

### ISSUE THREAD

**Issue by moore-bryan** [nextcloud-snap/nextcloud-snap#1029]
I'm trying to follow the instructions [here](https://github.com/nextcloud/nextcloud-snap/issues/150) to use an external hd for my files, but my snap install doesn't create a /var/snap/nextcloud/common/nextcloud/data directory, so there's nothing to move.

When I change the config.php file to point to my external hd, I just get internal server errors.

Any ideas?

**Comment by kyrofa** [comment]
> my snap install doesn't create a /var/snap/nextcloud/common/nextcloud/data directory, so there's nothing to move.

It only does that after you've created an admin user (at which time Nextcloud actually sets itself up).
