### ISSUE TITLE
Can not install app

### ISSUE THREAD

**Issue by andrkaz** [nextcloud-snap/nextcloud-snap#1030]
Hello.
Can not install app "Audio player". Error is: 
cURL error 7: Failed to connect to github-production-release-asset-2e65be.s3.amazonaws.com port 443: Connection timed out (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

Also can not update apps: "Music", "ONLYOFFICE", "Metadata"

**Comment by kyrofa** [comment]
That error sounds temporary, have you tried again?

**Comment by andrkaz** [comment]
Of course, nothing happens. I reinstall this apps manually
