### ISSUE TITLE
"dropping privs did not work: No data available" returned when excuting nextcloud.occ command

### ISSUE THREAD

**Issue by kact929** [nextcloud-snap/nextcloud-snap#1036]
I'm trying to use nextcloud.occ command to reset my admin passwd following instructions in [this link](https://github.com/nextcloud/nextcloud-snap/issues/505).

Running:
`sudo nextcloud.occ user:resetpassword admin`
But got the following strings returned:
`dropping privs did not work: No data available`

According to [occ command instructions](https://docs.nextcloud.com/server/9/admin_manual/configuration_server/occ_command.html) in nextcloud official site,I predicted that it was an issue of incorrect permission.

So i ran the following commands instead:
`sudo -u www-data nextcloud.occ user:resetpassword admin`
While got the following results:
`cmd_run.go:884: WARNING: cannot create user data directory: cannot create "/var/www/snap/nextcloud/13453": mkdir /var/www: permission denied
cannot create user data directory: /var/www/snap/nextcloud/13453: Read-only file system
`

**Comment by theoneandonly-vector** [comment]
@kact929 
hey there, try "sudo -u root nextcloud.occ" worked when I ran into this problem by using SETGUID..
