### ISSUE TITLE
Following the reverse proxy wiki guide breaks dav .well-known redirects

### ISSUE THREAD

**Issue by mcphail** [nextcloud-snap/nextcloud-snap#1042]
This may be a duplicate of #803 but could use some attention.

I've followed the wiki guide at https://github.com/nextcloud/nextcloud-snap/wiki/Putting-the-snap-behind-a-reverse-proxy to change my snapped instance to listen on port 444 and have set up haproxy as per the guide. Unfortunately, this breaks the redirections of `.well-known/caldav` and `.well-known/carddav` in the `.htaccess` file.

For example, the line `RewriteRule ^\.well-known/carddav /remote.php/dav/ [R=301,L]` matches a request of `https://my.server/.well-known/carddav` and rewrites it to `https://my.server:444/remote.php/dav/`. Note the insertion of port 444 to the url. From the `mod_rewrite` documentation:
```
Use of the [R] flag causes a HTTP redirect to be issued to the browser. If a fully-qualified URL is specified (that is, including http://servername/) then a redirect will be issued to that location. Otherwise, the current protocol, servername, and port number will be used to generate the URL sent with the redirect. 
```

Thus, the rewrite redirects away from port 443 (on which haproxy is listening and is open to the world) to port 444 (on which the nextcloud snap is listening and is firewalled). The request will never be answered and will just time out.

Is there a way to configure haproxy to stop this behaviour, or is there a tweak we should be making to the `.htaccess` file to work better with proxies?

**Comment by srottschaefer** [comment]
HAProxy can't help you there since you are just proxying encrypted packages to the snap. You would need to be able to recognize requests going to .well-known and redirect them back to remote.php/dav on port 443.
My solution was to let HAProxy handle HTTPS and leave https on the snap disabled.
This way you can manipulate the packages with HAProxy and alter e.g. redirects.

**Comment by mcphail** [comment]
Isn't this still going to be an issue, regardless of whether haproxy or the snap is handling the encryption? The redirect is still going to append the port on which the snap is listening rather than the proxy port which is open to the outside world, as a side effect of the `R` flag in the rewrite rule. Even if I wasn't using HTTPS, the rewrite rule would be appending port 81 rather than port 80.

**Comment by srottschaefer** [comment]
Sorry, I was a bit unclear on this:
You can add configuration so that once HAProxy receives a request for https://my.server/.well-known/{card,cal}dav it can immediately send a redirect to https://my.server/remote.php/dav/ instead of handing it to the snap. It's just a workaround for now but it certainly works for me.

This can only be done when HAProxy handles SSL because it wouldn't know the request URL otherwise.

**Comment by mickmattes** [comment]
@srottschaefer: Could you please elaborate on this? Where do those lines need to be put?

**Comment by srottschaefer** [comment]
Here is my frontend+backend configuration for HAProxy with Nextcloud and Collabora. HTTPS is disabled for the Nextcloud snap because HAProxy takes care of that:
```
frontend http
        bind :::80 v4v6
        bind :::443 v4v6 ssl crt /etc/haproxy/certs

        mode http

        acl path_letsencrypt path_beg /.well-known/acme-challenge/

        acl host_nextcloud hdr(host) -i nextcloud.example.com
        acl host_office hdr(host) -i office.example.com

        acl path_dav path_beg /.well-known/caldav || path_beg /.well-known/carddav

        redirect location "https://nextcloud.example.com/remote.php/dav" if path_dav

        redirect scheme https code 301 if !{ ssl_fc } !path_letsencrypt
        use_backend letsencrypt if path_letsencrypt

        use_backend nextcloud if host_nextcloud
        use_backend collabora if host_office

        default_backend show-403




backend show-403
        mode http
        http-request deny deny_status 403


backend letsencrypt
        mode http
        server letsencrypt 127.0.0.1:10500


backend nextcloud
        mode http
        option httpchk HEAD / HTTP/1.1\r\nHost:localhost

        server nextcloud 127.0.0.1:81 check


backend collabora
        mode http
        option httpchk HEAD / HTTP/1.1\r\nHost:localhost

        server collabora 127.0.0.1:9980 check ssl verify none

```

**Comment by moutasem1989** [comment]
@srottschaefer this works if HAProxy is handeling SSL ... what if Nextcloud does than and HAProxy just rerouts connections ?
