### ISSUE TITLE
occ_web App not working

### ISSUE THREAD

**Issue by scubamuc** [nextcloud-snap/nextcloud-snap#1115]
Hi, I'm an avid nextcloud-snapper and have successfully implemented nextcloud-snap on several productive systems.

On my hosted nextcloud-instance I use the occ_web App for administrative-tasks. 

Now I've tried to activate occ_web on a snap-instance, but failed.

I've searched all issues and could not find an existing issue, so I decided to create a new issue. Please excuse if an issue was overlooked.

The following log appeared:

`[PHP] Error: require_once(): Failed opening required '/var/snap/nextcloud/15565/nextcloud/extra-apps/occweb/lib/Controller/../../../../core/register_command.php' (include_path='/var/snap/nextcloud/15565/nextcloud/extra-apps/news/vendor/pear/net_url2:/var/snap/nextcloud/15565/nextcloud/extra-apps/mail/vendor/pear-pear.horde.org/Horde_Translation:/var/snap/nextcloud/15565/nextcloud/extra-apps/mail/vendor/pear-pear.horde.org/Horde_Util:/var/snap/nextcloud/15565/nextcloud/extra-apps/mail/vendor/pear-pear.horde.org/Horde_Nls:/var/snap/nextcloud/15565/nextcloud/extra-apps/mail/vendor/pear-pear.horde.org/Horde_Exception:/var/snap/nextcloud/15565/nextcloud/extra-apps/mail/vendor/pear-pear.horde.org/Horde_Date:/var/snap/nextcloud/15565/nextcloud/extra-apps/mail/vendor/pear-pear.horde.org/Horde_Stream_Filter:/var/snap/nextcloud/15565/nextcloud/extra-apps/mail/vendor/pear-pear.horde.org/Horde_Stream:/var/snap/nextcloud/15565/nextcloud/extra-apps/mail/vendor/pear-pear.horde.org/Horde_Socket_Client:/var/snap/nextcloud/15565/nextcloud/ at /var/snap/nextcloud/15565/nextcloud/extra-apps/occweb/lib/Controller/OCCApplication.php#112`

GET /index.php/apps/occweb/
from 10.231.4.99 by scuba at 2019-09-05T06:40:48+00:00

Thank you for great software. I hope to be able to assist.

Blubb SCUBA

**Comment by scubamuc** [comment]
bad ticket

**Comment by scubamuc** [comment]
Hi snappers,

I'm going to try to reopen this issue, because the latest upgrades on hosted environments require changes to database `occ db:convert-filecache-bigint`, which could possibly be an issue in a snap environment once 17.x reaches snap-stable.

occweb enables the admin to send occ-commands via the NC UI without having physical access to the device. 

Several of my snap-instances are running on SBC's with Ubuntu 18.04 LTS installed doing unattended upgrades.  

What I have discovered is that occweb can be installed in the snap instance without errors. The App doesn't start though. The result is a white page with no error message. The Error protocoll shows the following message:

Error | PHP | require_once():  Failed opening required  '/var/snap/nextcloud/16739/nextcloud/extra-apps/occweb/lib/Controller/../../../../core/register_command.php'   (include_path='/var/snap/nextcloud/16739/nextcloud/extra-apps/news/vendor/pear/net_url2:/var/snap/nextcloud/16739/nextcloud/extra-apps/mail/vendor/pear-pear.horde.org/Horde_Translation:/var/snap/nextcloud/16739/nextcloud/extra-apps/mail/vendor/pear-pear.horde.org/Horde_Util:/var/snap/nextcloud/16739/nextcloud/extra-apps/mail/vendor/pear-pear.horde.org/Horde_Nls:/var/snap/nextcloud/16739/nextcloud/extra-apps/mail/vendor/pear-pear.horde.org/Horde_Exception:/var/snap/nextcloud/16739/nextcloud/extra-apps/mail/vendor/pear-pear.horde.org/Horde_Date:/var/snap/nextcloud/16739/nextcloud/extra-apps/mail/vendor/pear-pear.horde.org/Horde_Stream_Filter:/var/snap/nextcloud/16739/nextcloud/extra-apps/mail/vendor/pear-pear.horde.org/Horde_Stream:/var/snap/nextcloud/16739/nextcloud/extra-apps/mail/vendor/pear-pear.horde.org/Horde_Socket_Client:/var/snap/nextcloud/16739/nextcloud/  at  /var/snap/nextcloud/16739/nextcloud/extra-apps/occweb/lib/Controller/OCCApplication.php#112
-- | -- | --

Is it possible to get the App working in a snap environment please?

**Comment by kyrofa** [comment]
> I'm going to try to reopen this issue, because the latest upgrades on hosted environments require changes to database occ db:convert-filecache-bigint, which could possibly be an issue in a snap environment once 17.x reaches snap-stable.

The snap takes care of running that for you, can you clarify what you mean by this?

**Comment by scubamuc** [comment]
Thank you for getting back to me on this... if the snap takes care of the issue with the necessary upgrades then thats fine.

Still occ-web app would be nice to have, because nextcloud.occ commands can be issued without physical access to the host-machine.
