### ISSUE TITLE
Theming Color switches back to default after app update

### ISSUE THREAD

**Issue by crustulumtheoneandonly** [nextcloud-snap/nextcloud-snap#1189]
Steps to reproduce:

-activate theming app
-change theming color
-wait for any app update
-make any apps update
-notice header color changed to default

**Comment by PnjDbq** [comment]
I have also had the same issue for a couple of upgrades.  I think it dates back to https://github.com/nextcloud/nextcloud-snap/pull/876 where the app was intentionally disabled on new installs.  Though, like you point out this should not impact upgrades (though in our case, it does).

**Comment by PnjDbq** [comment]
For what it's worth - I did not have his problem with the release of 16.0.8snap1.

I did have the theming app specified in the config settings file (not sure how that got there).  I suspect that was part of the problem but didn't thoroughly test it.
