### ISSUE TITLE
unable to find autoconfig file

### ISSUE THREAD

**Issue by gferrara8596** [nextcloud-snap/nextcloud-snap#1237]
Hi, i wanted to install next cloud but I can't configure the installation because i can't find the configuration file, instead i can find  folder named extra apps but is empty. 
what should i do?

i only used the command

 `sudo snap install nextcloud` 

and wanted to configure the installation...

![Schermata 2020-02-01 alle 16 28 41](https://user-images.githubusercontent.com/57630661/73594637-67b61180-4510-11ea-804e-e22d2cbf38a2.png)

**Comment by kyrofa** [comment]
Yeah extra-apps is the writable directory, where apps from the app store go when you install them. Take a look at the [configuration section](https://github.com/nextcloud/nextcloud-snap#configuration) of the README that discusses how to configure the snap.

**Comment by gferrara8596** [comment]
> Yeah extra-apps is the writable directory, where apps from the app store go when you install them. Take a look at the [configuration section](https://github.com/nextcloud/nextcloud-snap#configuration) of the README that discusses how to configure the snap.

I've read that.

![Schermata 2020-02-01 alle 20 17 40](https://user-images.githubusercontent.com/57630661/73597770-f6865680-452f-11ea-8fac-c650d326a8ee.png)

Is written that I've to edit configuration in the file `/var/snap/nextcloud/current/nextcloud/config/config.php` but i cannot find it! I need to change the main hdd to an external hdd for the storage and set https and the ports but i can't without that file.

**Comment by kyrofa** [comment]
Hmm, it should have been put there when you installed it. Can you paste in the output of [this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts), please?

**Comment by gferrara8596** [comment]
Done, I've putted the result in a file because I've expected a big result...

<img width="334" alt="Schermata 2020-02-02 alle 11 14 29" src="https://user-images.githubusercontent.com/57630661/73606689-51aa5e80-45ad-11ea-8b10-6a4113a91547.png">


[script.txt](https://github.com/nextcloud/nextcloud-snap/files/4143799/script.txt)

**Comment by kyrofa** [comment]
What is your operating system? Seems that it doesn't put `/snap` on the PATH.

**Comment by gferrara8596** [comment]
I'm using a raspberry pi with the last raspbian version

**Comment by llftony** [comment]
Exactly the same problem :-(
@gferrare8596: did you find a solution ?
thx, llftony

**Comment by gferrara8596** [comment]
Unfortunately not yet... :(

**Comment by loengsje** [comment]
I am also currently trying to setup nextcloud on a Raspberry Pi 4 running Raspbian. I have also encountered the problem of not being able to find the autoconfig.php in the desired path. I have found one at a different location though:
/snap/nextcloud/25282/htdocs/config/autoconfig.php
But unfortunately it's unwritable even with root.

@gferrara8596 Did you find a solution?
Did anyone else encounter this problem?

**Comment by GurenMarkV** [comment]
Same issue. RPi 4. Installed Nextcloud but cannot find the config or autoconfig file. Not even in @loengsje location with /25282/.
Is this an overall snap issue? 

Really hoping there is a solution soon.

**Comment by kyrofa** [comment]
Is anyone NOT on a raspberry pi? That darn ld.so error makes it impossible to see what's happening.

**Comment by meghadeep-com** [comment]
Docker image of NC20.0.7 seems to have the same problem. Weird thing is, I have another docker instance of NC20.0.7, but it shows the MacOS/iOS configuration profile. The docker-compose file has identical configuration except for the obvious (e.g. names, urls, etc.).
