### ISSUE TITLE
Video previews are not generated & some videos won't play on 18.0.4

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud-snap/nextcloud-snap#1314]
#### Describe the bug
In gallery, previews (thumbnails) of video files are not generated. Playing some videos doesn't work, only shows black screen and sound.

#### To Reproduce
1. go to gallery
2. see that video files are loading thumbnails (screenshot)
3. try playing some video files. Some will work, others not.

#### Screenshots
picture: preview never loads
![Screenshot_2](https://user-images.githubusercontent.com/36133540/80277753-83851a00-86f1-11ea-8476-6126eec67d80.png)

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud
18.0.4snap1 rev 20498 latest/stable

and:

    $ snap version
snap 2.44.3
snapd 2.44.3
series 16
ubuntu 19.10
kernel 5.3.0-46-generic

**Comment by montvid** [comment]
If having ffmpeg is not possible and the ffmpeg snap won't solve this issue then how to disable showing these generic icons in the photos app?
