### ISSUE TITLE
Support for TLS-ALPN-01 

### ISSUE THREAD

**Issue by sachingupta010** [nextcloud-snap/nextcloud-snap#1392]
Hello, 
This is a re-open of https://github.com/nextcloud/nextcloud-snap/issues/789 and a resolution will be useful for those who can not have port 80 opened. 
Certbot 1.4.0 has Added TLS-ALPN-01 challenge support in the acme library. Support of this challenge in the Certbot client is planned to be added in a future release.
It may be possible in the future to add an option on the command nextcloud.enable-https lets-encrypt to allow for the use of tls-alpn-01 instead of http-01
Just FYI.

Thanks

**Comment by kyrofa** [comment]
> Support of this challenge in the Certbot client is planned to be added in a future release.

Like I said in #789, we use certbot in the snap. Until that client adds ssupport for TLS-ALPN-01, there's nothing we can do short of transitioning to a completely different ACME client. That's possible, but not something we're looking to take on at this time. If someone wants to make a PR moving the snap to to acme.sh or dehydrated.io I'd be willing to entertain it, but keep the following in mind:

- The snap automatically updates
- The snap cannot break
- Thousands of people using the snap currently have a cert retrieved with certbot, and are relying on the snap to continue automatically updating that cert for them without user interaction

**Comment by sachingupta010** [comment]
Possibly another way of achieving this by using uacme/ualpn and the certbot plugin:

https://github.com/ndilieto/certbot-ualpn

Arguably it will increase the number of dependencies you have in the snap but you won’t have to put in a new acme client.

**Comment by lapo-luchini** [comment]
[Certbot issue regarding this](https://github.com/certbot/certbot/issues/6724).
