### ISSUE TITLE
HTTPS with NGINX shows port number

### ISSUE THREAD

**Issue by saadsaifse** [nextcloud-snap/nextcloud-snap#1411]
Hi, I am running NGINX with this snap package and I followed the guide [here](https://github.com/nextcloud/nextcloud-snap/wiki/Putting-the-snap-behind-a-reverse-proxy). 

I have hosted NextCloud on one my subdomain which is working fine except that when browsing through HTTPS, the URL redirects to `https://nextcloud.xyz.com:444` instead of staying at `https://nextcloud.xyz.com`. I have HTTPS enabled using Let's Encrypt. 

Any suggestions?

**Comment by kyrofa** [comment]
You're sure nginx is configured as a reverse proxy instead of a redirect? If so, see the "note" I just added to that wiki page (I took it from the README):

> **Note:** Nextcloud's automatic hostname detection can fail when behind a proxy; you might notice it redirecting incorrectly. If this happens, override the automatic detection (including the port if necessary), e.g.:
>
>     $ sudo nextcloud.occ config:system:set overwritehost --value="example.com:81"

**Comment by saadsaifse** [comment]
I have no specific redirect in NGINX for this subdomain.
When I overwrite the host, it automatically redirects to exactly that host. That means using
```
$ sudo nextcloud.occ config:system:set overwritehost --value="example.com:81"
```
will specifically add port `81` in the URL. Same goes for port `444`.  But when I overwrite without port, the `Not Secure - Your Connection is not private` page shows up, even though the protocol is `https` at that time. Even at this stage, specifying port `444` still works.

**Comment by Leptopoda** [comment]
@saadsaifse is terminating the ssl at your reverse proxy an option?

This works flawless for me...

**Comment by y0va** [comment]
For me terminating ssl at the frontend proxy is no option, as I use SSL passthrough with SNI, as port 443 is shared with another service that requires an own certificate.  Would like to have them neatly separated.  

Would be fine to have the apache rule use the configured hostname with port.

This still is an issue.
