### ISSUE TITLE
Snap revert broke some things

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud-snap/nextcloud-snap#1440]
#### Describe the bug
I reverted my snap installation to fix some server problems I thought were caused by the recent upgrade (they were actually not caused by that, but I didnt know that at the time). After seeing that the problems occur on older version still, I upgraded back to the newest version (we're talking two latest snap versions, going back and forth). After that I discovered a number of things simply not working.

- Couldn't play some video files using Android client
- Notes stopped working altogether (https://github.com/nextcloud/notes/issues/590)
- I had issues with client (linux+win) acting out, E2EE stopped working (would not sync).

I had restored a full server backup I had taken before reverting the snap and everything started working again. I conclude that it must have been the snap revert and/or the following upgrade that caused the mess. I have never needed snap revert as as all upgrades worked very well (kudos) but if by chance I need to revert sometime, I better restore server backup instead.

#### To Reproduce
1. snap revert (to latest stable version -1)
2. upgrade back (to latest stable version)

#### Expected behavior
no problems found

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  19.0.1snap3  22653  latest/stable  nextcloud✓  -

and:

snap    2.45.3.1
snapd   2.45.3.1
series  16
ubuntu  20.04
kernel  5.4.0-42-generic
#### Logs

Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).

**Comment by kyrofa** [comment]
> After seeing that the problems occur on older version still, I upgraded back to the newest version (we're talking two latest snap versions, going back and forth). After that I discovered a number of things simply not working.

So to clarify, did you notice these issues when you reverted? Or only after you refreshed again? There's only one way to revert, but there are multiple ways to "un-revert". How did you go about that?

**Comment by pilsnerbeer** [comment]
>So to clarify, did you notice these issues when you reverted?

Unfortunately I cant say. It is possible that the revert alone caused the server to act out and refresh had no effect on functionality. When I reverted, I was looking out to fix that specific issue I thought was caused by most recent upgrade. I started noticing multiple problems after I upgraded the server (snap refresh) but that was only because I started using NC/app as I normally do.

>There's only one way to revert, but there are multiple ways to "un-revert"

I went and executed snap refresh manually from console. NC was then upgraded. When I discovered it didnt go well (again, either the upgrade or revert messed it up although the auto upgrades had always been seamless) I restored server backup (fixed everyting).

**Comment by kyrofa** [comment]
Using test data (don't do this on your production instance, obviously), do you think you can come up with a minimal reproducer? Try installing from `18/stable`, refreshing to `19/stable`, then reverting and refreshing again. If you can figure out a way to consistently reproduce this then we can chase it down.
