### ISSUE TITLE
Nextcloud only displays a white screen

### ISSUE THREAD

**Issue by utybo** [nextcloud-snap/nextcloud-snap#1528]
#### Describe the bug

When going on my nextcloud, I am met with a white screen. Only my instance's logo (the little pokémon head on the top left) and my user picture can be seen. I'm also getting a bunch of errors in the dev console.

#### To Reproduce

1. Just go on your instance

#### Expected behavior

1. Everything should be working normally

#### Screenshots

![image](https://user-images.githubusercontent.com/5175705/97308514-3c730f80-1861-11eb-87a2-235fc90b1b01.png)

![image](https://user-images.githubusercontent.com/5175705/97308820-9542a800-1861-11eb-9b1c-0e4aaa67e103.png)

#### OS/snapd/snap version

Lubuntu 20.04.1

    $ snap list nextcloud
    nextcloud 20.0.1snap1 24051 latest/stable nextcloud -
and:

    $ snap version
    snap    2.47.1+20.04
    snapd   2.47.1+20.04
    series  16
    ubuntu  20.04
    kernel  5.4.0-52-generic

#### Logs

The logs are way too long for GitHub, i put them in a pastebin instead: https://pastebin.com/adJA4RhP

**Comment by scubamuc** [comment]
Hi, it seems like sidebar app is causing problems in 20.x. Usually incompatible apps are disabled on upgrade. There  are a few apps which are still incompatible in 20.x "untested" . Sidebar may not work in 20.x.

You could revert to 19.x and then disable sidebar app and then try to refresh to 20.x again

This is possibly not a snap issue.

**Comment by utybo** [comment]
Just fyi, the snap upgraded itself without me doing anything to it. I'll try reverting to 19 and see if that helps.

**Comment by kyrofa** [comment]
> The logs are way too long for GitHub, i put them in a pastebin instead: https://pastebin.com/adJA4RhP

Hmm, those are truncated as well, I guess try attaching them?

**Comment by utybo** [comment]
Dang it, RealVNC truncated it when i copy pasted it, give me a sec

**Comment by utybo** [comment]
There it is, my apologies

[debug.txt](https://github.com/nextcloud/nextcloud-snap/files/5446369/debug.txt)

**Comment by Minnietheandroid** [comment]
Same white screen here after snap auto-updated from 19.04.

**Comment by PnjDbq** [comment]
Same issue on my install - after upgrade the dashboard is blank.

My install is not using the "Hide sidebars" app referenced in above comment.

Since I can click the menu in the top right, I was able to go into the apps and start disabling them.  The new "dashboard" app that's the issue.  Toggling it on / off solves & recreates the issue.  Restarting the system / snap does not appear to have an impact.

Unsure as to what the conflict is.  But for now, the workaround appears to be disabling the dashboard app.

Only errors in the log appear to be related to requests form the desktop sync clients.  The clients work fine but are generating OC_Helper.php errors.

```
$ snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  20.0.1snap1  24051  latest/stable  nextcloud✓  -
```
```
$ snap version
snap    2.47.1
snapd   2.47.1
series  16
ubuntu  20.04
kernel  5.4.0-52-generic
```

**Comment by kyrofa** [comment]
Thank you, @PnjDbq. @Minnietheandroid, @utybo can you confirm that this seems to be caused by the dashboard app? I can't duplicate this, so I expect the dashboard app is somehow clashing with another app that you also have installed. Can I get the logs (or at least a list of apps installed) from @PnjDbq and @Minnietheandroid, please?

**Comment by kyrofa** [comment]
Similarly, @PnjDbq have you tried disabling other apps while leaving dashboard enabled? Basically, is the culprit only dashboard, or is it a combination of dashboard and something else that is the issue?

**Comment by utybo** [comment]
I can confirm that disabling the dashboard plugin fixes this issue. It is indeed still possible to access installed app via clicking on the profile image and choosing Apps then disabling the dashboard app.

**Comment by Minnietheandroid** [comment]
I don't really know how to provide the logs properly but hope these are helpful...
![Screenshot from 2020-10-28 06-12-42](https://user-images.githubusercontent.com/3885113/97351333-b51baf80-18e5-11eb-8847-a94395ff3066.png)
[nclog.txt](https://github.com/nextcloud/nextcloud-snap/files/5447611/nclog.txt)

**Comment by PnjDbq** [comment]
> Similarly, @PnjDbq have you tried disabling other apps while leaving dashboard enabled? Basically, is the culprit only dashboard, or is it a combination of dashboard and something else that is the issue?

I did disable everything except the dashboard and the problem persists (both in the latest Chrome & Firefox with freshly cleared cache & incognito).

![Screenshot 2020-10-27 141207](https://user-images.githubusercontent.com/37458932/97351117-527fd080-185f-11eb-8e5b-dca711d314d1.png)

There are a couple of "extra" apps showing in the command line that don't appear in the web UI.  Presumably, these are core and can't be disabled.


```
$ sudo nextcloud.occ app:list
Enabled:
  - cloud_federation_api: 1.3.0
  - dashboard: 7.0.0
  - dav: 1.16.0
  - federatedfilesharing: 1.10.1
  - files: 1.15.0
  - lookup_server_connector: 1.8.0
  - oauth2: 1.8.0
  - provisioning_api: 1.10.0
  - settings: 1.2.0
  - twofactor_backupcodes: 1.9.0
  - viewer: 1.4.0
  - workflowengine: 2.2.0
```

I didn't dump a list of active apps *before* disabling everything.  Here's the list of what I think is normally active in my setup:

```
$ sudo nextcloud.occ app:list
Enabled:
  - activity: 2.13.2
  - admin_audit: 1.10.0
  - bruteforcesettings: 2.0.1
  - cloud_federation_api: 1.3.0
  - dashboard: 7.0.0
  - dav: 1.16.0
  - federatedfilesharing: 1.10.1
  - files: 1.15.0
  - files_external: 1.11.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - impersonate: 1.7.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.0
  - provisioning_api: 1.10.0
  - richdocuments: 3.7.5
  - richdocumentscode: 6.4.13
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - suspicious_login: 3.2.1
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_u2f: 6.0.0
  - viewer: 1.4.0
  - workflowengine: 2.2.0
```

**Comment by PnjDbq** [comment]
I enabled the app and poked around a bit more.

Only observation in the logs is a lot of errors to the OC_Helper.php file.  Don't recall seeing these prior to v20.

A lot of the Helper.php errors appear to be triggered by the desktop sync app.  The specific error below appears to align with to an attempt to load the dashboard app (`index.php/apps/dashboard/`)

```
{"reqId":"Aht88xSw9YnpTdFQoUfR","level":3,"time":"2020-11-04T16:00:10+00:00","remoteAddr":"xxx","user":"xxx","app":"PHP","method":"GET","url":"/index.php/settings/user","message":{"Exception":"Error","Message":"Undefined offset: 3 at /snap/nextcloud/24051/htdocs/lib/private/legacy/OC_Helper.php#548","Code":0,"

Trace":[{"file":"/snap/nextcloud/24051/htdocs/lib/private/legacy/OC_Helper.php","line":548,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[8,"Undefined offset: 3","/snap/nextcloud/24051/htdocs/lib/private/legacy/OC_Helper.php",548,{"path":"/","rootInfo":{"__class__":"OC\\Files\\FileInfo"},"includeExtStorage":false,"used":31637726507,"quota":-3,"mount":

{"__class__":"OC\\Files\\Mount\\MountPoint"},"storage":{"cache":null,"scanner":

{"__class__":"OC\\Files\\Cache\\Scanner"},"watcher":null,"propagator":null,"updater":null,"__class__":"OCA\\Files_Trashbin\\Storage"},"sourceStorage":{"cache":null,"scanner":

{"__class__":"OC\\Files\\Cache\\Scanner"},"watcher":null,"propagator":null,"updater":null,"__class__":"OCA\\Files_Trashbin\\Storage"},"free":1170986029056,"total":1202623755563,"relative":2.63,"ownerId":"xxx","ownerDisplayName":"xxx","owner":

{"__class__":"OC\\User\\User"}}]},

{"file":"/snap/nextcloud/24051/htdocs/apps/settings/lib/Settings/Personal/PersonalInfo.php","line":108,"function":"getStorageInfo","class":"OC_Helper","type":"::","args":["/"]},

{"file":"/snap/nextcloud/24051/htdocs/apps/settings/lib/Controller/CommonSettingsTrait.php","line":141,"function":"getForm","class":"OCA\\Settings\\Settings\\Personal\\PersonalInfo","type":"->","args":[]},

{"file":"/snap/nextcloud/24051/htdocs/apps/settings/lib/Controller/PersonalSettingsController.php","line":77,"function":"formatSettings","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":[{"10":[{"__class__":"OCA\\Settings\\Settings\\Personal\\PersonalInfo"}],"1000":[{"__class__":"OCA\\Settings\\Settings\\Personal\\ServerDevNotice"}]}]},

{"file":"/snap/nextcloud/24051/htdocs/apps/settings/lib/Controller/CommonSettingsTrait.php","line":152,"function":"getSettings",
"class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":["personal-info"]},

{"file":"/snap/nextcloud/24051/htdocs/apps/settings/lib/Controller/PersonalSettingsController.php","line":68,"function":"getIndexResponse","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":["personal","personal-info"]},{"file":"/snap/nextcloud/24051/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"index","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":["personal-info"]},

{"file":"/snap/nextcloud/24051/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\PersonalSettingsController"},"index"]},

{"file":"/snap/nextcloud/24051/htdocs/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\PersonalSettingsController"},"index"]},

{"file":"/snap/nextcloud/24051/htdocs/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\PersonalSettingsController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"section":"personal-info","action":null,"_route":"settings.PersonalSettings.index"}]},

{"file":"/snap/nextcloud/24051/htdocs/lib/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/user"]},

{"file":"/snap/nextcloud/24051/htdocs/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/snap/nextcloud/24051/htdocs/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},

"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36","version":"20.0.1.1","id":"5fa2d0111a5cb"}`
```

**Comment by kyrofa** [comment]
Yeah that sounds like https://github.com/nextcloud/server/issues/23595, which will be fixed in 20.0.2.

**Comment by kyrofa** [comment]
You can confirm the fix by testing out `20/edge`, by the way. That's the current state of stable20.

**Comment by PnjDbq** [comment]
50/50 with update to `20/edge`.

The `OC_Helper.php` errors are gone but the dashboard app still displays a white screen.

Oddly, refreshing to `--channel=20/edge` kept getting stuck at the post-refresh hook.  The refresh worked fine with `--channel=latest/edge`.

...going to revert back to 20/stable and disable the dashboard app for now.

**Comment by JMoVS** [comment]
I ran into this problem a couple of times and rebooting my server helped

**Comment by HiranChaudhuri** [comment]
I have the same white-screen-but-logo-and-user symptom on Nextcloud 20.0.8 with these installed apps:

```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - calendar: 2.1.3
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.3
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_external: 1.11.1
  - files_pdfviewer: 2.0.1
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.3
  - provisioning_api: 1.10.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - tasks: 0.13.6
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather: 1.7.4
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - encryption
  - files_rightclick
  - privacy
  - recommendations
  - user_ldap
```

In my case when I disable the dashboard app obviously the landing page after login changes. The menu on top looks empty, on the left I can see some entries and the main are is also empty. When hovering above the top meny I can see the entries appear, so they exist but are rendered in white on white?

All in all, disabling the dashboard has not resolved the issue for me.

**Comment by ph00lt0** [comment]
@HiranChaudhuri have you checked the debug.txt file? and if this doesn't tell you the problem could you share the contents?

**Comment by HiranChaudhuri** [comment]
Where in the filesystem should I expect debug.txt?

```
$ docker exec -it nextcloud find / -name debug.txt
find: '/proc/1/map_files': Operation not permitted
find: '/proc/37/map_files': Operation not permitted
find: '/proc/38/map_files': Operation not permitted
find: '/proc/47/map_files': Operation not permitted
find: '/proc/49/map_files': Operation not permitted
find: '/proc/50/map_files': Operation not permitted
find: '/proc/63/map_files': Operation not permitted
find: '/proc/155/map_files': Operation not permitted
find: '/proc/156/map_files': Operation not permitted
find: '/proc/157/map_files': Operation not permitted
find: '/proc/170/map_files': Operation not permitted
find: '/proc/179/map_files': Operation not permitted
$
```

**Comment by ph00lt0** [comment]
@HiranChaudhuri I am confused what are you doing exactly. You seem to use Docker. This is the Nextcloud Snap repo, not docker image (https://github.com/nextcloud/docker). If you do not have permission in the device it won't show you the files.

**Comment by HiranChaudhuri** [comment]
@ph00lt0 Thank you for pointing out the snap. I came here following links from search engines since after all the symptoms I have are the same. I will raise an issue on the docker repository.
