### ISSUE TITLE
Can't See Client IP in Apache & NextCloud Logs when Behind IIS Reverse Proxy

### ISSUE THREAD

**Issue by UbuntuMan22** [nextcloud-snap/nextcloud-snap#1610]
Dear Developers,

I'm running NextCloud behind a Windows IIS Reverse Proxy. All working fine and users are able to access via browser, desktop app and Android. However, i'm not able to see the client's IP in Apache & Nextcloud Logs. All I see is the Reverse Proxy IP only. 

I tried all possible options for "forwarded_for_headers" & "trusted_proxies". However, still not able to get the "X-Forwarded-For" value passed to my Nextcloud server. 

Could it be the Apache logs format? I don't think that I can modify it in snap installation? Please help and guide. 

Here are details about my installation:

NextCloud Version: 20.0.4
OS: Ubuntu 18.04.5 LTS

Example of Apache Logs:
{Reverse Proxy IP} - - [16/Jan/2021:01:08:07 ] "GET /index.php/apps/serverinfo/update HTTP/1.1" 200 1135 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36"

**Comment by brenzi** [comment]
I have the same issue. the log always shows 127.0.0.1 and nextcloud's bruteforce protection kicks in constantly which is highly annoying

Ubuntu 20.04
snap info nextcloud: 20.0.7snap1

I run an apache2 reverse proxy on the host with 
```
<IfModule mod_ssl.c>
<VirtualHost *:443>
    ServerName my_server_name

    ProxyPreserveHost On

    ProxyPass / http://127.0.0.1:1080/
    ProxyPassReverse / http://127.0.0.1:1080/

...SSL stuff ....
```

**Comment by dinosmm** [comment]
I have a similar issue. My NC Snap is behind nginx as a reverse proxy, and every client that connects is seen as 127.0.0.1, which means I don't get email notifications when a new IP logs in. I got the first notification the first time a new IP connected (and it showed as 127.0.0.1), and I have tried connecting from other new IPs but not seeing any notifications since.

Is this the same problem or should I open another issue?
Can it be resolved with some nginx config parameter I am not aware of?

**Comment by brenzi** [comment]
this is not solved. is it?

**Comment by UbuntuMan22** [comment]
Hi there,

Nope, didn't receive anything. I really forgot about it.

It sounds like if you have no paid support.. Then you are alone..

**Comment by pachulo** [comment]
Well, this sound like something that a configuration on the snap could allow. PRs are welcome!

**Comment by strikeoncmputrz** [comment]
I've been trying to resolve this issue from behind an ingress-nginx proxy in Kubernetese and have confirmed that my proxy is populating X-Forwarded-For. Everything else works. 

There is a mountain of forum posts where people are grabbing at straws. I too have tried a number of random permutations of "trusted_proxies" and "forwarded_for_headers" and nothing works.  

The documentation should at least account for one or two of the most popular proxies. Massive security issue that simply goes unanswered.

**Comment by kyrofa** [comment]
We're all volunteers here, folks.

**Comment by strikeoncmputrz** [comment]
> We're all volunteers here, folks.

You are 100% correct here. Misguided crankiness on my part. Sorry dude.

**Comment by kyrofa** [comment]
> Our apache is not hiding any passed headers from our php-backend, right?

Not on purpose anyway. If so it's a bug.

> You are 100% correct here. Misguided crankiness on my part. Sorry dude.

Hey no problem, we've all been there :) .
