### ISSUE TITLE
Putting the snap behind a reverse proxy  -- Connection Refused

### ISSUE THREAD

**Issue by Telefza** [nextcloud-snap/nextcloud-snap#1653]
Hi, 

I followed the instructions [here](https://github.com/nextcloud/nextcloud-snap/wiki/Putting-the-snap-behind-a-reverse-proxy#nginx) but nothing seems to work.
I used the nginx revese proxy.

Nothing works and when I check `/var/log/nginx/error.log` I simply get connection refused from `127.0.0.1:444`.

I disabled the firewall and https but it  still simply says connection refused.
I did set nextcloud to listen to 81 and 444:  `sudo snap set nextcloud ports.http=81 ports.https=444`

**Comment by Uxio121** [comment]
Same problem here, any solution?

**Comment by leetxyz** [comment]
I think you have a problem with the certificates...

My setup looks like this:

WAN -> Firewall / Router -> nginx on VM1 (ubuntu 20.04) with LetsEncrypt -> nextcloud snap 20.0.7 on VM2 (ubuntu 20.04).

`snap get nextcloud ports`

> Key Value
> ports.http 80
> ports.https 443

My nginx-config:

> server
> {
>     client_max_body_size 16G;
>     listen 443 ssl http2;
>     ssl_certificate /etc/letsencrypt/live/<redacted>/fullchain.pem; # managed by Certbot
>     ssl_certificate_key /etc/letsencrypt/live/<redacted>/privkey.pem; # managed by Certbot
>     include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
>     ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
>     server_name subdomain.example.com;
>     location / {
>         proxy_pass http://<internal ip address of VM2>; # no port -> it uses port 80 internally
>         proxy_set_header Host $host;
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>         proxy_set_header X-Forwarded-Proto $scheme;
>         }
> }

The connection from VM1 to VM2 is not encrypted in my config.

**Comment by adrianvg** [comment]
FWIW, I couldn't get a reverse proxy solution built from scratch to work either.
I did however have a docker test-vm on which I installed an nginx reverse proxy container (https://github.com/jc21/nginx-proxy-manager) and had it set up. It was irritatingly easy and worked right of the bat.
It worked so great I decided to keep it..

My point is that you can have a look at the conf-files the container creates, to get an idea what to put in the reverse proxy-conf to get your own solution to work.
HTH.

**Comment by Fuseteam** [comment]
fwiw i did manage to get it to work but skimming through what is provided in the issue I cannot see what the difference is
