### ISSUE TITLE
Setup reverse proxy for "notify_push"

### ISSUE THREAD

**Issue by Pilzinsel64** [nextcloud-snap/nextcloud-snap#1655]
Hello.

An another question, just because I already did it and know it could be a bit complicated when using the snap.

Would it be an option to install and configure the app "notify_push" by default in the NC21 snap?
Since the Apache configuration is read-only, it would be hard to setup a reverse proxy (at least for home usage, e.g. using a single Raspberry Pi) without opening a new port for the notify_push service. This is the only but big point in my opinion.

It's just a question if it would be an idea or not.

### UPDATE:
It's only requierd for the snap to have the reverse proxy setted up (enable by cli or enabled by default). Because ClientPush can already be installed using an **unencrypted** connection through an **addition open port** to the internet.
See my comment at the bottom: https://github.com/nextcloud-snap/nextcloud-snap/issues/1655#issuecomment-975330965

### UPDATE 2:

I added a [wiki entry here](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-how-to-install-files-hpb-client-push). This demonstrates how I'm able to install Client Push at the moment without a built-in solution.

**Comment by pachulo** [comment]
@Pilzinsel64 do you have more info on what you did to set this up with the snap?

@kyrofa I think that we could explore if it would be feasible to create toggle on the snap to use the notify_push. I guess that we would need to:
* Create the [service](https://github.com/nextcloud/notify_push#setting-up-the-service) inactive so we can activate when the toggle is on
* Add the [Apache config](https://github.com/nextcloud/notify_push#apache) but only activate it if the toogle is on

**Comment by kyrofa** [comment]
We've got another thread about this on #1843 as well. @andybalaam mentioned that it didn't seem to improve performance at all given his tests, we might want to let this mature a bit before sinking any work into it.

**Comment by andybalaam** [comment]
Hmm, I didn't modify my apache config, so maybe the tests I did were invalid?

**Comment by pachulo** [comment]
@andybalaam did you try the [test client](https://github.com/nextcloud/notify_push#test-client)?

**Comment by Pilzinsel64** [comment]
It is possible to setup. But without revert proxy you need to open a new port to the internet.
I can provide some more infos, but I'm at work atm. Will do that during the day. Sorry for the delay.

PS: Even if it not improves the performance, it provides instant push notificiations instead of polling notifications for the most clients. Thats important especially for talk.

**Comment by andybalaam** [comment]
@pachulo no, I missed that - thank you.  I'll try it out.

**Comment by Pilzinsel64** [comment]
@pachulo First, sorry for the delay. :/

Then, to quickly answer your question... You install the server app "Client Push", then configure the reverse proxy (or open a new port to the internet, if you can't setup a reverse proxy) and lastly setup the "Client Push" app with one command via occ.
Detailed install instructions are here:
https://github.com/nextcloud/notify_push
If you want a detailed explaination how I did it myself, just tell me. But before, let's talk about a problem and a possible workaround for that would make a detailed description more useless.

The problem I see here is similar to #1700 where you can't know the domain that you need for the occ command to setup the client push app.

One workaround would be:
- Implement the reverse proxy by default, because it wont break anything and shouldn't break any security (but security is not my topic 😁)
- Do NOT install and configure the client push app by default
- BUT provide a quick "how to" for configure client push via occ. E.g. where to find the info about the installedredits-server and how to build the URL to use (so how the reverse proxy is pre-configured).
That is something I could takeover, if you want. But definetly it would need a review, because my English is not really good.

For the workaround the single part that has to be done in the snap is this:
https://github.com/nextcloud/notify_push/#apache

What do you think about the problem and the workaround? In my opinion it's not really possible to fully configure the client push. But you could pre-configure the reverse proxy to make it easier for the user.

**Comment by andybalaam** [comment]
OK, so I'm trying to follow the [instructions on how to configure the reverse proxy](https://github.com/nextcloud/notify_push#apache) and apply them to the running snap.  I managed to find httpd.conf at /snap/nextcloud/current but I can't find a `a2enmod` command that I can use to enable the required modules, and I can't find a `modules-enabled` directory to add the symlinks manually.

Any hints?

**Comment by pachulo** [comment]
> OK, so I'm trying to follow the instructions on how to configure the reverse proxy and apply them to the running snap.

Yo won't be able to, this is how snaps work. To be able to use the Apache from the snap as the reverse proxy you would need to modify the snap source, built it and install it.

**Comment by pachulo** [comment]
> The problem I see here is similar to #1700 or #1794 where you can't know the domain that you need for the occ command to setup the client push app.

What do you think about this  @kyrofa? Is there any way to get the domain?

> In my opinion it's not really possible to fully configure the client push. But you could pre-configure the reverse proxy to make it possible for the user to install client push. Otherwise it wouldn't work, even with opening a port to the internet, because the client push app wants an URL with http or https.

Totally, I was thinking about something similar. The snap would have some configuration parameter that, when enabled, would allow the app to be used by the snap, but the user would need to install it and configure it.

**Comment by Pilzinsel64** [comment]
> What do you think about this @kyrofa? Is there any way to get the domain?

The only options (as I know) to get the domain while snap running would be:
1. Let the user enter the URL or let him pre-config with an snap variable
2. Use the URL from 'overwrite.cli.url' property in config.php
3. Use the URLs from 'trusted_domains' property in config.php

**Comment by Pilzinsel64** [comment]
However... I guess the only solution would be pre-configuring the reverse proxy in the snap source by putting in three lines to the apache config.
For this, one thing that needs to be discussed for this would be the security aspect for that the reverse proxy would let you access a local port from the web via http(s), even if the client push app isn't configured.

**Comment by Pilzinsel64** [comment]
Well, after a lot more testing I guess this is not possible in snap without notify_push supports database connections throw sockets.
Because this is the output if I try to start the binary manually:
![grafik](https://user-images.githubusercontent.com/23138465/142832088-804ffe9e-9a6e-4596-9389-cfecb2f70ef1.png)
And that's the database host:
![grafik](https://user-images.githubusercontent.com/23138465/142832189-edfb6559-ee7a-407c-862a-864873cdfe35.png)

I will check the issues (and create one) at the notify_push repo. Let's come back to this, if that issue has been solved, I guess.

**Comment by Pilzinsel64** [comment]
Well, after some other tests and research I finally got notify push to work (using unencrypted http and opening a port).
![grafik](https://user-images.githubusercontent.com/23138465/142837144-a0b2598e-c620-4770-ace8-b0b4e32da713.png)

Using this official instruction how to setup in snap. Check here (collapsed area): https://github.com/nextcloud/notify_push#systemd

The only thing missing would be the reverse proxy. This is the part the user absolutely can't do, because the apache configuration is read-only.

**Comment by Pilzinsel64** [comment]
Well, after some other tests and research I finally got notify push to work (using unencrypted http and opening a port).
![grafik](https://user-images.githubusercontent.com/23138465/142837144-a0b2598e-c620-4770-ace8-b0b4e32da713.png)

Using this official instruction how to setup in snap. Check here (collapsed area): https://github.com/nextcloud/notify_push#systemd

The **only** thing missing would be the reverse proxy. This is the part the user **absolutely can't do**, because the apache configuration is read-only.

**Comment by pachulo** [comment]
Hi @Pilzinsel64 ! Thanks for the info!

> Should I try make a pull request with the changes added to the apache config or htaccesss file? Or how would you like to implement this or do you want to see this implemented at all? I ask because it's still not clear, if this get implemented, if it should be toogleable on and off or if it's just on. @kyrofa @pachulo

Yes, a PR is very welcome!

Regarding the how, my vote goes for having this implemented as a toggle that the user will need to turn on before installing the `notify_push` application.

What are your thoughts @kyrofa ?

**Comment by Pilzinsel64** [comment]
> Regarding the how, my vote goes for having this implemented as a toggle

And that's also a question in how to implement that. Hardccoded is not a problem, I can do this. But for a toogle (if it's possible somehow) I miss some technical know how for the snap system, I guess.
Maybe we can do the same (or something similar) as for [http compression](https://github.com/nextcloud-snap/nextcloud-snap#http-compression-configuration)? If yes, I could check out how this has been implemented.

**Comment by pachulo** [comment]
> Maybe we can do the same (or something similar) as for http compression? If yes, I could check out how this has been implemented and oriantate me on it.

Totally, I think that the approach should be almost the same.

The only thing that I don't really know how to do are the tests...any ideas there @kyrofa ?

**Comment by pachulo** [comment]
Gently ping @kyrofa ! ;)

**Comment by Refhi** [comment]
If I may also add a gentle ping ?

(I must say notify_push is really interesting to me, and I'd like to avoid a full reinstall on a new VM without snap just for that end)

thanks for your work !

**Comment by SubhashBose** [comment]
Since this thread is over a year old, just wondering if there is any plan to add this small but important feature in the next update?

Thanks for your snap package, it's perfect for lightweight installations. 

`notify_push` looks very important, and I personally think this should be active in the default installation. Or at least it should be supported for manual setup.

I main problem with manual setup of `notify_push` is we can not activate apache modules and edit apache configuration to setup reverse proxy to `/push` path.

This is the only reason I am looking to Nextcoud AIO docker, but that would be a bit too heavy and unnecessary for my requirements.

**Comment by tatrapikao** [comment]
Hi there, currently i am struggeling to set up notify push. I followed the asteps from the wiki (https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-how-to-install-files-hpb-client-push) but i am stuck with the following  error after `sudo nextcloud.occ notify_push:setup http://cloud.domain.de:7867`:
![Bildschirmfoto_2023-07-26_22-31-56](https://github.com/nextcloud-snap/nextcloud-snap/assets/77448960/3165d6cc-8cb7-4c30-a098-4220f0518953)

I wonder if it may be connected to me changing domains in the past? After a recent update letsencrypt and nextcloud used the old domain again and i had to manualy renew the certificate for the actual domain. But now i removed the legacy domain from config.php and changed letsencrypt domain as mentioned here (https://github.com/nextcloud-snap/nextcloud-snap/wiki/Managing-encryption) wich btw did not work but was solved by this post: https://github.com/nextcloud-snap/nextcloud-snap/issues/406#issuecomment-999510141

So after fiddeling for hours im quite lost and would really apriciate a hint.

**Comment by Pilzinsel64** [comment]
Hi @tatrapikao 
I've never seen this error and it sounds a little like an adventure you absolved.
However, it looks like you are using the localhost domain and this is wrong. The certificate is issued for e.g. `mycloud.com` and not for `localhost` You need to use the public domain. Also, the url you enter here will be used by client and they are not able to use the localhost address.
So try to replace localhost with your public domain and it should work. :)

**Comment by tatrapikao** [comment]
Thank you for this super fast reply! Can you send my in the right direction where to change localhost to domain?

**Comment by tatrapikao** [comment]
So for unknown reasons  overwrite.cli.url was set to http://localhost (Im pretty shure i never changed this value). After changing it to http://cloud.mydomain.de notify_push:setup run succesfull. I'm not shure if changing this affects anything alse but for the moment it seems to work?

**Comment by Pilzinsel64** [comment]
For everyone who want to test this out: See #2490. We now have builds for `amd64` architecture at the channel `latest/beta/pr-2490`.

But please beware! This is a temporary beta channel. If you try this on your prod, ensure there is a possibility that you can go back at any time (and you probably should until the pr is merged), e.g. via `snap revert nextcloud`.

I try to keep the PR up-to-date with `latest/beta` until it has been reviewed & merged, so switching from `latest/beta` is possible.

**Comment by pachulo** [comment]
This should be availalbe very soon, now that https://github.com/nextcloud-snap/nextcloud-snap/pull/2490 has been merged!
