### ISSUE TITLE
Session timeout

### ISSUE THREAD

**Issue by TidalWave123** [nextcloud-snap/nextcloud-snap#1676]
when I change config.php to include:

'remember_login_cookie_lifetime' => 0,
'session_lifetime' => 6000,
'session_keepalive' => false,

The website no longer functions and I get a contact administrator warning. I'm just trying to set a session timeout of 6 hours after first login, either browser in use or not. Please assist.

A security requirement for us to use next-cloud is to have automatic timeouts which force re-authentication. 

for example if user1 goes home for the day, and the next day a user2 logs into the same computer, user2 is currently able to access to all of user1's files, if for example, user1 forgets to log out. 

I appreciate the astronomical amount of work you do.

**Comment by kyrofa** [comment]
I'm sorry for the lack of response. This is a Nextcloud-specific question, not a snap-specific question. I'm afraid I've never used this feature and thus cannot advise, but I suggest asking on https://help.nextcloud.com where you will get people more familiar with these features.
