### ISSUE TITLE
Not Enough Free Space, but I clearly have enough free space

### ISSUE THREAD

**Issue by cindrmon** [nextcloud-snap/nextcloud-snap#1680]
Hello.

I'm having issues uploading files onto my nextcloud snap instance.

For some reason, downloading works fine, but when I'm uploading files, it says that I don't have enough free space, despite only using just 28% of my allocated space for my account.

I have been self-hosting this nextcloud instance, and I don't know why I can't upload.

This is what it looks like:
![nextcloud_issue](https://user-images.githubusercontent.com/37018771/111891814-abc7e680-8a30-11eb-80fc-ddef1c5e3979.gif)

**Comment by BomabayNitefrog** [comment]
I had a similar problem.
I don't know if the solution is the same, but for me it was a partition size problem.
I set up Nextcloud by ticking it off in the Ubuntu Server install process. This apparently only allocates 200GB to /dev/mapper/ubuntu--vg-ubuntu--lv which is mounted as /

check with:
# df

if this is the problem, you can resize the partition like this:
# umount /
# e2fsck -f /dev/ubuntu-vg/ubuntu-lv
# resize2fs -p /dev/ubuntu-vg/ubuntu-lv

restart the server, just in case :)

Maybe someone can elaborate on what this actually does? it was the end of a long Google-jurney :D

**Comment by cindrmon** [comment]
For some reason, I haven't changed anything, yet I was able to upload files, but in really specific cases.

1. I can upload by dragging the file into the folder (but I must be at the root folder to do it).
2. Uploading hangs when I do the same procedure as above but in subfolders, and when I refresh, it would just reset everything.
3. I can't upload from within the folder, and this would cause the "Not enough free space" error.

![newProblems](https://user-images.githubusercontent.com/37018771/114326511-bc6b0880-9b67-11eb-8743-b27ba5c0d2ff.gif)

**Comment by BomabayNitefrog** [comment]
Have you tried opening the folder you are dragging content into? That works for me. I have had the same issue, but I'm not sure if it's a browser issue or NC. 
I run firefox with a handful of privacy and ad blocking extensions and it's a bit buggy sometimes. Have you tried if it works in a different browser?

**Comment by cindrmon** [comment]
Apparently, I can only upload files in the root home, but not in its subfolders. I cannot upload directly from the root, but I have to put it in a folder that's already located in the root. If I try uploading from the subfolders (either by clicking and dragging them into the folders or by clicking and dragging them inside the folder themselves), it doesn't work. Somehow, the only way I can upload to my nextcloud instance is by clicking and dragging files from the root home to a folder, and nothing else.
