### ISSUE TITLE
Cannot connect to calendar from Android

### ISSUE THREAD

**Issue by Lotze83** [nextcloud-snap/nextcloud-snap#1681]
#### Describe the bug
Hello,

I am using nextcloud snap and everything is working fine except calendar connection for android phones..

On my Iphone it's OK, httpd://myserveur.com/remote.php/dav with SSL and credential
On android with DAVX i have this error:

[log_xdav.txt](https://github.com/nextcloud/nextcloud-snap/files/6181430/log_xdav.txt)

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud:
nextcloud 20.0.7snap1 26119 latest/stable

and:

    $ snap version

snap 2.49
snapd 2.49
series 16
ubuntu 20.10
kernel 5.8.0-45-generic

#### Logs
[log1.txt](https://github.com/nextcloud/nextcloud-snap/files/6181176/log1.txt)

It's work from local IP with Android but not with public URL...

thank you for your help

Stéphane

**Comment by Lotze83** [comment]
sorry i find the problem on sudo nextcloud.occ config:system:get trusted_domains

ty

**Comment by ph00lt0** [comment]
@lotze83 this seems a problem with your DNS or firewall not with nextcloud snap. At least the server as configured in your logs is not reachable.
