### ISSUE TITLE
Cannot delete or move files/folders from External storage.

### ISSUE THREAD

**Issue by erikbernt23** [nextcloud-snap/nextcloud-snap#1696]
#### Describe the bug
When attempting to move files/folders from External Storage through the Nextcloud web interface( a locally attached folder in this case), an error message "You are not permitted to move this file" appears. If I SSH into the server, I can manipulate the files/folders without issue.

www-data is the owner of the folder tree in question and ownership is set to 755. It is possible to create files/folders in the external storage folder.

#### To Reproduce
1. Go to file/folder to be moved.
2. Click on move/copy
3. See error message "You are not permitted to move this file"

#### Expected behavior
Moving/copying files/folders between external storage.

#### OS/snapd/snap version

Debian 10 and snap version 2.49.2

 Please also include the output of the
following commands:

    $Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  20.0.8snap1  27089  latest/stable  nextcloud✓  -

and:

    $ snap version

snap    2.49.2
snapd   2.49.2
series  16
debian  10
kernel  4.19.0-16-amd64

#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).

**Comment by scubamuc** [comment]
Check permissions on external file/folders, must belong to root. 
www-data is not for snap.
try; owner:root group:www-data
