### ISSUE TITLE
Builds on X/edge channels not updated

### ISSUE THREAD

**Issue by pachulo** [nextcloud-snap/nextcloud-snap#1827]
There seems to be a problem with the daily builds of the `X/edge` channels: they seem stuck at 15th of June.

**Comment by kyrofa** [comment]
Sadly, this is a known issue. It's due to Travis CI's shutdown. I need to move things to use GitHub Actions, but I'm waiting for some internal Nextcloud politics to play itself out before I continue.

**Comment by kyrofa** [comment]
Alright, these are back up and running. Still need to be TESTING them every day as well, but at least we're generating them again.
