### ISSUE TITLE
skeletondirectory

### ISSUE THREAD

**Issue by wangyifan349** [nextcloud-snap/nextcloud-snap#1828]
I modified the skeletondirectory of config.php
But create a new user
The user did not copy the files in the directory
It seems that config.php cannot take effect

'skeletondirectory' => '/1',

However, files from folder 1 will not be copied
The folder is located in the root directory
Permission is 777

**Comment by wangyifan349** [comment]
Folder 1 is in the lowest directory

**Comment by kyrofa** [comment]
The skeleton directory is copied into new users' areas, which means it needs to be readable by the snap. The snap is confined, though, and it can't access the root of your HD. Try putting the skeleton in `/var/snap/nextcloud/current` somewhere instead.

**Comment by wangyifan349** [comment]
Thank you for your help
The problem is solved by your solution

**Comment by kyrofa** [comment]
Excellent!
