### ISSUE TITLE
Latest auto snap update disabled the sql database that was filled with users photos

### ISSUE THREAD

**Issue by ASmith-** [nextcloud-snap/nextcloud-snap#1840]
Describe the bug
Users and myself attempting to view any of the thousands of photo images taken by users are shown a loading error. The logs indicate a syntax change occuring with the latest snap auto update is causing this in the MySQL Server.

A clear and concise description of the bug.
Error: An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'configvalue` + 1)` WHERE (`userid` = 'tascloud') AND (`configkey` = 'read') AND ' at line 1

To Reproduce
Select the Photos Folder, check any image to view
Error loading IMG_20210828_135058034_HDR.jpg

Expected behavior
The chosen image is displayed

OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud
nextcloud 22.1.1snap1 Rev 28503 latest stable nextcloud
and:
    $ snap version
snap 2.51.4
snapd 2.51.4
series 16
linux mint 19.3
kernel 4.15.0-96-generic

Additional
Mysql
8.0.26
992.3 MB

PHP
7.4.23
Memory Limit 4 GB

formatted error log
[index] Error: An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'configvalue` + 1)` WHERE (`userid` = 'tascloud') AND (`configkey` = 'read') AND ' at line 1

GET /index.php/core/preview?fileId=5377649&x=1440&y=900&a=true
from 192.168.1.4 by tascloud at 2021-09-13T20:26:26+00:00

raw error log
{"reqId":"cQC7f2kYjtVLrYYX10KA","level":3,"time":"2021-09-13T20:26:26+00:00","remoteAddr":"192.168.1.4","user":"tascloud","app":"index","method":"GET","url":"/index.php/core/preview?fileId=5377633&x=1440&y=900&a=true","message":"An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'configvalue` + 1)` WHERE (`userid` = 'tascloud') AND (`configkey` = 'read') AND ' at line 1","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36","version":"22.1.1.2","exception":{"Exception":"Doctrine\\DBAL\\Exception\\SyntaxErrorException","Message":"An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'configvalue` + 1)` WHERE (`userid` = 'tascloud') AND (`configkey` = 'read') AND ' at line 1","Code":1064,"Trace":[{"file":"/snap/nextcloud/28503/htdocs/3rdparty/doctrine/dbal/src/Connection.php","line":1728,"function":"convert","class":"Doctrine\\DBAL\\Driver\\API\\MySQL\\ExceptionConverter","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Driver\\PDO\\Exception"},{"__class__":"Doctrine\\DBAL\\Query"}]},{"file":"/snap/nextcloud/28503/htdocs/3rdparty/doctrine/dbal/src/Connection.php","line":1667,"function":"handleDriverException","class":"Doctrine\\DBAL\\Connection","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Driver\\PDO\\Exception"},{"__class__":"Doctrine\\DBAL\\Query"}]},{"file":"/snap/nextcloud/28503/htdocs/3rdparty/doctrine/dbal/src/Connection.php","line":1146,"function":"convertExceptionDuringQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Driver\\PDO\\Exception"},"UPDATE `oc_preferences` SET `configvalue` = `(`configvalue` + 1)` WHERE (`userid` = ?) AND (`configkey` = ?) AND (`appid` = ?)",["tascloud","read","user_usage_report"],[2,2]]},{"file":"/snap/nextcloud/28503/htdocs/lib/private/DB/Connection.php","line":262,"function":"executeStatement","class":"Doctrine\\DBAL\\Connection","type":"->","args":["UPDATE `oc_preferences` SET `configvalue` = `(`configvalue` + 1)` WHERE (`userid` = ?) AND (`configkey` = ?) AND (`appid` = ?)",["tascloud","read","user_usage_report"],[2,2]]},{"file":"/snap/nextcloud/28503/htdocs/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":213,"function":"executeStatement","class":"OC\\DB\\Connection","type":"->","args":["UPDATE `oc_preferences` SET `configvalue` = `(`configvalue` + 1)` WHERE (`userid` = :user) AND (`configkey` = :action) AND (`appid` = :appid)",{"appid":"user_usage_report","user":"tascloud","action":"read"},{"user":2,"action":2}]},{"file":"/snap/nextcloud/28503/htdocs/lib/private/DB/QueryBuilder/QueryBuilder.php","line":287,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[]},{"file":"/var/snap/nextcloud/28503/nextcloud/extra-apps/user_usage_report/lib/Listener.php","line":82,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"/var/snap/nextcloud/28503/nextcloud/extra-apps/user_usage_report/lib/Listener.php","line":64,"function":"storeAction","class":"OCA\\UserUsageReport\\Listener","type":"->","args":["read"]},{"file":"/var/snap/nextcloud/28503/nextcloud/extra-apps/user_usage_report/lib/AppInfo/Application.php","line":54,"function":"fileRead","class":"OCA\\UserUsageReport\\Listener","type":"->","args":[]},{"file":"/snap/nextcloud/28503/htdocs/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":264,"function":"OCA\\UserUsageReport\\AppInfo\\{closure}","class":"OCA\\UserUsageReport\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/snap/nextcloud/28503/htdocs/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":239,"function":"doDispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[[{"__class__":"Closure"},{"__class__":"Closure"}],"*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/snap/nextcloud/28503/htdocs/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[[{"__class__":"Closure"},{"__class__":"Closure"}],"*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/snap/nextcloud/28503/htdocs/lib/private/EventDispatcher/SymfonyAdapter.php","line":123,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/snap/nextcloud/28503/htdocs/lib/private/Preview/Generator.php","line":105,"function":"dispatch","class":"OC\\EventDispatcher\\SymfonyAdapter","type":"->","args":["*** sensitive parameter replaced ***",{"__class__":"Symfony\\Component\\EventDispatcher\\GenericEvent"}]},{"file":"/snap/nextcloud/28503/htdocs/lib/private/PreviewManager.php","line":189,"function":"getPreview","class":"OC\\Preview\\Generator","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"},1440,900,false,"fill",null]},{"file":"/snap/nextcloud/28503/htdocs/core/Controller/PreviewController.php","line":169,"function":"getPreview","class":"OC\\PreviewManager","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"},1440,900,false,"fill"]},{"file":"/snap/nextcloud/28503/htdocs/core/Controller/PreviewController.php","line":142,"function":"fetchPreview","class":"OC\\Core\\Controller\\PreviewController","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"},1440,900,true,true,"fill"]},{"file":"/snap/nextcloud/28503/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"getPreviewByFileId","class":"OC\\Core\\Controller\\PreviewController","type":"->","args":[5377633,1440,900,true,true,"fill"]},{"file":"/snap/nextcloud/28503/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\PreviewController"},"getPreviewByFileId"]},{"file":"/snap/nextcloud/28503/htdocs/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\PreviewController"},"getPreviewByFileId"]},{"file":"/snap/nextcloud/28503/htdocs/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Core\\Controller\\PreviewController","getPreviewByFileId",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"core.Preview.getPreviewByFileId"}]},{"file":"/snap/nextcloud/28503/htdocs/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/core/preview"]},{"file":"/snap/nextcloud/28503/htdocs/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/snap/nextcloud/28503/htdocs/3rdparty/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php","Line":84,"Previous":{"Exception":"Doctrine\\DBAL\\Driver\\PDO\\Exception","Message":"SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'configvalue` + 1)` WHERE (`userid` = 'tascloud') AND (`configkey` = 'read') AND ' at line 1","Code":1064,"Trace":[{"file":"/snap/nextcloud/28503/htdocs/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","line":84,"function":"new","class":"Doctrine\\DBAL\\Driver\\PDO\\Exception","type":"::","args":[{"errorInfo":["42000",1064,"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'configvalue` + 1)` WHERE (`userid` = 'tascloud') AND (`configkey` = 'read') AND ' at line 1"],"__class__":"PDOException"}]},{"file":"/snap/nextcloud/28503/htdocs/3rdparty/doctrine/dbal/src/Connection.php","line":1136,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDO\\Statement","type":"->","args":[]},{"file":"/snap/nextcloud/28503/htdocs/lib/private/DB/Connection.php","line":262,"function":"executeStatement","class":"Doctrine\\DBAL\\Connection","type":"->","args":["UPDATE `oc_preferences` SET `configvalue` = `(`configvalue` + 1)` WHERE (`userid` = ?) AND (`configkey` = ?) AND (`appid` = ?)",["tascloud","read","user_usage_report"],[2,2]]},{"file":"/snap/nextcloud/28503/htdocs/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":213,"function":"executeStatement","class":"OC\\DB\\Connection","type":"->","args":["UPDATE `oc_preferences` SET `configvalue` = `(`configvalue` + 1)` WHERE (`userid` = :user) AND (`configkey` = :action) AND (`appid` = :appid)",{"appid":"user_usage_report","user":"tascloud","action":"read"},{"user":2,"action":2}]},{"file":"/snap/nextcloud/28503/htdocs/lib/private/DB/QueryBuilder/QueryBuilder.php","line":287,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[]},{"file":"/var/snap/nextcloud/28503/nextcloud/extra-apps/user_usage_report/lib/Listener.php","line":82,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"/var/snap/nextcloud/28503/nextcloud/extra-apps/user_usage_report/lib/Listener.php","line":64,"function":"storeAction","class":"OCA\\UserUsageReport\\Listener","type":"->","args":["read"]},{"file":"/var/snap/nextcloud/28503/nextcloud/extra-apps/user_usage_report/lib/AppInfo/Application.php","line":54,"function":"fileRead","class":"OCA\\UserUsageReport\\Listener","type":"->","args":[]},{"file":"/snap/nextcloud/28503/htdocs/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":264,"function":"OCA\\UserUsageReport\\AppInfo\\{closure}","class":"OCA\\UserUsageReport\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/snap/nextcloud/28503/htdocs/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":239,"function":"doDispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[[{"__class__":"Closure"},{"__class__":"Closure"}],"*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/snap/nextcloud/28503/htdocs/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[[{"__class__":"Closure"},{"__class__":"Closure"}],"*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/snap/nextcloud/28503/htdocs/lib/private/EventDispatcher/SymfonyAdapter.php","line":123,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/snap/nextcloud/28503/htdocs/lib/private/Preview/Generator.php","line":105,"function":"dispatch","class":"OC\\EventDispatcher\\SymfonyAdapter","type":"->","args":["*** sensitive parameter replaced ***",{"__class__":"Symfony\\Component\\EventDispatcher\\GenericEvent"}]},{"file":"/snap/nextcloud/28503/htdocs/lib/private/PreviewManager.php","line":189,"function":"getPreview","class":"OC\\Preview\\Generator","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"},1440,900,false,"fill",null]},{"file":"/snap/nextcloud/28503/htdocs/core/Controller/PreviewController.php","line":169,"function":"getPreview","class":"OC\\PreviewManager","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"},1440,900,false,"fill"]},{"file":"/snap/nextcloud/28503/htdocs/core/Controller/PreviewController.php","line":142,"function":"fetchPreview","class":"OC\\Core\\Controller\\PreviewController","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"},1440,900,true,true,"fill"]},{"file":"/snap/nextcloud/28503/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"getPreviewByFileId","class":"OC\\Core\\Controller\\PreviewController","type":"->","args":[5377633,1440,900,true,true,"fill"]},{"file":"/snap/nextcloud/28503/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\PreviewController"},"getPreviewByFileId"]},{"file":"/snap/nextcloud/28503/htdocs/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\PreviewController"},"getPreviewByFileId"]},{"file":"/snap/nextcloud/28503/htdocs/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Core\\Controller\\PreviewController","getPreviewByFileId",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"core.Preview.getPreviewByFileId"}]},{"file":"/snap/nextcloud/28503/htdocs/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/core/preview"]},{"file":"/snap/nextcloud/28503/htdocs/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/snap/nextcloud/28503/htdocs/3rdparty/doctrine/dbal/src/Driver/PDO/Exception.php","Line":26,"Previous":{"Exception":"PDOException","Message":"SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'configvalue` + 1)` WHERE (`userid` = 'tascloud') AND (`configkey` = 'read') AND ' at line 1","Code":"42000","Trace":[{"file":"/snap/nextcloud/28503/htdocs/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","line":82,"function":"execute","class":"PDOStatement","type":"->","args":[null]},{"file":"/snap/nextcloud/28503/htdocs/3rdparty/doctrine/dbal/src/Connection.php","line":1136,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDO\\Statement","type":"->","args":[]},{"file":"/snap/nextcloud/28503/htdocs/lib/private/DB/Connection.php","line":262,"function":"executeStatement","class":"Doctrine\\DBAL\\Connection","type":"->","args":["UPDATE `oc_preferences` SET `configvalue` = `(`configvalue` + 1)` WHERE (`userid` = ?) AND (`configkey` = ?) AND (`appid` = ?)",["tascloud","read","user_usage_report"],[2,2]]},{"file":"/snap/nextcloud/28503/htdocs/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":213,"function":"executeStatement","class":"OC\\DB\\Connection","type":"->","args":["UPDATE `oc_preferences` SET `configvalue` = `(`configvalue` + 1)` WHERE (`userid` = :user) AND (`configkey` = :action) AND (`appid` = :appid)",{"appid":"user_usage_report","user":"tascloud","action":"read"},{"user":2,"action":2}]},{"file":"/snap/nextcloud/28503/htdocs/lib/private/DB/QueryBuilder/QueryBuilder.php","line":287,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[]},{"file":"/var/snap/nextcloud/28503/nextcloud/extra-apps/user_usage_report/lib/Listener.php","line":82,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"/var/snap/nextcloud/28503/nextcloud/extra-apps/user_usage_report/lib/Listener.php","line":64,"function":"storeAction","class":"OCA\\UserUsageReport\\Listener","type":"->","args":["read"]},{"file":"/var/snap/nextcloud/28503/nextcloud/extra-apps/user_usage_report/lib/AppInfo/Application.php","line":54,"function":"fileRead","class":"OCA\\UserUsageReport\\Listener","type":"->","args":[]},{"file":"/snap/nextcloud/28503/htdocs/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":264,"function":"OCA\\UserUsageReport\\AppInfo\\{closure}","class":"OCA\\UserUsageReport\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/snap/nextcloud/28503/htdocs/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":239,"function":"doDispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[[{"__class__":"Closure"},{"__class__":"Closure"}],"*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/snap/nextcloud/28503/htdocs/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[[{"__class__":"Closure"},{"__class__":"Closure"}],"*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/snap/nextcloud/28503/htdocs/lib/private/EventDispatcher/SymfonyAdapter.php","line":123,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/snap/nextcloud/28503/htdocs/lib/private/Preview/Generator.php","line":105,"function":"dispatch","class":"OC\\EventDispatcher\\SymfonyAdapter","type":"->","args":["*** sensitive parameter replaced ***",{"__class__":"Symfony\\Component\\EventDispatcher\\GenericEvent"}]},{"file":"/snap/nextcloud/28503/htdocs/lib/private/PreviewManager.php","line":189,"function":"getPreview","class":"OC\\Preview\\Generator","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"},1440,900,false,"fill",null]},{"file":"/snap/nextcloud/28503/htdocs/core/Controller/PreviewController.php","line":169,"function":"getPreview","class":"OC\\PreviewManager","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"},1440,900,false,"fill"]},{"file":"/snap/nextcloud/28503/htdocs/core/Controller/PreviewController.php","line":142,"function":"fetchPreview","class":"OC\\Core\\Controller\\PreviewController","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"},1440,900,true,true,"fill"]},{"file":"/snap/nextcloud/28503/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"getPreviewByFileId","class":"OC\\Core\\Controller\\PreviewController","type":"->","args":[5377633,1440,900,true,true,"fill"]},{"file":"/snap/nextcloud/28503/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\PreviewController"},"getPreviewByFileId"]},{"file":"/snap/nextcloud/28503/htdocs/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\PreviewController"},"getPreviewByFileId"]},{"file":"/snap/nextcloud/28503/htdocs/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Core\\Controller\\PreviewController","getPreviewByFileId",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"core.Preview.getPreviewByFileId"}]},{"file":"/snap/nextcloud/28503/htdocs/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/core/preview"]},{"file":"/snap/nextcloud/28503/htdocs/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/snap/nextcloud/28503/htdocs/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","Line":82}},"CustomMessage":"--"},"id":"613fb8b6e3b49"}

**Comment by kyrofa** [comment]
This is a bug in [user_usage_report app](https://github.com/nextcloud/user_usage_report/issues/69), not the snap. You have a few options:

1. Disable the broken user_usage_report app
2. Revert the snap back to v21 (`sudo snap revert nextcloud`) until user_usage_report is fixed
