### ISSUE TITLE
SNAP Update 22.1.1snap1 activates REDIS where no REDIS is installed

### ISSUE THREAD

**Issue by adb336** [nextcloud-snap/nextcloud-snap#1851]
#### Describe the bug
After getting on the 19th of September 2021 multiple error message "internal server error 500" I have checked with

# nextcloud.off integrity:check-core

what the issue might be. The message stated that redis cannot be used, because it is not configured.

True, I have never activated it since SNAP stable 9.0.53snap4.

I have reverted the snap to version SNAP stable 21.0.4snap2.

Service is working again.

#### To Reproduce
1. Update to SNAP stable 22.1.1snap1
2. try to login
3. shoud get you internal server error 500
4. check integrity of core
5. hint on redis issue in the error messages

#### Expected behavior
Login should get you into your dashboard.

#### Screenshots
none

#### OS/snapd/snap version
    $ snap list nextcloud

Name       Version      Rev    Tracking   Publisher   Notes
nextcloud  22.1.1snap1  28503  21/stable  nextcloud✓  disabled
nextcloud  21.0.4snap2  28473  21/stable  nextcloud✓  -

and:

    $ snap version

snap    2.51.4
snapd   2.51.4
series  16
ubuntu  18.04
kernel  4.15.0-156-generic

#### Logs
none

**Comment by Samathy** [comment]
This issue has been affecting me for a week or so too.
The symptoms here are similar to those in #1852. Perhaps related.

I have managed to revert to the snap revision suggested in #1851, `21.0.04snap2` which seems to make Nextcloud work again, suggesting that I do have the same issue as listed here.
snap refreshes Nextcloud up to v22 and the symptoms come back.

I havent managed to run `integrity:check-core` so I can't confirm having the redis errors show up or not.

**Comment by kyrofa** [comment]
Can you please paste the output of [this script](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Issue-Debugging-Scripts)?

**Comment by Samathy** [comment]
When Snap autoupgrades my Nextcloud install back to v22, I'll run the script. For now it is working fine on version 21.

**Comment by adb336** [comment]
Please find attached what the script is documenting.


[doc_20210925.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/7230414/doc_20210925.txt)

Be aware that in the process of incident management I also had to return to 21.0.4snap2 (28473) by using command
...
snap refresh nextcloud --channel=21/stable --classic
...

Kind regards.

**Comment by adb336** [comment]
From what I can see the snap 21.0.4snap2 (28473) is running stable since. All DAV clients and NC users have no complains so far.

Kind regards.
