### ISSUE TITLE
Installing nextcloud as PWA

### ISSUE THREAD

**Issue by negativesymptomatic** [nextcloud-snap/nextcloud-snap#1855]
#### Describe the bug
Before Nextcloud 22 i was asked to install in my chrome the PWA, but now i a new computer i can't install the app

#### Expected behavior
I expect that i'm prompted to install the web app when i'm in chrome

#### OS/snapd/snap version
snap -v: the last deployed

client os: mac os, with chrome

**Comment by kyrofa** [comment]
I'm afraid I know nothing about chrome's PWAs, but if the web app can effect this I believe it's an upstream Nextcloud issue. Please log it there.
