### ISSUE TITLE
Browser photo previews stop working after update to latest snap 21.1.1snap2

### ISSUE THREAD

**Issue by alexfalli** [nextcloud-snap/nextcloud-snap#1873]
#### Describe the bug
After updating to 21.1.1snap2, photo previews no longer work in the browser. (Tested with chrome, Firefox, and New Edge)

#### To Reproduce
1. Go to any photo that you have in your cloud
2. Click on the photo to open the browser view of the photo
3. See error

#### Expected behavior
It should not give an error. Snap 21.0.4snap2 was working fine.

#### Screenshots
![image](https://user-images.githubusercontent.com/67812243/135764642-2251d4e0-4f3b-4040-bf73-756740340918.png)

#### OS/snapd/snap version

Running nextcloud snap 21.1.1snap2 on Ubuntu 20.04.3 LTS vCPU, 12GB RAM

    $ snap list nextcloud
```
nyls@cloud:~$ snap list nextcloud 
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  22.1.1snap2  28549  latest/stable  nextcloud✓  -
```

and:

    $ snap version

```
nyls@cloud:~$ snap version 
snap    2.51.7
snapd   2.51.7
series  16
ubuntu  20.04
kernel  5.4.0-88-generic
```

#### Logs

[nextcloud debug  script output.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/7274228/nextcloud.debug.script.output.txt)
.

**Comment by ASmith-** [comment]
Looks like what I described earlier here https://github.com/nextcloud-snap/nextcloud-snap/issues/1840

**Comment by alexfalli** [comment]
Yes It seems like. I disabled the usage report and it seems to be working again.
