### ISSUE TITLE
Fix mysql performance_schema-related memory consumption for latest/stable

### ISSUE THREAD

**Issue by r4co0n** [nextcloud-snap/nextcloud-snap#1874]
@pachulo has provided the patch #1842, resulting in:
  
   * #1842 -> Merged to branch `devel`
   * #1858 -> Backport merged to branch `20`
   * #1859 -> Backport merged to branch `21`
 
This leaves branch `master`, which I think produces `latest/stable` a.k.a. 22.1.1snap2 unpatched regarding the (unfortunately apparently unraised) issue fixed in the aforementioned PRs for the other stable channels.

My 1GB RAM cloud instance just explodes with MySQL consuming all the available memory, right on first request after restart, I have been running the snap this way without problems for quite some years now. (If you want to recover without restart, send `kill -9` (normal kill didn't work for me) to mysqld's PID, to be able to have the necessary memory to run `snap stop nextcloud`.

That's some really annoying Oracle stunt that needs to be fixed in `latest/stable` as well, I think the relevant commit can be easily cherry-picked.

**Comment by kyrofa** [comment]
Yeah it's queued up, I'm just trying to land #1774 with a few tweaks before release. Hang tight.
