### ISSUE TITLE
Files app no longer shows any files after latest upgrade

### ISSUE THREAD

**Issue by bgcarlisle** [nextcloud-snap/nextcloud-snap#1900]
#### Describe the bug
After the latest update, the files app does not show any files. There doesn't seem to be data loss, as I can see the files there still on my iOS app, but I can't easily get to them through my desktop

It's giving me this error in the browser console

> Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).

#### To Reproduce
1. Open files in any browser
2. There's no files

#### Expected behavior
I expect to see the files

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud

Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  22.2.0snap2  28592  latest/stable  nextcloud✓  -

and:

    $ snap version

snap    2.52
snapd   2.52
series  16
ubuntu  20.10
kernel  5.8.0-1032-raspi

**Comment by ASmith-** [comment]
Perhaps the advise I was given when all of my Nextcloud's image files provided errors and wouldn't show properly would help. That happened immediately following a Nextcloud snap update.

https://github.com/nextcloud-snap/nextcloud-snap/issues/1840#issuecomment-918579769

> This is a bug in [user_usage_report app](https://github.com/nextcloud/user_usage_report/issues/69), not the snap. You have a few options:
> 
> 1. Disable the broken user_usage_report app
> 2. Revert the snap back to v21 (`sudo snap revert nextcloud`) until user_usage_report is fixed
