### ISSUE TITLE
Nextcloud down yet again.

### ISSUE THREAD

**Issue by ASmith-** [nextcloud-snap/nextcloud-snap#1904]
#### Describe the bug
Fails to connect remotely. Nextcloud connects and operates correctly locally with a browser on a workstation fed by LAN back to my Nextcloud server. However I cannot connect to it via its domain link, its error 522 timed out. I see snap updated my nextcloud 5 days earlier, its very likely that caused this but not sure. 

I tried snap revert nextcloud reverting back to 22.2.0snap1. Following this latest revert in the past 2 weeks here, I still have this server error 522 timing out. It seems like that snap nextcloud (22.2.0snap1) had a issue that made all of the users stored images unable to be shown. Can the revert command be issued back to back? IE Can I issue another revert command on my Nextcloud to further roll back nextcloud to see if that clears up this issue?

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud
nextcloud 22.2.0snap2 Rev 28586 latest/stable nextcloud

and:

    $ snap version
snap 2.52
snapd 2.52
series 16
linuxmint 19.2
kernel 4.15.0-96-generic

#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).

Log indicates a series of Core errors but not enough information as a breadcrumb or clue as to its cause. Was there another update pushed out that caused this latest instability?

[core] Error: Error while running background job (class: OCA\GroupFolders\BackgroundJob\ExpireGroupVersions, arguments: )

at 2021-10-12T03:00:56+00:00

  | Error | core | TypeError: Unsupported operand types: int & array

{"reqId":"VcbJXv5w738u5lFix3Ey","level":3,"time":"2021-10-12T03:00:56+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Error while running background job (class: OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions, arguments: )","userAgent":"--","version":"22.2.0.2","exception":{"Exception":"TypeError","Message":"Unsupported operand types: int & array","Code":0,"Trace":[{"file":"/snap/nextcloud/28586/htdocs/lib/private/Files/Cache/Wrapper/CacheWrapper.php","line":78,"function":"formatCacheEntry","class":"OC\\Files\\Cache\\Wrapper\\CachePermissionsMask","type":"->"},{"file":"/var/snap/nextcloud/28586/nextcloud/extra-apps/groupfolders/lib/Versions/VersionsBackend.php","line":170,"function":"get","class":"OC\\Files\\Cache\\Wrapper\\CacheWrapper","type":"->"},{"function":"OCA\\GroupFolders\\Versions\\{closure}","class":"OCA\\GroupFolders\\Versions\\VersionsBackend","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/snap/nextcloud/28586/nextcloud/extra-apps/groupfolders/lib/Versions/VersionsBackend.php","line":169,"function":"array_map"},{"file":"/var/snap/nextcloud/28586/nextcloud/extra-apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php","line":63,"function":"getAllVersionedFiles","class":"OCA\\GroupFolders\\Versions\\VersionsBackend","type":"->"},{"file":"/var/snap/nextcloud/28586/nextcloud/extra-apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php","line":57,"function":"expireFolder","class":"OCA\\GroupFolders\\Versions\\GroupVersionsExpireManager","type":"->"},{"file":"/var/snap/nextcloud/28586/nextcloud/extra-apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php","line":39,"function":"expireAll","class":"OCA\\GroupFolders\\Versions\\GroupVersionsExpireManager","type":"->"},{"file":"/snap/nextcloud/28586/htdocs/lib/private/BackgroundJob/Job.php","line":51,"function":"run","class":"OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions","type":"->"},{"file":"/snap/nextcloud/28586/htdocs/lib/private/BackgroundJob/TimedJob.php","line":58,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->"},{"file":"/snap/nextcloud/28586/htdocs/cron.php","line":127,"function":"execute","class":"OC\\BackgroundJob\\TimedJob","type":"->"}],"File":"/snap/nextcloud/28586/htdocs/lib/private/Files/Cache/Wrapper/CachePermissionsMask.php","Line":43,"CustomMessage":"Error while running background job (class: OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions, arguments: )"},"id":"6167c622bee17"}

**Comment by r4co0n** [comment]
These lines look to me as if there is something awry with snapd itself:
```
Jun 23 12:27:05 server nextcloud.nextcloud-cron[30749]: error: cannot communicate with server: Post http://localhost/v2/snapctl: dial unix /run/snapd-snap.socket: connect: connection refused
```

There seems to be a problem for the nextcloud database abstraction layer, which fails with `No such file or directory` on connection to your MySQL database:
```
Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directory in /snap/nextcloud/28586/htdocs/lib/private/DB/Connection.php:87
```
(and following stack trace)

**Comment by ASmith-** [comment]
Logging a error on group folders
[core] Warning: normalizing failed for "__groupfolders/1/Metal_Singles/Music_Name.mp3"
at 2021-10-14T20:42:51+00:00

{"reqId":"Xtb1ntcRPjTyrAfEWUKr","level":2,"time":"2021-10-14T20:42:51+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"normalizing failed for \"__groupfolders/1/Metal_Singles/Music_Name.mp3\"","userAgent":"--","version":"22.2.0.2","id":"616b1d0782716"}

Looks like I need to remove the group folders plugin, shame.

Every hour log entries of [core] Error: Error while running background job (class: OCA\GroupFolders\BackgroundJob\ExpireGroupVersions, arguments: ) at 2021-10-16T07:21:03+00:00

I rolled back the snap Nextcloud, doubly made sure the needed ports were being forwarded on the router, placing my nextcloud back online, leaving me to likely pull the plug on the useful group folders plugin.
