### ISSUE TITLE
Use openssl output in nextcloud.enable-https custom

### ISSUE THREAD

**Issue by ZER0-X** [nextcloud-snap/nextcloud-snap#1905]
I have a local server with nextcloud-snap in it and I use some nextcloud apps in my iphone but some of them are not working because of [Apple's requirements for an SSL certificate](https://support.apple.com/en-us/HT210176), which does not apply to the self-signed certificate that nextcloud makes. I need to have a self-signed certificate that my device can trusts so that apps can access my nextcloud server. I can't use a service like letsencrypt because my server can't be accessed from the internet. So I used [this](https://bob.gatsmas.de/caldav-sync-erinnerungen-app-ios-13-und-macos-1015) tutorial to make a certificate myself with `openssl`, it gives me a lot of files and I don't know witch is `cert`, `key` and `chain`

Those are the files/folders that I got:
- cacert.pem 
- crl
- index.txt.attr
- openssl-ca.cnf
- serial
- serverkey.pem
- cakey.pem
- crlnumber
- index.txt.old
- openssl-server.cnf
- servercert.csr
- certs
- index.txt
- newcerts
- servercert.pem

The command i need to use:

> $ sudo snap run nextcloud.enable-https custom `<cert>` `<key>` `<chain>`

I've thought of using `servercert.pem` as `cert` and `serverkey.pem` as `key` but i don't know what is `chain`. Is there anyone who is an expert on `openssl` can help with figuring out the required files?

Also, I would like to ask the project maintainers to take this into consideration and configure the self-signed certificate maded by `nextcloud.enable-https self-signed` to be compatible with Apple requirements.

**Comment by r4co0n** [comment]
If you want to explore your new Certificate Authority further, I can highly recommend https://jamielinux.com/docs/openssl-certificate-authority/ .

You might want to close this issue, as your specific problem is resolved. I will open two others referring what we found to keep the tide rising.
