### ISSUE TITLE
Performance issue -> What is recommended system requirements (CPU)?

### ISSUE THREAD

**Issue by NaXal** [nextcloud-snap/nextcloud-snap#1922]
Hello,

I am running a personal (web) backup server at home with NextCloud. My users (friends and family) use Mobile apps to backup images and videos of their phone / Digital camera (via web interface) into this system. This is like a Google Photos self hosted alternative to us.

Things are running theoretically fine but I am really disappointed with the actual performance of this setup.

Following is the setup I am running,

1. Ubuntu 20.04 LTS Clean installation (apt update / apt upgrade performed before nextcloud installation)
2. Snap NextCloud latest version installed
3. Let's Encrypt SSL with my Key and Cert files via https custom install command
4. System Configuration (Acer Laptop -> Intel Pentium Quad Core N3530 @ 2.16GHz / (2x2) 4GB RAM / Gigabit Wired Ethernet connection / Single 2TB 5400RPM HDD)
5. NOIP Ubuntu Linux Client to update my domain DNS since I don't get static IP

Everything in this setup is working fine but I am seeing really high CPU Usage. One user uploading or downloading isn't causing any major issue but when there are multiple users, the performance is dead slow.

Below screen shot is when 3 users are accessing (transferring data) simultaneously. 2 are mobile uploading and I am downgliding via web interface

![001](https://user-images.githubusercontent.com/91847371/139535388-3f5b0821-f4fe-4384-aad5-89cd8ebf69ee.jpeg)

Looking at the CPU usage, I wonder why such high usage. Is it normal?

Thanks.

**Comment by kyrofa** [comment]
You'll always get better performance using clients instead of the web interface. Check [this thread](https://help.nextcloud.com/t/after-upgrade-to-20-php-fpm-causes-high-cpu-load/107878) out. Unbearably high loads are generally cause by misbehaving apps, in my experience.

**Comment by NaXal** [comment]
Hello,

Thanks for the reply.

I am sorry if I have failed to make it clear in my first post, its not about web interface only.

This same high CPU usage is happening even when all users are on their respective software clients (android / iOS) and no web log-in at all.

I have gone through the thread on php issue but here with my installation,

Firstly its a dedicated system. I have nothing else running apart from what I wrote in my original post. Just to be clear,

1. Ubuntu Server 20.04 Minimum Install (Clean installation) with apt update / upgrade
2. NextCloud Snap Installation as per the information given here (Few simple commands)
3. NOIP client for Ubuntu 20 for Dynamic DNS update.

Even the NextCloud itself has no extra plug-in (Collabora or such) apart from what is included by default.

Secondly, with snap installation, I didn't have any options for any configuration changes for Apache / php or MySQL. So I am sure I haven't messed up anything with those. It is just at it is with default installation values.

People are happily running NextCloud over their Pi and here my Quad Core CPU is struggling :( 

What am I missing here?

**Comment by r4co0n** [comment]
@NaXal, thanks for the additional information, would you mind telling us what kind of system you are running Nextcloud on? It seems you have ~4G available RAM, how many CPU cores are available, how many users are on your instance, how many are (usually) using this service simulaneously?

Nextcloud users being variant, I am also interested in the usage pattern that provokes this behaviour, or simply speaking, what your users are usually doing with Nextcloud and how much of it.

**Comment by NaXal** [comment]
Hello,

Thanks for the reply.

I believe along with the screenshot of putty running htop, I have also written my setup information in my first post. In case there is any miscommunication from my part, below is my setup,

**Hardware**
1. Dedicated physical system, Not a VM.
2. Acer Laptop -> Intel Pentium Quad Core N3530 @ 2.16GHz / (2x2) 4GB DDR3 RAM / 2TB 5400 HDD / Gigabit wired Ethernet

**Software**

1. Clean installation of Ubuntu 20.04 LTS Server edition minimum installation (with apt update and upgrade done)
2. Snap NextCloud installation (as instructed here with the commands) -> Default installation, no extra plug-in or any modification
3. installed my Let's encrypt SSL via the custom SSL installation command as given here
4. NOIP Ubuntu Client to update my DNS (since I don't have static IP at home)

**Network Info**

1. My Internet Router is configured to forward Port 80 and 443 to the NAT IP of this Acer Laptop
2. My TLD is having a sub domain -> NoIP DDNS setup for the host name to access NextCloud

**how many CPU cores are available**

Since its a dedicated physical installation, the entire CPU (all 4 cores) is available for the system to use I guess. I haven't done anything extra in OS level apart from what I wrote above to change anything of a default Ubuntu Server installation.

**how many users are on your instance, how many are (usually) using this service simulaneously?**

This setup is suppose to have around 10/12 users with atleast 20 devices (android / iOS clients) since some users will have multiple devices. Plan is to use it as alternative to Google Photos as our self hosted Photos and Videos (phones / digital cameras) backup server, 

However, at present I have only 4 users for testing purposes and at max 3 (devices or users, rather login instant) is able to use (active upload / download) it. Forth connection pushes the CPU beyond its capacity and all users starts to experience issues.

**Nextcloud users being variant, I am also interested in the usage pattern that provokes this behaviour, or simply speaking, what your users are usually doing with Nextcloud and how much of it.**

As I wrote before, the plan is to use it as Google Photos alternative. NextCloud android or iOS app will upload what ever pictures are taken on their respective devices and when ever some uses their digital camera, those footages and images will be backed up via web interface, All users will have their respective collection always available online to free up the their device.

Frankly speaking, once the setup goes live and initial pressure of first (backup) upload is done, I guess even with 12 users 20 devices, chance of multiple simultaneous heavy usage connections are low. As you may imagine by looking at the planned use case. However, there will be few of those occasions where people may access and do heavy usage.

**What is Provoking**

2 Users are uploading and 1 is downloading -> That's the HTOP screenshot I have given. Regardless, whether this upload / download is done via NextCloud Android app or via web interface, CPU usage is shooting such high up.

I fail to understand how others on internet are using same installation process as mine with their lowest end CPU like a RashBerryPi can run smoothly yet in my case, a vastly superior CPU is struggling with just 3/4 concurrent connection.

What am I doing wrong here with my setup?

Thanks.

**Comment by negativesymptomatic** [comment]
Hi @NaXal the cpu is not that good as you think, it's very old and i think that probably a rpi 4 has more performance that this notebook.

The main reason could be temps, check out the temps of the notebook, it could be that it throttles the performance under load because temps raises.

Second thing: it could also be the HDD poor performance, maybe the cpu is not slow on loading things, but it has to wait the I/O of the hdd.

Could you run this script in the bash and paste here the results?
This can be show us the real laptop performance!

sudo apt-get install sysbench
sysbench --test=cpu --cpu-max-prime=20000 run

For examples: here is a dual core overselled VPS with some docker in background

CPU speed:
    events per second:   295.24

General statistics:
    total time:                          10.0031s
    total number of events:              2954

Latency (ms):
         min:                                    3.09
         avg:                                    3.37
         max:                                   22.36
         95th percentile:                        3.89
         sum:                                 9968.18

Threads fairness:
    events (avg/stddev):           2954.0000/0.00
    execution time (avg/stddev):   9.9682/0.00

**Comment by NaXal** [comment]
> Hi @NaXal the cpu is not that good as you think, it's very old and i think that probably a rpi 4 has more performance that this notebook.
> 
> The main reason could be temps, check out the temps of the notebook, it could be that it throttles the performance under load because temps raises.

Hello,

Thanks for the reply.

I don't have any Pi with me so I can't pit it head to head but after your reply, I did some searching in bench marking websites and you are somewhat right atleast as per the bench marking websites. Intel Pentium Quad Core N3530 is marginally better / ahead of Cortex-A72 (ARM v8) 1.5Ghz.

So I guess am certainly wrong in the assumption of it (Intel P N3530) being vastly superior over Pi but atleast as per the online information, N3530 isn't inferior to Pi.

**Coming to your second question about Thermals,**

Its an Acer Laptop and I was running Windows on it before making it dedicated to this server project. The device has active (fan) cooling and if you check docs of Intel Pentium Quad Core N3530, its a really power efficient processor. I am monitoring the temps and even with high load, I don't see its throttling (thermal) down since temps barely go over low 50s (highest being 53).

**last of all the bench marking results as requested,**

![Screenshot from 2021-11-04 20-21-52](https://user-images.githubusercontent.com/91847371/140339281-4870feff-c316-4a49-ad9b-63771835088a.png)

Above is the result as generated by the system in question.

One thing I understand, being scalable software, it may use more and more system resources as load (user count or task performed). However what is disappointing is the system requirement page of NextCloud. It has no mention about CPU requirements or recommendations. At least that may give any potential users idea on hardware choice.

Thanks.

**Comment by negativesymptomatic** [comment]
I think that Nextcloud team could help you to better understand the min specs for the installation, here we can talk about the snap.

From my experience with nextcloud, the specs depends on what you use and on the cpu performance per core, in fact the n3530 you are using misses a lot of cpu extensions that newer cpu's have. I know that Xeons are another grade CPU, but my main installation of nextcloud works in a 2vcore VPS and it has Talk, Deck, Calendar and other stuff with 6 user and about 12 devices connected (2 per user), and I don't have any problem with that, obv sometimes when all 6 user are doing something it caps the cpu, but only for seconds.

**Comment by NaXal** [comment]
> I think that Nextcloud team could help you to better understand the min specs for the installation, here we can talk about the snap.
> 

Hello,

Thanks for your reply.

I guess that sums it up. This issue may be closed now since its not within the boundaries of this issue tracker.

Yes, snap application is working as intended. It's the performance (namely CPU) which is the issue for me.

As you have directed, I shall try to get an response from NextCloud Devs but I guess that may be easier said than done. I already have an open issue in NextCloud forums with same question and information (post) as this. Link -> https://help.nextcloud.com/t/high-cpu-usage-nextcloud-22-2-0-snap-on-ubuntu-20-lts/126496 However, I am yet to receive a single reply.

**In case anyone ends up reading this thread,** 

NextCloud system requirement page (Link -> https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html ) is half informed & under played. Unlike specific RAM requirements, there are no details given on CPU and rely on platform specifications (like Ubuntu OS). However, in reality, one should consider at least Intel 3rd Gen i3 or above when deploying for multiple simultaneous users.

NextCloud as an app feels really CPU performance hungry where as RAM usage are generally low, 2GB should be sufficient as per my experience.

I am somewhat stuck since didn't experience any issues while testing (single user in test environment) and got somewhat mislead with the system requirement documentation. Didn't assume my choice of CPU might turned out to be underpowered. Went ahead with deployment and took the server live.

Users have already done the time consuming processor setting things up and get the entire backup done, so I don't have the liberty to re-setup the entire thing with a different hardware (CPU).

Anyway, at least things are working, albeit slower / issue prone when simultaneous multiple active users/devices performing large upload / downloads. I guess I have live with it for the time being.

Thanks for reading and thanks to all of you, who have taken their time off to reply.

**Comment by r4co0n** [comment]
@NaXal, thanks for following up on this issue until its (unsatisfactory) resolution.
