### ISSUE TITLE
Expose apache listen address in addition to listen port

### ISSUE THREAD

**Issue by sam-11100** [nextcloud-snap/nextcloud-snap#1934]
First of all I want to use the opportunity to thank the developers for this awesome repo!
When running it under a certain address (e.g. "nextcloud.example.com") while other addresses pointing to the same server the developers recommend the usage of a reverse proxy (https://github.com/nextcloud-snap/nextcloud-snap/wiki/Putting-the-snap-behind-a-reverse-proxy). I tried the solution with the HAProxy and it works very well.
However, there are a few difficulties, for instance when explicitly requesting the http website, one is redirected to the port 444, instead of 443. Probably, the access of the reverse proxy through port 80 to port 81 of the server is redirected by the snap to its https port, which is 444. The direct https access is correctly forwarded to 443.
Also the service discovery (https://docs.nextcloud.com/server/22/admin_manual/issues/general_troubleshooting.html#service-discovery) does not work properly, since the address "https://example.com/.well-known/caldav" is forwarded to port 444.
Furthermore, the brute force protection gets a bit confused, since every access is through 127.0.0.1. This also makes the log files a bit useless, since every access is through the home address. I noticed other users also had troubles with this by reading through the issues in this repo.
Reading a bit through the apache documentation I figured out the client can not only be set up to listen to a specific port by modification of the "httpd.conf" file, but also to a specific address. However, the apache config file is part of the non writeable squashfs. Recompiling the repo is a bit tedious, but maybe it would be possible to expose the listen address in addition to the ports, e.g. through the CLI or the conf.php?
Thanks for your reply in advance!

**Comment by r4co0n** [comment]
We recently had a discussion tackling the reverse proxy log and brute force protection bit: #1610 - Long story short, look at nextcloud config setting `trusted_proxies` and configure it appropriately. This will not help with the useless log files. We are tunneling HTTPS traffic through HAProxy, which means it cannot add `X-Forwareded-For` (or any other) HTTP header to the traffic to indicate the origin to Nextcloud. If you want this to work properly, I think you should look at doing TLS termination at your proxy and then pass plain HTTP (or reencrypt against a [self-signed] certificate) towards the Nextcloud backend. This means setting up a tool to automatically renew LetsEncrypt certificates on your host and providing those to HAProxy - There are many good tools and guides out there to achieve this.

As for your http->https redirects, just make HAProxy do those for you, so they never hit your nextcloud box. (Add the `http-request redirect scheme` line mentioned in [this HAProxy blog entry](http-request redirect scheme https) to your http frontend.) When doing this, you might want to exclude paths under `http://nextcloud.example.com/.well-known/acme-challenge/` from this redirect - Nah, it seems you will be fine, even when your current certificate is expired/invalid, see [Letsencrypt docs](https://letsencrypt.org/docs/challenge-types/#http-01-challenge).

For bootstrapping with this configuration, you would need to first generate a self-signed certificate (for https to work at all) and then switch to letsencrypt.

I hope this helps and will also fix your caldav service discovery.

**Comment by sam-11100** [comment]
Thanks for the quick reply!
I think the "trusted_proxies" solution will do the job, introducing another certificate might be not worth the effort.
The solution with the redirect worked quite well, the http request is redirected correctly (even though the ".well-known" addresses are still not redirected properly, but I guess that does not matter so much).
I will have to wait until the current certificate gets invalid to see, if a new certificate can be issued this way, but I think this should be a minor problem.

**Comment by sam-11100** [comment]
By chance I found a solution for the redirects of the CalDAV and CardDAV when running the nextcloud behind a reverse proxy in the documentation of nextcloud.
Depending on the tool used one can just instruct the redirection upon url discovery:
https://docs.nextcloud.com/server/23/admin_manual/configuration_server/reverse_proxy_configuration.html#haproxy

I just thought maybe you guys want to update your documentation :). Thanks again for your help!
