### ISSUE TITLE
PHP Memory Limit and Front-End Performance

### ISSUE THREAD

**Issue by LoganHub1** [nextcloud-snap/nextcloud-snap#1935]
Hello,

I have Nextcloud deployed on a home server and am looking for ways to increase the overall performance of the web front-end from WAN (not within the home).  Overall, it's pretty fast, however, sometimes when loading pages for the first time in a while, it takes over 30 seconds to complete the page load.  While looking through the readme file, I see that under the 'PHP Memory Limit Configuration' section [(here)](https://github.com/nextcloud-snap/nextcloud-snap#php-memory-limit-configuration)  it is listed as 'not recommended' to give PHP an unlimited memory limit.  **Is there a reason that it is not recommended?**  I figured that giving PHP a higher memory limit would be an easy way to increase the performance (and if not, it could only help in general).  My Nextcloud installation has up to 32GB of RAM to use, so I have plenty to spare.  Would love to hear some suggestions and get some clarification on the unlimited memory limit.  Thanks in advance!

**Comment by kyrofa** [comment]
> Is there a reason that it is not recommended?

Because it turns it into a DoS opportunity for your entire server. You don't want a server that has no RAM available. More practically speaking, Nextcloud has a lot of apps available that are written by people with varying skill levels. I'm sure some of them would happily claim a lot more RAM than they should.

I recommend starting by simply increasing this value if you have some RAM to play with. See if you can get better performance out of it without just taking the lid off entirely.

**Comment by LoganHub1** [comment]
@kyrofa Sounds good, and thanks for reaching out.  Perhaps of note is that I actually have the Nextcloud server deployed in a VM within Windows Server 2019 Standard, so completely eating the system resources away, or a DoS attack would be less of a concern here (the server has 64GB RAM and I have up to 32GB dynamically allocated for it in Hyper-V).  My last question about this would be, is it possible to assign any value to the configuration?  For example could I run the command `sudo snap set nextcloud php.memory-limit=4096M` or `sudo snap set nextcloud php.memory-limit=16384M` for 4GB or 16GB respectively?  Or is that configuration command locked to only certain values?  Thanks again for your time!

**Comment by kyrofa** [comment]
> Perhaps of note is that I actually have the Nextcloud server deployed in a VM within Windows Server 2019 Standard, so completely eating the system resources away, or a DoS attack would be less of a concern here

External control over the RAM allocation is definitely a mitigating factor.

> My last question about this would be, is it possible to assign any value to the configuration?

Yes, I believe both of your examples are valid. What you set here is passed straight to the PHP configuration, so [more details can be found there](https://www.php.net/manual/en/ini.core.php#ini.memory-limit).

**Comment by LoganHub1** [comment]
Thanks so much for the help!  I'll make that change and see if it helps over time.  I usually test to see WAN performance by doing a fresh page load (CTRL + F5).  I'll do that whilst check the network tab on the console of the web browser.  Most of the time I'm seeing the javascripts take the longest to load by far (see attached image).  If anyone has had any experience with speeding up the javascripts, feel free to post suggestions.

![nextcloud page load](https://user-images.githubusercontent.com/26229136/142029073-bcc27cf5-3c1a-4a4e-9d5f-fcd23a1737d4.png)
