### ISSUE TITLE
Cannot login through Nextcloud-Desktop using Nginx Reverse Proxy

### ISSUE THREAD

**Issue by Baa14453** [nextcloud-snap/nextcloud-snap#1946]
#### Describe the bug
An extra configuration is required to prevent Mixed Content errors when using an NGINX reverse proxy for SSL with the Snap. 

#### To Reproduce
1. Install Nextcloud-snap
2. Configure an NGNIX reverse-proxy for your frontend and enable SSL through the proxy.
3. Try to add your account through nextcloud-desktop.

#### Expected behaviour
The account will be added.

#### Actual behaviour
The login webpage that the nextcloud app launches is unable to access `/index.php/login/v2/grant` because it has been loaded through HTTP and your Content Security Policy is blocking access to mixed content.
In the web console this error will show:
`Content Security Policy: The page's settings blocked the loading of a resource at http://<Nextcloud URL>/index.php/login/v2/grant ("form-action").`

#### OS/snapd/snap version
    $ snap list nextcloud
```
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  22.2.3snap1  28654  latest/stable  nextcloud✓  -
```

    $ snap version
```
snap    2.52.1
snapd   2.52.1
series  16
ubuntu  20.04
kernel  5.4.0-81-generic
```
OS:
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```

#### NGINX Configuration
This is my Reverse Proxy setup:
```nginx
#Catch all HTTPS subdomains and redirect to <Nextcloud URL>
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name *.<Nextcloud URL>;
    return 301 https://<Nextcloud URL>$request_uri;
}

#Catch all HTTP requests and redirect to HTTPS
server {
        listen 80;
        listen [::]:80;

        server_name <Nextcloud URL> *.<Nextcloud URL>;
        return 301 https://<Nextcloud URL>$request_uri;
}

server {

    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    include /etc/nginx/snippets/ssl-nextcloud-url.conf;
    include /etc/nginx/snippets/ssl-params.conf;

    server_name <Nextcloud URL>;

    ### SSL CONFIGURATION ###
    #location /.well-known/ {
    #        default_type "text/plain";
    #        allow all;
    #        root /var/www/html/;
    #}

    location / {
        proxy_pass http://localhost:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 600;
        proxy_send_timeout 600;
        proxy_read_timeout 600;
        client_max_body_size 100000m;
    }

    location = /.well-known/carddav {
        return 301 $scheme://$host/remote.php/dav;
    }

    location = /.well-known/caldav {
        return 301 $scheme://$host/remote.php/dav;
    }

    location ~ /\.git {
        deny all;
    }

    location .gitignore {
        deny all;
    }

    location = /robots.txt {
         add_header Content-Type text/plain;
         return 200 "User-agent: *\nDisallow: /\n";
    }

}
```

Content of SSL-Params that is linked in:
```nignx
ssl_session_cache shared:MozSSL:10m;
ssl_session_timeout  10m;
ssl_session_tickets off;

# Modern configuration
ssl_protocols TLSv1.3;
ssl_prefer_server_ciphers on;
ssl_dhparam /etc/ssl/certs/dhparam.pem; # openssl dhparam -out /etc/nginx/dhparam.pem 4096
#ssl_ciphers EECDH+AESGCM:EDH+AESGCM;
#ssl_ecdh_curve secp384r1;

# OCSP stapling
ssl_stapling on; # Requires nginx >= 1.3.7
ssl_stapling_verify on; # Requires nginx => 1.3.7

# DNs Resolver
resolver 172.104.237.57 172.104.49.100 valid=300s;
resolver_timeout 5s; 

# Extra headers
add_header X-Frame-Options DENY;
add_header X-Content-Type-Options nosniff;
add_header X-XSS-Protection "1; mode=block";
```

#### Resolution
I resolved this based on this guide: https://help.nextcloud.com/t/fixing-mixed-content-errors-when-using-a-proxy/13571
Setting:
```
'overwrite.cli.url' => 'https://cloud.myserver.com',
'overwriteprotocol' => 'https',
```
Changes the behaviour so that the login pages are returned as HTTPS which resolves the mixed content issues.
Because I can't access config.php through the Snap, I instead ran these commands:

```
sudo nextcloud.occ config:system:set overwrite.cli.url --value "https://<Nextcloud URL>"
sudo nextcloud.occ config:system:set overwriteprotocol --value "https"
```

This step might be worth adding to the setup guide or exposing a snap set command for

**Comment by kyrofa** [comment]
> Because I can't access config.php through the Snap

Sure you can, it's in `/var/snap/nextcloud/current/nextcloud/config`, I believe. But using `occ` works just as well. I'm glad you got it working!

> This step might be worth adding to the setup guide [...]

I assume you're talking about [this wiki entry](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Putting-the-snap-behind-a-reverse-proxy)? It specifically includes this paragraph:

> NGINX is a little more difficult to setup as it wants badly to terminate SSL connections for you. If that works for you, great-- have the proxy machine handle the SSL stuff, and just leave the snap with HTTPS disabled. There are all sorts of docs out there for that, so I won't document it here.

What you're doing is well out of the scope of the snap. You're in all nginx/nextcloud territory, and is (as you found) documented elsewhere.
