### ISSUE TITLE
Unauthorized domain error

### ISSUE THREAD

**Issue by Drummond-Dev** [nextcloud-snap/nextcloud-snap#1954]
The certificate for the installation I made of Nexcloud has expired today. 
And when I run the command to reactivate the certificate, it gives an unauthorized domain error.

`sudo nextcloud.enable-https lets-encrypt`

Error:

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: mydomain.com
   Type:   unauthorized
   Detail: Invalid response from
   http://mydomain.com/.well-known/acme-challenge/R4SqIE3vVduvw384VGFj8l-x1WYom7aDw1He-Jqmap4
   [My IP]: "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML
   2.0//EN\">
<html><head>
<title>404 Not
   Found</title>
</head><body>
<h1>Not Found</h1>
<p"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.

How can I get around this problem?

**Comment by kyrofa** [comment]
That indicates that something has changed with your domain situation. Any chance your IP address changed and the domain in question is no longer actually pointing at Nextcloud?

**Comment by Drummond-Dev** [comment]
Hi @kyrofa 

There was no change, everything remains configured the same way it was before the certificate expired.

**Comment by Drummond-Dev** [comment]
I even tested routes for the domain and had no error in DNS A

**Comment by Drummond-Dev** [comment]
I did a DNS check and got this result

![chart](https://user-images.githubusercontent.com/60481837/145102369-ddb04b1d-657d-401d-a769-f713f1f442a9.jpeg)
