### ISSUE TITLE
Enable HTTP/2

### ISSUE THREAD

**Issue by sachingupta010** [nextcloud-snap/nextcloud-snap#1960]
This is the same request as in #298. Is there still reason to not enable this yet? The security issues identified are for a mixed http2 to client and http1 to the backend which shouldn’t be an issue here.

**Comment by ph00lt0** [comment]
https://github.com/nextcloud-snap/nextcloud-snap/issues/298#issuecomment-894100762

**Comment by ph00lt0** [comment]
And why open a new issue?

**Comment by sachingupta010** [comment]
#298 was closed. Apologies if I should have just opened that again instead of opening a new one.

**Comment by kyrofa** [comment]
Oh no problem, let's re-open #298. Triaged issues shouldn't get stale-- I've fixed that now.
