### ISSUE TITLE
not able to upload and set a profile pic for a contact (snap install)

### ISSUE THREAD

**Issue by kajdo** [nextcloud-snap/nextcloud-snap#1968]
#### Describe the bug
I want to upload an image as avatar for a contact which has no image. I get the file chose dialog (tried to upload a photo), chose a file - confirm. No error shows up but the image isn't set as profile pic for the contact.

I tried to upload the image into my "nextcloud files" and see if it works, when using an already uploaded image. Same behaviour -> image chosen, confirmed -> no error shows up - image not set.

#### To Reproduce
1. Go to 'contacts'
2. Click on 'contact without profile pic'
3. Click on image icon to upload a profile pic
4. chose image 
5. image not set as profile image

#### Expected behavior
1. Go to 'contacts'
2. Click on 'contact without profile pic'
3. Click on image icon to upload a profile pic
4. chose image 
5. image set as profile image

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
Linux ip-xxx-xx-x-xx 5.11.0-1022-aws #23~20.04.1-Ubuntu SMP Mon Nov 15 14:03:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
following commands:

    $ snap list nextcloud
nextcloud  22.2.3snap2  28713  latest/stable  nextcloud✓  -

and:

    $ snap version
snap    2.52.1
snapd   2.52.1
series  16
ubuntu  20.04
kernel  5.11.0-1022-aws

#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).
debugging script output contains sensitive data like username (failed login) and remote IP addresses - happy to provide specific info, but sharing the whole output isn't possible

**Comment by kyrofa** [comment]
Seems like an issue with upstream Nextcloud more than the snap. I suggest [logging an issue there](https://github.com/nextcloud/server).
