### ISSUE TITLE
SOLVED: Problems with cert and existing website

### ISSUE THREAD

**Issue by tabooki** [nextcloud-snap/nextcloud-snap#1969]
(UPDATE: Fixed things. Turned out to be really esy. I just had to install letsencrypt and run standalone for my apache server. Now both my personal apache and nextcloud apache have their own certs and everything is working)

Nextcloud newbie here. Have an existing simple webpage running on Ubuntu port 80 and 443. 

Installed the nextcloud snap and set things up. Running on ports 8000 and 8001. Put some nat rules on the firewall and did the  letsencrpyt portion successfully. 

I can use everything in nextcloud. Great job btw. Really cool. I have a hard time with my homepage on port 443 now. I'm assuming due to something in my browser and the cert from nextcloud.  I get an ERR_CONNECTION_REFUSED.  It works of I use another browser.

Any help would really be appreciated.

**Comment by tabooki** [comment]
If I do this and delete my domain then I can load my homepage again. Once I go to my nextcloud it's broken again. My nextcloud cert is breaking my homepage on the same domain. Do I copy my cert to my previous apache install some how?

http://classically.me/blogs/how-clear-hsts-settings-major-browsers/

**Comment by manasmgkar** [comment]
letsencrypt certs require nextcloud to run on 443

**Comment by tabooki** [comment]
Nope. I have it running on 8080 fine.

Just needed to do some firewall changes when getting the cert initially

**Comment by kyrofa** [comment]
> Just needed to do some firewall changes when getting the cert initially

Careful, those certs are only valid for 90 days. The snap will automatically renew them for you, but only if Let's Encrypt allows it. Let's Encrypt requires that traffic to the domain in question on ports 80/443 reach the snap.
