### ISSUE TITLE
Apache access log location

### ISSUE THREAD

**Issue by Malekingc** [nextcloud-snap/nextcloud-snap#1970]
Hello,

I know that this is not issue related, but I have really struggled to find anything related to my topic, so, I think this is my last resort.

In order to monitor Nextcloud accesses via a SIEM, I need to find the Apache server access logs, that are not on /var/log/

Any clues that can help?

Thank you so much.

**Comment by Guillaume99** [comment]
maybe this will help you : https://github.com/nextcloud-snap/nextcloud-snap#where-is-my-stuff

**Comment by kyrofa** [comment]
> I know that this is not issue related

We're perfectly happy to field questions on here! As @Guillaume99 hinted at, check out `/var/snap/nextcloud/current/logs`, you'll see most logs in there, including the Apache log. I'll go ahead and close this for now, but feel free to continue discussion here.

**Comment by Malekingc** [comment]
@Guillaume99 @kyrofa Thank you so much for the big help guys! So much appreciated.
Good Luck.
