### ISSUE TITLE
error: snap "nextcloud" has "refresh-snap" change in progress

### ISSUE THREAD

**Issue by King-GO** [nextcloud-snap/nextcloud-snap#1975]
upgrade nextcloud from 20/stable>21/stable successfully and keep go to upgrade to >22/stable
error: unknown communicate with server: timeout exceeded while waiting for response (waiting for server restart)
try 1
`sudo snap restart nextcloud`
error: snap "nextcloud" has "refresh-snap" change in progress

try 2
`sudo snap refresh nextcloud --channel=22/stable` 
error: cannot refresh "nextcloud": refreshing disable snap "nextcloud" not supported

snap list --all
nextcloud 20.0.14snap1, 21/stable, disabled
nextcloud 21.0.7snap2, 21/stable, disabled

currently, unable to connect to server
how to do next?

**Comment by King-GO** [comment]
sudo snap revert nextcloud
revert to nextcloud 20 
then
sudo snap refresh nextcloud --channel=21/stable
okay, now stay in 21

**Comment by kyrofa** [comment]
Can I actually see the entire log from the upgrade attempt? It sounds like maybe a hook is failing, which tries to ensure the Nextcloud app store is up. If it's down, you _want_ this to fail or the upgrade will go sideways. If I'm right, that will be a temporary failure and you should try again.

**Comment by King-GO** [comment]
You are right. Now I've successfully upgraded to v22.
