### ISSUE TITLE
permanently dropping privs did not work: File exists

### ISSUE THREAD

**Issue by sparkerb** [nextcloud-snap/nextcloud-snap#1979]
Hi, please help. I get this error when I run any nextcloud.occ command.

permanently dropping privs did not work: File exists

snap    2.53.4
snapd   2.53.4
series  16
ubuntu  20.04
kernel  5.4.0-94-generic

**Comment by sparkerb** [comment]
I tried as root

**Comment by kyrofa** [comment]
This sounds like a snapd bug, please [log it over there](https://bugs.launchpad.net/snapd/+filebug).
