### ISSUE TITLE
Update from 20.0.11 to 20.0.14 does not work

### ISSUE THREAD

**Issue by habakuk007** [nextcloud-snap/nextcloud-snap#1982]
#### Describe the bug
If I try to update from 20.0.11 to 20.0.14 I only get the message: "Current version is 20.0.11., No update available."

#### To Reproduce
1. On the page https://cloud.example.com/index.php/settings/admin/overview I get the message that 20.0.14 is available
2. If I try to run the webbased updater it tells me "No update available".
3. Same If I try `php occ upgrade` or `php updater/updater.phar --no-interaction` on the command line:

```
$ php occ upgrade
Nextcloud is already latest version
```

#### Expected behavior
I would expect that the update starts...

#### OS/snapd/snap version
* OS: Linux 3.10.0-1160.31.1.el7.x86_64 x86_64
* Nextcloud 20.0.11

**Comment by kyrofa** [comment]
A few points:

1. v20 is no longer supported, you should refresh to at least v21
2. The Nextcloud updater app is not compatible with the snap
