### ISSUE TITLE
letsencrypt https is breaking my nextcloud install

### ISSUE THREAD

**Issue by manasmgkar** [nextcloud-snap/nextcloud-snap#1988]
#### Describe the bug
Whenever i enable letsencrypt https my connection times out to the nextcloud instance. 
Port 443 is open on my router,whenever i disable https it works fine. i also tried deleting the certbot folder and then re-requesting a new cert to my domain. letsencrypt is able to fetch the cert etc etc and restart apache but nextcloud via domain wont load. i am able to access it on the local machine going to the local host ip but if i try it via the domain name on the local machine it wont load aswell. i am running the snap on ubuntu 18.04 lts vm on proxmox 

EDIT : i also disable fail2ban incase that was causing the issue and forced pfsense to direct pass port 433 instead of through couple of firewall layers yet the issue persists. With self signed cert if works fine.

Previously on the same instance i had self signed cert which i disabled and then installed letsecnrypt cert. i think the previous self signed cert is causing some issue.

#### OS/snapd/snap version
Snap version 2.2.3 latest stable release.

**Comment by kyrofa** [comment]
Oof, with all the firewall/proxy layers you have setup this could be due to _so_ many things. When you talk about the self-signed cert, are you talking about in the snap (`nextcloud.enable-https self-signed`)? Or another layer? Similarly, when you refer to enabling Let's Encrypt, we're talking about in the snap (`nextcloud.enable-https lets-encrypt`)?

**Comment by manasmgkar** [comment]
> Oof, with all the firewall/proxy layers you have setup this could be due to _so_ many things. When you talk about the self-signed cert, are you talking about in the snap (`nextcloud.enable-https self-signed`)? Or another layer? Similarly, when you refer to enabling Let's Encrypt, we're talking about in the snap (`nextcloud.enable-https lets-encrypt`)?

both self signed and lets encrypt are the inbuilt `nextcloud.enable-https ` ones even if i disable all the firewall's and have a 1:1 passthrough https does not work. now i retested it with `self signed` and even does not work. 

I did couple of nmap tests aswell to see if my isp is blocking outbound port `443` but that is not the case `port 443 on both tcp and udp is open. `Whatever that is happening is taking place in the ubuntu redirection of http to https because http is working fine on my domain name through all the firewall layers in both condition of the firewall being `enabled and disabled.`

**Comment by kyrofa** [comment]
If you `curl https://your-domain.com` what actually happens?

**Comment by kyrofa** [comment]
> i mistakenly did both step 2 (lets encrypt) and step 3 (self signed ) from the digital ocean artical. is there a way to reset the install without breaking my external hard disk mount settings ?

Don't worry too much about that, the snap is designed for you to be able to switch back and forth.

**Comment by manasmgkar** [comment]
> If you `curl https://your-domain.com` what actually happens?

i did this and even though i have letsencrypt enabled it thinks its self signed. 
![nextcloudhttp](https://user-images.githubusercontent.com/76769697/151587212-00451693-7453-4812-8d42-ef6c32f74f04.PNG)

**Comment by kyrofa** [comment]
If you use `curl -k <same domain>` what happens?

**Comment by manasmgkar** [comment]
> If you use `curl -k <same domain>` what happens?

so i guess some ssl error only by the browser 

![httpskflag](https://user-images.githubusercontent.com/76769697/151589084-1844e473-3044-4190-8098-e59bb52c09d7.PNG)

**Comment by kyrofa** [comment]
I can't tell 100% from your image, but that doesn't look like Nextcloud to me. Can you confirm?

**Comment by manasmgkar** [comment]
> I can't tell 100% from your image, but that doesn't look like Nextcloud to me. Can you confirm?

so i disabled the oscp check value in firefox and tried to resolve the site via https. so it is a nat issue only .apparently on the outbound side the nat is redirecting to the main routers login page. Sorry my bad. Thank you for the help,doing great work with the snap. 

![httpsnextclouderror](https://user-images.githubusercontent.com/76769697/151591925-c22127dc-9072-4b5a-86b9-07bf3ce5ebcd.PNG)

**Comment by kyrofa** [comment]
Alright good deal, happy to help!
