### ISSUE TITLE
When the 23? 

### ISSUE THREAD

**Issue by DanieleMar** [nextcloud-snap/nextcloud-snap#1989]
When will be release on snap the version 23 of nextcloud?

**Comment by Pilzinsel64** [comment]
As soon as v23.0.1 hits the changelog page (should be soon). And then it takes few days while it's in testing.
The next 1 or 2 weeks, I guess. As soon as v23.0.1 hit's the changelog I would make a pull request, if I have time. Or someone else does it faster. :D

**Comment by DanieleMar** [comment]
Nice

Il lun 31 gen 2022, 11:48 Pilzinsel64 ***@***.***> ha scritto:

**Comment by DanieleMar** [comment]
Nice.

**Comment by alexander-rieder** [comment]
Seems it is out already but the changelog is still missing.. https://help.nextcloud.com/t/why-is-23-0-1-so-heavily-delayed/132133/13

**Comment by kyrofa** [comment]
Yeah that thread is an example of why we avoid updating as soon as something is available from Nextcloud.

**Comment by kyrofa** [comment]
FYI, if someone would like daily builds of v23 to play with, you can [help me hound Nextcloud for what I need to make it happen](https://twitter.com/rainveil/status/1475347431474692104).

**Comment by juliensl** [comment]
Nextcloud 23 for snap is here !

Thank you guys 😃

**Comment by kyrofa** [comment]
Indeed it is! I will therefore close this issue :) .
