### ISSUE TITLE
Redis password can't be set properly

### ISSUE THREAD

**Issue by SamoLaser** [nextcloud-snap/nextcloud-snap#1990]
#### Describe the bug
When setting the username and password (or just password) for redis, an exception is thrown for all later occ commands. Eg:

`root@comp:~# nextcloud.occ -h`

output:
```
An unhandled exception has been thrown:
RedisException: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct? in /snap/nextcloud/29223/htdocs/lib/private/RedisFactory.php:130
Stack trace:
#0 /snap/nextcloud/29223/htdocs/lib/private/RedisFactory.php(130): Redis->auth()
#1 /snap/nextcloud/29223/htdocs/lib/private/RedisFactory.php(164): OC\RedisFactory->create()
#2 /snap/nextcloud/29223/htdocs/lib/private/Memcache/Redis.php(43): OC\RedisFactory->getInstance()
#3 /snap/nextcloud/29223/htdocs/lib/private/Memcache/Factory.php(115): OC\Memcache\Redis->__construct()
#4 /snap/nextcloud/29223/htdocs/lib/private/Server.php(1065): OC\Memcache\Factory->createLocking()
#5 /snap/nextcloud/29223/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(160): OC\Server->OC\{closure}()
#6 /snap/nextcloud/29223/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#7 /snap/nextcloud/29223/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(127): Pimple\Container->offsetGet()
#8 /snap/nextcloud/29223/htdocs/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query()
#9 /snap/nextcloud/29223/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query()
#10 /snap/nextcloud/29223/htdocs/lib/private/Server.php(2024): OC\AppFramework\Utility\SimpleContainer->get()
#11 /snap/nextcloud/29223/htdocs/lib/private/Files/View.php(118): OC\Server->getLockingProvider()
#12 /snap/nextcloud/29223/htdocs/lib/private/Server.php(435): OC\Files\View->__construct()
#13 /snap/nextcloud/29223/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(160): OC\Server->OC\{closure}()
#14 /snap/nextcloud/29223/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#15 /snap/nextcloud/29223/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(127): Pimple\Container->offsetGet()
#16 /snap/nextcloud/29223/htdocs/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query()
#17 /snap/nextcloud/29223/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query()
#18 /snap/nextcloud/29223/htdocs/lib/private/Server.php(1387): OC\AppFramework\Utility\SimpleContainer->get()
#19 /snap/nextcloud/29223/htdocs/lib/base.php(594): OC\Server->boot()
#20 /snap/nextcloud/29223/htdocs/lib/base.php(1089): OC::init()
#21 /snap/nextcloud/29223/htdocs/console.php(48): require_once('...')
#22 /snap/nextcloud/29223/htdocs/occ(11): require_once('...')
#23 {main}root@s432627:~# nano /var/snap/nextcloud/29223/nextcloud/config/config.php


```

#### To Reproduce
When editing the config.php file directly:
```
 'redis' => 
  array (
    'host' => '/tmp/sockets/redis.sock',
    'port' => 0,
    'user' => 'username',
    'password' => 'password',
  ),
```
When using the occ command:
`nextcloud.occ config:system:set redis password --value='password'`

#### Expected behavior
Commands such as `root@comp:~# nextcloud.occ -h`should have their normal outputs. Eg:
```
root@comp:~# nextcloud.occ -h
Description:
  List commands

Usage:
  list [options] [--] [<namespace>]

Arguments:
  namespace            The namespace name

Options:
      --raw            To output raw command list
      --format=FORMAT  The output format (txt, xml, json, or md) [default: "txt"]
```

#### Screenshots
None

#### OS/snapd/snap version
Ubuntu Server 20.04
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  22.2.3snap3  29223  latest/stable  nextcloud*  -

#### Logs
None

**Comment by kyrofa** [comment]
```
 'redis' => 
  array (
    'host' => '/tmp/sockets/redis.sock',
    'port' => 0,
    'user' => 'username',
    'password' => 'password',
  ),
```

Forgive me, I'm not entirely clear on what you're trying to do, can you help me understand? The redis instance listening on the `/tmp/sockets/redis.sock` socket is the redis shipped in the snap, which isn't configurable. So it appears that you're still using that instance, where you can't actually configure a password, but you're telling Nextcloud to _use_ a username/password. As far as I can tell, this can't possibly result in happiness.

**Comment by SamoLaser** [comment]
I think that would be it then. I thought it was possible to configure it. This same situation has happened many times throughout my installation. I'm unable to tell which components of the snap I can configure and which one's I can't. It's wasted many hours.

**Comment by kyrofa** [comment]
Yeah that's kind of the snap's schtick: it doesn't have a lot of knobs, it should just work. Why are you trying to configure redis? It's not taking a port, it's listening on a socket that is protected with POSIX permissions and it's intended to be private to the snap. What exactly are you trying to accomplish?

**Comment by SamoLaser** [comment]
I was attempting to add a layer of security to it to prevent it from being tampered with should someone get access to my machine.
> it's listening on a socket that is protected with POSIX permissions and it's intended to be private to the snap

This is something I didn't know. It sounds like it wasn't necessary to set the password to begin with if that's the case.

**Comment by kyrofa** [comment]
You only need to do two things to have a secure, production-ready setup with the snap:

- Use good passwords on your Nextcloud account
- Enable HTTPS

Of course, if you notice any micconfiguration, especially if it leads to a security issue, log a bug and we'll fix it ASAP.

**Comment by SamoLaser** [comment]
Will do. Thank you
