### ISSUE TITLE
copying files with cp gives readonly filesystem

### ISSUE THREAD

**Issue by DanieleMar** [nextcloud-snap/nextcloud-snap#1991]
#### Describe the bug
I moved data folder some time ago to a new place.
Now when I try to copy (to backup, not to move) the data folder that is inside ssd with cp to a brand new hdd, give error of readonly filesystem.
Same for other folders in same ssd configured as external storage in NC
I run `sudo snap disable nextcloud` before but give the same.

#### OS/snapd/snap version
snap list nextcloud:
nextcloud  22.2.3snap3  29247  latest/stable  nextcloud✓  disabled

snap version:
snap      2.54.2
snapd     2.54.2
series    16
raspbian  10
kernel    5.10.63-v7l+

Thanks

**Comment by kyrofa** [comment]
Sorry you're having trouble! We're missing some details though, can you clarify what you're trying to do?

> I moved data folder some time ago to a new place.

From this I take it that your data is not in the default `/var/snap/nextcloud/common`, but in `/media/` or `/mnt/` somewhere, utilizing the `removable-media` interface. Correct?

> Now when I try to copy (to backup, not to move) the data folder that is inside ssd with cp to a brand new hdd

When you say "copy", what are we talking about? SSHing in and actually running `cp`, or doing something in Nextcloud? If in Nextcloud, how have you configured the new HDD?

**Comment by DanieleMar** [comment]
> Sorry you're having trouble! We're missing some details though, can you clarify what you're trying to do?
> 
> > I moved data folder some time ago to a new place.
> 
> From this I take it that your data is not in the default `/var/snap/nextcloud/common`, but in `/media/` or `/mnt/` somewhere, utilizing the `removable-media` interface. Correct?
> 
I follow [this guide](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition)

> > Now when I try to copy (to backup, not to move) the data folder that is inside ssd with cp to a brand new hdd
> When you say "copy", what are we talking about? SSHing in and actually running `cp`, or doing something in Nextcloud? If in Nextcloud, how have you configured the new HDD?

both: cp and web interface. 
![image](https://user-images.githubusercontent.com/13423042/152565751-3642ae0c-7efa-4563-8f77-c3ec57259e42.png)

I just wipe the new disk with mkfs.ext4 but after copying from web page of NC and after gave same error of ‘impossible copy folder name’, the disk goes to readonly and it shows in ‘sudo mount’ as
/dev/sdb1 on /media/myDisk type ext4 (ro,relatime)

And Give me this error in NC
`Error: copy(): Write of 151828 bytes failed with errno=30 Read-only file system at /snap/nextcloud/29247/htdocs/lib/private/Files/Storage/Local.php#355`

It's a brand new hdd. Give me errors also with rclone

After I change with chown from root:root to myusername:myusergroup the folder where the hdd is mounted, copied correctly from web interface

But then I retry with other files from web page, and gave me error on web page. On log appear this error: copy(): Write of 104718630 bytes failed with errno=30 Read-only file system at /snap/nextcloud/29247/htdocs/lib/private/Files/Storage/Local.php#355
And the disk unmount automatically and remount on readonly.

I am using Raspberry Pi. I don't know if is a problem of usb that don't have enough power

**Comment by kyrofa** [comment]
>  both: cp and web interface.[...] And the disk unmount automatically and remount on readonly.

Yikes, yeah that sounds like a hardware issue. The snap has nothing to do with what `cp` does, so if that's failing this is an issue that falls outside of the snap. Especially if you see the HDD being remounted as read-only. I'm going to close this issue as a result, but we can continue discussion here.

So this could be because the rpi is having trouble pushing both drives, but it could also be the HDD itself going sideways. When you see the HDD remount, do you see any interesting entries in the syslog?

**Comment by DanieleMar** [comment]
I definitely think it is a problem of Ampere. Raspberry pi 4 support max 1.2 A. The hdd is 1.0 A. The other ssd I think is more than 0.2 :). I just bought a powered hub usb. I will let you know tomorrow
