### ISSUE TITLE
Last background job execution ran x days ago. Something seems wrong.

### ISSUE THREAD

**Issue by moutasem1989** [nextcloud-snap/nextcloud-snap#1994]
#### Describe the bug
getting an error on a fresh install of nextcloud:

`Last background job execution ran 7 days ago. Something seems wrong.`

#### To Reproduce
this is a fresh install using those [steps](https://www.hannahtech.co/post/setup-a-private-cloud-server-for-cloud-storage-chat-documents-and-more-with-nextcloud)

#### Expected behavior
the Corn Background Job runs every 5 min

#### Screenshots
[Screenshot](https://imgur.com/30lDzLV).

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud

Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  22.2.3snap3  29223  latest/stable  nextcloud✓  -

and:

    $ snap version

snap    2.54.2+20.04ubuntu2
snapd   2.54.2+20.04ubuntu2
series  16
ubuntu  20.04
kernel  5.13.0-28-generic

#### Logs
the [Log](https://drive.google.com/file/d/13lf78A_33vQ2Wb_Bh1-dPZx1fT6lOaoQ/view?usp=sharing) file

**Comment by kyrofa** [comment]
In your logs for the cron job I see this:

```
Feb 09 22:13:27 awesomepie-X9DRi-LN4-X9DR3-LN4 nextcloud.nextcloud-cron[15730]: DivisionByZeroError: Division by zero in /var/snap/nextcloud/29223/nextcloud/e…e.php:413
Feb 09 22:13:27 awesomepie-X9DRi-LN4-X9DR3-LN4 nextcloud.nextcloud-cron[15730]: Stack trace:
Feb 09 22:13:27 awesomepie-X9DRi-LN4-X9DR3-LN4 nextcloud.nextcloud-cron[15730]: #0 /var/snap/nextcloud/29223/nextcloud/extra-apps/maps/lib/Service/PhotofilesS…getExif()
Feb 09 22:13:27 awesomepie-X9DRi-LN4-X9DR3-LN4 nextcloud.nextcloud-cron[15730]: #1 /var/snap/nextcloud/29223/nextcloud/extra-apps/maps/lib/BackgroundJob/AddPh…hotoNow()
Feb 09 22:13:27 awesomepie-X9DRi-LN4-X9DR3-LN4 nextcloud.nextcloud-cron[15730]: #2 /snap/nextcloud/29223/htdocs/lib/public/BackgroundJob/Job.php(79): OCA\Maps…ob->run()
Feb 09 22:13:27 awesomepie-X9DRi-LN4-X9DR3-LN4 nextcloud.nextcloud-cron[15730]: #3 /snap/nextcloud/29223/htdocs/lib/public/BackgroundJob/QueuedJob.php(47): OC…execute()
Feb 09 22:13:27 awesomepie-X9DRi-LN4-X9DR3-LN4 nextcloud.nextcloud-cron[15730]: #4 /snap/nextcloud/29223/htdocs/cron.php(127): OCP\BackgroundJob\QueuedJob->execute()
Feb 09 22:13:27 awesomepie-X9DRi-LN4-X9DR3-LN4 nextcloud.nextcloud-cron[15730]: #5 {main}
```

It's not _entirely_ clear what's happening, but any chance it's related to https://github.com/nextcloud/maps/issues/443 ?

**Comment by moutasem1989** [comment]
I disabled and uninstalled the App .. the problem continues

**Comment by kyrofa** [comment]
Can you run `sudo snap restart nextcloud`, wait for Nextcloud to come back up, and then provide the output of `sudo journalctl -u snap.nextcloud.nextcloud-cron.service`, please?

**Comment by moutasem1989** [comment]
welcome to ubuntu 20.04.3 lts (gnu/linux 5.13.0-28-generic x86_64)

 * documentation:  https://help.ubuntu.com
 * management:     https://landscape.canonical.com
 * support:        https://ubuntu.com/advantage

0 updates can be applied immediately.

your hardware enablement stack (hwe) is supported until april 2025.
last login: wed feb  9 20:59:43 2022 from 192.168.87.247
awesomepie@local-server:~$ sudo snap restart nextcloud
[sudo] password for awesomepie:
restarted.                                                                         awesomepie@local-server:~$ sudo journalctl -u snap.nextcloud.nextcloud-cron.service
-- logs begin at wed 2021-07-21 21:25:18 cest, end at thu 2022-02-10 00:35:34 cet.>jan 29 10:55:03 local-server systemd[1]: started service for sna>jan 29 10:55:30 local-server nextcloud.nextcloud-cron[60403]: wa>jan 29 18:27:07 local-server systemd[1]: stopping service for sn>jan 29 18:27:07 local-server systemd[1]: snap.nextcloud.nextclou>jan 29 18:27:07 local-server systemd[1]: stopped service for sna>-- reboot --
jan 30 12:01:16 local-server systemd[1]: started service for sna>jan 30 12:01:31 local-server nextcloud.nextcloud-cron[1224]: wai>jan 30 12:30:26 local-server systemd[1]: stopping service for sn>jan 30 12:30:26 local-server systemd[1]: snap.nextcloud.nextclou>jan 30 12:30:26 local-server systemd[1]: stopped service for sna>-- reboot --
jan 30 12:31:22 local-server systemd[1]: started service for sna>jan 30 12:31:26 local-server nextcloud.nextcloud-cron[1270]: wai>jan 30 18:24:21 local-server systemd[1]: stopping service for sn>jan 30 18:24:21 local-server systemd[1]: snap.nextcloud.nextclou>jan 30 18:24:21 local-server systemd[1]: stopped service for sna>-- reboot --
jan 30 19:12:29 local-server systemd[1]: started service for sna>jan 30 19:12:32 local-server nextcloud.nextcloud-cron[1247]: wai>jan 30 23:58:14 local-server systemd[1]: stopping service for sn>jan 30 23:58:14 local-server systemd[1]: snap.nextcloud.nextclou>jan 30 23:58:14 local-server systemd[1]: stopped service for sna>jan 30 23:58:41 local-server systemd[1]: started service for sna>lines 1-25...skipping...
-- logs begin at wed 2021-07-21 21:25:18 cest, end at thu 2022-02-10 00:35:34 cet.>jan 29 10:55:03 local-server systemd[1]: started service for sna>jan 29 10:55:30 local-server nextcloud.nextcloud-cron[60403]: wa>jan 29 18:27:07 local-server systemd[1]: stopping service for sn>jan 29 18:27:07 local-server systemd[1]: snap.nextcloud.nextclou>jan 29 18:27:07 local-server systemd[1]: stopped service for sna>-- reboot --                                                                       jan 30 12:01:16 local-server systemd[1]: started service for sna>jan 30 12:01:31 local-server nextcloud.nextcloud-cron[1224]: wai>jan 30 12:30:26 local-server systemd[1]: stopping service for sn>jan 30 12:30:26 local-server systemd[1]: snap.nextcloud.nextclou>jan 30 12:30:26 local-server systemd[1]: stopped service for sna>-- reboot --                                                                       jan 30 12:31:22 local-server systemd[1]: started service for sna>jan 30 12:31:26 local-server nextcloud.nextcloud-cron[1270]: wai>jan 30 18:24:21 local-server systemd[1]: stopping service for sn>jan 30 18:24:21 local-server systemd[1]: snap.nextcloud.nextclou>jan 30 18:24:21 local-server systemd[1]: stopped service for sna>-- reboot --                                                                       jan 30 19:12:29 local-server systemd[1]: started service for sna>jan 30 19:12:32 local-server nextcloud.nextcloud-cron[1247]: wai>jan 30 23:58:14 local-server systemd[1]: stopping service for sn>jan 30 23:58:14 local-server systemd[1]: snap.nextcloud.nextclou>jan 30 23:58:14 local-server systemd[1]: stopped service for sna>jan 30 23:58:41 local-server systemd[1]: started service for sna>jan 30 23:58:41 local-server nextcloud.nextcloud-cron[119966]: w>jan 31 00:09:53 local-server systemd[1]: stopping service for sn>jan 31 00:09:53 local-server systemd[1]: snap.nextcloud.nextclou>jan 31 00:09:53 local-server systemd[1]: stopped service for sna>jan 31 00:09:53 local-server systemd[1]: started service for sna>jan 31 00:09:53 local-server nextcloud.nextcloud-cron[130577]: w>jan 31 00:10:30 local-server systemd[1]: stopping service for sn>jan 31 00:10:30 local-server systemd[1]: snap.nextcloud.nextclou>jan 31 00:10:30 local-server systemd[1]: stopped service for sna>-- reboot --                                                                       jan 31 12:03:12 local-server systemd[1]: started service for sna>-- logs begin at wed 2021-07-21 21:25:18 cest, end at thu 2022-02-10 00:35:34 cet.>jan 29 10:55:03 local-server systemd[1]: started service for sna>jan 29 10:55:30 local-server nextcloud.nextcloud-cron[60403]: wa>jan 29 18:27:07 local-server systemd[1]: stopping service for sn>jan 29 18:27:07 local-server systemd[1]: snap.nextcloud.nextclou>jan 29 18:27:07 local-server systemd[1]: stopped service for sna>-- reboot --                                                                       jan 30 12:01:16 local-server systemd[1]: started service for sna>jan 30 12:01:31 local-server nextcloud.nextcloud-cron[1224]: wai>jan 30 12:30:26 local-server systemd[1]: stopping service for sn>jan 30 12:30:26 local-server systemd[1]: snap.nextcloud.nextclou>jan 30 12:30:26 local-server systemd[1]: stopped service for sna>-- reboot --                                                                       jan 30 12:31:22 local-server systemd[1]: started service for sna>jan 30 12:31:26 local-server nextcloud.nextcloud-cron[1270]: wai>jan 30 18:24:21 local-server systemd[1]: stopping service for sn>jan 30 18:24:21 local-server systemd[1]: snap.nextcloud.nextclou>jan 30 18:24:21 local-server systemd[1]: stopped service for sna>-- reboot --                                                                       jan 30 19:12:29 local-server systemd[1]: started service for sna>jan 30 19:12:32 local-server nextcloud.nextcloud-cron[1247]: wai>jan 30 23:58:14 local-server systemd[1]: stopping service for sn>jan 30 23:58:14 local-server systemd[1]: snap.nextcloud.nextclou>jan 30 23:58:14 local-server systemd[1]: stopped service for sna>jan 30 23:58:41 local-server systemd[1]: started service for sna>jan 30 23:58:41 local-server nextcloud.nextcloud-cron[119966]: w>jan 31 00:09:53 local-server systemd[1]: stopping service for sn>jan 31 00:09:53 local-server systemd[1]: snap.nextcloud.nextclou>jan 31 00:09:53 local-server systemd[1]: stopped service for sna>jan 31 00:09:53 local-server systemd[1]: started service for sna>jan 31 00:09:53 local-server nextcloud.nextcloud-cron[130577]: w>jan 31 00:10:30 local-server systemd[1]: stopping service for sn>jan 31 00:10:30 local-server systemd[1]: snap.nextcloud.nextclou>lines 1-33...skipping...
-- logs begin at wed 2021-07-21 21:25:18 cest, end at thu 2022-02-10 00:35:34 cet.>jan 29 10:55:03 local-server systemd[1]: started service for sna>jan 29 10:55:30 local-server nextcloud.nextcloud-cron[60403]: wa>jan 29 18:27:07 local-server systemd[1]: stopping service for sn>jan 29 18:27:07 local-server systemd[1]: snap.nextcloud.nextclou>jan 29 18:27:07 local-server systemd[1]: stopped service for sna>-- reboot --
jan 30 12:01:16 local-server systemd[1]: started service for sna>jan 30 12:01:31 local-server nextcloud.nextcloud-cron[1224]: wai>jan 30 12:30:26 local-server systemd[1]: stopping service for sn>jan 30 12:30:26 local-server systemd[1]: snap.nextcloud.nextclou>jan 30 12:30:26 local-server systemd[1]: stopped service for sna>-- reboot --
jan 30 12:31:22 local-server systemd[1]: started service for sna>jan 30 12:31:26 local-server nextcloud.nextcloud-cron[1270]: wai>jan 30 18:24:21 local-server systemd[1]: stopping service for sn>jan 30 18:24:21 local-server systemd[1]: snap.nextcloud.nextclou>jan 30 18:24:21 local-server systemd[1]: stopped service for sna>-- reboot --
jan 30 19:12:29 local-server systemd[1]: started service for sna>jan 30 19:12:32 local-server nextcloud.nextcloud-cron[1247]: wai>jan 30 23:58:14 local-server systemd[1]: stopping service for sn>jan 30 23:58:14 local-server systemd[1]: snap.nextcloud.nextclou>jan 30 23:58:14 local-server systemd[1]: stopped service for sna>jan 30 23:58:41 local-server systemd[1]: started service for sna>jan 30 23:58:41 local-server nextcloud.nextcloud-cron[119966]: w>jan 31 00:09:53 local-server systemd[1]: stopping service for sn>jan 31 00:09:53 local-server systemd[1]: snap.nextcloud.nextclou>jan 31 00:09:53 local-server systemd[1]: stopped service for sna>jan 31 00:09:53 local-server systemd[1]: started service for sna>jan 31 00:09:53 local-server nextcloud.nextcloud-cron[130577]: w>jan 31 00:10:30 local-server systemd[1]: stopping service for sn>jan 31 00:10:30 local-server systemd[1]: snap.nextcloud.nextclou>jan 31 00:10:30 local-server systemd[1]: stopped service for sna>-- reboot --
jan 31 12:03:12 local-server systemd[1]: started service for sna>jan 31 12:03:23 local-server nextcloud.nextcloud-cron[1184]: wai>jan 31 13:15:05 local-server systemd[1]: stopping service for sn>jan 31 13:15:05 local-server systemd[1]: snap.nextcloud.nextclou>jan 31 13:15:05 local-server systemd[1]: stopped service for sna>jan 31 13:37:13 local-server systemd[1]: started service for sna>jan 31 13:37:13 local-server nextcloud.nextcloud-cron[22900]: wa>jan 31 13:54:43 local-server systemd[1]: stopping service for sn>jan 31 13:54:43 local-server systemd[1]: snap.nextcloud.nextclou>jan 31 13:54:43 local-server systemd[1]: stopped service for sna>-- reboot --
jan 31 20:47:33 local-server systemd[1]: started service for sna>jan 31 20:47:36 local-server nextcloud.nextcloud-cron[1276]: wai>jan 31 21:57:57 local-server systemd[1]: stopping service for sn>jan 31 21:57:57 local-server systemd[1]: snap.nextcloud.nextclou>jan 31 21:57:57 local-server systemd[1]: stopped service for sna>jan 31 22:02:42 local-server systemd[1]: started service for sna>jan 31 22:03:01 local-server nextcloud.nextcloud-cron[21088]: wa>jan 31 22:17:26 local-server systemd[1]: stopping service for sn>jan 31 22:17:26 local-server systemd[1]: snap.nextcloud.nextclou>jan 31 22:17:26 local-server systemd[1]: stopped service for sna>jan 31 22:17:26 local-server systemd[1]: started service for sna>jan 31 22:17:27 local-server nextcloud.nextcloud-cron[57198]: wa>jan 31 22:31:45 local-server systemd[1]: stopping service for sn>jan 31 22:31:45 local-server systemd[1]: snap.nextcloud.nextclou>jan 31 22:31:45 local-server systemd[1]: stopped service for sna>jan 31 22:31:46 local-server systemd[1]: started service for sna>jan 31 22:31:46 local-server nextcloud.nextcloud-cron[60339]: wa>jan 31 22:33:00 local-server systemd[1]: stopping service for sn>jan 31 22:33:00 local-server systemd[1]: snap.nextcloud.nextclou>jan 31 22:33:00 local-server systemd[1]: stopped service for sna>-- reboot --
jan 31 22:34:11 local-server systemd[1]: started service for sna>jan 31 22:34:14 local-server nextcloud.nextcloud-cron[1278]: wai>feb 01 09:19:37 local-server systemd[1]: stopping service for sn>feb 01 09:19:37 local-server systemd[1]: snap.nextcloud.nextclou>feb 01 09:19:37 local-server systemd[1]: stopped service for sna>feb 01 09:22:26 local-server systemd[1]: started service for sna>feb 01 09:22:26 local-server nextcloud.nextcloud-cron[420289]: w>feb 01 09:23:38 local-server systemd[1]: stopping service for sn>feb 01 09:23:38 local-server systemd[1]: snap.nextcloud.nextclou>feb 01 09:23:38 local-server systemd[1]: stopped service for sna>lines 1-77

**Comment by kyrofa** [comment]
Hmm, that was pretty garbled, I'm afraid I'm having trouble reading it. Mind copying it again, and pasting it within code blocks (i.e. ```)?

**Comment by moutasem1989** [comment]
SOLVED
I am guessing the Maps app was indeed the problem. i removed it yesterday but when i woke up this morning the problem has solved itself. 
Thank you for your help ! now i know what steps to take for the next time!

**Comment by gappleto97** [comment]
Of course I manage to fix it only after running the script...

Far as I can tell, my system's cron didn't used to need some environment variables that it now needs. I'm rather confused as to what fixed it, but my news feeds are updating again, so I'm happy with that much
