### ISSUE TITLE
Snap refresh error from 17 to 18 stable, received an unexpected http response code (404)

### ISSUE THREAD

**Issue by louis417asdo** [nextcloud-snap/nextcloud-snap#1997]
#### Describe the bug
I am currently using snap nextcloud 17/stable version, and want to upgrade to 22/stable.
but when I try to refresh nextcloud to 18/stable, it shows below error:

- Download snap "nextcloud" (25109) from channel "18/stable" (received an unexpected http response code (404) when trying to download https://canonical-lgw01.cdn.snapcraftcontent.com/download-origin/canonical-lgw01/njObIbGQEaVx1H4nyWxchk1i8opy4h54_25109.snap?interactive=1&token=1644688800_ac3061c813e49526e7836afcb79bc55d4e465a45)

I check the link, seems it is unreachable.

I tried to download 19/stable and others, they are ok.

Any solution of this?

#### To Reproduce
1. Sudo refresh nextcloud --channel=18/stable
2. See error

#### Expected behavior
Can upgrade to 18/stable version

#### OS/snapd/snap version
OS is Ubuntu 18.04.6

$ snap list nextcloud
Name       Version       Rev    Tracking  Publisher   Notes
nextcloud  17.0.10snap1  23903  17/edge   nextcloud✓  -

and:

$ snap version
snap    2.54.2+18.04ubuntu1
snapd   2.54.2+18.04ubuntu1
series  16
ubuntu  18.04
kernel  4.15.0-167-generic

#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).

**Comment by kyrofa** [comment]
Huh, that sounds like a store error. Mind making a post about this on the [snapcraft forum](https://forum.snapcraft.io/), in the store category?
