### ISSUE TITLE
what is the correct HAProxy configuration to fix dav .well-known redirects? (NextCloud handles SSL)

### ISSUE THREAD

**Issue by moutasem1989** [nextcloud-snap/nextcloud-snap#2004]
#### Describe the bug
This topic has been opened and closed under [this](https://github.com/nextcloud-snap/nextcloud-snap/issues/805) and [this](https://github.com/nextcloud-snap/nextcloud-snap/issues/1042) titles. The workaround provided there only applies in specific cases.

I have Nextcloud Snap running behind HAProxy. already configgured HAProxy to work with Nextcloud and functions as expected.
However, I am getting errors back under _Security & setup warnings_:
```
Your web server is not properly set up to resolve "/.well-known/caldav". Further information can be found in the documentation ↗.
Your web server is not properly set up to resolve "/.well-known/carddav". Further information can be found in the documentation ↗.
```
I have tested the following code inspired by [this ](https://github.com/nextcloud-snap/nextcloud-snap/issues/1042)but it did not work  because it is meant for HAProxy to handle the SSL cert:

> It's just a workaround for now ....
> This can only be done when HAProxy handles SSL because it wouldn't know the request URL otherwise.

This is the code i have tried to impliment:
```
frontend http
        bind *:80
        mode http

        acl host_nextcloud hdr(host) -i nextcloud.domain.com
        use_backend nextcloud-http if host_nextcloud

        acl path_dav path_beg /.well-known/caldav || path_beg /.well-known/carddav
        redirect location "http://nextcloud.domain.com/remote.php/dav" if path_dav

frontend https
        bind *:443
        mode tcp

        tcp-request inspect-delay 5s
        tcp-request content accept if { req_ssl_hello_type 1 }

        acl host_nextcloud req_ssl_sni -i nextcloud.domain.com
        use_backend nextcloud-https if host_nextcloud

        acl path_dav path_beg /.well-known/caldav || path_beg /.well-known/carddav
        redirect location "https://nextcloud.domain.com/remote.php/dav" if path_dav

backend nextcloud-http
        mode http
        balance roundrobin
        option forwardfor
        option httpchk HEAD / HTTP/1.1\r\nHost:localhost
        server nextcloud 127.0.0.1:81 check

backend nextcloud-https
        mode tcp
        balance roundrobin
        option httpchk HEAD / HTTP/1.1\r\nHost:localhost
        option ssl-hello-chk
        server nextcloud 127.0.0.1:444 check
```

What is the explicit correct configuration for HAProxy to fix the  dav .well-known redirects if SSL is handled by NextCloud?

#### OS/snapd/snap version

Name: nextcloud  
Version: 22.2.3snap3
Rev: 29223  
Tracking: latest/stable
Publisher: nextcloud✓
Notes:

snap    2.54.3
snapd   2.54.3
series  16
ubuntu  20.04
kernel  5.13.0-28-generic

**Comment by githubber4ever** [comment]
Maybe you can try to switch the order in https/http frontend: [1. redirect 2. use_back_end]
```	
	acl path_dav path_beg /.well-known/caldav || path_beg /.well-known/carddav
	redirect location "https://nextcloud.domain.com/remote.php/dav" if path_dav

	acl host_nextcloud req_ssl_sni -i nextcloud.domain.com
	use_backend nextcloud-https if host_nextcloud
```

I have something similar:
```
	acl path_carddav path /.well-known/carddav/ /.well-known/carddav
	acl path_caldav path /.well-known/caldav/ /.well-known/caldav
	http-request redirect location /nextcloud/remote.php/dav/ if path_carddav || path_caldav

	use_backend nextcloud-http if { path_beg /nextcloud }
```

**Comment by moutasem1989** [comment]
Other things I have tried:
Opened the port 444 on my machin .. forwarded it from the rowter and tried adding this bit at the end of HAProxy Config file:

```
frontend https
        bind *:444
        mode tcp

        tcp-request inspect-delay 5s
        tcp-request content accept if { req_ssl_hello_type 1 }

        http-request redirect location https://%[req.hdr(Host)]:443%[capture.req.uri] if is444
```
no success

**Comment by kyrofa** [comment]
It's been a long time since I looked at this, but I have a few thoughts that could potentially help:

1. My particular setup actually keeps the snap using standard ports and puts it in a LXD container. HAProxy runs in another lxd container. I do not see this problem.
2. You might try following [this bit of the README](https://github.com/nextcloud-snap/nextcloud-snap#httphttps-port-configuration) and try playing with overwriting what Nextcloud thinks is the host, e.g. `sudo nextcloud.occ config:system:set overwritehost --value="example.com:81"`.

**Comment by moutasem1989** [comment]
Well i saved myself a lot of trouble and disabled HTTPS on NextCloud and let HAProxy handle the SSL certificate. There might be other ways but if you're looking for a way to do it, this way will spare you a lot of headache

**Comment by ShapeShifter499** [comment]
@moutasem1989 does this conflict with auto updating the lets-encyrpt cert in the "nextcloud.enable-https lets-encrypt" command?

**Comment by ShapeShifter499** [comment]
@moutasem1989 mind sharing how you set it up?

**Comment by ShapeShifter499** [comment]
Okay so the above "path beg" config works fine if you switch away from "mode tcp" and have haproxy handle ssl

**Comment by githubber4ever** [comment]
In "mode tcp" HAProxy cannot see/know the path of the request (if its SSL protected), since its a different layer, so "path beg" will only in "mode http".
