### ISSUE TITLE
Updating the snap is removing Maintenance mode from Instance

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud-snap/nextcloud-snap#202]

**Comment by kyrofa** [comment]
This is by design. Are you saying you're actually manually putting it into maintenance mode? And then you refreshed the snap and expected maintenance mode to stay applied?

**Comment by MariusBluem** [comment]
Exactly. In some cases, you set your NC into Maintainance with config.php - so that users are locked out while you are working on the instance.

**Comment by kyrofa** [comment]
Fair enough. I think this ties into the work needed for #196, where the upgrade process generally needs to be more robust.
