### ISSUE TITLE
NextCloud 23.0.2 (Snap) upgrade killed all Yubikey NFC (2fa) access.... 

### ISSUE THREAD

**Issue by The-Real-Admin-Guy** [nextcloud-snap/nextcloud-snap#2021]
No problems until today, (new automated) snap upgrade to version 23.0.2 

The  Logins other wise work using email authentications, but for those who use only the Yubikey NFC's, they are dead in the water, with no access and the system locking them out due to excessive multiple login attempt.

Login in via a second device logged in also works.  Only my Yubikey now fails.

Removing the Yubikey, and re installing fails also.  Good Key.  The os is not the issue, all other servers requiring  Yubikey access = NFF.

Cheers!

**Comment by ph00lt0** [comment]
@The-Real-Admin-Guy do you use the Yubico standard or U2F?
For me it works as expected.

**Comment by kyrofa** [comment]
My production server is protected with U2F, so it always gets a test before I ship a release. It works fine. Can you clarify how your setup differs from mine?

**Comment by The-Real-Admin-Guy** [comment]
I setup both... fail.

**Comment by Guillaume99** [comment]
look like this one ?
https://github.com/nextcloud/server/issues/31489

**Comment by kyrofa** [comment]
Ah, I use firefox so that seems possible. Nice find @Guillaume99, thank you.

**Comment by ph00lt0** [comment]
> look like this one ? [nextcloud/server#31489](https://github.com/nextcloud/server/issues/31489)

I closed this issue now as it's not reported in the correct app. More information is here: https://github.com/nextcloud/twofactor_u2f/issues/947

**Comment by kyrofa** [comment]
Thank you @ph00lt0, very helpful.

**Comment by ph00lt0** [comment]
https://github.com/nextcloud/twofactor_webauthn#migration-from-two-factor-u2f 

The solution is here already :)

**Comment by kyrofa** [comment]
Indeed. @The-Real-Admin-Guy can you try that ^ ?

**Comment by ph00lt0** [comment]
@kyrofa i just migrated myself, works flawless, both in chrome and firefox :)
