### ISSUE TITLE
Update Netxcloud 23.0.2snap1 -- error message PHP OPcache module is not properly configured:

### ISSUE THREAD

**Issue by scubamuc** [nextcloud-snap/nextcloud-snap#2024]
After snap update to Netxcloud 23.0.2snap1

an error message appears in settings/overview

> 
> The PHP OPcache module is not properly configured:
> 
> The OPcache interned strings buffer is nearly full. To assure that repeating strings can be effectively cached, it is recommended to apply opcache.interned_strings_buffer to your PHP configuration with a value higher than 8.

How can this be corrected in cofig.php?
Which value is suggested?

**Comment by kyrofa** [comment]
Don't worry, this isn't harmful. Keep an eye on it over the next few days-- do you continue seeing it? If so we can make the interned buffer cache size configurable so you can get a little more performance out of it.

**Comment by scubamuc** [comment]
Restarted nextcloud-snap `# snap restart nextcloud ` to see message disappear!
Please close and forget

**Comment by kyrofa** [comment]
Right, this is a cache in PHP-- restarting clears it. As you use Nextcloud, it fills up and swaps strings out. If it gets pretty full, the new release of Nextcloud warns you about it. If you see a warning constantly, it means you would benefit from slightly improved performance if you increased the cache size (something that is not configurable in the snap today). So please still keep an eye on it-- if you see it often, I'm willing to make that configurable.

**Comment by scubamuc** [comment]
Thanks, I'll keep an eye on it nonetheless and give you feedback.
Configurable is great!

**Comment by scubamuc** [comment]
warning message continues.
I have several (4) systems running the same snap with almost identical setups. 
Only one system displays the warning message; 
![grafik](https://user-images.githubusercontent.com/54933878/158952841-6618df78-5614-431a-864b-0c2460d57210.png)
Please make configurable.

**Comment by ourownstory** [comment]
Same issue here. 
Please allow us to set
``` 
opcache.memory_consumption
opcache.interned_strings_buffer
```
Thank you!

**Comment by kyrofa** [comment]
Alright, I'm on board with this, just need to find time to do it unless someone else wants to take a crack at it.

**Comment by aagostini** [comment]
Hi to all,
I see the same warning message :
_The OPcache interned strings buffer is nearly full. To assure that repeating strings can be effectively cached, it is recommended to apply opcache.interned_strings_buffer to your PHP configuration with a value higher than 8._

on my two snap instance: **[Nextcloud Hub II](https://nextcloud.com/) (23.0.3)**

Only one of them instance have CODE installed.
It is possible to update/change php.ini configuration manually but persistently?
We have to waiting for next upgrade?

Thank you.

**Comment by scubamuc** [comment]
@kyrofa , may i bump this... as a friendly reminder?  :-)

**Comment by kz6fittycent** [comment]
> 

I tend to sync a lot of files and share them with others. I have several family members using my server so it sees a lot of traffic. Having the ability to set this value would be awesome. I'm looking through the code right now to see I can figure out how to add it and then do a PR, but I'm likely to take a while to get it done since this snap is new to me.

**Comment by kyrofa** [comment]
Refer to how the PHP memory limit works to get a leg up.

**Comment by kz6fittycent** [comment]
Do I need to be looking at this file: `src/php/utilities/php-utilities`? Just want to be sure I'm thinking along the right lines before I invest a ton of time barking up the wrong tree. It seems like you're using this script to get user input to then set values within the snap using `snapctl`.

**Comment by kyrofa** [comment]
Yes that's one piece. Look also at `src/hooks/bin/configure` and the PHP configs.

**Comment by kz6fittycent** [comment]
@kyrofa I've got a rough draft of the code needed to do this (I think). I need a sanity check on what I've done and wondering which branch you'd like me to do a PR in?

Please note: I am unable to build the snap locally, so I'm hoping your review of my code and potentially a test-build on your end will result in a good outcome.

**Comment by kyrofa** [comment]
Make a PR into develop, please.

**Comment by kz6fittycent** [comment]
PR #2216

**Comment by YoannPa** [comment]
Hi,
I have the same issue in Snap Nextcloud 24.0.6.
And actually to complete what has been said before, I think it would be nice if we could have access to modify any opcache.* parameters if possible.

If this isn't possible, here is a non-exhaustive list of parameters I believe nextcloud admin  may want to play with once it will be possible:

- opcache.interned_strings_buffer
- opcache.revalidate_freq
- opcache.fast_shutdown
- opcache.save_comments
- opcache.validate_timestamps
- opcache.enable
- opcache.enable_cli
- opcache.max_accelerated_files
- opcache.memory_consumption

I also would like to share additionnal sources for those who would like to read more about opcache teaking and find how to tune it properly for your own server:

- https://docs.nextcloud.com/server/latest/admin_manual/installation/server_tuning.html#enable-php-opcache
- https://github.com/nextcloud/server/issues/31223
- https://haydenjames.io/php-performance-opcache-control-panels/
- https://github.com/amnuts/opcache-gui 

Looking forward to get this available. Thank you :) !

**Comment by kyrofa** [comment]
Making most of those parameters configurable would be a footgun. For example, Nextcloud requires `opcache.save_comments`. If we made it configurable, and you turned it off, you'd break Nextcloud. There's no upside to that. The PHP shipped in the snap is not generically useful to you: it's entire purpose is to run Nextcloud. Because of that, for the most part, we can have a configuration that works for everyone, instead of exposing knobs.

**Comment by YoannPa** [comment]
> Making most of those parameters configurable would be a footgun. For example, Nextcloud requires `opcache.save_comments`. If we made it configurable, and you turned it off, you'd break Nextcloud. There's no upside to that. The PHP shipped in the snap is not generically useful to you: it's entire purpose is to run Nextcloud. Because of that, for the most part, we can have a configuration that works for everyone instead of exposing knobs.

Thank you for the information, I didn't know that.
Then it make sense to keep the list of configurable options short.

As mentionned before, `opcache.memory_consumption` and `opcache.interned_strings_buffer` should be made configurable, and as I have read, it is already done.
`opcache.revalidate_freq` could also be of primary interest.
As for the remaining parameters, I admit I don't know to which extend they could cause issues to Nextcloud.

**Comment by mattish91** [comment]
As many before already have mentioned, i also see this message, not sure how it affects me or the users on my server yet tho.

**Comment by kyrofa** [comment]
If someone would like to join @kz6fittycent on #2216 we could see this through.

**Comment by kz6fittycent** [comment]
Thanks @kyrofa  - life has been pretty busy recently. I could use an assist if anyone's game. If not, I'll try to get to the fixes during the holidays.

**Comment by kyrofa** [comment]
No explanation necessary @kz6fittycent! This is open source and personal time. I've got six kids-- if anyone understands, I do :) . Please feel only mutual interest, not pressure.

**Comment by alexx-250323** [comment]
I am also getting the warning on version 26.0.3 "...with a value higher than 128."

**Comment by YoannPa** [comment]
@alexx-250323 as far as I am concerned I don't have this warning anymore in 26.0.3.
Maybe the warning will resolve itself after some days?
Or, could it be that this warning is now triggered by the use of specific third part apps, idk?
Just wondering.

**Comment by scubamuc** [comment]
@YoannPa, agreed this is not appearing any longer. It has nothing to do with 3rd party apps though.

**Comment by alexx-250323** [comment]
> @alexx-250323 as far as I am concerned I don't have this warning anymore in 26.0.3. Maybe the warning will resolve itself after some days? Or, could it be that this warning is now triggered by the use of specific third part apps, idk? Just wondering.



> @YoannPa, agreed this is not appearing any longer. It has nothing to do with 3rd party apps though.


It went off by itself after a while. Weird but I am happy it's not showing up anymore.
