### ISSUE TITLE
IVersionBackend Fatal error & Cron has stopped working

### ISSUE THREAD

**Issue by Minnietheandroid** [nextcloud-snap/nextcloud-snap#2025]
#### Describe the bug
Hi.
Hoping someone can tell me what's going on! :)

This "fatal" error has appeared all over my logs possibly since the latest snap was pushed out.
\"OCA\\Files_Versions\\Versions\\IVersionBackend\" not found"

System 'Overview' says 
'Last background job execution ran 2 days ago. Something seems wrong'

Any advice would be most welcome.

[{"reqId":"71jU1S5JHKcMjtwzUWov","level":4,"time":"2022-03-18T08:33:44+00:00","remoteAddr":"192.168.1.50","user":"Mne","app":"no app in context","method":"GET","url":"/index.php/apps/logreader/get?offset=0&count=50&levels=00001","message":"Could not boot files_trashbin: Interface \"OCA\\Files_Versions\\Versions\\IVersionBackend\" not found","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0","version":"23.0.2.1","exception":{"Exception":"Error","Message":"Interface \"OCA\\Files_Versions\\Versions\\IVersionBackend\" not found","Code":0,"Trace":[{"file":"/snap/nextcloud/29929/htdocs/lib/composer/composer/ClassLoader.php","line":571,"function":"include"},{"file":"/snap/nextcloud/29929/htdocs/lib/composer/composer/ClassLoader.php","line":428,"function":"Composer\\Autoload\\includeFile"},{"file":"/var/snap/nextcloud/29929/nextcloud/extra-apps/groupfolders/lib/AppInfo/Application.php","line":99,"function":"loadClass","class":"Composer\\Autoload\\ClassLoader","type":"->"},{"file":"/snap/nextcloud/29929/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php","line":160,"function":"OCA\\GroupFolders\\AppInfo\\{closure}","class":"OCA\\GroupFolders\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/snap/nextcloud/29929/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php","line":118,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/snap/nextcloud/29929/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php","line":127,"function":"offsetGet","class":"Pimple\\Container","type":"->"},{"file":"/snap/nextcloud/29929/htdocs/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":457,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/snap/nextcloud/29929/htdocs/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":435,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/snap/nextcloud/29929/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php","line":56,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/var/snap/nextcloud/29929/nextcloud/extra-apps/groupfolders/lib/AppInfo/Application.php","line":94,"function":"get","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/snap/nextcloud/29929/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php","line":160,"function":"OCA\\GroupFolders\\AppInfo\\{closure}","class":"OCA\\GroupFolders\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/snap/nextcloud/29929/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php","line":118,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/snap/nextcloud/29929/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php","line":127,"function":"offsetGet","class":"Pimple\\Container","type":"->"},{"file":"/snap/nextcloud/29929/htdocs/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":457,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/snap/nextcloud/29929/htdocs/lib/private/ServerContainer.php","line":145,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/snap/nextcloud/29929/htdocs/apps/files_trashbin/lib/AppInfo/Application.php","line":90,"function":"query","class":"OC\\ServerContainer","type":"->"},{"file":"/snap/nextcloud/29929/htdocs/lib/private/AppFramework/Bootstrap/FunctionInjector.php","line":67,"function":"registerTrashBackends","class":"OCA\\Files_Trashbin\\AppInfo\\Application","type":"->"},{"file":"/snap/nextcloud/29929/htdocs/lib/private/AppFramework/Bootstrap/BootContext.php","line":51,"function":"injectFn","class":"OC\\AppFramework\\Bootstrap\\FunctionInjector","type":"->"},{"file":"/snap/nextcloud/29929/htdocs/apps/files_trashbin/lib/AppInfo/Application.php","line":56,"function":"injectFn","class":"OC\\AppFramework\\Bootstrap\\BootContext","type":"->"},{"file":"/snap/nextcloud/29929/htdocs/lib/private/AppFramework/Bootstrap/Coordinator.php","line":181,"function":"boot","class":"OCA\\Files_Trashbin\\AppInfo\\Application","type":"->"},{"file":"/snap/nextcloud/29929/htdocs/lib/private/legacy/OC_App.php","line":206,"function":"bootApp","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/snap/nextcloud/29929/htdocs/lib/private/legacy/OC_App.php","line":140,"function":"loadApp","class":"OC_App","type":"::"},{"file":"/snap/nextcloud/29929/htdocs/apps/dav/lib/AppInfo/Application.php","line":171,"function":"loadApps","class":"OC_App","type":"::"},{"file":"/snap/nextcloud/29929/htdocs/lib/private/AppFramework/Bootstrap/Coordinator.php","line":181,"function":"boot","class":"OCA\\DAV\\AppInfo\\Application","type":"->"},{"file":"/snap/nextcloud/29929/htdocs/lib/private/legacy/OC_App.php","line":206,"function":"bootApp","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/snap/nextcloud/29929/htdocs/lib/private/legacy/OC_App.php","line":140,"function":"loadApp","class":"OC_App","type":"::"},{"file":"/snap/nextcloud/29929/htdocs/lib/base.php","line":986,"function":"loadApps","class":"OC_App","type":"::"},{"file":"/snap/nextcloud/29929/htdocs/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/snap/nextcloud/29929/nextcloud/extra-apps/groupfolders/lib/Versions/VersionsBackend.php","Line":38,"CustomMessage":"Could not boot files_trashbin: Interface \"OCA\\Files_Versions\\Versions\\IVersionBackend\" not found"},"id":"623443e8861fd"}

**Comment by scubamuc** [comment]
Hi, found cron stopped working too.
Quick workaround:
change task to "webcron" --> refresh page --> see green spot --> change back to "cron" --> refresh --> see green spot
Worked for me.

**Comment by Minnietheandroid** [comment]
@scubamuc 
Thanks very much.
I rolled the snap back to 22 which got me out of trouble and let me update the backup :)
I'll give this a try next.

**Comment by ph00lt0** [comment]
Yeah also not sure why this happend, it just didn't run any crons anymore after, I solved it just by running this occ command. Without changing it back and forward between webcron as suggested above.

**Comment by scubamuc** [comment]
@ph00lt0
admitted my workaround is a bit GUI... but I was away from server

**Comment by Minnietheandroid** [comment]
@scubamuc 
Thanks again for the tip, in my case it didn't solve the issue unfortunately.
Didn't seem to change anything at all, even after a wait and a bit of switching over.
Might be something more than just a cron problem, I really don't know.

@ph00lt0 @kyrofa 
Thanks for joining in :) 
I gave 'nextcloud.occ background:cron' a go and it just ran out the same error stuff as mentioned, but this time in the terminal. 
No idea what it's all about, but it seems pretty adamant about "OCA\Files_Versions\Versions\IVersionBackend" having a prroblem.
In the Nextcloud log this error tics over every second in live mode.

Anyway, no worries, rolled back again.
TBC.....

**Comment by kyrofa** [comment]
This sounds like https://github.com/nextcloud/groupfolders/issues/1812 .

**Comment by Minnietheandroid** [comment]
@kyrofa 
That was exactly what that was. Thank you.
I enabled 'Versions' did the upgrade and no problem.
Cron working fine.

Thanks for the help :)

**Comment by kyrofa** [comment]
Excellent! I'll go ahead and close this, then, thank you for reporting back.

**Comment by ph00lt0** [comment]
Intressting @Minnietheandroid I also have Group folders, which causes other issues, f.x. with the new backup app but that one I have not experienced in my logs.
