### ISSUE TITLE
backup nextcloud new apps

### ISSUE THREAD

**Issue by pacbidouandco** [nextcloud-snap/nextcloud-snap#2026]
hi, i m a french boy, sorry for me bad english

with the new apps : backup  in (23.0.2)

i have this : 

Erreur | PHP | Error: Undefined variable $user at /var/snap/nextcloud/29929/nextcloud/extra-apps/backup/lib/Service/ExternalFolderService.php#900 |   | 2022-03-19T19:04:03+0100
-- | -- | -- | -- | --
Erreur | PHP | Error: Undefined variable $user at /var/snap/nextcloud/29929/nextcloud/extra-apps/backup/lib/Service/ExternalFolderService.php#899

snap version : snap    2.54.4

**Comment by kyrofa** [comment]
This sounds like an issue with the backup app, have you considered logging an issue there?

**Comment by pacbidouandco** [comment]
not yet

**Comment by ph00lt0** [comment]
Issue is already open: https://github.com/nextcloud/backup/issues/152

**Comment by kyrofa** [comment]
Thank you @ph00lt0, I'll go ahead and close this, then.
