### ISSUE TITLE
enhancement for shibboleth authentication

### ISSUE THREAD

**Issue by ReimarBauer** [nextcloud-snap/nextcloud-snap#2027]
Hi there,
I want to enable shibboleth authentication
https://apps.nextcloud.com/apps/user_saml

For the DFN-AAI I would need to add into the config
https://doku.tid.dfn.de/de:shibsp:beispiele_nextcloud#grundlegende_konfiguration
```
# local Admin-Login nicht von weltweit!
<Location /index.php/login>
    Require ip xxx.xxx.xxx.xxx/xx
</Location>
# SAML/SSO-Login auf AAI konfigurieren
<Location /index.php/apps/user_saml/saml/login>
   AuthType           shibboleth
   ShibRequestSetting requireSession true
   <RequireAll>
     Require shib-attr  eppn        ~ ^.+$
     Require shib-attr  displayName ~ ^.+$
     Require shib-attr  mail        ~ ^.+@.+$
     Require valid-user
   </RequireAll> 
</Location>
```

How can I do this? The ssl.conf is readonly. Is there an option to add such attributes?

**Comment by kyrofa** [comment]
As you noticed, the apache conf is entirely read-only. I'm afraid this is by design-- the snap doesn't have a lot of knobs on purpose. I don't know much about shibboleth, but if you need the ability to alter the Apache config, I recommend installing Nextcloud using another method.

**Comment by ReimarBauer** [comment]
It's ok, I switched to an apache based installation.
