### ISSUE TITLE
[nextcloud] update to 22.2.6

### ISSUE THREAD

**Issue by pachulo** [nextcloud-snap/nextcloud-snap#2029]
https://nextcloud.com/blog/nextcloud-23-0-3-and-22-2-6-are-out-bringing-a-series-of-bug-fixes-and-improvements/

**Comment by pachulo** [comment]
By the way @kyrofa , can we get a `22` branch on the repo?
Thanks!

**Comment by kyrofa** [comment]
Done!

**Comment by pachulo** [comment]
Hi @kyrofa ! Is this in any channel?

**Comment by kyrofa** [comment]
Thanks for the ping @pachulo-- no, I forgot to hook that part up :stuck_out_tongue: . It's building now, keep an eye on 22/beta.

**Comment by kyrofa** [comment]
Promoted to stable.
