### ISSUE TITLE
Decryption Option

### ISSUE THREAD

**Issue by notgarrettt** [nextcloud-snap/nextcloud-snap#2033]
So I have been following these tutorials to install nextcloud: https://www.youtube.com/watch?v=g1mYxrxdJXM&list=WL&index=17  https://www.youtube.com/watch?v=_lOwOc_UPIs

I used sudo nextcloud.enable-https lets-encrypt
(cd /mnt/cloud)

which was working great and all until this popped up  "The certificate used to encrypt your connection to this website does not match the domain it was issued for. Attackers might try to steal sensitive information from you, such as passwords or credit cards." 

This showed up after having to remake the server cause of permission issues. 

How do I decrypt my server?

I think that will solve the issue.

**Comment by kyrofa** [comment]
> sudo nextcloud.enable-https lets-encrypt

This enables encryption, yes, but only for traffic from/to the instance. It doesn't encrypt any of the files on disk or anything.

> The certificate used to encrypt your connection to this website does not match the domain it was issued for.

That indicates that you've switched domain names from the one you were using when you ran the above command. Does that seem to line up? Worst case, you get new certificates for whatever domain name you're using, now.
