### ISSUE TITLE
Error on nexcloud server after update 

### ISSUE THREAD

**Issue by igherardia** [nextcloud-snap/nextcloud-snap#2040]
In log i have this issue after update to [Nextcloud Hub II] (23.0.3)

{"reqId":"e1BSzRJ4kQwPr31a3OVp","level":3,"time":"2022-04-17T11:06:13+00:00","remoteAddr":"","user":"--","app":"documentserver_community","method":"","url":"--","message":"Error while applying changes for document 3574198600","userAgent":"--","version":"23.0.3.2","exception":{"Exception":"OCA\\DocumentServer\\Document\\DocumentConversionException","Message":"Uncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"128\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"127\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"126\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"125\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"124\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"123\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"122\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"121\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"120\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"119\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"118\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"117\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"116\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"115\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"114\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"113\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"112\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"111\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"110\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"109\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"108\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"107\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"106\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"105\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"104\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"103\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"102\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"101\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"100\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"99\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"98\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"97\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"96\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"95\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"94\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"93\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"92\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"91\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"90\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"89\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"88\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"87\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"86\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"85\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"84\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"83\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"82\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"81\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"80\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"79\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"78\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"77\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"76\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"75\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"74\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"73\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"72\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"71\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"70\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"69\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"68\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"67\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"66\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"65\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"64\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"63\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"62\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"61\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"60\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"59\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"58\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"57\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"56\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"55\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"54\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"53\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"52\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"51\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"50\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"49\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"48\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"47\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"46\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"45\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"44\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"43\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"42\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"41\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"40\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"39\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"38\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"37\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"36\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"35\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"34\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"33\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"32\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"31\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"30\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"29\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"28\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"27\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"26\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"25\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"24\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"23\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"22\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"21\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"20\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"19\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"18\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"17\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"16\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"15\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"14\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"13\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"12\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"11\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"10\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"9\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"8\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"7\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"6\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"5\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"4\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"3\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"2\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"1\" /></result>\nUncaught TypeError: Cannot read property 'nC' of undefined\nDoctRenderer:<result><error index=\"0\" /></result>\n","Code":0,"Trace":[{"file":"/var/snap/nextcloud/30258/nextcloud/extra-apps/documentserver_community/lib/DocumentConverter.php","line":125,"function":"run","class":"OCA\\DocumentServer\\Document\\ConverterBinary","type":"->"},{"file":"/var/snap/nextcloud/30258/nextcloud/extra-apps/documentserver_community/lib/DocumentConverter.php","line":80,"function":"runCommand","class":"OCA\\DocumentServer\\DocumentConverter","type":"->"},{"file":"/var/snap/nextcloud/30258/nextcloud/extra-apps/documentserver_community/lib/Document/DocumentStore.php","line":156,"function":"saveChanges","class":"OCA\\DocumentServer\\DocumentConverter","type":"->"},{"file":"/var/snap/nextcloud/30258/nextcloud/extra-apps/documentserver_community/lib/LocalAppData.php","line":102,"function":"OCA\\DocumentServer\\Document\\{closure}","class":"OCA\\DocumentServer\\Document\\DocumentStore","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/snap/nextcloud/30258/nextcloud/extra-apps/documentserver_community/lib/Document/DocumentStore.php","line":176,"function":"getReadWriteLocalPath","class":"OCA\\DocumentServer\\LocalAppData","type":"->"},{"file":"/var/snap/nextcloud/30258/nextcloud/extra-apps/documentserver_community/lib/Document/SaveHandler.php","line":58,"function":"saveChanges","class":"OCA\\DocumentServer\\Document\\DocumentStore","type":"->"},{"file":"/var/snap/nextcloud/30258/nextcloud/extra-apps/documentserver_community/lib/BackgroundJob/Cleanup.php","line":71,"function":"flushChanges","class":"OCA\\DocumentServer\\Document\\SaveHandler","type":"->"},{"file":"/snap/nextcloud/30258/htdocs/lib/public/BackgroundJob/Job.php","line":79,"function":"run","class":"OCA\\DocumentServer\\BackgroundJob\\Cleanup","type":"->"},{"file":"/snap/nextcloud/30258/htdocs/cron.php","line":150,"function":"execute","class":"OCP\\BackgroundJob\\Job","type":"->"}],"File":"/var/snap/nextcloud/30258/nextcloud/extra-apps/documentserver_community/lib/Document/ConverterBinary.php","Line":66,"CustomMessage":"Error while applying changes for document 3574198600"},"id":"625bf87e9b9cd"}

**Comment by kyrofa** [comment]
Sounds like a bug with documentserver_community, I recommend logging an issue there.
