### ISSUE TITLE
Extremely slow performance after migration to a new machine

### ISSUE THREAD

**Issue by codyhazelwood** [nextcloud-snap/nextcloud-snap#2058]
#### Describe the bug

I recently moved my nextcloud instance to a KVM-based VM on a newer machine.  Since then, I have been unable to load user settings.  When attempting to I get a 504 Gateway Timeout.  In general, the nextcloud installation is _very_ slow and logging in occasionally times out.

The VM has 12 GB RAM and 4 CPU cores available to it, and it is running on an SSD.  My plex and docker installs in the same VM run fine, so I don't think it's the VM.

Watching `htop` while trying to load the user settings shows almost no load on the VM:
<img width="970" alt="Screen Shot 2022-04-29 at 9 50 02 PM" src="https://user-images.githubusercontent.com/2680679/166087913-b26df2ef-cdeb-4406-8af1-d0e0018ee1ff.png">

I've tried setting the PHP memory to 2 GB, but it doesn't appear to change anything.

Does anyone have any ideas of where I could start to look for the issue?

#### Logs

Sorry, [logs were too long to paste inline](https://github.com/nextcloud-snap/nextcloud-snap/files/8595561/logs.md.txt).

**Comment by kyrofa** [comment]
Huh, your logs look fine, and it doesn't make sense that it would be slow to respond unless SOMEthing is pegged (memory, CPU, or disk). What does your setup look like? Do you have a reverse proxy on this VM?

**Comment by codyhazelwood** [comment]
Yeah, I'm a little confused.  It's normally easy to see when there are resource constraints.  In this case, htop is showing almost no load on CPU / memory, and iotop is showing very little on disk.

I do have a reverse proxy running (NGINX via NGINX Proxy Manager in Docker).  I have tried bypassing the reverse proxy and hitting the snap directly with HTTP, and there's no difference.

The setup:
Host - Intel Atom C3558 (4 core @ 2.4 GHz), 32 GB ECC RAM, SSD boot drive and SSD VM drive running Truenas Scale.  
VM - 4 cores, 12 GB RAM, Ubuntu Server 20.04, Nginx Proxy Manager, Plex, Portainer, and Nextcloud-snap.

The host is running ZFS, and I have a single zvol for the VM's disk (ubuntu's boot and nextcloud data are on the same zvol).  The host shows 20 GB of memory free.

**Comment by scubamuc** [comment]
@codyhazelwood:

not sure if this will help. after moving nextcloud-snap from physical machine to virtual machine or container. similar issue after moving to LXC.

your log: 
`
Apr 23 03:00:43 dockerhost nextcloud.apache[1532039]: AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message `

try setting FQDN in `/etc/hosts` in VM

could look like this:
                                                                     
```
127.0.0.1       localhost
127.0.1.1       sub.domain.xyz SERVERNAME

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```
this kind of worked for me, but moved nextcloud-snap back to physical machine anyway.

**Comment by codyhazelwood** [comment]
@scubamuc Thanks for that!  I set the FQDN, and now everything is blazing fast.  I'm not sure why that mattered, especially when I was trying to use the IP address instead of DNS, but I'm glad it works now!

**Comment by kyrofa** [comment]
Thank you @scubamuc! Good find.

**Comment by scubamuc** [comment]
@codyhazelwood 
please let me revoke the comment about snap containers not playing well in VM's or LXC.

after this issue was resolved I moved my snap to LXC once again and did exactly what I had suggested for @codyhazelwood. Now my snap container within an LXC container is working like a charm. It seems the "physical machine snap" reacts differently to a "containered snap" and heavily relies on /etc/hosts FQDN setting.

**Comment by codyhazelwood** [comment]
Interesting, that would explain why I didn't need that setting before.  Glad to hear that it's working in containers for you!

I've been running it in a VM for about a week and a half now, and it's been great. I do have an issue with one iOS device not syncing with CalDAV properly, but I think it's something to do with other CalDAV issues I've had with Nextcloud and not the snap.

**Comment by scubamuc** [comment]
@codyhazelwood cloud you contact me per email? For interest sake I'd like to talk about your VM and compare notes.
https://github.com/scubamuc/scubas_nextcloud-snap-wiki/wiki
