### ISSUE TITLE
nextcloud-snap with alias 

### ISSUE THREAD

**Issue by chrismaster** [nextcloud-snap/nextcloud-snap#2061]
Is there a way to set an alias for the nextcloud-snap package?
So nextcloud is accesable @
https://myserver.org/nc
and not
https://myserver.org
so I can use some more snap packages?
Or is HAProxy the only way to go with snap or do it without snap?

**Comment by scubamuc** [comment]
this is possible using a reverse proxy (nginx, apache, haproxy etc.). 
other snaps requesting the same port as nextcloud-snap will not work and vice versa.
you can change the nextcloud-snap port, but will need a reverse proxy for SSL-encryption.
see: https://github.com/nextcloud-snap/nextcloud-snap/wiki/Putting-the-snap-behind-a-reverse-proxy
