### ISSUE TITLE
TLS renewal problem

### ISSUE THREAD

**Issue by merkleID** [nextcloud-snap/nextcloud-snap#2063]
#### Describe the bug
renewed TLS certs get refused.
Never a problem in the last 3 years, now 15 machines of mine with nextcloud reported this problem.

#### To Reproduce
nextcloud.enable-https custom ./cert.pem ./privkey.pem ./fullchain.pem

#### OS/snapd/snap version

snap list nextcloud:

Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  23.0.3snap1  30258  latest/stable  nextcloud✓  -

snap version:

snap    2.55.3
snapd   2.55.3
series  16
ubuntu  20.04
kernel  5.4.0-109-generic

#### Logs
[Thu May 05 14:01:38.832143 2022] [ssl:emerg] [pid 5873:tid 139841141802176] AH02565: Certificate and private key 127.0.1.1:443:0 from /var/snap/nextcloud/30258/certs/live/cert.pem and /var/snap/nextcloud/30258/certs/live/privkey.pem do not match
AH00016: Configuration Failed

**Comment by kyrofa** [comment]
> AH02565: Certificate and private key 127.0.1.1:443:0 from /var/snap/nextcloud/30258/certs/live/cert.pem and /var/snap/nextcloud/30258/certs/live/privkey.pem do not match

It looks like your public and private key are not actually a proper pair.

**Comment by kyrofa** [comment]
Is the output of the following two commands the same?

1. `openssl rsa -in privkey6.pem -noout -modulus`
2. `openssl x509 -in cert6.pem -noout -modulus`

**Comment by merkleID** [comment]
root@luca: openssl rsa -in privkey7.pem -noout -modulus > rsa.txt
root@luca: openssl rsa -in privkey7.pem -noout -modulus > x509.txt
root@luca:diff rsa.txt x509.txt

( no output) 

yes it's the same
I really do not understand why this sudden issue

**Comment by kyrofa** [comment]
Even better would be to use the `/var/snap/nextcloud/30258/certs/live/cert.pem` and `/var/snap/nextcloud/30258/certs/live/privkey.pem` paths.

**Comment by merkleID** [comment]
Thanks for your answers, I'll do.

I'm setting up a brand new VM with snap/nextcloud to test if the problem arises from the very beginning and using your suggestion.

**Comment by merkleID** [comment]
> Even better would be to use the `/var/snap/nextcloud/30258/certs/live/cert.pem` and `/var/snap/nextcloud/30258/certs/live/privkey.pem` paths.

Hi,
Set-up a brand new VM with snap/nextcloud, created certs through certbot, and this is what happens at first cert installation:

root@pemtest:/var/snap/nextcloud/current# nextcloud.enable-https custom /etc/letsencrypt/live/pemtest.merkle.id/cert.pem /etc/letsencrypt/live/pemtest.merkle.id/privkey.pem /etc/letsencrypt/live/pemtest.merkle.id/fullchain.pem
Installing custom certificate... done
Restarting apache... error
Certificates have been activated: using HTTPS only
Certificates appear self-signed: disabling HSTS
HTTP compression is disabled
AH00526: Syntax error on line 102 of /snap/nextcloud/30258/conf/ssl.conf:
SSLCertificateKeyFile: file '/var/snap/nextcloud/30258/certs/live/privkey.pem' does not exist or is empty

Never had this error before.

I then tried to use the /etc/letsencrypt/archive/pemtest.merkle.id/ certs but it didn't work either.

So I guess a bug with snap/nextcloud exists if the problem arises since the very first installation

Thanks,
Luca

**Comment by merkleID** [comment]
As I wrote, I tried at first attempt your suggestion that didn't work.

Then I tried copying the certs in the /var/snap/nextcloud/current and installing them as I always did on a total of 30 VMS I've been managing in the last 3 years and never had a problem.

This didn't work either.

Snap/Nextcloud has a problem with this, I don't understand what it takes to open a bug.

**Comment by kyrofa** [comment]
> I don't understand what it takes to open a bug.

You're doing exactly what it takes. I'm not trying to debate that there is an issue here, I'm trying to get to the bottom of it! I don't have the issue you're describing, so the best I can do is ask questions to figure out what's going on :) .

I think your approach is trying to set up a vanilla system is a good one, but you didn't do it properly because you were using directories the snap can't actually import certs from. Can you try that again from one of those four directories and see what happens?

**Comment by merkleID** [comment]
And I thank you for help and I appreciate it, but what more can I tell you other then the fact that this time the 'usual' procedure, on 22 VMs, has an issue? 

I always copied certs into the ../current/ directory and installing them with custom ./certs.blahblahblah, but.,.. it's not working


root@luca:~# snap list
Name       Version        Rev    Tracking       Publisher   Notes
core18     20220309       2344   latest/stable  canonical✓  base
core20     20220329       1434   latest/stable  canonical✓  base
lxd        4.0.9-8e2046b  22753  4.0/stable/…   canonical✓  -
nextcloud  23.0.3snap1    30258  latest/stable  nextcloud✓  -
snapd      2.55.3         15534  latest/stable  canonical✓  snapd

**Comment by kyrofa** [comment]
> [...] what more can I tell you other then the fact that this time the 'usual' procedure, on 22 VMs, has an issue?

You can continue to answer my questions :) .

Alright how about this. It looks like you've perhaps got a test domain that you were using when setting up a fresh install to test this. Any chance you would be comfortable sharing the cert/private key/chain you got for that domain with me so I can try this locally? You can do that via email instead of attaching them here if you like (email in bio).
