### ISSUE TITLE
How can I access Nextcloud when LAMP is already in place?

### ISSUE THREAD

**Issue by JorgeCarousel** [nextcloud-snap/nextcloud-snap#2064]
Hey guys,

I have a Ubuntu Server 20.04 already with Apache, PHP and MySQL in place, I ran snap install nextcloud, it said it has been installed, but I don't know how to access it, if I go to http://12.34.56.78/nextcloud it says it doesn't exist.

Thanks

**Comment by kyrofa** [comment]
If you already have Apache, I suspect it's already claiming port 80 if not both ports 80 and 443. You'll need to change one of them (check the [README](https://github.com/nextcloud-snap/nextcloud-snap#httphttps-port-configuration) for how to change the snap, if that's what you want to do).

Also, the snap doesn't use the /nextcloud subdir. You'll just be able to visit your IP directly once you have the port issue worked out.

**Comment by JorgeCarousel** [comment]
Well that sucks, are you telling me that it installs another instance of Apache, PHP and MySQL to the server?

**Comment by kyrofa** [comment]
Kinda-- it doesn't install any new packages, but it _includes_ everything it needs, including a web server, database, and PHP, all specifically configured for Nextcloud.
