### ISSUE TITLE
nextcloud: update to v24

### ISSUE THREAD

**Issue by Refhi** [nextcloud-snap/nextcloud-snap#2065]
My apologies if another place was better suited to talk about this

I'm very interested in v24. I know there's usualy a 1-month (or so) gap between general release and snap update.

Would you forsee any problem in this new version ? Is there a better place to follow the update work to the last version ? (thanks a lot to kyrofa btw)

Thanks

**Comment by kyrofa** [comment]
> My apologies if another place was better suited to talk about this

Nothing is off limits here assuming it's related to the Nextcloud snap-- welcome!

> I'm very interested in v24. I know there's usualy a 1-month (or so) gap between general release and snap update.

Yeah we generally wait until the first point release before upgrading to a new major release. If you take a look at [upstream Nextcloud's schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) that looks to be scheduled toward the end of May, so we're probably looking around that timeframe.

> Would you forsee any problem in this new version ? Is there a better place to follow the update work to the last version ?

You logged the first issue about it, so we'll use this to track the work on it. You've _made_ the best place to follow the work :) . I don't foresee any issues, and the last few major releases have gone pretty smoothly, but we still have hiccups every once in a while. Let's see if we can get some daily builds setup to start testing. [We need Nextcloud to do stuff first, though](https://twitter.com/rainveil/status/1522599402853912577).

**Comment by petre2dor** [comment]
quick update about next point release: 

> Maintenance releases of 24.0.1, 23.0.5 and 22.2.8 are coming this Thu[May 19th] and RCs for those are now available on our download server.

https://help.nextcloud.com/t/rcs-of-24-0-1-23-0-5-22-2-8/139148

**Comment by rafaeljin** [comment]
Given that 24.0.1 is released, is there an estimate of when can we get in snap?

**Comment by Pilzinsel64** [comment]
There is already a pull request here. It isn't touched since 12 days but probably soon. ^^
#2077 <- Track this

**Comment by Refhi** [comment]
Now on 24.0.1 on main !
Thanks !
