### ISSUE TITLE
nextcloud.enable.https initial working directory

### ISSUE THREAD

**Issue by KOZI1** [nextcloud-snap/nextcloud-snap#2066]
find: Failed to restore initial working directory: /home/ubuntu: Permission denied. When trying enable https via lets encrypt using sudo on new version ubuntu 22.04 on raspberry pi 4.

    $snap nextcloud 23.0.3

#### Logs

sudo nextcloud.enable-https lets-encrypt

Attempting to obtain certtificates... done
find: Failed to restore initial working directory: /home/ubuntu: Permission denied

**Comment by RowdyRagamuffin** [comment]
+1 issue for me as well. Same error as above. Running on latest stable.

**Comment by kyrofa** [comment]
That sounds like a snapd issue, [please log this over there](https://bugs.launchpad.net/snapd/+filebug).

**Comment by qniesz** [comment]
I was able to get around this with sudo -i then run the command
