### ISSUE TITLE
No webp/mp4 thumbnails

### ISSUE THREAD

**Issue by killiandt** [nextcloud-snap/nextcloud-snap#2069]
Hi,
I have no thumbnails for webp / mp4 files in my nextcloud.

![webp1](https://user-images.githubusercontent.com/104907952/168987176-14df7759-10da-40b2-90ac-38d0d697c32b.png)

This is a fresh installation on a dedicated nextcloud server.

```
root@nextcloud:~# snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  23.0.3snap1  30258  latest/stable  nextcloud✓  -
root@nextcloud:~# snap version
snap    2.55.3
snapd   2.55.3
series  16
ubuntu  21.10
kernel  5.13.0-41-generic
root@nextcloud:~# 
```
Debug script :
[nextcloud.log](https://github.com/nextcloud-snap/nextcloud-snap/files/8714304/nextcloud.log)

Thank for your help.
Have a good day.
Sincerely.
Killian

**Comment by NaXal** [comment]
Hello,

It is a known issue for NextCloud snap. It lacks the necessary php extension / module for the thumbnail generation. There is an already open issue regarding this. Refer here -> https://github.com/nextcloud-snap/nextcloud-snap/issues/1327

Thanks.
