### ISSUE TITLE
Nextcloud SNAP PHP modules Ubuntu 22.04

### ISSUE THREAD

**Issue by severalthings** [nextcloud-snap/nextcloud-snap#2070]
Hi,
I've posted this in https://forum.snapcraft.io/t/ubuntu-22-04-nextcloud-snap-php-modules/30034 and been asked to pubish it here. I do not know if it is a bug or just a lack of (my) knowledge.

I want to use the ldap-authentication-app. It comes with the snap and just needs to be activated. It needs the php-ldap-module.
I didn't succeed in connection to my ldap/Domain-Controller.
(Steps done: Activate the ldap-auth-app; go to settings/ldap-auth-module and configure it. I didn't make it to the second configuration TAB.)
The connection to the ldap-server was lost. The connection to the ldap-server was enabled via vpn. The nextcloud-server has no DNS-Published name yet.

I suspect that the php-ldap-module might be missing.
How can one check which php-modules are available in a snap?
And if one is missing, how can it be installed?

Thanks a lot

Martin 

martin@martin-VirtualBox:~$ snap list nextcloud
Name       Version      Revision  Tracking       Herausgeber  Hinweise
nextcloud  23.0.3snap1  30258     latest/stable  nextcloud✓   -
martin@martin-VirtualBox:~$ snap version
snap    2.55.3+22.04ubuntu1
snapd   2.55.3+22.04ubuntu1
series  16
ubuntu  22.04
kernel  5.15.0-30-generic
martin@martin-VirtualBox:~$ 

#### Logs

  },
        "user_ldap": {
            "background_sync_interval": "1800",
            "enabled": "yes",
            "installed_version": "1.13.1",
            "s01_lastChange": "1652812235",
            "s01has_memberof_filter_support": "0",
            "s01home_folder_naming_rule": "",
            "s01last_jpegPhoto_lookup": "0",
            "s01ldap_agent_password": "***REMOVED SENSITIVE VALUE***",
            "s01ldap_attributes_for_group_search": "",
            "s01ldap_attributes_for_user_search": "",
            "s01ldap_backup_host": "",
            "s01ldap_backup_port": "",
            "s01ldap_base": "dc=xxx,dc=local",
            "s01ldap_base_groups": "",
            "s01ldap_base_users": "",
            "s01ldap_cache_ttl": "600",
            "s01ldap_configuration_active": "0",
            "s01ldap_default_ppolicy_dn": "",
            "s01ldap_display_name": "displayName",
            "s01ldap_dn": "cn=Administrator,cn=Users,dc=xxx,dc=local",
            "s01ldap_dynamic_group_member_url": "",
            "s01ldap_email_attr": "",
            "s01ldap_experienced_admin": "0",
            "s01ldap_expert_username_attr": "",
            "s01ldap_expert_uuid_group_attr": "",
            "s01ldap_expert_uuid_user_attr": "",
            "s01ldap_ext_storage_home_attribute": "",
            "s01ldap_gid_number": "gidNumber",
            "s01ldap_group_display_name": "cn",
            "s01ldap_group_filter": "",
            "s01ldap_group_filter_mode": "0",
            "s01ldap_group_member_assoc_attribute": "",
            "s01ldap_groupfilter_groups": "",
            "s01ldap_groupfilter_objectclass": "",
            "s01ldap_host": "192.168.xx.xx“,
            "s01ldap_login_filter": "",
            "s01ldap_login_filter_mode": "0",
            "s01ldap_loginfilter_attributes": "",
            "s01ldap_loginfilter_email": "0",
            "s01ldap_loginfilter_username": "1",
            "s01ldap_matching_rule_in_chain_state": "unknown",
            "s01ldap_nested_groups": "0",
            "s01ldap_override_main_server": "",
            "s01ldap_paging_size": "500",
            "s01ldap_port": "389",
            "s01ldap_quota_attr": "",
            "s01ldap_quota_def": "",
            "s01ldap_tls": "0",
            "s01ldap_turn_off_cert_check": "0",
            "s01ldap_turn_on_pwd_change": "0",
            "s01ldap_user_avatar_rule": "default",
            "s01ldap_user_display_name_2": "",
            "s01ldap_user_filter_mode": "0",
            "s01ldap_userfilter_groups": "",
            "s01ldap_userfilter_objectclass": "",
            "s01ldap_userlist_filter": "",
            "s01use_memberof_to_detect_membership": "1",
            "types": "authentication"
        },

5.0 (Macintosh; Intel Mac OS X 10.15; rv:100.0) Gecko/20100101 Firefox/100.0","version":"23.0.3.2","exception":{"Exception":"Error","Message":"ldap_bind(): Unable to bind to server: Can't contact LDAP server at /snap/nextcloud/30258/htdocs/apps/user_ldap/lib/LDAP.php#338","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"function":"ldap_bind","args":["*** sensitive parameters replaced

Full log is attached
[snap_nc_log.odt](https://github.com/nextcloud-snap/nextcloud-snap/files/8715100/snap_nc_log.odt)

**Comment by scubamuc** [comment]
Your log:

`17T18:14:44+00:00","remoteAddr":"192.168.178.32","user":"martin","app":"user_ldap","method":"POST","url":"/index.php/apps/user_ldap/ajax/wizard.php","message":"Configuration Error (prefix s01): No LDAP Port given!","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:100.0)`

check your LDAP Port setting in NC-LDAP config, seems like LDAP-Server is not connecting
