### ISSUE TITLE
SQLSTATE[HY000] [1045] Access denied for user ‘nextcloud’@‘localhost’

### ISSUE THREAD

**Issue by EdG973GCS** [nextcloud-snap/nextcloud-snap#2071]
Hello !

#### Describe the bug
After snap update (23.0.2.1 29929 to 23.0.3.2 30258), DB connexion broken

#### OS/snapd/snap version
Fedora 35
$ snap list nextcloud
Name Version Rev Tracking Publisher Notes
core18 20220428 2409 latest/stable canonical✓ base
nextcloud 23.0.3snap1 30258 latest/stable nextcloud✓ -
snapd 2.55.3 15534 latest/stable canonical✓ snapd

#### Logs
An unhandled exception has been thrown:
Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user ‘nextcloud’@‘localhost’ (using password: YES) in /snap/nextcloud/30258/htdocs/lib/private/DB/Connection.php:87
Stack trace:
#0 /snap/nextcloud/30258/htdocs/3rdparty/doctrine/dbal/src/Connection.php(1519): OC\DB\Connection->connect()
#1 /snap/nextcloud/30258/htdocs/3rdparty/doctrine/dbal/src/Connection.php(1041): Doctrine\DBAL\Connection->getWrappedConnection()
#2 /snap/nextcloud/30258/htdocs/lib/private/DB/Connection.php(237): Doctrine\DBAL\Connection->executeQuery()
#3 /snap/nextcloud/30258/htdocs/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php(345): OC\DB\Connection->executeQuery()
#4 /snap/nextcloud/30258/htdocs/lib/private/DB/QueryBuilder/QueryBuilder.php(287): Doctrine\DBAL\Query\QueryBuilder->execute()
#5 /snap/nextcloud/30258/htdocs/lib/private/AppConfig.php(361): OC\DB\QueryBuilder\QueryBuilder->execute()
#6 /snap/nextcloud/30258/htdocs/lib/private/AppConfig.php(126): OC\AppConfig->loadConfigValues()
#7 /snap/nextcloud/30258/htdocs/lib/private/AppConfig.php(317): OC\AppConfig->getApps()
#8 /snap/nextcloud/30258/htdocs/lib/private/legacy/OC_App.php(972): OC\AppConfig->getValues()
#9 /snap/nextcloud/30258/htdocs/lib/private/Server.php(692): OC_App::getAppVersions()
#10 /snap/nextcloud/30258/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(160): OC\Server->OC{closure}()
#11 /snap/nextcloud/30258/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility{closure}()
#12 /snap/nextcloud/30258/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(127): Pimple\Container->offsetGet()
#13 /snap/nextcloud/30258/htdocs/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query()
#14 /snap/nextcloud/30258/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query()
#15 /snap/nextcloud/30258/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(182): OC\AppFramework\Utility\SimpleContainer->get()
#16 /snap/nextcloud/30258/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(160): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility{closure}()
#17 /snap/nextcloud/30258/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility{closure}()
#18 /snap/nextcloud/30258/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(127): Pimple\Container->offsetGet()
#19 /snap/nextcloud/30258/htdocs/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query()
#20 /snap/nextcloud/30258/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query()
#21 /snap/nextcloud/30258/htdocs/lib/private/Server.php(1079): OC\AppFramework\Utility\SimpleContainer->get()
#22 /snap/nextcloud/30258/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(160): OC\Server->OC{closure}()
#23 /snap/nextcloud/30258/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility{closure}()
#24 /snap/nextcloud/30258/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(127): Pimple\Container->offsetGet()
#25 /snap/nextcloud/30258/htdocs/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query()
#26 /snap/nextcloud/30258/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query()
#27 /snap/nextcloud/30258/htdocs/lib/private/Server.php(2040): OC\AppFramework\Utility\SimpleContainer->get()
#28 /snap/nextcloud/30258/htdocs/lib/private/Files/View.php(118): OC\Server->getLockingProvider()
#29 /snap/nextcloud/30258/htdocs/lib/private/Server.php(439): OC\Files\View->__construct()
#30 /snap/nextcloud/30258/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(160): OC\Server->OC{closure}()
#31 /snap/nextcloud/30258/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility{closure}()
#32 /snap/nextcloud/30258/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(127): Pimple\Container->offsetGet()
#33 /snap/nextcloud/30258/htdocs/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query()
#34 /snap/nextcloud/30258/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query()
#35 /snap/nextcloud/30258/htdocs/lib/private/Server.php(1403): OC\AppFramework\Utility\SimpleContainer->get()
#36 /snap/nextcloud/30258/htdocs/lib/base.php(594): OC\Server->boot()
#37 /snap/nextcloud/30258/htdocs/lib/base.php(1087): OC::init()
#38 /snap/nextcloud/30258/htdocs/console.php(48): require_once(’…’)
#39 /snap/nextcloud/30258/htdocs/occ(11): require_once(’…’)

#### temporary solutions
I finally performed a snap revert, and my Nextcloud instance immediatly came back to life !
$ sudo snap revert nextcloud

Something goes wrong with the snap upgrade from 23.0.2snap1 to 23.0.3snap1
Now I am not confident into this update ; there is something wrong with the database and must be investiguate.

*** Request 
May you help me ?

Best Regards

**Comment by EdG973GCS** [comment]
Hello

Help stil expected, may you ?

My NC is still 23.0.2snap1 29929
What will happen if it update to 23.0.3snap1 (or above) ?
Is this update should work ? Because last time (29929 to 30258), I suspected a powercut to be responsible for this mess.

Best Regards

**Comment by kyrofa** [comment]
>  Is this update should work ? Because last time (29929 to 30258), I suspected a powercut to be responsible for this mess.

Yes I agree. First of all, you did the right thing by reverting. You could try the update again, but honestly if I were you I'd just wait for the next update. Your snap will attempt to update again, and assuming you don't have any power issues at the same time again, it should go through just fine. We'll be spinning a new release soon.

**Comment by EdG973GCS** [comment]
Hello ! Thank you very much.
Ok let's wait for the new snap release soon.
