### ISSUE TITLE
Improving load times of the Nextcloud website

### ISSUE THREAD

**Issue by S0ulf3re** [nextcloud-snap/nextcloud-snap#2072]
Ok, so this may be a first world problem but the Nextcloud snap is taking about 5 seconds to load in safari regardless of weather im on my MacBook with home wifi or my iPhone 12 mini with 5G. How can I improve the load times? So far I've increased the PHP memory limit, what else can I do? Im using digital ocean as my provider.

**Comment by NaXal** [comment]
Hello,

I am not the expert here, so please wait for others to reply. However, as for basic general troubleshooting, kindly consider including few details,

1. Details of OS You are running
2. Anything extra of this VPS apart from Snap NextCloud?
3. Config of the VPS (like how many CPU, HDD or SSD, RAM?)
4. What's the network latency between VPS and your location?
5. Do you have any Reverse Proxy in front?
6. Are you using SSL, which one?
7. How is the load when you access the instance? Does it spike up very high?
8. Number of simultaneous active users of this NextCloud instance?
9. Are you on the latest snap version of NextCloud? Mention the version also.

Thanks.

**Comment by scubamuc** [comment]
@S0ulf3re 
see [here ](https://github.com/nextcloud-snap/nextcloud-snap/issues/2058#issuecomment-1114015479) this might do the trick for you too. 

Try setting FQDN in /etc/hosts in VM
