### ISSUE TITLE
nextcloud.occ Command not working....please help

### ISSUE THREAD

**Issue by zhdhasn** [nextcloud-snap/nextcloud-snap#2091]
I have successfully Install and configure on Ubuntu 20.04
I am trying to add Lets Encrypt SSL certificate, But command not working, please help me.

$ sudo nextcloud.occ config: system: get trusted_domains
sudo: nextcloud.occ: command not found

nextcloud:~$ sudo nextcloud.enable-https lets-encrypt
sudo: nextcloud.enable-https: command not found

UFW status:
Status: active

To                         Action      From
--                         ------      ----
22/tcp                        ALLOW       Anywhere
80,443/tcp                 ALLOW       Anywhere
22/tcp (v6)                 ALLOW       Anywhere (v6)
80,443/tcp (v6)          ALLOW       Anywhere (v6)

**Comment by scubamuc** [comment]
See `sudo nextcloud.occ list` for command list

try `sudo nextcloud.enable-https lets-encrypt` for encryption (typo `:`)

**Comment by zhdhasn** [comment]
nextcloud:~$ sudo nextcloud.occ list
[sudo] password for jahid:
sudo: nextcloud.occ: command not found

**Comment by kyrofa** [comment]
Try `sudo /snap/bin/nextcloud.occ`. Some systems don't add `/snap/bin` to the PATH.

**Comment by csidirop** [comment]
I had to switch to the root user for it to work. With sudo I had the same outcome as you.
