### ISSUE TITLE
Cron job does not run, It stops suddenly. No more mail notifications.

### ISSUE THREAD

**Issue by EdG973GCS** [nextcloud-snap/nextcloud-snap#2092]
Hello,

The cron job stops to work suddently on my NC instance.
I do not know where to look for logs.

![NC](https://user-images.githubusercontent.com/105791599/171651324-07cf99ae-72ce-4703-8df3-47f71be4394c.PNG)

#### OS/snapd/snap version
$ snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  23.0.2snap1  29929  latest/stable  nextcloud✓ 

and:

$ snap version
snap    2.55.3-2.fc35
snapd   2.55.3-2.fc35
series  16
fedora  35
kernel  5.17.7-200.fc35.x86_64

Nothing is really relevant in logs. I restart nextcloud-cron service manually (sudo systemctl restart "snap.nextcloud.nextcloud-cron.service")
But it does not change anything.
I did not receive mail notifications.

#### Logs
P-- Boot a8a67df99fba4832a6b7c91a9774ea74 --
mai 13 16:08:07 sft systemd[1]: Started Service for snap application nextcloud.nextcloud-cron.
mai 13 16:08:08 sft nextcloud.nextcloud-cron[754]: Waiting for Nextcloud config dir... done
mai 13 16:42:47 sft systemd[1]: Stopping Service for snap application nextcloud.nextcloud-cron...
mai 13 16:42:47 sft systemd[1]: snap.nextcloud.nextcloud-cron.service: Deactivated successfully.
mai 13 16:42:47 sft systemd[1]: Stopped Service for snap application nextcloud.nextcloud-cron.
mai 13 16:42:47 sft systemd[1]: snap.nextcloud.nextcloud-cron.service: Consumed 1.688s CPU time.
-- Boot 0da6fae3c7bd421bb4aafe71c6c34081 --
mai 16 08:48:11 sft systemd[1]: Started Service for snap application nextcloud.nextcloud-cron.
mai 16 08:48:24 sft nextcloud.nextcloud-cron[772]: Waiting for Nextcloud config dir... done
mai 16 10:57:58 sft systemd[1]: Stopping Service for snap application nextcloud.nextcloud-cron...
mai 16 10:57:58 sft systemd[1]: snap.nextcloud.nextcloud-cron.service: Deactivated successfully.
mai 16 10:57:58 sft systemd[1]: Stopped Service for snap application nextcloud.nextcloud-cron.
mai 16 10:57:58 sft systemd[1]: snap.nextcloud.nextcloud-cron.service: Consumed 6.742s CPU time.
mai 16 10:58:11 sft systemd[1]: Started Service for snap application nextcloud.nextcloud-cron.
mai 16 10:58:11 sft nextcloud.nextcloud-cron[439583]: Waiting for Nextcloud config dir... done
mai 16 11:18:22 sft systemd[1]: Stopping Service for snap application nextcloud.nextcloud-cron...
mai 16 11:18:22 sft systemd[1]: snap.nextcloud.nextcloud-cron.service: Deactivated successfully.
mai 16 11:18:22 sft systemd[1]: Stopped Service for snap application nextcloud.nextcloud-cron.
mai 16 11:18:22 sft systemd[1]: snap.nextcloud.nextcloud-cron.service: Consumed 23.243s CPU time.
-- Boot 656983f91ea546b39559c33cc0b2b278 --
mai 16 11:40:49 sft systemd[1]: Started Service for snap application nextcloud.nextcloud-cron.
mai 16 11:40:53 sft nextcloud.nextcloud-cron[754]: Waiting for Nextcloud config dir... done
-- Boot 168bdeb6726d49ed8c860d748f79c8dc --
juin 02 11:07:00 sft systemd[1]: Stopping Service for snap application nextcloud.nextcloud-cron...
juin 02 11:07:00 sft systemd[1]: snap.nextcloud.nextcloud-cron.service: Deactivated successfully.
juin 02 11:07:00 sft systemd[1]: Stopped Service for snap application nextcloud.nextcloud-cron.
juin 02 11:07:00 sft systemd[1]: snap.nextcloud.nextcloud-cron.service: Consumed 39min 49.766s CPU time.
juin 02 11:07:00 sft systemd[1]: Started Service for snap application nextcloud.nextcloud-cron.
juin 02 11:07:00 sft nextcloud.nextcloud-cron[2358319]: Waiting for Nextcloud config dir... done

May you help me to understand what is wrong with snap cron job ?

Best Regards

**Comment by scubamuc** [comment]
try the following:

### Nextcloud-snap, cron

#### Get cron configuration:

`sudo snap get nextcloud nextcloud.cron-interval`

#### Set cron configuration:
`
sudo snap set nextcloud nextcloud.cron-interval=5`

#### Restart cron:

`sudo snap restart nextcloud.nextcloud-cron`

### Cron fails after Update:

`sudo nextcloud.occ background:cron`
