### ISSUE TITLE
Synced folders named "bin" crashes and loops

### ISSUE THREAD

**Issue by bowanner** [nextcloud-snap/nextcloud-snap#2093]
#### Describe the bug
Generally Nextcloud - for ages! - seems to have problems with folders named "bin". Assume the folder structure on Nextcloud disk is "~/data/username/files/binn/xerces/bin" and all files on disk are present and correct in the leaf ~/bin folder.

When trying to open this  ~/bin leaf folder, in the web interface, the page crashes and I'm returned to the root folder. 100% repeatable. This goes for many variants for folder structures with a "bin" folder present!

Syncing via Windows desktop client always gives error for files in this "bin" folder. "Folder does not exist" is a common error in the desktop client.

I have run "sudo snap run nextcloud.occ files:scan --all" frequently without problems.

#### Screenshots
<img width="927" alt="image" src="https://user-images.githubusercontent.com/102598393/172053561-3222ea9a-9e48-4a73-b9e8-ee9350c96cb0.png">

Pressing the "bin" link returns to the root folder.

The file system:
<img width="454" alt="image" src="https://user-images.githubusercontent.com/102598393/172053777-03b82841-171f-4034-902d-678fe47eb2cf.png">

#### OS/snapd/snap version
Server: Windows 10 very latest update
Client: Windows 11 very latest update
Browsers: Chrome. Edge, Brave, whatever
Nextcloud Desktop Client: Version 3.5.1 (Windows) (but problem has been there for a year, at least)

    $ snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  23.0.5snap1  30874  latest/stable  nextcloud✓  -

    $ snap version
snap    2.55.5
snapd   2.55.5
series  16
ubuntu  20.04
kernel  5.4.0-113-generic

#### Logs

[log.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/8840111/log.txt)

**Comment by kyrofa** [comment]
That sounds like an upstream nextcloud bug-- mind logging it there? As soon as it's fixed upstream it'll be fixed here.

**Comment by bowanner** [comment]
Please see https://github.com/nextcloud/server/issues/33400

**Comment by bowanner** [comment]
Just wondering if I'm the only one that can't sync folders named "bin" ?
