### ISSUE TITLE
No access to OnlyOffice after update to 24.0.1snap1

### ISSUE THREAD

**Issue by hiroshisuga** [nextcloud-snap/nextcloud-snap#2104]
#### Describe the bug
In the weekend my server seems to have updated itself to 24.0.1snap1. After that I cannot open office documents anymore via OnlyOffice; it gives the message "ONLYOFFICE cannot be reached. Please contact admin".

I am using it behind a firewall just internally.

#### To Reproduce
1. After update to 24.0.1snap1, open an office document such as XXX.docx
2. See the error and cannot open the document.

#### Expected behavior
I can open the document as previously.

#### OS/snapd/snap version
Ubuntu 20, updated.

snap list nextcloud
nextcloud  24.0.1snap1  31033  latest/stable  nextcloud?  -

snap version
snap    2.56
snapd   2.56
series  16
ubuntu  20.04
kernel  5.13.0-48-generic

#### Logs
Please paste in the output from

**Comment by hiroshisuga** [comment]
The problem solved. After the update, the app Community Document Server has been marked "untested", thus I needed to manually activate the app again.

**Comment by roo-punch** [comment]
I've got this same exact issue. Can't see what you mean by being marked "untested". I tried uninstalling and re-installing onlyoffice. Any suggestions here?

**Comment by vawaver** [comment]
I have a similar problem.
I have made a clean installation NC 24.0.6 snap1 on Ubuntu server 22.04 and I am not able to connect the OnlyOffice app to Community Document Server 0.1.12.
