### ISSUE TITLE
Strict-Transport-Security not setup correctly in snap package

### ISSUE THREAD

**Issue by JorgeCarousel** [nextcloud-snap/nextcloud-snap#2105]
Hey guys, I just installed Ubuntu 22.04 and chose nextcloud to be installed with it via snap, I enabled SSL in nextcloud, but when I checked the Status, it gave me this:

The "Strict-Transport-Security" HTTP header is not set to at least "15552000" seconds. For enhanced security, it is recommended to enable HSTS as described in the [security tips ↗](https://docs.nextcloud.com/server/24/go.php?to=admin-security).

The document tells me to change the SSL configuration, but since this is in /snap/nextcloud/current/conf/ssl.conf it won't let me change it, is there a way to change it using the snap command or the occ command?

Thank you.

**Comment by kyrofa** [comment]
Hey @JorgeCarousel, thanks for the report.

> I enabled SSL in nextcloud [...].

How did you do that? The snap will enable HSTS automatically, but not if it's self-signed. Any chance you're doing that?

**Comment by JorgeCarousel** [comment]
Yes, it's Self-Signed since this is not for public access.

**Comment by kyrofa** [comment]
Then you can and should ignore that warning. HSTS is not compatible with self-signed certificates.
