### ISSUE TITLE
data stored multiple times(3) on VPS? - Help

### ISSUE THREAD

**Issue by rw227** [nextcloud-snap/nextcloud-snap#2106]
I have a 350GB Nextcloud VPS. 100GB of data. However in Settings:Admin:System it shows Storages:3 & Free Space 37GB
It appears the data is stored 3 times?  cannot see where the other copies are. 

Where do I look? What setting to change?

Thank you.

**Comment by Domiking001** [comment]
Hi
I actually host a Nextcloud Snap myself on 1 Drive and actually have 6 Storages. The data isn't stored multiple times, I guess it's the number of directories Nextcloud Snap uses to save your Data. Maybe the number of Storages is related to the number of Users on your Nextcloud? I don't know about that one

So no, your data isn't stored multiple times and the number of Storages is nothing to worry about.

**Comment by kyrofa** [comment]
> It appears the data is stored 3 times? cannot see where the other copies are.

Not by default anyway. If you want to share the output of the [issue debugging script](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Issue-Debugging-Scripts) so we can double-check your config, we can see if it's in a place where that might happen, but I'd be surprised.
