### ISSUE TITLE
Modification date error with Nextcloud Desktop

### ISSUE THREAD

**Issue by ph00lt0** [nextcloud-snap/nextcloud-snap#2107]
The wikipage now finally seems to provide mitigation:
https://github.com/nextcloud/desktop/wiki/How-to-fix-the-error-invalid-or-negative-modification-date

Could you provide some guidance on how to run this within nextcloud-snap? Also I am facing the issue that not every user will be be having an up to date client.

**Comment by kyrofa** [comment]
Oof, that script is pretty hard-coded for a traditional install, getting it working here will be non-trivial. Learning of you're affected is pretty easy, though. Run `sudo nextcloud.mysql-client nextcloud` to get into the database, then run the query they give there: `SELECT COUNT(*) FROM oc_filecache WHERE mtime < 86400;`.

**Comment by ph00lt0** [comment]
Well my instance defenitely is affected, for none of our users the sync works with updated clients and everyone is rolled back to desktop client 3.4.1 so that sync works

**Comment by ph00lt0** [comment]
Syncing doesn't do anything with up to date clients. It's really a mess and support for it from Nextclouds side is very disappointing.

**Comment by kyrofa** [comment]
Yeah they should have shipped a fix for this in Nextcloud itself, or as an app. You can probably rewrite these scripts using the snap's exposed mysql and occ commands, but it will take some experimentation to get it right. I'm sorry this happened to you :( .

**Comment by ph00lt0** [comment]
I am getting actually just 3 files when running that command. But no sync client works on the new version stangely also not for users not having those files

**Comment by ph00lt0** [comment]
![Screenshot 2022-06-17 at 6 14 30 PM](https://user-images.githubusercontent.com/15004290/174346623-76af4240-87fe-422c-8532-22693d240204.png)

The files actually show modified date like this. Changing the file didn't help so i removed them and reuploaded them. 

Now actually installed latest client seems to work on my user. Crazy that such thing couldn't be patched by the server or even the desktop client itself :/

**Comment by kyrofa** [comment]
To be clear: it could have been, they just didn't. Again, I'm really sorry-- that's no way to handle issues like this.
