### ISSUE TITLE
Lets Encrypt give error while setup SSL certificate.....Need help

### ISSUE THREAD

**Issue by zhdhasn** [nextcloud-snap/nextcloud-snap#2108]
$ sudo nextcloud.enable-https lets-encrypt

Have you met these requirements? (y/n) y
Please enter an email address (for urgent notices or key recovery): admin@example.com
Please enter your domain name(s) (space-separated): file.example.com

Attempting to obtain certificates... error running certbot:

Saving debug log to /var/snap/nextcloud/current/certs/certbot/logs/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for file.example.com
Using the webroot path /var/snap/nextcloud/current/certs/certbot for all unmatched domains.
Waiting for verification...
Challenge failed for domain file.example.com
http-01 challenge for file.example.com
Cleaning up challenges
Some challenges have failed.
IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: file.example.com
   Type:   unauthorized
   Detail: 172.16.200.30: Invalid response from
   http://file.example.com/index.php/login: "<!DOCTYPE html>
<html
   class=\"ng-csp\" data-placeholder-focus=\"false\" lang=\"en\"
   data-locale=\"en\" >
        <head
 data-requesttoken=\"HBgb"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.

Getting this error, Please help.

**Comment by scubamuc** [comment]
@zhdhasn ,

please check your domain... 

![grafik](https://user-images.githubusercontent.com/54933878/174756008-891e890c-1dfd-43c3-b3c4-0d709efc621d.png)
