### ISSUE TITLE
External Storage File Locked Exception error

### ISSUE THREAD

**Issue by usergitty** [nextcloud-snap/nextcloud-snap#2115]
#### Describe the bug
I've been having this issue where after some time, I realise that some apps that I have setup to sync over WebDAV to my external storage are failing. For example, Joplin. But this happens with any and all apps I have setup once it decides to go into lockdown and this is not just about syncing, the external storage just becomes unusable in all ways except for the fact that I can still upload new things to it using the nextcloud app but if I try to modify existing things or move thigs around it's not working. The only way to get things up and running again is to physically shutdown my device and boot up again. A reboot/restart of the OS doesn't do it. Another way I've found that fixes it is to physically disconnect my USB external storage and reconnect it. 

I saw in other threads that a scan could fix the issue. But this is the error I get once I run the following command, although it's not always the same exact output error:

`sudo nextcloud.occ files:scan --all`

```
Exception during scan: "files/4b2051ba4fbedcef303492dc291890fb"("local::/media/USER/EXTERNAL-STORAGE/::scanner::") is locked, existing lock on file: exclusive
#0 /snap/nextcloud/31033/htdocs/lib/private/Files/Storage/Common.php(758): OC\Lock\MemcacheLockingProvider->acquireLock()
#1 /snap/nextcloud/31033/htdocs/lib/private/Files/Storage/Wrapper/Wrapper.php(610): OC\Files\Storage\Common->acquireLock()
#2 /snap/nextcloud/31033/htdocs/lib/private/Files/Storage/Wrapper/Wrapper.php(610): OC\Files\Storage\Wrapper\Wrapper->acquireLock()
#3 /snap/nextcloud/31033/htdocs/lib/private/Files/Cache/Scanner.php(335): OC\Files\Storage\Wrapper\Wrapper->acquireLock()
#4 /snap/nextcloud/31033/htdocs/lib/private/Files/Utils/Scanner.php(256): OC\Files\Cache\Scanner->scan()
#5 /snap/nextcloud/31033/htdocs/apps/files/lib/Command/Scan.php(144): OC\Files\Utils\Scanner->scan()
#6 /snap/nextcloud/31033/htdocs/apps/files/lib/Command/Scan.php(200): OCA\Files\Command\Scan->scanFiles()
#7 /snap/nextcloud/31033/htdocs/3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\Scan->execute()
#8 /snap/nextcloud/31033/htdocs/core/Command/Base.php(168): Symfony\Component\Console\Command\Command->run()
#9 /snap/nextcloud/31033/htdocs/3rdparty/symfony/console/Application.php(1009): OC\Core\Command\Base->run()
#10 /snap/nextcloud/31033/htdocs/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#11 /snap/nextcloud/31033/htdocs/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#12 /snap/nextcloud/31033/htdocs/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#13 /snap/nextcloud/31033/htdocs/console.php(99): OC\Console\Application->run()
#14 /snap/nextcloud/31033/htdocs/occ(11): require_once('...')
#15 {main}
```

And here's another type of error that I sometimes get running the same scan command:

```
Exception during scan: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction
#0 /snap/nextcloud/31033/htdocs/3rdparty/doctrine/dbal/src/Connection.php(1780): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert()
#1 /snap/nextcloud/31033/htdocs/3rdparty/doctrine/dbal/src/Connection.php(1719): Doctrine\DBAL\Connection->handleDriverException()
#2 /snap/nextcloud/31033/htdocs/3rdparty/doctrine/dbal/src/Connection.php(1173): Doctrine\DBAL\Connection->convertExceptionDuringQuery()
#3 /snap/nextcloud/31033/htdocs/lib/private/DB/Connection.php(294): Doctrine\DBAL\Connection->executeStatement()
#4 /snap/nextcloud/31033/htdocs/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php(354): OC\DB\Connection->executeStatement()
#5 /snap/nextcloud/31033/htdocs/lib/private/DB/QueryBuilder/QueryBuilder.php(281): Doctrine\DBAL\Query\QueryBuilder->execute()
#6 /snap/nextcloud/31033/htdocs/lib/private/Files/Cache/Cache.php(380): OC\DB\QueryBuilder\QueryBuilder->execute()
#7 /snap/nextcloud/31033/htdocs/lib/private/Files/Cache/Wrapper/CacheWrapper.php(145): OC\Files\Cache\Cache->update()
#8 /snap/nextcloud/31033/htdocs/lib/private/Files/Cache/Scanner.php(401): OC\Files\Cache\Wrapper\CacheWrapper->update()
#9 /snap/nextcloud/31033/htdocs/lib/private/Files/Cache/Scanner.php(393): OC\Files\Cache\Scanner->scanChildren()
#10 /snap/nextcloud/31033/htdocs/lib/private/Files/Cache/Scanner.php(342): OC\Files\Cache\Scanner->scanChildren()
#11 /snap/nextcloud/31033/htdocs/lib/private/Files/Utils/Scanner.php(256): OC\Files\Cache\Scanner->scan()
#12 /snap/nextcloud/31033/htdocs/apps/files/lib/Command/Scan.php(144): OC\Files\Utils\Scanner->scan()
#13 /snap/nextcloud/31033/htdocs/apps/files/lib/Command/Scan.php(200): OCA\Files\Command\Scan->scanFiles()
#14 /snap/nextcloud/31033/htdocs/3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\Scan->execute()
#15 /snap/nextcloud/31033/htdocs/core/Command/Base.php(168): Symfony\Component\Console\Command\Command->run()
#16 /snap/nextcloud/31033/htdocs/3rdparty/symfony/console/Application.php(1009): OC\Core\Command\Base->run()
#17 /snap/nextcloud/31033/htdocs/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#18 /snap/nextcloud/31033/htdocs/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#19 /snap/nextcloud/31033/htdocs/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#20 /snap/nextcloud/31033/htdocs/console.php(99): OC\Console\Application->run()
#21 /snap/nextcloud/31033/htdocs/occ(11): require_once('...')
#22 {main}
```

#### To Reproduce
1. Run my nextcloud instance from a fresh boot of the OS and after a couple of days realise that things are not working which I guess it's after a few things have synced/ transferred files.

#### Expected behavior
For my nextcloud instance to stay online and working without things getting locked and me needing to physically access my device to shutdown or replug my storage. 

#### OS/snapd/snap version

    $ snap list nextcloud

```
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  24.0.1snap1  31033  latest/stable  nextcloud✓  -
```

and:

    $ snap version

```
snap    2.56
snapd   2.56
series  16
ubuntu  20.04
kernel  5.18.8-051808-generic
```

**Comment by scubamuc** [comment]
i'm not sure if your issue is a nextcloud-snap issue... you could try disabling file locking and see if that works for you...
edit config.php, disable file lock:
`sudo nano /var/snap/nextcloud/current/nextcloud/config/config.php`

if your external storage is HDD, it sounds more like OS or hardware issue see: 
https://askubuntu.com/questions/546062/my-external-hard-drive-keeps-unmounting-and-remounting-itself
https://unix.stackexchange.com/questions/172282/how-to-prevent-automatic-external-hard-drive-unmount

**Comment by usergitty** [comment]
@scubamuc  I'm not sure what I need to do exactly to disable file lock. I don't see anything in the config file.

Regarding the links you shared, I don't think it applies to me because my drive does not get unmounted. Whenever the error occurs, the drive is still mounted and I can access it with Files app.

**Comment by scubamuc** [comment]
see here https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/files_locking_transactional.html

edit config.php, disable file lock:
sudo nano /var/snap/nextcloud/current/nextcloud/config/config.php

**Comment by usergitty** [comment]
@scubamuc  This is what I have in my config file:

```
 'memcache.locking' => '\\OC\\Memcache\\Redis',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => '/tmp/sockets/redis.sock',
    'port' => 0,
  ),
```

Should I just add a new line above it like this?:

`'filelocking.enabled' => false,`

**Comment by scubamuc** [comment]
that should do it, but please note, since this is not a nextcloud-snap issue and i'm not a nextcloud supporter, this a personal suggestion!
please close issue when done

**Comment by usergitty** [comment]
Still facing issues even after disabling file locking.
It happened again today where I noticed things are not syncing. It might not be a nextcloud snap issue like to mentioned but I don't know what it is. When this happens, I can still go to my nextcloud and for example manually upload a file to my external drive or create a new file/folder. Those things still work but for some reason anything sync related won't work. But I also noticed that I can't "unmount" the external drive when this happens... I get error that disk is busy even though I fully stopped nextcloud instance. I don't know what else to do at this point

**Comment by scubamuc** [comment]
please show permissions for external storage

**Comment by scubamuc** [comment]
permissions for data must be root only
`sudo chown -R root:root /media/nextcloud/data`

see [here](https://github.com/nextcloud-snap/nextcloud-snap/issues/2169)

**Comment by usergitty** [comment]
@scubamuc I have been testing things for a while after changing the permissions as you mentioned and I'm still facing the same issue. I've even completely reinstalled a fresh ubuntu just to make sure. 

As I've mentioned, everything works fine at first but then the external drive seems to be inaccessbile to nextcloud after some time, usually after a bunch of things have been automatically uploaded either through the Nextcloud android app and/or WebDAV. 

Running the scan command:
`sudo nextcloud.occ files:scan --all`
it now just keeps loading and never shows anything so I just have to eventually force close terminal.

My External drive is mounted at: /media/user/drive and has root permissions. 

The external drive is accessible from the Files app in Ubuntu and if I try to unmount once it's in this state, I get the following error in the Disks app: 

**Error unmounting filesystem unmounting /dev/dm-0: target is busy (udisks-error-quark, 14)**

The only way to fix things is to physically unplug the external drive and plug it back in. Even rebooting the OS doesn't work because it seems like the drive is holding it back since it's "busy".

Every day or 2 I have to unplug and plug back in my drive to get things going again. Really frustrating. If you have any ideas at all, maybe a workaround to keep using my external drive, I would really appreciate your help.

**Comment by scubamuc** [comment]
try mounting the removable drive to ` /media/drive ` or ` /mnt/drive ` in ` fstab `. that way only root can mount or unmount and only root has permissions.

**be sure to enable removable media for snap**
` sudo snap connect nextcloud:removable-media `

do you experience any issue when up-downloading using webDAV from command-line or file-manager? 

- in Files address-bar: ` davs://user@nextcloud.domain.xyz `
- in command-line: try ` rclone ` 

can you read write in browser interface alright? 

if this is only an issue when syncing via webDAV from application (Joplin) or client (Android), not sure this is a nextcloud-snap issue. 

@kyrofa do you have any ideas?

**Comment by usergitty** [comment]
@scubamuc I've been testing things again with your recommendations and at first, it seemed like things were better when I changed the mount point to /media/drive (I did that in the Disks app by choosing the "Edit Mount Options...") , it lasted longer than usual before things got locked again. This time, I tested mostly by only allowing the auto-upload from the nextcloud app on my phone. So no WebDAV sync but same thing happened eventually. 

I tried using WebDAV in the files app as you mentioned when things are locked and I can't access it. But read and write in the browser interface works fine. I can access the external drive there and create folders etc. But no more uploads from the app or WebDAV sync. I still get the same error when trying to unmount the external drive so I have to unplug it like before.

**Comment by scubamuc** [comment]
@usergitty i have no further ideas or suggestions... sorry

@kyrofa do you have any ideas?

**Comment by usergitty** [comment]
@scubamuc  - I'm about to give up for good but one last thing, do you know if it could be the fact that my external drive is encrypted (LUKS Encryption)? I'm aware that the drive needs to be unlocked with the password and I always do that first thing but could it still be the cause of these issues? 

Also, in the mount options, does it matter what I choose under "Identify As" ?  Any other settings there that I could play with?

**Comment by scubamuc** [comment]
@usergitty 
aaaarrgggh... the encrypted drive is definitely your bug-source! maybe you hadn't mentioned it or I over read your mention?
I would suggest disabling encryption on the external drive and to encrypt your data using Nextcloud encryption from within Nextcloud. that way Nextcloud will handle decryption for you.
I'm glad we've finally debugged this issue.
 don't give up... you'll get it right eventually :-)

**Comment by usergitty** [comment]
@scubamuc - I had not mentioned the encryption, I had no idea it would matter lol. 

I remember looking into Nextcloud encryption and it seemed to be a little inconvenient. By encrypting the drive itself, I'm still able to directly access the files without going through nextcloud if needed. With the Nextcloud encryption, I just feel like it will cause complications down the road trying to access the files and for syncing with 3rd party apps etc. Not sure though so for now I'm just gonna format my drive and test it out for a few days without encryption to see if that fixes things. I will follow up to close the issue if all goes well. Thanks for you help!
