### ISSUE TITLE
Ability to change session.cache_limiter // video buffering improvements

### ISSUE THREAD

**Issue by hitindags** [nextcloud-snap/nextcloud-snap#2116]
Please enable the PHP option to set "session.cache_limiter = public" as I heard that it will improve choppy playback of videos in the browser.

**Comment by pachulo** [comment]
Hi @hitindags ! Thanks for this, but do you have any link with information about that PHP option improving the video playback?

**Comment by hitindags** [comment]
somebody posted it here: https://help.nextcloud.com/t/streaming-hd-videoclips-buffering-takes-ages-while-downloading-the-entire-file-is-quick/50072/20

and here here are also other options like nginx and a section about buffering in the nextcloud config mentioned: https://github.com/nextcloud/files_videoplayer/issues/49

As of now, buffering is not working in my snap.

**Comment by Anisotropic** [comment]
Any updates on this?

**Comment by hitindags** [comment]
Thank you for taking care of this! How does it work now? Just change the setting in the php config?
