### ISSUE TITLE
well-known/caldav

### ISSUE THREAD

**Issue by gerovichev** [nextcloud-snap/nextcloud-snap#2118]
#### Describe the bug
How can be edited below in the snap installation?
In the full installation ".htaccess" should be updated

#### To Reproduce
1. Go to 'Settings'
2. Click on 'Overview'
3. Scroll down to 'Security & setup warnings'

#### Expected behavior
Should not be warnings.

#### Screenshots
There are some warnings regarding your setup.
Your web server is not properly set up to resolve "/.well-known/caldav". Further information can be found in the [documentation ↗](https://docs.nextcloud.com/server/24/go.php?to=admin-setup-well-known-URL).
Your web server is not properly set up to resolve "/.well-known/carddav". Further information can be found in the [documentation ↗](https://docs.nextcloud.com/server/24/go.php?to=admin-setup-well-known-URL).

#### OS/snapd/snap version
What OS and version are you running? nextcloud  24.0.1snap1  31037  latest/stable  nextcloud

**Comment by scubamuc** [comment]
please see notes in the last section of [Nextcloud and Collabora behind HAProxy](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Nextcloud-and-Collabora-behind-HAProxy/79ac69592512ba23f3bf24e175684cb8fd362bc2)

**Comment by gerovichev** [comment]
> please see notes in the last section of [Nextcloud and Collabora behind HAProxy](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Nextcloud-and-Collabora-behind-HAProxy/79ac69592512ba23f3bf24e175684cb8fd362bc2)

Thank you

**Comment by ClassickTech** [comment]
This is still an issue because it will not allow iOS to connect to CalDAV and CardAv. How to fix the well-known issues?

**Comment by scubamuc** [comment]
@ClassickTech as this is a Nextcloud problem experienced by some iOS users, please create an issue with the Nextcloud folks.
