### ISSUE TITLE
How to get Netxtcloud Office to work?

### ISSUE THREAD

**Issue by JorgeCarousel** [nextcloud-snap/nextcloud-snap#2130]
Hey guys,

I installed Nextcloud using snap, I installed the default Apps to it to see how the Office worked, but when i went to check the standard docx file in Documents, all I see is this (a loading page with nothing showing up), how can I get this to work?:

![image](https://user-images.githubusercontent.com/103138304/179816874-014b4755-8f9a-4d64-9f69-178950368e02.png)

I'm using Ubuntu Linux Server 22.04

**Comment by kyrofa** [comment]
I'm sorry, we can't offer support for each individual app, you'll need to address this question to the apps themselves. We don't know much about them, especially the complex beasts that are the office apps.

**Comment by scubamuc** [comment]
@JorgeCarousel, see [CODE & Nextcloud Office configuration](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-CODE-and-Nextcloud-office-for-Nextcloud-snap)
