### ISSUE TITLE
Theming changes not possible with HTTP error 412 (Precondition failed)

### ISSUE THREAD

**Issue by asmw** [nextcloud-snap/nextcloud-snap#2133]
#### Describe the bug
I migrated my snap-installed nextcloud from one VM to another using nextcloud.export/nextcloud.import.
Apart from the theme, everything seems to work.
If I try to change any aspect of the theme (color, upload an image, change the name) the request fails with an HTTP error 412.
A spinner and the text 'Saving...' is shown indefinitely.

#### To Reproduce
1. Go to Settings -> Theming
2. Click on anything that would change the theme
4. See error in the 'Network' tab of the developer tools

#### Expected behavior
The theme can be changed

#### OS/snapd/snap version

The current snap on Ubuntu 22.04 LTS

# snap version
snap    2.55.3+22.04
snapd   2.55.3+22.04
series  16
ubuntu  22.04
kernel  5.15.0-41-generic

# snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  24.0.1snap1  31033  latest/stable  nextcloud✓  -

#### Logs
Cannot paste here, the comment gets too long

**Comment by asmw** [comment]
Note that other settings can be changed, i.e. the mail settings worked

**Comment by scubamuc** [comment]
your logs:
```
Jul 20 19:37:14 cloudia nextcloud.nextcloud-fixer[221441]: Nextcloud is in maintenance mode, hence the database isn't accessible.
Jul 20 19:37:14 cloudia nextcloud.nextcloud-fixer[221441]: Cannot perform any command except 'maintenance:mode --off'
Jul 20 19:37:14 cloudia nextcloud.nextcloud-fixer[2214]: done
Jul 20 19:37:14 cloudia nextcloud.nextcloud-fixer[221450]: run-parts: executing /snap/nextcloud/31033/fixes/fresh-install/1_disable-theming.sh
Jul 20 19:37:14 cloudia nextcloud.nextcloud-fixer[221451]: Disabling theming by default...
Jul 20 19:37:14 cloudia nextcloud.nextcloud-fixer[221451]: done
Jul 20 19:37:14 cloudia nextcloud.nextcloud-fixer[221450]: run-parts: executing /snap/nextcloud/31033/fixes/fresh-install/2_add-missing-indices.sh
Jul 20 19:37:14 cloudia nextcloud.nextcloud-fixer[221588]: Nextcloud is in maintenance mode, hence the database isn't accessible.
Jul 20 19:37:14 cloudia nextcloud.nextcloud-fixer[221588]: Cannot perform any command except 'maintenance:mode --off'
Jul 20 19:37:14 cloudia nextcloud.nextcloud-fixer[221588]: Check indices of the share table.

```

Install missing indices...

```
Jul 20 19:37:17 cloudia nextcloud.nextcloud-fixer[221450]: run-parts: executing /snap/nextcloud/31033/fixes/fresh-install/3_add-missing-columns.sh
Jul 20 19:37:17 cloudia nextcloud.nextcloud-fixer[221662]: Nextcloud is in maintenance mode, hence the database isn't accessible.
Jul 20 19:37:17 cloudia nextcloud.nextcloud-fixer[221662]: Cannot perform any command except 'maintenance:mode --off'
Jul 20 19:37:17 cloudia nextcloud.nextcloud-fixer[221662]: Check columns of the comments table.
Jul 20 19:37:17 cloudia nextcloud.nextcloud-fixer[221662]: Done.
Jul 20 19:37:17 cloudia nextcloud.nextcloud-fixer[221450]: run-parts: executing /snap/nextcloud/31033/fixes/fresh-install/4_convert-filecache-bigint.sh
Jul 20 19:37:18 cloudia nextcloud.nextcloud-fixer[221733]: Nextcloud is in maintenance mode, hence the database isn't accessible.
Jul 20 19:37:18 cloudia nextcloud.nextcloud-fixer[221733]: Cannot perform any command except 'maintenance:mode --off'
```

see `sudo nextcloud.occ list` for command list and execute `filecache-bigint` and `fix-missing-columns`

**Comment by scubamuc** [comment]
see alternative for moving nextcloud-snap:

> currently I'm using an alternative "snap-backup" skript for this:
> 
> snap stop 'nextcloud'
> snap save 'nextcloud'
> snap start 'nextcloud'
> find snapshot in "/var/lib/snapd/snapshots" and move to external media
> find /var/lib/snapd/snapshots/ -name "*.zip" -exec mv '{}' /media/BACKUP/ \;
> find and remove older snapshots
> find /var/lib/snapd/snapshots/ -name "*.zip" -mtime +30 -exec rm -f {} \;
> 
> this works fine in weekly automatic (cronjob as root) mode and has the added convenience of easy snap transfer to different server when needed. thus always 4 weeks of snap-backup on external medium.
> 
>     cronjob daily/weekly/monthly, reduced downtime

**Comment by asmw** [comment]
I have run 
nextcloud.occ db:add-missing-indices and db:convert-filecache-bigint

The error persists.
I am pretty sure the timestamps on those errors are _before_ I imported the exported data

**Comment by scubamuc** [comment]
may have misread your logs... timestamp irrelevant
check if `filecache` and `bigint` error remains and fix
use alternative export/import method if error persists

**Comment by asmw** [comment]
@scubamuc thanks for helping. I noticed, that in the fresh-install fixes, the theming app is explicitly disbaled.

I could fix the problem by running `nextcloud.occ app:enable theming`

Weird symptoms. Maybe the theming option should mention not be available in that case?

**Comment by kyrofa** [comment]
> I noticed, that in the fresh-install fixes, the theming app is explicitly disabled.

That's true, it's because it constantly warns about not having imagick installed and provides a poor experience. However, it's totally valid to enable it and live without the features imagick gives you (i.e. favicons). Definitely supported, so don't take what the fresh-install fixes do that way.
