### ISSUE TITLE
it's not encrypt....

### ISSUE THREAD

**Issue by wangyifan349** [nextcloud-snap/nextcloud-snap#2140]
I started the end-to-end encryption module and hung it on the external storage. But neither webdav nor local external storage, the files are not encrypted. But the files located at /var/snap/nextcloud/common/nextcloud/data are encrypted.

journal error file

Error: Trying  to access array offset on value of type bool at  /snap/nextcloud/31033/htdocs/lib/private/Files/Storage/Wrapper/Encryption.php#431/snap/nextcloud/31033/htdocs/lib/private/Files/Storage/Wrapper/Encryption.php - line 431: OC\Log\ErrorHandler::onError()/snap/nextcloud/31033/htdocs/lib/private/Files/Storage/Wrapper/Wrapper.php - line 301: OC\Files\Storage\Wrapper\Encryption->fopen()/snap/nextcloud/31033/htdocs/lib/private/Files/Storage/Wrapper/Encryption.php - line 782: OC\Files\Storage\Wrapper\Wrapper->fopen()/snap/nextcloud/31033/htdocs/lib/private/Files/Storage/Wrapper/Encryption.php - line 639: OC\Files\Storage\Wrapper\Encryption->copyBetweenStorage()/snap/nextcloud/31033/htdocs/lib/private/Files/Storage/Wrapper/Wrapper.php - line 595: OC\Files\Storage\Wrapper\Encryption->moveFromStorage()/snap/nextcloud/31033/htdocs/apps/files_trashbin/lib/Storage.php - line 239: OC\Files\Storage\Wrapper\Wrapper->moveFromStorage()/snap/nextcloud/31033/htdocs/apps/files_trashbin/lib/Trashbin.php - line 323: OCA\Files_Trashbin\Storage->moveFromStorage()/snap/nextcloud/31033/htdocs/apps/files_trashbin/lib/Trash/LegacyTrashBackend.php - line 107: OCA\Files_Trashbin\Trashbin::move2trash()/snap/nextcloud/31033/htdocs/apps/files_trashbin/lib/Trash/TrashManager.php - line 102: OCA\Files_Trashbin\Trash\LegacyTrashBackend->moveToTrash()/snap/nextcloud/31033/htdocs/apps/files_trashbin/lib/Storage.php - line 202: OCA\Files_Trashbin\Trash\TrashManager->moveToTrash()/snap/nextcloud/31033/htdocs/apps/files_trashbin/lib/Storage.php - line 102: OCA\Files_Trashbin\Storage->doDelete()/snap/nextcloud/31033/htdocs/lib/private/Files/View.php - line 1177: OCA\Files_Trashbin\Storage->unlink()/snap/nextcloud/31033/htdocs/lib/private/Files/View.php - line 733: OC\Files\View->basicOperation()/snap/nextcloud/31033/htdocs/apps/dav/lib/Connector/Sabre/File.php - line 512: OC\Files\View->unlink()/snap/nextcloud/31033/htdocs/3rdparty/sabre/dav/lib/DAV/Tree.php - line 179: OCA\DAV\Connector\Sabre\File->delete()/snap/nextcloud/31033/htdocs/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 281: Sabre\DAV\Tree->delete()/snap/nextcloud/31033/htdocs/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89: Sabre\DAV\CorePlugin->httpDelete()/snap/nextcloud/31033/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php - line 472: Sabre\DAV\Server->emit()/snap/nextcloud/31033/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php - line 253: Sabre\DAV\Server->invokeMethod()/snap/nextcloud/31033/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php - line 321: Sabre\DAV\Server->start()/snap/nextcloud/31033/htdocs/apps/dav/lib/Server.php - line 352: Sabre\DAV\Server->exec()/snap/nextcloud/31033/htdocs/apps/dav/appinfo/v2/remote.php - line 35: OCA\DAV\Server->exec()/snap/nextcloud/31033/htdocs/remote.php - line 166: require_once("/snap/nextc ... p") |

**Comment by wangyifan349** [comment]
[PHP] 错误: Error: Trying to access array offset on value of type bool at /snap/nextcloud/31033/htdocs/lib/private/Files/Storage/Wrapper/Encryption.php#431 at <<closure>>

 0. /snap/nextcloud/31033/htdocs/lib/private/Files/Storage/Wrapper/Encryption.php line 431
    OC\Log\ErrorHandler::onError()
 1. /snap/nextcloud/31033/htdocs/lib/private/Files/Storage/Wrapper/Wrapper.php line 301
    OC\Files\Storage\Wrapper\Encryption->fopen()
 2. /snap/nextcloud/31033/htdocs/lib/private/Files/Storage/Wrapper/Encryption.php line 782
    OC\Files\Storage\Wrapper\Wrapper->fopen()
 3. /snap/nextcloud/31033/htdocs/lib/private/Files/Storage/Wrapper/Encryption.php line 639
    OC\Files\Storage\Wrapper\Encryption->copyBetweenStorage()
 4. /snap/nextcloud/31033/htdocs/lib/private/Files/Storage/Wrapper/Wrapper.php line 595
    OC\Files\Storage\Wrapper\Encryption->moveFromStorage()
 5. /snap/nextcloud/31033/htdocs/apps/files_trashbin/lib/Storage.php line 239
    OC\Files\Storage\Wrapper\Wrapper->moveFromStorage()
 6. /snap/nextcloud/31033/htdocs/apps/files_trashbin/lib/Trashbin.php line 323
    OCA\Files_Trashbin\Storage->moveFromStorage()
 7. /snap/nextcloud/31033/htdocs/apps/files_trashbin/lib/Trash/LegacyTrashBackend.php line 107
    OCA\Files_Trashbin\Trashbin::move2trash()
 8. /snap/nextcloud/31033/htdocs/apps/files_trashbin/lib/Trash/TrashManager.php line 102
    OCA\Files_Trashbin\Trash\LegacyTrashBackend->moveToTrash()
 9. /snap/nextcloud/31033/htdocs/apps/files_trashbin/lib/Storage.php line 202
    OCA\Files_Trashbin\Trash\TrashManager->moveToTrash()
10. /snap/nextcloud/31033/htdocs/apps/files_trashbin/lib/Storage.php line 102
    OCA\Files_Trashbin\Storage->doDelete()
11. /snap/nextcloud/31033/htdocs/lib/private/Files/View.php line 1177
    OCA\Files_Trashbin\Storage->unlink()
12. /snap/nextcloud/31033/htdocs/lib/private/Files/View.php line 733
    OC\Files\View->basicOperation()
13. /snap/nextcloud/31033/htdocs/apps/dav/lib/Connector/Sabre/File.php line 512
    OC\Files\View->unlink()
14. /snap/nextcloud/31033/htdocs/3rdparty/sabre/dav/lib/DAV/Tree.php line 179
    OCA\DAV\Connector\Sabre\File->delete()
15. /snap/nextcloud/31033/htdocs/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 281
    Sabre\DAV\Tree->delete()
16. /snap/nextcloud/31033/htdocs/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpDelete()
17. /snap/nextcloud/31033/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php line 472
    Sabre\DAV\Server->emit()
18. /snap/nextcloud/31033/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php line 253
    Sabre\DAV\Server->invokeMethod()
19. /snap/nextcloud/31033/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php line 321
    Sabre\DAV\Server->start()
20. /snap/nextcloud/31033/htdocs/apps/dav/lib/Server.php line 352
    Sabre\DAV\Server->exec()
21. /snap/nextcloud/31033/htdocs/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
22. /snap/nextcloud/31033/htdocs/remote.php line 166
    require_once("/snap/nextcloud ... p")

DELETE /remote.php/dav/files/123/%E6%9C%AC%E5%9C%B0/%E8%AE%B0%E5%BD%95%E7%9A%84MD5.txt
from 192.168.123.19 by 123 at 2022-07-25T10:30:33+00:00

**Comment by kyrofa** [comment]
This sounds like either a config issue, or an issue with the upstream app. We're not really qualified to debug either one, here-- I recommend logging an issue [upstream](https://github.com/nextcloud/server).
