### ISSUE TITLE
Issue installing on Ubuntu 22.04

### ISSUE THREAD

**Issue by ntng99** [nextcloud-snap/nextcloud-snap#2153]
#### Describe the bug
Hello, apologies if this is not the right forum for this. Please let me know where I should reach out for help.
I have a clean install of Ubuntu 22.04 and am trying to get Nextcloud running via Snap.
After the install and user creation, when I log into the web interface, no pages load. It just says "Site cannot be reached."

#### To Reproduce
sudo snap install nextcloud
sudo nextcloud.manual-install [user] [pass]
"Nextcloud was successfully installed"
sudo nextcloud.occ config:system:set trusted_domains 1 --value=the.ip.add.ress
sudo nextcloud.enable-https self-signed

https://the.ip.add.ress
Login page loads successfully
Enter in admin user & pass previously created
Next page shows only "This site can’t be reached", does not load

#### Expected behavior
To be logged into Nextcloud to get things set up

#### OS/snapd/snap version
I'm running a clean install of Ubuntu Server 22.04

$ snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  24.0.3snap1  31222  latest/stable  nextcloud✓  -

$ snap version
snap    2.56.2+22.04ubuntu1
snapd   2.56.2+22.04ubuntu1
series  16
ubuntu  22.04
kernel  5.15.0-46-generic

#### Logs
Let me know what logs would be helpful.

**Comment by kyrofa** [comment]
Hey there @ntng99, thanks for logging an issue. Would you mind helping future issue searchers by sharing your solution?

**Comment by ntng99** [comment]
Sure, sorry for the false alarm. It turns out there was an issue with a proxy firewall in between me and the server, which was causing problems for the HTTPS connectivity. Not related to snap or nextcloud at all.
