### ISSUE TITLE
Move data folder to external usb hard drive

### ISSUE THREAD

**Issue by dying4004** [nextcloud-snap/nextcloud-snap#2154]
Hello all

I am trying to setup nextcloud in Ubuntu 22.04 using snap and want to use my external usb drive as data folder and my laptop's ssd is very small.

I tried the instruction from https://github.com/nextcloud-snap/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition

I tried If you just installed the snap, and haven't created an admin user yet first.

sudo mkdir -p /media/nextcloud/data
sudo chown -R root:root /media/nextcloud/data
sudo chmod 0770 /media/nextcloud/data

sudo snap install nextcloud

Update the Nextcloud config to use the new data directory by editing /var/snap/nextcloud/current/nextcloud/config/autoconfig.php and making sure the directory setting is pointing to the right place, e.g.:

// ...
'directory' => '/media/nextcloud/data',
// ...

sudo snap restart nextcloud.php-fpm
sudo snap connect nextcloud:removable-media
sudo snap connect nextcloud:network-observe
sudo nextcloud.manual-install sammy password

Now, I checked /media/nextcloud/data and the folder is empty. I also checked /var/snap/nextcloud/current/nextcloud/config/config.php and the datadirectory is the default location not what i put into autoconfig.php which is /media/nextcloud/data and the data is written into /var/snap/nextcloud/common/nextcloud/data.

Then I tried the moving data way and after running this command sudo mv /var/snap/nextcloud/common/nextcloud/data /media/my/new/data when i run sudo nextcloud.occ config:system:get trusted_domainsI get below

sudo nextcloud.occ config:system:get trusted_domains
Your data directory is readable by other users.
Please change the permissions to 0770 so that the directory cannot be listed by other users.

An unhandled exception has been thrown:
Exception: Environment not properly prepared. in /snap/nextcloud/31222/htdocs/lib/private/Console/Application.php:164
Stack trace:
#0 /snap/nextcloud/31222/htdocs/console.php(99): OC\Console\Application->loadCommands()
https://github.com/nextcloud-snap/nextcloud-snap/issues/1 /snap/nextcloud/31222/htdocs/occ(11): require_once('...')

What am I doing wrong and what can I do to fix this?
Thanks heaps

**Comment by scubamuc** [comment]
see here https://github.com/nextcloud-snap/nextcloud-snap/issues/2159

**Comment by edsonsbj** [comment]
For NTFS formatted drives follow this step by step

1.  Run the `blkid` command and find the `UUID` for your drive and write it down.
 
2. Create the mount point where you want it to mount. In my case I only managed to get it to work in the `/mnt/` folder

Example:
`cd /mnt/`
`mkdir /Nextcloud/`

3. Edit your `/etc/fstab` file with your preferred editor and add the line below

`UUID=0071900363FC570D /mnt/Nextcloud ntfs-3g utf8,uid=root,gid=root,umask=0007,noatime,x-gvfs-show 0 0`

**Obs** 

Change the UUID to the value corresponding to your unit

Remember the drive cannot be recognized by Nextcloud if it is mounted at `/media/user/path.`

Restart the system to apply the settings.
