### ISSUE TITLE
Disk space limited to 85,7 Gb on a 1 Tb disk

### ISSUE THREAD

**Issue by enricozennaro** [nextcloud-snap/nextcloud-snap#2155]
Hello,

I have just installed nextcloud via  snap on ubuntu server 22.04.1 LTS. The total disk space is limited to 85,7 Gb on the 1 Tb HDD of the old laptop i have installed the server on. 
![image](https://user-images.githubusercontent.com/64738155/185239586-23e567cb-40d4-4854-9255-6b2a1528fc47.png)

I have set up LVM during OS installation, but i did not chose any custom partitioning scheme, the installation did the following:
```
enrico@zennaro-server:~$ sudo -s
[sudo] password for enrico:
root@zennaro-server:/home/enrico# cd
root@zennaro-server:~# fdisk -l
Disk /dev/loop0: 55.56 MiB, 58261504 bytes, 113792 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop1: 44.68 MiB, 46845952 bytes, 91496 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop2: 61.89 MiB, 64901120 bytes, 126760 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop3: 79.95 MiB, 83832832 bytes, 163736 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop4: 232.61 MiB, 243908608 bytes, 476384 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/sda: 931.51 GiB, 1000204886016 bytes, 1953525168 sectors
Disk model: TOSHIBA MQ01ABD1
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: gpt
Disk identifier: 3D5F9714-6F32-442C-A7A6-AA24A903AF62

Device       Start        End    Sectors   Size Type
/dev/sda1     2048    2203647    2201600     1G EFI System
/dev/sda2  2203648    6397951    4194304     2G Linux filesystem
/dev/sda3  6397952 1953521663 1947123712 928.5G Linux filesystem


Disk /dev/mapper/ubuntu--vg-ubuntu--lv: 100 GiB, 107374182400 bytes, 209715200 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
```
How to increase the nextcloud space to potentially use the all the `/dev/sda3` partition?

**Comment by kyrofa** [comment]
Dumb question, but where are you actually seeing that output in Nextcloud?

**Comment by kyrofa** [comment]
Ah, the monitoring app. You should be specific, not everyone has the same apps enabled. I don't know how that app gets its data, but it seems to work okay for me:

![Screenshot from 2022-08-17 13-56-50](https://user-images.githubusercontent.com/946674/185241733-2dd352a3-82e6-4863-bb04-7be8139059d6.png)

**Comment by enricozennaro** [comment]
Thank you for your really quick answer!


>Note that it is indeed FREE space, not TOTAL space, as you say.

Yes, i get the difference, I don't know why i was confusing the two, sorry.  Anyway, if I'm now uploading some stuff to the nextcloud server, by the time I was writing my previous message nearly nothing had been uploades jet, so the two were really close values. 


>Any chance you just have a lot of data on that partition?

I don't think so, I just installed ubuntu server with nextcloud snap today. As I mentioned, I'm using an old laptop as a server. I haven't installed or loaded anything else on that computer, i just booted and installed the ubuntu server 22.04.1 LTS OS with the nextcloud snap, the only one additional thing installed is ddclient.

Anyway, as i logged in again using `ssh` i noticed the following, in `Usage of /:`:

```
Welcome to Ubuntu 22.04 LTS (GNU/Linux 5.15.0-46-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Wed Aug 17 09:01:26 PM UTC 2022

  System load:  0.46826171875     Temperature:             42.0 C
  Usage of /:   7.4% of 97.87GB   Processes:               169
  Memory usage: 9%                Users logged in:         1
  Swap usage:   0%                IPv4 address for enp4s0: 192.168.1.28
```


I'm sorry if I may make dumb questions... Am I supposed to make this kind of questions here in the nextcloud-snap GitHub issues or in the https://help.nextcloud.com/ forum?

**Comment by kyrofa** [comment]
> Anyway, as i logged in again using ssh i noticed the following, in `Usage of /:`:

Yeah that's the size of your `/dev/mapper/ubuntu--vg-ubuntu--lv` volume. It looks like LVM isn't setup properly to me; Nextcloud is using all the space it sees.

> I'm sorry if I may make dumb questions... Am I supposed to make this kind of questions here in the nextcloud-snap GitHub issues or in the https://help.nextcloud.com/ forum?

Oh no problem, you're always encouraged to ask questions here. [help.nextcloud.com](https://help.nextcloud.com/) will generally be crickets or trolls, in my experience.
