### ISSUE TITLE
sudden catastrophic slowdown in Nextcloud

### ISSUE THREAD

**Issue by seatrout** [nextcloud-snap/nextcloud-snap#2157]
#### Describe the bug
Since the start of this week, Nextcloud has become ludicrously slow. I have not, to my knowledge, changed anything on the server. 

#### OS/snapd/snap version
Running 
What OS and version are you running? Please also include the output of the
following commands:

###### $ snap list nextcloud
```
❯ snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  24.0.3snap1  31227  latest/stable  nextcloud✓  -
```
and:

###### $ snap version
```
❯ snap version
snap      2.56.2
snapd     2.56.2
series    16
raspbian  10
```

#### Logs
Too long to past: included as an attachment
There are numerous entries from a user called "Iona" trying to log in and failing. This user has been deleted but there is something crazy about their phone. I will ask them to delete the client. But, again, nothing changed to my knowledge with that phone in the last week or so. Before then it was working fine. 

[nextcloud_debug_log.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/9386949/nextcloud_debug_log.txt)

**Comment by scubamuc** [comment]
@seatrout 
none of your issues seem to be snap related. please be more specific as to OS and version you're runnung the nextcloud-snap on.

your logs show 2 recurring errors which could the cause of your performance issues:

```
[Thu Aug 18 18:09:05.877184 2022] [proxy_fcgi:error] [pid 24781:tid 2930742304] (70007)The timeout specified has expired: [client 192.168.50.50:42424] AH01075: Error dispatching request to : (reading input brigade)
[Thu Aug 18 23:27:48.837558 2022] [proxy_fcgi:error] [pid 24783:tid 3025126432] [client 192.168.50.50:44932] AH01071: Got error 'Primary script unknown', referer: http://nextcloud.unclaimed.space/wp-login.php
[Fri Aug 19 11:12:08.578192 2022] [proxy_fcgi:error] [pid 24781:tid 3041911840] [client 192.168.50.50:46672] AH01071: Got error 'Primary script unknown'
[Fri Aug 19 11:33:23.695428 2022] [proxy_fcgi:error] [pid 24781:tid 2983195680] [client 192.168.50.50:46840] AH01071: Got error 'Primary script unknown'
[Fri Aug 19 11:33:24.788511 2022] [proxy_fcgi:error] [pid 24781:tid 2955920416] [client 192.168.50.50:46840] AH01071: Got error 'Primary script unknown'
[Fri Aug 19 14:15:08.574621 2022] [mpm_event:notice] [pid 24780:tid 3070034864] AH00491: caught SIGTERM, shutting down
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
```

Error 1.  _PHP-FPM: AH01071: error 'Primary script unknown' --> Check $USER (uid/gid) for mounted data directory._
If data directory is on a mounted external device. Make sure mount permissions are root:root

Error 2.   _httpd: Could not reliably determine the server's fully qualified domain name --> set FQDN in `/etc/hosts` in VM_
could look like this:
``` 
127.0.0.1       localhost
127.0.1.1       your.domain.xyz SERVERNAME

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

**Comment by seatrout** [comment]
Thank you for this reply. 
I have changed the `etc/hosts` file as suggested, without making any difference. The data directory error is odd, because the whole system is booted off an external ssd. But I will have a look

**Comment by seatrout** [comment]
Sorry — just noticed the omission of the OS information,. This is a raspberry pi 4, 2GB memory, running the latest Pi OS, with apt update etc applied

**Comment by scubamuc** [comment]
@seatrout 
quite sure that this is not a snap issue. we can try to troubleshoot nonetheless:
 
the [proxy_fcgi:error] has been known to appear when CODE and Nextcloud-Office apps are installed. 
if this is the case, please disable CODE and Nextcloud-Office and compare performance.

**Comment by seatrout** [comment]
Thanks again, but neither are installed. 

I think I will just abandon the whole experiment. I already pay Microsoft £80 a year for a terabyte of disk space in the cloud and I might as well use more of it. I've used NC for about four years now and the community has always been helpful when I needed help.  I do appreciate the trouble you've taken. But I can't be doing with these apparently random collapses.

**Comment by scubamuc** [comment]
no problem.
please close issue.
