### ISSUE TITLE
Changing data directory before install (using autoconfig.php) does NOT work

### ISSUE THREAD

**Issue by flkrz** [nextcloud-snap/nextcloud-snap#2159]
#### Describe the bug
Despite following all the instructions as specified on https://github.com/nextcloud-snap/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition the snap install persists with using the default data location within the /var directory.

#### To Reproduce
1. Follow standard snap install procedure from https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-nextcloud-on-ubuntu-22-04 until at point where manual-install is called
2. Follow procedure outlined as option 1 within the https://github.com/nextcloud-snap/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition specificly written guide, after ensuring that removeable-media connection has been enabled
3. Go back to main install guide and continue process to install, enabling Lets Encrypt as per SOP
4. Once install complete, do "sudo ls -a /var/snap/nextcloud/common/nextcloud/data" and see that data is stored there rather than in "/media/nextcloud/data"

#### Expected behavior
Data would not be stored in /var/snap and instead be stored in /media/nextcloud as per the guide

#### Screenshots

![2022-08-22 20_48_40-Window](https://user-images.githubusercontent.com/59532240/186006435-caeb31c7-c481-4a7b-a7ff-7811663318fb.png)

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

Operating System: Ubuntu Server 22.04.01

Kernel: Linux 5.15.0-1017-azure x86_64

CPU: Intel(R) Xeon(R) E-2288G CPU @ 3.70GHz (4 cores)

Memory: 2.70 GB

Nextcloud version 24.0.3

    $ snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  24.0.3snap1  31222  latest/stable  nextcloud✓  -

and:

    $ snap version
snap    2.56.2+22.04ubuntu1
snapd   2.56.2+22.04ubuntu1
series  16
ubuntu  22.04
kernel  5.15.0-1017-azure

#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).
[Debug_Info_2022-08-22-2100.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/9397267/Debug_Info_2022-08-22-2100.txt)

**Comment by kyrofa** [comment]
It's possible that functionality was broken/is no longer available on more recent Nextcloud releases. Have you tried the second option, for moving an existing data directory? If so, we can just get rid of the first option.

**Comment by flkrz** [comment]
Just tried the second option. Migrated correctly and adopted the new changes fine. Free space now showing up as the capacity of the intended drive.

**Comment by dying4004** [comment]
> Just tried the second option. Migrated correctly and adopted the new changes fine. Free space now showing up as the capacity of the intended drive.

how did you partition your external drive for nextcloud?
every time i try the 2nd option and move data to external drive Nextcloud doesnt work anymore and shows error that the drive can be accessible by everyone.

My drive is NTFS and people say that ntfs can not have linux permission.

thanks

**Comment by kyrofa** [comment]
> My drive is NTFS and people say that ntfs can not have linux permission.

That's not true, you just need to mount it properly.

**Comment by dying4004** [comment]
> > My drive is NTFS and people say that ntfs can not have linux permission.
> 
> That's not true, you just need to mount it properly.

would you know how to mount?

I tried many mount option from different discussion but nothing worked.

**Comment by edsonsbj** [comment]
For those who want to move the data nextcloud folder to a hard drive whose file system is NTFS, follow the steps described on this site `https://simon-koester.de/Die-Website/raspberry-pi-nextcloud-datenverzeichnis-auf-ntfs-festplatte-verschieben/` in my case it worked perfectly

**Comment by edsonsbj** [comment]
1.  Run the `blkid` command and find the `UUID` for your drive and write it down.
2. 
3. Create the mount point where you want it to mount. In my case I only managed to get it to work in the `/mnt/` folder

Example:
`cd /mnt/`
`mkdir /Nextcloud/`

3. Edit your `/etc/fstab` file with your preferred editor and add the line below

`UUID=0071900363FC570D /mnt/Nextcloud ntfs-3g utf8,uid=root,gid=root,umask=0007,noatime,x-gvfs-show 0 0`

**Obs** 

Change the UUID to the value corresponding to your unit

Remember the drive cannot be recognized by Nextcloud if it is mounted at `/media/user/path.`

Restart the system to apply the settings.

**Comment by BeppoBremse** [comment]
In my case, moving doesn't work either: The drives I want to store the data directory on are a RAID 1 using MD. The partition on the RAID is formatted as EXT4 just as the root filesystem. When I stop nextcloud, move the directory and restart nextcloud, I get 

"Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log."

Any ideas?

**Comment by flkrz** [comment]
> In my case, moving doesn't work either: The drives I want to store the data directory on are a RAID 1 using MD. The partition on the RAID is formatted as EXT4 just as the root filesystem. When I stop nextcloud, move the directory and restart nextcloud, I get
> 
> "Internal Server Error
> 
> The server encountered an internal error and was unable to complete your request. Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report. More details can be found in the server log."
> 
> Any ideas?

What does the server log say?

What is the mount path for your nextcloud directory?

**Comment by BeppoBremse** [comment]
copying the data-directory to the raid1 and setting a symlink doesn't work either.

**Comment by BeppoBremse** [comment]
The raid1 is not removable.
