### ISSUE TITLE
How can I change the default rights nextcloud uses when creating a new user? NC 24.0.3

### ISSUE THREAD

**Issue by sparkerb** [nextcloud-snap/nextcloud-snap#2160]
I have external apps which add and remove files so I need them to have access to the folder structure. I don't want to give them root access. When a new user is create i have to manually change the rights of the folder so that my apps can do their thing. I'm using Ubuntu.

**Comment by scubamuc** [comment]
external app permissions for data directory --> _this is only possible as root_ 
or
'one-time at user creation' access --> _consider using `skeleton`_

**Comment by sparkerb** [comment]
Skeleton ?
________________________________

**Comment by scubamuc** [comment]
see [skelton](https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/default_files_configuration.html)

**Comment by sparkerb** [comment]
Hi thanks. This will not solve the issue. I want to avoid using root to share the data directory via samba so I can allow my app move and delete files.

Any further ideas?
________________________________

**Comment by scubamuc** [comment]
possible solution;

1. use "[external storage](https://docs.nextcloud.com/server/24/admin_manual/configuration_files/external_storage_configuration_gui.html)" to connect to external apps read/writable directory.  
2. use [skelton](https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/default_files_configuration.html) to add "external folder" upon account creation. 
(optional)
2.1 use "[Group Folders](https://apps.nextcloud.com/apps/groupfolders)" 

please note, not sure if "samba" is an option when adding external storage in nextcloud-snap... known to have issues
