### ISSUE TITLE
Cannot change URL

### ISSUE THREAD

**Issue by DrKeks** [nextcloud-snap/nextcloud-snap#2163]
I cannot find a command to change the URL in my nextcloud snap installation. My dynamic dns provider seems to have closed my account, so I have to make a new one. And now, I will get another URL. How can I change it in the installation?

**Comment by scubamuc** [comment]
edit the config manually:
```
sudo nano /var/snap/nextcloud/current/nextcloud/config/config.php

**Comment by scubamuc** [comment]
> I cannot find a command to change the URL in my nextcloud snap installation. My dynamic dns provider seems to have closed my account, so I have to make a new one. And now, I will get another URL. How can I change it in the installation?

servus, hast du das hinbekommen?
