### ISSUE TITLE
htdocs/dist dir malicious content in google

### ISSUE THREAD

**Issue by george2asenov** [nextcloud-snap/nextcloud-snap#2164]
#### Describe the bug
On nextcloud-snap there is a public "dist" directory that is found by google and other web protection tools as malicious.
I'm not sure that this dir should or should not be there but the directory is in the nextcloud repo but on other (not snap) installation there is no such directory.
Unfortunately in snap I can't modify it or any other config to disable public access to it.

#### To Reproduce
1. Go to 'https://domain.tld/dist/core-common.js'
4. See the content plain text 

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud
nextloud  24.0.3snap1  31222  latest/stable  nextcloud
and:

    $ snap version
snap 2.56.2
snapd   2.56.2
series  16
ubuntu  20.04
kernel  5.4.0-122-generic
#### Logs
n/a

**Comment by kyrofa** [comment]
The `dist` subdirectory comes from the upstream nextcloud tarball. You can [download it for yourself](https://nextcloud.com/install/#instructions-server) and see. It contains various javascript files, and you can see it being used if you view source.

> [...] on other (not snap) installation there is no such directory.

That doesn't seem to be true. For example, here's a snippet from https://cloud.nextcloud.com/login, which is not hosted via the snap:

```
<script nonce="ako0czh5TENiV2RkOGlkb3hMd1B3NTkvbFpqa0dZZ2wzaEFuY3llaXdqRT06eWM1MnhYYVhBRk13bDFKSGwvMS85L3dSMXZTdGZPWjM5VmNNRkJUSWcxUT0=" defer src="/dist/core-common.js?v=844894ea-73"></script>
<script nonce="ako0czh5TENiV2RkOGlkb3hMd1B3NTkvbFpqa0dZZ2wzaEFuY3llaXdqRT06eWM1MnhYYVhBRk13bDFKSGwvMS85L3dSMXZTdGZPWjM5VmNNRkJUSWcxUT0=" defer src="/dist/core-main.js?v=844894ea-73"></script>
<script nonce="ako0czh5TENiV2RkOGlkb3hMd1B3NTkvbFpqa0dZZ2wzaEFuY3llaXdqRT06eWM1MnhYYVhBRk13bDFKSGwvMS85L3dSMXZTdGZPWjM5VmNNRkJUSWcxUT0=" defer src="/dist/core-files_fileinfo.js?v=844894ea-73"></script>
<script nonce="ako0czh5TENiV2RkOGlkb3hMd1B3NTkvbFpqa0dZZ2wzaEFuY3llaXdqRT06eWM1MnhYYVhBRk13bDFKSGwvMS85L3dSMXZTdGZPWjM5VmNNRkJUSWcxUT0=" defer src="/dist/core-files_client.js?v=844894ea-73"></script>
<script nonce="ako0czh5TENiV2RkOGlkb3hMd1B3NTkvbFpqa0dZZ2wzaEFuY3llaXdqRT06eWM1MnhYYVhBRk13bDFKSGwvMS85L3dSMXZTdGZPWjM5VmNNRkJUSWcxUT0=" defer src="/js/core/merged-template-prepend.js?v=844894ea-73"></script>
```

When you say that it's "found by google and other web protection tools as malicious", what tools are we talking about?

**Comment by george2asenov** [comment]
Thanks for your answer.
For this:
"on other (not snap) installation there is no such directory."
I have  one working installation of nextcloud in the company I work (this ticket is for my personal self hosted nextcloud) and there is no such subdir in the nextcloud dir .
![zoc_aDhNPYA7mF](https://user-images.githubusercontent.com/15124861/187638876-6ce88f32-637e-4fa6-a661-e886592302fb.png)
 Probably we have deleted it in the process of installation I do not remember. But defiantly this installation is working without this subdir.

I'm referring to the Google safe browsing - i.e. the whole red page in chrome that say that this website is malicious an when I ask for more information the detected malicious address is "/dist/core-common.js?v=74ac84f8"
also some safe browsing service working om my mobile operator (it can get it  from google) also shows that this page is malicious!

**Comment by kyrofa** [comment]
That might be worth reporting against upstream Nextcloud. It sounds like a false positive I suspect they could work out with Google.
