### ISSUE TITLE
Installing on digitalocean's Ubuntu 22.04 fails with General error: 2006 MySQL server has gone away

### ISSUE THREAD

**Issue by vasaka** [nextcloud-snap/nextcloud-snap#2166]
Trying to install nextcloud on Nextcloud machine with  512 MB Memory / 10 GB Disk and fail on
the command `sudo nextcloud.manual-install user password` with error message
`An exception occurred while executing a query: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away`

1. Create a droplet on nextcloud that has  512 MB Memory / 10 GB Disk
2. login and run command `sudo snap install nextcloud`
3. run command `sudo nextcloud.manual-install`
4. See error `An exception occurred while executing a query: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away`

Internet suggests that I might need to tweak `max_allowed_packet` but I am not really sure how to do this with snap package. Also the problem might be something else

**Comment by kyrofa** [comment]
Yeah you need at least 1GB of RAM to run this thing, sorry.
