### ISSUE TITLE
snap change data directory permissions issue?

### ISSUE THREAD

**Issue by kmsgli** [nextcloud-snap/nextcloud-snap#2169]
I am having trouble changing the location of my data directory maybe I am missing something simple;.
I have turned on outside access to /mnt and /media with `sudo snap connect nextcloud:removable-media`

Then followed the instructions here for an already existing admin account:
https://github.com/nextcloud-snap/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition

when I turn my nextcloud back on and go the website I get the blue nextcoud background wit the error;
```
Error

    Your data directory is invalid.

    Ensure there is a file called ".ocdata" in the root of the data directory.
```

That file is in my data folder as I am using the same drive as before I just don't want it buried in 
`/var/snap/nextcloud/common/nextcloud/data`

I want it in
`/media/nextcloud/data`

permissions for the data directory are as follows;

`drwxr-x--- 5 http http 4096 Sep  4 18:16`
`drwxr-xr-x 3 root root 4096 Sep  6 16:33 `
`drwxrwx--- 6 root root 4096 Jun 23 21:17 data`
`-rwxrwx--- 1 http http  542 Mar 28 16:29 .htaccess`
`-rwxrwx--- 1 http http    0 Mar 28 16:29 .ocdata`
`drwxr-x--- 2 root root 4096 Sep  6 16:26 tmp`
`drwxrwx--- 5 http http 4096 Mar 20  2020 .Trash-1000`

Any help is much appreciated, thank you.

**Comment by scubamuc** [comment]
permissions for data must be root only
'sudo chown -R root:root /media/nextcloud/data'

**Comment by kmsgli** [comment]
> permissions for data must be root only `sudo chown -R root:root /media/nextcloud/data`

The data directory is root:root are you talking about the first entry which is presumably the /media/nextcloud folder? Wouldn't  chmod -R root:root make .htaccess and .ocdata owned by root?  As far as I know that needs to be owned by http?

in my current directory /`var/snap/nextcloud/common/nextcloud` (my nextcloud works proper with the drive mounted here)
it looks like this;

`drwxr-x--- 5 root root 4096 Sep  4 18:16 .`
`drwxr-xr-x 4 root root 4096 Jun 29 17:58 ..``
drwxrwx--- 6 root root 4096 Jun 23 21:17 data`
`-rwxrwx--- 1 http http  542 Mar 28 16:29 .htaccess`
`-rwxrwx--- 1 http http    0 Mar 28 16:29 .ocdata`
`drwxr-x--- 2 root root 4096 Sep  6 20:22 tmp`
`drwxrwx--- 5 http http 4096 Mar 20  2020 .Trash-1000`

**Comment by kyrofa** [comment]
No, @scubamuc is correct. For the snap, everything is root. There is no http/www-data here.

**Comment by kmsgli** [comment]
So I tried @scubamuc recommendation with no luck, same error. I even went in and specifically changed .htaccess and .ocdata files to root:root with no luck

**Comment by kyrofa** [comment]
Can we see the output of `sudo /snap/bin/nextcloud.occ config:list`, please?

**Comment by edsonsbj** [comment]
1.  Run the `blkid` command and find the `UUID` for your drive and write it down.
 
2. Create the mount point where you want it to mount. In my case I only managed to get it to work in the `/mnt/` folder

Example:
`cd /mnt/`
`mkdir /Nextcloud/`

3. Edit your `/etc/fstab` file with your preferred editor and add the line below

`UUID=0071900363FC570D /mnt/Nextcloud ntfs-3g utf8,uid=root,gid=root,umask=0007,noatime,x-gvfs-show 0 0`

**Obs** 

Change the UUID to the value corresponding to your unit

Remember the drive cannot be recognized by Nextcloud if it is mounted at `/media/user/path.`

Restart the system to apply the settings.

**Comment by kmsgli** [comment]
> `sudo /snap/bin/nextcloud.occ config:list`,


This is the output currently, do you want me to change the config dir and mount it to the /media spot then output this?

my system works when i mount the drive to //var/snap/nextcloud/common/nextcloud

```
{
    "system": {
        "apps_paths": [
            {
                "path": "\/snap\/nextcloud\/current\/htdocs\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/snap\/nextcloud\/current\/nextcloud\/extra-apps",
                "url": "\/extra-apps",
                "writable": true
            }
        ],
        "supportedDatabases": [
            "mysql"
        ],
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "log_type": "file",
        "logfile": "\/var\/snap\/nextcloud\/current\/logs\/nextcloud.log",
        "logfilemode": 416,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.1.6",
            "ctrlsync",
            "ctrlsync.ddns.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "24.0.3.2",
        "overwrite.cli.url": "http:\/\/192.168.1.6",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "loglevel": 2,
        "theme": ""
    },
    "apps": {
        "accessibility": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": ""
        },
        "activity": {
            "enabled": "yes",
            "installed_version": "2.16.0",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "2525"
        },
        "backup": {
            "allow_weekday": "1",
            "cron_enabled": "0",
            "cron_lock": "0",
            "delay_full_rp": "24",
            "delay_partial_rp": "3",
            "enabled": "yes",
            "external_appdata": "{\"storageId\":9,\"storage\":\"local::\\\/media\\\/\",\"root\":\"backups\"}",
            "installed_version": "1.1.3",
            "mockup_date": "0",
            "pack_backup": "1",
            "pack_compress": "1",
            "pack_encrypt": "0",
            "store_items": "3",
            "store_items_external": "5",
            "time_slots": "23-5",
            "types": ""
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "2.4.0",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "3.5.0",
            "types": ""
        },
        "circles": {
            "enabled": "yes",
            "installed_version": "24.0.0",
            "loopback_tmp_scheme": "http",
            "maintenance_run": "0",
            "maintenance_update": "{\"3\":1662593020,\"2\":1662594829,\"1\":1662594829}",
            "migration_22": "1",
            "migration_22_1": "1",
            "migration_run": "0",
            "types": "filesystem,dav"
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.14.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "4.2.0",
            "types": "dav"
        },
        "contactsinteraction": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "dav"
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "installed.bundles": "[\"CoreBundle\"]",
            "installedat": "1656033275.7012",
            "lastcron": "1662594829",
            "lastupdatedat": "0",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "previewsCleanedUp": "1",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "theming.variables": "d41d8cd98f00b204e9800998ecf8427e",
            "vendor": "nextcloud"
        },
        "dashboard": {
            "enabled": "yes",
            "installed_version": "7.4.0",
            "types": ""
        },
        "dav": {
            "buildCalendarReminderIndex": "yes",
            "buildCalendarSearchIndex": "yes",
            "enabled": "yes",
            "installed_version": "1.22.0",
            "regeneratedBirthdayCalendarsForYearFix": "yes",
            "types": "filesystem"
        },
        "electronicsignatures": {
            "enabled": "no",
            "installed_version": "2.0.1",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.14.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.14.0",
            "types": "authentication"
        },
        "files": {
            "enabled": "yes",
            "installed_version": "1.19.0",
            "types": "filesystem"
        },
        "files_external": {
            "allow_user_mounting": "yes",
            "enabled": "yes",
            "installed_version": "1.16.1",
            "types": "filesystem",
            "user_mounting_backends": "ftp,dav,owncloud,sftp,amazons3,swift,\\OC\\Files\\Storage\\SFTP_Key"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "2.5.0",
            "types": ""
        },
        "files_rightclick": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.16.2",
            "types": "filesystem"
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.14.0",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.17.0",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.13.0",
            "types": "logging"
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.9.0",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "authentication"
        },
        "mail": {
            "enabled": "yes",
            "installed_version": "1.13.8",
            "types": ""
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200",
            "types": "logging"
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.12.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "authentication"
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.14.0",
            "types": "authentication"
        },
        "photos": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "privacy": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.14.0",
            "types": "prevent_group_restriction"
        },
        "recommendations": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": ""
        },
        "richdocuments": {
            "disable_certificate_verification": "yes",
            "enabled": "yes",
            "installed_version": "6.2.0",
            "types": "prevent_group_restriction",
            "wopi_url": "http:\/\/192.168.1.6\/extra-apps\/richdocumentscode\/proxy.php?req="
        },
        "richdocumentscode": {
            "enabled": "yes",
            "installed_version": "22.5.502",
            "types": ""
        },
        "serverinfo": {
            "cached_count_filecache": "54671",
            "cached_count_storages": "8",
            "enabled": "yes",
            "installed_version": "1.14.0",
            "types": ""
        },
        "settings": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.14.0",
            "types": "filesystem"
        },
        "spreed": {
            "enabled": "yes",
            "has_reference_id": "yes",
            "installed_version": "14.0.4",
            "project_access_invalidated": "1",
            "types": "dav,prevent_group_restriction"
        },
        "support": {
            "SwitchUpdaterServerHasRun": "yes",
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": "session"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.14.0",
            "types": "logging"
        },
        "text": {
            "enabled": "yes",
            "installed_version": "3.5.1",
            "types": "dav"
        },
        "theming": {
            "enabled": "no",
            "installed_version": "1.15.0",
            "types": "logging"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": ""
        },
        "twofactor_totp": {
            "enabled": "yes",
            "installed_version": "6.4.0",
            "types": ""
        },
        "user_status": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "viewer": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "weather_status": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "2.6.0",
            "types": "filesystem"
        }
    }
}
```

**Comment by kyrofa** [comment]
Agh darnit, it sanitized the thing I cared about:

> "datadirectory": "***REMOVED SENSITIVE VALUE***",

Can you confirm that you updated that to `/media/nextcloud/data`?

**Comment by kyrofa** [comment]
Can you also please confirm that `/media` and `/media/nextcloud` are also owned by `root:root`?

**Comment by kmsgli** [comment]
> Can you also please confirm that `/media` and `/media/nextcloud` are also owned by `root:root`?

I edited the above output to show you the file the directory resides in
below is ls -la for /media and /media/nextcloud

/media`
drwxr-xr-x  3 root root 4096 Sep  6 16:33 .`
`drwxr-xr-x 18 root root 4096 Sep  6 07:15 ..`
`drwxr-x---  5 root root 4096 Sep  4 18:16 nextcloud`


/media/nextcloud
`total 24`
`drwxr-x--- 5 root root 4096 Sep  4 18:16 .`
`drwxr-xr-x 3 root root 4096 Sep  6 16:33 ..`
`drwxrwx--- 6 root root 4096 Jun 23 21:17 data`
`-rwxrwx--- 1 root root  542 Mar 28 16:29 .htaccess`
`-rwxrwx--- 1 root root    0 Mar 28 16:29 .ocdata`
`drwxr-x--- 2 root root 4096 Sep  7 17:29 tmp`
`drwxrwx--- 5 http http 4096 Mar 20  2020 .Trash-1000`

**Comment by kmsgli** [comment]
after a reboot using fstab to mount /dev/sdb1 to /media/nextcloud i got an error but slightly different.


```

Your data directory is invalid.

Ensure there is a file called ".ocdata" in the root of the data directory.

Cannot create "data" directory.
```

**Comment by edsonsbj** [comment]
> Então, acabei de instalar o nextcloud snap em uma máquina diff e segui a mesma instrução, mas usando a seção ainda sem configuração de usuário admin e consegui fazer isso funcionar, quando tentei mover o diretório de dados de /media/nextcloud/data para /mnt/nextcloud/data nessa nova configuração apenas para teste, recebi o mesmo erro. Talvez eu tenha que reinstalar do zero e refazer o upload e reconectar todos os meus dispositivos, o que será uma dor, mas não consigo descobrir outra maneira de fazer isso funcionar?

Some time ago when I installed nextcloud for the first time I had these same problems where the solution was the post above only after I added the unit in `fstab` and the mount point to `/mnt/` that worked. I didn't find anyone talking about this in any forum but from my own experience and from some friends of mine the nextcloud snap doesn't work well with the drive mounted in `/media/usr` because as the snap is executed in the background and the `root` needs to have access to the folder /media/usr is owned by the logged in user such as `/media/robert.`

**Comment by kmsgli** [comment]
> > Então, acabei de instalar o nextcloud snap em uma máquina diff e segui a mesma instrução, mas usando a seção ainda sem configuração de usuário admin e consegui fazer isso funcionar, quando tentei mover o diretório de dados de /media/nextcloud/data para /mnt/nextcloud/data nessa nova configuração apenas para teste, recebi o mesmo erro. Talvez eu tenha que reinstalar do zero e refazer o upload e reconectar todos os meus dispositivos, o que será uma dor, mas não consigo descobrir outra maneira de fazer isso funcionar?
> 
> Some time ago when I installed nextcloud for the first time I had these same problems where the solution was the post above only after I added the unit in `fstab` and the mount point to `/mnt/` that worked. I didn't find anyone talking about this in any forum but from my own experience and from some friends of mine the nextcloud snap doesn't work well with the drive mounted in `/media/usr` because as the snap is executed in the background and the `root` needs to have access to the folder /media/usr is owned by the logged in user such as `/media/robert.`

Winner!!!!!!!
You are correct mounting to /mnt/nextcloud worked after a reboot via fstab entry!!!!!

I was getting ready to give up and reinstall.

Interesting no one else found this same issue. I am wondering what distro you are using any change it is Manjaro or arch based?

**Comment by kyrofa** [comment]
Wow, very interesting, sounds like a snapd bug on your distro. Please log a bug against it. I'll go ahead and close this, then, but feel free to continue discussions here.

**Comment by kmsgli** [comment]
lets wait and see if @edsonsbj uses an arch based distro. I know standard arch mounts usb devices at /run/media/(username)/....
I don't know where manjaro mounts but I would assume the same, I only use manjaro for my nextcloud setup for the stability.

**Comment by edsonsbj** [comment]
> vamos esperar e ver se@edsonsbjusa uma distro baseada em arco. Eu sei que o arch padrão monta dispositivos usb em /run/media/(username)/.... Eu não sei onde o manjaro é montado, mas eu diria o mesmo, eu só uso manjaro para minha configuração nextcloud para a estabilidade.

at the moment i am running the nextcloud instance in the big linux distribution which is based on manjaro kde before i used zorin os and ubuntu server 20.04 and i always had this bug when trying to mount the hd in /media/

**Comment by kmsgli** [comment]
hmmm well if u experienced it in ubuntu that means it cant be an arch based distro issue.
