### ISSUE TITLE
snap.nextcloud.nextcloud-fixer.service fails

### ISSUE THREAD

**Issue by sfabel** [nextcloud-snap/nextcloud-snap#2170]
Rebooted the server. After reboot, Nextcloud does not come back up again.

Am on latest/stable, today that is 24.0.3snap1.

Running `nextcloud.occ maintenance:mode --off && nextcloud.occ -n upgrade` shows the fixer service running until it hits the following error:

```
Nextcloud[70566]: {"reqId":"OzFnX7ZUJdwVAwGcCeWs","level":3,"time":"2022-09-08T00:33:28+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Allowed memory size of 536870912 bytes exhausted (tried to allocate 232837600 bytes) at /snap/nextcloud/31228/htdocs/3rdparty/doctrine/dbal/src/Driver/PDO/Connection.php#82","userAgent":"--","version":"24.0.3.2","data":{"app":"PHP"}}
```

After which it keeps retrying without ever succeeding, thus leaving NC in maintenance mode indefinitely.

```
Sep 07 17:33:28 rpi4 nextcloud.nextcloud-fixer[70023]: run-parts: /snap/nextcloud/31228/fixes/existing-install/5_regenerate-assets.sh exited with return code 255
Sep 07 17:33:28 rpi4 systemd[1]: snap.nextcloud.nextcloud-fixer.service: Main process exited, code=exited, status=1/FAILURE
Sep 07 17:33:28 rpi4 systemd[1]: snap.nextcloud.nextcloud-fixer.service: Failed with result 'exit-code'.
Sep 07 17:33:29 rpi4 systemd[1]: snap.nextcloud.nextcloud-fixer.service: Scheduled restart job, restart counter is at 336.
Sep 07 17:33:29 rpi4 systemd[1]: Stopped Service for snap application nextcloud.nextcloud-fixer.
Sep 07 17:33:29 rpi4 systemd[1]: Started Service for snap application nextcloud.nextcloud-fixer.
Sep 07 17:33:30 rpi4 nextcloud.nextcloud-fixer[70706]: Nextcloud is in maintenance mode, hence the database isn't accessible.
```

Any ideas what's going on here? Is there some PHP memory limit set somewhere I need to adjust?

**Comment by kyrofa** [comment]
Yeah, try playing with [the PHP memory limits](https://github.com/nextcloud-snap/nextcloud-snap#php-memory-limit-configuration). What is it currently set to? Try bumping it up, even temporarily, and seeing if that helps.

**Comment by edsonsbj** [comment]
Friend if you have a snap revert I'm facing several problems with the new update from applications not working to internal server errors messages and my application store is gone not to mention that applications appear to update more when I click update they do not update

**Comment by sfabel** [comment]
Hi Kyle :)

OK so I raised the memory limit, but even after that stopped throwing an error (with `php.memory-limit=2048M`), it still croaked, but this time without any error whatsoever. The last app that was checked was "duplicatefinder", so I disabled that, and it works now.

Seems like the app is somehow broken.

Anyway, upon now turning off maintenance mode successfully, I see these messages (which don't seem to have any noticeable effect) I thought I'd highlight to you:

```
Sep 08 07:51:12 rpi4 audit[4097411]: AVC apparmor="DENIED" operation="mknod" profile="snap.nextcloud.php-fpm" name="/root/.rnd" pid=4097411 comm="php-fpm" requested_mask="c" denied_mask="c" fsuid=0 ouid=0
Sep 08 07:51:12 rpi4 audit[4097411]: AVC apparmor="DENIED" operation="mknod" profile="snap.nextcloud.php-fpm" name="/root/.rnd" pid=4097411 comm="php-fpm" requested_mask="c" denied_mask="c" fsuid=0 ouid=0
```

Presumably, this is desired behavior.

Thanks,
Stephan

**Comment by kyrofa** [comment]
Huh, indeed. You might consider logging a bug against duplicatefinder. Not sure what was happening, there.

> Presumably, this is desired behavior.

Yeah, that's expected. Thanks for getting back to us! I'll go ahead and close this, but feel free to continue discussion here.
