### ISSUE TITLE
snap and fedora upgrade

### ISSUE THREAD

**Issue by EdG973GCS** [nextcloud-snap/nextcloud-snap#2176]
Hello,
My curent snap version is NC 24.0.3snap1 Rev 31222
This is installed on a fedora 35.
I would like to upgrade fedora to 37 ; will this OS upgrade can break my snap instance of NC ?

Best Regards.

**Comment by kyrofa** [comment]
I'm afraid I have no idea, I'm sorry. Ubuntu is really the only OS I support, here, regardless of what snapd supports. Whether or not that works is up to both snapd and Fedora itself. Best of luck!
