### ISSUE TITLE
Snap NC instance behind a Traefik Proxy

### ISSUE THREAD

**Issue by EdG973GCS** [nextcloud-snap/nextcloud-snap#2177]
Hello,
Because I have only 1 public IP, I would like to put my Snap NC instance behind au Traefik proxy.
Traefik proxy can serve several http services (as apache proxy).
But Traefik proxy can also manage several https certificates in a local store on the proxy ; this is particulary interesting with letencrypt (automatical renews for certificates).

Does Traefik proxy works with Snap NC instance ? Is there any conflicts or issues ?
The architecture would be :
internet <===> HTTPS <===> TRAEFIK PROXY <===> HTTP <===> SNAP NC (in DMZ)

Best Regards

**Comment by kyrofa** [comment]
I've never personally used Traefik, but the architecture you outlined is pretty typical. We have some options [documented in our wiki](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Putting-the-snap-behind-a-reverse-proxy) that could be helpful.

**Comment by EdG973GCS** [comment]
Thank you very much.
HAproxy and Nginx proxy seems to be simplier than Traefik to setup.
I will read it carefully and try to understant how automate the letencrypt certificate renew.

**Comment by EdG973GCS** [comment]
I am sorry ; I read the wiki part about HA proxy.
It is written _You can continue to use nextcloud.enable-https as normal._

In my case, does it mean that I can continue to renew letencrypt certificate of my snap NC instance with the command **nextcloud.enable-https lets-encrypt** ??

**Comment by kyrofa** [comment]
If you want to. That's what I do, so it can manage certs for me, but it's perfectly okay (and probably MORE normal) to terminate SSL at the reverse proxy. Your call.

**Comment by EdG973GCS** [comment]
I am totally agree with you about to terminate SSL at reverse proxy.
Unfortunatly I installed my Snap NC instance too fast, without to think about all cases.
So I will use HA proxy according to the wiki, and manage certificate directly from the Snap NC instance.
Have a nice day

**Comment by NaXal** [comment]
I run exact same setup.

I have only one Public IP but I am running multiple server / services so needed to put a Reverse Proxy in place.

Me being somewhat non-technical user, settled for Nginx Proxy Manager.

Its a docker container project, comes with it's own GUI -> I felt it was really easy and simple to setup and Web Gui makes lifes really easy for me to add DNS Hosts for various services !!

Runs really smooth with a simple 1GB RAM VM with Ubuntu Server

Thanks.
