### ISSUE TITLE
Nextcloud snap suddenly stopped working. 

### ISSUE THREAD

**Issue by ph00lt0** [nextcloud-snap/nextcloud-snap#2179]
#### Describe the bug
Just encouraged the same issue randomly overnight the instance stopped working. Restarting Nextcloud itself did not help. The snaps seem running but the server isn't looks like php isn't doing anything.

When running sudo nextcloud.occ  I get  `Waiting for PHP...`. After a restart the issue is unchanged.

#### To Reproduce
Unknown, didn't change anything server side.

I ran sudo rm -rf /tmp/snap.nextcloud trying to see it this would help and restarted the server, before outputting this log.

#### Expected behavior
Keep doing what it did

#### OS/snapd/snap version

![image](https://user-images.githubusercontent.com/15004290/190861449-d8815000-3fe8-42a7-80ae-ad731669432c.png)

![image](https://user-images.githubusercontent.com/15004290/190861456-83a4d50c-31e0-4d0f-897b-49a622d85b1d.png)

#### Logs
https://gist.github.com/ph00lt0/fa57ed35090ad88a95827e5dd9b22fb5

**Comment by kyrofa** [comment]
Your logs are truncated. Maybe attaching them would be better?

**Comment by kyrofa** [comment]
I need your logs in a non-truncated form, don't really care how I get them. All I know is the gist you shared is not useful.

**Comment by kyrofa** [comment]
See how it starts in the middle of the mDNS log? You're missing the Apache, MySQL, PHP, and redis logs entirely.

**Comment by kyrofa** [comment]
There we go, that's just fine, thank you :) .

**Comment by kyrofa** [comment]
This does appear to be mysql-related:

> ```
> 2022-09-17T15:17:32.721921Z 0 [System] [MY-010116] [Server] /snap/nextcloud/31563/bin/mysqld (mysqld 8.0.30) starting as process 343930
> 2022-09-17T15:17:32.752990Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
> 2022-09-17T15:17:33.828097Z 1 [ERROR] [MY-012526] [InnoDB] Upgrade is not supported after a crash or shutdown with innodb_fast_shutdown = 2. This redo log was created with MySQL 8.0.29, and it appears logically non empty. Please follow the instructions at http://dev.mysql.com/doc/refman/8.0/en/upgrading.html
> 2022-09-17T15:17:33.828343Z 1 [ERROR] [MY-012930] [InnoDB] Plugin initialization aborted with error Generic error.
> 2022-09-17T15:17:33.829788Z 1 [ERROR] [MY-010334] [Server] Failed to initialize DD Storage Engine
> 2022-09-17T15:17:33.830218Z 0 [ERROR] [MY-010020] [Server] Data Dictionary initialization failed.
> 2022-09-17T15:17:33.830284Z 0 [ERROR] [MY-010119] [Server] Aborting
> 2022-09-17T15:17:33.831210Z 0 [System] [MY-010910] [Server] /snap/nextcloud/31563/bin/mysqld: Shutdown complete (mysqld 8.0.30)  Source distribution.
> ```

Looks like it crashed, and now it doesn't want to upgrade. A potential fix is [here](https://serverfault.com/questions/1110089/mysql-upgrade-is-not-supported-after-a-crash-or-shutdown-with-innodb-fast-shutd). You'll find the mysql files in `/var/snap/nextcloud/current/mysql`.

**Comment by kyrofa** [comment]
It's certainly possible, although you'll lose anything you did in the current version. Is that okay?

**Comment by kyrofa** [comment]
Yeah try `snap changes`.

**Comment by kyrofa** [comment]
Yes, that seems to be the case. Give it a shot!

**Comment by kyrofa** [comment]
I... guess? That's a new one for me.

**Comment by kyrofa** [comment]
It's complaining about `occ`, which is interesting. You probably still have some lying around "waiting for PHP." Try `ps ax | grep occ`.

**Comment by kyrofa** [comment]
Haha, nice. Okay good deal. I don't think you need to stop the snap to revert.

**Comment by kyrofa** [comment]
Did you start it again?

**Comment by kyrofa** [comment]
I suggest just leaving it alone. By reverting you marked the new rev as "bad", so it won't update you there again unless you force it, and you don't want to do that without clearing out the bad data as well. I'm going to be releasing a new version shortly, so if you're back up and running I'd just wait for that and it'll skip the one that went sideways for you.

**Comment by kyrofa** [comment]
Alright I'm going to go ahead and close this, since the immediate issue was resolved. Keep an eye on the next update though.
