### ISSUE TITLE
No default phone region error

### ISSUE THREAD

**Issue by linuxosd** [nextcloud-snap/nextcloud-snap#2181]
Ubuntu Server 22.04
Snapd version 2.57.1
Nextcloud version 24.0.4

Fresh installation of Nextcloud snap shows the following error in the Security and setup warnings:

"Your installation has no default phone region set. This is required to validate phone numbers in the profile settings without a country code. To allow numbers without a country code, please add "default_phone_region" with the respective ISO 3166-1 code ↗ of the region to your config file."

I am unable to find documentation on the Snap command to add a default phone region.

**Comment by scubamuc** [comment]
edit the config by hand:

` sudo nano /var/snap/nextcloud/current/nextcloud/config/config.php `

add phone region

` 'default_phone_region' => 'US' `

phone regions, see [here](https://help.nextcloud.com/t/where-to-specify-default-phone-region-parameter/130475)

**Comment by kyrofa** [comment]
Thanks @scubamuc. This isn't an issue with the snap. I have no idea why nextcloud shows this as a warning, but it does :man_shrugging: . I believe this question is answered, so I'll go ahead and close.
