### ISSUE TITLE
nextcloud stopped working

### ISSUE THREAD

**Issue by czinehuba** [nextcloud-snap/nextcloud-snap#2188]
#### Describe the bug
It started with updating the snapd package two days ago. After that I received a message about apparmor not being enabled. And nextcloud stopped working since.
I've tried to go back to older version of snapd, thinking that was the issue. I've tried 2.5.7, 2.5.7.1, 2.5.7.2 which is the stable and also the 2.5.7.4 from GitHub package. Still nothing changed
Also tried removing the snap and reinstalling, I've tried ver 23 as well. No changes.

mysql service isn't running. I'veattached logs from the debug script.

#### Expected behavior
For it to work

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud
nextcloud  24.0.4snap1  31563  24/stable  nextcloud✓

and:

    $ snap version
snap    2.57.2-1
snapd   2.57.2-1
series  16
arch    -
kernel  5.19.12-arch1-1

#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).
[nuc nextcloud NC debug.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/9689703/nuc.nextcloud.NC.debug.txt)

**Comment by kyrofa** [comment]
MySQL is crashing _hard_, looks like your database might be corrupted. But you said you tried re-installing the snap and it still didn't work?

**Comment by czinehuba** [comment]
I have backups, so kind of save with my data. But is there a way to rebuild the database with the snap , or I have to reinstall, and start fresh?

**Comment by czinehuba** [comment]
> MySQL is crashing _hard_, looks like your database might be corrupted. But you said you tried re-installing the snap and it still didn't work?

Yes. Ive tried reinstalling the snap.. still didn't work.

**Comment by czinehuba** [comment]
Had to start from scratch.  It's working now.
