### ISSUE TITLE
Snap is unable to access zpool

### ISSUE THREAD

**Issue by kz6fittycent** [nextcloud-snap/nextcloud-snap#2203]
#### Describe the bug
The Nextcloud snap is unable to access a zpool on localhost. Zpool is located off / (e.g. `/zpool/tank01`) 

#### To Reproduce
1. Setup config to point to zpool
2. Nextcloud complains about missing `.ocdata` file
3. Verify `.ocdata` file is present

#### Expected behavior
The snap should be able to access/use a zpool on localhost for data path for files.

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud
`24.0.6snap1`
and:

    $ snap version
```
snap    2.57.2
snapd   2.57.2
series  16
ubuntu  22.04
kernel  5.15.0-46-generic
```
Is this to be expected? I've built other snaps and one of them wasn't able to see any data within a `zpool`, either. I wondering if anyone else has experienced this with the Nextcloud (or other) snaps like I have.

**Comment by kz6fittycent** [comment]
Actually, I found this - I guess we can consider this a way to help others looking into the same issue as me:
https://forum.snapcraft.io/t/vlc-cannot-play-files-on-zfs-raid-array/4624

**Comment by kz6fittycent** [comment]
If the existing data is owned by `www-data:www-data`, how does the snap access it? Which user needs own it?

**Comment by kyrofa** [comment]
Try `root:root`

**Comment by kz6fittycent** [comment]
Recommend running `nextcloud.occ files:scan $USER` after this. I am going to fix my PR #2204 and open it again. I figured out what was wrong with my steps in the README. Thanks @kyrofa - yer awesome!

**Comment by kz6fittycent** [comment]
@kyrofa , sorry to tag you directly, but I don't see any documentation in the README for setting the FQDN? Is that just done in the `config.php`?

**Comment by kyrofa** [comment]
In what sense? Domains are used in the Nextcloud config in a few different ways. Trusted domains, overrides, and so on. You can definitely edit the `config.php` directly, or use `nextcloud.occ` if you want to set things that way. For example, trusted domains might look like `sudo nextcloud.occ config:system:set trusted_domains 2 --value=your.domain`.

**Comment by kz6fittycent** [comment]
Snap is working -  see PR #2204 that will include some directions in case this comes up again.
