### ISSUE TITLE
Upgrade to Nextcloud 25

### ISSUE THREAD

**Issue by Seb3thehacker** [nextcloud-snap/nextcloud-snap#2211]
Nextcloud released v25 a few days ago. The snap is a bit behind currently.

**Comment by kyrofa** [comment]
Yes, we wait for point releases on new major releases before upgrading.

**Comment by Seb3thehacker** [comment]
Ok! Thanks

**Comment by kyrofa** [comment]
No need to close, let's keep this open to track.

**Comment by hollisticated-horse** [comment]
What does "point release" mean ? I was looking at the nextcloud release cycle and couldn't figure out what it meant.

**Comment by kyrofa** [comment]
Basically, we're waiting for the first release AFTER 25, e.g. 25.0.1. Historically, major Nextcloud releases have been pretty unstable, and get a slew of issues logged against them by people willing to upgrade right away. We've learned not to subject our users to that, and just wait until that initial slew has been fixed. This generally makes our job easier as well, working out any kinks in the upgrade process.

**Comment by gordnhoo** [comment]
Around when do you think these releases will be made?

**Comment by kyrofa** [comment]
Looks like [early November-ish](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule).

**Comment by sesu-san** [comment]
I was very curious about this, thanks for the post! Really excited for Hub 3 :)

**Comment by NaXal** [comment]
I think Nextcloud has released the first maintenance update for version 25, so I guess now we can expect snap to go 25 also. Eagerly waiting for v25.

Reference -> https://help.nextcloud.com/t/first-maintenance-release-for-hub-3-out-updates-to-older-releases-too/149003

Thanks.

**Comment by kyrofa** [comment]
I'm afraid there's a [blocking bug on 25.0.1](https://github.com/nextcloud/server/issues/34674), so we're holding out for 25.0.2.

**Comment by NaXal** [comment]
No problem, sensible decision I would say. I don't want to spoil this wonderful trouble-free experience that I am having with Snap NextCloud deployment. Stability & reliability is far valuable for me over new features. 

Will wait.

Thanks.

**Comment by Insprill** [comment]
[25.0.2](https://github.com/nextcloud/server/releases/tag/v25.0.2) has been released

**Comment by tdalbo92** [comment]
Quick question (I'm unfamiliar with the release promotion with this snap)

When #2247 is merged, when will this hit `latest/stable`?

**Comment by Pilzinsel64** [comment]
When this is merged it will take at least a week until it moves from the latest/beta channel to latest/stable.

**Comment by kyrofa** [comment]
Right, as @Pilzinsel64 hints, when this PR is merged, it will hit latest/beta. Then we make a new release and it hits latest/candidate. Then when we're happy with it, it hits latest/stable.

**Comment by Pilzinsel64** [comment]
Beeing at `latest/beta` for ~a week now, seems to be stable on my end. No problems. JFYI

**Comment by yavko** [comment]
> Beeing at `latest/beta` for ~a week now, seems to be stable on my end. No problems and no negative user feedback. JFYI

Strange I don't see it anywhere, not on the website nor the snap command line utility

**Comment by Pilzinsel64** [comment]
@yavko It is called `24.0.8snap1+git2.67080dd`. you can find it in the `latest/beta` channel. Install via `snap install nextcloud --channel=latest/beta` or `snap refresh nextcloud --channel=latest/beta`>

**Comment by yavko** [comment]
> @yavko It is called `24.0.8snap1+git2.67080dd`. you can find it in the `latest/beta` channel. Install via `snap install nextcloud --channel=latest/beta` or `snap refresh nextcloud --channel=latest/beta`.

Ah thank you! But isn't it nextcloud 25, why is it called `24.0.8`? Anyways thank you!

**Comment by Pilzinsel64** [comment]
> But isn't it nextcloud 25, why is it called `24.0.8`?

You need to split `24.0.8snap1+git2.67080dd` into two parts:
- `24.0.8snap1` <-- This is the current stable version present in `latest/stable`
- `+git2.67080dd` <-- This means that all changed from the git commit `67080dd` since the current stable version `24.0.8snap1` has been added ([difs](https://github.com/nextcloud-snap/nextcloud-snap/compare/master...develop)). In this case also the change to NC25.

This is my interpretation at least. Maybe kyrofa corrects me if it's wrong. ;D

**Comment by kyrofa** [comment]
Spot on. `+git2.67080dd` can be further split:

- `git2`: two commits since 24.0.8snap1
- `67080dd`: commit hash that was used to build this particular snap

**Comment by yavko** [comment]
> > But isn't it nextcloud 25, why is it called `24.0.8`?
> 
> You need to split `24.0.8snap1+git2.67080dd` into two parts:
> 
>     * `24.0.8snap1` <-- This is the current stable version present in `latest/stable`
> 
>     * `+git2.67080dd` <-- This means that all changed from the git commit `67080dd` since the current stable version `24.0.8snap1` has been added ([difs](https://github.com/nextcloud-snap/nextcloud-snap/compare/master...develop)). In this case also the change to NC25.
> 
> 
> This is my interpretation at least. Maybe kyrofa corrects me if it's wrong. ;D

Ah thanks for clarifying!

**Comment by yavko** [comment]
> @yavko It is called `24.0.8snap1+git2.67080dd`. you can find it in the `latest/beta` channel. Install via `snap install nextcloud --channel=latest/beta` or `snap refresh nextcloud --channel=latest/beta`.

idk why but it seems it wont refresh
![image](https://user-images.githubusercontent.com/15178513/210114606-34312e0e-46ee-4830-b4ca-3cbda2e068e5.png)

**Comment by NaXal** [comment]
I see the main page of Github is saying snap is now on Nextcloud 25.

However, my installation hasn't auto updated yet. I am still on 24 latest

Am I missing something? Do I need to do something extra to make it update itself?

Thanks.

**Comment by Pilzinsel64** [comment]
The snap with NC25 onboard is currently in the channels `latest/beta` and `latest/stable`. One week after publishing it moves to `latest/stable`.

**Comment by kyrofa** [comment]
There's no hard rule for that, it's more like "however long it takes for @kyrofa to deploy it to his production stack and make sure it doesn't eat his data." I'm only comfortable rolling stuff out to everyone else once that happens, and sometimes it takes a little bit. Just finished though-- you should upgrade automatically shortly, or can just run `sudo snap refresh nextcloud` and get it immediately.

**Comment by NaXal** [comment]
My snap installation updated itself to 25. Working ok, but not liking the new theme of the v25 of Nextcloud :(

**Comment by kyrofa** [comment]
Heh, you and me both. Very early 2000's.
