### ISSUE TITLE
Nextcloud 24.0.6snap1 + Onlyoffice app?

### ISSUE THREAD

**Issue by vawaver** [nextcloud-snap/nextcloud-snap#2212]
#### Describe the bug
I have made a clean installation NC 24.0.6 snap1 on Ubuntu server 22.04 and I would like to use the OnlyOffice app for online editing.
How to make it work?

#### To Reproduce
1. Installed Onlyoffice app 7.5.6 + Community document server 0.1.12 
2. Click on Settings -> Community document server - there are no settings for Onlyoffice,
3. That is why it is not possible to add a new Onlyoffice file in Files via + (plus) button

#### Expected behavior
Settings for Onlyofficeis are available and visible.

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud
Ubuntu server 22.04
Nextcloud 24.0.6snap1

**Comment by kyrofa** [comment]
Sorry, we don't support individual apps here, you'll need a lot an issue against OnlyOffice.
