### ISSUE TITLE
Documentation request: how to add multiple custom certificates

### ISSUE THREAD

**Issue by ph00lt0** [nextcloud-snap/nextcloud-snap#2221]
I am trying to add multiple origin certificates to my instance from Cloudflare:
https://developers.cloudflare.com/ssl/origin-configuration/origin-ca

I am seeing the `sudo nextcloud.enable-https custom` command and it's options but it is unclear to me how I can do this for multiple certificates as I have multiple domains connected.

**Comment by NaXal** [comment]
Hello,

I run custom SSL with my Snap Installation of NextCloud.

Please refer here for detailed explanation as how to setup your custom SSL -> https://github.com/nextcloud-snap/nextcloud-snap/issues/199

Besically speaking,

1. You need obtain your SSL Certificate files in PEM format. There are 3, Certificate, your Private Key and the Key Chain
2. You need to put those files at following location of your Nextcloud installation, ` /var/snap/nextcloud/current/certs/custom/`
3. You need to navigate to that directory and then run following command, `sudo nextcloud.enable-https custom -s cert.pem privkey.pem chain.pem` (file names as per your own)

That will enable your custom SSL

However, I doubt if snap nextcloud supports multiple SSL within same installation for different domains. But I am no expert, so please wait for snap devs to reply on this issue.

Thanks.

**Comment by NaXal** [comment]
Hello,

In my case, I am copying my certificate from cPanel based host for my nextcloud subdomain, there I too don't have Chain, rather I see 3rd option named as "Certificate Authority Bundle: (CABUNDLE)". I renamed that file as chain in Nextcloud and it worked.

Do you have any such?

Worst case, if you are only getting a pvt key and cert file, then I guess try using that cert file as chain too.

Once again, I am no expert here. I don't have in-depth knowledge on this. I only know what worked for my installation.

Thanks.
