### ISSUE TITLE
Strict-Transport-Security not setup correctly in snap package when using a custom SSL certificate

### ISSUE THREAD

**Issue by landcaster** [nextcloud-snap/nextcloud-snap#2225]
### Describe the bug
When using a custom SSL certificate to enable HTTPS 
```
nextcloud.enable-https custom <cert> <key> <chain>
```

Nextcloud security check throws the following warning like in #2105 :

"The "Strict-Transport-Security" HTTP header is not set to at least "15552000" seconds. For enhanced security, it is recommended to enable HSTS as described in the [security tips ↗](https://docs.nextcloud.com/server/24/go.php?to=admin-security)."

### Expected behavior
As a custom certificate is typically one issued by a signing authority other than let's encrypt, the ssl.conf file should be configured correctly so the warning message can be suppressed, like which is done if let's encrypt is used.

```
<IfModule mod_headers.c>
    Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains"
</IfModule>
```

### OS/snapd/snap version
What OS and version are you running? 

```
$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```

Please also include the output of the
following commands:

```
$ snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  24.0.6snap1  31751  latest/stable  nextcloud✓  -
```

and:

```
$ snap version
snap    2.57.5+22.04
snapd   2.57.5+22.04
series  16
ubuntu  22.04
kernel  5.15.0-52-generic
```

**Comment by kyrofa** [comment]
If you want HSTS you need to request it:

```
$ sudo nextcloud.enable-https custom -h
Usage:
    nextcloud.enable-https custom [-h -s] <cert> <key> <chain>

    <snip>
    -s: Enable HTTP Strict Transport Security (HSTS)
        (default is off-- leave off if self-signed).
```
