### ISSUE TITLE
Front end stylesheets no longer load for the dashboard

### ISSUE THREAD

**Issue by K4LCIFER** [nextcloud-snap/nextcloud-snap#2230]
#### Describe the bug
The front end stylesheets no longer load. The dashboard as a result just displayes images, and raw html without any styling
I'm also seeing the following error in the console of the webpage:
```
The resource from “https://<domain-name>/index.php/apps/theming/styles?v=0” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
```

#### To Reproduce
unknown

#### Expected behavior
n/a

#### Screenshots
![image](https://user-images.githubusercontent.com/7829231/201036284-afc094de-4722-4214-8590-ee7c55ca42da.png)
![image](https://user-images.githubusercontent.com/7829231/201036313-ffb7498c-9d3e-4838-83b9-2632ac692ab4.png)

#### OS/snapd/snap version
Arch Linux LTS
following commands:

    $ snap list nextcloud
```
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  24.0.6snap1  31751  latest/stable  nextcloud✓  -
```

and:

    $ snap version
```
snap    2.57.5-1
snapd   2.57.5-1
series  16
arch    -
kernel  5.15.76-1-lts
```

#### Logs
[Output of script](https://pastebin.com/bYCf3eCs)

**Comment by Anisotropic** [comment]
Did you tried other browser?

**Comment by K4LCIFER** [comment]
> Did you tried other browser?

Yeah. I tried it with Firefox, Ungoogled Chromium, and Firefox iOS; they all have the same issue.

**Comment by kyrofa** [comment]
@K4LCIFER I'm afraid your link to logs appears to be invalid.

**Comment by K4LCIFER** [comment]
Aside: I accidentally didn't include the troubleshooting script when I first posted it. I have now updated the post to include the proper output of that script.

**Comment by kyrofa** [comment]
Huh, yeah this is what I was looking for:

> Nov 10 07:27:04 archlinux nextcloud.nextcloud-fixer[2555]:  - Clear frontend caches
> Nov 10 07:27:04 archlinux nextcloud.nextcloud-fixer[2555]:      - Image cache cleared
> Nov 10 07:27:04 archlinux nextcloud.nextcloud-fixer[2555]:      - SCSS cache cleared
> Nov 10 07:27:04 archlinux nextcloud.nextcloud-fixer[2555]:      - JS cache cleared

I expected to see errors there, though. That's the only time I've seen this kind of breakage.

**Comment by K4LCIFER** [comment]
> Huh, yeah this is what I was looking for:
> 
> > Nov 10 07:27:04 archlinux nextcloud.nextcloud-fixer[2555]:  - Clear frontend caches
> > Nov 10 07:27:04 archlinux nextcloud.nextcloud-fixer[2555]:      - Image cache cleared
> > Nov 10 07:27:04 archlinux nextcloud.nextcloud-fixer[2555]:      - SCSS cache cleared
> > Nov 10 07:27:04 archlinux nextcloud.nextcloud-fixer[2555]:      - JS cache cleared
> 
> I expected to see errors there, though. That's the only time I've seen this kind of breakage.

hooray, unique bugs.

**Comment by Sakrecoer** [comment]
This has happened to me too, a few times, always after updating an app. Each time i solved it by rebooting the snap.

**Comment by K4LCIFER** [comment]
The issue never solved itself for me up until a week or so ago. What I ended up doing was just switching from Arch Linux to Ubuntu Server.
