### ISSUE TITLE
Switch from fedora to Ubuntu

### ISSUE THREAD

**Issue by EdG973GCS** [nextcloud-snap/nextcloud-snap#2238]
Hello,

My NC Snap instance is running under Fedora Linux 37.
Is there a procedure/wiki to migrate under Ubuntu ?

snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  24.0.7snap1  32537  latest/stable  nextcloud✓  -

snap version
snap    2.56.2-5.fc37
snapd   2.56.2-5.fc37
series  16
fedora  37
kernel  6.0.9-300.fc37.x86_64

Best Regards

**Comment by scubamuc** [comment]
you could check out 
https://github.com/scubamuc/scubamuc.github.io#3-export-import----backup-restore
and 
https://github.com/scubamuc/scubamuc.github.io#32-nextcloud-snap-snapshot--restore
for some Export / import ideas.

the latter describes a snap container export. that should be the easiest solution in your case, as the entire snap would be transferred to the new machine including DB, Data, and Certs. this is actually the snap "selling point"... easy snap migration!

**Comment by EdG973GCS** [comment]
Hello,
That is very kind
Tnahink you very much for your help
