### ISSUE TITLE
LDAP Authentication not working with 24.0.7snap1

### ISSUE THREAD

**Issue by markfen88** [nextcloud-snap/nextcloud-snap#2239]
#### Describe the bug
Started getting complaints from users that they were not able to login. I tested and sure enough LDAP authentication was not working. I was able to login with my local admin account and teste LDAP. LDAP queries were working correctly but when I went to the users pain the "Active Users" was stuck in an infinite loading loop as well as the user groups were not populated correctly.

#### To Reproduce
1. Update to 24.0.7snap1
2. Try to login with AD

#### Expected behavior
Able to login

#### Screenshots
<img width="950" alt="image" src="https://user-images.githubusercontent.com/55214319/204314145-ce5ae020-2e21-459d-a080-5f1165d11de7.png">

#### OS/snapd/snap version

Ubuntu 18.04.6 LTS

What OS and version are you running? Please also include the output of the
following commands:
24.0.7snap1

**Comment by kyrofa** [comment]
I'm sorry, this sounds like an issue with the LDAP integration in Nextcloud, nothing specific to the snap. We aren't experts in that aspect, I recommended logging an issue against [Nextcloud itself](https://github.com/nextcloud/server).

**Comment by markfen88** [comment]
Reverting to 24.0.6 fixed the issue, so is it?

**Comment by kyrofa** [comment]
Unless you want to argue that the [updated PHP](https://github.com/nextcloud-snap/nextcloud-snap/blob/master/CHANGELOG#L1-L3) caused it, yes.
