### ISSUE TITLE
Can't upgrade nextcloud-snap using http proxy

### ISSUE THREAD

**Issue by ferror56** [nextcloud-snap/nextcloud-snap#2241]
From command line I setup proxy:
snap set system proxy.http=http://127.0.0.1:8118
snap set system proxy.https=http://127.0.0.1:8118

Then I issue downloading and installing updates:
snap refresh

Snaps are downloaded and updated, but
Nextcloud snap will download and then fails installing with following message:
error: cannot perform the following tasks:
- Run pre-refresh hook of "nextcloud" snap if present (run hook "pre-refresh": Unable to refresh: apps.nextcloud.com seems to be down, please try again later)

So how to persuade Nextcloud pre-refresh hook to use proxy? Without proxy it works ...

OS version: Debian 11

    $ snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  24.0.6snap1  31751  latest/stable  nextcloud✓  -

and:

    $ snap version
snap    2.57.6
snapd   2.57.6
series  16
debian  11
kernel  5.10.0-18-amd64

Here is another user having the same problem:
https://help.nextcloud.com/t/cant-upgrade-nextcloud-using-sudo-snap-refresh-nextcloud/128803

**Comment by scubamuc** [comment]
not sure if this is a snap issue.
have you added your proxy as trusted proxy in cinfig.php?

# Nextcloud.snap -- edit config.php

edit the config.php by hand:

```
sudo nano /var/snap/nextcloud/current/nextcloud/config/config.php. 
```

## add trusted proxy ip/ips
```
  'trusted_proxies' => 
  array (
    0 => '192.168.2.xxx',
    1 => '192.168.2.xxx',
  ),
```

**Comment by kyrofa** [comment]
Very interesting. The pre-refresh hook is pretty basic, you can see that it just [uses curl](https://github.com/nextcloud-snap/nextcloud-snap/blob/master/src/hooks/bin/pre-refresh#L19). Curl respects the `{http,https}_proxy` environment variables. I assumed the `snap set system proxy` commands would set those for all snaps, perhaps they don't?
