### ISSUE TITLE
Cannot update to  24.0.7snap1  

### ISSUE THREAD

**Issue by Nadeem1967** [nextcloud-snap/nextcloud-snap#2242]
#### Describe the bug
I am using sudo snap refresh to update from 24.0.3snap1  and it fails and stays at 24.0.3snap1 

#### To Reproduce

sudo snap refresh and get an error starting "error: cannot perform the following tasks:
- Copy snap "nextcloud" data (cannot copy "/var/snap/nextcloud/31222" to "/var/snap/nextcloud/32537": failed to copy all: "'/var/snap/nextcloud/31222' -> '/var/snap/nextcloud/32537'\n'/var/snap/nextcloud/31222/redis' -> '/var/snap/nextcloud/32537/redis'\n'/var/snap/nextcloud/31222/redis/dump.rdb'..."

#### Expected behavior
I expect it to update to 24.0.7snap1  

#### Screenshots
[https://ibb.co/jTR14QP](url)

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  24.0.3snap1  31222  latest/stable  nextcloud✓  -

snap    2.57.6
snapd   2.57.6
series  16
ubuntu  22.04
kernel  5.15.0-56-generic

#### Logs

Output from terminal  [https://goonlinetools.com/snapshot/code/#843om4iactdisvjblq4w3f](url)

Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).

[https://goonlinetools.com/snapshot/code/#t8rlkzwaxfr40183ynk80t](url)

**Comment by kyrofa** [comment]
Any chance you're out of hard drive space?

**Comment by Nadeem1967** [comment]
doesn't seem to be;

loudeemy@loudeemy:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           770M  1.5M  768M   1% /run
/dev/sda2       457G  188G  246G  44% /
tmpfs           3.8G     0  3.8G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sdb1       916G  179G  691G  21% /media/Archive
/dev/sdc1       7.3T  4.7T  2.2T  69% /media/Seagate
/dev/sda1       511M  5.3M  506M   2% /boot/efi
tmpfs           770M  4.0K  770M   1% /run/user/1000

**Comment by Nadeem1967** [comment]
Seems I had a failing hard drive!! All fixed now with new drive.
