### ISSUE TITLE
Reset error log level

### ISSUE THREAD

**Issue by anibtro** [nextcloud-snap/nextcloud-snap#2243]
Hi to everybody.

My NC is a snap install and runs smoothly on my own MiniPC since almost one year. But during the automated update process to 24.07 last week the error log level seems to not have been reset correctly. 

I now see only fatals on the admin logging page,, but all the less important notifications (eg failed login attempts by bots) don't show up any more. I am not able to correct this via the admin page. Could anybody please direct me to how to do this manually? I do have access as su via ssh.

Many thanks in advance!

**Comment by scubamuc** [comment]
you can adjust the visible log level in Nextcloud settings;

![grafik](https://user-images.githubusercontent.com/54933878/205611510-64c0b751-1bd0-402e-a08e-66bd7e5f5968.png)

or adjust the log level in config.php;

**Nextcloud.snap -- edit config.php**

edit the config.php by hand:
`
sudo nano /var/snap/nextcloud/current/nextcloud/config/config.php. `

**Comment by anibtro** [comment]
Thank you very much, scubamuc, you helped me a lot!
But still the former log entries (unsucessful login attempts) don't show up any more in the listing.
The tail command gives me "no such file or directory".
Everything else works as expected.
Maybe the recent update changed the way the logfile is saved / displayed.

**Comment by scubamuc** [comment]
could you please run the "[Issue-Debugging-Script](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Issue-Debugging-Scripts)" as suggested?
that might give some more insight

**Comment by anibtro** [comment]
Thank you again, scubamuc, for your very detailed help!

1)
There's plenty of free disk space (17% used).

2) snap list nextcloud --all:

nextcloud  24.0.6snap1  31751  latest/stable  nextcloud✓  disabled
nextcloud  24.0.7snap1  32537  latest/stable  nextcloud✓  -

3)
I think logging is enabled. My config.php contains:

'log_type' => 'file',
'logfile' => '/var/snap/nextcloud/current/logs/nextcloud.log',
'logfilemode' => 416,
'loglevel' => 2,

4)
I've checked
/var/snap/nextcloud/current/logs/nextcloud.log
and it contains the same what shows up in the admin homepage. Could it be a problem with write permissions because of the different location? I mean because it's not in
/var/snap/nextcloud/common/nextcloud/data/ ?

Thanks a lot again! and best regards.

**Comment by scubamuc** [comment]
yes, permissions could be an issue concerning the log file path. 
as far as i'm aware the log file path should be in `/common/nextcloud/data/`.
i can only compare with my system and changes were not made.

@kyrofa do you have any idea if the update has any effect on the log file path?

**Comment by anibtro** [comment]
Thanks again for your help!

Another thought: Could it be that with the last NC update logging itself has changed? In a way that attempts of bot logins are not protocolled any more? Just wondering.

Anyway, I could try to change the logfile location to 
/common/nextcloud/data/
as you suggested. I would mv the existing logfile to its new destination and change the path in config.php accordingly. Would there be anything else to do, change permissions or something like that?

Thanks and best regards!

**Comment by scubamuc** [comment]
agree, change path and test. i'm not aware of any other changes required for log path

> Another thought: Could it be that with the last NC update logging itself has changed? In a way that attempts of bot logins are not protocolled any more? Just wondering.

not sure if changes took place, you could request information upstream.

**Comment by scubamuc** [comment]
hey, i've been thinking about the missing log for suspicious logins... is the app installed at all? possibly it was deactivated due to incompatibility. 
please check;
![grafik](https://user-images.githubusercontent.com/54933878/206783932-fd3d0435-2200-4776-8dca-8f8fd46f8364.png)

**Comment by anibtro** [comment]
This app wasn't installed! I have no idea why not, neither if it was before the recent update.
Anyway. I now downloaded and activated it. I will report tomorrow.
Again THANK YOU, scubamuc!

**Comment by anibtro** [comment]
Just an update: "suspicious logins" didn't log suspicious logins until yesterday. (?) I'll keep an exe on it.
