### ISSUE TITLE
I don't know why. I can't mount the local hard disk

### ISSUE THREAD

**Issue by mch-anmc** [nextcloud-snap/nextcloud-snap#2255]
I don't know why. I can't mount the local hard disk

![20221218230041](https://user-images.githubusercontent.com/62496094/208305483-71dd53ce-fa03-4c04-9536-b2701cb2ca47.png)

    $ snap list nextcloud
```
sudo snap list nextcloud
名称         版本           修订版本   追踪             发布者         注记
nextcloud  24.0.7snap1  32537  latest/stable  nextcloud✓  -
```
and:

    $ snap version

```
snap    2.57.6
snapd   2.57.6
series  16
ubuntu  22.04
kernel  5.15.0-56-generic
```
 
This is a log.

```
[PHP] 错误: Error: opendir(/home/homeserver/): Failed to open directory: Permission denied at /snap/nextcloud/32537/htdocs/lib/private/Files/Storage/Local.php#143 at <<closure>>

 0. <<closure>>
    OC\Log\ErrorHandler::onError()
 1. /snap/nextcloud/32537/htdocs/lib/private/Files/Storage/Local.php line 143
    opendir()
 2. /snap/nextcloud/32537/htdocs/lib/private/Files/Storage/Common.php line 884
    OC\Files\Storage\Local->opendir()
 3. /snap/nextcloud/32537/htdocs/lib/private/Files/Storage/Wrapper/PermissionsMask.php line 157
    OC\Files\Storage\Common->getDirectoryContent()
 4. <<closure>>
    OC\Files\Storage\Wrapper\PermissionsMask->getDirectoryContent()
 5. /snap/nextcloud/32537/htdocs/lib/private/Files/Cache/Scanner.php line 410
    iterator_to_array()
 6. /snap/nextcloud/32537/htdocs/lib/private/Files/Cache/Scanner.php line 390
    OC\Files\Cache\Scanner->handleChildren()
 7. /snap/nextcloud/32537/htdocs/lib/private/Files/Cache/Scanner.php line 342
    OC\Files\Cache\Scanner->scanChildren()
 8. /snap/nextcloud/32537/htdocs/lib/private/Files/View.php line 1360
    OC\Files\Cache\Scanner->scan()
 9. /snap/nextcloud/32537/htdocs/lib/private/Files/View.php line 1400
    OC\Files\View->getCacheEntry()
10. /snap/nextcloud/32537/htdocs/lib/private/Files/Node/Root.php line 205
    OC\Files\View->getFileInfo()
11. /snap/nextcloud/32537/htdocs/lib/private/Files/Node/LazyUserFolder.php line 59
    OC\Files\Node\Root->get()
12. /snap/nextcloud/32537/htdocs/apps/text/lib/Controller/WorkspaceController.php line 122
    OC\Files\Node\LazyUserFolder->get()
13. /snap/nextcloud/32537/htdocs/lib/private/AppFramework/Http/Dispatcher.php line 225
    OCA\Text\Controller\WorkspaceController->folder()
14. /snap/nextcloud/32537/htdocs/lib/private/AppFramework/Http/Dispatcher.php line 133
    OC\AppFramework\Http\Dispatcher->executeController()
15. /snap/nextcloud/32537/htdocs/lib/private/AppFramework/App.php line 172
    OC\AppFramework\Http\Dispatcher->dispatch()
16. /snap/nextcloud/32537/htdocs/lib/private/Route/Router.php line 298
    OC\AppFramework\App::main()
17. /snap/nextcloud/32537/htdocs/ocs/v1.php line 62
    OC\Route\Router->match()
18. /snap/nextcloud/32537/htdocs/ocs/v2.php line 23
    require_once("/snap/nextcloud/32537/htdocs/ocs/v1.php")
```

**Comment by kyrofa** [comment]
`/home/homeserver` will be entirely inaccessible to the snap due to its confinement. Try mounting it in `/media/` or `/mnt/`, and then `snap connect nextcloud:removable-media`, and it should work.

**Comment by mch-anmc** [comment]
Thank you.

I installed nextcloud using homeserver, and I used ` sudo chmod - R 777 xxx` for xxx folder.
![20221218230041](https://user-images.githubusercontent.com/62496094/208306705-4549fcde-84d0-4541-9e80-b1f73def78c9.png)

I'll try your method.

**Comment by kyrofa** [comment]
> I used sudo chmod - R 777 xxx for xxx folder

I'm afraid it doesn't matter. It's not a permissions issue, it's a _confinement_ issue. The Linux kernel won't allow the snap to touch your home directory.

**Comment by mch-anmc** [comment]
> > 我使用 sudo chmod - R 777 xxx 为 xxx 文件夹
> 
> 恐怕没关系。这不是权限问题，而是_禁闭_问题。Linux 内核不允许快照接触您的主目录。

Oh, well, thanks. I'll try it your way now.

**Comment by mch-anmc** [comment]
Thank you very much. I succeeded in your way. 

I want to ask why last time (about half a year ago) I was on the raspberry 4B, I could mount the hard disk under '/home/xxx/data'

> > I used sudo chmod - R 777 xxx for xxx folder
> 
> I'm afraid it doesn't matter. It's not a permissions issue, it's a _confinement_ issue. The Linux kernel won't allow the snap to touch your home directory.

**Comment by kyrofa** [comment]
If you're using a non-Ubuntu operating system, snap confinement is entirely broken. It's the primary reason we don't support non-Ubuntu operating systems, here.

**Comment by mch-anmc** [comment]
> If you're using a non-Ubuntu operating system, snap confinement is entirely broken. It's the primary reason we don't support non-Ubuntu operating systems, here. You were using raspbian, I assume? Not surprising, then.

Oh, so it is.

Yes, the last time I used raspbian, I said how to configure nextcloud according to the last method.

Thank you for your help.

**Comment by scubamuc** [comment]
you could [bypass snap confinement](https://github.com/scubamuc/scubamuc.github.io/blob/scubamuc/wiki-md/NEXTCLOUD.snap--snap-confinement.md) in a local network
