### ISSUE TITLE
nextCloud want to "opcache.interned_strings_buffer=8"

### ISSUE THREAD

**Issue by neeks76** [nextcloud-snap/nextcloud-snap#2261]
My nextCloud request to "opcache.interned_strings_buffer=8"

To change php.ini, I tried it at /snap/nextcloud/32871/config/php/php.ini

But, I couldn't edit it becatuse of Read-only file system.
chmod, remount, all of that can't avoid write-protected.

Could you show me how to change?

**Comment by scubamuc** [comment]
@neeks76 
see here #2024 
maybe you can help devs? 
otherwise stand by...

**Comment by kyrofa** [comment]
Indeed, dupe of #2024.
