### ISSUE TITLE
How to change certificate domain

### ISSUE THREAD

**Issue by MrMid** [nextcloud-snap/nextcloud-snap#2262]
Some time ago, I changed my domain name, in Nextcloud I've changed the overwriteDomain param, disabled and re-enabled https with `nextcloud.enable-https lets-encrypt`.

All went well, except when I access my server from a browser, I get a certificate that's old and with the original domain.

Did I miss something?

**Comment by scubamuc** [comment]
**Change Nextcloud Lets Encrypt Domain**

1. Disable Lets Encrypt

2. Remove all current Certificates

3. Get new Certificates

disable HTTPS (this just removes a symlink, it doesn’t remove any certs):

`$ sudo nextcloud.disable-https`


remove all/any certificates that are there (this includes self-signed certs, Let’s Encrypt certs, everything). Make sure you get this command right, you don’t want to delete anything else in the current/ dir:

`$ sudo rm -rf /var/snap/nextcloud/current/certs`


pretend you’re enabling HTTPS for the first time, using only the domains you want:

`$ sudo nextcloud.enable-https lets-encrypt`

**Comment by MrMid** [comment]
Thank you for your reply!

But I was too quick to act on your advice. I removed the certs folder and when enabling the https again, I got `error running certbot, certs/certbot missing`.

I restored it from an earlier copy, but I cannot find what to remove in the certs folder so the certbot would run well.

Certbot docs didn't help, as these are using the certbot executable, which isn't part of this snap.

Do you have any further advice?

**Comment by scubamuc** [comment]
See #406

**Comment by MrMid** [comment]
Thank you! https://github.com/nextcloud-snap/nextcloud-snap/issues/406#issuecomment-999510141 helped.

As I had no simple way of restoring the original state of the folder, temporarily installing certbot was a nice solution. Maybe you and @kyrofa could include it (or at least warn) in your answers?

Anyways, keep up the great job! I had a nextcloud install using docker, and it was a huge pain to maintain. The snap works flawlessly.
