### ISSUE TITLE
Nextcloud 25.0.2snap1 - text distorted

### ISSUE THREAD

**Issue by Bif-jackson** [nextcloud-snap/nextcloud-snap#2264]
#### Text distorted - difficult to read after auto upgrade from 24.0.8snap1 to 25.0.2snap1
Text on nextcloud site is not clear after upgrade to 25.0.2snap1 .

#### To Reproduce
1. running nextcloud 24.0.8snap1 on Ubuntu 20.04.5 LTS (snap channel 'stable')
2. Nextcloud snap auto-updates to nextcloud 25.0.2snap1
3. Nextcloud text on web browser appears distorted

#### Expected behavior
Text is unaffected after update

#### Text using 25.0.2 snap (distorted text)
![2023-01-01_23-16](https://user-images.githubusercontent.com/101933121/210196248-b320d4c7-8351-4e98-9d59-1956ea55cfcb.png)

#### Text after reverting to 24.0.8 snap (normal appearance)
![2023-01-01_23-17](https://user-images.githubusercontent.com/101933121/210196282-21f31f77-89ee-4dbf-aefe-b3973849a2c4.png)

#### OS/snapd/snap version
What OS and version are you running? 
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"

Please also include the output of the
following commands:

    $ snap list nextcloud
    Name       Version      Rev    Tracking       Publisher   Notes
    nextcloud  24.0.8snap1  32871  latest/stable  nextcloud✓  disabled
    nextcloud  25.0.2snap1  33054  latest/stable  nextcloud✓  -

and:

    $ snap version
    snap    2.57.6
    snapd   2.57.6
    series  16
    ubuntu  20.04
    kernel  5.4.0-135-generic

#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).

After snap revert nextcloud
[log.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/10330071/log.txt)

**Comment by scubamuc** [comment]
![grafik](https://user-images.githubusercontent.com/54933878/210349234-015695b6-3963-446f-b0f5-b6264def4f30.png)

**Comment by Bif-jackson** [comment]
Thanks scubamuc,
I incorrectly thought it was related to the snap upgrade.  It was activated in 24.0.8, but  it appears differently in 25.0.2.
Never-the-less this is not a snap issue.
