### ISSUE TITLE
System monitoring can't access temperature

### ISSUE THREAD

**Issue by FilipHoertner** [nextcloud-snap/nextcloud-snap#2266]
#### Describe the bug
In the system monitoring, no temperature is shown in the corresponding area.

#### To Reproduce
Go to Settings > System, the temperature value is on the upper right side.

#### Expected behavior
I think it should draw a graph like with CPU and RAM, but there should at least be a value visible.

#### Screenshots
![Bildschirm­foto 2023-01-05 um 12 45 19](https://user-images.githubusercontent.com/37515756/210773223-15c5a71e-a3a2-4cc5-bdc0-0238339adad8.png)

#### OS/snapd/snap version
OS: Ubuntu 20.04.5 LTS (GNU/Linux 5.4.0-135-generic x86_64)

$ snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  25.0.2snap1  33054  latest/stable  nextcloud✓  -

$ snap version
snap    2.57.6
snapd   2.57.6
series  16
ubuntu  20.04
kernel  5.4.0-135-generic

#### Logs
I think the relevant part is the following output in the syslog, as nextcloud is not able to read the temperature, but I can also share the full log if useful.

```
Jan  5 11:35:31 ubuntunextcloud kernel: [1211761.978032] audit: type=1400 audit(1672918531.015:882155): apparmor="DENIED" operation="open" profile="snap.nextcloud.php-fpm" name="/sys/devices/virtual/thermal/thermal_zone0/type" pid=1855426 comm="php-fpm" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
```

**Comment by kyrofa** [comment]
I don't believe snapd supports confined access to temperature data, but [I asked](https://forum.snapcraft.io/t/interface-to-access-temperature-sensors/33781) to double check. Waiting on a response.
