### ISSUE TITLE
Cron Job failed after Update from 24.0.8 to 25.0.2

### ISSUE THREAD

**Issue by Krumpatz** [nextcloud-snap/nextcloud-snap#2270]
I updated to Version 25 and after a few hours there is a warning in the dashboard that the last run of the cron job was aproxx the last time system restart.

An woraround via Webcron does not run all tasks (waring is still there). I tried to start it normally within the snap php installation and got a error while loading shared libraries: libargon2.so.0: cannot open shared object file: No such file or directory.

I also tried to use the snap command for the cron intervall time, and nothing worked (but the comand ran without any feedback, so i think it was set correctly).

Now i reverted to 24.0.8 and the cron job works.

Thanks for all your work, my family is using the snap for 4 Years now with only minor problems.

**Comment by kyrofa** [comment]
Can we see some [logs](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Issue-Debugging-Scripts), please?

**Comment by Krumpatz** [comment]
I am sorry, since it was a production system i reverted quite early. I know that my request is useless without any logs ;-(. 
My hope is that someone else does have simmilar problems.

Before i will try Version 25 again (and look for logs) id like to ask if there a way  start the cron job inside the snap manually?

**Comment by scubamuc** [comment]
maybe this could help :https://github.com/scubamuc/scubamuc.github.io/blob/scubamuc/wiki-md/NEXTCLOUD.snap--restart_cron.md to start cron manually.

**Comment by Krumpatz** [comment]
Thanks for your help. I rereverded (known as update ) to 25.0.2 again and with the comands i was able to fix it.
Have you published them right after my post or have i totally overseen something?
