### ISSUE TITLE
nextcloud data directory to zfs pool

### ISSUE THREAD

**Issue by grkravi** [nextcloud-snap/nextcloud-snap#2279]
I installed nextcloud using snap on ubuntu 22.04. I was not able to change to a different data directory at all. I have a zfs pool setup and could not change data dir to zfs pool. I followed instructions on the wiki but everytime i keep getting this error - "Your data directory is invalid. Ensure there is a file called ".ocdata" in the root of the data directory. Cannot create "data" directory. This can usually be fixed by giving the web server write access to the root directory. See https://docs.nextcloud.com/server/25/go.php?to=admin-dir_permissions". I tried linking the /media/nextcloud folder to zfs pool and moved the data dir from its original var folder to the media folder and nothing worked. Any suggestions?

**Comment by scubamuc** [comment]
dup of  https://github.com/nextcloud-snap/nextcloud-snap/issues/2203
