### ISSUE TITLE
onlyoffice with snapd

### ISSUE THREAD

**Issue by gnosisd** [nextcloud-snap/nextcloud-snap#2287]
since you are already making a great work may i suggest create also a snapd for onlyoffice ready inside nextcloud pre installed?
since it is really difficult to make it working also when you try to install via community app you get a lot of problems such as no co editing empty pdf files when downloading etc or at lease give instructions of how you can actually make it work on a self hosted server or some options suck us a localhost server inside an intranet etc !!!

but you are doing a really great job already !!!

**Comment by kyrofa** [comment]
Sorry, we can't support individual apps. If apps have trouble running from within the snap, they'll need to care enough to make it work. Going the other way around (having us support every app) just doesn't scale, and ultimately doesn't work anyway: we don't have the power to make changes in those apps. Only they do.

**Comment by gnosisd** [comment]
alright thanks for the answer !!!

**Comment by adrianvg** [comment]
And then there are those of us who don't want OnlyOffice installed per default. Just saying...
