### ISSUE TITLE
Nextcloud-snap "feature request" nextcloud-office

### ISSUE THREAD

**Issue by scubamuc** [nextcloud-snap/nextcloud-snap#2288]
for several years now I've been a Nextcloud-snap user. The great community here and the tireless commitment of the team have convinced me of this Snap-project.

Not only my self-hosted Nextcloud, but also further instances I've implemented are based on Nextcloud-snap. 
Considerable effort has gone into support, [documentation](https://scubamuc.github.io/) and automation.

Current instances include: 
- 	corporate instance -- 120 Users
- 	3x private RPi instances -- 3x 1-5 users
- 	self-hosted server -- 5 users

There are but a handful of Nextcloud Hub 3 features that are not available in Nextcloud-snap. One of the selling points of Nextcloud is "nextcloud office" allowing collaborative document processing and is frequently requested by corporate users. 

I've tried different solutions, yet even a standalone CODE server instance connecting to Nextcloud-snap was unsuccessful.

Document processing in Nextcloud-snap would be a killer feature for Nextcloud-snap. This has been discussed here previously and I acknowledge the challenges. 

Nonetheless I'd like to request this feature in Nextcloud-snap.

**Comment by vawaver** [comment]
I would like to add to this request.
I use the snap version from version 18 on my servers.
Actually, there are 3 servers but it's a pity no office online document editing is possible.
It would be great to offer this option to my users on these Nextcloud servers.

**Comment by scubamuc** [comment]
I'm assuming its not a Nextcloud-snap issue here... more like a CODE issue. 
CODE is running and available through NGINX-reverse proxy:

![grafik](https://user-images.githubusercontent.com/54933878/214102395-7aeffe4f-ef57-4543-ad37-bfd85e42c17c.png)



![grafik](https://user-images.githubusercontent.com/54933878/214099801-32b55d11-8967-4db5-82fe-35d95606cb48.png)

`curl https://office.example.com/hosting/capabilities`

![grafik](https://user-images.githubusercontent.com/54933878/214100250-8d313e72-8daf-46a4-a43a-e53478a836d6.png)

`NC-snap log shows nothing regarding CODE`

![grafik](https://user-images.githubusercontent.com/54933878/214099485-eba5af3a-7c82-45eb-90e6-4f80abe75e51.png)

Nextcloud office admin panel:

![grafik](https://user-images.githubusercontent.com/54933878/214101219-f26525a0-8655-4f0f-9133-5e521b7f078d.png)

@kyrofa please contact me if you'd like to debug this... i've documented carefully and would gladly assist.

**Comment by scubamuc** [comment]
More verbose output here:
![grafik](https://user-images.githubusercontent.com/54933878/214111607-67776317-d0f8-42b0-875a-0d93b819fbcf.png)

**Comment by NaXal** [comment]
I would vote for this also. I understand that it is not possible for the snap team to add or support every other odd app but nextcloud office would be really nice. Infact one of the biggest selling for nextcloud itself is the office and collaboration ability.

So I too vote for this.

If possible, please do consider adding Nextcloud office to snap package.

Thanks.

**Comment by kyrofa** [comment]
> If possible, please do consider adding Nextcloud office to snap package.

To be clear, we will not be doing this. It's not a default app, and it's tremendously unstable in my experience. It used to work in the snap, now it doesn't, and they don't really care, so I'm afraid it's the users that pay the price here. I don't have the ability to make changes there, so I can't just make it work and keep it working.

Even ignoring all that, the fact that @scubamuc can't even get it working standalone makes the whole thing look pretty darn grim to me.

**Comment by scubamuc** [comment]
> To be clear, we will not be doing this. It's not a default app, and it's tremendously unstable in my experience. It used to work in the snap, now it doesn't, and they don't really care, so I'm afraid it's the users that pay the price here.

@kyrofa agreed, thanks for looking into it.

corporate users will have to move to a different instance if this request is a show stopper for the nextcloud-snap.
sad, but so be it... 

as for private and self-hosted instances, snap is the way to go

**Comment by scubamuc** [comment]
![grafik](https://user-images.githubusercontent.com/54933878/216956283-bdae59b3-ffbf-4a68-be71-ca8bb4b65c3f.png)

**Comment by vawaver** [comment]
> ![grafik](https://user-images.githubusercontent.com/54933878/216956283-bdae59b3-ffbf-4a68-be71-ca8bb4b65c3f.png)

Can you please share a tutorial on how to make it work? I fight with the settings from 11-2022, with no success.

**Comment by scubamuc** [comment]
https://nextcloud.com/blog/how-to-install-onlyoffice-in-nextcloud-hub-and-new-integration-feature/

**Comment by vawaver** [comment]
> https://nextcloud.com/blog/how-to-install-onlyoffice-in-nextcloud-hub-and-new-integration-feature/

Greetings, I finally resolve this. Nextcloud Snap + Onlyoffice online are finally working!!!

**Comment by scubamuc** [comment]
> Even ignoring all that, the fact that @scubamuc can't even get it working standalone makes the whole thing look pretty darn grim to me. If I get some time I can poke at it, but time is in short supply.

@kyrofa would you like me to share my LXC office container? I could also share my docs... just give me a shout 👍

**Comment by scubamuc** [comment]
See working **CODE & Nextcloud office** configuration here: https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-CODE-and-Nextcloud-office-for-Nextcloud-snap
