### ISSUE TITLE
Email Server doesn't work

### ISSUE THREAD

**Issue by TechXero** [nextcloud-snap/nextcloud-snap#2289]
#### Describe the bug

I am new to NextCloud, I just got a Ubuntu Linode and installed Nextcloud via snap and added it to my own subdomain.. All went well except I cannot get Email server to work with any email service I use, be it Outlook, gmail, Vivaldi webmail etc.. And yes I have checked that I can access them from outside apps.. I been working on this all day reading various reports and solutions nothing works.. All I get is this error with every single one...

#### To Reproduce
1. Go to 'email server'
2. Configure it
3. See error

#### Expected behavior
for it to successfully work

#### Screenshots
![error](https://i.imgur.com/KvIvXIy.png)

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud
`nextcloud  25.0.2snap1  33054  latest/stable  nextcloud✓ `

and:

    $ snap version

```
snap    2.58
snapd   2.58
series  16
ubuntu  22.10
kernel  5.19.0-29-generic
```

#### Logs
https://notes.xerolinux.xyz/?f7e7e6871ce1eef1#3Y11gwR3PGheVa55u3syAdq28Yx8AunXEFJWotshzxqY

**Comment by solracsf** [comment]
https://www.websitebuilderinsider.com/does-linode-block-port-587/

**Comment by TechXero** [comment]
I tried other ports as well same result

**Comment by Vysp3r** [comment]
I had to mess around a lot, but got it working at one point. Just keep trying.
