### ISSUE TITLE
Wrong folder sizes after update to Netxcloud 25.0.2snap1

### ISSUE THREAD

**Issue by dasaweb** [nextcloud-snap/nextcloud-snap#2290]
After the update from `24.0.8snap1` to `25.0.2snap1` the folder sizes shown in the web frontend and in the sync client are wrong.

#### Example

I have a folder called "Mail" with an alleged size of "2GB". Inside that folder there is (among other folders) a folder "Archive", and this folder alone shows 4GB. Inside that "Archive" folder is a folder called "Daniel", this folder has 20.4 GB (and that size seems to be shown correctly, mabe because inside that folder are only a few files and two folders with no subfolders).

#### System information

I'm running Nextcloud Snap on an **32 bit** system (Ubuntu 18.04.6 LTS) on an ODROID HC2 (armv7l).

#### Logs

see [debug.log](https://github.com/nextcloud-snap/nextcloud-snap/files/10517195/debug.log)

**Comment by dasaweb** [comment]
FYI: I'm now on 25.0.3snap2, still the same.

**Comment by dasaweb** [comment]
I checked some issues and discussion on the Nextcloud server repo on Github (https://github.com/nextcloud/server/issues/33768 and https://github.com/nextcloud/server/issues/25283 and ...) and then tried to rescan all my files. And what can I say, the folder sizes are correct again. I have no idea why the update generated incorrect values, but whatever. Will close the issue here. Thanks a lot!

**Comment by dasaweb** [comment]
Ha, updated to 25.0.3snap3 this night, and boom: folder sizes are wrong again. After rescanning all the files (`sudo nextcloud.occ files:scan`) everything is fine again. Could it be that the update process is messing something up?

**Comment by kyrofa** [comment]
Huh, that's odd. I wouldn't think so-- that latest update shouldn't have run an upgrade process at all. Once you have them fixed again, what happens if you run `sudo snap restart nextcloud`? Are they wrong again?

**Comment by dasaweb** [comment]
Restarting, good point. Just tried that, but after the restart the folder sizes were still correct, no rescan of the files needed. Hmmmm...

**Comment by dasaweb** [comment]
This night my snap updated to 25.0.4snap1: No wrong folder sizes! No idea, what's going on, so I will close this issue for now.
