### ISSUE TITLE
Resetting a lost admin password

### ISSUE THREAD

**Issue by engerex** [nextcloud-snap/nextcloud-snap#2291]
Hello,

I don't remember the admin password. I want to reset. The method below doesn't work. How can I reset the admin password?

_$ sudo -u www-data php /var/www/nextcloud/occ user:resetpassword admin
sudo: php: command not found_

https://docs.nextcloud.com/server/22/admin_manual/configuration_user/reset_admin_password.html

**Comment by kyrofa** [comment]
Yeah we could make this a little more prominent in the README, huh. Everywhere you see `sudo -u www-data php /var/www/nextcloud/occ`, in the snap, replace that with `sudo nextcloud.occ`.
