### ISSUE TITLE
another apparmor denial

### ISSUE THREAD

**Issue by bjhgov** [nextcloud-snap/nextcloud-snap#2292]
Hello, and thanks for a nice snap.

This bug seems to be repeatable.

I am using 25.0.2snap1 running on Linux Mint Mate 21.1 (VirtualBox).  
Apparmor denies and mysql crashes whenever I select the "Photos" view from the top menu.

Jan 31 08:31:36 linuxmint-vm kernel: [  236.284023] audit: type=1400 audit(1675171896.335:63): apparmor="DENIED" operation="mknod" profile="snap.nextcloud.php-fpm" name="/root/.rnd" pid=4919 comm="php-fpm" requested_mask="c" denied_mask="c" fsuid=0 ouid=0
Jan 31 08:31:36 linuxmint-vm kernel: [  236.284030] audit: type=1400 audit(1675171896.335:64): apparmor="DENIED" operation="mknod" profile="snap.nextcloud.php-fpm" name="/root/.rnd" pid=4919 comm="php-fpm" requested_mask="c" denied_mask="c" fsuid=0 ouid=0
Jan 31 08:33:26 linuxmint-vm kernel: [  346.276298] audit: type=1400 audit(1675172006.319:65): apparmor="DENIED" operation="ptrace" profile="snap.nextcloud.mysql" pid=5077 comm="ps" requested_mask="read" denied_mask="read" peer="unconfined"
Jan 31 08:33:26 linuxmint-vm kernel: [  346.276602] audit: type=1400 audit(1675172006.319:66): apparmor="DENIED" operation="ptrace" profile="snap.nextcloud.mysql" pid=5077 comm="ps" requested_mask="read" denied_mask="read" peer="unconfined"
Jan 31 08:33:26 linuxmint-vm kernel: [  346.276717] audit: type=1400 audit(1675172006.319:67): apparmor="DENIED" operation="ptrace" profile="snap.nextcloud.mysql" pid=5077 comm="ps" requested_mask="read" denied_mask="read" peer="unconfined"
Jan 31 08:33:26 linuxmint-vm kernel: [  346.276882] audit: type=1400 audit(1675172006.319:68): apparmor="DENIED" operation="ptrace" profile="snap.nextcloud.mysql" pid=5077 comm="ps" requested_mask="read" denied_mask="read" peer="unconfined"
Jan 31 08:33:26 linuxmint-vm kernel: [  346.276975] audit: type=1400 audit(1675172006.319:69): apparmor="DENIED" operation="ptrace" profile="snap.nextcloud.mysql" pid=5077 comm="ps" requested_mask="read" denied_mask="read" peer="unconfined"
Jan 31 08:33:26 linuxmint-vm kernel: [  346.277064] audit: type=1400 audit(1675172006.319:70): apparmor="DENIED" operation="ptrace" profile="snap.nextcloud.mysql" pid=5077 comm="ps" requested_mask="read" denied_mask="read" peer="unconfined"
Jan 31 08:33:26 linuxmint-vm kernel: [  346.277156] audit: type=1400 audit(1675172006.319:71): apparmor="DENIED" operation="ptrace" profile="snap.nextcloud.mysql" pid=5077 comm="ps" requested_mask="read" denied_mask="read" peer="unconfined"
Jan 31 08:33:26 linuxmint-vm kernel: [  346.277259] audit: type=1400 audit(1675172006.319:72): apparmor="DENIED" operation="ptrace" profile="snap.nextcloud.mysql" pid=5077 comm="ps" requested_mask="read" denied_mask="read" peer="unconfined"
Jan 31 08:33:26 linuxmint-vm kernel: [  346.277349] audit: type=1400 audit(1675172006.319:73): apparmor="DENIED" operation="ptrace" profile="snap.nextcloud.mysql" pid=5077 comm="ps" requested_mask="read" denied_mask="read" peer="unconfined"
Jan 31 08:33:26 linuxmint-vm kernel: [  346.277434] audit: type=1400 audit(1675172006.319:74): apparmor="DENIED" operation="ptrace" profile="snap.nextcloud.mysql" pid=5077 comm="ps" requested_mask="read" denied_mask="read" peer="unconfined"
Jan 31 08:33:26 linuxmint-vm nextcloud.mysql[5092]:  * MySQL server PID file could not be found!
Jan 31 08:33:56 linuxmint-vm systemd[1]: snap.nextcloud.mysql.service: State 'stop-sigterm' timed out. Killing.
Jan 31 08:33:56 linuxmint-vm systemd[1]: snap.nextcloud.mysql.service: Killing process 1860 (mysqld_safe) with signal SIGKILL.
Jan 31 08:33:56 linuxmint-vm systemd[1]: snap.nextcloud.mysql.service: Killing process 5093 (mysqld) with signal SIGKILL.
Jan 31 08:33:56 linuxmint-vm systemd[1]: snap.nextcloud.mysql.service: Killing process 5138 (mysqld) with signal SIGKILL.
Jan 31 08:33:56 linuxmint-vm systemd[1]: snap.nextcloud.mysql.service: Killing process 5139 (mysqld) with signal SIGKILL.
Jan 31 08:33:56 linuxmint-vm systemd[1]: snap.nextcloud.mysql.service: Killing process 5141 (mysqld) with signal SIGKILL.
Jan 31 08:33:56 linuxmint-vm systemd[1]: snap.nextcloud.mysql.service: Killing process 5142 (mysqld) with signal SIGKILL.
Jan 31 08:33:56 linuxmint-vm systemd[1]: snap.nextcloud.mysql.service: Killing process 5143 (n/a) with signal SIGKILL.
Jan 31 08:33:56 linuxmint-vm systemd[1]: snap.nextcloud.mysql.service: Killing process 5144 (n/a) with signal SIGKILL.

Thx, B.

**Comment by scubamuc** [comment]
duplicate of https://github.com/nextcloud-snap/nextcloud-snap/issues/1270#issuecomment-605504292
