### ISSUE TITLE
-- disable renew-certs, certs over reverse proxy --

### ISSUE THREAD

**Issue by scubamuc** [nextcloud-snap/nextcloud-snap#2298]
certification in nextcloud-snap is disabled in favour of reverse proxy termination. 

may the service `nextcloud.renew-service` be disabled or could this break something?

#### To Reproduce
disable https `nextcloud.disable-https`
see service is still enabled, checks cause minimal regular unnecessary cpu usage 

#### Expected behavior
Service is disabled

#### Screenshots
![grafik](https://user-images.githubusercontent.com/54933878/216941970-a7a7be56-bf3f-4e7b-8781-3a0116880b4e.png)

**Comment by kyrofa** [comment]
Oh sure, you can disable it without consequence if you're not using snap-provided HTTPS.

**Comment by scubamuc** [comment]
> From the referenced certbot bug:
> 
>     `sudo snap stop --disable certbot.renew`
> That sounds like a legit snapd bug.

```
sudo snap stop --disable certbot.renew
error: snap "certbot" has no service "renew"
```

**issue correct command:**
```
sudo snap stop --disable nextcloud.renew-certs
Stopped
```
![grafik](https://user-images.githubusercontent.com/54933878/217049851-47d4439a-814b-4fb1-9029-01d07928795b.png)

many thanks
