### ISSUE TITLE
Update removes logo, header logo, and favicon on every update

### ISSUE THREAD

**Issue by ph00lt0** [nextcloud-snap/nextcloud-snap#2299]
As title says, this happens every update of the instances using snap.

**Comment by aquananu** [comment]
yes i confirm same is also happening with me

**Comment by scubamuc** [comment]
be sure to disable user-settings

![grafik](https://user-images.githubusercontent.com/54933878/216994883-c3e2a9dc-77ed-407f-b523-bcf422314692.png)

**Comment by scubamuc** [comment]
this is not a Nextcloud-snap issue 
it seems to be a general Nextcloud issue, see here;
https://help.nextcloud.com/t/background-image-favicon-icon-etc-gone-after-updating-to-nextcloud-25/151807

**Comment by scubamuc** [comment]
> Strange cuz i do not have this on other non snap instances

@kyrofa any ideas?

**Comment by kyrofa** [comment]
I'm afraid not, no, sorry @ph00lt0! That's an app with which I have zero experience. I also can't explain why one snap would do this and another wouldn't. You're sure they're the same revision? If so, they are binary identical except for third-party apps and configuration.
