### ISSUE TITLE
Embedded upload shared folder link gives http error 500.

### ISSUE THREAD

**Issue by smokingwheels** [nextcloud-snap/nextcloud-snap#2307]
#### Describe the bug
Accessing an upload shared folder give Http error 500 after not being connected to LAN web server for sometime.
https://twitter.com/smokingwheels/status/1623155529030766593

#### To Reproduce
1. leave disconnected for sometime
2. Click on Embedded link in QB64 Web page. Note: Works after connecting to server.
4. Http Error 500.

#### Expected behavior
Web server not to give error 500

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:
Ubuntu 22.04 
nextcloud  25.0.3snap1  33493  latest/stable  nextcloud✓  -

snap    2.58+22.04
snapd   2.58+22.04
series  16
ubuntu  22.04
kernel  5.15.0-58-generic
  

#### Logs
http://gts.undo.it/index.php/s/bGMrxgmbjr7bofL

**Comment by scubamuc** [comment]
could we see your log for certbot:   `/var/snap/nextcloud/current/certs/certbot/logs/letsencrypt.log`

**Comment by smokingwheels** [comment]
Looks fine. I don.t use https yet.

`2023-02-16 15:57:01,403:DEBUG:certbot.main:certbot version: 0.33.1
2023-02-16 15:57:01,403:DEBUG:certbot.main:Arguments: ['--text', '--config-dir', '/var/snap/nextcloud/current/certs/certbot/config', '--work-dir', '/var/snap/nextcloud/current/certs/certbot/work', '--logs-dir', '/var/snap/nextcloud/current/certs/certbot/logs', '--post-hook', 'restart-apache']
2023-02-16 15:57:01,403:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#nextcloud:webroot,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2023-02-16 15:57:01,414:DEBUG:certbot.log:Root logging level set at 20
2023-02-16 15:57:01,414:INFO:certbot.log:Saving debug log to /var/snap/nextcloud/current/certs/certbot/logs/letsencrypt.log
2023-02-16 15:57:01,415:DEBUG:certbot.renewal:no renewal failures`

**Comment by scubamuc** [comment]
please post logs: https://github.com/nextcloud-snap/nextcloud-snap/wiki/Issue-Debugging-Scripts

**Comment by smokingwheels** [comment]
[http://gts.undo.it/index.php/s/JJ6gdpqg3Xsspor](http://gts.undo.it/index.php/s/JJ6gdpqg3Xsspor)

**Comment by scubamuc** [comment]
you should enable https and set [FQDN ](https://github.com/scubamuc/scubamuc.github.io/blob/scubamuc/wiki-md/NEXTCLOUD.snap--set_FQDN.md) in `/etc/hosts` to resolve following log issues

your log:
```
Feb 07 09:02:28 cloud-party nextcloud.apache[606019]: No certificates are active: using HTTP only
Feb 07 09:02:28 cloud-party nextcloud.apache[606204]: error: cannot communicate with server: Post "http://localhost/v2/snapctl": read unix @->/run/snapd-snap.socket: read: connection reset by peer
Feb 07 09:02:28 cloud-party nextcloud.apache[606209]: error: cannot communicate with server: Post "http://localhost/v2/snapctl": read unix @->/run/snapd-snap.socket: read: connection reset by peer
Feb 07 09:02:28 cloud-party nextcloud.apache[606217]: error: cannot communicate with server: Post "http://localhost/v2/snapctl": read unix @->/run/snapd-snap.socket: read: connection reset by peer
Feb 07 09:02:28 cloud-party nextcloud.apache[606019]: HTTP compression is disabled
Feb 07 09:02:28 cloud-party nextcloud.apache[606281]: error: cannot communicate with server: Post "http://localhost/v2/snapctl": read unix @->/run/snapd-snap.socket: read: connection reset by peer
Feb 07 09:02:28 cloud-party nextcloud.apache[606300]: error: cannot communicate with server: Post "http://localhost/v2/snapctl": EOF
Feb 07 09:02:28 cloud-party nextcloud.apache[606335]: error: cannot communicate with server: Post "http://localhost/v2/snapctl": EOF
Feb 07 09:02:28 cloud-party nextcloud.apache[606341]: error: cannot communicate with server: Post "http://localhost/v2/snapctl": EOF
Feb 07 09:02:28 cloud-party nextcloud.apache[606346]: error: cannot communicate with server: Post "http://localhost/v2/snapctl": EOF
Feb 07 09:02:28 cloud-party nextcloud.apache[606351]: error: cannot communicate with server: Post "http://localhost/v2/snapctl": EOF
Feb 07 09:02:28 cloud-party nextcloud.apache[606357]: error: cannot communicate with server: Post "http://localhost/v2/snapctl": EOF
Feb 07 09:02:28 cloud-party nextcloud.apache[606362]: error: cannot communicate with server: Post "http://localhost/v2/snapctl": EOF
Feb 07 09:02:28 cloud-party nextcloud.apache[606367]: error: cannot communicate with server: Post "http://localhost/v2/snapctl": EOF
Feb 07 09:02:28 cloud-party nextcloud.apache[606372]: AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
```
----
your error-log seems to be complaining about missing SSL-certification. maybe @kyrofa can shed some light?

```
### Error log

[Sun Feb 12 00:00:11.438192 2023] [ssl:warn] [pid 445625:tid 139784389608640] AH01873: Init: Session Cache is not configured [hint: SSLSessionCache]
[Sun Feb 12 00:00:11.438276 2023] [lbmethod_heartbeat:notice] [pid 445625:tid 139784389608640] AH02282: No slotmem from mod_heartmonitor
[Sun Feb 12 00:00:11.438399 2023] [mpm_event:notice] [pid 445625:tid 139784389608640] AH00489: Apache/2.4.55 (Unix) OpenSSL/1.1.1 configured -- resuming normal operations
[Sun Feb 12 00:00:11.438406 2023] [core:notice] [pid 445625:tid 139784389608640] AH00094: Command line: 'httpd -d /snap/nextcloud/33587 -D EnableCompression -D FOREGROUND'
[Sun Feb 12 00:00:12.440452 2023] [unixd:alert] [pid 702897:tid 139784389608640] AH02155: getpwuid: couldn't determine user name from uid 4294967295, you probably need to modify the User directive
[Sun Feb 12 00:00:12.440452 2023] [unixd:alert] [pid 702896:tid 139784389608640] AH02155: getpwuid: couldn't determine user name from uid 4294967295, you probably need to modify the User directive
[Sun Feb 12 00:00:12.440482 2023] [unixd:alert] [pid 702898:tid 139784389608640] AH02155: getpwuid: couldn't determine user name from uid 4294967295, you probably need to modify the User directive
[Sun Feb 12 00:00:13.425347 2023] [mpm_event:notice] [pid 445625:tid 139784389608640] AH00493: SIGUSR1 received.  Doing graceful restart
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Sun Feb 12 00:00:13.426770 2023] [ssl:warn] [pid 445625:tid 139784389608640] AH01873: Init: Session Cache is not configured [hint: SSLSessionCache]
[Sun Feb 12 00:00:13.426836 2023] [lbmethod_heartbeat:notice] [pid 445625:tid 139784389608640] AH02282: No slotmem from mod_heartmonitor
[Sun Feb 12 00:00:13.426965 2023] [mpm_event:notice] [pid 445625:tid 139784389608640] AH00489: Apache/2.4.55 (Unix) OpenSSL/1.1.1 configured -- resuming normal operations
[Sun Feb 12 00:00:13.426972 2023] [core:notice] [pid 445625:tid 139784389608640] AH00094: Command line: 'httpd -d /snap/nextcloud/33587 -D EnableCompression -D FOREGROUND'
[Sun Feb 12 00:00:14.428540 2023] [unixd:alert] [pid 703107:tid 139784389608640] AH02155: getpwuid: couldn't determine user name from uid 4294967295, you probably need to modify the User directive
[Sun Feb 12 00:00:14.428539 2023] [unixd:alert] [pid 703108:tid 139784389608640] AH02155: getpwuid: couldn't determine user name from uid 4294967295, you probably need to modify the User directive
[Sun Feb 12 00:00:14.428548 2023] [unixd:alert] [pid 703109:tid 139784389608640] AH02155: getpwuid: couldn't determine user name from uid 4294967295, you probably need to modify the User directive
[Sun Feb 12 00:00:20.433559 2023] [unixd:alert] [pid 703361:tid 139784389608640] AH02155: getpwuid: couldn't determine user name from uid 4294967295, you probably need to modify the User directive
[Tue Feb 14 00:02:25.455379 2023] [core:error] [pid 703108:tid 139782713759488] [client 185.225.74.55:33242] AH10244: invalid URI path (/cgi-bin/.%%%%32%%65/.%%%%32%%65/.%%%%32%%65/.%%%%32%%65/.%%%%32%%65/bin/sh)
[Tue Feb 14 14:49:53.069789 2023] [proxy_fcgi:error] [pid 703107:tid 139783913326336] [client 5.188.210.227:47600] AH01071: Got error 'Primary script unknown', referer: https://www.google.com/
[Tue Feb 14 15:55:36.425074 2023] [mpm_event:notice] [pid 445625:tid 139784389608640] AH00491: caught SIGTERM, shutting down
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Tue Feb 14 15:57:31.753560 2023] [ssl:warn] [pid 4859:tid 140104732632256] AH01873: Init: Session Cache is not configured [hint: SSLSessionCache]
[Tue Feb 14 15:57:31.753945 2023] [lbmethod_heartbeat:notice] [pid 4859:tid 140104732632256] AH02282: No slotmem from mod_heartmonitor
[Tue Feb 14 15:57:31.754516 2023] [mpm_event:notice] [pid 4859:tid 140104732632256] AH00489: Apache/2.4.55 (Unix) OpenSSL/1.1.1 configured -- resuming normal operations
[Tue Feb 14 15:57:31.754529 2023] [core:notice] [pid 4859:tid 140104732632256] AH00094: Command line: 'httpd -d /snap/nextcloud/33587 -D EnableCompression -D FOREGROUND'
[Tue Feb 14 15:57:31.817682 2023] [unixd:alert] [pid 4863:tid 140104732632256] AH02155: getpwuid: couldn't determine user name from uid 4294967295, you probably need to modify the User directive
[Tue Feb 14 15:57:31.817689 2023] [unixd:alert] [pid 4864:tid 140104732632256] AH02155: getpwuid: couldn't determine user name from uid 4294967295, you probably need to modify the User directive
[Tue Feb 14 15:57:31.817697 2023] [unixd:alert] [pid 4862:tid 140104732632256] AH02155: getpwuid: couldn't determine user name from uid 4294967295, you probably need to modify the User directive
[Tue Feb 14 15:57:59.779899 2023] [unixd:alert] [pid 6641:tid 140104732632256] AH02155: getpwuid: couldn't determine user name from uid 4294967295, you probably need to modify the User directive
[Wed Feb 15 04:52:45.136620 2023] [proxy_fcgi:error] [pid 6641:tid 140104098109184] [client 139.59.241.204:52325] AH01071: Got error 'Primary script unknown'
[Wed Feb 15 10:16:42.232526 2023] [core:error] [pid 6641:tid 140104089716480] [client 152.89.196.211:37558] AH10244: invalid URI path (/cgi-bin/.%2e/.%2e/.%2e/.%2e/bin/sh)
[Wed Feb 15 12:21:56.098489 2023] [proxy_fcgi:error] [pid 6641:tid 140103343126272] (70008)Partial results are valid but processing is incomplete: [client 192.168.1.20:61057] AH01075: Error dispatching request to : (reading input brigade)
[Wed Feb 15 13:11:28.544608 2023] [proxy_fcgi:error] [pid 6641:tid 140104567871232] (70008)Partial results are valid but processing is incomplete: [client 192.168.1.53:64664] AH01075: Error dispatching request to : (reading input brigade)
[Wed Feb 15 13:11:28.544748 2023] [proxy_fcgi:error] [pid 4863:tid 140104551085824] (70008)Partial results are valid but processing is incomplete: [client 192.168.1.53:64674] AH01075: Error dispatching request to : (reading input brigade)
[Wed Feb 15 13:30:09.312101 2023] [proxy_fcgi:error] [pid 4864:tid 140104467158784] [client 147.78.103.174:64814] AH01071: Got error 'Primary script unknown'
[Wed Feb 15 14:13:17.045748 2023] [proxy_fcgi:error] [pid 6641:tid 140104576263936] [client 44.192.247.64:33340] AH01071: Got error 'Primary script unknown'
[Thu Feb 16 23:30:32.350391 2023] [proxy_fcgi:error] [pid 6641:tid 140104106501888] [client 139.59.61.30:53804] AH01071: Got error 'Primary script unknown'
[Fri Feb 17 12:43:56.329181 2023] [core:error] [pid 4864:tid 140104576263936] [client 185.225.74.55:56764] AH10244: invalid URI path (/cgi-bin/.%%%%32%%65/.%%%%32%%65/.%%%%32%%65/.%%%%32%%65/.%%%%32%%65/bin/sh)
```

**Comment by smokingwheels** [comment]
I added the FDQN to /etc/hosts file and was checking out various snap commands and I found a error because a Domain was blocked with my Pihole. I whitelisted the domain and bash snap commands had no errors anymore.
There is less 

<html>
<body>

forum-snapcraft-io.s3.amazonaws.com
--

</body>
</html>

[https://forum.snapcraft.io/t/has-anyone-restored-a-snapshot-to-another-machine-even-different-hardware/33953](https://forum.snapcraft.io/t/has-anyone-restored-a-snapshot-to-another-machine-even-different-hardware/33953)


 

I was saving snapshot with snap had an error because the apache log changed.
I had stopped the server. ` snap stop nextcloud` and forgot to start in.
 
Hit reconnect, connected ok, then logoff after leaving it open in a tab for 5 hours and starting and stopping my QB64 web server a few times with a hyperlink in it pointing to the server.

`This page isn’t working192.168.1.53 is currently unable to handle this request.
HTTP ERROR 500`

Rebooted server to try to test again.
My debug  [log](http://gts.undo.it/index.php/s/CdJ7DSgqA29jnA8)
I have noticed that the CPU time taken is less in the log now.\
I did a 8 GB SSH file upload to the mirror HDD in the nextcloud server, the speed was 80-90 mb/s, I think this is also faster was around 50 before.

**Comment by smokingwheels** [comment]
I have come across the. [https://noc.wikimedia.org/conf/highlight.php?file=CommonSettings.php](https://noc.wikimedia.org/conf/highlight.php?file=CommonSettings.php)

Text from my yacy search engine.
Not sure if this helps..2.1 gb of second pass is 'spiky'. no compression enabled  
`compression of second pass is 'spiky', alternating between. // single-threaded and multithreaded portions, so you can somewhat. // overcommit process threads per CPU thread. $wgFFmpegThreads. =. 8. ;. // HD transcodes of full`

I have to learn how to fix these errors.

`Feb 23 03:31:04 Nextcloud-ASUS nextcloud.apache[1203673]: No certificates are active: using HTTP only
Feb 23 03:31:04 Nextcloud-ASUS nextcloud.apache[1203673]: HTTP compression is disabled
Feb 23 03:31:05 Nextcloud-ASUS nextcloud.apache[1203726]: AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
Feb 23 11:39:02 Nextcloud-ASUS systemd[1]: Stopping Service for snap application nextcloud.apache...
Feb 23 11:39:05 Nextcloud-ASUS nextcloud.apache[1267369]: No certificates are active: using HTTP only
Feb 23 11:39:06 Nextcloud-ASUS nextcloud.apache[1267498]: error: cannot communicate with server: Post http://localhost/v2/snapctl: EOF
Feb 23 11:39:06 Nextcloud-ASUS nextcloud.apache[1267503]: error: cannot communicate with server: Post http://localhost/v2/snapctl: EOF
Feb 23 11:39:06 Nextcloud-ASUS nextcloud.apache[1267509]: error: cannot communicate with server: Post http://localhost/v2/snapctl: EOF
Feb 23 11:39:06 Nextcloud-ASUS nextcloud.apache[1267369]: HTTP compression is disabled`

Had connection inactive for over 6 hours and error did no happen.
