### ISSUE TITLE
Unresponsive,  log shows guzzlehttp error

### ISSUE THREAD

**Issue by damopinn** [nextcloud-snap/nextcloud-snap#2309]
I freshly installed ubuntu 22.04 and installed nextcloud snap, I enabled https I have duckdns and everything is working as expected. I now see the 'access through untrusted domain' page. I add my duckdns domain to the config.php. Everything runs slowly and the error log shows guzzle http errors. I remove my duckdns domain from config.php and everything goes back to normal. I can use nextcloud locally again. I don't have a clue what could be causing this behavior. Any help would be very appreciated.
[nextcloud.log](https://github.com/nextcloud-snap/nextcloud-snap/files/10685787/nextcloud.log)

**Comment by scubamuc** [comment]
> Everything runs slowly and the error log shows guzzle http errors. 

- if installed on VM or LXC set [FQDN](https://github.com/scubamuc/scubamuc.github.io/blob/scubamuc/wiki-md/NEXTCLOUD.snap--set_FQDN.md)
- disable CODE (_some reports show `guzzlhttp` error when (CODE) RichTextDocumentServer is enabled_)

**Comment by damopinn** [comment]
Thanks that fixed it. It seems a little strange that it would behave this way after adding my duckdns domian to the trusted domains, I did a fresh install on a physical system and installed the hub bundle. seemed like it would be a normal thing to do but that's what caused my problems. from now on I will only install stuff I actually need. Thanks for the help.

**Comment by scubamuc** [comment]
@damopinn, see [CODE & Nextcloud Office configuration](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-CODE-and-Nextcloud-office-for-Nextcloud-snap)
