### ISSUE TITLE
Documentation on running behind nginx frontend proxy is broken

### ISSUE THREAD

**Issue by y0va** [nextcloud-snap/nextcloud-snap#2320]
The path documented in the [wiki to run behind nginx](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Putting-the-snap-behind-a-reverse-proxy#nginx) is only partly usable.  [In the issues it is recommended](https://github.com/nextcloud-snap/nextcloud-snap/issues/1411) to just terminate ssl at the frontend proxy, but there are cases where it makes sense to let it do the snap. 

There is already some functionality in this direction, but it is incomplete.

Missing is functionality is setting the snaps listening address, to avoid world accessible ports: 
- https://github.com/nextcloud-snap/nextcloud-snap/issues/1934#issue-1052734285
- https://github.com/nextcloud-snap/nextcloud-snap/issues/331

And to correctly use the host + port from nextclouds overwritehost setting for apache overwrite rules, ie for the dav well-known urls.
- https://github.com/nextcloud-snap/nextcloud-snap/issues/1411
- https://github.com/nextcloud-snap/nextcloud-snap/issues/111
- https://github.com/nextcloud-snap/nextcloud-snap/issues/1042 

For the latter an adaption of [this](https://github.com/nextcloud-snap/nextcloud-snap/pull/183/commits/6fe9ac21469314730341ab1865a4fc9d810b30d2) might solve the issue. Alas I don't have the resources to set up a snap build env nor do i know apache very well.

**Comment by kyrofa** [comment]
> Missing is functionality is setting the snaps listening address, to avoid world accessible ports:

While I understand this being desired, this is unrelated, and certainly not required. All ports should be firewalled except the ones you want available.

**Comment by y0va** [comment]
I'm used to clean network setups that not necessarily need to be firewalled. Firewalls, as like containers are for additional security not for hiding sloppy coding. Also I like documented functionality to work.
