### ISSUE TITLE
Documentation on using zfs is incomplete, needs transfer to wiki

### ISSUE THREAD

**Issue by y0va** [nextcloud-snap/nextcloud-snap#2322]
In the [very hidden doumentation](https://github.com/nextcloud-snap/nextcloud-snap/pull/2204) on how to use zfs it is said to be possible to bind mount the dataset to a arbitrary folder under /mnt. While this is possible under ubuntu 20.04.5, the apparmor of ubuntu 22.04.1 does not allow that.  

So a better working mount command would be:

`mount -o bind   /pool/tank0 /var/snap/nextcloud/common/nextcloud/data`

The mentioned doc could be a bit more present.

**Comment by kyrofa** [comment]
Not intentionally hidden, just not something we wanted to put into the README. We need a wiki page for it.
