### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Draqun** [nextcloud-snap/nextcloud-snap#2323]
Hi.
Today I discovered there is service to renew nextcloud certs from Let's Encrypt (I did it always manually). In the status I see the following logs. Can you tell me how A/AAAA entries should looks to make it working?

Best regards.

```bash
● snap.nextcloud.renew-certs.service - Service for snap application nextcloud.renew-certs
   Loaded: loaded (/etc/systemd/system/snap.nextcloud.renew-certs.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2023-02-21 17:46:31 CET; 1h 44min ago
 Main PID: 1197 (renew-certs)
    Tasks: 2 (limit: 4463)
   CGroup: /system.slice/snap.nextcloud.renew-certs.service
           ├─1197 /bin/sh /snap/nextcloud/33587/bin/renew-certs
           └─4603 sleep 1d

Feb 21 17:49:08 smurfs_village nextcloud.renew-certs[1197]:    Detail: 83.145.177.199: Fetching
Feb 21 17:49:08 smurfs_village nextcloud.renew-certs[1197]:    http://www.smurfshome.pl/.well-known/acme-challenge/Zodh8T9oc2cdHWYfl8_ZIbJrLLAJCNF25OQh5TIu9TY:
Feb 21 17:49:08 smurfs_village nextcloud.renew-certs[1197]:    Timeout during connect (likely firewall problem)
Feb 21 17:49:08 smurfs_village nextcloud.renew-certs[1197]:    To fix these errors, please make sure that your domain name was
Feb 21 17:49:08 smurfs_village nextcloud.renew-certs[1197]:    entered correctly and the DNS A/AAAA record(s) for that domain
Feb 21 17:49:08 smurfs_village nextcloud.renew-certs[1197]:    contain(s) the right IP address. Additionally, please check that
Feb 21 17:49:08 smurfs_village nextcloud.renew-certs[1197]:    your computer has a publicly routable IP address and that no
Feb 21 17:49:08 smurfs_village nextcloud.renew-certs[1197]:    firewalls are preventing the server from communicating with the
Feb 21 17:49:08 smurfs_village nextcloud.renew-certs[1197]:    client. If you're using the webroot plugin, you should also verify
Feb 21 17:49:08 smurfs_village nextcloud.renew-certs[1197]:    that you are serving files from the webroot path you provided.
```

**Comment by kyrofa** [comment]
> Today I discovered there is service to renew nextcloud certs from Let's Encrypt (I did it always manually)

You poor soul, what a pain! Yeah, let the snap take care of that for you.

Can you explain how exactly you've been doing this manually? Once I get a clear picture I can hopefully make some recommendations.

**Comment by Draqun** [comment]
I have a data file prepared and have always passed the contents of the file to the command.

```bash
 sudo /snap/bin/nextcloud.enable-https lets-encrypt < /etc/cert.data
```

From the logs I discovered there is a rpbolem with configuration file in /var/snap/nextcloud/current/certs/certbot/config/renewal

I could not find a template file to compare with the following config. There were also a few other files, but I removed them because their contents contain old, incorrect entries.

```
# renew_before_expiry = 30 days
version = 0.33.1
archive_dir = /var/snap/nextcloud/current/certs/certbot/config/archive/www.smurfshome.pl
cert = /var/snap/nextcloud/current/certs/certbot/config/live/www.smurfshome.pl/cert.pem
privkey = /var/snap/nextcloud/current/certs/certbot/config/live/www.smurfshome.pl/privkey.pem
chain = /var/snap/nextcloud/current/certs/certbot/config/live/www.smurfshome.pl/chain.pem
fullchain = /var/snap/nextcloud/current/certs/certbot/config/live/www.smurfshome.pl/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = <SOME UUID>
work_dir = /var/snap/nextcloud/current/certs/certbot/work
config_dir = /var/snap/nextcloud/current/certs/certbot/config
server = https://acme-v02.api.letsencrypt.org/directory
authenticator = webroot
logs_dir = /var/snap/nextcloud/current/certs/certbot/logs
rsa_key_size = 4096
webroot_path = /var/snap/nextcloud/current/certs/certbot,
[[webroot_map]]
www.smurfshome.pl = /var/snap/nextcloud/current/certs/certbot
smurfshome.pl = /var/snap/nextcloud/current/certs/certbot
```

Anyway it probably does not resolve all problems since certbot has a problem with fetching http://www.smurfshome.pl/.well-known/acme-challenge/Zodh8T9oc2cdHWYfl8_ZIbJrLLAJCNF25OQh5TIu9TY

**Comment by scubamuc** [comment]
you could try [resetting lets-encrypt](https://github.com/scubamuc/scubamuc.github.io/blob/scubamuc/wiki-md/NEXTCLOUD.snap--change_LetsEncrypt_domain.md).

check what is being blocked by your firewall?
your logs:
`Feb 21 17:49:08 smurfs_village nextcloud.renew-certs[1197]:    Timeout during connect (likely firewall problem)`

post your [logs ](https://github.com/scubamuc/scubamuc.github.io/blob/scubamuc/wiki-md/NEXTCLOUD.snap_logs.md) **after** trying to renew with Nextcloud-snap renewal service:

`$ sudo journalctl -u snap.nextcloud.renew-certs`

also logs for Certbot:  

 `$ sudo cat /var/snap/nextcloud/current/certs/certbot/logs/letsencrypt.log`

View logs: `less` is `more`, `head` or `tail` or `cat` or `bat`, `lnav` is the way to go!

**Comment by scubamuc** [comment]
it seems as though you have your certificate now:
![grafik](https://user-images.githubusercontent.com/54933878/220618162-2ec55857-076f-40ed-95f2-cc22eda69a9d.png)

is this still an issue or is it solved?

**Comment by Draqun** [comment]
It looks like all works fine. Thank you a lot!

Draqun
