### ISSUE TITLE
Allow rate-limiting of downloads/uploads

### ISSUE THREAD

**Issue by thomascobb** [nextcloud-snap/nextcloud-snap#233]
I would like to be able to customise the apache config by adding a rate limit as shown here:

https://httpd.apache.org/docs/trunk/mod/mod_ratelimit.html

If I understand correctly, if the main apache httpd.conf included ${SNAP_DATA}/some_user_file.conf then I could place such statements in /var/snap/common/some_user_file.conf.

Would this work? Would there be any security considerations?

I'm happy to have a go at this and make a pull request if this is a valid approach.

**Comment by kyrofa** [comment]
There are two issues here:

1. I assume this requires mod_ratelimit, which I don't believe is shipped in the snap.
2. I'd like to reserve the right to switch to using, say, nginx without the user caring. As soon as we support this, we can't go back. We'll need to stick with Apache forever.

**Comment by kyrofa** [comment]
Note that this doesn't mean the snap should never support rate limiting. Maybe that makes sense. But it should be done at a more technology-agnostic level, once the snap implements configuration.

**Comment by thomascobb** [comment]
> it should be done at a more technology-agnostic level, once the snap implements configuration.

That sounds like a good idea. Let me know if there is anything I can do to help.

**Comment by kyrofa** [comment]
Thanks for renaming the issue. This is blocked behind the same issues as #134 for now.

**Comment by Guard13007** [comment]
No longer blocked, any idea on when/if/how this can be done?
