### ISSUE TITLE
Upgrade PHP to PHP 8.1

### ISSUE THREAD

**Issue by neonota** [nextcloud-snap/nextcloud-snap#2333]
Hi,

Nextcloud Snap is currently using php8.0. Although php8.1 is recommended by Nextcloud docs.

Kindly upgrade php.

Thanks to the awesome people who made Nextcloud installation easy-peasy.

**Comment by kyrofa** [comment]
You need version 25.0.3snap3, try running `sudo snap refresh nextcloud`. Then you can confirm you have 8.1 like so:

```
$ snap run --shell nextcloud.occ -c '$SNAP/bin/php --version'
PHP 8.1.16 (cli) (built: Feb 21 2023 14:20:15) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.16, Copyright (c) Zend Technologies
```
