### ISSUE TITLE
Unable to restore data with User migration application

### ISSUE THREAD

**Issue by rezib** [nextcloud-snap/nextcloud-snap#2335]
#### Describe the bug
The [_User migration_](https://apps.nextcloud.com/apps/user_migration) application fails at restoring user's data.

#### To Reproduce
1. Install _User migration_ application
2. Export one user's data
3. Import user's data (CAUTION: this is a destructive operation)
4. Observe the user's data have not been restored

#### Expected behavior
The restoration of user's data should succeeds.

#### Screenshots
N/A

#### OS/snapd/snap version
```
root@hub:~ # snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  25.0.3snap3  33730  latest/stable  nextcloud✓  devmode
```

```
root@hub:~ # snap version
snap    2.58.2
snapd   2.58.2
series  16
debian  11
kernel  5.10.0-21-amd64
```
#### Logs
See [debug-script-output.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/10849125/debug-script-output.txt) attached file.

Here is the relevant log entry from `/var/snap/nextcloud/current/logs/nextcloud.log`:

```json
{
  "reqId": "ozfdzAmxk5x60Dpk7vYK",
  "level": 3,
  "time": "2023-02-28T10:13:57+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "user_migration",
  "method": "",
  "url": "--",
  "message": "Invalid or uninitialized Zip object",
  "userAgent": "--",
  "version": "25.0.3.2",
  "exception": {
    "Exception": "ValueError",
    "Message": "Invalid or uninitialized Zip object",
    "Code": 0,
    "Trace": [
      {
        "file": "/snap/nextcloud/33730/htdocs/lib/private/Archive/ZIP.php",
        "line": 172,
        "function": "getFromName",
        "class": "ZipArchive",
        "type": "->"
      },
      {
        "file": "/var/snap/nextcloud/33730/nextcloud/extra-apps/user_migration/lib/ImportSource.php",
        "line": 56,
        "function": "getFile",
        "class": "OC\\Archive\\ZIP",
        "type": "->"
      },
      {
        "file": "/var/snap/nextcloud/33730/nextcloud/extra-apps/user_migration/lib/ImportSource.php",
        "line": 147,
        "function": "getFileContents",
        "class": "OCA\\UserMigration\\ImportSource",
        "type": "->"
      },
      {
        "file": "/var/snap/nextcloud/33730/nextcloud/extra-apps/user_migration/lib/Service/UserMigrationService.php",
        "line": 232,
        "function": "getMigratorVersions",
        "class": "OCA\\UserMigration\\ImportSource",
        "type": "->"
      },
      {
        "file": "/var/snap/nextcloud/33730/nextcloud/extra-apps/user_migration/lib/BackgroundJob/UserImportJob.php",
        "line": 100,
        "function": "import",
        "class": "OCA\\UserMigration\\Service\\UserMigrationService",
        "type": "->"
      },
      {
        "file": "/snap/nextcloud/33730/htdocs/lib/public/BackgroundJob/Job.php",
        "line": 78,
        "function": "run",
        "class": "OCA\\UserMigration\\BackgroundJob\\UserImportJob",
        "type": "->"
      },
      {
        "file": "/snap/nextcloud/33730/htdocs/lib/public/BackgroundJob/QueuedJob.php",
        "line": 58,
        "function": "start",
        "class": "OCP\\BackgroundJob\\Job",
        "type": "->"
      },
      {
        "file": "/snap/nextcloud/33730/htdocs/lib/public/BackgroundJob/QueuedJob.php",
        "line": 48,
        "function": "start",
        "class": "OCP\\BackgroundJob\\QueuedJob",
        "type": "->"
      },
      {
        "file": "/snap/nextcloud/33730/htdocs/cron.php",
        "line": 152,
        "function": "execute",
        "class": "OCP\\BackgroundJob\\QueuedJob",
        "type": "->"
      }
    ],
    "File": "/snap/nextcloud/33730/htdocs/lib/private/Archive/ZIP.php",
    "Line": 172,
    "message": "Invalid or uninitialized Zip object",
    "exception": {},
    "CustomMessage": "Invalid or uninitialized Zip object"
  }
}
```

**Comment by rezib** [comment]
As far as I have tested, it looks like it is related to PHP unable to handle the zip file. I have reproduced the error with this tiny script:

```
root@host:~ # snap run --shell nextcloud.occ
root@host:/root# cat /tmp/test.php
<?php
$source = "/mnt/data/nextcloud/user/files/user.nextcloud_export";
$zip = new \ZipArchive();
if ($zip->open($source, \ZipArchive::CREATE)) {
    echo "ok";
} else {
    echo "failed";
}

$path = "migrator_versions.json";
$content = $zip->getFromName($path);
echo $content;
?>
root@host:/root# php /tmp/test.php 
ok
Fatal error: Uncaught ValueError: Invalid or uninitialized Zip object in /tmp/test.php:12
Stack trace:
#0 /tmp/test.php(11): ZipArchive->getFromName('migrator_versio...')
#1 {main}
  thrown in /tmp/test.php on line 12
```

FWIW, the same script works properly on the same host, outside the snap environment, with system PHP and the exact same file:

```
root@host:~ # php test.php 
ok{"usermigrationservice":1,"calendar":1,"contacts":1,"trashbin":1,"account":1,"files":1}

root@host:~ 1 # dpkg -l | grep php
ii  php-cli                        2:7.4+76                       all          command-line interpreter for the PHP scripting language (default)
ii  php-common                     2:76                           all          Common files for PHP packages
ii  php-zip                        2:7.4+76                       all          Zip module for PHP [default]
ii  php7.4-cli                     7.4.33-1+deb11u3               amd64        command-line interpreter for the PHP scripting language
ii  php7.4-common                  7.4.33-1+deb11u3               amd64        documentation, examples and common module for PHP
ii  php7.4-json                    7.4.33-1+deb11u3               amd64        JSON module for PHP
ii  php7.4-opcache                 7.4.33-1+deb11u3               amd64        Zend OpCache module for PHP
ii  php7.4-readline                7.4.33-1+deb11u3               amd64        readline module for PHP
ii  php7.4-zip                     7.4.33-1+deb11u3               amd64        Zip module for PHP
```

I have also tested to set `php.memory-limit=-1` but it does not change anything.

**Comment by scubamuc** [comment]
looks like this issue is being handled upstream?
https://github.com/nextcloud/user_migration/issues/344
please see if you could add your input

**Comment by rezib** [comment]
> looks like this issue is being handled upstream? [nextcloud/user_migration#344](https://github.com/nextcloud/user_migration/issues/344) please see if you could add your input

Well, I don't see how it could be related as the issue there occurs on user migration _export_ (here it is all about _import_) and the bug is 32bits architecture specific, I'm running x86_64.

**Comment by rezib** [comment]
I have dug into this deeper and managed to find a workaround eventually. Actually, I found out that the failing zip file generated by the _User migration_ app has a zip v4.5 format (don't ask me what it is), as per `file` command:

```
root@host:~ # nextcloud.occ user:import /mnt/data/nextcloud/user.nextcloud_export
Importing from /mnt/data/nextcloud/user.nextcloud_export…
An unhandled exception has been thrown:
ValueError: Invalid or uninitialized Zip object in /snap/nextcloud/33730/htdocs/lib/private/Archive/ZIP.php:172
Stack trace:
#0 /snap/nextcloud/33730/htdocs/lib/private/Archive/ZIP.php(172): ZipArchive->getFromName()
#1 /var/snap/nextcloud/33730/nextcloud/extra-apps/user_migration/lib/ImportSource.php(56): OC\Archive\ZIP->getFile()
#2 /var/snap/nextcloud/33730/nextcloud/extra-apps/user_migration/lib/ImportSource.php(147): OCA\UserMigration\ImportSource->getFileContents()
#3 /var/snap/nextcloud/33730/nextcloud/extra-apps/user_migration/lib/Service/UserMigrationService.php(232): OCA\UserMigration\ImportSource->getMigratorVersions()
#4 /var/snap/nextcloud/33730/nextcloud/extra-apps/user_migration/lib/Command/Import.php(93): OCA\UserMigration\Service\UserMigrationService->import()
#5 /snap/nextcloud/33730/htdocs/3rdparty/symfony/console/Command/Command.php(255): OCA\UserMigration\Command\Import->execute()
#6 /snap/nextcloud/33730/htdocs/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#7 /snap/nextcloud/33730/htdocs/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#8 /snap/nextcloud/33730/htdocs/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#9 /snap/nextcloud/33730/htdocs/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run()
#10 /snap/nextcloud/33730/htdocs/console.php(100): OC\Console\Application->run()
#11 /snap/nextcloud/33730/htdocs/occ(11): require_once('...')
#12 {main}
root@host:~ # file /mnt/data/nextcloud/user.nextcloud_export
/tmp/user.nextcloud_export: Zip archive data, at least v4.5 to extract
```

By regenerating the file with the `zip` command, I get a zip file with v1.0 format:

```
root@host:~ # mkdir extract && cd extract/
root@host:~ # unzip /mnt/data/nextcloud/user.nextcloud_export
root@host:~ # rm /mnt/data/nextcloud/user.nextcloud_export
root@host:~ # zip /mnt/data/nextcloud/user.nextcloud_export -r *
root@host:~ # file /mnt/data/nextcloud/user.nextcloud_export 
/mnt/data/nextcloud/user.nextcloud_export: Zip archive data, at least v1.0 to extract
```

This zip v1.0 formatted file can be successfully imported in the snap!

```
root@host:~ # nextcloud.occ user:import /mnt/data/nextcloud/user.nextcloud_export 
Importing from /mnt/data/nextcloud/user.nextcloud_export…
Importing user information from user.json…
Importing settings from settings.json…
Importing calendars from dav/calendars/…
Importing contacts from dav/address_books/…
Importing trashbin from files_trashbin…
Importing trashbin files…
Importing account information from settings/account.json…
Importing avatar from settings/avatar.jpg…
Importing profile config from settings/config.json…
Importing files…
Importing file versions…
Importing file tags…
Importing file systemtags…
Importing file comments…
Successfully imported foo
Successfully imported from /mnt/data/nextcloud/user.nextcloud_export
```

Then the bug is due to PHP in the snap not supporting zip v4.5 files. The bug can be easily reproduced with this script:

```
root@host:~ # cat /tmp/test.php
<?php
$source = "/mnt/data/nextcloud/user.nextcloud_export";
$zip = new \ZipArchive();
if ($zip->open($source, \ZipArchive::CREATE)) {
    echo "ok\n";
} else {
    echo "failed\n";
}

$path = "migrator_versions.json";
$content = $zip->getFromName($path);
echo "$content\n";
?>
```

It works fine with system PHP:

```
root@host:~ # php /tmp/test.php 
ok
{"usermigrationservice":1,"calendar":1,"contacts":1,"trashbin":1,"account":1,"files":1}
```

But fails with snap PHP:

```
root@host:~ s # export LD_LIBRARY_PATH=/snap/nextcloud/33730/usr/lib/x86_64-linux-gnu
root@host:~ # /snap/nextcloud/33730/bin/php /tmp/test.php
ok

Fatal error: Uncaught ValueError: Invalid or uninitialized Zip object in /tmp/test.php:11
Stack trace:
#0 /tmp/test.php(11): ZipArchive->getFromName('migrator_versio...')
#1 {main}
  thrown in /tmp/test.php on line 11
```

The weird thing that makes this non-sense to me is that the original v4.5 zip file was generated on another Nextcloud instance installed with the exact same snap…

**Comment by scubamuc** [comment]
user migration app has received an update to 3.0 today

![grafik](https://user-images.githubusercontent.com/54933878/223371279-1ce2ba7d-b228-41ff-9612-ed2e0a7e0bab.png)

**Comment by Jayvratsinh** [comment]
> user migration app has received an update to 3.0 today
> 
> ![grafik](https://user-images.githubusercontent.com/54933878/223371279-1ce2ba7d-b228-41ff-9612-ed2e0a7e0bab.png)

This issue is still there in the NC 27 and it has made the user mgration feature totally useless. I tried @rezib methods and it worked for once and now no matter what I try I keep getting "[ERROR] Failed to get migrators versions". This is only happing in the snap install. I tried to check the logs and journal entries but found nothing. 

My actual aim was to migrate to a snap install as it barely required to configure anything, as I only use Nextcloud as Google photos alternative but since last few months Nextcloud has kept getting bug in the name of update and I though, I would give a try to the snap install which @TheLinuxEXP on youtube mentions that it is fairly stable than the normal install. 

If someone can please help me migrate my data to the snap version, it would be great as I am fairly new to the world of self hosting and linux.

**Comment by scubamuc** [comment]
[User migrationm](https://apps.nextcloud.com/apps/user_migration) is a **third party app** which we do not maintain and cannot support. See [third party app incompatibility](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-nextcloud-snap-is-not-working-because-of-third-party-app-incompatibility-what-can-i-do). Please log an issue against the app itself.

**Comment by pachulo** [comment]
This might be due to the snap using an old version of libzip, [the one included with Ubuntu 18.04](https://launchpad.net/ubuntu/bionic/+package/libzip-dev). Another reason to solve https://github.com/nextcloud-snap/nextcloud-snap/issues/2011 I guess

**Comment by rezib** [comment]
> This might be due to the snap using an old version of libzip, [the one included with Ubuntu 18.04](https://launchpad.net/ubuntu/bionic/+package/libzip-dev). Another reason to solve #2011 I guess

Yeah :+1: It looks like a good lead! It would nicely explain the behavior I mentioned with PHP/zip inside and outside the snap.

**Comment by pachulo** [comment]
Hi! We are now testing [the upgrade to core20](https://github.com/nextcloud-snap/nextcloud-snap/issues/2011), which means that [libzip version 1.5.1 should be now available](https://launchpad.net/ubuntu/focal/+package/libzip-dev) inside the snap.

@rezib could you repeat your tests with the upgraded snap from `latest/beta`? You can refresh to it with:
```
sudo snap refresh --beta nextcloud
```

Thanks!

**Comment by rezib** [comment]
Thank you @pachulo for this longstanding issue tracking but I don't use the snap anymore, I won't be able to test by myself 😕

**Comment by pachulo** [comment]
OK, tried this again with the new core20-based snap and seems solved.
I've:
1. Created an `user.nextcloud_export` file using the [User migration](https://apps.nextcloud.com/apps/user_migration) App.
2. Created a `test.php` file with this content:
```
<?php
$source = "/home/ubuntu/snap/nextcloud/52976/user.nextcloud_export";
$zip = new \ZipArchive();
if ($zip->open($source, \ZipArchive::CREATE)) {
    echo "ok\n";
} else {
    echo "failed\n";
}

$path = "migrator_versions.json";
$content = $zip->getFromName($path);
echo "$content\n";
?>
```
3. Moved both files to a directory accesible by the snap:
```
mv test.php user.nextcloud_export /home/ubuntu/snap/nextcloud/52976/
```
4. Opened a shell inside the snap:
```
snap run --shell nextcloud.occ
```
5. Run the test script:
``` 
ubuntu@nextcloud-container:~$ php ./test.php
ok
{"usermigrationservice":1,"calendar":1}
```

Thanks for your investigation @rezib !
