### ISSUE TITLE
Nextcloud Office does not load documents

### ISSUE THREAD

**Issue by safranat** [nextcloud-snap/nextcloud-snap#2339]
#### Describe the bug
When installing the nextcloud snap on ubuntu server 22.04 it is possible to create new collabora documents from the existing templates but it will not open any new or existing documents.
When installing the same snap on ubuntu desktop 22.04 it works.

#### To Reproduce
1. Login to the nextcloud instance via browser from a different machine.
2. Go to the files section
3. Create a new office document or click on an existing one
4. See error: it will not open and there is only an cancel button.

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  25.0.3snap3  33730  latest/stable  nextcloud✓  -
r
and:

    $ snap version
snap    2.58.2
snapd   2.58.2
series  16
ubuntu  22.04
kernel  5.15.0-67-generic

#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).

**Comment by kyrofa** [comment]
I'm sorry, we can't support individual apps in this repo, you'll need to log an issue against the upstream app.

**Comment by kyrofa** [comment]
Please see #2288.

**Comment by scubamuc** [comment]
@safranat ,

see [CODE & Nextcloud Office configuration](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-CODE-and-Nextcloud-office-for-Nextcloud-snap)
