### ISSUE TITLE
Please upgrade the snap git clone link

### ISSUE THREAD

**Issue by szaimen** [nextcloud-snap/nextcloud-snap#2341]
Hi, it looks like the snap git clone link is outdated. Please update it. See https://github.com/nextcloud-snap/nextcloud-snap/wiki/Building-your-first-Nextcloud-snap#getting-a-working-version

**Comment by szaimen** [comment]
Looks like there is a redirect in place

**Comment by kyrofa** [comment]
Oof. So many of those pages aren't even valid anymore :see_no_evil: . Thanks for the heads up, I'll see if I can prune and update.
