### ISSUE TITLE
Enable dailies for Nextcloud to 26

### ISSUE THREAD

**Issue by Pilzinsel64** [nextcloud-snap/nextcloud-snap#2348]
Current Release is RC2. The point-zero release is planed for 21st March.

What's about starting beta-testing already now this time, instead after the first point release? We then have a lot time to test until first pint release.
I would open a PR, but not sure what needs to change for beta/daily builds.

The tarball ([the only need](https://github.com/nextcloud-snap/nextcloud-snap/pull/2222#issuecomment-1302274113) that @kyrofa mentoined) [is already available](https://cloud.nextcloud.com/call/xs25tz5y#message_1758673)! See here: https://download.nextcloud.com/server/daily/latest-stable26.tar.bz2

**Comment by kyrofa** [comment]
Well what do you know! Thanks for the heads up, I usually need to beg for those. I've enabled the dailies, but I'll [need Canonical to grant me the track before they'll be accessible](https://forum.snapcraft.io/t/nextcloud-track-26/34298?u=kyrofa).

**Comment by Pilzinsel64** [comment]
The track seems to be created.

**Comment by ZOKOB** [comment]
Good morning ,

I apologize in advance for my English,

I can't upgrade my nextcloud on snap to version 26.

Can you help me please ?

**Comment by Pilzinsel64** [comment]
@ZOKOB the snap hasn't been updated to v26 yet and will not before the first point release.

**Comment by ZOKOB** [comment]
Thank you for your reply
how soon do you think it will be up to date on snap?

**Comment by Pilzinsel64** [comment]
Probably in one or two months, but it depends when Nextcloud releases 26.0.1.

**Comment by Pilzinsel64** [comment]
Is there anything missing here kyrafo? I see https://github.com/nextcloud-snap/nextcloud-snap/commit/d1c6bfb293e822c294488a1db2a24d6dbe0ba6ed has been merged and the track granted but the dailies get not generated/uploaded to snapcraft.

**Comment by kyrofa** [comment]
Yeah, a merge to master. Github only supports running scheduled jobs on the default branch.

**Comment by kyrofa** [comment]
Keep an eye on #2360.

**Comment by Pilzinsel64** [comment]
Ah, true, just didn't see. :)

**Comment by kyrofa** [comment]
In case you missed it:

```
Track    Arch     Channel    Version        Revision    Progress
26       amd64    stable     -              -           -
                  candidate  -              -           -
                  beta       -              -           -
                  edge       26-2023-03-25  34115       -
         arm64    stable     -              -           -
                  candidate  -              -           -
                  beta       -              -           -
                  edge       26-2023-03-25  34126       -
         armhf    stable     -              -           -
                  candidate  -              -           -
                  beta       -              -           -
                  edge       26-2023-03-24  34110       -
         i386     stable     -              -           -
                  candidate  -              -           -
                  beta       -              -           -
                  edge       26-2023-03-25  34113       -
         ppc64el  stable     -              -           -
                  candidate  -              -           -
                  beta       -              -           -
                  edge       26-2023-03-25  34122       -
```
