### ISSUE TITLE
Nextcloud snap won't update, stuck on "Run pre-refresh hook of "nextcloud" snap if present (run hook "pre-refresh":" with Apache timeout

### ISSUE THREAD

**Issue by Pajkastare** [nextcloud-snap/nextcloud-snap#2349]
#### Describe the bug
Nextcloud snap won't update, stuck on "Run pre-refresh hook of "nextcloud" snap if present (run hook "pre-refresh":" with Apache timeout (after 10 minutes)
Also, my Nextcloud setup is apparently really old - I configured it a few years ago, mainly use it to backup photos from my mobile phone, but I haven't really touched the setup for a long while. 
The version that Nextcloud/snap attempts to install during an update is 33738, but the two version listed under /var/snap/nextcloud are 24943 and 25284. So this appears to be around version 18 or 19, according to "snap info nextcloud".

Yesterday, but not today, I also noticed a lot of apparmor denies when I tried to start nextcloud. No idea why I did not see those today.

#### To Reproduce
1. From Linux prompt: Type "sudo snap refresh nextcloud"
2. Wait 10 minutes
3. See this message, when the refresh aborts.

>  error: cannot perform the following tasks:
> - Run pre-refresh hook of "nextcloud" snap if present (run hook "pre-refresh":
> -----
> Waiting for Apache...
> 
> <exceeded maximum runtime of 10m0s>
> -----)

#### Expected behavior
Nextcloud snap should update to the latest version.

#### Screenshots
N/A

#### OS/snapd/snap version
Ubuntu 20.04.5 LTS on a Raspberry Pi 4B.

    $ snap list nextcloud

> Name       Version      Rev    Tracking       Publisher   Notes
> nextcloud  20.0.4snap1  25284  latest/stable  nextcloud✓  -

and:

    $ snap version

> snap    2.58.2
> snapd   2.58.2
> series  16
> ubuntu  20.04
> kernel  5.4.0-1081-raspi

#### Logs
I thought this was informative, related parts from the system log during the refresh (notably no log mention of retries during the 10-minute window until the timeout), since it apparently tries to update my ancient active Nextcloud setup:

journalctl -f | sed "s/$(hostname)/MYSYSTEM/g" | grep -i -e snap -e audit -e apparmor -e nextcloud

> mar 10 10:09:20 MYSYSTEM systemd[1]: Mounting Mount unit for nextcloud, revision 33738...
> mar 10 10:09:20 MYSYSTEM systemd[1]: Mounted Mount unit for nextcloud, revision 33738.
> mar 10 10:09:20 MYSYSTEM systemd[1]: Started snap.nextcloud.hook.pre-refresh.b756f175-ed0d-449f-8b9e-dbff7e1d629b.scope.
> mar 10 10:19:20 MYSYSTEM systemd[1]: snap.nextcloud.hook.pre-refresh.b756f175-ed0d-449f-8b9e-dbff7e1d629b.scope: Succeeded.
> mar 10 10:19:20 MYSYSTEM snapd[1492]: taskrunner.go:289: [change 9716 "Run pre-refresh hook of \"nextcloud\" snap if present" task] failed: run hook "pre-refresh":
> mar 10 10:19:20 MYSYSTEM snapd[1492]: -----
> mar 10 10:19:20 MYSYSTEM snapd[1492]: Waiting for Apache...
> mar 10 10:19:20 MYSYSTEM snapd[1492]: <exceeded maximum runtime of 10m0s>
> mar 10 10:19:20 MYSYSTEM snapd[1492]: -----
> mar 10 10:19:21 MYSYSTEM systemd[4002]: snap-nextcloud-33738.mount: Succeeded.
> mar 10 10:19:21 MYSYSTEM systemd[3096]: snap-nextcloud-33738.mount: Succeeded.
> mar 10 10:19:21 MYSYSTEM systemd[1]: snap-nextcloud-33738.mount: Succeeded.
> mar 10 10:19:23 MYSYSTEM snapd[1492]: handlers.go:669: Reported install problem for "nextcloud" as already-reported

**Comment by kyrofa** [comment]
Interesting. An automatic refresh won't actually succeed at this point because you'd be skipping several major versions of Nextcloud, which isn't a supported upgrade path. That's okay, we can deal with that by holding its hand a little, but let's look into this first: 

> mar 10 10:19:20 MYSYSTEM snapd[1492]: Waiting for Apache...
> mar 10 10:19:20 MYSYSTEM snapd[1492]: <exceeded maximum runtime of 10m0s>

Can you confirm that the snap _is_ actually working? You can visit it in the browser?

**Comment by kyrofa** [comment]
Assuming yes, please run these following commands. They could be the ones that are timing out, so they could potentially take a while:

> sudo nextcloud.occ -n app:update --all
> sudo nextcloud.occ -n upgrade

**Comment by Pajkastare** [comment]
Yes, Nextcloud works in the sense that my photos are backed up, and both the Android client and the web interface work as usual. (Except for the other day, where the system log showed apparmor denies, I think it was for the capability "dac_read_search", but I could not reproduce that today.) 

I tried the commands you posted with the Nextcloud snap stopped.
The first command: "sudo nextcloud.occ -n app:update --all" immediately displayed this, but nothing else for 60+ minutes.
> Waiting for PHP...

The following was shown by journalctl at the same time, but then nothing snap-related for at least an hour (no timeout during that time).
> systemd[1]: Started snap.nextcloud.occ.83727d2c-6085-49b9-a77a-2f35745bbc52.scope.

I aborted using Ctrl-C, and this appeared in the system log (but nothing in the console):
>  systemd[1]: snap.nextcloud.occ.83727d2c-6085-49b9-a77a-2f35745bbc52.scope: Succeeded.


The second command seemed to behave the same except the log entry was "systemd[1]: Started snap.nextcloud.occ.23123712-2bfb-4a11-b608-45eff387afcb.scope." (This time I did not wait a full hour.)


I then started the Nextcloud snap, and tried "time nextcloud.occ -n app:update --all". It failed after 1.15 seconds, with this console output: 

> An unhandled exception has been thrown:
> ArgumentCountError: Too few arguments to function OCA\PreviewGenerator\Command\Generate::__construct(), 0 passed in /snap/nextcloud/25284/htdocs/lib/private/Console/Application.php on line 224 and at least 5 expected in /var/snap/nextcloud/25284/nextcloud/extra-apps/previewgenerator/lib/Command/Generate.php:72
> Stack trace:
> #0 /snap/nextcloud/25284/htdocs/lib/private/Console/Application.php(224): OCA\PreviewGenerator\Command\Generate->__construct()
> #1 /snap/nextcloud/25284/htdocs/lib/private/Console/Application.php(136): OC\Console\Application->loadCommandsFromInfoXml(Array)
> #2 /snap/nextcloud/25284/htdocs/console.php(99): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #3 /snap/nextcloud/25284/htdocs/occ(11): require_once('/snap/nextcloud...')
> #4 {main}




If a complete reinstall turns out to be needed (in case the normal upgrade process won't work), after first backing up my configuration, I would like to transfer as much of the setup as possible (reindexing all files is no problem, but I'd like to avoid having to reconfigure all accounts and passwords), but the Nextcloud migration documentation is very clear that the same version of Nextcloud must be running on both the old and new systems. 

Any idea what to do next?

**Comment by kyrofa** [comment]
> I tried the commands you posted with the Nextcloud snap stopped.

Ah, don't do that-- get it up and running like normal, THEN run those commands.

**Comment by Pajkastare** [comment]
> > I tried the commands you posted with the Nextcloud snap stopped.
> 
> Ah, don't do that-- get it up and running like normal, THEN run those command

I did. :-) In my post above:

> I then started the Nextcloud snap, and tried "time nextcloud.occ -n app:update --all". It failed after 1.15 seconds, with this console output:
> 
>     An unhandled exception has been thrown:
>     ArgumentCountError: Too few arguments to function OCA\PreviewGenerator\Command\Generate::__construct(), 0 passed in /snap/nextcloud/25284/htdocs/lib/private/Console/Application.php on line 224 and at least 5 expected in /var/snap/nextcloud/25284/nextcloud/extra-apps/previewgenerator/lib/Command/Generate.php:72
>     Stack trace:
>     #0 /snap/nextcloud/25284/htdocs/lib/private/Console/Application.php(224): OCA\PreviewGenerator\Command\Generate->__construct()
>     https://github.com/nextcloud-snap/nextcloud-snap/issues/1 /snap/nextcloud/25284/htdocs/lib/private/Console/Application.php(136): OC\Console\Application->loadCommandsFromInfoXml(Array)
>     https://github.com/nextcloud-snap/nextcloud-snap/issues/2 /snap/nextcloud/25284/htdocs/console.php(99): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
>     https://github.com/nextcloud-snap/nextcloud-snap/issues/3 /snap/nextcloud/25284/htdocs/occ(11): require_once('/snap/nextcloud...')
>     https://github.com/nextcloud-snap/nextcloud-snap/pull/4 {main}
> 
>

**Comment by scubamuc** [comment]
your log:
> #0 /snap/nextcloud/25284/htdocs/lib/private/Console/Application.php(224): OCA\PreviewGenerator\Command\Generate->__construct()

is the Preview Generator app installed?
![grafik](https://user-images.githubusercontent.com/54933878/224511970-606f2af6-aaad-41d7-b611-5930e54eedbf.png)

try deactivating this before updating:
https://github.com/scubamuc/scubamuc.github.io/blob/scubamuc/wiki-md/NEXTCLOUD.snap--administration_wiki.md#enable--disable-apps

then refresh snap:
`sudo snap refresh nextcloud`

**Comment by Pajkastare** [comment]
Thanks, PreviewGenerator definitely had something to do with it. Actually, I could not even type "nextcloud.occ --help" without getting a PreviewGenerator-related exception, but I could (and did) disable it in the web interface.


"snap refresh nextcloud" went busy for a while, then stopped (aborted without upgrading) with this error message:

> 2023-03-11T22:45:10+01:00 INFO Waiting for "snap.nextcloud.mysql.service" to stop.
> error: cannot perform the following tasks:
> - Run post-refresh hook of "nextcloud" snap if present (run hook "post-refresh": Nextcloud doesn't support skipping major versions, you must upgrade to Nextcloud 21 first. Try 'sudo snap refresh nextcloud --channel=21')


I then tried "sudo nextcloud.occ -n app:update --all" (which actually did some behind-the-scene work according to journalctl, but nothing shown in the console) and "sudo nextcloud.occ -n upgrade" (which responded by printing "Nextcloud is already latest version" in the console, **which is definitely not true**).

Then I tried the " sudo snap refresh nextcloud --channel=21" message according to the error output from the refresh command above. It actually seemed to work, Nextcloud was updated to release number 29852 (from 25284 before).


I'll keep upgrading to 22, 23, 24, 25 and if all works, I'll re-enable the preview generator then. 

I guess the real test will be to see if Nextcloud still works after all these steps, and if my setup will auto-upgrade to release 26 when the time comes, but it is looking good so far.

**Comment by kyrofa** [comment]
> I'll keep upgrading to 22, 23, 24, 25 [...]

Excellent, yes you've hit on the right formula. Once you get to 25, you can do one final `sudo snap refresh nextcloud --stable` and you'll be fully up to date and continue updating once 26 comes out, and so on.

Nice catch @scubamuc. I'll go ahead and close this.

**Comment by scubamuc** [comment]
@Pajkastare 
> I'll re-enable the preview generator then.

don't do that, you'll run into update problems again. you could create an [issue](https://github.com/nextcloud/previewgenerator/issues)

it looks as though the app needs to be configured outside of [confinement](https://github.com/scubamuc/scubamuc.github.io/blob/scubamuc/wiki-md/NEXTCLOUD.snap--snap-confinement.md) which doesn't work. 
can you confirm the app was working at all?

@kyrofa do you see an issue here?

**Comment by Pajkastare** [comment]
The version-by-version upgrade method worked, thanks for the help.

I can't really say if the PreviewGenerator was working before or not, but I'm doing a complete generation of previews right now, will test it in the coming days.

Also, I know that I'm now on version 25.0.4snap1 (33915), so if upgrades fail again, I now where to start looking. But I'll keep PreviewGenerator until at least one more snap refresh.
