### ISSUE TITLE
Android app Nextcloud Talk cannot upload images - issue 

### ISSUE THREAD

**Issue by vawaver** [nextcloud-snap/nextcloud-snap#2351]
A few days ago I was uploading a larger file via Firefox to my Nextcloud server.
I interrupted this process while uploading the file. Something happened and suddenly I was unable to see the file and directory structure through Firefox on the Nextcloud server.
I cleared the browser cache and in addition, I ran the command on the server

`sudo nextcloud.occ maintenance:repair`

This helped me, the files and directories started showing up again.

However, I found out yesterday that it is not possible to upload an image larger than 1 MB to chats via the Nextcloud Talk Android application. In about 15 seconds, the recording ends with the message "Failure".

I tried it on my other Nextcloud server and it works fine there. This means that it is not a problem with the Nextcloud Talk Android application.

From this, I assume that something went wrong in the Nextcloud Talk settings on this Nextcloud server.
I want to ask how to solve it.

Is there a command that can check and possibly fix this? Any other ideas?

PS01: Uploading an image ( bigger than 1 MB) to the Nextcloud server via Firefox in chats in Nextcloud Talk works fine.
PS02: Automatic image backup via the primary Nextcloud Android app also works fine. 
 
**My server:**
Ubuntu server 20.04.5
Nextcloud 25.0.4 Snap 1

**Comment by scubamuc** [comment]
looks like this is an upstream problem... you're not alone
https://github.com/nextcloud/talk-android/issues/2587
please raise issue upstream
