### ISSUE TITLE
Change data directory (wiki) not working

### ISSUE THREAD

**Issue by baaahm** [nextcloud-snap/nextcloud-snap#2352]
Hi,
I followed the wiki article to change the data directory.

At step 2 by editing the /var/snap/nextcloud/current/nextcloud/config/autoconfig.php file is a problem.

If I change
 // ...
 'directory' => '/media/nextcloud/data',
 // ...

After restarting the snap, the file is changed back to
'directory' => getenv('NEXTCLOUD_DATA_DIR'),

It happens every time.

Thank you for help

**Comment by scubamuc** [comment]
OS ?

**Comment by baaahm** [comment]
Ubuntu server 22.04.2

**Comment by scubamuc** [comment]
confirm [removable media](https://github.com/nextcloud-snap/nextcloud-snap/blob/master/README.md#removable-media)

post `ls -al  /media/nextcloud/data`

**Comment by baaahm** [comment]
With my normal user:
`ls: cannot open directory '/DATA/nextcloud/data': Permission denied`
It is an extra partition for the data directory mounted at /DATA

removable media is active

**Comment by scubamuc** [comment]
need root permission for this
try `sudo ls -al  /media/nextcloud/data` 

confirm [removable media](https://github.com/nextcloud-snap/nextcloud-snap/blob/master/README.md#removable-media)

directory mounted at /DATA will not work, see [confinement](https://github.com/scubamuc/scubamuc.github.io/blob/scubamuc/wiki-md/NEXTCLOUD.snap--snap-confinement.md)

directory will need to be mounted at `/mnt/DATA` or `/media/DATA` as root

**Comment by baaahm** [comment]
```
total 8
drwxrwx--- 2 root root 4096 Mär 13 11:25 .
drwxr-xr-x 3 root root 4096 Mär 13 11:25 ..
```
I now mounted the partition at /mnt/data with the same result. The config file is changed back aber 2x stopping and starting the snap with snap stop/start/ nextcloud.

**Comment by scubamuc** [comment]
alternatively try edit `/var/snap/nextcloud/current/nextcloud/config/config.php` instead of `/var/snap/nextcloud/current/nextcloud/config/autoconfig.php` and making sure the datadirectory setting is pointing to the right place, e.g.:
````
 // ...
 'datadirectory' => ' /mnt/data/nextcloud/data',
 // ...
````

**Comment by baaahm** [comment]
In the config.php is no entry for datadirectory. I added the point and even if both files were edited with ne new path the autoconfig.php falls back (config not). Files were not stored in the new path but still in the old default directory.

**Comment by scubamuc** [comment]
what format is your external device?
post `sudo blkid | grep '/dev/sd'`

**Comment by kyrofa** [comment]
> At step 2 by editing the /var/snap/nextcloud/current/nextcloud/config/autoconfig.php file is a problem.
> 
> If I change
> // ...
> 'directory' => '/media/nextcloud/data',
> // ...
> 
> After restarting the snap, the file is changed back to
> 'directory' => getenv('NEXTCLOUD_DATA_DIR'),

After making the autoconfig.php change, you need to actually finish installing Nextcloud (by creating an admin user). Otherwise, when you restart the snap, it'll just copy config files over again, overwriting what you just did.

**Comment by baaahm** [comment]
Thanks a lot, both of you! That solved my problem :)
