### ISSUE TITLE
Imagick snap for NC-snap

### ISSUE THREAD

**Issue by kz6fittycent** [nextcloud-snap/nextcloud-snap#2363]
I know, I know, this is a sore topic. However, I was reviewing the CVE's regarding Imagick and it appears that the majority (if not all) of them are related to RHEL/CentOS, and not Ubuntu or Debian distros. That said, I have created a [snap](https://github.com/kz6fittycent/imagick/blob/master/snap/snapcraft.yaml) for Imagick; which may be useful to address the security concerns. 

I could create a PR with the Imagick snap listed in the `stage-snaps` section but I didn't want to go thru the work if it wasn't gonna pass muster. There are a couple of useful NC apps that require Imagick, and this could expand the capability of the snap to better match that of a local install.

**Comment by kyrofa** [comment]
Oh not a sore topic, don't worry!

>  I was reviewing the CVE's regarding Imagick and it appears that the majority (if not all) of them are related to RHEL/CentOS, and not Ubuntu or Debian distros.

I haven't reviewed them for a while, but is it your view that the CVEs are actually specific to RHEL's packaging strategy? Or were they simply discovered on RHEL and actually applicable to anything using that version of imagick?

> I have created a [snap](https://github.com/kz6fittycent/imagick/blob/master/snap/snapcraft.yaml) for Imagick; which may be useful to address the security concerns.

That depends on the security model, but this:

> I could create a PR with the Imagick snap listed in the stage-snaps section but I didn't want to go thru the work if it wasn't gonna pass muster.

... negates any benefit, I'm afraid. `stage-snaps` are just unpacked-- they don't retain any interfaces or confinement from the original snap. I'm glad you logged an issue, I would say this won't pass muster indeed.

**Comment by kz6fittycent** [comment]
What if we looked at this from a different perspective...a content interface?
