### ISSUE TITLE
[NC26+] Add PHP-Module `sysvsem`

### ISSUE THREAD

**Issue by Pilzinsel64** [nextcloud-snap/nextcloud-snap#2365]
Nextcloud 26 suggest `sysvsem` as recommended php module for performance reason.
By reading [this](https://help.nextcloud.com/t/26-0-php-extension-sysvsem/158819/5) it is used to limit the amount of previews generated at the same time.

I suggest to add this php module.

![grafik](https://user-images.githubusercontent.com/23138465/229188740-30e81728-affd-432d-8cb6-c7e569929905.png)

_(Seen that after updated our prod to `26/edge` for early testing - except this warning everthing seems to be correct and working! Just as an early feedback.)_

**Comment by razel89** [comment]
How can this error be solved, because it also appears on my nextcloud page, I put the php -m command and the sysvsem module but the error persists, how can it be solved?

**Comment by Pilzinsel64** [comment]
Tested on my prod and works fine! :)
![Screenshot_20230615-055800_Firefox](https://github.com/nextcloud-snap/nextcloud-snap/assets/23138465/c8d98963-81d4-4f1d-a2d3-24e2c8ea371a)
