### ISSUE TITLE
Question about instructions to change data directory to use another disk partition

### ISSUE THREAD

**Issue by dln949** [nextcloud-snap/nextcloud-snap#2366]
I currently have the nextcloud snap package running on an Ubuntu 20.04 machine.  All the data files (photos, music, family movies, films, etc.) are stored on that computer's internal hard drive.  That hard drive has about 780GB of such data on it, and it is now about 93% full.  

I would like to plug a USB external 2TB hard drive into this computer and move all that data to that external drive and have Nextcloud "see" the data there instead on the computer's internal hard drive.  But I'd still like to have Nextcloud itself and all Nextcloud apps to still remain undisturbed on the computer's hard drive.  

I found these instructions, "Change data directory to use another disk partition" (I already have an admin user, and I already have Nextcloud set to access external media) at [https://github.com/nextcloud-snap/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition](url) .  I have a few questions:  

1. Are these the instructions I need to follow for what I am wanting to do?  
2. Do these instructions contain all I need to know in order to do this?  (I am not a Nextcloud expert, so I want to make sure there aren't some missing steps that are assumed I'd know.)  
3. I see that these instructions were last updated over one year ago.  Are they still correct?  
4. One thing I don't understand:  I don't see anywhere in these instructions an explicit command to tell Nextcloud to scan the data in its new location to update Nextcloud's database.  How does that happen?  
5. Once this is all done, will remote clients - e,g,, android nextcloud app, android yaga photo app connected to nextcloud - etc., "know" to find the data in its new location?  

Thanks in advance for helping me with these questions.

**Comment by scubamuc** [comment]
>    1. Are these the instructions I need to follow for what I am wanting to do?

yes, that looks correct

>   2. Do these instructions contain all I need to know in order to do this? (I am not a Nextcloud expert, so I want to make sure there aren't some missing steps that are assumed I'd know.)

the instructions should work as expected

>   3. I see that these instructions were last updated over one year ago. Are they still correct?

the instructions should work as expected

>   4. One thing I don't understand: I don't see anywhere in these instructions an explicit command to tell Nextcloud to scan the data in its new location to update Nextcloud's database. How does that happen?

scan should not be necessary, but can be done manually (see `sudo nextcloud.occ` do `sudo nextcloud.occ files:scan --all`

>   5. Once this is all done, will remote clients - e,g,, android nextcloud app, android yaga photo app connected to nextcloud - etc., "know" to find the data in its new location?

the "new" path is in the config.php thus Nextcloud will know where the files are.  

>Update the Nextcloud config to use the new data directory by editing /var/snap/nextcloud/current/nextcloud/config/config.php and making sure the datadirectory setting is pointing to the right place, e.g.: 

----
> I would like to plug a USB external 2TB hard drive into this computer and move all that data to that external drive and have Nextcloud "see" the data there instead on the computer's internal hard drive.

1. consider external USB 1.x or 2.x may cause performance issues. replacing internal drive may be an option. use dd to clone drive and expand new drive using partition tool (eg. GParted)

2. be sure to disable USB-Boot in BIOS or mount the USB-Device with option `nofail` in FSTAB to ensure boot process doesn't error out when no boot device on USB is discovered. 

3. 780GB is quite a chunk... rather copy before move, just in case

**Comment by dln949** [comment]
Thank you very much.  Regarding your suggestion about including the nofail option in the fstab entry:  

Are there any other options Nextcloud will be needing me to use in that fstab entry?  Would these be the entries I should use?  

auto,nofail,rw,sync,users,exec 0 0

**Comment by scubamuc** [comment]
fstab options are not required by Nextcloud. you can use what works best for you. 

`ext4 defaults,nofail 0 2`
