### ISSUE TITLE
Help with setting up external access! Really need your help!

### ISSUE THREAD

**Issue by mimimi-home** [nextcloud-snap/nextcloud-snap#2367]
Installed Nextcloud 25.0.4 Snap

Everything is working fine on the local network and all computers can access it. I can't connect to the external domain so that I can access Nextcloud from the Internet.

What is it:
- Nextcloud is installed on my local computer - my network address is 192.168.0.100
- Router is connected to the network with a direct IP address
- Binded domain to the Ip address

I have added in the router a virtual server and added 192.168.0.100 Ip address of the computer where the Nextcloud is installed.

What should I do next to have domain access to Nextcloud?

Help me please!

**Comment by kyrofa** [comment]
Network infrastructures can vary dramatically depending on hardware available and ISPs, and debugging network problems remotely is a bear. We are often unable to able to help with IT stuff like that, but we will do our best.

> - Nextcloud is installed on my local computer - my network address is 192.168.0.100
> - Router is connected to the network with a direct IP address
> - Binded domain to the Ip address

Assuming I understand the terminology you're using, this sounds fine so far.

> I have added in the router a virtual server and added 192.168.0.100 Ip address of the computer where the Nextcloud is installed.

I need more details here. Did you set up port forwarding to 192.168.0.100, then? If so, which ports?

**Comment by mimimi-home** [comment]
I didn't change anything in the Nextcloud settings.

**Comment by kyrofa** [comment]
Ah, that's helpful, okay. It looks like you're forwarding port 80, which is good-- add 443 as well and you can use HTTPS.

Once you do that, you _should_ be able to visit your external IP address at this point in your browser and see Nextcloud. Can you confirm?

**Comment by mimimi-home** [comment]
Done, no access.

**Comment by kyrofa** [comment]
Your router might not support hairpinning. Are you able to try it from a completely different network? An AWS-hosted server, perhaps?

**Comment by mimimi-home** [comment]
another computer that is on the local network connects

**Comment by kyrofa** [comment]
Allow me to clarify. You have router R, computer A behind router R which is serving Nextcloud, and computer B behind router R as well. Then you also have computer C, which is on an external network somewhere else (i.e. in AWS). There are three things that will need to be possible to make this work. 

1. Computer B must be able to reach computer A (sounds like that works)
2. Computer B must be able to reach router R's public IP and get forwarded to computer A (hairpinning, sounds like maybe this isn't working)
3. Computer C must be able to reach router R's public IP and get forwarded to computer A (unknown)

Can you report the outcome of all three scenarios?

**Comment by mimimi-home** [comment]
Maybe you need to change the nextcloud configuration.
On another server, I wrote the configuration:
udo nano /etc/apache2/sites-available/nextcloud.conf

<VirtualHost *:80>
ServerAdmin mimimi.home@yandex.ru
DocumentRoot /var/www/nextcloud/
ServerName 192.168.0.100
ServerAlias 192.168.0.100

Alias /nextcloud "/var/www/nextcloud/"

<Directory /var/www/nextcloud/>
Options +FollowSymlinks
AllowOverride All
Require all granted
<IfModule mod_dav.c>
Dav off
</IfModule>
SetEnv HOME /var/www/nextcloud
SetEnv HTTP_HOME /var/www/nextcloud
</Directory>

ErrorLog ${APACHE_LOG_DIR}/error.log
CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>

And here I don't even know how to do it.

**Comment by mimimi-home** [comment]
doesn't work (
What to do?

**Comment by kyrofa** [comment]
I gave you three very clear steps to debug what is happening. Responding with "doesn't work" isn't useful.

**Comment by mimimi-home** [comment]
I'm going to connect my computer directly to the Internet without the router and see if the router is glitchy

**Comment by kyrofa** [comment]
Alright. I'll go ahead and close this since it's not an issue with the snap, but feel free to continue discussion here.

**Comment by mimimi-home** [comment]
Ок, спасибо!

**Comment by slomo-official** [comment]
Do you know that you have to access your nexctloud website via your public ip?
Because the IP that you access your nextcloud instance is not **192.168.0.100** that's your private IP.
You can get your Public IP via websites like this one [](https://www.whatismyip.com/) or in on your routers dashboard.
You might also want to set up DDNSif you don't have a fixed public IP.
[](https://www.cloudns.net/blog/what-is-dynamic-dns/)

**Comment by mimimi-home** [comment]
I followed your scheme. Thank you very much, I figured it out. The problem was in the router, it reset the IP address assignment settings. Now it's all set up and everything works. Many thanks again!
