### ISSUE TITLE
Add `pdo_pgsql` to allow migration to AIO

### ISSUE THREAD

**Issue by yan-foto** [nextcloud-snap/nextcloud-snap#2369]
Would it be possible add `pdo_pgsql` so `nextcloud.occ db:convert-type` also works with PSQL? I'd like to migrate data from my ancient netxcloud box to a proper server using nextcloud AIO.

ref: https://github.com/nextcloud/all-in-one/blob/main/migration.md#migrate-the-files-and-the-database

**Comment by kyrofa** [comment]
I'm sorry, but since the snap bundles everything together, we have a policy of not adding things that most people don't need.

**Comment by yan-foto** [comment]
Fair enough. I considered it as a missing part of `occ db:convert-type` . This feels like a vendor lock now.

**Comment by kyrofa** [comment]
I'm sorry you feel that way. You can import and export mysql databases, so it's definitely not intended to be vendor lock, but installing other drivers would just be bloat.

**Comment by yan-foto** [comment]
I totally get it, thanks.

I'll probably start a container to import the DB and convert it to PSQL.

**Comment by kyrofa** [comment]
Yeah that's the direction I'd go as well.

**Comment by ppittle** [comment]
@yan-foto I'm also trying to migrate an old snap nextcloud instance to a docker-aio instance.

Do you know of any guides that cover how to covert the snap mysql db to psql to support a [db migration](https://github.com/nextcloud/all-in-one/blob/main/migration.md)?

**Comment by yan-foto** [comment]
@ppittle not that I know of. But it shouldn't be that complicated:

1. Start and link 2 containers MariaDB and NextCloud (expose http port of NC container)
2. Import sql dump in MariaDB container (using a volume and the sql import)
3. Navigate to NextCloud in your broweser, setup MySQL (MariaDB) connection
4. Use NextCloud OCC to convert from MySQL to PSQL
5. Dump data and reimport in AIO

I have decided *not* to use AIO  since mouting Docker socket on AIO is not something that I'm comfortable with. Instread, I'm going for Podman (alternative rootless container management) with autoupdates etc.

**Comment by DraconPern** [comment]
I need this also.  This is yet another reason snaps suck.  It basically makes things incompatible with upstream/missing features, etc.
