### ISSUE TITLE
Not able to open Collabora documents

### ISSUE THREAD

**Issue by suzsolt** [nextcloud-snap/nextcloud-snap#2377]
#### Describe the bug
I am not able to open Collabora documents, only able to open Markdown files.
Collabora Online - Built-in CODE Server (ARM64) is installed, but connection to Collabora Online server cannot be established.

#### To Reproduce
1. Go to any .ods file
2. Click on .ods file
3. error: .ods files do not load

#### Expected behavior
.ods files should open in Collabora online

#### Screenshots
<img width="960" alt="Loading" src="https://user-images.githubusercontent.com/121458535/232060210-1e2f8bb7-5036-494d-9f29-d965ba4905e6.png">

<img width="960" alt="Collabora_Online_Server" src="https://user-images.githubusercontent.com/121458535/232060639-826970f6-8b2e-4c5b-8702-897f0a85946d.png">

<img width="960" alt="CODE" src="https://user-images.githubusercontent.com/121458535/232062696-43eb7ecc-10a6-4f98-a472-1a0669b60add.png">

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the

Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  25.0.5snap2  34375  latest/stable  nextcloud✓  -

and:

snap    2.58.3
snapd   2.58.3
series  16
ubuntu  22.04
kernel  5.15.0-1032-oracle

#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).

[log.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/11233701/log.txt)

**Comment by kyrofa** [comment]
We don't support individual apps here, please log an issue against collabora.

**Comment by scubamuc** [comment]
@suzsolt,

see [CODE & Nextcloud Office configuration](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-CODE-and-Nextcloud-office-for-Nextcloud-snap)
