### ISSUE TITLE
Internal Server Error after config.php changes

### ISSUE THREAD

**Issue by TheErasedChild** [nextcloud-snap/nextcloud-snap#2378]
#### Describe the bug
Hi everyone.
I opened this thread because I have configuration problems with access to the nextcloud WebUI.

my configuration:
caddy webserver installed in an LXC container in proxmox reverse proxying the ip address where an ubuntu LXC container is installed with nextcloud snap.
(caddy takes care of SSL certificates, so I left the default configuration with snap's apache).

It worked perfectly, both locally and remotely.
I wanted to manually make changes to the config.php and since then, even accessing nextcloud from local via browser gives me the message: "Internal Server Error".
I restored the previous configuration but nothing changed.
I've had a look at the logs but I can't interpret the error (perhaps I did some damage by not putting it in maintenance mode before the change?)

Thanks in advance for any help you can give me!

Daniel

![Immagine 2023-04-15 152806](https://user-images.githubusercontent.com/43590626/232226910-c2740507-c1d8-4a3c-a7d6-ca82c0619552.png)

![Immagine 2023-04-15 152849](https://user-images.githubusercontent.com/43590626/232226897-0dc081bd-100f-4206-acbe-9509378cd124.png)

I'm using Proxmox Virtual Environment 7.4-3 (x86_64) as main system OS
Nextcloud is running in a LXC container of Ubuntu 22.04.2 LTS (GNU/Linux 5.15.104-1-pve x86_64)

```
root@ubuntu1-nextcloud:~# snap list nextcloud
Name       Version      Rev    Tracking       Publisher    Notes
nextcloud  25.0.5snap2  34372  latest/stable  nextcloud**  -
```
```
root@ubuntu1-nextcloud:~# snap version
snap    2.58.3
snapd   2.58.3
series  16
ubuntu  22.04
kernel  5.15.104-1-pve
```
[Debugging script.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/11239645/Debugging.script.txt)

**Comment by kyrofa** [comment]
I see this in your log, sounds like maybe there is still a config issue:

```
ParseError: syntax error, unexpected single-quoted string "overwrite.cli.url", expecting ")" in /var/snap/nextcloud/34372/nextcloud/config/config.php:42
```

**Comment by TheErasedChild** [comment]
I already tried to change it but it has no effect.
This is my config.php file:

```
  GNU nano 6.2                                                                        /var/snap/nextcloud/current/nextcloud/config/config.php                                                                                 
<?php
$CONFIG = array (
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/snap/nextcloud/current/htdocs/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/snap/nextcloud/current/nextcloud/extra-apps',
      'url' => '/extra-apps',
      'writable' => true,
    ),
  ),
  'supportedDatabases' => 
  array (
    0 => 'mysql',
  ),
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => '/tmp/sockets/redis.sock',
    'port' => 0,
  ),
  'log_type' => 'file',
  'logfile' => '/var/snap/nextcloud/current/logs/nextcloud.log',
  'logfilemode' => 416,
  'passwordsalt' => '**********',
  'secret' => '************',
  'trusted_domains' => 
  array (
    0 => 'cloud.mydomain.com',
    1 => '192.168.2.38',
  ),
  'datadirectory' => '/var/snap/nextcloud/common/nextcloud/data',
  'dbtype' => 'mysql',
  'version' => '25.0.5.1'
  'overwrite.cli.url' => 'https://cloud.mydomain.com',
  'htaccess.RewriteBase' => '/',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost:/tmp/sockets/mysql.sock',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud',
  'dbpassword' => '**********',
  'installed' => true,
  'instanceid' => '********',
  'maintenance' => false,
  'loglevel' => 2,
);
```

**Comment by kyrofa** [comment]
> 'dbtype' => 'mysql',
> 'version' => '25.0.5.1'
> 'overwrite.cli.url' => 'https://cloud.mydomain.com',

Try adding a comma after `'version' => '25.0.5.1'`.

**Comment by TheErasedChild** [comment]
It was just that! you have no idea how many hours of work I spent on it without considering this comma.

I thank you so much,
Daniel

**Comment by kyrofa** [comment]
You're in good company! I think we've all been there at one point or another. Happy to help :) .
