### ISSUE TITLE
Apache config in Snap does not consider WebAssembly (WASM) files

### ISSUE THREAD

**Issue by kroko** [nextcloud-snap/nextcloud-snap#2381]
#### Describe the bug

Apache config in Snap does not consider WebAssembly (WASM) files.
There are apps, that break for this reason on snap installs.
It can be traced upstream to [mime.types](https://github.com/apache/httpd/blob/trunk/docs/conf/mime.types).

#### To Reproduce

1. Install whatever Nextcloud app that does smth using WASM via `.wasm` files, such as [files_3dmodelviewer](https://github.com/WARP-LAB/files_3dmodelviewer)
2. Open file in WEB file tree, where the logic loads WASM files (it lazy loads `draco_decoder.wasm`, `occt-import-js.wasm`, `rhino3dm.wasm`, `web-ifc.wasm`, based on wether the file type requires any of them).
3. `*.wasm` will not be served.

Related issue https://github.com/WARP-LAB/files_3dmodelviewer/issues/11#issue-1666178959

Attaching example STEP file to this issue.

#### Expected behavior

Apache config shipped together with nextcloud-snap considers WASM.
It is not esoteric requirement 😄 , see [the official suggested Nginx config](https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html) that considers WASM OOB.

#### OS/snapd/snap version

```sh
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
```

```sh
snap list nextcloud
Name       Version            Rev  Tracking  Publisher  Notes
nextcloud  25.0.5snap2-dirty  x1   -         -          -
```

```sh
snap version
snap    2.58.3
snapd   2.58.3
series  16
ubuntu  20.04
kernel  5.4.0-139-generic
```

Note that Nextcloud version reported above is self-built in order to confirm that this is an issue in order to make PR that will follow this issue. The actual issue appears in `latest/stable:    25.0.5snap2               2023-04-13 (34372) 275MB`

#### Logs

DNA.

[cube.step.zip](https://github.com/nextcloud-snap/nextcloud-snap/files/11256720/cube.step.zip)

**Comment by kyrofa** [comment]
Release in 25.0.6snap1.
