### ISSUE TITLE
Wiki page "Where to find logs of components" shows wrong locations

### ISSUE THREAD

**Issue by tuxick** [nextcloud-snap/nextcloud-snap#2390]
#### Describe the bug
Wiki page "Where to find logs of components" shows wrong locations

#### Expected behavior
mention correct locations:
/var/snap/nextcloud/current/logs/*.log 
and /var/snap/nextcloud/current/certs/certbot/logs/

**Comment by scubamuc** [comment]
more log locations [here](https://github.com/scubamuc/scubamuc.github.io/blob/scubamuc/wiki-md/NEXTCLOUD.snap_logs.md)
