### ISSUE TITLE
Upgrade Nextcloud to 26

### ISSUE THREAD

**Issue by Pilzinsel64** [nextcloud-snap/nextcloud-snap#2391]
~~Download: https://download.nextcloud.com/server/releases/nextcloud-26.0.1.tar.bz2
Checksum: `6f9c6a1248d7c8af4ad473d73a42565f6adabad4531c5cfa57bc3497b2b64f48`~~

@kyrofa ~~It's not on changelog yet~~ but update is rolled out. Should I already make a PR anyway, or do you even want to do that yourself?

**Comment by kyrofa** [comment]
Go for it! We'll wait for the changelog, but this way the CI will get out of the way.

**Comment by Pilzinsel64** [comment]
Looks like we need to wait for another release, v26.0.2.
https://github.com/nextcloud/server/issues/37610

**Comment by blizzz** [comment]
> Looks like we need to wait for another release, v26.0.2. [nextcloud/server#37610](https://github.com/nextcloud/server/issues/37610)

Please correct me If I am wrong. I understand php is self-contained in a snap, and not shared. Unless you can run multiple instances within the same snap, the issue does not affect you.

**Comment by Pilzinsel64** [comment]
Hm, that is true.
@kyrofa Your thoughts for this? Would I re-open the PR again, if you agree.

**Comment by kyrofa** [comment]
Yes, I agree with @blizzz.

**Comment by Pilzinsel64** [comment]
Version 24.0.1 is on changelog page now: https://nextcloud.com/changelog/

**Comment by willemb2** [comment]
> Version 24.0.1 is on changelog page now

And so is 26.0.1 ;-) But have a look at this issue: https://github.com/nextcloud/photos/issues/1755

**Comment by Pilzinsel64** [comment]
Tested on my prod and works fine!
