### ISSUE TITLE
Can't delete or move files in 25.0.5

### ISSUE THREAD

**Issue by ihack3** [nextcloud-snap/nextcloud-snap#2394]
I can delete whole folders but cannot move or delete single files that I've created or uploaded in 25.0.5. I am able to delete and move the default files that came with the new install of Nextcloud though.

To Reproduce
1. Go to 'files'
2. Click on menu for a file that a user uploaded or created and click delete ,copy or move it gives these errors ~
3. See error "Error deleting file 'user-file_txt'" & "Could not move "user-file_jpg'"

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud
ame       Version      Rev    Tracking       Publisher   Notes
nextcloud  25.0.5snap2  34372  latest/stable  nextcloud✓  -

and:

    $ snap version
snap    2.59.1
snapd   2.59.1
series  16
ubuntu  22.04
kernel  5.19.0-40-generic

#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).

{"reqId":"6V4oTGgckGN9dpiwhpEO","level":3,"time":"2023-04-22T15:50:06+00:00","remoteAddr":"127.0.0.1","user":"user@email.com","app":"onlyoffice","method":"GET","url":"/index.php/core/preview?fileId=6871&x=250&y=250","message":"GetConvertedUri: from pdf to jpeg","userAgent":"Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36","version":"25.0.5.1","exception":{"Exception":"GuzzleHttp\\Exception\\ClientException","Message":"Client error: `POST http://next.cloud.com/index.php/apps/documentserver_community/ConvertService.ashx` resulted in a `405 Method Not Allowed` response","Code":405,"Trace":[{"file":"/snap/nextcloud/34372/htdocs/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":69,"function":"create","class":"GuzzleHttp\\Exception\\RequestException","type":"::"},{"file":"/snap/nextcloud/34372/htdocs/3rdparty/guzzlehttp/promises/src/Promise.php","line":204,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/snap/nextcloud/34372/htdocs/3rdparty/guzzlehttp/promises/src/Promise.php","line":153,"function":"callHandler","class":"GuzzleHttp\\Promise\\Promise","type":"::"},{"file":"/snap/nextcloud/34372/htdocs/3rdparty/guzzlehttp/promises/src/TaskQueue.php","line":48,"function":"GuzzleHttp\\Promise\\{closure}","class":"GuzzleHttp\\Promise\\Promise","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/snap/nextcloud/34372/htdocs/3rdparty/guzzlehttp/promises/src/Promise.php","line":248,"function":"run","class":"GuzzleHttp\\Promise\\TaskQueue","type":"->"},{"file":"/snap/nextcloud/34372/htdocs/3rdparty/guzzlehttp/promises/src/Promise.php","line":224,"function":"invokeWaitFn","class":"GuzzleHttp\\Promise\\Promise","type":"->"},{"file":"/snap/nextcloud/34372/htdocs/3rdparty/guzzlehttp/promises/src/Promise.php","line":269,"function":"waitIfPending","class":"GuzzleHttp\\Promise\\Promise","type":"->"},{"file":"/snap/nextcloud/34372/htdocs/3rdparty/guzzlehttp/promises/src/Promise.php","line":226,"function":"invokeWaitList","class":"GuzzleHttp\\Promise\\Promise","type":"->"},{"file":"/snap/nextcloud/34372/htdocs/3rdparty/guzzlehttp/promises/src/Promise.php","line":62,"function":"waitIfPending","class":"GuzzleHttp\\Promise\\Promise","type":"->"},{"file":"/snap/nextcloud/34372/htdocs/3rdparty/guzzlehttp/guzzle/src/Client.php","line":187,"function":"wait","class":"GuzzleHttp\\Promise\\Promise","type":"->"},{"file":"/snap/nextcloud/34372/htdocs/lib/private/Http/Client/Client.php","line":289,"function":"request","class":"GuzzleHttp\\Client","type":"->"},{"file":"/var/snap/nextcloud/34372/nextcloud/extra-apps/onlyoffice/lib/documentservice.php","line":372,"function":"post","class":"OC\\Http\\Client\\Client","type":"->"},{"file":"/var/snap/nextcloud/34372/nextcloud/extra-apps/onlyoffice/lib/documentservice.php","line":177,"function":"Request","class":"OCA\\Onlyoffice\\DocumentService","type":"->"},{"file":"/var/snap/nextcloud/34372/nextcloud/extra-apps/onlyoffice/lib/documentservice.php","line":91,"function":"SendRequestToConvertService","class":"OCA\\Onlyoffice\\DocumentService","type":"->"},{"file":"/var/snap/nextcloud/34372/nextcloud/extra-apps/onlyoffice/lib/preview.php","line":269,"function":"GetConvertedUri","class":"OCA\\Onlyoffice\\DocumentService","type":"->"},{"file":"/snap/nextcloud/34372/htdocs/lib/private/Preview/ProviderV1Adapter.php","line":53,"function":"getThumbnail","class":"OCA\\Onlyoffice\\Preview","type":"->"},{"file":"/snap/nextcloud/34372/htdocs/lib/private/Preview/GeneratorHelper.php","line":65,"function":"getThumbnail","class":"OC\\Preview\\ProviderV1Adapter","type":"->"},{"file":"/snap/nextcloud/34372/htdocs/lib/private/Preview/Generator.php","line":343,"function":"getThumbnail","class":"OC\\Preview\\GeneratorHelper","type":"->"},{"file":"/snap/nextcloud/34372/htdocs/lib/private/Preview/Generator.php","line":162,"function":"getMaxPreview","class":"OC\\Preview\\Generator","type":"->"},{"file":"/snap/nextcloud/34372/htdocs/lib/private/Preview/Generator.php","line":114,"function":"generatePreviews","class":"OC\\Preview\\Generator","type":"->"},{"file":"/snap/nextcloud/34372/htdocs/lib/private/PreviewManager.php","line":185,"function":"getPreview","class":"OC\\Preview\\Generator","type":"->"},{"file":"/snap/nextcloud/34372/htdocs/core/Controller/PreviewController.php","line":144,"function":"getPreview","class":"OC\\PreviewManager","type":"->"},{"file":"/snap/nextcloud/34372/htdocs/core/Controller/PreviewController.php","line":113,"function":"fetchPreview","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/snap/nextcloud/34372/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"getPreviewByFileId","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/snap/nextcloud/34372/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/snap/nextcloud/34372/htdocs/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/snap/nextcloud/34372/htdocs/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/snap/nextcloud/34372/htdocs/lib/base.php","line":1047,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/snap/nextcloud/34372/htdocs/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/snap/nextcloud/34372/htdocs/3rdparty/guzzlehttp/guzzle/src/Exception/RequestException.php","Line":113,"message":"GetConvertedUri: from pdf to jpeg","CustomMessage":"GetConvertedUri: from pdf to jpeg"}}

**Comment by scubamuc** [comment]
your log: 
`Client error: POST http://next.cloud.com/index.php/apps/documentserver_community/ConvertService.ashx resulted in a 405 Method Not Allowed response","Code":405,`

Seems to be a 3rd-party issue with `documentserver_community`.  There are mentions of similar issues see [here](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/664).

Please consider posting your issue [here](https://github.com/ONLYOFFICE/onlyoffice-nextcloud)

**Comment by noneabove1182** [comment]
Have you checked your file permissions? I just fixed a similar sounding issue yesterday, for some reason I could only delete files from the UI if the file was owned by root or if the permission for other was set to rw..

which is extremely confusing, because the group of the file was www-data, and the permission for group was rw, and root is in the www-data group.. so i'd love someone to explain to me how that's possible (folder matches permissions too)

**Comment by scubamuc** [comment]
see nextcloud-snap [confinement](https://github.com/scubamuc/scubamuc.github.io/blob/scubamuc/wiki-md/NEXTCLOUD.snap--snap-confinement.md).

**Comment by ihack3** [comment]
It turns out those office apps weren't playing to well with the end to end encryption I had enabled. I disabled that and now I can edit and delete new files but the encrypted files are stuck there.
