### ISSUE TITLE
PHP from the snap can't run, errors when adding requested line to crontab

### ISSUE THREAD

**Issue by noneabove1182** [nextcloud-snap/nextcloud-snap#2395]
#### Describe the bug
I added /snap/nextcloud/current/bin/php -f /snap/nextcloud/current/htdocs/cron.php to my crontab as root, but noticed in my logs it never actually ran:

/snap/nextcloud/current/bin/php: error while loading shared libraries: libldap_r-2.4.so.2: cannot open shared object file: No such file or directory

And even worse, when I use my OS's built in php, I still get an error:
App directory "/htdocs/apps" not found! Please put the Nextcloud apps folder in the Nextcloud folder. You can also configure the location in the config.php file.

yet if I go to the htdocs folder you can see apps right there:
/snap/nextcloud/current/htdocs# ls
3rdparty  AUTHORS  console.php  core      dist        index.php  occ           ocs           public.php  resources   status.php  updater
apps      config   COPYING      cron.php  index.html  lib        ocm-provider  ocs-provider  remote.php  robots.txt  themes      version.php

This is a default snap install, though I did update my OS from 20.04 to 22.04, not sure if this was ever working

#### To Reproduce
/snap/nextcloud/current/bin/php -f /snap/nextcloud/current/htdocs/cron.php

#### Expected behavior
The PHP script runs

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

Ubuntu 22.04

root@Server:/snap/nextcloud/current/htdocs# snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  25.0.5snap2  34372  latest/stable  nextcloud✓  -

root@Server:/snap/nextcloud/current/htdocs# snap version
snap    2.59.1
snapd   2.59.1
series  16
ubuntu  22.04
kernel  5.15.0-69-generic

#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).
log is massive with personal data, if it seems relevant i'll prune it and upload

**Comment by scubamuc** [comment]
you need to run cron from within the nextcloud-snap [confinement](https://github.com/scubamuc/scubamuc.github.io/blob/scubamuc/wiki-md/NEXTCLOUD.snap--snap-confinement.md). It is not possible from host.
see nextcloud-snap [cron](https://github.com/scubamuc/scubamuc.github.io/blob/scubamuc/wiki-md/NEXTCLOUD.snap--restart_cron.md)
