### ISSUE TITLE
SSO & SAML authentication doesn't work anymore after 25.0.6snap1 (34542) upgrade.

### ISSUE THREAD

**Issue by theneighb** [nextcloud-snap/nextcloud-snap#2401]
#### Describe the bug
SSO & SAML authentication doesn't work anymore after 25.0.6snap1 (34542) upgrade.
It worked fine with previous versions.

#### To Reproduce
1. Login to nextcloud with  SSO & SAML authentication

#### Expected behavior
login succeed.

#### OS/snapd/snap version

    $ snap list nextcloud --all
Name       Version      Rev    Tracking          Publisher   Notes
nextcloud  25.0.5snap1  34073  latest/candidate  nextcloud✓  disabled
nextcloud  25.0.5snap2  34372  latest/candidate  nextcloud✓  disabled
nextcloud  25.0.6snap1  34542  latest/candidate  nextcloud✓  -

    $ snap version
snap    2.59.1
snapd   2.59.1
series  16
ubuntu  22.04
kernel  5.15.0-70-generic

#### Logs
     from /var/snap/nextcloud/current/logs/nextcloud.log : 
{"reqId":"qhKuurMcFCQw8Xy0SfLr","level":3,"time":"2023-04-25T06:31:57+00:00","remoteAddr":"10.1.0.18","user":"myUserName","app":"index","method":"GET","url":"/index.php/apps/dashboard/","message":"OCA\\Password_Policy\\ComplianceService::entryControl(): Argument #2 ($password) must be of type string, null given, called in /snap/nextcloud/34542/htdocs/apps/password_policy/lib/Listener/BeforeUserLoggedInEventListener.php on line 45","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0","version":"25.0.6.1","exception":{"Exception":"TypeError","Message":"OCA\\Password_Policy\\ComplianceService::entryControl(): Argument #2 ($password) must be of type string, null given, called in /snap/nextcloud/34542/htdocs/apps/password_policy/lib/Listener/BeforeUserLoggedInEventListener.php on line 45","Code":0,"Trace":[{"file":"/snap/nextcloud/34542/htdocs/apps/password_policy/lib/Listener/BeforeUserLoggedInEventListener.php","line":45,"function":"entryControl","class":"OCA\\Password_Policy\\ComplianceService","type":"->"},{"file":"/snap/nextcloud/34542/htdocs/lib/private/EventDispatcher/ServiceEventListener.php","line":87,"function":"handle","class":"OCA\\Password_Policy\\Listener\\BeforeUserLoggedInEventListener","type":"->"},{"file":"/snap/nextcloud/34542/htdocs/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":251,"function":"__invoke","class":"OC\\EventDispatcher\\ServiceEventListener","type":"->"},{"file":"/snap/nextcloud/34542/htdocs/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/snap/nextcloud/34542/htdocs/lib/private/EventDispatcher/EventDispatcher.php","line":88,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/snap/nextcloud/34542/htdocs/lib/private/EventDispatcher/EventDispatcher.php","line":100,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/snap/nextcloud/34542/htdocs/lib/private/legacy/OC_User.php","line":192,"function":"dispatchTyped","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/snap/nextcloud/34542/htdocs/lib/private/legacy/OC_User.php","line":243,"function":"loginWithApache","class":"OC_User","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/snap/nextcloud/34542/htdocs/lib/base.php","line":1103,"function":"handleApacheAuth","class":"OC_User","type":"::"},{"file":"/snap/nextcloud/34542/htdocs/lib/base.php","line":1037,"function":"handleLogin","class":"OC","type":"::"},{"file":"/snap/nextcloud/34542/htdocs/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/snap/nextcloud/34542/htdocs/apps/password_policy/lib/ComplianceService.php","Line":90,"CustomMessage":"--"}}

**Comment by scubamuc** [comment]
please confirm 25.0.6snap1.

![grafik](https://user-images.githubusercontent.com/54933878/234259888-f00c2daf-7f7f-46a8-960b-fb6214cb11d7.png)

**Comment by theneighb** [comment]
![image](https://user-images.githubusercontent.com/131758957/234283487-3bbdbcb8-d65a-43e0-95c0-3cb2def97a40.png)

**Comment by theneighb** [comment]
![image](https://user-images.githubusercontent.com/131758957/234284002-bd1dd97d-f44c-4a41-9008-2f7f7f0b1cd0.png)
the running version is `25.0.6snap1  34542  latest/candidate  nextcloud✓`

**Comment by kyrofa** [comment]
Shoot, I rolled it out before seeing this, sorry @theneighb. Would you mind logging this against upstream Nextcloud, please?

**Comment by kyrofa** [comment]
@theneighb I've re-released 25.0.5snap2 onto a temporary channel for you if you want to stay on it: `stable/sso`.

**Comment by theneighb** [comment]
@kyrofa Ok, thanks

**Comment by nori-st** [comment]
It seems that an error occurred in combination with user_saml & password_policy.
https://github.com/nextcloud/password_policy/pull/461

merged in 25.0.7
