### ISSUE TITLE
"Site cant be reached" error

### ISSUE THREAD

**Issue by rorybellows** [nextcloud-snap/nextcloud-snap#2406]
Everything was working fine yesterday with my home cloud server and now, inexplicably, I keep getting the error message, "This site cant be reached" from my browser and "Server unavailable" on the mobile app.  I even tried connecting to the server at home by going directly through the IP address to no avail.  When I've had issues in the past, any combination of rebooting the server and router, retyping my DNS host info into my router, updating the trusted domains and/or DNS host, would do the trick but nothing seems to make a difference. I'm at a loss of what to do.  

Please help. Thank you so much.

**Comment by dasaweb** [comment]
Maybe your issue is connected with #2405 and it happend when your Nextcloud updated to 25.0.6snap1. In this case try to go back to 25.0.5snap2:

`sudo snap revert nextcloud`

**Comment by rorybellows** [comment]
It worked!  Thank you so much

**Comment by eperezv** [comment]
I had the same issue but the revert option works only partially. My nextcloud instance is randomly unavailable, not sure why
