### ISSUE TITLE
External Storage - Local not working

### ISSUE THREAD

**Issue by jpneergaard** [nextcloud-snap/nextcloud-snap#2408]
#### Describe the bug
I assume that this issue is related to snap since all the documents/tutorials present this as fully functional.

I am running NextCloud SNAP on an Ubuntu 20.04 server VM in VMWare Workstation on a Windows 10 machine.  I have several external USB drives mounted on the host OS.  I've mapped a folder as a shared folder on one of the external drives to the VM.  I've added an fstab entry in Ubuntu to mount the folder to /mnt/hgfs/ncdata.  I then tried to add an external storage entry within NextCloud for /mnt/hgfs/ncdata.

From the guest OS, I can read & write to the /mnt/hgfs/ncdata folder.  But, the NextCloud interface doesn't see any contents.  I've set everything to chmod 777, but that didn't seem to have any effect.

#### To Reproduce
See above

#### Expected behavior
I expected to see the content of the folder from the NextCloud interface.  The folder in question is on the external USB drive that is shared with the VM.  I can see the contents from the guest OS, and also have write access.

#### OS/snapd/snap version

ncadmin@nextcloud:~$ sudo snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  25.0.5snap2  34372  latest/stable  nextcloud✓  -
ncadmin@nextcloud:~$ sudo snap version
snap    2.59.1
snapd   2.59.1
series  16
ubuntu  20.04
kernel  5.4.0-148-generic

#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).

**Comment by kyrofa** [comment]
Make sure that each directory in the `/mnt/hgfs/ncdata` tree is owned by root.

**Comment by jpneergaard** [comment]
> Make sure that each directory in the `/mnt/hgfs/ncdata` tree (i.e. `/`, `/mnt`, `/mnt/hgfs`, and `/mnt/hgfs/ncdata`) is owned by root.

Sorry, I forgot to include that indeed I did a chown -R root:root /mnt/hgfs as well as the chmod -R 777

**Comment by jpneergaard** [comment]
This message now appears when I try to access the Local folder (which is the name of the link to the external storage on the local drive... actually, the local drive on the windows box that is shared to the Ubuntu VM through the shared folder feature of VMware).

Of course the interesting thing is that there are a bunch of files that should appear, but the Readme.md is the only thing listed - but you cant access it.

![image](https://user-images.githubusercontent.com/12038729/236093911-23fce8a8-9bfe-4e7d-9e9a-e000aaf36549.png)

**Comment by kyrofa** [comment]
And you connected the `removable-media` interface?
