### ISSUE TITLE
using nextcloud.export to migrate between different versions of snap

### ISSUE THREAD

**Issue by skinfax** [nextcloud-snap/nextcloud-snap#2410]
Hello,
I need to migrate data from a running nextcloud snap v25 to another at v24.
Can I use the nextcloud.export/import tool to migrate data between different version snaps or will this just work on same versions?
The base problem, is we recently updated our server but some users are complaining of issues with Deck App after the upgrade, so we would like to setup a previous version and migrate data to test things and compare.
Any help will be welcome. Thanks a lot!

**Comment by scubamuc** [comment]
sure you could use export and import. also see here [Nextcloud-snap export & import](https://github.com/scubamuc/scubamuc.github.io/blob/scubamuc/Readme.md#31-nextcloud-snap-export--import)

you could also do it the Snap way. see here [Managing Nextcloud-snap with Snap](https://github.com/scubamuc/scubamuc.github.io/blob/scubamuc/wiki-md/NEXTCLOUD.snap--snap-management.md#managing-nextcloud-snap-with-snap)

**Revert to defined stable channel** 
see [Release strategy](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Release-strategy)

```
sudo snap refresh --channel=24/stable nextcloud
```

official wiki see [Available channels/Release strategy](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Release-strategy)

**Comment by scubamuc** [comment]
to be clear, if you are experiencing an issue with a 3rd-party app I'd suggest creating an issue and getting help from the Deck folks https://github.com/nextcloud/deck

**Comment by skinfax** [comment]
Thank you very much @scubamuc  I will try to open an issue with the app. But anyway, just one more question: does a snap revert keep the user data? (ie the files or whatever has changed since the version update)?
Thanks a lot really!

**Comment by kyrofa** [comment]
I'm afraid this isn't going to work. Refreshing from 25 to 24 and trying to import a 25 export into 24 results in the same thing: a downgrade. Upstream Nextcloud itself doesn't support this, which means the snap can't either. The only way to pull this off is to revert 25 back to 24, which means you lose everything that happened while you were on 25, which almost certainly is undesired at this point (also it means you still need to have the v24 revision around, which you probably don't since several releases have happened since then).

**Comment by skinfax** [comment]
Thank you @kyrofa , i suspected that, and also wanted to know if by reverting i may loose data (which is indeed the case as per your answer).
I will stick to 25 and try to figure out how to sort out problems with the app itself, going back to 24 is a dead-end anyway.
Thank you very much!
