### ISSUE TITLE
Periodically High mysqld CPU load

### ISSUE THREAD

**Issue by dzx-dzx** [nextcloud-snap/nextcloud-snap#2412]
This is a repost of https://help.nextcloud.com/t/periodically-high-mysqld-cpu-load-with-snap-installation/160809. Truly sorry if that's inappropriate.
#### Describe the bug

While monitoring I find that, according to `sysstat`, every 12 minutes the CPU load of two `mysqld` processes spike to 100%. 
Executing `show full processlist` gives the following at the time of the incident:
```
| 16698 | nextcloud       | localhost | nextcloud | Query   |    60 | executing              | SELECT `user_id` FROM `oc_filecache` `f` INNER JOIN `oc_mounts` `m` ON `storage_id` = `storage` WHERE (`size` < 0) AND (`parent` > -1) LIMIT 1 |
```

#### To Reproduce
1. Wait for 12 minutes.
2. Run `show full processlist` from the provided sql client.

#### Expected behavior
The CPU utilization and temperature doesn't spike?

#### OS/snapd/snap version
What OS and version are you running? `25.0.5snap2`
#### Logs
[Untitled-1.md](https://github.com/nextcloud-snap/nextcloud-snap/files/11460121/Untitled-1.md)

**Comment by scubamuc** [comment]
you have a recurring exception pointing to a 3rd party app https://apps.nextcloud.com/apps/drawio

your logs:

> {"Exception":"OCP\\Files\\NotFoundException","Message":"/appdata_octrt98mu9bc/drawio/previews"

> ,"user":"***_***","app":"drawio","method":"DELETE","url":"/remote.php/dav/files/***_***/+++/main.log","message":"Can't delete preview for file: /***_***/files/+++/main.log","userAgent":"Mozilla/5.0 (Windows) mirall/3.8.1stable-Win64 (build 20230419) (Nextcloud, windows-10.0.19044 ClientArchitecture: x86_64 OsArchitecture: 

try deactivating the "drawio" app and see if CPU load is reduced

**Comment by scubamuc** [comment]
watch process mysqld every 5 sec. for 15 min.:

`$ pidstat -G mysqld 5 900`

```
Linux 5.15.0-71-generic (NEXTCLOUD)     05/12/23        _x86_64_        (4 CPU)

09:45:29      UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
09:45:34        0      2714    0.20    0.20    0.00    0.00    0.40     2  mysqld

09:45:34      UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
09:45:39        0      2714    0.40    0.20    0.00    0.00    0.60     2  mysqld

09:45:39      UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
09:45:44        0      2714    0.20    0.40    0.00    0.00    0.60     2  mysqld

Average:      UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
Average:        0      2714    0.27    0.27    0.00    0.00    0.53     -  mysqld
```

**Comment by dzx-dzx** [comment]
Miracle... It does work. The server is quiet now.
I haven't even use the app this year, that's the last thing I'd suspect.

**Comment by dzx-dzx** [comment]
So sorry to disturb again... But the problem seems to persist after hours of tranquility. This time I have the `drawio` app removed, though it somehow remains in the log.
[out.log](https://github.com/nextcloud-snap/nextcloud-snap/files/11472227/out.log)

**Comment by scubamuc** [comment]
after looking at your installed 3rd party apps, there may be some incompatibilities.
your **new** logs:

>May 13 19:47:48 ******-All-Series nextcloud.nextcloud-fixer[15024]: run-parts: executing /snap/nextcloud/34372/fixes/fresh-install/1_disable-theming.sh
May 13 19:47:48 ******-All-Series nextcloud.nextcloud-fixer[15025]: Disabling theming by default...
May 13 19:47:48 ******-All-Series nextcloud.nextcloud-fixer[15025]: error
May 13 19:47:48 ******-All-Series nextcloud.nextcloud-fixer[15025]: theming can't be disabled.
May 13 19:47:48 ******-All-Series nextcloud.nextcloud-fixer[15024]: run-parts: /snap/nextcloud/34372/fixes/fresh-install/1_disable-theming.sh exited with return code 1
May 13 19:47:48 ******-All-Series systemd[1]: snap.nextcloud.nextcloud-fixer.service: Main process exited, code=exited, status=1/FAILURE

the theming app has changed considerably in vs. 25.0x, so try disable this first. reinstalling again afterwards may work.

```
sudo nextcloud.occ app:disable theming

```
also see [managing Nextcloud-snap with Nextcloud management console](https://github.com/scubamuc/scubamuc.github.io/blob/scubamuc/wiki-md/NEXTCLOUD.snap--nextcloud.occ.md#managing-nextcloud-snap-with-nextcloud-management-console)
