### ISSUE TITLE
Why is core-common.js so big?

### ISSUE THREAD

**Issue by technout** [nextcloud-snap/nextcloud-snap#2414]
#### Describe the bug
Not sure what the actual size of /dist/core-common.js should be. But my version is about 13.5 MB in size!
Maybe it was after the last major upgrade but i noticed an unusual spike in bandwidth usage lately and did a log file analysis that pointed to this big, publicly and frequently requested JavaScript library. With hundreds of megabytes a day just for this file!

#### To Reproduce
1. Install the snap docker version as described
2. Run it with some test users and some files and folders, nothing special.
3. Notes the high bandwidth usage and large JavaScript library

#### Expected behavior
This JavaScript file should be 80% smaller, and maybe not so simple to request without authentication?

#### OS/snapd/snap version
Ubuntu 22.04
Nextcloud snap: 25.0.6snap1

**Comment by kyrofa** [comment]
The snap just ships vanilla Nextcloud, please log this against upstream Nextcloud.
