### ISSUE TITLE
I cannot get external storage working

### ISSUE THREAD

**Issue by mwthrane** [nextcloud-snap/nextcloud-snap#2416]
I've installed the pluging external storage and attempted to add a local directory (which is a cifs share).

I've done this:
sudo snap connect nextcloud:removable-media

sudo vim /etc/fstab
//10.0.0.131/Public/nextcloud-backup  /media/nextcloud-backup/  cifs  credentials=/root/.SMBcredentials,file_mode=0777,dir_mode=0777 0       0

@nextcloudtwo:/media/nextcloud-backup$ ls -la $pwd
total 4
drwxrwxrwx 2 root root    0 May 23 18:47 .
drwxr-xr-x 3 root root 4096 May 23 18:37 ..
drwxrwxrwx 2 root root    0 May 23 19:15 backups

@nextcloudtwo:/media$  ls -la $pwd
total 8
drwxr-xr-x  3 root root 4096 May 23 18:37 .
drwxr-xr-x 26 root root 4096 May 23 19:20 ..
drwxrwxrwx  2 root root    0 May 23 18:47 nextcloud-backup

From the host (ubuntu where nextcloud snap is running) i can access the directories and create/delete files as i expected. 
sudo touch hh
ls -la
total 0
drwxrwxrwx 2 root root 0 May 23 19:26 .
drwxrwxrwx 2 root root 0 May 23 18:47 ..
-rwxrwxrwx 1 root root 0 May 23 19:26 hh

I go to external storage in nextcloud and enter:
/media/nextcloud-backup/backups
/media/nextcloud-backup/backups/
/media/nextcloud-backup/
/media/nextcloud-backup

No matter how i type it, I get the RED exclamation mark.
![red](https://github.com/nextcloud-snap/nextcloud-snap/assets/3908460/409a70c5-ae2c-4b2d-b53b-8fd90e50e3fa)

Any ideas?

snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  25.0.6snap1  34542  latest/stable  nextcloud✓  -

snap version
snap    2.58.3
snapd   2.58.3
series  16
ubuntu  18.04
kernel  4.15.0-197-generic

**Comment by scubamuc** [comment]
your `fstab`:

> `//10.0.0.131/Public/nextcloud-backup /media/nextcloud-backup/ cifs credentials=/root/.SMBcredentials,file_mode=0777,dir_mode=0777 0 0`

try:
`//network.local/SHARE /media/mountpoint cifs vers=3.0,username=username,password=password,iocharset=utf8,filemode=0770,dirmode=0770 0 0 `

see [here](https://github.com/scubamuc/scubamuc.github.io/blob/scubamuc/wiki-md/HowTo_add_SAMBA-Shares%26local-shares_to_nextcloud-snap.md)

**Comment by mwthrane** [comment]
> 

Doesn't work either.
Thanks tho.
