### ISSUE TITLE
Old certbot certificates may be used after generating with a new base domain

### ISSUE THREAD

**Issue by scottyeager** [nextcloud-snap/nextcloud-snap#2417]
#### Describe the bug

When `nextcloud.enable-https lets-encrypt` is invoked multiple times with different domains (or different domains in the first position of a multiple domain list), multiple certificate directories accumulate under `certs/certbot/config/live/`. Since the command [selects](https://github.com/nextcloud-snap/nextcloud-snap/blob/88b796324e372d411d843ce408fd2228148b0089/src/https/utilities/https-utilities#L114) the first certs folder according to a simple sort, the wrong certs can be linked as `live`.

#### To Reproduce

1. Provision Ubuntu 22.04 host
2. Point two subdomains to the server's public IP, for example `subdomain1.example.com` and `subdomain2.example.com` (note that the order of the subdomains is important, based on how they will be sorted, and reversing them won't demonstrate the issue)
3. `# snap install nextcloud`
4. `# nextcloud.manual-install name password`
5. `# nextcloud.enable-https lets-encrypt`
6. When prompted for the domain, enter `subdomain1.example.com` 
7. Again, `# nextcloud.enable-https lets-encrypt`
8. This time enter `subdomain2.example.com`

Now we can check which certs are in use:

```
$ ls -l /var/snap/nextcloud/current/certs/
live -> /var/snap/nextcloud/current/certs/certbot/config/live/subdomain1.example.com
```
When we navigate to  `subdomain2.example.com` we won't get a secure connection because the cert for `subdomain1` is in use.

#### Expected behavior

Use the most recently generated certificate.

#### To resolve

A couple potential fixes come to mind:

1. Delete existing certificates at some point during the generation process. Probably don't want to do this before the new certificate is successfully generated
2. Keep track of which certificate was generated last and use that one. This could be done creating the `live` symbolic link during creation or adding another link under `certbot/config/live/` that points to the newest certificate folder. Alternatively, just move old certificates to some kind of archive folder

For the majority of cases, deleting the old certificates would be okay. It seems that, based on the comment in the code at the link above, that having multiple certificate domain folders was never intended.

**Comment by kyrofa** [comment]
Yeah this is a known issue, as you discovered! Both of your ideas seem like a reasonable approach. Is this something you'd like to tackle?

**Comment by scottyeager** [comment]
Hi @kyrofa, I wasn't sure since I didn't find any open issues in a search. I'll take a swing at a solution.
