### ISSUE TITLE
 Enable dailies for Nextcloud to 27

### ISSUE THREAD

**Issue by Pilzinsel64** [nextcloud-snap/nextcloud-snap#2420]
We might want a `27/edge` branche for dailies.
Tarball url: https://download.nextcloud.com/server/daily/latest-stable27.tar.bz2

- [x] [Track exists](https://forum.snapcraft.io/t/nextcloud-track-27/35624?u=kyrofa)
- [x] [Tarball exists](https://cloud.nextcloud.com/call/xs25tz5y#message_1957289)
- [x] [Make changes to `develop`](https://github.com/nextcloud-snap/nextcloud-snap/pull/2436)
- [x] Merge `develop` to `master`

**Comment by kyrofa** [comment]
[Track requested](https://forum.snapcraft.io/t/nextcloud-track-27/35624?u=kyrofa).

**Comment by Pilzinsel64** [comment]
@kyrafo Track & Tarball exists both now! :)

**Comment by Pilzinsel64** [comment]
Hm, seems to be on master now but looks like master can not be tested? Other dailies has been built successfully.

**Comment by Pilzinsel64** [comment]
Yep, the tests for the 27 daily hasn't suggess. The channel `27/edge` [isn't available](https://github.com/nextcloud-snap/nextcloud-snap/actions/runs/5483013222/jobs/9988928947).
I re-triggered the tests for the last commit on `master` that now successed. So, maybe it will be availabel after the upcomming night.
