### ISSUE TITLE
How to increase php-fpm, mysqld and possibly also Redis cache sizes?

### ISSUE THREAD

**Issue by Pajkastare** [nextcloud-snap/nextcloud-snap#2422]
I use a mostly default Nextcloud snap setup under Ubuntu 20.04, running on a Raspberry Pi 4. I want to increase the RAM cache size in order to reduce the disk access (which seems to be a bottleneck). According to iotop, `php-fpm: pool www` and `mysqld` are the most disk-intensive processes.

However, my Nextcloud data (but not the Nextcloud database) is stored on another system, and I access it via a Samba share (over 1 GbE). It is mounted under /mnt/, and as far as the Nextcloud snap is concerned, it should appear as a local filesystem.

**First question: Where can I adjust cache parameters for `php-fpm`/`mysqld` (in the Nextcloud snap)?**

**Second question: Is Redis part of that kind of caching, or is Redis only used for the actual data files (via Samba in my case)?**

**********************

Regarding Redis, I tried (after some googling) to see if changing the "maxmemory" parameter (which is expressed as RAM size in bytes) would make any difference, but I got stuck on even getting it configured in the correct place.

I tried to look for redis-related items like this: `nextcloud.occ config:list | grep -i redis -B 3 -A 3`
I found this:

>         "memcache.locking": "\\OC\\Memcache\\Redis",
>         "memcache.local": "\\OC\\Memcache\\Redis",
>         "redis": {
>             "host": "***REMOVED SENSITIVE VALUE***",
>             "port": 0
>         },
 
I would guess that a "maxmemory" item should be added under the "redis" heading, but how?

I tried `nextcloud.occ config:system:set --type=integer --value=1073741824` followed by variable names such as `redis.maxmemory` and `redis:maxmemory`, but did not find a syntax that did what I wanted (values were added, but not in the "redis" section).
Also, should the type be "integer" or "string"?

***********************
**Edit:** I know about `snap set nextcloud php.memory-limit=1024M`, but it is not clear to me that this is equivalent to reducing disk access.
But I realized that my high disk utilization could also be due to a lot of small sync writes, in case a larger cache would not do anything. Not sure how to monitor this, though...

**Comment by scubamuc** [comment]
you'll not be able to edit cache sizes manually as this will not be exposed for the snap see [confinement](https://github.com/scubamuc/scubamuc.github.io/blob/scubamuc/wiki-md/NEXTCLOUD.snap--snap-confinement.md#snap-confinement-in-nextcloud-snap). this will be the same for "redis" configuration.

you'll not be able to to more than you've done:
> I know about snap set nextcloud php.memory-limit=1024M, but it is not clear to me that this is equivalent to reducing disk access.

i'm guessing your bottleneck is due to 
> Nextcloud data (but not the Nextcloud database) is stored on another system, and I access it via a Samba share (over 1 GbE)

some folks have managed to connect to external data using `sftp` and `nfs` with less "lag". another option could be to "keep data local" but connect to NAS via external-storage-app and Groupfolders. 

could you show IO-States in `iotop` or `sysstat`  %iowait should be near zero even on Raspi:

![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/1eccebb6-f136-4955-85d6-3c7a143f792a)

**Comment by Pajkastare** [comment]
Thanks - I have been using `iostat` and `iotop` to check disk accesses and which process that does what, but I was looking at the "%util" value for the disk, not the CPU "%iowait" value...

It seems the Raspberry Pi is the weakest part of this chain, not Samba. When I push it, e.g. by quickly scrolling through all photos, the %iowait value fluctuates wildly but I saw it exceed 60% for short bursts. It seemed it was the `mysqld` process that was the most disk-using one (it was consistently higher than the `php-fpm` process when `iotop` was sorting on "IO").

The Samba-connected device with the actual files had much lower %iowait and %util values - But not near zero.

This is running the Raspberry from an SD card. IIRC, it's an Samsung Extreme micro-SD card, so pretty good as far as SD cards go, but I suppose I'll have to run it from an USB3 SSD instead if I'm to get better performance from it.


(Sorry about the late response.)
