### ISSUE TITLE
Not able to use letsencrypt for internal Nextcloud - allow DNS-API

### ISSUE THREAD

**Issue by ne0YT** [nextcloud-snap/nextcloud-snap#2432]
#### Describe the bug
I need to use the API of Cloudlfare DNS to generate the letsencrypt SSL as it will be online after my setup is complete, but while settign up I want to keep it offline, but the ssl needs to be the letsencrypt one already to pass my checks.

#### To Reproduce
I cannot chose to use a nextcloud API token to generate my SSL when I need to.

#### Expected behavior
I would prefer ot use the snap as it's currently distributed without building nextcloud with an additional reverse-proxy.

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

nextcloud  25.0.7snap1  35562  latest/stable  nextcloud✓

and:

snap version
snap    2.59.4
snapd   2.59.4
series  16
ubuntu  22.04
kernel  5.15.0-70-generic

**Comment by kyrofa** [comment]
I've wanted this myself, but after looking into it a while ago it sounded like something that was impossible to properly automate. You can definitely fetch certs from Let's Encrypt outside of the snap and configure the snap to use them using `nextcloud.enable-https custom -h`, though. Does that help at all?

**Comment by ne0YT** [comment]
> I've wanted this myself, but after looking into it a while ago it sounded like something that was impossible to properly automate. You can definitely fetch certs from Let's Encrypt outside of the snap and configure the snap to use them using `nextcloud.enable-https custom -h`, though. Does that help at all?
