### ISSUE TITLE
Question: Recover existing users from db

### ISSUE THREAD

**Issue by andrisr223** [nextcloud-snap/nextcloud-snap#2437]
A question whether it is possible to recover from a situation where `nextcloud` instance does not know about
existing users after a system restart and wants to proceed with intstall. Whether it is possible to salvage any user data.
Tried `sudo snap disable nextcloud && sudo snap enable nextcloud` for now.

#### Describe the bug

Nextcloud asks to create an admin account and proceed with install.

#### To Reproduce

The issue started after a server restart.
After restart partition with `nextcloud` data, `snap` location was not immediately available (had to be mounted).

#### Expected behavior

Nextcloud allows to log in with existing user and admin account

#### OS/snapd/snap version

```txt
$ uname -a
Linux serene-shaw 5.4.0-1092-kvm #98-Ubuntu SMP Fri May 19 09:21:45 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  25.0.7snap1  35562  latest/stable  nextcloud✓  -
```

and:

```
$ snap version

snap    2.59.5
snapd   2.59.5
series  16
ubuntu  20.04
kernel  5.4.0-1092-kvm
```

#### Logs

[nextcloud-debug-1.zip](https://github.com/nextcloud-snap/nextcloud-snap/files/11814611/nextcloud-debug-1.zip)

**Comment by scubamuc** [comment]
> Tried `sudo snap disable nextcloud && sudo snap enable nextcloud` for now.

this would only induce automated start of Nextcloud snap at boot.

try:

- **stop Nextcloud snap:** `sudo snap stop nextcloud`

- **mount the device containing data**

- **start Nextcloud snap:** `sudo snap start nextcloud`

see  [managing Nextcloud snap with Snap](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Managing-Nextcloud-snap-with-Snap)
also see [change data directory](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Wiki-Change-data-directory)
especially [path to data directory](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Wiki-Change-data-directory#path-to-data-directory)

**Comment by andrisr223** [comment]
@scubamuc Thanks for the response. It helped.

In the end it was an issue with improperly mounted volumes containing data and configuration. With that solved `nextcloud` starts and works nicely.
