### ISSUE TITLE
Upgrade Nextcloud to 25.0.8

### ISSUE THREAD

**Issue by Pilzinsel64** [nextcloud-snap/nextcloud-snap#2440]
Download: https://download.nextcloud.com/server/releases/nextcloud-25.0.8.tar.bz2
SHA256: `21ae9a7e8a0308d0d9b064a887975d759bcb504ddf53e8d4eaccba32bc54315b`

**Comment by Pilzinsel64** [comment]
@nextcloud-snap/developers I would make a PR, but not sure if I should target branche `develop` or `25`? I mostly made PRs for the most recent version. 😄

**Comment by kyrofa** [comment]
Good instincts: yes, changes made to v25 are no happening on the `25` branch.

**Comment by pachulo** [comment]
I think this is not yet in the beta channel @Pilzinsel64 , isn't it?

**Comment by kyrofa** [comment]
No, it's not.

**Comment by Pilzinsel64** [comment]
Hm, I am very sure that I did see it in the beta channel last week. But you are right, why it isn't yet? 🤔 

Would be #2444 be needed on 25 and 24 Branche as well?

**Comment by pachulo** [comment]
It is now in the `25/beta` channel!

> But you are right, why it isn't yet? 🤔

Because the autobuild failed as a consequence of https://github.com/nextcloud-snap/nextcloud-snap/issues/2443

**Comment by pachulo** [comment]
Upgrade went smooth over here!

**Comment by pachulo** [comment]
It's been 4 days and everything works as expected, I think this is ready to release.

**Comment by kyrofa** [comment]
Alright @pachulo, want to make the CHANGELOG PR?

**Comment by pachulo** [comment]
I've tried with https://github.com/nextcloud-snap/nextcloud-snap/pull/2454 @kyrofa
