### ISSUE TITLE
Snap failing to build due to mdns-publisher

### ISSUE THREAD

**Issue by kyrofa** [nextcloud-snap/nextcloud-snap#2443]
mdns-publisher is failing to build with the following error:

```
Cloning into '/root/parts/mdns-publisher/src'...
Fetching godeps...
cannot find package "golang.org/x/tools/go/vcs" in any of:
	/snap/go/8304/src/golang.org/x/tools/go/vcs (from $GOROOT)
	/root/parts/mdns-publisher/go/src/golang.org/x/tools/go/vcs (from $GOPATH)

go get -d github.com/rogpeppe/godeps
Failed to run 'go get -d github.com/rogpeppe/godeps' for 'mdns-publisher': Exited with code 1.
Verify that the part is using the correct parameters and try again.
Run the same command again with --debug to shell into the environment if you wish to introspect this failure.
Error: Process completed with exit code 2.
```

I detest that it's failing to build with zero changes from us. My proposal isn't to actually fix this: it's to **remove it entirely.**

So what does this component actually DO? It's broadcasts a `nextcloud.local` (or `<hostname>.local`) hostname via mdns, which allows for easy network discovery. It's a feature that has existed from the beginning, when the primary purpose of this snap was the Nextcloud Box, a hardware device based on Ubuntu Core, which was entirely headless. Using mdns meant that you didn't actually need to connect a monitor to it or otherwise determine its IP address before being able to access it. That worked reasonably well, but today I think it's an out-of-date concern. The Nextcloud Box no longer exists, and thus the use-case behind why this component exists in the first place no longer exists.

The downside is: I don't generally like removing things from the snap. It's entirely possible there are users out there that depend on this feature. But that seems unlikely at this point. And if we get bugs logged by people who need it, we can always solve the build failure and add it back in. It's a scream test, which I hate, but it seems warranted here given that this isn't the first time this component has suddenly ceased building.

Thoughts?

**Comment by Pilzinsel64** [comment]
Hm, a common kind of "just happened - over night", it is misterious. I don't have insights to this component. But yes, the time seems to be over for that mdoule. Without deeper investigation (might more people effected, even if only a few) there is no ability to keep it. I gave it quick two mins to quickly search for on Google but didn't find something yet.

Basically, while reading this, I agree with you:
- Remove that module
- Adjust the title name of this issue (or create a new one) and pin it to the top, so users will see this issue very fast, if there are problems.
- If users have problems, we need a deeper research and revert that commit that removes the module.

Let the users test is not nice, but sometimes needed. You can't ask them and have no statistics. 

### My suggestion for what we do now:

__**A)**__
*--> if possible to ignore the tests this time - you did see that they would pass*
1. Merge #2442 
2. Remove in develop and let us test `latest/beta` if we regonize any change.
3. Merge the change with the next PR (~end on July when the new v26 patch is out and beta-tested) to master.
4. If anything goes wrong, we can quickly revert that commit that removes that module.

__**B)**__
1. Remove in develop and let us test for another week `latest/beta` if we regonize any change.
2. Merge #2442 
3. If anything goes wrong, we can quickly revert that commit that removes that module.

**Comment by kyrofa** [comment]
>  --> if possible to ignore the tests this time - you did see that they would pass

This is actually a build failure, not a test failure. We can't ignore it. You'll notice the dailies are behind as well because they have been failing for the same reason.

**Comment by pachulo** [comment]
> The downside is: I don't generally like removing things from the snap. It's entirely possible there are users out there that depend on this feature. But that seems unlikely at this point. And if we get bugs logged by people who need it, we can always solve the build failure and add it back in. It's a scream test, which I hate, but it seems warranted here given that this isn't the first time this component has suddenly ceased building.


This is far from ideal, yes, but to me is more than justified in this case; we don't have the skills or time to maintain [a dependency which latest change is more more than 7.5 years old and its repo already archived](https://github.com/davecheney/mdns).

And it we really need to keep the functionality I guess we should move to something more up-to-date, like https://github.com/hashicorp/mdns, but that would imply a re-write of https://github.com/kyrofa/mdns-publisher
