### ISSUE TITLE
Changed channel from beta (26.0.3.2) to stable (26.0.2.1) and i can't access Nextlcoud for now.

### ISSUE THREAD

**Issue by mattish91** [nextcloud-snap/nextcloud-snap#2446]
#### Describe the bug
Not really a bug, more of a human error 😬

#### To Reproduce
1. As stable 25. something failed an upgrade and revert wasn't working out i did a channel hopp from stable to 26/latest
2. Upgrade daily for a few releases (working fine)
3. Figure stable works as daily upgrades on 26 paled of and change channel to latest/stable

#### Expected behavior
Not sure what i was expecting actually 🤞

#### Screenshots
<img width="548" alt="image" src="https://github.com/nextcloud-snap/nextcloud-snap/assets/6743307/a74790fc-b919-4a05-8f4c-68d5c99d92b4">

#### OS/snapd/snap version
Ubuntu Server 22.04 LTS

    $ snap list nextcloud

Name       Version           Rev     Tracking        Publisher      Notes
nextcloud  26.0.2snap1  35830  latest/stable  nextcloud✓  -

and:

    $ snap version

snap    2.59.5
snapd   2.59.5
series  16
ubuntu  22.04

Any way i can use specific release untill i know that 26.0.3.2 gets released in stable? 
I suppose it's this release: https://github.com/nextcloud/server/releases/tag/v26.0.3 ?

**Comment by kyrofa** [comment]
Oh don't worry, we'll get you sorted! Couple clarifying questions:

> i did a channel hopp from stable to 26/latest

Do you mean `26/edge`?

> Figure stable works as daily upgrades on 26 paled of and change channel to latest/stable

Yep, classic. Nextcloud doesn't support downgrades, so this is expected.

> Any way i can use specific release untill i know that 26.0.3.2 gets released in stable?

I'm afraid not-- you'll need to stay on `26/edge` (assuming that's what you were using) and switch to stable at exactly the right time: once we release 26.0.3, hopefully!

As you probably realized by now, the edge channel is really only for testing. We really don't recommend running production stuff there for several reasons, including this one: it's a really hard train to get off of. Hang tight though, we'll get you there.

**Comment by mattish91** [comment]
Yes, 26/edge is what i ment :) Ill hang tight on the edge channel for now incase i miss the 26.0.3 stable ill shoot back here. 

As it's only running at home (four users), there is no real problem with running the edge channel, it's been really stable trough out. 

Ill go back to 26/latest for now and hopefully soon enough ill be back to latest/stable. 

Thanks for your understanding 😄

**Comment by kyrofa** [comment]
Let's leave this open for now-- once we release 26.0.3 I'll ping you and see if that works for you. If not I have a backup plan, just might take a little longer.

**Comment by YamiYukiSenpai** [comment]
I'm having issues with mine as well.

Only works on 25.0.7snap1

```
Jul 09 03:19:14 skarletsky nextcloud.nextcloud-fixer[2218222]: Check primary keys.
Jul 09 03:19:14 skarletsky nextcloud.nextcloud-fixer[2217599]: run-parts: executing /snap/nextcloud/35562/fixes/existing-install/6_add-missing-primary-keys.sh
Jul 09 03:19:14 skarletsky nextcloud.nextcloud-fixer[2218032]:  - Populating added database structures for workflows
Jul 09 03:19:14 skarletsky nextcloud.nextcloud-fixer[2218032]:  - Add background job to check for backup codes
Jul 09 03:19:14 skarletsky nextcloud.nextcloud-fixer[2218032]:  - Initialize migration of background images from dashboard to theming app
Jul 09 03:19:14 skarletsky nextcloud.nextcloud-fixer[2218032]:  - Send an admin notification if monthly report is disabled
Jul 09 03:19:14 skarletsky nextcloud.nextcloud-fixer[2218032]:      - Repair step already executed
Jul 09 03:19:14 skarletsky nextcloud.nextcloud-fixer[2218032]:  - Switches from default updater server to the customer one if a valid subscription is available
Jul 09 03:19:00 skarletsky nextcloud.nextcloud-fixer[2218032]:  - Install dependencies
Jul 09 03:19:00 skarletsky nextcloud.nextcloud-fixer[2218032]:     0 [--->------------------------]
Jul 09 03:19:00 skarletsky nextcloud.nextcloud-fixer[2218032]:  - Migrate legacy conversation reading states
Jul 09 03:19:00 skarletsky nextcloud.nextcloud-fixer[2218032]:  - Update OAuth token expiration times
Jul 09 03:19:00 skarletsky nextcloud.nextcloud-fixer[2218032]:  - Show a hint about the new editor to existing users
Jul 09 03:19:00 skarletsky nextcloud.nextcloud-fixer[2218032]:  - Clean up meta table
Jul 09 03:19:00 skarletsky nextcloud.nextcloud-fixer[2218032]:  - Set creation and update dates for the library entities without one
Jul 09 03:19:00 skarletsky nextcloud.nextcloud-fixer[2218032]:  - Register Music background jobs and remove legacy registrations
Jul 09 03:19:00 skarletsky nextcloud.nextcloud-fixer[2218032]:  - Combine multi-disk albums and store disk numbers per track
Jul 09 03:19:00 skarletsky nextcloud.nextcloud-fixer[2218032]:  - Remove any playlist files mistakenly added to music_tracks table
Jul 09 03:19:00 skarletsky nextcloud.nextcloud-fixer[2218032]:      - WARNING: ffmpeg binary could not be configured
Jul 09 03:19:00 skarletsky nextcloud.nextcloud-fixer[2218032]:      - go-vod binary is configured: /var/snap/nextcloud/35562/nextcloud/extra-apps/memories/exiftool-bin/go-vod-amd64
Jul 09 03:19:00 skarletsky nextcloud.nextcloud-fixer[2218032]:      - exiftool binary is configured: /var/snap/nextcloud/34375/nextcloud/extra-apps/memories/exiftool-bin/exiftool-aarch64-glibc
```

**Comment by kyrofa** [comment]
Okay @mattish91, 26.0.3 has been released to stable. Can you try switching back?

**Comment by kyrofa** [comment]
@YamiYukiSenpai it's unclear what issues you're encountering, but I suspect it's unrelated to this one. Would you mind logging another issue with more details?

**Comment by LofiTurtle** [comment]
I have a similar issue, except I'm on `latest/beta` instead of `/edge`, and I wasn't able to switch to the stable channel. `sudo snap refresh nextcloud --channel=latest/stable` results in the same "nextcloud doesn't support downgrades" message. 

Here's the output of my `snap list nextcloud`:
```
Name       Version                   Rev    Tracking     Publisher   Notes
nextcloud  26.0.3snap1+git3.054fac4  35877  latest/beta  nextcloud✓  -
```

Is switching like this supposed to work for the beta channel too, or only edge? All I would like to do is switch from `latest/beta` to `latest/stable`.

**Comment by scubamuc** [comment]
@YamiYukiSenpai,

> Jul 09 03:19:00 skarletsky nextcloud.nextcloud-fixer[2218032]:      - WARNING: ffmpeg binary could not be configured
Jul 09 03:19:00 skarletsky nextcloud.nextcloud-fixer[2218032]:      - go-vod binary is configured: /var/snap/nextcloud/35562/nextcloud/extra-apps/memories/exiftool-bin/go-vod-amd64
Jul 09 03:19:00 skarletsky nextcloud.nextcloud-fixer[2218032]:      - exiftool binary is configured: /var/snap/nextcloud/34375/nextcloud/extra-apps/memories/exiftool-bin/exiftool-aarch64-glibc

@kyrofa is right, this is unrelated and not a Nextcloud snap issue. The [Memories app](https://apps.nextcloud.com/apps/memories) you have installed relies on `ffmpeg`which is not included in the snap and is outside of confinement. You'll need to [disable](https://github.com/nextcloud-snap/nextcloud-snap/wiki/OCC-management-console#disable-apps) the app first in order to get to stable and then create an issue with the app developers.

**Comment by scubamuc** [comment]
@LofiTurtle,
see here in [Wiki](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Managing-Nextcloud-snap-with-Snap#revert-to-stable-channel) 
`sudo snao refresh nextcloud --stable` should get you back on stable

**Comment by scubamuc** [comment]
@kyrofa should I close this now?

**Comment by mattish91** [comment]
Im running tje refresh now, i have been out of town since today and just got the message, hopefully not to late

**Comment by mattish91** [comment]
> Okay @mattish91, 26.0.3 has been released to stable. Can you try switching back?

Now it's all done, had to reboot my VM in order to get it up and running again, but now im back to stable once again 🙂

Thanks for your help and by pinging me! 🙂

**Comment by LofiTurtle** [comment]
@scubamuc Thanks, but unfortunately that has the same issue as using `--channel=latest/stable`. snap runs through the various tasks, then fails with the following error:

```
$ sudo snap refresh nextcloud --stable
2023-07-09T10:37:13-07:00 INFO Waiting for "snap.nextcloud.mysql.service" to stop.
error: cannot perform the following tasks:
- Run post-refresh hook of "nextcloud" snap if present (run hook "post-refresh": Nextcloud doesn't support downgrades, but you can revert. See 'snap revert -h' for details.)
```

**Comment by kyrofa** [comment]
> I have a similar issue, except I'm on latest/beta instead of /edge, and I wasn't able to switch to the stable channel. sudo snap refresh nextcloud --channel=latest/stable results in the same "nextcloud doesn't support downgrades" message.

Yeah that's expected. You'll need to wait for master to be ahead of develop, which won't happen until the next release. Just stay on beta for now, it should be pretty stable, and I'll come back here and ping you on the next release.
