### ISSUE TITLE
Improve core js scripts cashing (?)

### ISSUE THREAD

**Issue by Pilzinsel64** [nextcloud-snap/nextcloud-snap#2450]
I open an issue here to discuss again [about this topic](https://help.nextcloud.com/t/loading-new-page-hanging-under-certain-conditions/165873), because I got to the point that it might be a webserver (probably php) configuration.

Please read the topic carefully and also check my later comments. You will see that even in private mode my both manual installed cloud instances can cash its scripts in a private/incognitor window while my private snappy instance is not able to even within android webview clients without (like Files for Android & Notes for Android - seems like they clear the cashe on close).

As all the scripts together loaded again for each single site takes over 50MB. If you just want to open a Note while going shopping e.g. you need 50MB of your expensive mobile data JUST to open the document! This is not feasable, mobile data is very expensive in some countries (like Germany) and public infrastructures has a big lack of free Wi-fi (like schools - this is one of a lot use-case of my private cloud in my family).

@nextcloud-snap/developers Sorry for pinging, but I want to ask you if anyone of you have a little bit knowledge about js cashing!

I'm also going to [ask the Nextcloud devs in the public community chat](https://cloud.nextcloud.com/call/xs25tz5y#message_2008580), I should get an answer for such a question probably.

**Comment by Pilzinsel64** [comment]
Alright, compared with the snap instance of @scubamuc (also NC26):
It works well on his instance. The scripts cache fine.

This is the state of what get caches and what get loaded on re-loading the login page on @scubamuc instance:
![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/23138465/95cf4d49-efd6-40dc-beab-f275b44935ab)
![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/23138465/1cb5b684-ae97-4f48-9585-b4f7639b7491)

And this is the state on my own instance:
![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/23138465/7cd5637f-118a-40da-bc9c-37d126e8d5a4)
![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/23138465/73bb27d8-632b-4661-ac3c-c9d3367c2188)

**Comment by pachulo** [comment]
A stupid and maybe unrelated question @Pilzinsel64 but, why don't you have [HTTP compression](https://github.com/nextcloud-snap/nextcloud-snap#http-compression-configuration) enabled?
In my case that helped with load times and the like

**Comment by Pilzinsel64** [comment]
@pachulo My server hardware was bad and I thought http compression would need even slightly more performance. Also my internet connection is really fast. That's why I didn't enabled it. 🤔 

I now tried to enable it. The result:
Uff, how can this have anything to do with each other...?! It works now exactly the same as on @scubamuc instance and nearly the same as on my other two manual instances.

Initial page load is nearly instant now and reload the page is definitely instant now.

Reload login page of @scubamuc will always load this
![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/23138465/96f881bc-3c13-4e05-abcc-a1b9620751ad)

Reload login page of my instance after enabling http compression:
![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/23138465/b13ec98e-4466-4ad3-9570-c801d2df00f9)

Sorry for that trouble. I took me ages to find that out.
Thank you all for your help and @pachulo for the final tip. I never thought that this could every help me in this situation.

**Comment by Pilzinsel64** [comment]
@scubamuc I tested the mobile clients also with your cloud instance now. It turns out that each single time opening a text file the data transfered increase about 15MB - the size of the `core-common.js` file.
https://dragoncloud.ddnss.de/index.php/s/JQPZtCHf3jBgdzp

I did read that starting with NC28 the size of that file will be less then 2MB. This would much better. I will raise an issue on the Nextcloud Files Android repo anyway, maybe it will help anything.
https://github.com/nextcloud/server/issues/38502

**Comment by scubamuc** [comment]
@Pilzinsel64 my mobile device is always connected to my network including DNS via  (Wireguard) VPN and never leaves my own network. Thus I've never had an issue with data overhead, So possibly data transferred is quicker than on service provider network with service providers DNS. The device is always connected to my cloud instance via app and browser as it is my primary news and mail reader. I've never noticed lags or overhead on my device. But I see your point with the caching situation of `core-common.js`.

**Comment by Pilzinsel64** [comment]
Yea, right. This is another workaround. But I'm sure there are enough people without the ability or knowledge for such things.

I still have no idea if the reason on side of Nextcloud or on side of Snap or even other installation parameters.

Going to make an issue on Files Android GitHub later this day. Let's see what comes out.

**Comment by Pilzinsel64** [comment]
Well, I am still not sure if there is nothing else depending on the installation and the current behavior is still the same:

> This does happen on our two snap installations but not on my other two manual installlations (there it's "only" 8 MB).

But let's see what NC28 will change.

**Comment by scubamuc** [comment]
@Pilzinsel64 fixed & tested in PR https://github.com/nextcloud-snap/nextcloud-snap/pull/2785
