### ISSUE TITLE
[NC27] Tests failing

### ISSUE THREAD

**Issue by Pilzinsel64** [nextcloud-snap/nextcloud-snap#2452]
The (daily) tests for NC27 are failing. [See here](https://github.com/nextcloud-snap/nextcloud-snap/actions/runs/5527822298/jobs/10085545805#step:5:95).

What the reason is for I don't exactly know.

I'm current searching throw the log and a local fresh installation. My current ideas are:

- **Theming** is a default and required app now! You CAN NOT disable it anymore. But it is still disabled in Nextcloud Snap by default.
- There is any other App disabled that is required
- There is any other appt hat is enabled and break everything
- Some apps seems to be not updates(?) and may break everything

**Comment by Pilzinsel64** [comment]
I think this explains everything. 🤔 
![image](https://github.com/nextcloud-snap/nextcloud-snap/assets/23138465/fe440002-1732-4ce6-a062-ab300f5abdd4)

**Comment by kyrofa** [comment]
@Pilzinsel64 man, you're able to debug and fix stuff before I can even _think_ about it, thank you so much! Looks like they fixed it, so let's keep an eye on the tests today.

**Comment by Pilzinsel64** [comment]
@kyrofa If you keep exaggerating like this, I'll blush.

As I regoniced during this issue: What do you think should we do with the thiming app? In Nextcloud since 26 (or even 25?) it is a hard dependency and you can't even disable the app on the normal way with the message "This app can not be disabled.". It isn't even listed on the Web Interface as installable app anymore, like the files app e.g..

Should we go ahead and also enable theming for snap by default? I mean, it is a core feature and were an big feature for the NC25 update. Not sure if keep it disabled is the best anymore. I mean, if someone has problems due theming we can navigate him to the the upstream repo, same as with other core issues. What do you think? 🤔 

We could also open an issue for if you consider we could discuss about.

**Comment by pachulo** [comment]
> We could also open an issue for if you consider we could discuss about. Maybe we can share our experiences with. On my side it mostly works fine.

I think it's best to open a new issue to discuss that, yes.
