### ISSUE TITLE
high idle mysql workload after some hours

### ISSUE THREAD

**Issue by Bobmorton-TX** [nextcloud-snap/nextcloud-snap#2457]
#### Describe the bug
after a few hours 2 mysql threads are causing high cpu load.
I am not sure how to troubleshoot this.

htop shows 2 threads with 50% load each:
 /snap/nextcloud/35883/bin/mysqld --defaults-file=/snap/nextcloud/35883/my.cnf --basedir=/snap/nextcloud/35883  --datadir=/var/snap/nextcloud/35883/mysql  --plugin-dir=/snap/nextcloud/35883/lib/plugin  --user=root --lc-messages-dir=/snap/nextcloud/35883/share --log-error=../logs/mysql_errors.log --pid-file=/tmp/pids/mysql.pid --socket=/tmp/sockets/mysql.sock

#### To Reproduce
after a few hours 2 mysql threads are causing high cpu load.
after reboot this is gone but high load on 2 sql theads comes back after a few hours.

#### Expected behavior
stay at low idle cpu workload

#### Screenshots
![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/86124810/b0401a8d-9e0d-4e36-934d-7229d6ed87f0)

#### OS/snapd/snap version
Armbian 23.02.2 Jammy with Linux 5.10.110-rockchip-rk3588

Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  26.0.3snap1  35883  latest/stable  nextcloud✓  -

snap    2.59.5
snapd   2.59.5
series  16
ubuntu  22.04
[bug report snap 20230713.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/12040165/bug.report.snap.20230713.txt)
[bug report snap 20230713.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/12040172/bug.report.snap.20230713.txt)

kernel  5.10.110-rockchip-rk3588

#### Logs
attached

**Comment by Bobmorton-TX** [comment]
instead of a reboot - just restarting the snap (sudo snap restart nextcloud)
works as well

**Comment by scubamuc** [comment]
see [getting help](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Getting-help)

post your logs
[run the debugging script](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Issue-Debugging-Scripts#debugging-script)

**Comment by scubamuc** [comment]
sorry, just saw your logs now... your issues are not related to Nextcloud snap

I believe these are 3rd-party issues

1. uninstall nextcloud office
your logs
```
        "richdocuments": {
            "disable_certificate_verification": "yes",
            "enabled": "yes",
            "installed_version": "8.0.2",
            "public_wopi_url": "https:\/\/cloud.sessionvictim.com\/extra-apps\/richdocumentscode_arm64\/proxy.php?req=",
            "types": "prevent_group_restriction",
            "wopi_url": "https:\/\/cloud.sessionvictim.com\/extra-apps\/richdocumentscode_arm64\/proxy.php?req="
        },
        "richdocumentscode_arm64": {
            "enabled": "yes",
            "installed_version": "23.5.104",
            "types": ""
```
2. uninstall recognize
your logs:
```
        "recognize": {
            "enabled": "no",
            "faces.batchSize": "50",
            "faces.enabled": "true",
            "faces.lastFile": "1688027570",
            "faces.status": "true",
            "imagenet.batchSize": "20",
            "imagenet.enabled": "true",
            "imagenet.lastFile": "1688027565",
            "imagenet.status": "true",
            "installed_version": "4.3.0",
            "landmarks.batchSize": "20",
            "landmarks.enabled": "false",
            "movinet.batchSize": "5",
            "movinet.enabled": "false",
            "musicnn.batchSize": "20",
            "musicnn.enabled": "false",
            "nice_binary": "\/usr\/bin\/nice",
            "node_binary": "\/var\/snap\/nextcloud\/35883\/nextcloud\/extra-apps\/recognize\/bin\/node",
            "tensorflow.cores": "0",
            "tensorflow.gpu": "true",
            "tensorflow.purejs": "true",
            "types": "filesystem,dav"
```

**Comment by Bobmorton-TX** [comment]
thanks for looking into it. I will disable these apps now and see if this helps

**Comment by scubamuc** [comment]
Adding this for reference: https://github.com/nextcloud/recognize/issues/890
