### ISSUE TITLE
Update: MySQL to 8.0.34

### ISSUE THREAD

**Issue by stondino00** [nextcloud-snap/nextcloud-snap#2460]
Oracle's Quarterly Security Updates

https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-34.html

Release notes will be released tomorrow.

**Comment by kyrofa** [comment]
Wonder if this will help with #2405.

**Comment by kyrofa** [comment]
Let's use the versioned tags only when the issue (or PR) is specific to that version. This will apply to all currently-supported versions.

**Comment by pachulo** [comment]
> Wonder if this will help with https://github.com/nextcloud-snap/nextcloud-snap/issues/2405.

We will have to check in the commits if there's one with the bug [110752](https://bugs.mysql.com/bug.php?id=110752) referenced 🤞

**Comment by kyrofa** [comment]
> We will have to check in the commits if there's one with the bug [110752](https://bugs.mysql.com/bug.php?id=110752)

Doesn't look like it :( .

**Comment by kyrofa** [comment]
Ah, last comment on that bug indicates that it's fixed in 8.0.35.
