### ISSUE TITLE
OCP\Files\NotPermittedException: Could not create folder

### ISSUE THREAD

**Issue by alexx-250323** [nextcloud-snap/nextcloud-snap#2471]
#### Describe the bug
UI shows an Error when trying to empty the whole Trash Bin. If files are removed 100%-1 file no error is given.
My data directory is a fstab rclone mounted IDrive E2 bucket.

#### To Reproduce
1. Upload any file
2. Remove said file
3. Try to empty it from the trash bin

#### Expected behavior
The file should be removed from trash bin

#### OS/snapd/snap version
nextcloud  26.0.3snap1  35883  latest/stable  nextcloud✓  -
snap    2.59.5
snapd   2.59.5
series  16
ubuntu  22.04
kernel  5.15.0-76-generic

#### Logs
Attached log files:
[-- Boot b2e2c0cd4cf84f6a989ca481b07.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/12157300/--.Boot.b2e2c0cd4cf84f6a989ca481b07.txt)
[[webdav] Error OCPFilesNotPermitted.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/12157301/webdav.Error.OCPFilesNotPermitted.txt)

**Comment by scubamuc** [comment]
see [Managing Nextcloud snap with Nextcloud management console](https://github.com/nextcloud-snap/nextcloud-snap/wiki/OCC-management-console)

Cleanup Trashbin specified user:
`sudo nextcloud.occ trashbin:cleanup USERNAME`

or

Cleanup Trashbin all users
`sudo nextcloud.occ trashbin:cleanup --all-users`

**Comment by alexx-250323** [comment]
> I'm quite sure this is not a Nextcloud snap issue

What on the logs makes you so sure that it is not a Nextcloud Snap issue?

**Comment by alexx-250323** [comment]
> > Could it maybe be a general Nextcloud issue (not exclusive of snap version)?
> 
> Possible, I've never seen a similar issue. This points to a permission issue.
> 
> > "Exception":"OCP\Files\NotPermittedException"
> 
> Since the error only appears when clearing trashbin and there are no other file issues mentioned, you obviously know about [confinement](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#snap-confinement-in-nextcloud-snap).
> 
Actually I did not know about that. Might have something to do with it.
> Perhaps you have tried suggested OCC cleanup... it would be interesting to know if `root` was able to clear trashbin.
> 
I tried the command to clean all users(2) trashbins and it ran successfully.

> If you agree that this is not a Nextcloud snap issue, please create an issue with the Nextcloud folks and close here.
You tell me as I honestly don't know how to better approach this issue.
