### ISSUE TITLE
`snap run nextcloud.occ upgrade` fails with mysql error `An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes`

### ISSUE THREAD

**Issue by christiansacks** [nextcloud-snap/nextcloud-snap#2491]
#### Describe the bug
When trying to upgrade the snap for nextcloud it errors with a mysql error about a key being too long

#### To Reproduce

```
root@nextcloud:~# snap run nextcloud.occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Updating <mail> ...
Exception: Database error when running migration 3300Date20230801124717 for app mail
An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes
Update failed
Maintenance mode is kept active
Resetting log level
```

#### Expected behavior
To upgrade without error

#### Screenshots
```
root@nextcloud:~# snap run nextcloud.occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Updating <mail> ...
Exception: Database error when running migration 3300Date20230801124717 for app mail
An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes
Update failed
Maintenance mode is kept active
Resetting log level
```

#### OS/snapd/snap version
What OS and version are you running? 
```
root@nextcloud:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
```

Please also include the output of the following commands:
```
# snap list nextcloud
Name       Version            Rev    Tracking     Publisher   Notes
nextcloud  master-2023-08-08  36723  latest/edge  nextcloud✓  -
```

and:

```
root@nextcloud:~# snap version
snap    2.59.5
snapd   2.59.5
series  16
ubuntu  22.04
kernel  5.15.0-78-generic
```

#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).

**Comment by christiansacks** [comment]
Output from the script above is inside this file; [debug.log](https://github.com/nextcloud-snap/nextcloud-snap/files/12290684/debug.log)

**Comment by Pilzinsel64** [comment]
Yes, @kyrofa is right. I had the same trouble with mail app. Feel free to open an issue at the mail repo @christiansacks ! https://github.com/nextcloud/mail

**Comment by christiansacks** [comment]
Created: https://github.com/nextcloud/mail/issues/8706

**Comment by Pilzinsel64** [comment]
@christiansacks Are you on `27/edge`? At least you are using the latest alpha version of mail. That is why I disabled the app for now to see what happens when I am back on stable or at least beta channel soon.

**Comment by christiansacks** [comment]
```
root@nextcloud:~# snap list|grep nextcloud
nextcloud  master-2023-08-08  36723  latest/edge    nextcloud**  -
```
According to the Administration page in the webui;
Nextcloud Hub 5 (28.0.0 dev Build:2023-08-07T23:34:41+00:00 eb2f3bcb64afce19de2c2893f92a71729209105a)

**Comment by Pilzinsel64** [comment]
Uff, you are on latest/edge. You are really living on the edge, my dear. This is only for testing/development, not for production use at all.

Yes, you should drop these tables. You also should delete everything with app=mail from oc_migrations.

**Comment by kyrofa** [comment]
Yeah, check out the [snap release strategy](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Release-strategy).

**Comment by christiansacks** [comment]
I'm not even sure how I got onto the testing/development branch, I just installed the snap via `snap install nextcloud` and that's what I landed on. I'll have to try and figure out how to go back to a more stable branch. I assume it's fairly simple?

**Comment by christiansacks** [comment]
I managed to get back to stable, but had to completely remove and reinstall nextcloud snap, not entirely straight forward, not hard... but had to rescan for my files and now it's all working ok. Unfortunately this means that I can't test any further for a fix for the original issue, as it completely wiped and started a fresh.
