### ISSUE TITLE
After expanding partition, Nextcloud or Snap does not recognise the new free storage space

### ISSUE THREAD

**Issue by Kaassouffleetje** [nextcloud-snap/nextcloud-snap#2492]
#### Describe the bug
I run nextcloud snap, on Debian, in a VM. I was low on storage and have expanded the VM disk and partition. The Debian VM recognizes the new storage space (lsblk shows this), but Nextcloud still reports it's low on storage

#### To Reproduce
1. Fill up partition
2. Nextcloud will report "Storage almost full", and some things will be disabled (for example, Nextcloud Office/built in CODE server)
3. Expand partition
4. Nextcloud will not detect the new free storage space

#### Expected behavior
Nextcloud or Snap should scan the amount of free space again, remove the warning and enable previously disabled features

#### OS/snapd/snap version
Running in a VM, Debian 11
Snap/Snapd version 2.59.5
Nextcloud snap version 26.0.3snap1

#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).

I have not added the logs because they are incredibly long and contain personal info, like filenames and usernames. I looked through them, and they don't mention disk or storage space.

**Comment by scubamuc** [comment]
[Ubuntu is the only supported distribution](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Why-Ubuntu-is-the-only-supported-distro) for Nextcloud snap.

1. Check if VM disk usage is limited by VM host. 
2. Check if Nextcloud user disk quota is defined in Nextcloud.

- find `10` (iterate variable) largest files in Nextcloud snap:
- `sudo find /var/snap/nextcloud/common/nextcloud/data -type f -printf "%s\t%p\n" | sort -n | tail -10`
- check nextcloud log size
- `sudo du -hs /var/snap/nextcloud/common/nextcloud/data/nextcloud.log` or ` sudo du -hs /var/snap/nextcloud/current/logs/nextcloud.log`

The debugging [script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts) will reliably strip output of personal data.

This is certainly not a Nextcloud snap issue.

**Comment by Kaassouffleetje** [comment]
Thank you for the info. I did not know Ubuntu was the only supported distro, maybe it would be good to add it to the readme? The output of the debugging script does not filter usernames and filenames out of the config and logs. Since the file is half a megabyte I didn't bother stripping it from that info :)

**Comment by scubamuc** [comment]
@Kaassouffleetje, its mentioned in the extensive [Wiki](https://github.com/nextcloud-snap/nextcloud-snap/wiki)
