### ISSUE TITLE
This version of Nextcloud is not compatible with > PHP 8.0. You are currently running 8.1.21.

### ISSUE THREAD

**Issue by mahesh2017** [nextcloud-snap/nextcloud-snap#2501]
My NextCloud installation was working fine. However, from a few days back I started to get the following error message:
**This version of Nextcloud is not compatible with > PHP 8.0.
You are currently running 8.1.21.**

After having trouble, I even tried to update it via beta channel to see if this solves the trouble. However, it hasn't. 

Version: nextcloud  26.0.4snap1+git14.18f28b3

How can I solve this problem?

**Comment by scubamuc** [comment]
> Version: nextcloud 26.0.4snap1+git14.18f28b3
could you revert to stable?

**Comment by mahesh2017** [comment]
Hi,
No, I couldn't revert to stable version as I may have installed beta
version directly when I installed it first time.
I am surprised with this error as NextCloud is using the PHP version
bundled with it. So, such issue shouldn't have occurred.

Is there anyway I can downgrade php version bundled in the snap?

**Comment by kyrofa** [comment]
This doesn't make sense. Beta should be relatively stable, and indeed I just installed it without issue. @mahesh2017 any chance this error is actually coming from one of your apps? Can you [share your logs](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Issue-Debugging-Scripts), please?

**Comment by mahesh2017** [comment]
Hi @kyrofa , 
I've disabled all apps except the following (as the following apps couldn't be disabled with 'sudo nextcloud.occ app:disable ...' command. 
Apps that are active now:
Enabled:
  - cloud_federation_api: 1.10.0
  - dav: 1.27.0
  - federatedfilesharing: 1.17.0
  - files: 1.22.0
  - lookup_server_connector: 1.15.0
  - oauth2: 1.15.1
  - provisioning_api: 1.17.0
  - settings: 1.9.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - viewer: 2.1.0
  - workflowengine: 2.9.0

I'm receiving the same error message even after disabling all third-party apps and then restarting the NextCloud.

**Comment by kyrofa** [comment]
Alright, we're going to need your logs then.

**Comment by mahesh2017** [comment]
Following is the recent log:

{
   "reqId":"DS3v5HFXOJWj9MdJ11MB",
   "level":3,
   "time":"2023-08-17T15:47:14+00:00",
   "remoteAddr":"78.128.191.40",
   "user":"[MASKED_USERID]",
   "app":"webdav",
   "method":"PROPFIND",
   "url":"/remote.php/dav/calendars/[MASKED_USERID]/contact_birthdays/",
   "message":"OC\\DB\\Exceptions\\DbalException: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away",
   "userAgent":"DAVx5/4.3.5.2-gplay (2023/08/07; dav4jvm; okhttp/4.11.0) Android/13",
   "version":"27.0.2.1",
   "exception":{
      "Exception":"Sabre\\DAV\\Exception\\ServiceUnavailable",
      "Message":"OC\\DB\\Exceptions\\DbalException: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away",
      "Code":0,
      "Trace":[
         {
            "file":"/snap/nextcloud/36880/htdocs/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php",
            "line":180,
            "function":"check",
            "class":"OCA\\DAV\\Connector\\Sabre\\Auth",
            "type":"->"
         },
         {
            "file":"/snap/nextcloud/36880/htdocs/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php",
            "line":135,
            "function":"check",
            "class":"Sabre\\DAV\\Auth\\Plugin",
            "type":"->"
         },
         {
            "file":"/snap/nextcloud/36880/htdocs/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
            "line":89,
            "function":"beforeMethod",
            "class":"Sabre\\DAV\\Auth\\Plugin",
            "type":"->"
         },
         {
            "file":"/snap/nextcloud/36880/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php",
            "line":456,
            "function":"emit",
            "class":"Sabre\\DAV\\Server",
            "type":"->"
         },
         {
            "file":"/snap/nextcloud/36880/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php",
            "line":253,
            "function":"invokeMethod",
            "class":"Sabre\\DAV\\Server",
            "type":"->"
         },
         {
            "file":"/snap/nextcloud/36880/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php",
            "line":321,
            "function":"start",
            "class":"Sabre\\DAV\\Server",
            "type":"->"
         },
         {
            "file":"/snap/nextcloud/36880/htdocs/apps/dav/lib/Server.php",
            "line":364,
            "function":"exec",
            "class":"Sabre\\DAV\\Server",
            "type":"->"
         },
         {
            "file":"/snap/nextcloud/36880/htdocs/apps/dav/appinfo/v2/remote.php",
            "line":35,
            "function":"exec",
            "class":"OCA\\DAV\\Server",
            "type":"->"
         },
         {
            "file":"/snap/nextcloud/36880/htdocs/remote.php",
            "line":172,
            "args":[
               "/snap/nextcloud/36880/htdocs/apps/dav/appinfo/v2/remote.php"
            ],
            "function":"require_once"
         }
      ],
      "File":"/snap/nextcloud/36880/htdocs/apps/dav/lib/Connector/Sabre/Auth.php",
      "Line":146,
      "message":"OC\\DB\\Exceptions\\DbalException: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away",
      "exception":{}
   },
   "CustomMessage":"OC\\DB\\Exceptions\\DbalException: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away"
}

**Comment by kyrofa** [comment]
I mean logs generated by [this script](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Issue-Debugging-Scripts), which I shared above.

**Comment by mahesh2017** [comment]
Log is very large. So, I've attached it here. 

[NextCloud logs.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/12372142/NextCloud.logs.txt)

**Comment by mahesh2017** [comment]
Yes, I see it in the web interface.

I have no issues connecting it with Mobile App and Desktop app.

**Comment by kyrofa** [comment]
Would you mind sharing a picture of what you actually see, please?

**Comment by scubamuc** [comment]
@kyrofa , sorry for barging in, but I'm a bit worried about the SQLSTATE exceptions in lines 2743.. 1746, they're caused by mobile app issues.

**Comment by kyrofa** [comment]
I've seen those when mysql runs out of RAM and restarts, too. Not ideal, certainly, but it seems unrelated to this particular issue.

**Comment by kyrofa** [comment]
Can I see the output of this command, please?

    $ cat /snap/nextcloud/current/htdocs/lib/versioncheck.php

**Comment by mahesh2017** [comment]
<?php

declare(strict_types=1);

/**
 * @copyright Copyright (c) 2016 Roeland Jago Douma <roeland@famdouma.nl>
 *
 * @author Christoph Wurst <christoph@winzerhof-wurst.at>
 * @author Morris Jobke <hey@morrisjobke.de>
 * @author Roeland Jago Douma <roeland@famdouma.nl>
 *
 * @license GNU AGPL version 3 or any later version
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 *
 */
// Show warning if a PHP version below 8.0 is used,
if (PHP_VERSION_ID < 80000) {
	http_response_code(500);
	echo 'This version of Nextcloud requires at least PHP 8.0<br/>';
	echo 'You are currently running ' . PHP_VERSION . '. Please update your PHP version.';
	exit(1);
}

// Show warning if >= PHP 8.3 is used as Nextcloud is not compatible with >= PHP 8.3 for now
if (PHP_VERSION_ID >= 80300) {
	http_response_code(500);
	echo 'This version of Nextcloud is not compatible with PHP>=8.3.<br/>';
	echo 'You are currently running ' . PHP_VERSION . '.';
	exit(1);
}

**Comment by kyrofa** [comment]
See the `This version of Nextcloud is not compatible with PHP>=8.3`? THAT is the message you should see if this was originating from the snap. I hate to ask this but... any chance you actually looking at an entirely different nextcloud installation? That's really what this looks like.

**Comment by mahesh2017** [comment]
Ahhh! I changed the subdomain for the Nextcloud and seems like I forgot about the change. I was checking for subdomainn I had installed Nextcloud in the past as you mentioned. 
Shamefully admitting, I wasted several days of mine and some of yours with this silly confusion.
I apologize for it.

**Comment by kyrofa** [comment]
Haha, been there! No trouble, glad that's all it was.
