### ISSUE TITLE
How to use Nextcloud snap with protonmail

### ISSUE THREAD

**Issue by dln949** [nextcloud-snap/nextcloud-snap#2504]
I'm trying to get my protonmail account be the smtp server in my nextcloud snap installation.  I've already installed the protonmail bridge on the same machine that hosts nextcloud.  But entering all the protonmail bridge smtp information into the smtp server in nextcloud won't work.  

I saw this post, https://help.nextcloud.com/t/trying-to-link-to-protonmail/100326/18 , and the post by sohrabsa - currently the last post in the thread - says this:  

I had the same issue with connecting protonmail bridge to Nextcloud and everytime I searched the issue online I would come across this post so I will post it here for anyone who wants to do the same (after you completely setup protonmail bridge with a password manager):

Basically you have to disable peer verification and allow local server.

to disable peer verification add this to Config.php

"mail_smtpstreamoptions" => array(
    'ssl' => array(
        'allow_self_signed' => true,
        'verify_peer' => false,
        'verify_peer_name' => false
    )
),

and then allow local server:

'allow_local_remote_servers' => true,

This lets you setup the SMTP setting and enable the Mail app.

For STARTTSL, you have to choose “None” as the Encryption, both in the Basic Settings and when setting up Mail application.

Here are my questions:  

1)  What are the ramifications of making these changes?  
2)  Where is the config.php file located?  
3)  Can I put these changes anywhere in the config.php file?  
4)  Will future updates of nextcloud snap wipe out these changes, so I'd always have to remember to manually redo  them after every nextcloud snap update?

**Comment by scubamuc** [comment]
> 1. What are the ramifications of making these changes?

@kyrofa , any ideas?
   
>  2. Where is the config.php file located?

[PHP configuration](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-config.php)

>  3. Can I put these changes anywhere in the config.php file?

See [Configuration parameters](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#configuration-parameters)

Make a [backup]((https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-config.php#nextcloud-snap-editing-configuration-file)) before changing anything.
 
> 4. Will future updates of nextcloud snap wipe out these changes, so I'd always have to remember to manually redo them after every nextcloud snap update?

Changes will remain in config.php even after Nextcloud snap update

**Comment by kyrofa** [comment]
@scubamuc is spot on. Regarding the ramifications of those particular configuration parameters, I'm afraid I know nothing about proton, thus I can't vouch for that configuration.

**Comment by scubamuc** [comment]
@dln949 I suggest you simply try and see if it works...

- Be sure to make a backup of config.php before trying this.
- Beware of the config.php syntax. 

It should look more like this:
```
'mail_smtpstreamoptions' => array(
'ssl' => array(
'allow_self_signed' => true,
'verify_peer' => false,
'verify_peer_name' => false,
)
),
```
You'd have to turn to the nextcloud folks for support for this as its not something related to the snap.

**Comment by scubamuc** [comment]
hey @dln949 well that's great... then leave it like it is and be happy :-)

I'm not a developer myself, so I stand to be corrected :+1:
