### ISSUE TITLE
Some odd errors

### ISSUE THREAD

**Issue by mattish91** [nextcloud-snap/nextcloud-snap#2506]
#### Describe the bug
After a server reboot earlier today i do get some odd errors on my install that i have not seen before nor can i really find anything about such an issue.

#### To Reproduce
1. Reboot your server without running sudo snap stop nextcloud?
2. See error

#### Expected behavior
Hopefully a working Nextcloud setup?

#### Screenshots
I managed to expand one of the error messages:
![image](https://github.com/nextcloud-snap/nextcloud-snap/assets/6743307/d8039123-5cf9-4129-ae23-6ff84a62c497)
Here is a full bord of what i can see (Can't expand the php chmod(): Permission denied error):
![image](https://github.com/nextcloud-snap/nextcloud-snap/assets/6743307/91c37d90-f935-4e67-adb8-d683cb1a3fe3)

#### OS/snapd/snap version
Nextcloud 26.0.4Snap1

snap 2.60.2
snapd 2.60.2
series 16
ubuntu 22.04.3
kernel 5.15.0-79-generic

#### Logs
[my paste](https://pastes.io/vdagkefiyp) #Updated with full output.

Any suggestions?

**Comment by mattish91** [comment]
OH! I found the solution! 

Seams to be the Nextcloud app "Recognize" that makes this happen. Phuu im safe for now 😂

Solved by `sudo snap run nextcloud.occ app:disable recognize`
and `sudo snap run nextcloud.occ mainenance:mode --off`

Not activating that one again, thats for sure! 😂

**Comment by scubamuc** [comment]
Adding this for reference: https://github.com/nextcloud/recognize/issues/890
