### ISSUE TITLE
Cannot open documents with built in CODE Server

### ISSUE THREAD

**Issue by suzsolt** [nextcloud-snap/nextcloud-snap#2508]
#### Describe the bug
A clear and concise description of the bug.

#### To Reproduce
1. Go to files
2. Click on any .odt or .ods document
3. See error. It never worked, tried with multiple fresh installs. Collabora Online - Built-in CODE Server (ARM64) cannot connect to the server

#### Expected behavior
The .odt or .ods should open in Collabora online

#### OS/snapd/snap version
Ubuntu 22.04LTS on Amper A1 Oracle instance

    $ snap list nextcloud

Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  26.0.4snap1  36394  latest/stable  nextcloud✓  -

and:

    $ snap version

snap    2.59.5
snapd   2.59.5
series  16
ubuntu  22.04
kernel  5.15.0-1040-oracle

#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).

**Comment by Bobmorton-TX** [comment]
> see [FAQ](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-nextcloud-office-is-not-working-in-nextcloud-snap-what-can-i-do)
> 
> see [Install Nextcloud snap](https://github.com/nextcloud-snap/nextcloud-snap/wiki/install-Nextcloud-snap#recommended-apps)
> 
> **Collabora Online - Built-in CODE Server** is not compatible with Nextcloud snap

this is new - it used to work perfectly 
why was this feature removed?
essential app for a nextcloud install :(

**Comment by scubamuc** [comment]
> this is new - it used to work perfectly

This is certainly not a new issue, see #2288

> why was this feature removed?

**Collabora Online - Built-in CODE Server** is a third party app, see [here](https://github.com/nextcloud-snap/nextcloud-snap/issues/2288#issuecomment-1409423950)

> essential app for a nextcloud install

Agreed, would be nice to have in Nextcloud snap too... but this has been discussed [here](https://github.com/nextcloud-snap/nextcloud-snap/issues/2288#issuecomment-1409423950)

Last mentioned:  in issue #2477 by @Bobmorton-TX

**Comment by Bobmorton-TX** [comment]
up until NC26 I had the Collabora Online - Built-in CODE Server working for 2 years at least. 
Even with NC26 it works when I use the old version of CODE, so it seems to me that there is should be a way to make this work as it did before.
@kyrofa could you confirm this feature is phased out - it would mean I would have to move away from a snap install :(

**Comment by suzsolt** [comment]
> up until NC26 I had the Collabora Online - Built-in CODE Server working for 2 years at least. Even with NC26 it works when I use the old version of CODE, so it seems to me that there is should be a way to make this work as it did before. @kyrofa could you confirm this feature is phased out - it would mean I would have to move away from a snap install :(

Hi @Bobmorton-TX , How did you manage to use an old version of CODE? Could you please support? At the begining of the year it was also working for me, but after a nextcloud update it didn't anymore. I tried several fresh installs but was not able to make it work.

**Comment by Bobmorton-TX** [comment]
check my entry https://github.com/nextcloud-snap/nextcloud-snap/issues/2477

using Rock5B (arm) and armbian.

1. try older version of CODE (works with fresh install)
2. purge db entries for CODE (this made it work for me with existing database)

**Comment by kyrofa** [comment]
>  @kyrofa could you confirm this feature is phased out - it would mean I would have to move away from a snap install :(

I'm not sure what feature we're talking about here: the snap has always maintained a position of not catering to specific third-party applications. We don't offer support for any of them here. Collabora/CODE/whatever-that-other-one-is has always been unreliable: sometimes they work, sometimes they don't, sometimes they grind an entire Nextcloud installation to a halt. These are problems with the app, not the snap. We don't maintain those apps, and thus we can't fix anything within them, nor do we have the manpower to do so.

If you're having issues with a Nextcloud app, I'm afraid you need to log an issue against the app itself.

**Comment by scubamuc** [comment]
See working configuration here: https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-CODE-and-Nextcloud-office-for-Nextcloud-snap

**Comment by Bobmorton-TX** [comment]
> See working configuration here: https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-CODE-and-Nextcloud-office-for-Nextcloud-snap

I ran the steps exactly like listed,  this is not working for my Rock5 (arm) armbian setup.

**Comment by scubamuc** [comment]
oh... that's right, replace "richdocumentscode" with the ARM version. 
@Pilzinsel64 we forgot about ARM users?

**Comment by Bobmorton-TX** [comment]
Yes, i used the arm verison of richdodcumentscode.
Can any arm user confirm its working for them?
