### ISSUE TITLE
"Your web server is not properly set up to resolve "/.well-known/caldav" errors

### ISSUE THREAD

**Issue by ClassickTech** [nextcloud-snap/nextcloud-snap#2510]
Describe the bug
How can be edited below in the snap installation?
In the full installation ".htaccess" should be updated. This well-known error is not allowing me to connect with my iOS device via Cardav and Caldav.

To Reproduce

Go to 'Settings'
Click on 'Overview'
Scroll down to 'Security & setup warnings'
See error
Expected behavior
Should not be warnings.

Errors:
There are some warnings regarding your setup.
Your web server is not properly set up to resolve "/.well-known/caldav". Further information can be found in the [documentation ↗](https://docs.nextcloud.com/server/24/go.php?to=admin-setup-well-known-URL).
Your web server is not properly set up to resolve "/.well-known/carddav". Further information can be found in the [documentation ↗](https://docs.nextcloud.com/server/24/go.php?to=admin-setup-well-known-URL).

nextcloud  26.0.4snap1  36392  latest/stable  nextcloud✓

**Comment by scubamuc** [comment]
Are you running Nextcloud snap behind a reverse proxy? See [here](https://github.com/nextcloud-snap/nextcloud-snap/wiki/NGINX-proxy-manager#advanced-settings-for-nextcloud-snap) and [here](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Putting-the-snap-behind-a-reverse-proxy)
