### ISSUE TITLE
Nextcloud 26 won't start

### ISSUE THREAD

**Issue by YamiYukiSenpai** [nextcloud-snap/nextcloud-snap#2515]
#### Describe the bug
Nextcloud 26 appears to won't start on my system

#### To Reproduce
1. `snap refresh --channel latest/stable nextcloud`

#### Expected behavior
Should be able to access the login page at the very least

#### Screenshots
![image](https://github.com/nextcloud-snap/nextcloud-snap/assets/13153124/07ab9910-2567-418d-b794-fdacfc1f619c)

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud
    Name       Version      Rev    Tracking       Publisher   Notes
    nextcloud  26.0.4snap1  36392  latest/stable  nextcloud✓  -

and:

    $ snap version
    snap    2.60.3
    snapd   2.60.3
    series  16
    ubuntu  22.04
    kernel  6.2.0-32-generic

#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).
[output.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/12517705/output.txt)

**Comment by YamiYukiSenpai** [comment]
I also made sure "Memories" was disabled, which it already was

https://github.com/nextcloud-snap/nextcloud-snap/issues/2446#issuecomment-1627669426

I forgot about the fact I left it on 25 till now.

**Comment by scubamuc** [comment]
We'll need your logs to investigate. Please paste in the output from [this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)

**Comment by YamiYukiSenpai** [comment]
> We'll need your logs to investigate. Please paste in the output from [this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)

https://github.com/nextcloud-snap/nextcloud-snap/files/12517705/output.txt

It's on the original post

**Comment by scubamuc** [comment]
Please paste in the output from [this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)

**Comment by YamiYukiSenpai** [comment]
> Please paste in the output from [this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)

There's massive amount of lines...

**Comment by scubamuc** [comment]
> Run the following command (copy and paste the entire thing into your terminal and press enter). Paste the output into the issue/PR; it's pre-formatted to be a nice comment, so only make it an attachment if it's too long to be a comment.

**Comment by YamiYukiSenpai** [comment]
> > Run the following command (copy and paste the entire thing into your terminal and press enter). Paste the output into the issue/PR; it's pre-formatted to be a nice comment, so only make it an attachment if it's too long to be a comment.

I tried...

its' so long it cuts out a lot of the stuff...

**Comment by scubamuc** [comment]
> It's on the original post

Thanks for pointing that out... its bad practice to expect someone to download your stuff! That's why we have the script.
See [getting help](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Getting-help)

Your issues seem to be due to several [third party apps](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-nextcloud-snap-is-not-working-because-of-third-party-app-incompatibility-what-can-i-do):

Some have been disabled automatically

> Sep 05 01:07:41 skarletsky nextcloud.apache[41517]: Disabled incompatible app: breezedark
> Sep 05 01:07:41 skarletsky nextcloud.apache[41517]: Disabled incompatible app: external
> Sep 05 01:07:41 skarletsky nextcloud.apache[41517]: Disabled incompatible app: ocsms
> Sep 05 01:07:41 skarletsky nextcloud.apache[41517]: Disabled incompatible app: richdocuments

Some should be removed see [here](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-nextcloud-snap-is-not-working-because-of-third-party-app-incompatibility-what-can-i-do)

- facerecognition
- previewgenerator
- recognize
- tvshownamer

**Comment by YamiYukiSenpai** [comment]
> Thanks for pointing that out... its bad practice to expect someone to download your stuff! That's why we have the script.

I understand, but I was following this part:
> only make it an attachment if it's too long to be a comment.

> Some should be removed see [here](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-nextcloud-snap-is-not-working-because-of-third-party-app-incompatibility-what-can-i-do)
> 
> * facerecognition
> * previewgenerator
> * recognize
> * tvshownamer

Ok. Done.  It took a bit, but now it's back.  Thanks!  I'll keep an eye out for the whole day today.
