### ISSUE TITLE
Can't access nextcloud after enabling https

### ISSUE THREAD

**Issue by kemelzaidan** [nextcloud-snap/nextcloud-snap#2517]
#### Describe the bug
I just installed Nextcloud with the snap but after enabling https with let's encrypt I just can't access the application anymore

#### To Reproduce
just use `nextcloud.enable-https lets-encrypt` and follow the instructions

#### Screenshots
![image](https://github.com/nextcloud-snap/nextcloud-snap/assets/897436/0d8db12c-2a5f-436b-8556-ad5e8572e076)

#### OS/snapd/snap version
I'm running nextcloud in a Oracle cloud. The only difference is that it is an ARM64 architecture:

```
uname -a
Linux nextcloud 5.15.0-1040-oracle #46-Ubuntu SMP Fri Jul 14 21:47:21 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```

```
snap --version
snap    2.58.3
snapd   2.58.3
series  16
ubuntu  22.04
kernel  5.15.0-1040-oracle
```

following commands:

    $ snap list nextcloud

```
snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  26.0.4snap1  36394  latest/stable  nextcloud✓  -
```

**Comment by scubamuc** [comment]
See [getting help](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Getting-help)

your issue seems to be a connection issue. check if you can reach the instance using http only (http://IP-ADRESS).

**Comment by kemelzaidan** [comment]
No,

same thing happens when trying to access the IP address. And I know I configured the network to open the required doors:

![image](https://github.com/nextcloud-snap/nextcloud-snap/assets/897436/cf5b881d-d444-473d-a744-3786dc409306)

I can access it when turning off https, but turning it on brings the problem back again. I don't know what to look for in the logs to fix it...

**Comment by scubamuc** [comment]
[Run the debugging script](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Issue-Debugging-Scripts#debugging-script) and post your logs here.
Check port 443 is open on your router

**Comment by scubamuc** [comment]
we don't know Ingress, but according to this: [Oracle Cloud native ingress controller](https://blogs.oracle.com/cloud-infrastructure/post/oracle-cloud-native-ingress-controller-kubernetes) **TLS termination** is managed by the controller. 
Thus you can leave Nextcloud snap https encryption deactivated and let Ingress manage https or find a way to pass through.

That would be similar to letting a [reverse proxy](https://github.com/nextcloud-snap/nextcloud-snap/wiki/NGINX-proxy-manager) manage certificates?

**Comment by kemelzaidan** [comment]
Well, I'm not using Kubernets, but just a VM... I believe Ingress, in that screen, is just for the "incoming traffic" rules. Unless Oracle is using Ingress "under the hood".

**Comment by kemelzaidan** [comment]
Does this error offer any help?


```
https: LogLevel.ERROR: ConnectionError: HTTPSConnectionPool(host='nextcloud.kemelzaidan.com.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4659958310>: Failed to establish a new connection: [Errno 113] No route to host')) while doing a GET request to URL: https://nextcloud.kemelzaidan.com.br/
```

**Comment by scubamuc** [comment]
See [setting FQDN](https://github.com/nextcloud-snap/nextcloud-snap/wiki/configure-Nextcloud-snap#fqdn-for-nextcloud-snap-vm-or-container)

**Comment by kemelzaidan** [comment]
Well, the command `nextcloud.enablehttps lets-encrypt` doe not show any error when trying to run it... Quite the opposite, it shows a successful message, although the certificate doesn't seem to be correctly configured and that's why I believe it's a problem with the snap or at least with this specific service (probably let's encrypt or apache)... I can't see anyway to access Apache configuration to check it.

The  certificates seems to have been generated:

```sh
# ls /var/snap/nextcloud/current/certs/live
README  cert.pem  chain.pem  fullchain.pem  privkey.pem
```

**Comment by scubamuc** [comment]
See [getting help](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Getting-help).
We'll need your logs to investigate. Please paste in the output from [this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)

**Comment by kemelzaidan** [comment]
Here it is:

[output.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/12647677/output.txt)

Thanks for all the help! 😁

**Comment by scubamuc** [comment]
> [Mon Sep 18 00:00:03.483035 2023] [ssl:warn] [pid 7463:tid 281472905802816] AH01909: 127.0.1.1:443:0 server certificate does NOT include an ID which matches the server name

see [setting FQDN](https://github.com/nextcloud-snap/nextcloud-snap/wiki/configure-Nextcloud-snap#fqdn-for-nextcloud-snap-vm-or-container)

> https: LogLevel.ERROR: ConnectionError: HTTPSConnectionPool(host='nextcloud.kemelzaidan.com.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4659958310>: Failed to establish a new connection: [Errno 113] No route to host')) while doing a GET request to URL: https://nextcloud.kemelzaidan.com.br/

this is a connection error `[Errno 113] No route to host` which is why something went wrong while getting the lets encrypt certificate.

**Comment by kemelzaidan** [comment]
Is there anything wrong here?

```
$ sudo cat /etc/hosts
127.0.0.1	localhost
#127.0.1.1	nextcloud	nextcloud
#127.0.1.1	nextcloud.kemelzaidan.com.br	nextcloud
144.22.182.242	nextcloud.kemelzaidan.com.br	nextcloud

# The following lines are desirable for IPv6 capable hosts
::1	ip6-localhost	ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
ff02::3	ip6-allhosts
```
I did a clean install again and the same problem happens. When trying to enable HTTPS with let's encrypt with `sudo nextcloud.enable-https lets-encrypt` gives me the following find error at the end, even though I using sudo to run the command:

```
Have you met these requirements? (y/n) y
Please enter an email address (for urgent notices or key recovery): kemelzaidan@gmail.com
Please enter your domain name(s) (space-separated): nextcloud.kemelzaidan.com.br
Attempting to obtain certificates... done
find: Failed to restore initial working directory: /home/ubuntu/snap/nextcloud: Permission denied
Restarting apache... done
```

**Comment by scubamuc** [comment]
hey, nope it seems like you've done the necessary... good :+1: 
There is still a connection error. The Host is not reachable. @kyrofa please can you confirm?
I'm quite sure this is not a Nextcloud snap issue, its a connection issue and I believe it has to do with your VM on Oracle cloud. Have you tried contacting support at Oracle?

**Comment by scubamuc** [comment]
@kemelzaidan, did you by any chance change the default ports of your instance?
please show the output of:
```
sudo snap get nextcloud
```
the output should look something like this:
```
Key        Value
http       {...}
mode       production
nextcloud  {...}
php        {...}
ports      {...}
private    {...}

```

**Comment by kemelzaidan** [comment]
No, I didn't change the ports. The values are the default ones.

**Comment by scubamuc** [comment]
@kyrofa can you please assist.... I have no more ideas.

**Comment by felipegenef** [comment]
Hey guys this is happening to me as well! 
I've tryed many subdomains and its always the same:
- HTTP works well, even with my subdomain
- After  `sudo nextcloud.enable-https lets-encrypt` I get an :
```
Attempting to obtain certificates... done
find: Failed to restore initial working directory: /home/ubuntu: Permission denied
Restarting apache... done
```
- then the connection to nextcloud stop working

It seams to be an error on snap version or on ubuntu . I'm running my nextcloud from an AWS Ec2 instance...

**Comment by felipegenef** [comment]
I Also tryed to add the lets-encrypt generated certificate as a custom certificate (using the command `nextcloud.enable-https custom certPath.pem keypath.pem chainPath.pem`) and I got the same result.
From all the tutorials I found on the internet there is no sign of that Permission denied error, and everything works well... 
It should be a recent update error from snap version or ubuntu.

**Comment by scubamuc** [comment]
@kyrofa @pachulo, I'm running out of ideas here, could someone please assist?

**Comment by scubamuc** [comment]
@kemelzaidan, did you contact support? I found this: https://docs.oracle.com/en/cloud/saas/b2c-service/facca/t-Activate-an-SSL-certificate-ed7902BA.html#ActivateSSLCertificate-ED7902BA

**Comment by scubamuc** [comment]
@felipegenef, also AWS has experienced changes: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/SSL-on-amazon-linux-2.html

**Comment by kemelzaidan** [comment]
I believe I should keep the FQDN the same right?

**Comment by scubamuc** [comment]
@Pilzinsel64, can you assist here please?

**Comment by Pilzinsel64** [comment]
@kemelzaidan Can you show me the output of this command, please? `ls -l /home/ubuntu`

**Comment by kemelzaidan** [comment]
Sure @Pilzinsel64. Thanks for the help. Here it is:

```bash
$ ls -l /home/ubuntu/
total 168
-rwxr-xr-x 1 ubuntu ubuntu   2123 Sep 18 12:19 nextcloud-debugging-script.sh
-rw-rw-r-- 1 ubuntu ubuntu 160093 Sep 18 13:40 output.txt
drwx------ 3 ubuntu ubuntu   4096 Sep  6 20:04 snap
```

**Comment by Pilzinsel64** [comment]
Hm, looks like the owner is "ubuntu" and not "root" for the snap folder.
Try this:
```
sudo chown -R root:root /home/ubuntu
```

**Comment by kyrofa** [comment]
`/home/ubuntu` SHOULD be owned by ubuntu. All sorts of things will start to break if you make it owned by root.

**Comment by kyrofa** [comment]
> find: Failed to restore initial working directory: /home/ubuntu: Permission denied

This is because `find` (used in the script to find the certs) tries to cd back to where it started, and under confinement the snap doesn't have access to `/home/ubuntu`. I suspect this error is a red herring, and it not actually related to why the snap can't be reached. It looks like certificates are fetched successfully.

**Comment by kemelzaidan** [comment]
@kyrofa yes, the certificates are fetched successfully since they are installed in the right folder.

**Comment by kemelzaidan** [comment]
Despite that, the application doesn't work. I'll try to install it through Docker since the snap doesn't work in this case. Thanks.
