### ISSUE TITLE
Nextcloud will not start?

### ISSUE THREAD

**Issue by dd900** [nextcloud-snap/nextcloud-snap#2519]
I'm not sure what happened. I was at work and when I got home I could not access Nextcloud anymore. I have no logs to look at. The `current` directory is empty. `snap refresh` complains about nextcloud being disabled. And many of the Nextcloud services can't be found. Sorry I don't have more. Believe me I wish I did.

Here is the output from the debug script linked [here](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Issue-Debugging-Scripts#debugging-script)

[debug script output.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/12591634/debug.script.output.txt)

**Comment by scubamuc** [comment]
view failed services

`sudo systemctl list-units --state failed `

if all is well you should see `0 loaded units listed.` you'll probably have some listed

**Comment by kyrofa** [comment]
> `snap refresh` complains about nextcloud being disabled

Maybe give `sudo snap enable nextcloud` a shot?

**Comment by dd900** [comment]
Ubuntu 22.04.3

> ```
> $ snap list nextcloud
> ```

nextcloud  26.0.4snap1  36392  latest/stable  nextcloud✓  disabled

> ```
> $ snap version
> ```

```
snap    2.60.3
snapd   2.60.3
series  16
ubuntu  22.04
kernel  6.2.0-32-generic
```

> ```
> $ sudo systemctl list-units --state failed 
> ```

```
  UNIT                                   LOAD      ACTIVE SUB    DESCRIPTION
● snap.nextcloud.apache.service          not-found failed failed snap.nextcloud.apache.service
● snap.nextcloud.mysql.service           not-found failed failed snap.nextcloud.mysql.service
● snap.nextcloud.nextcloud-cron.service  not-found failed failed snap.nextcloud.nextcloud-cron.service
● snap.nextcloud.nextcloud-fixer.service not-found failed failed snap.nextcloud.nextcloud-fixer.service
● snap.nextcloud.php-fpm.service         not-found failed failed snap.nextcloud.php-fpm.service
● snap.nextcloud.redis-server.service    not-found failed failed snap.nextcloud.redis-server.service
● snap.nextcloud.renew-certs.service     not-found failed failed snap.nextcloud.renew-certs.service
● snap.nextcloud.logrotate.timer         not-found failed failed snap.nextcloud.logrotate.timer

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.
8 loaded units listed.
```

> Maybe give sudo snap enable nextcloud a shot?

Tried that already.

```
error: cannot perform the following tasks:
- Make snap "nextcloud" (36392) available to the system (cannot cleanup failed attempt at making snap "nextcloud" available to the system: cannot remove snap current symlink: remove /var/snap/nextcloud/current: directory not empty)
- Make snap "nextcloud" (36392) available to the system (symlink 36392 /var/snap/nextcloud/current: file exists)
```

Everything else on my server is still running fine and as far as I can tell there has been no unauthorized access to the server.

**Comment by scubamuc** [comment]
@kyrofa this is strange: `(cannot cleanup failed attempt at making snap "nextcloud" available to the system: cannot remove snap current symlink: remove /var/snap/nextcloud/current: directory not empty)` maybe manually created files or permissions?

@dd900 please post output of `ls -al /var/snap/nextcloud/current` and `ls -al /var/snap/nextcloud/current/`

**Comment by scubamuc** [comment]
@dd900 please post output of `sudo snap list --all` ... could there be two nextcloud instances???

**Comment by dd900** [comment]
> `ls -al /var/snap/nextcloud/current/`

```
total 12
drwxr-xr-x 3 root root 4096 Sep 12 17:08 .
drwxr-xr-x 6 root root 4096 Sep 12 17:08 ..
drwxr-xr-x 2 root root 4096 Sep 12 19:11 logs
```

> `sudo snap list --all`

```
nextcloud    26.0.3snap1    35878    latest/stable    nextcloud✓    disabled
nextcloud    26.0.4snap1    36392    latest/stable    nextcloud✓    disabled
```

It seems there are two instances of nextcloud.

**Comment by scubamuc** [comment]
> It seems there are two instances of nextcloud.

no, those are revisions which are retained automatically by Snapd... that's your "backup" if you were to revert to the previous version.

> total 12
drwxr-xr-x 3 root root 4096 Sep 12 17:08 .
drwxr-xr-x 6 root root 4096 Sep 12 17:08 ..
drwxr-xr-x 2 root root 4096 Sep 12 19:11 logs

is that your complete output of `ls -al /var/snap/nextcloud/current/` ? It says `total 12` but you're only showing `../logs` and there should be `total 9`.

please post complete output of `ls -al /var/snap/nextcloud/current/`

**Comment by dd900** [comment]
> please post complete output of ls -al /var/snap/nextcloud/current/

That is the complete output

**Comment by dd900** [comment]
I tried to remove all instances of nextcloud and start fresh from a backup, but everytime I try to reinstall nextcloud I get the same error about not being able to remove the current symlink at the nextcloud/current directory. I removed the folders manually after i uninstalled nextcloud and still got the same error.

**Comment by kyrofa** [comment]
Can I see the output of `ls -l /var/snap/nextcloud`, please? It actually sounds like that isn't symlink at all, which is problematic.

**Comment by dd900** [comment]
> ls -l /var/snap/nextcloud

```
total 4
drwxr-xr-x 3 root root 4096 Sep 13 19:22 current
```

That's the full output. Tried deleting /var/nextcloud manually and installing got this error. (same as before)
```
error: cannot perform the following tasks:
- Copy snap "nextcloud" data (failed to remove snap "nextcloud" base directory: remove /var/snap/nextcloud: directory not empty)
- Make snap "nextcloud" (37045) available to the system (cannot cleanup failed attempt at making snap "nextcloud" available to the system: cannot remove snap current symlink: remove /var/snap/nextcloud/current: directory not empty)
- Make snap "nextcloud" (37045) available to the system (symlink 37045 /var/snap/nextcloud/current: file exists)
```

Sorry I have been super busy at work lately. I appreciate the help.

**Comment by scubamuc** [comment]
@kyrofa, there are two pointers to this symlink, that's why I had remarked "could there be two instances?" [here](https://github.com/nextcloud-snap/nextcloud-snap/issues/2519#issuecomment-1718353555)

1.  `symlink 37045 /var/snap/nextcloud/current` (older)
2.  `symlink 36392 /var/snap/nextcloud/current`  (latest)

**Comment by kyrofa** [comment]
Interesting, this isn't a symbolic link. It needs to be. Any chance you're using a filesystem type that doesn't support them? Can we see the output of `df -Th`, please?

**Comment by dd900** [comment]
> df -Th

```
Filesystem     Type     Size  Used Avail Use% Mounted on
tmpfs          tmpfs    1.6G  5.8M  1.6G   1% /run
/dev/nvme0n1p2 ext4     234G   33G  189G  15% /
tmpfs          tmpfs    7.8G     0  7.8G   0% /dev/shm
tmpfs          tmpfs    5.0M  4.0K  5.0M   1% /run/lock
/dev/nvme0n1p1 vfat     511M  6.1M  505M   2% /boot/efi
/dev/sda1      ext4     229G   11G  206G   5% /ssd
/dev/sdb1      ext4     3.6T  370G  3.1T  11% /media/containerdata
/dev/sdd1      ext4     7.3T  380G  6.9T   6% /backup
/dev/sdc1      fuseblk  5.5T  2.7T  2.8T  50% /retrodrive
```
