### ISSUE TITLE
Improve CD so PRs snaps can be safely uploaded to the store

### ISSUE THREAD

**Issue by pachulo** [nextcloud-snap/nextcloud-snap#2521]
Hi,

Well, yesterday I couldn't sleep and I was reading about all the problems @kyrofa mentioned around [not having a proper](https://github.com/nextcloud-snap/nextcloud-snap/issues/1818#issuecomment-952183030) way to automate the release process and the testing of PRs anymore, because support to build snaps [from Docker](https://forum.snapcraft.io/t/build-on-docker/4158/20?u=pachulo) is [hacky](https://forum.snapcraft.io/t/build-on-docker/4158/30?u=pachulo).
From what he wrote in [A better way to review Hithub pull requests for snaps](https://kyrofa.com/posts/a-better-way-to-review-github-pull-requests-for-snaps/), I get that the main problem is this one:
> Besides, we already have one of those– the snap store! Why can’t we just upload there? Because it involves a very private token, which would need to be exposed on pull requests to the code random people submit, which means anyone can just steal your private token and start releasing snaps your behalf. I hope you agree that such a thing would be bad.

So, while thinking "There must be a way, our project can't be the only one with such problem", I found this nice post by @mheap: https://michaelheap.com/access-secrets-from-forks/
The main idea behind it is that:
> GitHub Actions provides a triggering actor field that lets you know who ran (or re-ran) a workflow. This allows maintainers to provide access to secrets on forks once they’ve checked the changes manually and are happy that they don’t pose a security risk by re-running a job.

And also this:
> ...a mostly safe way to run workflows with access to secrets when a pull request is raised from a fork.
> Why mostly safe rather than 100% safe? It relies on humans to read the pull request diff and make a good decision. We’re all human and mistakes happen. At some point a PR will get run that shouldn’t have been, and you’ll need to rotate your secrets.

So, I think that would be a viable option to create a GitHub action to push the built snaps from a PR to the store, that would fail when the PR is opened by the external contributor, but one of the maintainers can re-ran it once the code has been checked.

Please, bear with me if I'm missing something, this is just me trying to really understand how all this works.

**Comment by kyrofa** [comment]
The "proper" github way to do this would be to run the [upload workflow from one of our branches](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/), using something like this:

```
on:
  workflow_run:
    workflows: ["test"]
    types:
      - completed
```

That workflow then downloads the snap from the artifacts of the pull request, and uploads it from controlled code. I almost have that working, but I can't figure out how to get the pull request number using the github API. Code that downloads the snap looks like this:

```
- name: Download snap artifact
        uses: actions/github-script@v5
        with:
          script: |
            var artifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "snap"
            })[0];
            var download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/snap.zip', Buffer.from(download.data));
```

But I haven't had any luck getting a pull request number from there for determining the channel.

**Comment by pachulo** [comment]
hmmm, interesting! Didn't know about that option.

Not the most elegant way, but what about saving another artifact, apart from the snap, with the PR name on it? Would that work?

**Comment by kyrofa** [comment]
It would work inasmuch it would give us the information we need to release the snap, but it wouldn't work in that it would be hackable; it means a PR could manipulate the channel into which it would be released. I'd rather avoid that possibility.

**Comment by pachulo** [comment]
Sorry, I meant the PR number, not the PR _name_. That shouldn't be manipulable, shouldn't it?

**Comment by kyrofa** [comment]
Sorry, I'm operating on some assumed knowledge here: I generally use the PR number to determine the channel, e.g. `latest/beta/pr-<whatever>`. If we make it possible for the PR author to manipulate the `<whatever>`, they can overwrite the snaps from other PRs.

**Comment by kyrofa** [comment]
Alright I think I finally sorted this out. Please see #2529.
