### ISSUE TITLE
[Documentation] Update backup instructions

### ISSUE THREAD

**Issue by Flaburgan** [nextcloud-snap/nextcloud-snap#2522]
Hello everyone, thank you for the good work.

I'd like to suggest to update the backup / migration instructions for the snap installation. Indeed, there are two methods described and it is not clear which one should be used. When searching in search engines "backup nextcloud snap" the page we find is https://github.com/nextcloud-snap/nextcloud-snap/wiki/How-to-backup-your-instance which describes a method based on the `nextcloud.export` tool. However, that page has not been updated since 2019, and on the home page of the wiki, there is another page referenced: https://github.com/nextcloud-snap/nextcloud-snap/wiki/Backup-and-Restore which has been updated less than 3 months ago and describes a process based on `snap save nextcloud`.

Which method should be used? Are they achieving the same goal? Can one of the two pages be dropped?

Thank you

**Comment by Flaburgan** [comment]
Alright. But I guess you should add those information to the wiki? Thanks anyway.

**Comment by scubamuc** [comment]
I'll go ahead and close this then?...
