### ISSUE TITLE
migrate from snap to AIO - add `pdo_pgsql` PHP extension.

### ISSUE THREAD

**Issue by Bobmorton-TX** [nextcloud-snap/nextcloud-snap#2555]
#### Describe the bug
I need to use Nextcloud Office, which is not supported and does not work anymore on the snap install. 
Therefore I like to migrate my whole install to Nextcloud AIO. In the documentation of AIO its stated by @szaimen that the `pdo_pgsql` PHP extension needs to be added to provide a pathway for migration. (https://github.com/nextcloud/all-in-one/commit/c54395aa4c695fb53e6110328ede473c13693de2)

feature request :)

**Comment by szaimen** [comment]
No, it allows to convert the database to postgresql which is required for migrating files and database to AIO. See https://github.com/nextcloud/all-in-one/blob/main/migration.md#migrate-the-files-and-the-database

**Comment by Pilzinsel64** [comment]
Ah, I see. Interesting... So it only is required for migrating the existing mysql db to psql for AIO before the export.

Hm, basically this allow users to use PostgressSQL for their snap installation whenever they want. Not sure if this should be allowed. @kyrofa what do you think about? 🤔

**Comment by kyrofa** [comment]
I recommend not doing this. This is bloat that most snap users will never need, and as @Pilzinsel64 noted, it also provides an extra footgun for our users: the belief that postgresql is supported. In general, we have tried to avoid adding software to the snap to support third-party applications.

**Comment by Pilzinsel64** [comment]
I agree and will close the PR then.

@Bobmorton-TX you can switch to the channel `latest/beta/pr-2557` and try if you can change the database type here (if you are on nc27 and if you are on a x64 system).
Not sure how long that channel will be available, it is temporary.

For everyone else, I am sure, there is another way to convert the db between export and import. :)

**Comment by shaib** [comment]
For anybody who finds themselves here looking for a way to do this, it was generally described in [this comment](https://github.com/nextcloud-snap/nextcloud-snap/issues/2369#issuecomment-1503042360).

**Comment by scubamuc** [comment]
@Bobmorton-TX, did you see this in the Nextcloud snap Wiki? [CODE & Nextcloud Office configuration](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-CODE-and-Nextcloud-office-for-Nextcloud-snap)

**Comment by szaimen** [comment]
Hi, just to mention it, we just improved the migration.md docs in the AIO repo to document a way how to migrate from snap to AIO with a temporary docker install in between: https://github.com/nextcloud/all-in-one/pull/8003/changes

**Comment by pachulo** [comment]
> Hi, just to mention it, we just improved the migration.md docs in the AIO repo to document a way how to migrate from snap to AIO with a temporary docker install in between: https://github.com/nextcloud/all-in-one/pull/8003/changes

Thanks, that's appreciated!

**Comment by christianlupus** [comment]
Worth mentioning in the wiki?

**Comment by scubamuc** [comment]
> Worth mentioning in the wiki?

nope... worth mentioning in  AIO wiki yes ✔️ anyone wanting to migrate to AIO will check there first.
