### ISSUE TITLE
Problem updating from 25.0.5snap2 to newer versions

### ISSUE THREAD

**Issue by prince2023-10** [nextcloud-snap/nextcloud-snap#2561]
I followed the Thread [https://github.com/nextcloud-snap/nextcloud-snap/issues/2405], because it seemed I have the same problem. The solution should be:

`sudo snap refresh nextcloud --channel=25/stable`
Then `sudo snap refresh nextcloud --channel=26/stable`
Then `sudo snap refresh nextcloud --channel=latest/stable`

Unfortunately this does not work for me. After the first command, snap installs the snap nextcloud 25.0.11snap1, and this version does not work. The desktop client says „connection refused“. Reverting to 25.0.5snap2 works.

`snap list` says: 
Name       Version        Revision  Tracking       Herausgeber  Hinweise 
core18     20230703       2795      latest/stable  canonical✓   base 
core20     20230801       2018      latest/stable  canonical✓   base 
lxd        4.0.9-a29c6f1  24064     4.0/stable/…   canonical✓   - 
nextcloud  25.0.5snap2    34377     25/stable      nextcloud✓   - 
snapd      2.60.3         20101     latest/stable  canonical✓   snapd

So … you need more information, I assume. What do you need exactly?

Please help!

**Comment by prince2023-10** [comment]
This is longer than I could copy from the terminal, so I made an attachment (about 2600 lines ...) Sorry for that.

[output.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/12821135/output.txt)

**Comment by scubamuc** [comment]
@kyrofa, the "connection refused" exception comes from `swiftmailer` app:

```
{"reqId":"G4mrVgryPjP4IXNGk5UO","level":3,"time":"2023-10-05T16:40:28+00:00","remoteAddr":"","user":"--","app":"notifications","method":"","url":"--","message":"Connection could not be established with host 127.0.0.1 :stream_socket_client(): Unable to connect to 127.0.0.1:25 (Connection refused)","userAgent":"--","version":"25.0.5.1","exception":{"Exception":"Swift_TransportException","Message":"Connection could not be established with host 127.0.0.1 :stream_socket_client(): Unable to connect to 127.0.0.1:25 (Connection refused)","Code":0,"Trace":[{"function":"{closure}","class":"Swift_Transport_StreamBuffer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/snap/nextcloud/34377/htdocs/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php","line":264,"function":"stream_socket_client"},{"file":"/snap/nextcloud/34377/htdocs/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php","line":58,"function":"establishSocketConnection","class":"Swift_Transport_StreamBuffer","type":"->"},{"file":"/snap/nextcloud/34377/htdocs/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php","line":143,"function":"initialize","class":"Swift_Transport_StreamBuffer","type":"->"},{"file":"/snap/nextcloud/34377/htdocs/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php","line":65,"function":"start","class":"Swift_Transport_AbstractSmtpTransport","type":"->"},{"file":"/snap/nextcloud/34377/htdocs/lib/private/Mail/Mailer.php","line":191,"function":"send","class":"Swift_Mailer","type":"->"},{"file":"/snap/nextcloud/34377/htdocs/apps/notifications/lib/MailNotifications.php","line":217,"function":"send","class":"OC\\Mail\\Mailer","type":"->"},{"file":"/snap/nextcloud/34377/htdocs/apps/notifications/lib/MailNotifications.php","line":168,"function":"sendEmailToUser","class":"OCA\\Notifications\\MailNotifications","type":"->"},{"file":"/snap/nextcloud/34377/htdocs/apps/notifications/lib/BackgroundJob/SendNotificationMails.php","line":49,"function":"sendEmails","class":"OCA\\Notifications\\MailNotifications","type":"->"},{"file":"/snap/nextcloud/34377/htdocs/lib/public/BackgroundJob/Job.php","line":78,"function":"run","class":"OCA\\Notifications\\BackgroundJob\\SendNotificationMails","type":"->"},{"file":"/snap/nextcloud/34377/htdocs/lib/public/BackgroundJob/TimedJob.php","line":103,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/snap/nextcloud/34377/htdocs/lib/public/BackgroundJob/TimedJob.php","line":93,"function":"start","class":"OCP\\BackgroundJob\\TimedJob","type":"->"},{"file":"/snap/nextcloud/34377/htdocs/cron.php","line":152,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->"}],"File":"/snap/nextcloud/34377/htdocs/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php","Line":261,"message":"Connection could not be established with host 127.0.0.1 :stream_socket_client(): Unable to connect to 127.0.0.1:25 (Connection refused)","exception":{},"CustomMessage":"Connection could not be established with host 127.0.0.1 :stream_socket_client(): Unable to connect to 127.0.0.1:25 (Connection refused)"}}
```

**Comment by kyrofa** [comment]
Hmm, nothing in here seems super problematic to me. Maybe @scubamuc is right and this is ultimately due to a third-party app, but I suspect the logs you grabbed were far after the failure occurred. Ideally you could capture logs right after the upgrade while the thing was down.

**Comment by scubamuc** [comment]
@prince2023-10, stop the snap, delete the logs, start the snap, start the refresh... see log are smaller :-)

**Comment by prince2023-10** [comment]
OK, not sure what happened. Today, it was running 25.0.11snap1 without problems. Hate when this happens, because there is nothing more to learn about it.

But then
`sudo snap refresh nextcloud --channel=26/stable`
leads to the „connection refused“ issue.

This is what I did then:

```
sudo snap revert nextcloud
snap list
```

```
Name       Version        Revision  Tracking       Herausgeber  Hinweise
core18     20230703       2795      latest/stable  canonical✓   base
core20     20230801       2018      latest/stable  canonical✓   base
lxd        4.0.9-a29c6f1  24064     4.0/stable/…   canonical✓   -
nextcloud  25.0.11snap1   37839     26/stable      nextcloud✓   -
snapd      2.60.3         20101     latest/stable  canonical✓   snapd
```

This is a working system (don’t know how and why …). Then:

`sudo snap stop nextcloud`

deleted the logs

```
sudo snap start nextcloud
sudo snap refresh nextcloud
```

Connection refused error

Ran the script. I took very long. Send a strg + c then. See the [output.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/12838038/output.txt)

Thank you very much for helping me.

**Comment by kyrofa** [comment]
This doesn't look great:

> ```
> 2023-10-07T14:30:09.860850Z 0 [Warning] [MY-011037] [Server] The CYCLE timer is not available. WAIT events in the performance_schema will not be timed.
> 2023-10-07T14:30:09.964881Z 0 [System] [MY-010116] [Server] /snap/nextcloud/37836/bin/mysqld (mysqld 8.0.34) starting as process 9112
> 2023-10-07T14:30:10.174685Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
> 2023-10-07T14:30:11.324366Z 1 [ERROR] [MY-012531] [InnoDB] No valid checkpoint found (corrupted redo log). You can try --innodb-force-recovery=6 as a last resort.
> 2023-10-07T14:30:11.324834Z 1 [ERROR] [MY-012930] [InnoDB] Plugin initialization aborted with error Generic error.
> 2023-10-07T14:30:11.328471Z 1 [ERROR] [MY-010334] [Server] Failed to initialize DD Storage Engine
> 2023-10-07T14:30:11.329623Z 0 [ERROR] [MY-010020] [Server] Data Dictionary initialization failed.
> 2023-10-07T14:30:11.329870Z 0 [ERROR] [MY-010119] [Server] Aborting
> 2023-10-07T14:30:11.334162Z 0 [System] [MY-010910] [Server] /snap/nextcloud/37836/bin/mysqld: Shutdown complete (mysqld 8.0.34)  Source distribution.
>```

**Comment by prince2023-10** [comment]
Thank you @kyrofa! What can I do next?

**Comment by prince2023-10** [comment]
For me it is not "completed". Still running the machine, but cannot upgrade.

**Comment by prince2023-10** [comment]
It is fascinating but hard to understand. In the last days, it seems to have upgraded:

```
Name       Version        Revision  Tracking       Herausgeber  Hinweise
core18     20230901       2799      latest/stable  canonical✓   base
core20     20230801       2018      latest/stable  canonical✓   base
lxd        4.0.9-a29c6f1  24064     4.0/stable/…   canonical✓   -
nextcloud  26.0.8snap1    38518     26/stable      nextcloud✓   -
snapd      2.60.4         20301     latest/stable  canonical✓   snapd
```

And it works. How to get to latest/stable now? When I try to upgrade, it does not work.

**Comment by pachulo** [comment]
> When I try to upgrade, it does not work.

How does it not work? Do you see any error message?

**Comment by prince2023-10** [comment]
Recently it made an upgrade automatically

```
Name       Version        Revision  Tracking       Herausgeber  Hinweise
core18     20231027       2807      latest/stable  canonical✓   base
core20     20231123       2106      latest/stable  canonical✓   base
lxd        4.0.9-a29c6f1  24064     4.0/stable/…   canonical✓   -
nextcloud  26.0.9snap1    39236     26/stable      nextcloud✓   -
snapd      2.60.4         20301     latest/stable  canonical✓   snapd
```

Works :) An upgrade made manually to latest/stable does not. Any ideas?

**Comment by scubamuc** [comment]
@prince2023-10 so I've taken the time to study your logs and am seeing a 3rd party app that may be the cause of your update failure... before running the upgrade process de-activate and remove `ransomware_protection`

> Okt 07 16:09:27 ubuntu nextcloud.apache[16244]: Nextcloud or one of the apps require upgrade - only a limited number of commands are available
Okt 07 16:09:27 ubuntu nextcloud.apache[16244]: You may use your browser or the occ upgrade command to do the upgrade
Okt 07 16:09:27 ubuntu nextcloud.apache[16244]: Setting log level to debug
Okt 07 16:09:27 ubuntu nextcloud.apache[16244]: Turned on maintenance mode
Okt 07 16:09:34 ubuntu nextcloud.apache[16244]: Updating database schema
Okt 07 16:10:41 ubuntu nextcloud.apache[16244]: Updated database
Okt 07 16:10:41 ubuntu nextcloud.apache[16244]: Disabled incompatible app: ransomware_protection

If this doesn't work, try disabling and removing **all** 3rd party apps before upgrading.

**Comment by prince2023-10** [comment]
Thank you very much @scubamuc for reading the logs. Indeed, there was Collaborative Office with an issue. I removed it, removed ransomware_protection, too, but the upgrade fails again. So ... I'd like to disable *all* 3rd party apps. How can I find out, which of the installed are 3rd party apps? Or can I remove all listed unter "Active Apps"?

**Comment by scubamuc** [comment]
@prince2023-10, here's the list of apps from my fresh install test instance:

```
Enabled:
  - activity: 2.19.0
  - announcementcenter: 6.7.0
  - bruteforcesettings: 2.7.0
  - calendar: 4.6.0
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.5.0
  - contactsinteraction: 1.8.0
  - dashboard: 7.7.0
  - dav: 1.27.0
  - external: 5.2.1
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_external: 1.19.0
  - files_fulltextsearch: 27.0.1
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - fulltextsearch: 27.0.3
  - groupfolders: 15.3.2
  - guests: 2.5.1
  - impersonate: 1.14.0
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - mail: 3.5.0
  - nextcloud_announcements: 1.16.0
  - notes: 4.9.1
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - photos: 2.3.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - quota_warning: 1.18.0
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - richdocuments: 8.2.3
  - richdocumentscode: 23.5.604
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - spreed: 17.1.4
  - support: 1.10.0
  - survey_client: 1.15.0
  - suspicious_login: 5.0.0
  - systemtags: 1.17.0
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
Disabled:
  - admin_audit: 1.17.0
  - encryption: 2.15.0
  - twofactor_totp: 9.0.0
  - user_ldap: 1.17.0

```
note: this is my nextcloud snap testing instance... you could compare with this list of working apps. do compare version numbers.

**Comment by prince2023-10** [comment]
Thank you again! I have less apps and the version numbers are lower. When I remove ransomware_protection, the line does not show up again in the output.

Unfortunately, this keeps showing:

`Nextcloud or one of the apps require upgrade - only a limited number of commands are available`

But nothing further.

In the admin account is no notification for an upgrade. The only thing I see is in the section "version":

`It seems like you are running a 32-bit PHP version. Nextcloud needs 64-bit to run well. Please upgrade your OS and PHP to 64-bit! For further details read [the documentation page ↗](https://docs.nextcloud.com/server/26/go.php?to=admin-system-requirements) about this.`

But it is the snap version. Could this be the problem? I am puzzled.

**Comment by scubamuc** [comment]
@prince2023-10, what hardware are you running the snap on?

**Comment by prince2023-10** [comment]
`sudo lshw -C system`

says
```
ubuntu                      
    description: ARMv7 Processor rev 5 (v7l)
    product: Raspberry Pi 2 Model B Rev 1.1
    serial: 0000000052df2375
    width: 32 bits
    capabilities: smp
```

Let me guess ... it is too old?

**Comment by scubamuc** [comment]
@prince2023-10, 

Raspi2b is a sturdy ol' board, a bit low on memory and performance but it'll probably outrun most modern systems. The caveat is the SD card which has limited read/write cycles, but obviously your system is chugging along.

The message you're getting is merely a suggestion and not the cause for your issue. 

> It seems like you are running a 32-bit PHP version. Nextcloud needs 64-bit to run well. Please upgrade your OS and PHP to 64-bit! For further details read [the documentation page ↗](https://docs.nextcloud.com/server/26/go.php?to=admin-system-requirements) about this.

Who knows, maybe Santa puts some spanking new hardware in your stocking :+1:  you'd be doing yourself a favour by making a backup of your snap while its still running so you can [migrate](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Backup-and-Restore).

I'm at a loss for any ideas why you're stuck on 25.0.5snap2, sorry...

**Comment by kyrofa** [comment]
I strongly suspect that this is RAM-related. I suspect that the mysql upgrades require a fair bit of RAM, and if it doesn't get it, it decides to corrupt your database instead. Then you revert, and one of those channels receives an update and it automatically tries to update again, and happens to succeed because your RAM utilization was low enough the mysql migration was able to happen.

**Comment by prince2023-10** [comment]
Thank you @scubamuc and @kyrofa for your ideas. Had to look up "chugging along", but ... this picture fits :) So let's hope for Santa, and then I can change the Rasbpi. The old one could do other things then. Thank you again!
