### ISSUE TITLE
Nextcloud Snap offline install/update broken

### ISSUE THREAD

**Issue by MookiBar** [nextcloud-snap/nextcloud-snap#2562]
#### Describe the bug
Pre-refresh hooks unnecessarily fail install during static online check.
Problem has been detailed here: https://stackoverflow.com/questions/77128973/offline-update-of-nextcloud-snap-fails-during-online-hooks

#### To Reproduce
While WAN/internet is inaccessible, run:  snap install ./nextcloud*.snap

#### Expected behavior
Attempting to install should either *not* require a successful connection to apps.nextcloud.com or at least check one of the config options such as appstoreurl or appstoreenabled.

#### OS/snapd/snap version
OS: ubuntu 22.04
Nextcloud  Snap versions: 25, 26, 27 stable

#### Logs
Output of snap install:
"Unable to refresh: apps.nextcloud.com seems to be down, please try again later"

**Comment by kyrofa** [comment]
> Attempting to install should either not require a successful connection to apps.nextcloud.com [...]

I'm afraid that check was put in place for good reason; removing it isn't really an option.

> [...] or at least check one of the config options such as appstoreurl or appstoreenabled.

Not a bad idea, but it will need some investigation. The `appstoreenabled` docs say:

> When enabled, admins may install apps from the Nextcloud app store.

Does that disable updates for already-installed apps? Or just prevent the installations of new ones?

**Comment by MookiBar** [comment]
> I'm afraid that check was put in place for good reason; removing it isn't really an option.
What is that reason? I have manually updated Nextcloud from a tarball and manually updated Nextcloud from a snap. Previously, it was never an issue to require the *base program* to have extra apps updated before installing itself....

> 
> > [...] or at least check one of the config options such as appstoreurl or appstoreenabled.

> > When enabled, admins may install apps from the Nextcloud app store.
The intention was, when disabled, don't allow installation from the app store. Hence, don't reach out to the app store...

As mentioned in my SO post, the documentation for base Nextcloud does not hold the main app hostage to its own apps, much less to external apps, so I'm confused at why here....

**Comment by kyrofa** [comment]
> Granted, anything in extra-apps had to be replaced with versions that matched compatibility with the new NC version. But those are extra, and a server maintainer can easily run occ app:update after the base program is installed/updated.

You hit on exactly the issue. Remember that snaps update automatically. We can't require things of the server maintainer, because the update often happens outside of their oversight. Requiring manual interaction on an automatic update is a non-starter.

> The intention was, when disabled, don't allow installation from the app store. Hence, don't reach out to the app store...

Can you provide a reference for that assertion so we can be sure?

**Comment by MookiBar** [comment]
Here is the documentation:
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#appstoreenabled
Enabled means can install apps from app store. Implication: disabled means cannot install apps from app store.

Here is confirmation that attempts to reach the app store should be disabled when appstoreenabled is false:
https://github.com/nextcloud/server/issues/4056


I see you skipped over the part where I put out a reminder that extra-apps are..."extra", unlike the core program, which is now broken for users such as myself. Saying that leaving the automation of extra-apps updates "isn't really an option" but implying that this broken state of the core app (for the use-cases mentioned) is valid, we may need to address that.
You also, seriously, need to detach the notion that extra apps need to be fully integrated into the install of the core program. You *do not* need to have the latest extra apps installed at the time of Nextcloud install! They can be added after the fact. Admins can add from the app store, from command line, manually copy the files, etc etc. If you want to pretend that people won't have to still do some maintenance on their apps after install, that is false. Breaking core functionality to double-down on that assertion...is just bad. 
I "hit the nail on the head"? When i was telling you that

**Comment by MookiBar** [comment]
Honestly, the way you have conducted these conversations since the SO post have not been in good faith. Starting with how this isn't a "use case" for snaps or even nextcloud, you have been putting up the wall, claiming the normal scenario I present is outside the bounds of normal use or reasonable expectation. If you want someone to actually assist you, maybe start by admitting they are a real, valid user with a real valid use-case. Otherwise, if you haven't been reading my post, I'm already accounting for a "lost cause" here...

**Comment by kyrofa** [comment]
I'm not going to argue. Let's just agree to go our separate ways.
