### ISSUE TITLE
Update PHP to 8.2

### ISSUE THREAD

**Issue by ghost** [nextcloud-snap/nextcloud-snap#2564]
#### What dependency/component is out of date?
This is not personally required, or related to a particular security issue.

I noticed that the recommended version by the Nextcloud docs was [8.2](https://docs.nextcloud.com/server/stable/admin_manual/installation/system_requirements.html) whilst doing some maintenance, although 8.1 is still acceptable.

**Comment by stondino00** [comment]
This is probably a good idea.  I use the passwords app and it appears they are ending support for php 8.1.

**Comment by kyrofa** [comment]
Yeah I like to stay one release behind PHP. Given that they're on 8.3 now, I'm on board with 8.2.
