### ISSUE TITLE
Need instructions for migration to another system

### ISSUE THREAD

**Issue by RealTehreal** [nextcloud-snap/nextcloud-snap#2570]
Hey there,

first: thank you very much for your hard work on Nextcloud Snap. I'm using it for several months now. It's easy to set up and easy to maintain!

Currently, the Snap runs on a barebone machine. At first, it was just used for testing purposes, but as one or another may know from experience: it worked, it was used, it was used on a regular basis, now it's productive ;-)

I would like to migrate from the barebone machine to a VM. I know about the export / import functionality and the possibility to save and restore entire Snaps. Now I would like to know, what is the easiest and most fail proof way to go? Is it enough to just save the snap on the barebone and restore on the VM? Will it just continue running like before? Will it save everything like configs, apps, db and certificates? Will it be a real clone of the original Snap? Or will I have to install anything on the VM beforehand?

The OS on both machines is the same: Ubuntu Server 22.04 LTS. So there shouldn't be incompatibilities.

I'm asking because I would like to reduce down-time to an absolute minimum. I was using nextcloud-pi with docker before - it was a nightmare. This time, I would like to get this done as smooth as possible without recreating the entire Nextcloud instance.

Thank you very much in advance for some advice on migration.

Greets

**Comment by scubamuc** [comment]
the option to [migrate a snap](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Backup-and-Restore) to a new machine is easy quick and one of the selling points for using snap.
[Snap snapshot](https://snapcraft.io/docs/snapshots) is the way to go.

**Comment by RealTehreal** [comment]
> the option to [migrate a snap](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Backup-and-Restore) to a new machine is easy quick and one of the selling points for using snap. [snap snapshot](https://snapcraft.io/docs/snapshots) is the way to go. snap snapshot may be scripted and automated, see [here](https://github.com/scubamuc/scubamuc.github.io/blob/scubamuc/wiki-md/NEXTCLOUD.snap--backup_snap-snapshot.md) and [here](https://github.com/nextcloud-snap/nextcloud-snap/issues/2453#issuecomment-1684987142)

Thank you very much for your reply. I did the migration as mentioned, and it worked without a hitch. Just a few minutes of downtime. Thanks again!
