### ISSUE TITLE
Uploads over ~8KB fail over WebDav

### ISSUE THREAD

**Issue by adil192** [nextcloud-snap/nextcloud-snap#2583]
#### Describe the bug
Files around 6-10KB and higher don't upload successfully.
If the file doesn't exist on the server already, nothing happens.
If the file already exists on the server, it's replaced with a 0 byte file.

#### To Reproduce
This error doesn't occur with every WebDav client. It's occurring with the https://github.com/nextcloud/neon Flutter package, but not with any other server.

1. Upload 20KB file via webdav.put
2. See that either the file doesn't exist on the server, or its size is 0 bytes.

#### Expected behavior
Successful uploads via webdav.put

#### Other information
Please see the previous discussion here: https://github.com/adil192/saber/issues/945.

#### OS/snapd/snap version
```console
root@nc:~# neofetch
            .-/+oossssoo+/-.               root@nc.saber.adil.hanney.org 
        `:+ssssssssssssssssss+:`           ----------------------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 22.04.3 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: KVM/QEMU (Standard PC (i440FX + PIIX, 1996) pc-i440fx-2.7) 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.15.0-87-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 16 hours, 34 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 683 (dpkg), 6 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.1.16 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Terminal: node 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   CPU: Intel Xeon (Skylake, IBRS) (2) @ 2.099GHz 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   GPU: 00:02.0 Red Hat, Inc. QXL paravirtual graphic card 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Memory: 889MiB / 3876MiB 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/                            
  +sssssssssdmydMMMMMMMMddddyssssssss+                             
   /ssssssssssshdmNNNNmyNMMMMhssssss/
    .ossssssssssssssssssdMMMNysssso.
      -+sssssssssssssssssyyyssss+-
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.

root@nc:~# snap list nextcloud
Name       Version      Rev    Tracking   Publisher   Notes
nextcloud  27.1.1snap1  37720  27/stable  nextcloud✓  -
root@nc:~# snap version
snap    2.60.4
snapd   2.60.4
series  16
ubuntu  22.04
kernel  5.15.0-87-generic
root@nc:~# 
```

#### Logs
Comment is too long, see this gist: https://gist.github.com/adil192/ba7223cfdfe851416154011203d5f461

**Comment by adil192** [comment]
[debugscript.output.md](https://github.com/nextcloud-snap/nextcloud-snap/files/13069882/debugscript.output.md)

**Comment by kyrofa** [comment]
Sounds like maybe this should be logged against that flutter package?

**Comment by adil192** [comment]
See @provokateurin's (who made nextcloud/neon) comments in https://github.com/saber-notes/saber/issues/945. Their testing as well as my testing shows that it works fine on any other server we've tried.
Honestly, I have no idea what's causing it. At first I thought it was because my server didn't have enough space, so I bought a new server and `nextcloud.export` and `nextcloud.import`'ed it across, but it still occurs on the new server.
Maybe it's an issue with chunking or something similar due to it being an issue with larger files, but I'm just spitballing.
Are you able to see anything glaring in the logs?

**Comment by kyrofa** [comment]
Do you have a reverse-proxy in front of the snap? I do see a number of services being oom killed, which indicates that you could be running low on RAM, but I would expect an error status to be returned in that case.

**Comment by adil192** [comment]
No this is basically just a fresh Ubuntu install with the snap installed.

![Only 1GB out of 4GB of RAM is being used](https://github.com/nextcloud-snap/nextcloud-snap/assets/21128619/b63562bb-093c-488f-8fe5-54c3eabd67b7)

Maybe it could have something to do with this notification about the size of my instance.

![This is the unsupported community build of Nextcloud. Given the size of this instance, performance, reliability and scalability cannot be guaranteed. Push notifications are limited to avoid overloading our free service. Learn more about the benefits of Nextcloud Enterprise at https://nextcloud.com/enterprise.](https://github.com/nextcloud-snap/nextcloud-snap/assets/21128619/0ff4359b-9fe2-4419-bd78-d1c3ac9206c2)
