### ISSUE TITLE
Question: how does one  terminate TLS only at reverse-proxy leaving downstream connection unencrypted

### ISSUE THREAD

**Issue by notjames** [nextcloud-snap/nextcloud-snap#2584]
What I'm trying to accomplish:

setting up an on-prem nextcloud via snap on a home server situated behind a home internet connection

My setup is thus:

ISP/CPE (filtered with port-forwarding enabled) => server => docker container nginx-reverse proxy => nextcloud

TLS communication desired:

client over TLS to CPE => CPE forwards TLS to server => server forwards TLS to container (nginx reverse proxy) => nginx proxy-passes unencrypted traffic to nextcloud

Problem:

I am fairly certain I've set up the reverse proxy correctly. Test connections succeed all the way until nextcloud returns a response. The problem, as I see it, is 

`sudo nextcloud.occ config:system:set overwritehost --value="myexternaldomain:non-std-tls-port"` 

...fails to allow me to set the schema to `https`. My guess is that the scheme is set to automatically set based on the fact that `https` is enabled or not. What I need to do be able to do, however, is leave `https` disabled and force the scheme to `https` in the `overwritehost` redirect.

Is that something I can do? If not, is that something we can allow to be done?

**Comment by notjames** [comment]
> What I'm trying to accomplish:
> 
> setting up an on-prem nextcloud via snap on a home server situated behind a home internet connection
> 
> My setup is thus:
> 
> ISP/CPE (filtered with port-forwarding enabled) => server => docker container nginx-reverse proxy => nextcloud
> 
> TLS communication desired:
> 
> client over TLS to CPE => CPE forwards TLS to server => server forwards TLS to container (nginx reverse proxy) => nginx proxy-passes unencrypted traffic to nextcloud
> 
> Problem:
> 
> I am fairly certain I've set up the reverse proxy correctly. Test connections succeed all the way until nextcloud returns a response. The problem, as I see it, is
> 
> `sudo nextcloud.occ config:system:set overwritehost --value="myexternaldomain:non-std-tls-port"`
> 
> ...fails to allow me to set the schema to `https`. My guess is that the scheme is set to automatically set based on the fact that `https` is enabled or not. What I need to do be able to do, however, is leave `https` disabled and force the scheme to `https` in the `overwritehost` redirect.
> 
> Is that something I can do? If not, is that something we can allow to be done?

I think my answer is here:
https://docs.nextcloud.com/server/19/admin_manual/configuration_server/config_sample_php_parameters.html?highlight=overwrite%20cli%20url#proxy-configurations

**Comment by scubamuc** [comment]
your setup is listed in Wiki [here](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Hosts-and-FQDN-for-Nextcloud-snap#fqdn-for-nextcloud-snap-instance-vm-or-container-behind-reverse-proxy-with-termination). See [configuration ](https://github.com/nextcloud-snap/nextcloud-snap/wiki/configure-Nextcloud-snap) for more information.

`overwritehost` setting in `php.config` is not required and will be managed by reverse proxy. be aware of configuration for [CODE](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-CODE-and-Nextcloud-office-for-Nextcloud-snap).
