### ISSUE TITLE
Stuck on 26/edge

### ISSUE THREAD

**Issue by ItMeCorban** [nextcloud-snap/nextcloud-snap#2587]
#### Describe the bug
I updated to the edge build a while ago to try it out while waiting for the stable release, however I'm now stuck on 26/edge. If I try to move to stable or beta, I get `Downgrading is not supported and is likely to cause unpredictable issues (from 26.0.8.0 to 26.0.7.0) ` in the browser.

So I tried upgrading to 27, but whether I use 27/stable, beta or edge, I get `error: cannot perform the following tasks:
Run post-refresh hook of "nextcloud" snap if present (run hook "post-refresh": Nextcloud doesn't support skipping major versions, you must upgrade to Nextcloud 26 first. Try 'sudo snap refresh nextcloud --channel=26')`

#### To Reproduce
1. Update to edge build of 26
2. Try to update to 27

#### Expected behavior
Surely I should just be able to move to version 27, since I'm already on 26.

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:
```
 snap list nextcloud
Name       Version        Rev    Tracking  Publisher   Notes
nextcloud  26-2023-10-19  38345  26/edge   nextcloud✓  -

```
```
 snap version
snap    2.60.4
snapd   2.60.4
series  16
ubuntu  22.04
kernel  5.15.0-84-generic
```

#### Logs
[nc-logs.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/13165474/nc-logs.txt)

**Comment by ItMeCorban** [comment]
> * The reason why you can't refresh to 26/stable is because 26/edge has daily builds and is newer then 26/stable the most of the time (blocked by Nextcloud itself). To refresh to 26/stable you need to stop automatic refreshs and then refresh manually when 26/stable is newer then 26/edge. See below.
> 
>     * The reason why you can't refresh to 27 is because you first need to update to the last stable minor version of the 26 branche before you can update to another major version. While you stuck in beta/daily you simply can't. That's also a limitation of Nextcloud itself.
> 
> 
> #### What you need to do now:
> 
>     1. Execute this command now to stop auto refresh: `sudo snap refresh --hold nextcloud`
> 
>     2. And then wait until the next release become stable (probably 2 to 4 weeks) and don't refresh in this time.
> 
>     3. Execute this command to refresh to stable 26: `sudo snap refresh nextcloud --channel=26/stable`
> 
>     4. Execute this command to enable auto refresh: `sudo snap refresh --unhold nextcloud`
> 
>     5. Execute this command to refresh to stable 27: `sudo snap refresh nextcloud --channel=27/stable`
> 
> 
> Generally, if I want to switch to the new version using the /edge channel, I do it once on release day and then disable automatic refreshs and only refresh on one day after a release day manually. If I then want to switch to /beta or /stable I just need to wait for the next release.

Thanks for the thorough response, much appreciated, I've held refreshes and will give it a few weeks and do the updates manually, I was getting ready to do a full reinstall so that's a relief.

Thanks again!

**Comment by corban-intk** [comment]
So I've come back to try and get this sorted but unfortunately I'm still getting weird update behaviour. According to the messages, I need to upgrade from 26 stable to 26 stable before I can use 26 stable?

```
installed:          26.0.8snap1                  (38511) 288MB held


$  sudo snap refresh --unhold nextcloud
Removed general refresh hold of "nextcloud"

$  sudo snap refresh nextcloud --channel latest/stable
2023-11-13T11:47:37Z INFO Waiting for "snap.nextcloud.redis-server.service" to stop.
2023-11-13T11:47:43Z INFO Waiting for "snap.nextcloud.mysql.service" to stop.
error: cannot perform the following tasks:
- Run post-refresh hook of "nextcloud" snap if present (run hook "post-refresh": Nextcloud doesn't support skipping major versions, you must upgrade to Nextcloud 26 first. Try 'sudo snap refresh nextcloud --channel=26')


$  sudo snap refresh nextcloud --channel=26
nextcloud (26/stable) 26.0.8snap1 from Nextcloud✓ refreshed


$  sudo snap refresh nextcloud --channel=27
2023-11-13T11:56:02Z INFO Waiting for "snap.nextcloud.redis-server.service" to stop.
2023-11-13T11:56:04Z INFO Waiting for "snap.nextcloud.mysql.service" to stop.
error: cannot perform the following tasks:
- Run post-refresh hook of "nextcloud" snap if present (run hook "post-refresh": Nextcloud doesn't support skipping major versions, you must upgrade to Nextcloud 26 first. Try 'sudo snap refresh nextcloud --channel=26')


$  sudo snap refresh nextcloud --channel=26
nextcloud (26/stable) 26.0.8snap1 from Nextcloud✓ refreshed
```

**Comment by ItMeCorban** [comment]
So I've come back to try and get this sorted but unfortunately I'm still getting weird update behaviour. According to the messages, I need to upgrade from 26 stable to 26 stable before I can use 26 stable?

```
installed:          26.0.8snap1                  (38511) 288MB held


$  sudo snap refresh --unhold nextcloud
Removed general refresh hold of "nextcloud"

$  sudo snap refresh nextcloud --channel latest/stable
2023-11-13T11:47:37Z INFO Waiting for "snap.nextcloud.redis-server.service" to stop.
2023-11-13T11:47:43Z INFO Waiting for "snap.nextcloud.mysql.service" to stop.
error: cannot perform the following tasks:
- Run post-refresh hook of "nextcloud" snap if present (run hook "post-refresh": Nextcloud doesn't support skipping major versions, you must upgrade to Nextcloud 26 first. Try 'sudo snap refresh nextcloud --channel=26')


$  sudo snap refresh nextcloud --channel=26
nextcloud (26/stable) 26.0.8snap1 from Nextcloud✓ refreshed


$  sudo snap refresh nextcloud --channel=27
2023-11-13T11:56:02Z INFO Waiting for "snap.nextcloud.redis-server.service" to stop.
2023-11-13T11:56:04Z INFO Waiting for "snap.nextcloud.mysql.service" to stop.
error: cannot perform the following tasks:
- Run post-refresh hook of "nextcloud" snap if present (run hook "post-refresh": Nextcloud doesn't support skipping major versions, you must upgrade to Nextcloud 26 first. Try 'sudo snap refresh nextcloud --channel=26')


$  sudo snap refresh nextcloud --channel=26
nextcloud (26/stable) 26.0.8snap1 from Nextcloud✓ refreshed
```

**Comment by Pilzinsel64** [comment]
Hm, this looks against everything I know regarding the upgrade mechanism of Nextcloud. 🤔 
Normally you should be able to update from 26.0.8 to 27.1.x without any problems.

But maybe the update script or the Nextcloud updater itself wants you to update from 26.0.8 to 27.0.x before updating to 27.1.x. 🤔

@pachulo @kyrofa Any idea if this script here can be the cause?
https://github.com/nextcloud-snap/nextcloud-snap/blob/55795679727f1737b9e47f5770d327e8d49043de/src/common/utilities/common-utilities#L187-L192

**Comment by scubamuc** [comment]
Hey @ItMeCorban, so I've taken the time to study your very extensive logs and especially your **long list of 3rd party apps**...

you're using apps like `side menu`, `memories`, `rawphotos`, `drawio`, `CODE & Nextcloud Office` together with `ONLYOFFICE`... the list goes on. some 3rd party apps don't work with newer Nextcloud versions any more, some have been discontinued and some of your apps are redundant.

so  I'd like to suggest disabling/removing 3rd party apps, updating the snap and then carefully re-enabling (only compatible) 3rd party apps. some of yours are incompatible and will simply not work with the snap see [here](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-nextcloud-snap-is-not-working-because-of-third-party-app-incompatibility-what-can-i-do).

**Comment by scubamuc** [comment]
@Pilzinsel64

> Hm, this looks against everything I know regarding the upgrade mechanism of Nextcloud. 🤔
Normally you should be able to update from 26.0.8 to 27.1.x without any problems.

see the list of 3rd party apps installed on ItMeCorban's system.... there is no way the update mechanism could cope with that

**Comment by ItMeCorban** [comment]
I may be mistaken here but I feel like installing supported apps on a platform designed around them probably shouldn't completely break the update process if you try to use them - that and the fact that this has worked fine previously but I'll give it a go just in case
