### ISSUE TITLE
mysql locking system

### ISSUE THREAD

**Issue by JR1994** [nextcloud-snap/nextcloud-snap#259]
I have nextcloud on my RPI3 using Ubuntu Snappy. Every time I load a picture from the browser or load an image from my iPhone the Pi freezes. Everything locks up. I use a serial console to see what was happening and it appears to me a memory issue with mysql. I am posting the logs **[here](https://pastebin.com/HZKCd6G5)**. Has anyone seen this before?

**Comment by kyrofa** [comment]
Yeah, the rpi3 is a bit on the low side as far as RAM goes. When that happens, how is your memory split up (e.g. take a look at `top` and sort by memory usage)?

**Comment by JR1994** [comment]
I will thanks. I was a running nextcloud instance using Gentoo on the RPI and never ran across this. I switched to snappy b/c it much easier to  set up.

**Comment by JR1994** [comment]
I was able to capture this before it crashed again

`top - 22:47:44 up 9 min,  1 user,  load average: 1.29, 1.60, 0.87
Tasks: 162 total,   9 running, 153 sleeping,   0 stopped,   0 zombie
%Cpu0  : 80.0 us, 17.7 sy,  0.0 ni,  0.3 id,  0.0 wa,  0.0 hi,  2.0 si,  0.0 st
%Cpu1  : 85.2 us, 14.8 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu2  : 84.2 us, 15.8 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu3  : 84.9 us, 15.1 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :   942124 total,     5016 free,   618460 used,   318648 buff/cache
KiB Swap:        0 total,        0 free,        0 used.   278840 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND     
 1842 root      20   0 1248632 179836  13248 S  12.2 19.1   0:27.46 mysqld      
 5351 root      20   0  119404  74804   9328 R  49.3  7.9   0:08.05 php-fpm     
 5336 root      20   0  119320  74720   9300 R  52.3  7.9   0:09.90 php-fpm     
 5396 root      20   0  119096  73332   8216 R  53.9  7.8   0:02.14 php-fpm     
 5394 root      20   0  119096  73192   8216 R  51.3  7.8   0:02.96 php-fpm     
 5393 root      20   0  119096  73188   8216 R  57.6  7.8   0:03.12 php-fpm     
 5392 root      20   0  119096  73184   8216 R  54.6  7.8   0:03.10 php-fpm     
 5398 root      20   0   69804  23708   8004 R  46.1  2.5   0:01.90 php-fpm     
 1180 root      20   0  871144  14508   8832 S   0.0  1.5   0:02.22 snapd       
 1888 root      20   0   56352  13696  11340 S   0.0  1.5   0:01.67 php-fpm     
 2052 root      20   0  237492   5216   3576 S   0.0  0.6   0:06.08 httpd       
 2049 root      20   0    7612   5020   4120 S   0.0  0.5   0:00.77 httpd       
 2150 root      20   0  237432   5012   3556 S   0.0  0.5   0:10.55 httpd 
      
[  598.390425] Out of memory: Kill process 1842 (mysqld) score 178 or sacrifice child
[  598.398666] Killed process 1842 (mysqld) total-vm:1248632kB, anon-rss:166600kB, file-rss:0kB
[  598.431052] Out of memory: Kill process 1873 (mysqld) score 180 or sacrifice child
[  598.439197] Killed process 1847 (mysqld) total-vm:1248632kB, anon-rss:168088kB, file-rss:0kB
[  640.531334] brcmf_sdio_bus_rxctl: resumed on timeout
[  640.536580] brcmf_link_down: WLC_DISASSOC failed (-52)
[  720.193539] INFO: task redis-server:1613 blocked for more than 120 seconds.
[  720.200835]       Not tainted 4.4.0-1030-raspi2 #37-Ubuntu
[  720.206569] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  720.215207] INFO: task mysqld:1847 blocked for more than 120 seconds.
[  720.221933]       Not tainted 4.4.0-1030-raspi2 #37-Ubuntu
[  720.227661] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  720.236167] INFO: task mysqld:1849 blocked for more than 120 seconds.
[  720.242894]       Not tainted 4.4.0-1030-raspi2 #37-Ubuntu
[  720.248620] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  720.257127] INFO: task mysqld:1850 blocked for more than 120 seconds.
[  720.268635]       Not tainted 4.4.0-1030-raspi2 #37-Ubuntu
[  720.279180] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  720.297361] INFO: task mysqld:1851 blocked for more than 120 seconds.
[  720.308910]       Not tainted 4.4.0-1030-raspi2 #37-Ubuntu
[  720.319397] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  720.337308] INFO: task mysqld:1852 blocked for more than 120 seconds.
[  720.348668]       Not tainted 4.4.0-1030-raspi2 #37-Ubuntu
[  720.358991] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  720.376959] INFO: task mysqld:1856 blocked for more than 120 seconds.
[  720.388437]       Not tainted 4.4.0-1030-raspi2 #37-Ubuntu
[  720.398883] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  720.416860] INFO: task php-fpm:1888 blocked for more than 120 seconds.
[  720.428455]       Not tainted 4.4.0-1030-raspi2 #37-Ubuntu
[  720.438907] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  720.457057] INFO: task httpd:2049 blocked for more than 120 seconds.
[  720.468471]       Not tainted 4.4.0-1030-raspi2 #37-Ubuntu
[  720.478866] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  720.496677] INFO: task httpd:2133 blocked for more than 120 seconds.
[  720.508016]       Not tainted 4.4.0-1030-raspi2 #37-Ubuntu
[  720.518352] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
`

**Comment by kyrofa** [comment]
Huh... it says you're out of memory but I count only about 50% utilization there.

**Comment by JR1994** [comment]
I am willing to test

**Comment by JR1994** [comment]
I tried moving another RPI3 in case it was hardware related. Still crashed.
