### ISSUE TITLE
Change DB data mount path

### ISSUE THREAD

**Issue by mozg31337** [nextcloud-snap/nextcloud-snap#2598]
Hello everyone,

This is more of a documentation request update / feature. Along with the guides on how to change of the data directory path it would be useful to learn how to change the folder path for the database store in the context of nextcloud snap install. I have a separate faster disk mounted on a separate disk that I would like to utilise for mysql db which is installed with the nextcloud snap package.

Thanks

**Comment by kyrofa** [comment]
I'm afraid this isn't supported. When snaps update, they take a snapshot of their data, of which the database is the most important. They do this in case the new revision garbles the database for whatever reason: you can rollback, and be confident that you'll be where you were right before the update. If you take the database outside of the snap's control, it will no longer be able to do that.

**Comment by mozg31337** [comment]
Hi Kyrofa,
I can see that you guys support mounting the data path in /mnt or /media. Can't you do a similar thing for database, to mount its partition to /mnt/database for example? Not sure why this will take the database outside of the snap's control.
