### ISSUE TITLE
Another upgrade problem (related to MySQL?) from 26.0.3snap1 to stable/26

### ISSUE THREAD

**Issue by Jopyth** [nextcloud-snap/nextcloud-snap#2610]
#### Describe the bug

It seems as if some MySQL problem occurs (MySQL will not start, and the website is not reachable) during the upgrade from 26.0.3snap1 to 26.0.8snap1 (MySQL 8.0.33 to 8.0.35). I successfully reverted to 26.0.3snap1. The same problem occured in previous stable versions of 26, but until now I only had the time to fix it by reverting. (The logs below are taken after the revert.)

At first I thought it is the same as the bug reported and fixed [here](https://github.com/nextcloud-snap/nextcloud-snap/issues/2405). But it seems the suggested process of upgrading to the stable version did not help (I am also "stuck" on a different major version compared to the linked issue).

Also I can not make out a real error in the logs, except that the MySQL process is killed. (I have tried properly disabling https, since I am running a reverse proxy before nextcloud).

Any ideas on what could be the problem? (I could try an export/import of the data and newly setup the snap if that is a promising alternative.)

#### OS/snapd/snap version
I am running the snap in a virtual machine (Ubuntu 22) on a Synology NAS.
```
$ snap list nextcloud
Name       Version      Rev    Tracking   Publisher   Notes
nextcloud  26.0.3snap1  35878  26/stable  nextcloud✓  -
$ snap version
snap    2.60.4
snapd   2.60.4
series  16
ubuntu  22.04
kernel  5.15.0-88-generic
```

#### Logs
Due to their size, the logs are here as an attachment: [info.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/13288729/info.txt)

**Comment by scubamuc** [comment]
> Also I can not make out a real error in the logs, except that the MySQL process is killed.

neither can I...

> Nov 07 20:08:22 nextcloud-vm nextcloud.apache[97368]

you're obviously running your cloud on a vm... 

> (I could try an export/import of the data and newly setup the snap if that is a promising alternative.)

so if you tried a fresh install on a new vm and [exporting and importing](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Export-and-Import) like you suggest, it might save you some headache and time

**Comment by scubamuc** [comment]
oh and by the way... your logs are being spammed with the good ol' "set fqdn" message:

>Nov 07 20:08:25 nextcloud-vm nextcloud.apache[97846]: AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message

do consider [setting FQDN](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Hosts-and-FQDN-for-Nextcloud-snap) on your new vm, some folks have mentioned improved site response and less log "spamming" :+1:  and it makes for better reading when scraping logs

**Comment by Jopyth** [comment]
Thank you for the responses.

> you're obviously running your cloud on a vm...

Yes, I mentioned it under OS, maybe that info was hidden too far down.

> so if you tried a fresh install on a new vm and [exporting and importing](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Export-and-Import) like you suggest, it might save you some headache and time

Any recommendation on whether to go to the most recent stable version directly by export/import, or rather try to go to the stable 26 first and then try to upgrade from there?

And thanks very much for the hint with FQDN.

**Comment by scubamuc** [comment]
> Any recommendation on whether to go to the most recent stable version 

yeah, go for latest stable. you should be okay...

**Comment by kyrofa** [comment]
> yeah, go for latest stable. you should be okay...

I only recommend using the included export/import functions with the same revision of the snap, personally. Otherwise you'll run into mysql version changes and whatnot.

**Comment by scubamuc** [comment]
> I only recommend using the included export/import functions with the same revision of the snap, personally. Otherwise you'll run into mysql version changes and whatnot.

I'd agree with @kyrofa if you're planning to export the database too,

>  (I could try an export/import of the data and newly setup the snap if that is a promising alternative.)

If you only export the data though, you should be fine on latest stable .
