### ISSUE TITLE
Unable to enable face recognization app

### ISSUE THREAD

**Issue by achuet** [nextcloud-snap/nextcloud-snap#2611]
Installed pdlib by following this guide
https://github.com/goodspb/pdlib

Still getting the same error
You do not meet the dependencies to install the model 1 (Default)
Summary: The PDlib PHP extension is not loaded
Please read the documentation for this model to continue: https://github.com/matiasdelellis/facerecognition/wiki/Models#model-1

**Comment by pachulo** [comment]
Duplicate https://github.com/nextcloud-snap/nextcloud-snap/issues/1458

**Comment by scubamuc** [comment]
@pachulo added to [FAQ's](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's)
