### ISSUE TITLE
Unable to connect to Nextcloud via HTTTPS

### ISSUE THREAD

**Issue by varriaza** [nextcloud-snap/nextcloud-snap#2612]
#### Describe the bug
I am not able to connect to my nextcloud instance via HTTPS. HTTP connects and works but I'm looking to enable HTTPS.

Error:
Unable to connect
An error occurred during a connection to cloud.my-domain.com.
    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the web.

#### To Reproduce
- New install of nextcloud snap
- Setup Nginx Proxy Manger with cloudflare for SLL (following the guide for nextcloud snap)
- I am also using my-domain.com as an email handle, if that makes a difference. (Eg username@my-domain.com)
- Try to go to https://cloud.my-domain.com and get unable to connect error

#### Expected behavior
I go to HTTPS url and the page loads to login screen.

#### OS/snapd/snap version
snap list nextcloud:
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  27.1.3snap1  38457  latest/stable  nextcloud✓  -

snap version:
snap    2.60.4
snapd   2.60.4
series  16
ubuntu  22.04
kernel  5.15.0-88-generic

#### Logs
Debug script output attached
[debug output.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/13326111/debug.output.txt)

**Comment by kyrofa** [comment]
> Setup Nginx Proxy Manger with cloudflare for SLL (following the guide for nextcloud snap)

So the snap isn't handling SSL for you, nor the fetching/renewal of certs? Then that error is coming from something that is _not_ the snap? If so, I'm not sure how much we can help.

**Comment by varriaza** [comment]
Got it. Do you know if the dual use of the domain as email and website could cause issues? I'm new to SSL stuff so not sure where to look, or what to look for.

**Comment by kyrofa** [comment]
No that shouldn't be a problem at all. You'll find the issue somewhere around the "Nginx Proxy Manger with cloudflare for SLL", whatever that looks like. Make sure your domain is pointing at it. You might consider logging an issue against it. Once you have SSL working there, passing traffic back to the snap should be trivial (since you mention HTTP is working).

**Comment by varriaza** [comment]
I followed this for the NPM setup. 
https://github.com/nextcloud-snap/nextcloud-snap/wiki/NGINX-proxy-manager

I have my domain registered with Cloudflare but am open to switching out NPM since it may not be working. Any recommendations on alternatives?

**Comment by kyrofa** [comment]
Oh, I've never seen that document before. Maybe @scubamuc can help, here.

**Comment by scubamuc** [comment]
> Nginx Proxy Manger with cloudflare for SLL

I haven't seen cloudflare SLL myself either... if you mean [cloudflare SSL](https://www.cloudflare.com/application-services/products/ssl/), then presumably you're expecting cloudflare to handle the certificates? You'll have to contact cloudflare for help with that.

We don't support cloudflare or NPM here, but NPM desperately wants to terminate your connection. Thus you should either use cloudflare's termination **OR** NPM termination **AND** disable certificates in Nextcloud snap. There can only be one!

The example in the wiki assumes that NPM is managing your certificates. There is absolutely no mention of cloudflare.

> I am also using my-domain.com as an email handle, if that makes a difference. (Eg [username@my-domain.com](mailto:username@my-domain.com))

That shouldn't interfere at all and is irrelevant.

> So the snap isn't handling SSL for you, nor the fetching/renewal of certs? Then that error is coming from something that is not the snap? If so, I'm not sure how much we can help.

I'd agree with @kyrofa that this is not a snap issue and bar any experience with cloudflare, there's really nothing we could suggest.

**Comment by varriaza** [comment]
I use npm to connect to cloudflare and authenticate that the domain is mine and NPM generates the SSL. I think I disabled Nextcloud certificates. Seems most likely a issue on my end setting everything up. I'll have to keep poking around. Thanks to both of you for the help!
