### ISSUE TITLE
Unable to add to Gnome as an online account

### ISSUE THREAD

**Issue by Richard-Quinlivan** [nextcloud-snap/nextcloud-snap#2613]
#### Describe the bug
I am unable to add my nextcloud account to Gnome as an online account. After I enter my details, the settings app just hangs and eventually a popup saying it has stopped responding appears and asks if I want to wait or force quit. I'm fairly certain this was not an issue when I used the Docker image, but i's been a while since I switched and I don't rememeber 100% if this started before I switched or right after, but I'm pretty sure it's when I switched. 

#### To Reproduce
1. Open the Gnome settings app on Fedora (I'm on fedora 39 but this was also the case for 38 and I think 37 as well) 
2. Navigate to online accounts and select the nextcloud option
3. Enter the details of the nextcloud instance (server, username and password) Optionally, you can create an app password here by going to the Security tab of your nextcloud instance
4. Press Connect and observe that it will freeze and ask if you want to force quit.

#### Expected behavior
After pressing Connect it should add your Nextcloud account to the system

#### OS/snapd/snap version
Fedora 39 (desktop)
Ubuntu 22.04.3 LTS (This is where my nextcloud server is hosted)

snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  27.1.3snap1  38457  latest/stable  nextcloud✓  -

snap version
snap    2.60.4
snapd   2.60.4
series  16
ubuntu  22.04
kernel  5.15.0-83-generic

#### Logs
[logs.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/13344178/logs.txt)

**Comment by Pilzinsel64** [comment]
What url did you enter?

Also you might take a look how to setup the FQDN on your system. This can help a vesting you ibstance. Even more if you access your instance on the same mashine. https://github.com/nextcloud-snap/nextcloud-snap/wiki/Hosts-and-FQDN-for-Nextcloud-snap

**Comment by scubamuc** [comment]
> Nov 06 03:35:50 localhost nextcloud.renew-certs[2347636]: Self-signed certificates aren't due for renewal
Nov 06 03:35:55 localhost nextcloud.renew-certs[2348083]: Saving debug log to /var/snap/nextcloud/current/certs/certbot/logs/letsencrypt.log
Nov 06 03:35:55 localhost nextcloud.renew-certs[2348083]: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Nov 06 03:35:55 localhost nextcloud.renew-certs[2348083]: No renewals were attempted.
Nov 06 03:35:55 localhost nextcloud.renew-certs[2348083]: No hooks were run.
Nov 06 03:35:55 localhost nextcloud.renew-certs[2348083]: - - - - - - - - - - -

please check your SSL certificate. it seems your instance is not encrypted correctly. GNOME online accounts expects HTTPS, regardless of version and OS. Self-signed certificates will not work.

**Comment by Richard-Quinlivan** [comment]
> What url did you enter?
> 
> Also you might take a look how to setup the FQDN on your system. This can help a vesting you ibstance. Even more if you access your instance on the same mashine. https://github.com/nextcloud-snap/nextcloud-snap/wiki/Hosts-and-FQDN-for-Nextcloud-snap

This isn't the exact name but it's in the same format as this https://11.11.111.111
This is the url that is in the top bar of my search engine when i go to my instance online, it's also what appears when I go to the "Mobile and desktop" section on my instance and scroll down to the server address from there.

**Comment by Richard-Quinlivan** [comment]
> > Nov 13 03:36:07 localhost nextcloud.renew-certs[2347636]: Self-signed certificates aren't due for renewal
> > Nov 13 03:36:09 localhost nextcloud.renew-certs[3300347]: Saving debug log to /var/snap/nextcloud/current/certs/certbot/logs/letsencrypt.log
> > Nov 13 03:36:09 localhost nextcloud.renew-certs[3300347]: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
> > Nov 13 03:36:09 localhost nextcloud.renew-certs[3300347]: No renewals were attempted.
> > Nov 13 03:36:09 localhost nextcloud.renew-certs[3300347]: No hooks were run.
> > Nov 13 03:36:09 localhost nextcloud.renew-certs[3300347]: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
> 
> please check your SSL certificate. it seems your instance is not encrypted correctly. GNOME online accounts expects HTTPS regardless of version and OS. Self-signed certificates will not work.

I'm not exactly sure how to do this, but I'll see if I can find a guide online. I'm curious, is there a reason the snap doesn't do this automatically?

**Comment by scubamuc** [comment]
see [configure Nextcloud snap wiki](https://github.com/nextcloud-snap/nextcloud-snap/wiki/configure-Nextcloud-snap)

> [Configure Nextcloud snap](https://github.com/nextcloud-snap/nextcloud-snap/wiki/configure-Nextcloud-snap#configure-nextcloud-snap)
The only thing we recommend you do up front is enable HTTPS. Nextcloud snap includes a service for automated HTTPS encryption using Lets Encrypt, or self-signed certificates. Run nextcloud.enable-https -h for more information.

**Comment by kyrofa** [comment]
> I'm curious, is there a reason the snap doesn't do this automatically?

Because Let's Encrypt requires two very key pieces of information in order to issue certs:

1. An administrator's email address
2. The domain in question

The snap doesn't actually know these by default. You have to tell it via the `nextcloud.enable-https lets-encrypt` command.

**Comment by Richard-Quinlivan** [comment]
I see, it looks like I'll have to get a domain for my Nextcloud instance then. From what I can tell letsencrypt only works if you aren't just using the ip address. Thanks all, I'll start looking around for somewhere to buy a domain name and then switch from self signing to lestencypt

**Comment by Richard-Quinlivan** [comment]
> As alternative to by a top level domain you can also just get a sub-domain from a free dyn-dns provider, like no-ip or clou-dns (no guaranty, never tried them), if you don't want to pay for a domain. I do that for my private cloud instance too (I use ddnss.de).

That's interesting, I didn't know that was an option. I'd have to do some research to see if there's one in the US that's any good. I'm not opposed to buying a domain, but if I can do it without that then I'm all for saving some money

**Comment by scubamuc** [comment]
Modern DNS Hosting for Everyone

deSEC is a free DNS hosting service, designed with security in mind.

Running on open-source software and supported by [SSE](https://securesystems.de/), deSEC is free for everyone to use.

https://desec.io/

**Comment by Richard-Quinlivan** [comment]
Awesome thanks, I'll check that out!
