### ISSUE TITLE
Changing datadirectory based on nextcloud wiki is a recipe for disaster

### ISSUE THREAD

**Issue by matriculus** [nextcloud-snap/nextcloud-snap#2615]
#### Describe the bug
Documentation in https://github.com/nextcloud-snap/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition shows the procedure to change the datadirectory for nextcloud snap version.

This is the crucial point while moving the data to the new location:
```
$ sudo mv /var/snap/nextcloud/common/nextcloud/data /media/nextcloud/
```
By following the documentation (for admin created already), every time, my server shows the following error in browser.
```
Your data directory is invalid. Ensure there is a file called ".ocdata" in the root of the data directory. 
```
No matter how twisted I can do, the documentation is a pure recipe for disaster. Please update this documentation with additional things which need to be done to avoid these problems. There is no proper solution is available anywhere including nextcloud community pages.

#### To Reproduce
1. Just follow the steps in https://github.com/nextcloud-snap/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition

#### Expected behavior
The nextcloud should be running without any hiccups with new datadirectory.

#### Screenshots
![image](https://github.com/nextcloud-snap/nextcloud-snap/assets/10431830/4f7ec28f-83a2-4ae7-a7a9-fbeda0970d3a)

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  27.1.3snap1  38457  latest/stable  nextcloud✓  -

and:

    $ snap version
snap    2.60.4
snapd   2.60.4
series  16
ubuntu  22.04
kernel  6.2.0-37-generic
#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).

**Comment by matriculus** [comment]
The following link is also followed. It shows if we give path correctly to the `data` folder, including` it should solve. But it doesn't.
https://github.com/nextcloud-snap/nextcloud-snap/wiki/Wiki-Change-data-directory#path-to-data-directory

**Comment by kyrofa** [comment]
You're missing the output of that issue debugging script.

**Comment by scubamuc** [comment]
@matriculus are you sure you're including `'` and not " ` " you have to be meticulous about this.

`'datadirectory' => '/your/path/to/directory/data'`

ensure also that ` /your/path/to/directory/data `  is accessible by snap, see See [connect external media](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-Nextcloud-snap#removable-media)

**Comment by matriculus** [comment]
I'm using ' and not `. The path is to `$HOME/Nextcloud/data`. `$HOME` is expanded. Absolute path is given.

**Comment by matriculus** [comment]
> You're missing the output of that issue debugging script.

I'll add it sometime today.

**Comment by scubamuc** [comment]
See first section in [Wiki](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Wiki-Change-data-directory#change-nextcloud-snap-data-directory)

**Comment by kyrofa** [comment]
> Oh! I didn't know about that. Is there a way this point be mentioned along with the documentation? 

It's literally the first sentence of the [wiki page you followed](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition):

> The partition you want to use must be mounted somewhere in `/media/` or `/mnt/`.

If I may offer some advice: when asking for help on an open source project, read what you're saying for tone.

> No matter how twisted I can do, the documentation is a pure recipe for disaster. Please update this documentation with additional things which need to be done to avoid these problems. There is no proper solution is available anywhere including nextcloud community pages.

I recommend avoiding hyperbole, assuming good intentions, and assuming what _you're_ doing is wrong, not the docs or software. Obviously that may not always be the case, but people will be far more willing to help you.
