### ISSUE TITLE
Where is the database password stored in backups?

### ISSUE THREAD

**Issue by Matth3wW** [nextcloud-snap/nextcloud-snap#2621]
I recently lost a hard drive containing my nextcloud snap instance. Luckily, all I need to recover are the calendars and contacts in the database, which I have a backup of from running nextcloud.export. 

From the backup that is taken, where can I find the database username and password? 

From my very limited programming knowledge, this file seems to indicate a random password is generated for the root and nextcloud users: https://github.com/nextcloud-snap/nextcloud-snap/blob/master/src/mysql/bin/start_mysql

I checked config.php, but only found this:
`  'dbpassword' => 'DBPASSWORD',`

**Comment by scubamuc** [comment]
poking around too...
![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/e308a105-af1e-4b8a-a3c8-357a1e9bf1ce)
try
user: nextcloud
pwd: root-user-password

**Comment by kyrofa** [comment]
Can you expand on what you're trying to do, here? Do you just want to restore a backup? Or are you wanting to poke at the database on another machine? The backup generated by `nextcloud.export` is just a mysql dump of the `nextcloud` database. It doesn't really have a concept of users. When you install a new instance of the snap, it'll generate its own root (and nextcloud user) passwords, and then you'll be able to `nextcloud.import` your backup. Assuming all you care about is importing your backup, you shouldn't need to care about users at all.

**Comment by Matth3wW** [comment]
Thank you two, that was a misunderstanding on my end. I was able to import the database to my personal machine by using the following commands:
`sudo mysql`
`create database nextcloud;`
`exit`
`sudo mysql -u root -p nextcloud < /path/to/database.sql`

I've already created a new nextcloud instance without the use of my backup. My intent is to export the calendar, contacts, and notes tables from my old database and import them into my new database.

**Comment by kyrofa** [comment]
No problem, that's what this issue tracker is all about! Yeah I'd say you're on the right track here. `nextcloud.mysql-client` will probably prove useful to you. Just remember it will only be able to access `/var/snap/nextcloud/current` under confinement, so if you shave off smaller table dumps to import in pieces, make sure you put them in there.

**Comment by Matth3wW** [comment]
For anyone who might stumbled across this post via a search engine, I ended up creating a new snap nextcloud instance and did a backup import (without data). I then used the calcardbackup script with the -p flag and it worked great! 

https://codeberg.org/BernieO/calcardbackup

**Comment by kyrofa** [comment]
Awesome, thanks for the update @Matth3wW!
