### ISSUE TITLE
FUSE needed (perhaps) for Collabora CODE server

### ISSUE THREAD

**Issue by kz6fittycent** [nextcloud-snap/nextcloud-snap#2622]
#### What dependency/component is out of date?
The Collabora CODE application loads a AppImage which requires `fuse`.  This isn't working for many, and in reading the docs, it looks like the application requires the fuse lib(s). This might just fix the problem we're all seeing.

**Comment by kyrofa** [comment]
Sorry @kz6fittycent, we have a policy of not adding dependencies beyond that required by the default apps. Especially that one: it's been a nightmare to try and support.

**Comment by scubamuc** [comment]
@kz6fittycent, did you follow this [Wiki](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-CODE-and-Nextcloud-office-for-Nextcloud-snap#collabora-online---built-in-code-server-and-nextcloud-office-for-nextcloud-snap) there's nothing else needed.

> This isn't working for many

Whom are you referring to?

**Comment by kz6fittycent** [comment]
> @kz6fittycent, did you follow this [Wiki](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-CODE-and-Nextcloud-office-for-Nextcloud-snap#collabora-online---built-in-code-server-and-nextcloud-office-for-nextcloud-snap) there's nothing else needed.
> 
> > This isn't working for many
> 
> Whom are you referring to?

Well the forums are full of people who can't get it working. Yeah, I'm very familiar with the wiki. That said, I just did my own thing and spun up the docker container on a separate server, pointed to that host and port and it's working. I'd have rather had it all working on the same host, but it's fine.

**Comment by Pilzinsel64** [comment]
> The Collabora CODE application loads a AppImage which requires `fuse`.

Not related for solving the issue, but as side Info: If `fuse` is not available, the app image will be extracted and started from there instead. This is case also for me. The only side effect is at first startup where it takes a few seconds to extract the image.
