### ISSUE TITLE
Blank Apps Pages and Logs Page PHP Errors

### ISSUE THREAD

**Issue by stondino00** [nextcloud-snap/nextcloud-snap#2624]
Anybody else seeing these in logs section of admin?  Also all of the sudden seeing blank pages when going to any apps section pages.

Just wondering if it's on my end or something else in the beta channel.

![image](https://github.com/nextcloud-snap/nextcloud-snap/assets/54154986/469dcc91-002b-470d-9475-e22685856d5c)

**Comment by stondino00** [comment]
Appears others are seeing this as well.

https://github.com/nextcloud/server/issues/42042

**Comment by stondino00** [comment]
Seems to be fixed and related to nextcloud store API.

**Comment by 1manprojects** [comment]
This Bug might have happed due to a change in the Store API however this causes another Bug in NextCloud itself.
See https://github.com/nextcloud/server/issues/42042#issuecomment-1841472058
