### ISSUE TITLE
Migrating user from Nextcloud server to Nextcloud snap causes "Application updatenotification (updatenotification) is not present or has a non-compatible version with this server. Please check the apps directory" error

### ISSUE THREAD

**Issue by kubuntu-newbie** [nextcloud-snap/nextcloud-snap#2625]
#### Describe the bug
I'm trying to migrate from the Nextcloud server running on Ubuntu to Nextcloud snap, I was unable to find any instructions online except the official Nextcloud docs that do not cover snap

#### To Reproduce

1. Create a backup of folders and database as described in https://docs.nextcloud.com/server/stable/admin_manual/maintenance/backup.html
2. Install snap version of nextcloud, enter web interface, configure nextcloud - at this point everything works as expected
4. Enter maintenance mode
nextcloud.occ maintenance:mode --on
5. Restore dir backup to /var/snap/nextcloud/common/nextcloud
6. chown to root restored folders
7. Delete and create new nextcloud database using nextcloud.mysql-client
8. Restore backup of database
nextcloud.mysql-client nextcloud < nextcloud-sqlbkp.sql
9. Exit maintenance mode
nextcloud.occ maintenance:mode --off

at this point I get a message: "Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Maintenance mode disabled"

running nextcloud.occ upgrade produces: "UnexpectedValueException: The files of the app "updatenotification" were not correctly replaced before running the update
Update failed"

accessing Nextcloud web interface shows:

Error
Application updatenotification (updatenotification) is not present or has a non-compatible version with this server. Please check the apps directory.

#### Expected behavior
Expected to be able to see the restored data in the nextcloud web interface

#### OS/snapd/snap version

    $ snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  27.1.3snap1  38457  latest/stable  nextcloud✓  -

and:

    $ snap version

snap    2.60.4+23.10.1
snapd   2.60.4+23.10.1
series  16
ubuntu  23.10
kernel  6.5.0-14-generic

as far as I understand updatenotification doesn't even exist in the snap version of Nextcloud

**Comment by kubuntu-newbie** [comment]
The workaround I found is to do the following:

nextcloud.occ config:app:set updatenotification enabled
and then run nextcloud.occ upgrade

can't uninstall updatenotification, get an error that app is not installed

the proper fix would be, since updatenotification doesn't exist in Nextcloud snap, it's config should be ignored all together

**Comment by kyrofa** [comment]
Glad you found the solution!

> it's config should be ignored all together

Sadly that's something that upstream Nextcloud would need to do, not us.
