### ISSUE TITLE
Auto-renewal of Let's Encrypt certificate fails

### ISSUE THREAD

**Issue by wah211** [nextcloud-snap/nextcloud-snap#2636]
#### Describe the bug
Auto-renewal of Let's Encrypt certificate fails.

#### To Reproduce
1. Attempt to auto-renew SSL certificate.
2. Renewal fails.

#### Expected behavior
SSL certificate is successfully renewed.

#### OS/snapd/snap version
What OS and version are you running? 

Ubuntu 22.04.3 LTS x86_64

Please also include the output of the following commands:

    $ snap list nextcloud

Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  27.1.4snap1  39212  latest/stable  nextcloud✓  -

and:

    $ snap version

snap    2.60.4
snapd   2.60.4
series  16
ubuntu  22.04
kernel  5.15.0-91-generic

#### Logs
See attached log.txt file.
[log.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/13747482/log.txt)
Also see the below output from the command `sudo journalctl -u snap.nextcloud.renew-certs.service`

Dec 17 02:56:56 homeserver nextcloud.renew-certs[1119363]: Cert is due for renewal, auto-renewing...
Dec 17 02:56:56 homeserver nextcloud.renew-certs[1119363]: Non-interactive renewal: random delay of 357 seconds
Dec 17 03:02:53 homeserver nextcloud.renew-certs[1119363]: Plugins selected: Authenticator webroot, Installer None
Dec 17 03:02:53 homeserver nextcloud.renew-certs[1119363]: Renewing an existing certificate
Dec 17 03:02:54 homeserver nextcloud.renew-certs[1119363]: Performing the following challenges:
Dec 17 03:02:54 homeserver nextcloud.renew-certs[1119363]: http-01 challenge for URL
Dec 17 03:02:54 homeserver nextcloud.renew-certs[1119363]: Cleaning up challenges
Dec 17 03:02:54 homeserver nextcloud.renew-certs[1119363]: Attempting to renew cert (URL) from /var/snap/nextcloud/current/certs/certbot/config/renewal/URL.conf produced an unexpected error: Missing command line flag or config entry for this setting
Dec 17 03:02:54 homeserver nextcloud.renew-certs[1119363]: Input the webroot for URL:. Skipping.
Dec 17 03:02:54 homeserver nextcloud.renew-certs[1119363]: All renewal attempts failed. The following certs could not be renewed:
Dec 17 03:02:54 homeserver nextcloud.renew-certs[1119363]:   /var/snap/nextcloud/current/certs/certbot/config/live/URL/fullchain.pem (failure)
Dec 17 03:02:54 homeserver nextcloud.renew-certs[1119363]: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Dec 17 03:02:54 homeserver nextcloud.renew-certs[1119363]: All renewal attempts failed. The following certs could not be renewed:
Dec 17 03:02:54 homeserver nextcloud.renew-certs[1119363]:   /var/snap/nextcloud/current/certs/certbot/config/live/URL/fullchain.pem (failure)
Dec 17 03:02:54 homeserver nextcloud.renew-certs[1119363]: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Dec 17 03:02:54 homeserver nextcloud.renew-certs[1119363]: Running post-hook command: restart-apache
Dec 17 03:02:55 homeserver nextcloud.renew-certs[1119363]: Output from post-hook command restart-apache:
Dec 17 03:02:55 homeserver nextcloud.renew-certs[1119363]: Restarting apache... done
Dec 17 03:02:55 homeserver nextcloud.renew-certs[1119363]: 1 renew failure(s), 0 parse failure(s)

**Comment by scubamuc** [comment]
your certificate looks fine:

![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/c65eaf93-9e91-40b3-bd3b-dcb53b369bf2)

renewal not necessary

you could try [this](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Managing-HTTP-encryption-(HTTPS)#change-nextcloud-lets-encrypt-domain) and encrypt from scratch

**Comment by wah211** [comment]
Okay, thank you for your help. I will close the issue since it is not a bug.
