### ISSUE TITLE
Dailies for NC28 not available on `28/edge`

### ISSUE THREAD

**Issue by Pilzinsel64** [nextcloud-snap/nextcloud-snap#2638]
#### Describe the bug
The channel `28/edge` does not exists. The daily builds and tests success and the snap package for latest-28 seems to get updated fine to launchpad. But it doesn't seem to have a channel (in this case `28/edge`) assicoated with.

#### To Reproduce
Perform a fresh install via `sudo snap install nextcloud --channel=28/edge` or refresh an existing instance via `sudo snap refresh nextcloud --channel=28/edge`.

#### Expected behavior
The installation or refresh should work, the channel 28/edge should exist.

**Comment by kyrofa** [comment]
Ah, thank you, just made it: https://launchpad.net/~kyrofa/+snap/nextcloud-daily-28 .

**Comment by Pilzinsel64** [comment]
Ah thank you. I completely missed that new track. :D

**Comment by kyrofa** [comment]
Wow, that took forever to get approved, but finally done now.

**Comment by Pilzinsel64** [comment]
Hallelujah. :D

**Comment by kyrofa** [comment]
I'm not bitter about anything :stuck_out_tongue: .
