### ISSUE TITLE
Nextcloud Connection refused - Waiting for PHP issue? MySQL corrupted tables?

### ISSUE THREAD

**Issue by gjanos89** [nextcloud-snap/nextcloud-snap#2640]
My colleagues reported me that Nextcloud is offline since yesterday. It says when trying to reach the webpage that connection refused. This has happened before with a sudden power outage, but this time there was none to my knowledge. Last time it was repaired with reinstall, but we have some users to be recreated and also using Deck app to manage projects since last time, so a reinstall is not an option. I am thinking about corrupted MySQL tables as a guess and would like to know how is it possible to repair it with the snap install? 

1. Try to connect to nextcloud - connection refused
2. Try "sudo netstat -tulpn
   --> Nextcloud not listening on http or https ports
3. Try Debug script from github - never finishes, stuck with "Waiting for PHP..."

#### Expected behavior
Working Nextcloud

#### OS/snapd/snap version

    $ snap list nextcloud

Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  27.1.4snap1  39216  latest/stable  nextcloud✓  -

    $ snap version

snap    2.60.4
snapd   2.60.4
series  16
debian  10
kernel  5.10.103-v8+

Could you please take a look and help? I might have an SSD that is not working properly, so I plan to move the data folder anyhow to new HDDs, but I need the status back from yesterday. Also I was dumb enough to not have a backup, which I will do now (possible automatically with snap??)

I cannot find any log files related to PHP or MySQL under /var/snap/nextcloud/... could you please let me know the directories? Trying based in Issue 1246, but did not find the log files - I have not done any customization on the snap, so should be in original place.

**Comment by scubamuc** [comment]
we can't be sure about support for your OS, see [requirements](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Installation-requirements) and why [Ubuntu is the only supported distribution](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Why-Ubuntu-is-the-only-supported-distro).

- Can you name details about your environment, (hardware, VM, container etc...)
- Do you recall any changes made lately (before yesterday)? 
- Did you add any apps?

> I cannot find any log files related to PHP or MySQL under /var/snap/nextcloud/... could you please let me know the directories? Trying based in Issue [1246](https://github.com/nextcloud-snap/nextcloud-snap/issues/1246), but did not find the log files - I have not done any customization on the snap, so should be in original place.

See  [managing logs](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Managing-logs).

> Also I was dumb enough to not have a backup, which I will do now (possible automatically with snap??)

This may help for automated snap backups; [Backup, restore & migrate](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Backup-and-Restore) see also [example rotating backup script](https://github.com/scubamuc/scubamuc.github.io/blob/scubamuc/wiki-md/NEXTCLOUD.snap--backup_snap-snapshot.md#rotating-nextcloud-snap-snapshots-script-to-media-incl-logging)

**Comment by gjanos89** [comment]
@scubamuc thanks for the support!

> Can you name details about your environment, (hardware, VM, container etc...)

**Hardware**        : BCM2835
Model           : Raspberry Pi 4 Model B Rev 1.2

**OS:**
pi@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"

I managed to save the logs:
[ApacheLog.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/13838373/ApacheLog.txt)
[MySQLLog.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/13838374/MySQLLog.txt)
[NextcloudLog.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/13838375/NextcloudLog.txt)

MySQL log is partial, but these messages are on repeat. 
InnoDB insertion error as I suspected, there should be a recovery for that, but I only find commands where MySQL or mariaDB is directly installed, I found also docker commands, but not for snap 🈂️ 

> Do you recall any changes made lately (before yesterday)?
> Did you add any apps?
I do not recall any changes made lately, We use only two "extra" apps, but those were initially intalled:

- Temporary file locks
- Decks

> This may help for automated snap backups; [Backup, restore & migrate](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Backup-and-Restore) see also [example rotating backup script](https://github.com/scubamuc/scubamuc.github.io/blob/scubamuc/wiki-md/NEXTCLOUD.snap--backup_snap-snapshot.md#rotating-nextcloud-snap-snapshots-script-to-media-incl-logging)

Thank you so much for sure will do this after restoring :)

**Comment by scubamuc** [comment]
so your logs are displaying a mysql issue:

````
2024-01-04T17:37:32.736449Z 0 [ERROR] [MY-013183] [InnoDB] Assertion failure: fut0lst.ic:81:addr.page == FIL_NULL || addr.boffset >= FIL_PAGE_DATA thread 5$InnoDB: We intentionally generate a memory trap.
InnoDB: Submit a detailed bug report to http://bugs.mysql.com.
InnoDB: If you get repeated assertion failures or crashes, even
InnoDB: immediately after the mysqld startup, there may be
InnoDB: corruption in the InnoDB tablespace. Please refer to
InnoDB: http://dev.mysql.com/doc/refman/8.0/en/forcing-innodb-recovery.html
InnoDB: about forcing recovery.
2024-01-04T17:37:32Z UTC - mysqld got signal 6 ;
Most likely, you have hit a bug, but this error can also be caused by malfunctioning hardware.
BuildID[sha1]=7a7b99da33acb19c1a647ceeb813a45d4786fb61
Thread pointer: 0x7f48000b20
Attempting backtrace. You can use the following information to find out
where mysqld died. If you see no messages after this, something went
terribly wrong...
````
Have you done suggested:

> InnoDB: Submit a detailed bug report to http://bugs.mysql.com.

**Comment by gjanos89** [comment]
No I have not done it since I am not sure how to navigate in mysql within the Nextcloud snap...is there a possibility to do the repair similar like this: https://stackoverflow.com/questions/28521530/mysql-fatal-error-cant-open-and-lock-privilege-tables-incorrect-file-format

But with commands inside the snap install?

**Comment by scubamuc** [comment]
> You won't be able to run snap commands to package it up nicely, but you can just slurp off the entire directory if you have another drive (or machine to scp it to). Worst case you lose your database, but you should be able to grab all the raw data assuming your drive hasn't eaten it. I would grab the entire /var/snap/nextcloud directory if I were you-- by default everything you care about is there. Did you change the data directory, though? If so, you'll need to grab that directory as well.

**Comment by gjanos89** [comment]
But for sure all users has to be recreated with the corrupted tables right?

**Comment by scubamuc** [comment]
yeah, I guess... 
how many users are you hosting on a Raspi4?

**Comment by gjanos89** [comment]
not much, 5-10, but they also have to be instructed how to synch the desktop app again and what ever they changed in the meantime...
thanks a lot for the support :)
