### ISSUE TITLE
[NC28] Missing recommended php module `sodium`

### ISSUE THREAD

**Issue by Pilzinsel64** [nextcloud-snap/nextcloud-snap#2643]
While testing NC28 via the `28/edge` channel Nextcloud complains about some missing PHP modules but without telling me what exactly is missing. So, let's review the installed and recommended/required php modules by following the [official documentation](https://docs.nextcloud.com/server/28/admin_manual/installation/php_configuration.html#php-modules).

### Required:
- [x] Core
- [x] ctype
- [x] curl
- [x] dom
- [x] fileinfo
- [x] filter (only on Mageia and FreeBSD)
- [x] GD
- [x] hash (only on FreeBSD)
- [x] JSON
- [x] libxml
- [x] mbstring
- [x] openssl
- [x] posix
- [x] session
- [x] SimpleXML
- [x] XMLReader
- [x] XMLWriter
- [x] zip
- [x] zlib

### Database connectors
- [x] pdo_mysql

### _Recommended_ packages
- [x] bz2 (required for extraction of apps)
- [x] intl (increases language translation performance and fixes sorting of non-ASCII characters)
- [ ] sodium (for Argon2 for password hashing. bcrypt is used as fallback, but if passwords were hashed with Argon2 already and the module is missing, your users can’t log in.)

### Required for specifc apps:
- [x] ldap (for LDAP integration)
- [ ] smbclient ([SMB/CIFS](https://docs.nextcloud.com/server/28/admin_manual/configuration_files/external_storage/smb.html) integration, see SMB/CIFS)
- [x] ftp (for FTP storage / external user authentication)
- [ ] imap (for external user authentication)
- [x] bcmath (for passwordless login)
- [ ] gmp (for passwordless login)

### Recommended for specific apps _(optional)_:
- [x] exif (for image rotation in pictures app)

### For enhanced server performance _(optional)_:
- [x] PHP module redis (>= 2.2.6, required for Transactional File Locking)

### For preview generation _(optional)_:
- [ ] imagick

### For command line processing _(optional)_:
- [x] pcntl (enables command interruption by pressing ctrl-c)

## Review

There are five modules that are "recommended" and not needed. Let's check them...
- imagick: We probably will never install this. So, ignore it.
- gmp: Might be required if someone uses passworldess login.
- imap: Might be requied if someone uses the app [External user authentication](https://apps.nextcloud.com/apps/user_external)
- smbclient: Might be required if someone wants to mount an external storage via smb.
- sodium: It's just recommended for Argon2 as an alternative to bcrypt.

## Summary

The only two modules that might be suggested by Nextcloud 28 admin overview page can be `imagick` or `sodium`. While `imagick` has its own message, the possibility is high that the meant recommended php module is `sodium`.

This said, it is probably not required to install any other module. But have you any suggestions or thoughts about installing some of the recommended apps that aren't installed yet? Should we maybe try when we finally have nc28 in stable via a PR and test its temporar channel? @nextcloud-snap/developers 

I leave this open for discussion for now. We can close it at any time and keep it as documentation or move it to a Wiki page. :)

**Comment by Pilzinsel64** [comment]
It turns out that the missing package is `sodium`. That said, a fix is in the pipe in #2655

**Comment by MichaelNienburg** [comment]
Imagick is needed also for Photo and Memories apps if you want to save a photo after editing. Does not work. Are there any workarounds?
![image](https://github.com/nextcloud-snap/nextcloud-snap/assets/129684706/b8715693-391c-4fb1-b41a-4ee354528933)

**Comment by scubamuc** [comment]
@MichaelNienburg see [FAQ's](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-nextcloud-snap-shows-security--setup-warnings-what-can-i-do)

**Comment by MichaelNienburg** [comment]
Thank you @scubamuc . Imagick is not included in the sanp due to security concerns, I understand. But still the software is not working without it. Does it make sense?
