### ISSUE TITLE
NextCloud Office

### ISSUE THREAD

**Issue by paulh358** [nextcloud-snap/nextcloud-snap#2644]
#### Describe the bug
NextCloud Office with Built-In Collabora CODE Server does not load documents.

#### To Reproduce
(1) Add Apps for: NextCloud Office and Collabora Built-In CODE Server
(2) Configure Administration Settings to enable Collabora Built-In Server
(3) Add WOPI IP address for NextCloud Server
OBSERVE that all appears OK with connection to Collabora confirmed. But all is not as it appears.

#### Expected behaviour
I expect to create a new NextCloud Office document but the system hangs attempting to load the document.
I expect to edit an existing Office document but the system hangs attempting to load the document.
I expect NextCloud Office to 'just work'. But it does not. I have been working on this for months. No joy.

###
Using Latest updated version of NextCloud Snap on Ubuntu with all Linux updates installed.

**Comment by Pilzinsel64** [comment]
Please take a look at our wiki pages. There are some infos that might help you, e.g. packages to install, hostname and other nextcloud config adjustments. They're mostly to get the Build-in CODE app to work, but probably helps on dedicated installation too.
- https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-CODE-and-Nextcloud-office-for-Nextcloud-snap
- https://github.com/nextcloud-snap/nextcloud-snap/wiki/Hosts-and-FQDN-for-Nextcloud-snap

What's you setup? Do you have Collabora as docker installed? Is it on the same server as Nextcloud or on another server?

**Comment by scubamuc** [comment]
@paulh358 

you can reset WOPI by issuing following command on host see [here](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-CODE-and-Nextcloud-office-for-Nextcloud-snap#5-configure-code)

 **delete configs**: `sudo nextcloud.occ config:app:delete richdocuments public_wopi_url`
and
  **delete configs**: `sudo nextcloud.occ config:app:delete richdocuments wopi_url`
