### ISSUE TITLE
I've installed Nextcloud with Snap. Now what?

### ISSUE THREAD

**Issue by Flimm** [nextcloud-snap/nextcloud-snap#2645]
I've installed Nextcloud on Ubuntu using Snap like this:

    sudo snap install nextcloud

I've installed it now. Now what do I do?

The README says:

> Upon visiting the Nextcloud installation for the first time, ...

How do I do that? How do I visit the Nextcloud installation? What address should I put in my browser?

**Comment by kyrofa** [comment]
The IP address of the computer on which you installed the snap. If you're trying to visit it on the same machine, you can try `http://localhost`. Otherwise, you'll need to know the IP of the machine.

**Comment by Flimm** [comment]
Thank you! Visiting http://localhost or http://127.0.0.1 worked for me. It would be helpful if this was mentioned in the Snap package's description and in this repo's README.

**Comment by scubamuc** [comment]
@Flimm its right here in the wiki: https://github.com/nextcloud-snap/nextcloud-snap/wiki/install-Nextcloud-snap

**Comment by Flimm** [comment]
Thank you, that is helpful!

Most GitHub projects have sparse or empty "Wiki" sections, so I would have never thought to check the wiki section. I suggest that a link to the wiki section be added to the README and/or the description of the Snap, so that others find the wiki quicker.
