### ISSUE TITLE
typo on page Configure CODE and Nextcloud office for Nextcloud snap

### ISSUE THREAD

**Issue by Guillaume99** [nextcloud-snap/nextcloud-snap#2646]
typo error on the page
https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-CODE-and-Nextcloud-office-for-Nextcloud-snap

paragraph: 4. Set trusted proxy in Config-php

sudo nextcloud.occ config:system:set trusted_poxies 0 --value="your.proxy.ip" ;
                                                                              ^^^

**Comment by scubamuc** [comment]
thanks for the heads up... 
I must be blind 'cause I can't see where the typo is. 
can you be clearer please?

**Comment by Guillaume99** [comment]
in the command, trusted_poxies is missing an r and writes "poxies"

sudo nextcloud.occ config:system:set trusted_**poxies** 0 --value="your.proxy.ip"

**Comment by scubamuc** [comment]
thank you so much and keep reading :+1:
