### ISSUE TITLE
PhpRedis

### ISSUE THREAD

**Issue by stondino00** [nextcloud-snap/nextcloud-snap#2647]
What is phpredis used for in the snap?

They have released a version 6.0.X that fixes tons of bugs it appears as the current 5.X version is from Sept 2022.

![image](https://github.com/nextcloud-snap/nextcloud-snap/assets/54154986/9fe6d2c4-441f-4ebb-9114-5f1cd67ee530)

**Comment by pachulo** [comment]
> What is phpredis used for in the snap?

It's the PHP extension that allows it to "talk" to the Redis server on the snap. We should be checking this!

**Comment by pachulo** [comment]
I'm on channel `27/beta`, testing the upgraded components in my production instance.

```
$ /snap/nextcloud/current/bin/redis-server --version
Redis server v=7.0.15 sha=c3a14d49:0 malloc=jemalloc-5.2.1 bits=64 build=f4a348a9408698d1
```
