### ISSUE TITLE
App-Breaking Login-Issue on ARM-Version

### ISSUE THREAD

**Issue by ne0YT** [nextcloud-snap/nextcloud-snap#2648]
#### Describe the bug
It's impossible to login on the arm version of nextloud snap-package.
the only simple circumvention is to refresh the page after login. BUT this workaround doesn't work for Apps.
Especially not for the Talk App. (It sometimes works on the Nextcloud App, when trying many times).
The login itself works, but it doesn't continue (it creates the app-password in the background).
login in the talk app with a user and app-password doesn't circumvent it.

#### To Reproduce
1. got to the nextcloud page
2. login
3. it loads forever

#### Expected behavior
1. got to the nextcloud page
2. login
3. getting logged in like in the x86 package

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:
nextcloud  27.1.4snap1  39216  latest/stable  nextcloud✓

snap version                                                                                                                  
snap    2.61.1                                                                                                                             
snapd   2.61.1                                                                                                                             
series  16                                                                                                                                 
ubuntu  23.10                                                                                                                              
kernel  6.5.0-1008-raspi

**Comment by ne0YT** [comment]
[outputofscript.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/13948074/outputofscript.txt)

**Comment by scubamuc** [comment]
it seems as though you have skipped some configuration steps...

your logs are showing the following recurring errors:
```
Jan 15 22:00:54 rpi5 nextcloud.apache[10965]: No certificates are active: using HTTP only
Jan 15 22:00:57 rpi5 nextcloud.apache[11162]: error: cannot communicate with server: Post "http://localhost/v2/snapctl": read unix @->/run/snapd-snap.socket: read: connection reset by peer
....
Jan 15 22:00:57 rpi5 nextcloud.apache[11672]: AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
Jan 15 22:00:57 rpi5 systemd[1]: snap.nextcloud.apache.service: Deactivated successfully.
```
error messages:

> No certificates are active: using HTTP only

- enable HTTPS encryption? See [Configuration](https://github.com/nextcloud-snap/nextcloud-snap/wiki/configure-Nextcloud-snap) first section [enable HTTPS encryption with Lets Encrypt](https://github.com/nextcloud-snap/nextcloud-snap/wiki/configure-Nextcloud-snap#enable-https-encryption-with-lets-encrypt) 
  - that should resolve the logging in issue  

> Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message

- you may want to check out [hosts & FQDN configuration](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Hosts-and-FQDN-for-Nextcloud-snap) to resolve the second recurring log message. This section for [your setup](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Hosts-and-FQDN-for-Nextcloud-snap#fqdn-for-nextcloud-snap-on-internet-facing-instance)
  - this is optional but recommended

**Comment by ne0YT** [comment]
> it seems as though you have skipped some configuration steps...
> 
> your logs are showing the following recurring errors:
> 
> ```
> Jan 15 22:00:54 rpi5 nextcloud.apache[10965]: No certificates are active: using HTTP only
> Jan 15 22:00:57 rpi5 nextcloud.apache[11162]: error: cannot communicate with server: Post "http://localhost/v2/snapctl": read unix @->/run/snapd-snap.socket: read: connection reset by peer
> ....
> Jan 15 22:00:57 rpi5 nextcloud.apache[11672]: AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
> Jan 15 22:00:57 rpi5 systemd[1]: snap.nextcloud.apache.service: Deactivated successfully.
> ```
> 
> log error messages:
> 
> > No certificates are active: using HTTP only
> 
> * enable HTTPS encryption? See [Configuration](https://github.com/nextcloud-snap/nextcloud-snap/wiki/configure-Nextcloud-snap) first section [enable HTTPS encryption with Lets Encrypt](https://github.com/nextcloud-snap/nextcloud-snap/wiki/configure-Nextcloud-snap#enable-https-encryption-with-lets-encrypt)
>   
>   * that should resolve the logging in issue
> 
> > Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
> 
> * you may want to check out [hosts & FQDN configuration](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Hosts-and-FQDN-for-Nextcloud-snap) to resolve the second recurring log message. See [here for your setup](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Hosts-and-FQDN-for-Nextcloud-snap#fqdn-for-nextcloud-snap-on-internet-facing-instance)
>   
>   * this is optional but recommended

hey there

I use a reverse-proxy.
the issue also occurs when setting it up direclty wiht the builtin letsencrypt without the reverse-proxy.

**Comment by scubamuc** [comment]
thanks for that info... double check [proxy manager handle encryption](https://github.com/nextcloud-snap/nextcloud-snap/wiki/NGINX-proxy-manager) see [last section](https://github.com/nextcloud-snap/nextcloud-snap/wiki/NGINX-proxy-manager#advanced-settings-for-nextcloud-snap)

**Comment by scubamuc** [comment]
@ne0YT, on a personal note, I'm interested to see your script. is there any chance you could upload it to your github so that I could have a look see?

I've put mine [here](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Develop-and-contribute#setup-testing-instance-per-script-optional) so you might want to compare.

**Comment by scubamuc** [comment]
no problem, glad I cloud help
