### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes

### ISSUE THREAD

**Issue by fcmircea** [nextcloud-snap/nextcloud-snap#2651]
#### Describe the bug
snap.fixer service keeps failing complaining about missing indices

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t
Jan 17 01:36:55 hal9002 nextcloud.nextcloud-fixer[1512969]:   oo long; max key length is 3072 bytes

#### To Reproduce
None, nextcloud seems to be working fine.

#### Expected behavior
Systemlog is clear of errors related to nextcloud

#### OS/snapd/snap version
See attached file.
[nextcloud.log](https://github.com/nextcloud-snap/nextcloud-snap/files/13956764/nextcloud.log)

#### Logs
See attached file.

**Comment by scubamuc** [comment]
your error log:

```
Jan 17 01:36:58 hal9002 nextcloud.nextcloud-fixer[1514910]: Adding additional mail_messages_msgid_idx index to the oc_mail_messages table, this can take some time...
Jan 17 01:36:58 hal9002 nextcloud.nextcloud-fixer[1514910]: In ExceptionConverter.php line 119:
Jan 17 01:36:58 hal9002 nextcloud.nextcloud-fixer[1514910]:   An exception occurred while executing a query: SQLSTATE[42000]: Syntax erro
Jan 17 01:36:58 hal9002 nextcloud.nextcloud-fixer[1514910]:   r or access violation: 1071 Specified key was too long; max key length is 3
Jan 17 01:36:58 hal9002 nextcloud.nextcloud-fixer[1514910]:   072 bytes
Jan 17 01:36:58 hal9002 nextcloud.nextcloud-fixer[1514910]: In Exception.php line 30:
Jan 17 01:36:58 hal9002 nextcloud.nextcloud-fixer[1514910]:   SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t
Jan 17 01:36:58 hal9002 nextcloud.nextcloud-fixer[1514910]:   oo long; max key length is 3072 bytes
Jan 17 01:36:58 hal9002 nextcloud.nextcloud-fixer[1514910]: In Connection.php line 72:
Jan 17 01:36:58 hal9002 nextcloud.nextcloud-fixer[1514910]:   SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t
Jan 17 01:36:58 hal9002 nextcloud.nextcloud-fixer[1514910]:   oo long; max key length is 3072 bytes
Jan 17 01:36:58 hal9002 nextcloud.nextcloud-fixer[1514910]: db:add-missing-indices [--dry-run]
```
is referring to this [issue](https://docs.nextcloud.com/server/latest/admin_manual/configuration_database/mysql_4byte_support.html): 

![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/c48a287c-1ded-4e18-8a29-0d04c659b5c4)

But I'm sure this should be managed by the snap without user action required.

@kyrofa could you shed some light please?

**Comment by scubamuc** [comment]
adding reference #2491

**Comment by scubamuc** [comment]
It looks like you are having an issue with the Mail app. 

Feel free to open an issue at the mail repo @christiansacks https://github.com/nextcloud/mail

**Comment by scubamuc** [comment]
see Wiki [OCC management console](https://github.com/nextcloud-snap/nextcloud-snap/wiki/OCC-management-console)
try issuing the command on host:
```
sudo nextcloud.occ db:add-missing-indices
```
and
```
sudo nextcloud.occ db:convert-mysql-charset
```
