### ISSUE TITLE
[NC28] Configure maintenance time for daily resource intensive background jobs

### ISSUE THREAD

**Issue by Pilzinsel64** [nextcloud-snap/nextcloud-snap#2658]
![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/23138465/8e6316ef-34c7-4e85-ae60-588050523ad8)

Config to add ("1" stands for the first hour of the day, so 1 a.m.):

    'maintenance_window_start' => 1

Ref: https://docs.nextcloud.com/server/28/admin_manual/configuration_server/background_jobs_configuration.html#maintenance-window-start

**Comment by scubamuc** [comment]
added to wiki documentation
https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-config.php#setting-default-maintenance-window

**Comment by user8446** [comment]
Just adding that this is in UTC time according to the docs.

**Comment by scubamuc** [comment]
@user8446 added to [FAQ](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-how-can-i-set-default-maintenance-window-in-nextcloud-snap)
