### ISSUE TITLE
Build Failure: Virtual Memory Exhausted During MySQL Compilation in Nextcloud Snap

### ISSUE THREAD

**Issue by kaklik** [nextcloud-snap/nextcloud-snap#2660]
During the snap building process of Nextcloud using Snapcraft, the build fails at the MySQL compilation stage. The error virtual memory exhausted: Cannot allocate memory occurs when compiling the sql_gis target, indicating a possible memory allocation issue.
Environment:

  * Host Operating System: Ubuntu 22.04.3 LTS
  * Snapcraft Version: snapcraft 7.5.4
  * Multipass Version: multipass   1.13.0

Steps to Reproduce:

  1. Clone the Nextcloud Snap repository: git clone git@github.com:nextcloud-snap/nextcloud-snap.git
  1. Navigate to the cloned directory: cd nextcloud-snap
  1. Run Snapcraft to build the snap: snapcraft

Expected Behavior:

The snap should build without errors, successfully compiling all components including MySQL.
Actual Behavior:

The build process fails at 88% completion during the MySQL compilation. The specific error messages look like this:

```
[ 88%] Building CXX object sql/CMakeFiles/sql_gis.dir/gis/crosses.cc.o
virtual memory exhausted: Cannot allocate memory
sql/CMakeFiles/sql_gis.dir/build.make:86: recipe for target 'sql/CMakeFiles/sql_gis.dir/gis/buffer.cc.o' failed
make[2]: *** [sql/CMakeFiles/sql_gis.dir/gis/buffer.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:14206: recipe for target 'sql/CMakeFiles/sql_gis.dir/all' failed
make[1]: *** [sql/CMakeFiles/sql_gis.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

```

```
[ 88%] Building CXX object sql/CMakeFiles/sql_gis.dir/gis/difference_functor.cc.o
virtual memory exhausted: Cannot allocate memory
sql/CMakeFiles/sql_gis.dir/build.make:182: recipe for target 'sql/CMakeFiles/sql_gis.dir/gis/difference_functor.cc.o' failed
make[2]: *** [sql/CMakeFiles/sql_gis.dir/gis/difference_functor.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:14206: recipe for target 'sql/CMakeFiles/sql_gis.dir/all' failed
make[1]: *** [sql/CMakeFiles/sql_gis.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
```

Troubleshooting Steps Taken:

  *  Checked system resources to ensure sufficient memory was available.
  *  Attempted to increase the memory allocation for the Multipass VM  using multipass launch --name snapcraft-nextcloud --memory 8G.
  *  Attempt to examine the GitHub Actions script to explain why it passes seamlessly. But there I did not find any configuration affecting the size of memory in use.

**Comment by pachulo** [comment]
I guess you should have some swap partition/file if you are gonna do this with 8GB or RAM.

**Comment by kyrofa** [comment]
@pachulo is right, you need a sort of ridiculous amount of RAM to build MySQL. I'm not actually sure how much the GitHub runners give us, to be honest, but we haven't had an issue there. Definitely had problems in this area in the past, though.

**Comment by kaklik** [comment]
Ok, but I had a machine with physically 32GB of RAM and the issue persists. The problem is that snapcraft always creates the VM with only 2GB of RAM and I have not found a solution how to avoid that (by using configuration from this repository).

**Comment by kyrofa** [comment]
That sounds like a snapcraft bug. I personally don't use the lxd backend instead of multipass.

**Comment by kaklik** [comment]
> That sounds like a snapcraft bug. I personally use the lxd backend instead of multipass, which doesn't have those kinds of limitations. I'm not really sure what knobs snapcraft exposes these days to make that VM usable.

Perfect! Thanks for the suggestion. The use of `snapcraft --use-lxd` solves the issue. Unfortunately the multipass is used by default for snapcraft without parameters.

**Comment by kyrofa** [comment]
Yeah, Snapcraft was required to use Multipass as the default backend for political reasons (a straight ask from Mark, hoping that it would make Multipass more popular). It works for simple cases, but anything more complex and it really gets in the way. The Snapcraft devs have maintained the LXD backend as a first-class citizen knowing that a significant number of people would use it instead.
