### ISSUE TITLE
Error on mail app after update to 3.5.0

### ISSUE THREAD

**Issue by negativesymptomatic** [nextcloud-snap/nextcloud-snap#2675]
#### Describe the bug
On Dec 2023 the Mail app has been updated causing a lot of problems of connections error to the mailservers.

The only one solution that i've found related to this update is to update the NC version to the 27.

See more at: https://help.nextcloud.com/t/mail-app-not-connecting-after-update/176599

#### To Reproduce
Update the mail app in a NC 26 version and it won't work anymore

#### Expected behavior
I'm the the NC27.1.4 and it doesn't work also, does anyone have the same issue as me?

**Comment by scubamuc** [comment]
welcome and thanks for your request. See [getting help](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Getting-help)

- what errors are you seeing?
- what doesn't work?

this is most probably an app issue. see [FAQ's](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-nextcloud-snap-is-not-working-because-of-third-party-app-incompatibility-what-can-i-do)

**Comment by negativesymptomatic** [comment]
Hi scuba, yes it's probably an app issue because the same problem has happened in 2 of the 5 istances that i have.
I'm going to uninstall the mail app and delete all the configs of them, then reinstall them and see what happens

**Comment by scubamuc** [comment]
Hi @negativesymptomatic, that sounds good. 

Take a look at [Snappymail](https://apps.nextcloud.com/apps/snappymail) that may be an alternative.

I'll close this then...

**Comment by negativesymptomatic** [comment]
Bro that's a beautiful app, is that stable enough to use in production?

**Comment by scubamuc** [comment]
@negativesymptomatic, yip its a great app... been using it for ages. I started out using Rainloop and migrated to Snappymail when Rainloop died. Great support on https://github.com/the-djmaze/snappymail and a great community.
