### ISSUE TITLE
[BROKEN TRASH BIN] Upgrade Nextcloud to 27.1.7 (Once released)

### ISSUE THREAD

**Issue by AMDBartek** [nextcloud-snap/nextcloud-snap#2678]
https://github.com/nextcloud/server/pull/43259

https://nextcloud.com/changelog/

**Comment by user8446** [comment]
Just adding that the files are visible in the mobile app deleted files if someone needs to restore a file in the meantime.

**Comment by scubamuc** [comment]
@AMDBartek thanks for mentioning that. I'm seeing this in **27.1.6** too...

> files are visible in the mobile app deleted files 

@user8446 thank, thats a great tip...

I've added a cron job as root to clean trash out for all users once a week for the time being, until the issue is solved upstream

```
 0 0 * * 0 nextcloud.occ trashbin:cleanup --all-users
```

**Comment by scubamuc** [comment]
> Hi, Just making sure you know that force deletes everything in trash overriding the [retention policy](https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/trashbin_configuration.html).
> 
> If anyone just wants to delete trash according to the retention policy, use sudo nextcloud.occ trashbin:expire.

@user8446 great, thanks for pointing that out!
