### ISSUE TITLE
Is there a way to boost the speed and lower the weight on access devices?

### ISSUE THREAD

**Issue by alfi4000** [nextcloud-snap/nextcloud-snap#2682]
I have the problem that the more files I upload the more the user device the device that is accessing the Nextcloud instance that it looks like it loads the hole stuff the same in emails I would like to boost it up and lower the heavy for access devices like google drive!

Server that I have:
DELL power edge r730xd
Ram: 256gb
HDD Total: 12tb
24 core
Current nextcloud instance load: closely 400gb

If need additional information let me know I really need to speed this thing up because I want to add in the next few days 1.5tb of data because I want to clean up my bad that we're very slow!

I would be happy if someone can help me walk trough that! :)thanks for any advice!!!

**Comment by scubamuc** [comment]
- Please show active users? (administrative settings -> system -> Active users)
- Please show active users during performance issues? (administrative settings -> system -> Active users)
  
![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/35b51e40-c686-4e0d-8775-1cb8eafd0fa7)

- Which clients are being used?
  - Browser 
  - Nextcloud app
  - Android
  - IOS
- Are you talking about files synchronising or only files uploading?
- Please show your PHP memory limit setting (administrative settings -> system -> PHP)
  
![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/6b3c3259-2017-4ad2-8045-dd5c5d2e0325)

**Comment by alfi4000** [comment]
I want that the Content loads faster when I access it from the browser Media and Mails because it is sometimes very slow and like you can see in the video the nextcloud dashboard crashes in some kind when I upload a bunch of files!:

<img width="1046" alt="Bildschirmfoto 2024-02-13 um 21 10 59" src="https://github.com/nextcloud-snap/nextcloud-snap/assets/149228038/16367df1-1f5f-4915-b1dd-4b95a06c932f">
<img width="1047" alt="Bildschirmfoto 2024-02-13 um 21 10 48" src="https://github.com/nextcloud-snap/nextcloud-snap/assets/149228038/342c67df-1b43-400e-9d9e-1fbd220f8c83">

https://youtu.be/N6HCmIYDYww

https://youtu.be/jUZLJeerT4s

https://youtu.be/SI38H3qpjyY

https://youtu.be/h_Swq2nAN1Y

you not need to watch the hole videos but try to understand what I mean when you ee the screen recordings and when I recorded the videos it were better then usually the performance!! Often the videos need long to load and on one android devices like an Alexa the loading took over 1min 30sec the nextcloud dashboard loading!

Just that you are not wondering why there are several name I help some friends to manage their websites and those email addresses are the one where security mails and such stuff comes to!

**Comment by alfi4000** [comment]
I user Browser to Access Just to tell it clearly!

**Comment by scubamuc** [comment]
@alfi4000, there is nothing wrong with your system settings as far as I can tell from the screenshots.

in your video clips it seems like the mail app is on the slow side. but that isn't something you can change by tuning the system. as mentioned before, try a different mail app like Snappymail and see if that works better for you.

as for the photo uploads, this may depend on your internet connection, photo file size etc. ... but judging by your system specs, you'll have superb bandwidth too?

I'm not a sysadmin nor a developer, but honestly there is nothing I can think of to speed up your system. It would be great to compare what you're seeing to a different install, just so we could see if it has anything to do with the snap?

**Comment by scubamuc** [comment]
@alfi4000 ...come to think of it, could you list your apps please? judging by your server name and the 3rd party issue you've had recently, I have the suspicion that you may be running some sort of AI app that is trying to scan your data locally.

Please list your apps by issuing command on the host:
```
sudo nextcloud.occ app:list
```

**Comment by alfi4000** [comment]
<img width="622" alt="Bildschirmfoto 2024-02-13 um 23 04 27" src="https://github.com/nextcloud-snap/nextcloud-snap/assets/149228038/24079cb9-b873-4df4-be47-2b6a76faead9">
here

**Comment by scubamuc** [comment]
@alfi4000 so there are some apps installed... but nothing really troublesome that meets the eye. the only app that could be scanning files locally is the `files_antivirus` app as far as I can tell. Try disabling that and see if it speeds up things:

``` 
sudo nextcloud.occ app:disable files_antivirus
```

the reason being, that usually antivirus on linux depends on ClamAV which needs to be installed on the host. Now due to [confinement](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-explain-snap-confinement) there is no way for the snap to access ClamAV on the host and vice versa leading to failure for every file that needs to be scanned... which would be every file that's uploaded. hence your issues upon uploading files.

maybe @Pilzinsel64 could have a look if he sees anything else that may be suspicious?

-- side note --

if you don't have [CODE & Nextcloud Office](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-CODE-and-Nextcloud-office-for-Nextcloud-snap) configured at all then you may as well remove `richdocuments` too:

```
sudo nextcloud.occ app:disable richdocuments
```

**Comment by alfi4000** [comment]
I use files_antivirus but it only scans files before they get uploaded but disabling doesn't improve the performance! But suddenly toady it stoped working or maybe since the recent! idk 
And sudo nextcloud.occ app:disable richdocuments        code & Nextcloud office either not improve the performance when I disable them any suggests?

**Comment by alfi4000** [comment]
I already set something higher that speeded something up I just can't remember what I changed I think ram (memory limit) but not sure what it improved its a few months ago! I think it were file loading speed it improved, but I am not sure too long ago!

**Comment by alfi4000** [comment]
This had let me think:

https://github.com/nextcloud-snap/nextcloud-snap/issues/1822#issuecomment-916916528

Why does the NC uses the client cpu should it not use the servers one so that it performs the best!? I know when I transfer files that cpu on the client will be used for transfer process but for mail loading and so on should it not use the server cpus? Or have I got something wrong?!

**Comment by scubamuc** [comment]
> any other way to improve loading speed and so o with more ram or so?

nope, your ram is more than sufficient, I'd say its totally overkill 👌

> I already set something higher that speeded something up I just can't remember what I changed I think ram (memory limit) but not sure what it improved its a few months ago! I think it were file loading speed it improved, but I am not sure too long ago!

that may have been your [PHP memory limit](https://github.com/nextcloud-snap/nextcloud-snap/wiki/configure-Nextcloud-snap#php-memory-limit-configuration) which can make a difference when you have many users and clients connected. I'm not sure if 10GB is overkill on your system with 1 user? My corporate instance with similar system specs has +120 users maxing out at 30 - 40 users during office hours... and is set to 2GB. I've never had complaints.

**Comment by alfi4000** [comment]
Is there maybe any way to remove the load from the client device I unsure if it is maybe my Mac! I maybe need to try tomorrow some other devices but with the mail loading I am sure that is a nextcloud problem that it loads them very slow I had used it today on several device to access the mails fast and on every device it loaded very slow and like in the video I had to wait until it loaded the next ones!

**Comment by Pilzinsel64** [comment]
Looking at your videos...
- The upload seems to be fine. Each photo has a few megabyte and Nextcloud usually uploads every single file doesn't that in parallel (yet, bulk upload was introduced already but not sure where and when it should work currently).
- Looking on a photo is very slow for you. Well, it normally takes a few seconds if you recently uploaded the video. The "previews" of the photo are not generated yet and needs a lot of resources on the server. Q: Does it load faster if you load a photo once, then close it and open it again?
- The performance of the mail app seems to be fine while scrolling. There is nothing I would worry about. The mails do load on demand when you scroll down. But it very slow on switching the mailboxes. The first time I would understand that but not if this happens again and again.

> Why does the NC uses the client cpu should it not use the servers one so that it performs the best!?

The client needs to calculate a checksum for each single file and even for each single chunk it does upload. The client just has todo some calculation. Shouldn't be too havy but yea, it's more then nothing.
The server then needs to do the same reverse and also access the storage drive. It also add some entries to the database and update some others. Again, checksum calculation is done here too.

However, there is another few things I have in mind that you could check at least.
1. Do you have a reverse proxy between your nextcloud and the internet / the clients?
2. What is the content of your `/etc/hosts` file?
3. Do you have [http compression](https://github.com/nextcloud-snap/nextcloud-snap#http-compression-configuration) enabled?
4. What is your debug level? Set the set to production mode via `sudo snap set nextcloud mode=debug` and set Nextclouds log level to warning via `sudo nextcloud.occ config:system:set log_level 2`

**Comment by kyrofa** [comment]
> DELL power edge r730xd
> Ram: 256gb
> HDD Total: 12tb
> 24 core

_whistle_. Can you confirm you have the snap installed on bare metal? Or is it within a VM or LXC container, or something similar?

**Comment by alfi4000** [comment]
Spinning disks but very fast ones it writes 40mb sec

**Comment by Pilzinsel64** [comment]
> Spinning disks but very fast ones it writes 40mb sec.

They still have a reaction time, like when they leave its standby mode. And if you access many minor files (and yes, that happens on each access to the website as some js and ohter files are located in the appdata folder of Nextcloud's data directory) HDDs need some time to move it's reader to the right position.

I have a 4 TB SSD (normal one, not a special one for NAS or Gaming) as primary data storage and a 4 TB HDD as backup storage. Since I have that SSD the general performance of my cloud instance has increased a lot.

@alfi4000 Do you have a reverse proxy between the Nextcloud server and the clients?

**Comment by alfi4000** [comment]
@Pilzinsel64 

1. do you mean in nextcloud the function reverse proxy or the router between client and server?
2. Some Ai stuff but those things are not active just some files!
3. No I haven't!
4. sudo nextcloud.occ config:system:set log_level 2
System config value log_level => 2 set to empty string

**Comment by alfi4000** [comment]
@Pilzinsel64 
Oh I didn't know that there is a difference between those storage just that ssd is faster then HDD and NVMe faster then SSD and HDD!

**Comment by alfi4000** [comment]
@Pilzinsel64 
Shloud I use reverse proxy I have done I web search it says a reverse proxy is for more security and better performance for the client!?

**Comment by kyrofa** [comment]
>  Shloud I use reverse proxy I have done I web search it says a reverse proxy is for more security and better performance for the client!?

No, @Pilzinsel64 is just trying to get a handle on your setup is all. You don't need one, but it could (negatively) impact performance.

**Comment by alfi4000** [comment]
i am getting crazy now nextcloud just load and load audio and video files but I cant play them I get crazy!

**Comment by alfi4000** [comment]
oh ok @kyrofa

**Comment by scubamuc** [comment]
@alfi4000 try dropping your video file [here](https://ycloud.scubamuc.dedyn.io/index.php/s/6SGXqrWPiSt7XL4) compare upload speed... take note. Then view the file.

**Comment by scubamuc** [comment]
@alfi4000 view your video file [here](https://ycloud.scubamuc.dedyn.io/index.php/s/mWDXCPJ7nT6Dy5s) compare download speed, take note.

**Comment by alfi4000** [comment]
@scubamuc 
I uploaded a test video so all the same speed is slower then mine but its different server and also over the internet its might be a bit slower so all the same just I can't play the video when I uploaded it !

**Comment by scubamuc** [comment]
@alfi4000 yeah, I can view video 5.mov without issues... in that case it may well be a client issue:
![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/8b10a942-49bc-46ff-a207-13ef02705d45)

**Comment by alfi4000** [comment]
Yeah I found the issue when I tried to do a internet speed test because I tried to upload a short video then it started to load the video look at this insane :/ : 
<img width="1381" alt="Bildschirmfoto 2024-02-14 um 13 01 16" src="https://github.com/nextcloud-snap/nextcloud-snap/assets/149228038/0dc14522-430b-4351-8a17-0d8427cc1004">

Something is wrong with my client device!

**Comment by scubamuc** [comment]
simple html5 [speedtest](https://openspeedtest.com)

**Comment by alfi4000** [comment]
Thanks the connection is very unstable I have seen and the computer has some problems I need to fix that wasn't normal that he has started to operate when I tried to do a speed test maybe something does things what it shouldn't!

**Comment by alfi4000** [comment]
I have to check what is running in the background!

**Comment by alfi4000** [comment]
Hhm all looks good I'll have a look on it the next few days! But now everything works ok!

**Comment by alfi4000** [comment]
But is there not a way to boost the mail loading in my opinion it could be a way faster! or is that normal with cron jobs (I am unfamiliar with cron jobs I just know them from wordpress!)?

**Comment by scubamuc** [comment]
@alfi4000 you should definitely enable HTTPS encryption. That will speed up things considerably, especially with [http compression](https://github.com/nextcloud-snap/nextcloud-snap#http-compression-configuration)

see your follow up issue  #2683

so I'll go ahead and close this then...

**Comment by alfi4000** [comment]
Ok thanks to you all guys how helped me!!!
