### ISSUE TITLE
how to show upload speed 

### ISSUE THREAD

**Issue by 666damn** [nextcloud-snap/nextcloud-snap#2687]
Hi, I searched for answers, and I see if they build with docker or just normal apache they have a file called file-upload.js which can add to show the upload speed. But with snap, I can't find this file

**Comment by 666damn** [comment]
and what's the way to config max_chunk_size

**Comment by scubamuc** [comment]
Welcome and thanks for your request.

> ... to show the upload speed. But with snap...

Do you mean something like this while uploading files? 

![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/4a2b9708-9f97-4911-a5ad-bea4fff7f40c)

It will show you the approximate time left before your upload is completed and is included in the default Nextcloud installation. 

If you want to see upload speed as in MB/s then you'll need external tools. I believe upload speed is displayed when uploading files via the Nextcloud Desktop app.

----

> what's the way to config max_chunk_size

Do you mean the maximum upload size?

![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/b4c43e09-1695-4d7c-801d-c7fa80635806)

That is preconfigured in the snap.

**Comment by scubamuc** [comment]
> searched on google and some solutions are just to change max_chunk_size to unlimited.

@666damn, where does Google suggest you change the `max_chunk_size` value?

See [PHP configuration](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-config.php)

**Comment by 666damn** [comment]
https://help.nextcloud.com/t/file-upload-stuck-at-max-chunk-size/157340/6

**Comment by 666damn** [comment]
https://help.nextcloud.com/t/can-i-display-the-actual-upload-speed-in-the-web-interface/10224/8
and here for show the upload speed

**Comment by 666damn** [comment]
I downloaded the desktop app, but it's just transfer me to the chrome and to my website, it doesn't display the upload speed

**Comment by scubamuc** [comment]
> https://help.nextcloud.com/t/can-i-display-the-actual-upload-speed-in-the-web-interface/10224/8
and here for show the upload speed

this is not possible in the snap

**Comment by 666damn** [comment]
Alright, so is there any way to show or we can't see the speed

**Comment by scubamuc** [comment]
so according to this https://help.nextcloud.com/t/how-to-show-upload-speed-in-nextcloud-26-27/166988 its an upstream issue and certainly nothing we can change in the snap.

**Comment by scubamuc** [comment]
so I've double checked... according to the description above, the upload speed is displayed upon mouseover within the bottom 3 (three) pixels:

![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/5915ee1f-9941-4614-b72d-eb9d310590db)
