### ISSUE TITLE
PHP OPcache performance tuning to benefit the Nextcloud snap

### ISSUE THREAD

**Issue by user8446** [nextcloud-snap/nextcloud-snap#2698]
Hi,

According to the [official Nextcloud server tuning](https://docs.nextcloud.com/server/latest/admin_manual/installation/server_tuning.html) docs, there is a [JIT compiler](https://php.watch/versions/8.0/jit#jit-flags) that can be enabled that will benefit apps that are CPU intensive simply by adding it to `php.ini`:

```
opcache.jit = 1255
opcache.jit_buffer_size = 128M
```

Would a PR be entertained?

Also, there is `opcache.revalidate_freq=2` - checking for changes to `config.php` every 2 seconds by default. The docs mention this should be increased for performance benefits. Checking every 2 seconds is excessive and a waste of resources.

This value should be user configurable like the PHP memory limit is in `php.ini` ( `memory_limit = ${PHP_MEMORY_LIMIT}` ).

`opcache.revalidate_freq = ${OPCACHE_REVALIDATE_FREQ}` is easy enough in `php.ini` but I need help to get it exposed to make it configurable (ex. `sudo snap set nextcloud php.revalidate-freq=60` )

**Comment by pachulo** [comment]
Hi @user8446 ! First of all, thanks for your contribution!

Now, some comments:
> According to the [official Nextcloud server tuning](https://docs.nextcloud.com/server/latest/admin_manual/installation/server_tuning.html) docs, there is a [JIT compiler](https://php.watch/versions/8.0/jit#jit-flags) that can be enabled that will benefit apps that are CPU intensive simply by adding it to php.ini:

From [this comment](https://github.com/nextcloud/documentation/pull/9230#issuecomment-1289566661) from the PR that added that to the docs, nobody run benchmarks to see if JIT really improved the performance; literally:
> I don't have the time to do benchmarks, but my best guess is it's not gonna be slower :)

But well, I'm not an expert and not even really sure how those benchmarks should be really done. Maybe @oparoz could help?

Regarding your second proposal:
> Also, there is opcache.revalidate_freq=2 - checking for changes to config.php every 2 seconds by default. The docs mention this should be increased for performance benefits. Checking every 2 seconds is excessive and a waste of resources.

Sounds like something that could be exposed as a config value, but again, I would like to see some benchmarkings to see if there is any real improvement.

Thoughts @kyrofa ?

**Comment by kyrofa** [comment]
> The docs mention this should be increased for performance benefits.

`revalidate_freq` cannot be zero, because it's the only way `config.php` changes are picked up (one of the many reasons why I'd wish they'd move to some other kind of config). So then, what should it be? The docs don't actually say, as far as I can tell. They give 60 seconds as an example, but that's a pretty long time to wait from when you make a config change to when it takes effect. Is 2 seconds too short? Maybe. I'm not sure there's a reason to add and maintain a knob for it, though: everyone will want maximum performance with minimum annoyance. Is there a more reasonable value that will work for everyone?

**Comment by pachulo** [comment]
`60` is used on these two flavours of "packaged nextcloud":
1. [Docker](https://github.com/nextcloud/docker/blob/6151f60208d08fe7dbd28b6b00a3bcd1e626e7ff/27/fpm/Dockerfile#L103)
2. [all-in-one](https://github.com/nextcloud/all-in-one/blob/257b9217f8e7e04a28aa48da2e4dc22d4f3c03a4/Containers/nextcloud/Dockerfile#L105)

But then, it's set to `1` on:
1. [VM](https://github.com/nextcloud/vm/blob/669164ac7b6a3a79c0506059c4f5e27b47b0722a/nextcloud_install_production.sh#L701) (But that was configured [almost 7 years ago](https://github.com/nextcloud/vm/pull/225))

**Comment by user8446** [comment]
Ok I found some benchmarks for tracing JIT from PHP themselves: https://php.watch/articles/jit-in-depth
Approx. twice as fast on average.

Tracing JIT is the [same method Android uses](https://source.android.com/docs/core/runtime/jit-compiler) in ART, where it determines the "hot" code to "selectively compiles those structures for the best balance of compilation time and memory usage."

With just one line in php.ini it's active: 
`opcache.jit_buffer_size = 128M`

As for `revalidate_freq`, for every user where resources and power consumption are top of mind, there is another where only performance matters - hence my thought on having it user configurable with a reasonable default for those that don't dig into the config.
