### ISSUE TITLE
Upgrade to 27.1.8 to fix "Enforce password protection" bug

### ISSUE THREAD

**Issue by TheRealEscimo** [nextcloud-snap/nextcloud-snap#2701]
#### Describe the bug
(https://github.com/nextcloud/server/issues/44269)
If you create an share with "Enforce password protection", the share creation fails with the error:
"Error creating the share: Passwords are enforced for link and mail shares"

#### To Reproduce
Enable "Enforce password protection" and email sharing fails unless you manually change the password during share creation.

#### Expected behavior
The password should be autogenerated and pre-filled, the share should be created and the password should be sent per email to the initiator, recipient, none or both depending on the settings. 

#### OS/snapd/snap version

    $ snap list nextcloud

Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  27.1.7snap1  40887  latest/stable  nextcloud✓  -

    $ snap version

snap    2.61.2
snapd   2.61.2
series  16
ubuntu  22.04
kernel  5.15.0-97-generic

**Comment by pachulo** [comment]
Hi @TheRealEscimo! Honest question:
* What do you expect for us to do with these issues (apart from waiting for the nextcloud stable release that fixes them)?

I mean, we are a nextcloud downstream project, and we never monkey-patch upstream bugs, even those that impact nextcloud when run inside snapd sandbox....

**Comment by TheRealEscimo** [comment]
Oops, my thick thumb managed to hit close.
You are right @pachulo, not a lot that can be done except implement the fixed version.

I might be wrong, but I thought I had observed that sometimes minor releases haven’t been taken downstream at all?
We have hundreds of users affected and I just wanted to make sure you guys were aware of this bug.

**Comment by scubamuc** [comment]
@TheRealEscimo, thanks for the heads up

**Comment by pachulo** [comment]
Hi again @TheRealEscimo 

First, as @scubamuc said, thanks for taking the time to report things and making the nextcloud snap better for everyone!

> I might be wrong, but I thought I had observed that sometimes minor releases haven’t been taken downstream at all?

That should only be the case for minor releases that break when run into the snap sandbox or for old branches, like for example `26` now, where our support is not the greatest due to lack of resources.

> We have hundreds of users affected and I just wanted to make sure you guys were aware of this bug.

Another way to help would be to test if the releases on the corresponding `/edge` channel fixes the issue, one day or so after the fix is merged upstream, of course.

**Comment by TheRealEscimo** [comment]
@pachulo 
> Another way to help would be to test if the releases on the corresponding `/edge` channel fixes the issue, one day or so after the fix is merged upstream, of course.

I would do this, but not sure what happens if I do this in a prod environment? Is there an easy rollback whilst preserving user data and config? We are of course running this in a VM, so we can snapshot and revert if a snap revert would fail. How would changing the channel affect config changes etc, and how would an revert back to stable affect it again?

**Comment by scubamuc** [comment]
@TheRealEscimo, we all appreciate you wanting to help... but would suggest not to touch prod instance.
> How would changing the channel affect config changes etc, 

don't swap channels on a prod instance. prefer to stay on stable channel. be safe.

if you're running in a VM then clone the VM and run another instance if you want to swap channels and test? 

> how would an revert back to stable affect it again?

see [managing Nextcloud snap with snap](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Managing-Nextcloud-snap-with-Snap) 

- backup your prod instance [Backup, Restore & Migrate](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Backup-and-Restore) be safe

- if you can't clone the VM [copy the snap to another machine](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Backup-and-Restore) for testing/experimenting
