### ISSUE TITLE
Curl errors now showing up in the logs

### ISSUE THREAD

**Issue by michmoor0725** [nextcloud-snap/nextcloud-snap#2721]
#### Describe the bug
This is flooding my  nextcloud logs

`[richdocuments] Error: GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to nc.networkingtitan.com port 80: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://nc.networkingtitan.com/extra-apps/richdocumentscode/proxy.php?req=/hosting/capabilities at <<closure>>

 0. /snap/nextcloud/41512/htdocs/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php line 158
    GuzzleHttp\Handler\CurlFactory::createRejection("*** sensitive parameters replaced ***")
 1. /snap/nextcloud/41512/htdocs/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php line 110
    GuzzleHttp\Handler\CurlFactory::finishError()
 2. /snap/nextcloud/41512/htdocs/3rdparty/guzzlehttp/guzzle/src/Handler/CurlHandler.php line 47
    GuzzleHttp\Handler\CurlFactory::finish()
 3. /snap/nextcloud/41512/htdocs/3rdparty/guzzlehttp/guzzle/src/Middleware.php line 137
    GuzzleHttp\Handler\CurlHandler->__invoke()
 4. /snap/nextcloud/41512/htdocs/lib/private/Http/Client/DnsPinMiddleware.php line 114
    GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensitive parameters replaced ***")
 5. /snap/nextcloud/41512/htdocs/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php line 35
    OC\Http\Client\DnsPinMiddleware->OC\Http\Client\{closure}("*** sensitive parameters replaced ***")
 6. /snap/nextcloud/41512/htdocs/3rdparty/guzzlehttp/guzzle/src/Middleware.php line 31
    GuzzleHttp\PrepareBodyMiddleware->__invoke()
 7. /snap/nextcloud/41512/htdocs/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php line 71
    GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensitive parameters replaced ***")
 8. /snap/nextcloud/41512/htdocs/3rdparty/guzzlehttp/guzzle/src/Middleware.php line 63
    GuzzleHttp\RedirectMiddleware->__invoke()
 9. /snap/nextcloud/41512/htdocs/3rdparty/guzzlehttp/guzzle/src/HandlerStack.php line 75
    GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensitive parameters replaced ***")
10. /snap/nextcloud/41512/htdocs/3rdparty/guzzlehttp/guzzle/src/Client.php line 331
    GuzzleHttp\HandlerStack->__invoke()
11. /snap/nextcloud/41512/htdocs/3rdparty/guzzlehttp/guzzle/src/Client.php line 168
    GuzzleHttp\Client->transfer()
12. /snap/nextcloud/41512/htdocs/3rdparty/guzzlehttp/guzzle/src/Client.php line 187
    GuzzleHttp\Client->requestAsync("*** sensitive parameters replaced ***")
13. /snap/nextcloud/41512/htdocs/lib/private/Http/Client/Client.php line 230
    GuzzleHttp\Client->request()
[output.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/15018691/output.txt)

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud
` snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  27.1.8snap1  41512  latest/stable  nextcloud✓  -
`
and:

    $ snap version
` snap version
snap    2.62
snapd   2.62
series  16
ubuntu  22.04
kernel  5.15.0-101-generic
`
#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).

Logs added as an attachmeent

**Comment by scubamuc** [comment]
welcome @michmoor0725 and thank you for your request.

> [richdocuments] Error: GuzzleHttp\Exception\ConnectException: cURL error 7

your issue is due to a third party app and seems to be related to CODE and Nextcloud office. Please refer to our wiki [CODE & Nextcloud Office configuration](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-CODE-and-Nextcloud-office-for-Nextcloud-snap) and double check your configuration.

in many cases, issues may be resolved by following [configure CODE](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-CODE-and-Nextcloud-office-for-Nextcloud-snap#5-configure-code) steps according to your architecture. you will need to ensure correct [FQDN configuration](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-CODE-and-Nextcloud-office-for-Nextcloud-snap#2-set-hostname-and-fqdn) taking reverse proxies into account.

see also what to do if third party apps are causing issues in [FAQ's](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-nextcloud-snap-is-not-working-because-of-third-party-app-incompatibility-what-can-i-do)

**Comment by michmoor0725** [comment]
Understood. I appreciate the very quick feedback.

**Comment by michmoor0725** [comment]
seeing how the only thing that changed was the recent update i rebooted the server but now i cant create any files. The messages appear in the log below


`[PHP] Error: disk_free_space(): Resource temporarily unavailable at /snap/nextcloud/41512/htdocs/lib/private/Files/Storage/Local.php#455

PROPFIND /remote.php/dav/files/michael/
from 192.168.50.241 by michael at 2024-04-18T16:48:05+00:00`

**Comment by scubamuc** [comment]
Hey @michmoor0725, this is a different issue. 

please open a new issue and don't forget to post your logs... see [getting help](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Getting-help#dont-panic)

**Comment by michmoor0725** [comment]
for me the solution was to standing up a separate Collabora server and pointing to that. Resolve the issues here.
Strange that this started happening. 
I will open another issue if the problem comes back or persists.
