### ISSUE TITLE
Update Nextcloud to 29

### ISSUE THREAD

**Issue by Pilzinsel64** [nextcloud-snap/nextcloud-snap#2724]
### Pending todos
- [x] Wait for 29.0.1 stable
- [x] https://github.com/nextcloud-snap/nextcloud-snap/issues/2641
- [x] Create branch [`28`](https://github.com/nextcloud-snap/nextcloud-snap/tree/28)
- [x] Create label [`28`](https://github.com/nextcloud-snap/nextcloud-snap/labels/28)

### Pending PRs
_None_

### Pending upstream issues
_None_

**Comment by pachulo** [comment]
How are your tests going @Pilzinsel64 & @scubamuc ? Do you have this running in any pro instance?

If everything looks fine, do you think we should already be pushing this to the `latest/stable` @kyrofa ?

**Comment by kyrofa** [comment]
Yeah if you're on a point release and it seems to be stable, let's ship it! We have a 29 channel ready to go?

**Comment by pachulo** [comment]
> We have a 29 channel ready to go?

@Pilzinsel64 [asked for one to be created](https://forum.snapcraft.io/t/track-29-for-nextcloud/40101), but I would say that we should now be able to create them on our own from now on! 🥳 
<img width="251" alt="image" src="https://github.com/nextcloud-snap/nextcloud-snap/assets/3256953/a56029b7-3409-4490-9073-1f1a15b572e3">

**Comment by scubamuc** [comment]
@pachulo, i have an 29.02 instance that I fire up on demand... not productive though. give me a shout if you need access.

**Comment by Pilzinsel64** [comment]
Yeah, everything looks fine on my side. We can create a stable release. My private prod works fine since we merged it.

**Comment by pachulo** [comment]
> Just had no time for a release pr or anything else, the past two weeks were full of trouble in my family. :/

Hope everything is fine now @Pilzinsel64 !
