### ISSUE TITLE
NEXTCLOUD VERSION - still 24 as per security scan of nextcloud

### ISSUE THREAD

**Issue by aquananu** [nextcloud-snap/nextcloud-snap#2730]
Running Snap nextcloud on Ubuntu 22.04.4 LTS
core 5.15.0-101-generic
Nextcloud Version
27.1.8
![image](https://github.com/nextcloud-snap/nextcloud-snap/assets/93096176/9ed36187-012d-437f-9047-f67820c5e0a8)

the results from scan.nextcloud.com

![image](https://github.com/nextcloud-snap/nextcloud-snap/assets/93096176/2a1d3e74-306b-4ece-8e2d-e12066b3c5e3)

kindly advise if the snap version has not been bumped up or there is somewhere version 24 left to be changed which is getting reported to nextcloud

**Comment by scubamuc** [comment]
Hi @aquananu welcome back,

the security warning/suggestion for "imagick" see [FAQ](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-nextcloud-snap-shows-security--setup-warnings-what-can-i-do). This issue has been around for ages and there are plenty threads describing the reasons why "imagick-php" is a security issue and will not be packaged in the snap. so this is one of those "its not a bug its a feature" things...

the incorrect version displayed on [Nextcloud security scan](https://scan.nextcloud.com/) is an issue of that site. the version in the snap is not visible to the outside world. I understand this information is "confined".

@kyrofa could you confirm security scan version issue?

**Comment by scubamuc** [comment]
@aquananu 

the security scan issue seem to be around for a while too see [here](https://help.nextcloud.com/t/latest-snappy-version-24-0-3snap1-but-nextcloud-security-scan-says-running-nextcloud-22-2-3-0/144957)

>... If you have previously scanned your TLD via that scan page, it shows cached data from previous scan by default. There is a button called Trigger Re-Scan → Try hitting that button, then wait for 10/15 mins to revisit that scan page to query your domain [02] Check if that is the issue here. …

**Comment by scubamuc** [comment]
Added this to [FAQ's](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-incorrect-version-displayed-on-nextcloud-security-scan) for future requests...
