### ISSUE TITLE
nextcloud-snap/wiki/Managing-services | error in text + suggestions

### ISSUE THREAD

**Issue by yannicklescure** [nextcloud-snap/nextcloud-snap#2736]
Hello,

I found an error in the text from the _nextcloud-snap/wiki/Managing-services_ page. I tried to pull and push the fix but it seems the wiki pages don't allow this process.

Here are the proposed changes + others that follow the markdown rule [MD040 - Fenced code blocks should have a language specified](https://github.com/DavidAnson/markdownlint/blob/v0.33.0/doc/md040.md):

![image](https://github.com/nextcloud-snap/nextcloud-snap/assets/40220809/013f8d7f-6b4b-4677-9539-e35e3e040053)

#### Markdown file including fixes 

[Managing-services.md](https://github.com/nextcloud-snap/nextcloud-snap/files/15201272/Managing-services.md)

### Suggestions

I've been using nextcloud-snap for a few months now and you guys did a very good job. I would like to suggest those 2 things:

1. Copying a backup of my phone camera pictures from one hdd to /var/snap/nextcloud/common/nextcloud/data/$USER/files I ran into the problem of having conflict when trying to backup new pictures from my phone camera. Until one day, I figured out that all files in this folder should have a root:root ownership. It should probably be mentioned on /nextcloud-snap/nextcloud-snap/wiki/Default-path wiki page.

2. I found that the front-end is very slow! It should probably worth it to test tunings shared on this article https://haefelfinger.ch/posts/2021/2021-03-29-nextcloud-tuning/ that was refered here https://help.nextcloud.com/t/web-interface-very-slow-bad-performance/152757/4

Thank you for your time.

**Comment by scubamuc** [comment]
@yannicklescure welcome and thanks for the heads up,

> I tried to pull and push the fix but it seems the wiki pages don't allow this process.

yeah... kind of defeats the wiki philosophy, but we've made that decision and we're quite happy with it.

> I found an error in the text from the nextcloud-snap/wiki/Managing-services page. 

changes to wiki done! (thanks and keep reading)

----

>1. Copying a backup of my phone camera pictures from one hdd to /var/snap/nextcloud/common/nextcloud/data/$USER/files I ran into the problem of having conflict when trying to backup new pictures from my phone camera. Until one day, I figured out that all files in this folder should have a root:root ownership. It should probably be mentioned on /nextcloud-snap/nextcloud-snap/wiki/Default-path wiki page.

would you agree that this is mentioned here: https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-what-permissions-should-external-media-have

----
>2. I found that the front-end is very slow! It should probably worth it to test tunings shared on this article https://haefelfinger.ch/posts/2021/2021-03-29-nextcloud-tuning/ that was refered here https://help.nextcloud.com/t/web-interface-very-slow-bad-performance/152757/4

as for your front-end issues, would it be possible to create a new issue for that? that is somethings the devs may want to look into... but, remember that we don't have any [upstream devs](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-why-is-nextcloud-snap-version-out-of-sync-with-upstream-nextcloud) in the snap team, so if its an upstream issue it should be handled upstream.

**Comment by scubamuc** [comment]
@yannicklescure
>I found that the front-end is very slow! 

could you please describe how your instance is setup and what are you comparing "front-end speeds" to?

-  is your instance self-hosted?
-  describe hardware specs of your instance (arch, RAM, CPU, OS)
-  describe your connectivity (asynchronous DSL, synchronous DSL, uplink, downlink etc.)

**Comment by pachulo** [comment]
Thanks for the suggestions @yannicklescure 

> I found that the front-end is very slow! 

Adding to what @scubamuc already asked: do you have [HTTP compression](https://github.com/nextcloud-snap/nextcloud-snap?tab=readme-ov-file#http-compression-configuration) enabled? It usually helps with this.

> It should probably worth it to test tunings shared on this article https://haefelfinger.ch/posts/2021/2021-03-29-nextcloud-tuning/ that was refered here https://help.nextcloud.com/t/web-interface-very-slow-bad-performance/152757/4

The thing with those kind of tunings is that they should be adapted for the hardware the snap is running on, not just hardcoded, so we would need to do some test when they make sense to apply.

**Comment by yannicklescure** [comment]
> @yannicklescure welcome and thanks for the heads up,
> 
> > I tried to pull and push the fix but it seems the wiki pages don't allow this process.
> 
> yeah... kind of defeats the wiki philosophy, but we've made that decision and we're quite happy with it.
> 
> > I found an error in the text from the nextcloud-snap/wiki/Managing-services page.
> 
> changes to wiki done! (thanks and keep reading)
> 
> > 1. Copying a backup of my phone camera pictures from one hdd to /var/snap/nextcloud/common/nextcloud/data/$USER/files I ran into the problem of having conflict when trying to backup new pictures from my phone camera. Until one day, I figured out that all files in this folder should have a root:root ownership. It should probably be mentioned on /nextcloud-snap/nextcloud-snap/wiki/Default-path wiki page.
> 
> would you agree that this is mentioned here: https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-what-permissions-should-external-media-have

Yes, it is indeed mentioned in the FAQ but to find it I should have known the question and if so I would have never look in there; which I did not (if that make any sense). Mentioning it in the wiki default-path page would have been easier at least for me.
> 
> > 2. I found that the front-end is very slow! It should probably worth it to test tunings shared on this article https://haefelfinger.ch/posts/2021/2021-03-29-nextcloud-tuning/ that was refered here https://help.nextcloud.com/t/web-interface-very-slow-bad-performance/152757/4
> 
> as for your front-end issues, would it be possible to create a new issue for that? that is something the devs may want to look into... but, remember that we don't have any [upstream devs](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-why-is-nextcloud-snap-version-out-of-sync-with-upstream-nextcloud) in the snap team, so if its an upstream issue it should be handled upstream.

I'll investigate further on my side before doing so. I don't want to make people waste time. :)

**Comment by yannicklescure** [comment]
> @yannicklescure
> 
> > I found that the front-end is very slow!
> 
> could you please describe how your instance is setup and what are you comparing "front-end speeds" to?
> 
> * is your instance self-hosted?

I setup a virtual server hosted on Proxmox with 4 CPUs and 8 GB memory, which should be more than enough. Collabora is hosted in its own virtual server because Office CODE was slowing everything down.

> * describe hardware specs of your instance (arch, RAM, CPU, OS)
> * describe your connectivity (asynchronous DSL, synchronous DSL, uplink, downlink etc.)

I have no clue how to answer that. I'm using a wired network with 1 GB powerline ethernet plugs.
> 
> please post your logs: run the [debugging script](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Issue-Debugging-Scripts#debugging-script)

**Comment by yannicklescure** [comment]
> Thanks for the suggestions @yannicklescure
> 
> > I found that the front-end is very slow!
> 
> Adding to what @scubamuc already asked: do you have [HTTP compression](https://github.com/nextcloud-snap/nextcloud-snap?tab=readme-ov-file#http-compression-configuration) enabled? It usually helps with this.

Yes, I did enable it when reading the doc at initial setup. Thank you for the help. :)

> 
> > It should probably worth it to test tunings shared on this article https://haefelfinger.ch/posts/2021/2021-03-29-nextcloud-tuning/ that was refered here https://help.nextcloud.com/t/web-interface-very-slow-bad-performance/152757/4
> 
> The thing with those kind of tunings is that they should be adapted for the hardware the snap is running on, not just hardcoded, so we would need to do some tests on different hardware to see when they make sense to apply.

**Comment by scubamuc** [comment]
@yannicklescure 

>I have no clue how to answer that. I'm using a wired network with 1 GB powerline ethernet plugs.

no problem... 1GB powerline is enough to know. 

but we will need your logs: run the [debugging script](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Issue-Debugging-Scripts#debugging-script) if you'd like us to have a look

**Comment by scubamuc** [comment]
@yannicklescure, 

>Yes, it is indeed mentioned in the FAQ but to find it I should have known the question and if so I would have never look in there; which I did not (if that make any sense). Mentioning it in the wiki default-path page would have been easier at least for me.

this being something which is snapd specific and only tertiary Nextcloud snap specific, although the Nextcloud snap team has embraced snapd, it is not our goal to cover both snapd and Nextcloud. Our project is Nextcloud snap and we merely take both technologies add a little snapd magic, test and release see [here](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-why-is-nextcloud-snap-version-out-of-sync-with-upstream-nextcloud) and [here](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-what-is-snap-confinement)

so yes it is our goal to cover as much as we can in the wiki and FAQ's, but we will reach boundaries. 

I've added that in [default path](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Default-path) too. 
thanks and keep reading, suggestions are always welcome.

**Comment by scubamuc** [comment]
@yannicklescure, on a personal note...

>... Collabora is hosted in its own virtual server because Office CODE was slowing everything down.

did you by any chance document this procedure? 

it would be great if we could add this procedure to the [CODE & Nextcloud Office](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-CODE-and-Nextcloud-office-for-Nextcloud-snap) wiki

**Comment by yannicklescure** [comment]
> @yannicklescure, on a personal note...
> 
> > ... Collabora is hosted in its own virtual server because Office CODE was slowing everything down.
> 
> did you by any chance document this procedure?
> 
> it would be great if we could add this procedure to the [CODE & Nextcloud Office](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-CODE-and-Nextcloud-office-for-Nextcloud-snap) wiki

It wasn't straight forward as I had to read several articles. However, I could summarize the steps as follow:

1. I installed collabora on an ubuntu server ([See article](https://www.linuxbabe.com/ubuntu/integrate-collabora-onlinenextcloud-without-docker))
2. I modified the apache server conf to listen port 8443 instead of 80 as nextcloud already used it. I had to configure my router to listen to those ports to redirect to the according server; 80 nextcloud and 8443 collabora.
3. On the collabora server, I had to generate an ssl certificate using DNS Validation with acme-dns-certbot ([See article](https://www.digitalocean.com/community/tutorials/how-to-acquire-a-let-s-encrypt-certificate-using-dns-validation-with-acme-dns-certbot-on-ubuntu-18-04))

So it's a bit of everything and I think very specific to my proxmox setup which use the same internet IP with several ubuntu servers.
I could definitely write a step by step markdown document if that could be any useful. Let me know.

**Comment by yannicklescure** [comment]
> @yannicklescure
> 
> > I have no clue how to answer that. I'm using a wired network with 1 GB powerline ethernet plugs.
> 
> no problem... 1GB powerline is enough to know.
> 
> but we will need your logs: run the [debugging script](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Issue-Debugging-Scripts#debugging-script) if you'd like us to have a look

I ran it and discovered that I had an SSL certificate issue that I fixed today. It seems running better now.

**Comment by scubamuc** [comment]
@yannicklescure 

> I think very specific to my proxmox setup which use the same internet IP with several ubuntu servers.
I could definitely write a step by step markdown document if that could be any useful. Let me know

that would be greatly appreciated.

> I ran it and discovered that I had an SSL certificate issue that I fixed today. It seems running better now.

that sounds great, so this issue is resolved then?

**Comment by scubamuc** [comment]
@yannicklescure 

>Ok, I'll find some time to do it. How can I submit the markdown file?

simply open a new issue and attach the markdown file... just like you did in the OT

thanks a million
