### ISSUE TITLE
Directory listing failed Storage is temporarily not available

### ISSUE THREAD

**Issue by Simon1V** [nextcloud-snap/nextcloud-snap#2746]
#### Describe the bug
Nextcloud throws an error "Directory listing failed Storage is temporarily not available"

#### To Reproduce
Using either method described in https://github.com/nextcloud-snap/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition. 
The steps have been followed, permissions set.  
Changing the data directory back to the default directory restores functionality (unless the admin user hasn't been created yet).
 it used to work in previous versions for me.

#### Expected behavior
The new data directory being accepted. 

#### OS/snapd/snap version
27.1.9snap1

#### Logs
See attached file
[debug.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/15387073/debug.txt)

**Comment by scubamuc** [comment]
Hi @Simon1V and thanks for your request.

could you mention what partition format the data directory you are trying to connect to uses and where it is mounted to? 

ensure that you connected [removable media](https://github.com/nextcloud-snap/nextcloud-snap/wiki/configure-Nextcloud-snap#removable-media)

>it used to work in previous versions for me.

hmmm... the process hasn't changed. maybe see the "newer" [wiki entry](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Wiki-Change-data-directory) and compare the setup.

**Comment by Simon1V** [comment]
Thanks for the quick reply :) 
and sure - here some more data : 
It's an encrypted btrfs formatted disk mounted at /media/simon/cloud/
Physically, it's an internal NVME drive, which is mounted automatically on boot. 
the data from the default directory has been copied to /media/simon/cloud/nextcloud/data and the permissions set. 
config.php has been adjusted accordingly. 
I did not have removable media interface set up, however, afaik I did not need to set that up during the last install.
I am currently using the default directory - out of necessity (urgently had to get nextcloud running to sync devices) - but I will give it another shot and point the data directory to the nvme again using the nextcloud:removable-media connection once I can!

**Comment by scubamuc** [comment]
>Thanks for the quick reply :)

sure, no problem

>It's an encrypted btrfs formatted disk mounted at /media/simon/cloud/

don't encrypt the drive... let Nextcloud handle the encryption. this is the reason why the device is "temporarily" unavailable. 

>it used to work in previous versions for me.

was that also encrypted?

**Comment by Simon1V** [comment]
> was that also encrypted?

Yes, that's why I don't think it would matter. The same file system + luks managed encryption works just fine with nextcloud on the current main system drive with the default directory set as data directory. 
Nextcloud shouldn't even know the drive is encrypted, just like it's intransparent to any other app (unless it specifically checks some partition attributes I suppose)

**Comment by scubamuc** [comment]
@Simon1V, also see [removable media](https://github.com/nextcloud-snap/nextcloud-snap/wiki/configure-Nextcloud-snap#removable-media)

>Tip: Recommend creating a dedicated directory in /media/MYDIRECTORY/ or /mnt/MYDIRECTORY/ instead of "automount" /media/$USER/DEVICE/ directory and mounting the dedicated directory in /etc/fstab.

**Comment by scubamuc** [comment]
@Simon1V,

>Yes, that's why I don't think it would matter. 

yeah... its only a suggestion.

**Comment by Simon1V** [comment]
> @Simon1V, also see [removable media](https://github.com/nextcloud-snap/nextcloud-snap/wiki/configure-Nextcloud-snap#removable-media)
> 
> >Tip: Recommend creating a dedicated directory in /media/MYDIRECTORY/ or /mnt/MYDIRECTORY/ instead of "automount" /media/$USER/DEVICE/ directory and mounting the dedicated directory in /etc/fstab.

Going to try that out as well once I get the opportunity. I do wonder why that would be recommended in the first place though

**Comment by scubamuc** [comment]
@Simon1V,

> I do wonder why that would be recommended in the first place though

... [Removable media](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-Nextcloud-snap#removable-media) must be mounted to either /media or /mnt as **root** with **root** permissions and connected to Snap!

mounting in `/media/$USER/...` as **root** with **root** permission would be tricky.

**Comment by ehidle** [comment]
I get this error when simply trying to move the data directory to another location on the filesystem. In my example, my system disk is an nvme and my storage volume is an md mounted on /mnt/storage. Creating /mnt/storage/nextcloud/data and attempting to reconfigure nextcloud to use this as the location for data results in the error mentioned in this post. Is the snap simply incapable of handling a storage location outside of the snap root or some exotic, unreliable removable media?

**Comment by scubamuc** [comment]
> I get this error..

please be clear what error?

>  Is the snap simply incapable of handling a storage location outside of the snap...

nope, that's certainly not a snap issue, more likely an OS thing... if you've covered [Requirements](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Installation-requirements) and know about [Removable media](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-Nextcloud-snap#removable-media) and [Snap confinement](https://snapcraft.io/docs/snap-confinement) depending on your storage volume and whether it is mounted correctly into the host OS with the correct permissions, see [How to add network (SAMBA, NFS, SSHFS) shares to Nextcloud snap](https://github.com/nextcloud-snap/nextcloud-snap/wiki/How-to-add-samba-shares-and-local-shares) you should be able to connect to most devices.

> volume is an md mounted... some exotic, unreliable removable media...

please be clear, what's an "md" and did you follow the steps as described here [Change data directory](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Wiki-Change-data-directory) and here [Change data directory to use another disk partition](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition)
