### ISSUE TITLE
SNAP Nextcloud 27 stable 27.1.9snap1 has broken libpsl.so.5.2.0

### ISSUE THREAD

**Issue by adb336** [nextcloud-snap/nextcloud-snap#2755]
#### Describe the bug
nextcloud.php-fpm:         simple, enabled, inactive

# snap logs nextcloud.php-fpm
2024-05-27T12:20:26+02:00 systemd[1]: Started Service for snap application nextcloud.php-fpm.
2024-05-27T12:20:26+02:00 nextcloud.php-fpm[4083]: Obtaining nextcloud mysql credentials... done
2024-05-27T12:20:26+02:00 nextcloud.php-fpm[4166]: php-fpm: error while loading shared libraries: /snap/nextcloud/42230/usr/lib/x86_64-linux-gnu/libpsl.so.5: cannot read file data: Input/output error
2024-05-27T12:20:26+02:00 systemd[1]: snap.nextcloud.php-fpm.service: Main process exited, code=exited, status=127/n/a
2024-05-27T12:20:26+02:00 systemd[1]: snap.nextcloud.php-fpm.service: Failed with result 'exit-code'.
2024-05-27T12:20:27+02:00 systemd[1]: snap.nextcloud.php-fpm.service: Scheduled restart job, restart counter is at 6.
2024-05-27T12:20:27+02:00 systemd[1]: Stopped Service for snap application nextcloud.php-fpm.
2024-05-27T12:20:27+02:00 systemd[1]: snap.nextcloud.php-fpm.service: Start request repeated too quickly.
2024-05-27T12:20:27+02:00 systemd[1]: snap.nextcloud.php-fpm.service: Failed with result 'exit-code'.
2024-05-27T12:20:27+02:00 systemd[1]: Failed to start Service for snap application nextcloud.php-fpm.

# cd /snap/nextcloud/42230/usr/lib/x86_64-linux-gnu
# file libpsl.so.5.2.0
libpsl.so.5.2.0: ERROR: cannot read `libpsl.so.5.2.0' (Input/output error)

#### To Reproduce
1. Ubuntu VM running bullseye/sid, Ubuntu 20.04.6 LTS
2. apt update
3. apt full-upgrade -y
4. apt dist-upgrade
5. apt autoremove --purge
6. apt autoclean
7. reboot
8. nextcloud.occ status --> Waiting for PHP...

#### Expected behavior
Service nextcloud.php-fpm should be active after reboot.

#### Screenshots
NA

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud
Name       Version      Rev    Tracking   Publisher   Notes
nextcloud  27.1.9snap1  42230  27/stable  nextcloud✓  -

and:

    $ snap version
snap    2.62+20.04
snapd   2.62+20.04
series  16
ubuntu  20.04
kernel  5.4.0-182-generic

#### Logs
See above the logs from nextcloud.php-fpm...

I have no possibility to reload this file only.

I have checked the filesystem of the VM with guestfish in offline mode of the VM --> no errors

One the host the library is now
root@next01:/usr/lib/x86_64-linux-gnu# ll libpsl.so*
263927 lrwxrwxrwx 1 root root    15 Mar 31  2020 libpsl.so.5 -> libpsl.so.5.3.2
263876 -rw-r--r-- 1 root root 71672 Mar 31  2020 libpsl.so.5.3.2

Please consider this urgent.

**Comment by scubamuc** [comment]
welcome @adb336 and thanks for your request... urgency noted

we'll need some more infos, please run the [debugging script](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Issue-Debugging-Scripts#debugging-script) and post results here.

**Comment by adb336** [comment]
BTW: sorry I didn't got what a hash in front of a line is producing. Normally I am using the hash to make clear that I run the commands as root...

Output of your script:

Hanging as expected at "Waiting for PHP..."

[output-20240527.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/15455414/output-20240527.txt)

Thanks for the help...

**Comment by scubamuc** [comment]
@adb336 you are right:
>May 27 10:02:09 next01 nextcloud.php-fpm[4326]: php-fpm: error while loading shared libraries: /snap/nextcloud/42230/usr/lib/x86_64-linux-gnu/libpsl.so.5: cannot read file data: Input/output error
May 27 10:02:09 next01 systemd[1]: snap.nextcloud.php-fpm.service: Main process exited, code=exited, status=127/n/a
May 27 10:02:09 next01 systemd[1]: snap.nextcloud.php-fpm.service: Failed with result 'exit-code'.

this seems your issue

can you be clear about:

>Ubuntu VM running bullseye/sid, Ubuntu 20.04.6 LTS

do you mean, that the VM host is bullseye/sid and the Nextcloud snap Host is Ubuntu 20.04.6 LTS?

I do agree that "libpsl.so.5.2.0" cannot be found... but as far as I know, that is not a snap library... so this could be related to OS.

@pachulo could you please assist?

**Comment by adb336** [comment]
Dear all, sorry for the ambigous information:

Host OS is openSUSE Leap 15.4

VM OS is Ubuntu 20.04.6 LTS.

Do you need more info from Host OS?

Kind regards,

**Comment by scubamuc** [comment]
@adb336, no Problem,

>VM OS is Ubuntu 20.04.6 LTS.

should be all the info that devs need...

labelled this as "help wanted", we'll have to wait and see if someone can assist.

so I'm assuming the upgrade mentioned was a VM OS (Ubuntu) upgrade right?

you can't roll back the upgrade, so you won't be able to revert the snap? that's a bit of a caveat.

**Comment by adb336** [comment]
Many thanks for taking action on this issue, the update of NextCloud was including DB schema updates, therefor I don't think it is feasible to go back.

The OS doesn't know about "atomar" therefor the only way I think is to get hands on libpsl.so.5.2.0 and make it available to the snap. Since I don't want to mess around without someone looking over my shoulders I depend on you to give me hints for solving this corrupted file.

BTW: is libpsl.so.5.2.0 part of the snap and if not - how is the snap accessing it? It would be then an idea to look for a package holding this file if the snap is using the OS one...

Kind regards,

**Comment by adb336** [comment]
Next idea: in the past in plain OS environments I sometimes linked the actual version of a lib to the name of an different one. More than often this did work, nothing guaranteed, though...

**Comment by scubamuc** [comment]
@adb336, so I'm finding `libpsl.so` in the snap.

![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/3177402e-03dc-4a02-a8f6-971418d65fb0)

>The libpsl package provides a library for accessing and resolving information from the Public Suffix List (PSL). The PSL is a set of domain names beyond the standard suffixes, such as .com. 

now the question is, why does your snap need a different version... and why does it need a different version than what is packaged in the snap?

do you have any third party apps installed that require a different version?

**Comment by adb336** [comment]
Good question. libpsl.so.5 is linked to libpsl.so.5.2.0

`# cd /snap/nextcloud/42230/usr/lib/x86_64-linux-gnu
root@next01:/snap/nextcloud/42230/usr/lib/x86_64-linux-gnu# ll libpsl.so.5*
32446 lrwxrwxrwx 1 root root    15 Mar  4  2018 libpsl.so.5 -> libpsl.so.5.2.0
32447 -rw-r--r-- 1 root root 55136 Mar  4  2018 libpsl.so.5.2.0
`

From my point of view I am using NextCloud in a quite native manner. Without the WebGUI: how can we list third party apps? Is there a nextcloud.occ command which will work without PHP?

Kind regards,

**Comment by pachulo** [comment]
Hi! As far as I know, the version of the library reported by @adb336 is indeed included on the snap, and I don't think the error is related to 3rd party apps or OS updates.

To me, the fact that you are getting an input/output error when trying to access it, suggests that something is wrong with the file system. The thing is that, in the end, the mounted directories where snaps are run from are read-only squashfs mounts, so I don't really know what might be going on here, sorry....
Any ideas @kyrofa ?

**Comment by adb336** [comment]
Dear all, the message from pachulo indicates an error in the underlying file. I am assuming this is the Squashfs file. There was a suggestion to check those file by reading the content. I am not sure if this is ok. Reading might be limited to meta information only.

Can you tell me the Squashfs files to check, i will read them with dd ...

BTW: as mentioned earlier I have checked the VM filesystem (EXT4) offline with no errors coming up.

Kind regards,

**Comment by scubamuc** [comment]
@adb336 

> Is there a nextcloud.occ command which will work without PHP?

nope, afraid not.

do you have a backup copy of the VM?

**Comment by adb336** [comment]
Ok, @scubamuc : let's start with the dd on the Squashfs files having libpsl.so.5 in them.

Which are these and where are these located in the VM filesystem?

Kind regards,

**Comment by adb336** [comment]
Task 2: how can I replace either the Squashfs file for my version or the file libpsl.so.5 in the Squashfs file?

Kind regards,

**Comment by scubamuc** [comment]
@adb336 thanks for your confidence in my abilities... 

>Which are these and where are these located in the VM filesystem?

>can I replace either the Squashfs file for my version of NextCloud snap or the file libpsl.so.5 in the Squashfs file?

but I'm afraid this is beyond my scope :-)

considering the urgency and my limited resources, I'd suggest [copying your raw data](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Getting-help#disaster-recovery) and setting up a new VM. otherwise, you'd have to wait for the devs to pitch in with their magic.

**Comment by adb336** [comment]
@scubamuc : is there a documented way to dump the database - MySQL - without nextcloud.dump?

Example: connect into the snap, start mysql or similiar to generate a dump? Beyond the files we are using contacts and calendars to synchronize between the users.

Kind regards,

**Comment by adb336** [comment]
Dear all, I am preparing for a new environment...

In the meantime I might have luck to revert with

`# snap revert nextcloud --revision=??????`

to the former snap if there are no DB schema updates in between.

What is the revision before 27.1.9snap1 (42230)?

Kind regards,

PS: MySQL dump still an open issue...

**Comment by adb336** [comment]
Dear all,

Is nextcloud,export also dependend on PHP?

Kind regards,

**Comment by adb336** [comment]
Some news from today:

`# dmesg`

revealed that indeed one Squashfs is corrupted:

[   46.187687] SQUASHFS error: xz decompression failed, data probably corrupt
[   46.187728] SQUASHFS error: squashfs_read_data failed to read block 0x12f3b825
[   46.192632] SQUASHFS error: xz decompression failed, data probably corrupt
[   46.192672] SQUASHFS error: squashfs_read_data failed to read block 0x12f3b825
[   46.632928] SQUASHFS error: xz decompression failed, data probably corrupt
[   46.632968] SQUASHFS error: squashfs_read_data failed to read block 0x12f3b825
[   47.147543] SQUASHFS error: xz decompression failed, data probably corrupt
[   47.147593] SQUASHFS error: squashfs_read_data failed to read block 0x12f3b825
[   47.639043] SQUASHFS error: xz decompression failed, data probably corrupt
[   47.639084] SQUASHFS error: squashfs_read_data failed to read block 0x12f3b825
[   48.147288] SQUASHFS error: xz decompression failed, data probably corrupt
[   48.147327] SQUASHFS error: squashfs_read_data failed to read block 0x12f3b825
[   48.642222] SQUASHFS error: xz decompression failed, data probably corrupt
[   48.642259] SQUASHFS error: squashfs_read_data failed to read block 0x12f3b825
[  120.829969] SQUASHFS error: xz decompression failed, data probably corrupt
[  120.830009] SQUASHFS error: squashfs_read_data failed to read block 0x12f3b825

Any idea how to identify the file and how to get it fixed. Again: the underlying FS doesn't show an issue...

Kind regards,

**Comment by scubamuc** [comment]
@adb336 

>In the meantime I might have luck to revert with
>
>`# snap revert nextcloud --revision=??????`

no need for that

see [here](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-nextcloud-snap-stopped-working-after-an-update-what-can-i-do) the snap will revert to last known good.

**Comment by scubamuc** [comment]
@adb336 

>Is nextcloud,export also dependend on PHP?

yes

**Comment by adb336** [comment]
Dear all, trying

`# snap revert nextcloud`

`# snap info nextcloud`
name:      nextcloud
summary:   Nextcloud Server - A safe home for all your data
publisher: Nextcloud✓
store-url: https://snapcraft.io/nextcloud
contact:   https://github.com/nextcloud/nextcloud-snap
license:   unset
description: |
  Access, share and protect your files, calendars, contacts, communication and
  more at home and in your enterprise.
commands:
  - nextcloud.disable-https
  - nextcloud.enable-https
  - nextcloud.export
  - nextcloud.import
  - nextcloud.manual-install
  - nextcloud.mysql-client
  - nextcloud.mysqldump
  - nextcloud.occ
services:
  nextcloud.apache:          simple, enabled, active
  nextcloud.logrotate:       simple, enabled, inactive
  nextcloud.mysql:           simple, enabled, active
  nextcloud.nextcloud-cron:  simple, enabled, active
  nextcloud.nextcloud-fixer: simple, enabled, inactive
  nextcloud.php-fpm:         simple, enabled, active
  nextcloud.redis-server:    simple, enabled, active
  nextcloud.renew-certs:     simple, enabled, active
snap-id:      njObIbGQEaVx1H4nyWxchk1i8opy4h54
tracking:     27/stable
refresh-date: today at 12:33 CEST
installed:          27.1.8snap1                  (41512) 322MB -

`# nextcloud.occ status?`
  - installed: true
  - version: 27.1.8.1
  - versionstring: 27.1.8
  - edition:
  - maintenance: false
  - needsDbUpgrade: false
  - productname: Nextcloud
  - extendedSupport: false

Now I am looking into synch errors:

Windows 10 pops up with 

File could not be synchronized because of errors

Trying to find about those errors.

**Comment by scubamuc** [comment]
@adb336, good work, sounds like the revert worked... 

time to export the DB and possibly the entire snap, see [backup, restore & migrate](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Backup-and-Restore). 

You may want to try and migrate the snap to a newer "22.04 LTS" or brand new "24.04 LTS" VM.... my thoughts, this is an OS thing... snap core 18 vs. snap core 20 etc... but that's just my guess.

**Comment by adb336** [comment]
@scubamuc yep, things seem to be more under control. Since Ubuntu goes "weird" strategies I have started a Fedora server and will backup all data to this environment.

Many thanks for the hints but the incident now is over. Still interested in why the Squashfs has been corrupted and why there are no optional ways to retrieve data once PHP or http don't work anymore...

Kind regards,

**Comment by scubamuc** [comment]
@adb336 

>Since Ubuntu goes "weird" strategies I have started a Fedora server and will backup all data to this environment.

I wouldn't do that... see why [Ubuntu is the only supported distribution](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Why-Ubuntu-is-the-only-supported-distro).

>Many thanks for the hints but the incident now is over. 

sure thing, glad I could help.

so I'll close this now?

**Comment by adb336** [comment]
Yep, can be closed.

In regards for support: Ubuntu makes itself dependend on too many levels of technology. As a solution architect I try to follow KISS: keep it simple s.....

Nevertheless you and the team are doing a much appreciated job.

Kind regards,
