### ISSUE TITLE
PHP opcache and imagick problems after update to Nextcloud-snap 28.0.6.1

### ISSUE THREAD

**Issue by adrianvg** [nextcloud-snap/nextcloud-snap#2759]
#### Describe the bug
Nextcloud-snap auto-updated the other night, seems to work okay, but in Administration/Overview GUI I now have some 70ish problems since 2024-05-24.

Notable are these:

- X PHP opcache: The PHP OPcache module is not properly configured. OPcache is not working as it should, opcache_get_status() returns false, please check configuration.

The maximum number of OPcache keys is nearly exceeded. To assure that all scripts can be kept in the cache, it is recommended to apply "opcache.max_accelerated_files" to your PHP configuration with a value higher than "10000".
The OPcache buffer is nearly full. To assure that all scripts can be hold in cache, it is recommended to apply "opcache.memory_consumption" to your PHP configuration with a value higher than "128"..

- ℹ PHP Imagick module: The PHP module "imagick" is not enabled although the theming appis. For favicon generation to work correctly, you need to install and enable this module.

Disabling the Theming app from Apps (I don't need it anyway) reports that it can't be disabled because I need NC v13 or lower. See screendump below.

#### To Reproduce
**From GUI**
1. Go to Administration settings.
2. Click Administration Overview.
3. A check will start automatically.

**From CLI**
1. Open a terminal on the nextcloud-snap server.
2. sudo nextcloud.occ setupchecks
3. Output from my nextcloud-snap server attached.
[nextcloud.occ.setupchecks.txt](https://github.com/user-attachments/files/15509431/nextcloud.occ.setupchecks.txt)

#### Expected behavior
No errors. Theming app can be disabled.

#### Screenshots
Theming can't be disabled.

![2024-05-31_08-47-43](https://github.com/nextcloud-snap/nextcloud-snap/assets/15629475/433a582b-13db-4280-8109-64ffe80074e7)

#### OS/snapd/snap version
What OS and version are you running? 
```
root@nextcloud2:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
root@nextcloud2:~#
```

Please also include the output of the
following commands:

    $ snap list nextcloud
```
root@nextcloud2:~# snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  28.0.6snap1  42563  latest/stable  nextcloud✓  -
root@nextcloud2:~#
```

and:

    $ snap version
```
root@nextcloud2:~# snap version
snap    2.63
snapd   2.63
series  16
ubuntu  22.04
kernel  6.5.0-35-generic
root@nextcloud2:~#
```

#### Logs
[issue.debugging.script.output.txt](https://github.com/user-attachments/files/15509676/issue.debugging.script.output.txt)

The debugging script reports certificate errors etc, but the server certs work/are fine.
My Nextcloud server is behind a Nginx Proxy Manager, so that may be why.

I'd be grateful for any hints, comments and tips on how to resolve this.
Thanks!

**Comment by scubamuc** [comment]
@adrianvg welcome and thanks for your request,

>Theming can't be disabled.

this is true, but you could try disabling user theming..

your settings

```
        "theming": {
            "cachebuster": "3",
            "disable-user-theming": "no",
            "enabled": "no",
            "installed_version": "2.3.0",
            "types": "logging"
``` 

I would agree that the OPCache warning is connected to the "themeing" app and `imagick`.

you might consider reverting, see [FAQ's](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-nextcloud-snap-stopped-working-after-an-update-what-can-i-do)

----

>The debugging script reports certificate errors etc, but the server certs work/are fine. My Nextcloud server is behind a Nginx Proxy Manager, so that may be why.

you can disable the renewal service if you're terminating with [NGINX proxy manager](https://github.com/nextcloud-snap/nextcloud-snap/wiki/NGINX-proxy-manager#reverse-proxy-with-termination)

**Comment by adrianvg** [comment]
Hello and thanks for the suggestions!

Re the user theming, I actually disabled it after posting the issue.

Looked into reverting and am now back to v27.1.9. 
No errors reported.

![2024-05-31_13-29-40](https://github.com/nextcloud-snap/nextcloud-snap/assets/15629475/c2b5e1ee-f634-40a0-83b0-5af231430c5f)


What happens now?
Will v28 get autoinstalled later and the errors back?
I haven't had to revert back ever while using Nextcloud-snap, it's been that stable.




Will wait a bit with the certificates, thanks though for the hint!

**Comment by adrianvg** [comment]
Actually, would it be possible to revert all the way down to v13, then uninstall the Theming app, and after that update all the way up to the latest v28?

**Comment by scubamuc** [comment]
nope, you'll lose data.

**Comment by adrianvg** [comment]
> nope, you'll lose data.

Thanks, good thing I asked first! :-)

**Comment by adrianvg** [comment]
Okay then, I'm happy so far. Will wait till a later major version is released and try it out again then and see if things get better.

Closing this issue for now.

Thanks again for swift the hints and tips!

**Comment by adrianvg** [comment]
For posterity, this is what I did.

```
root@nextcloud2:~# snap revert nextcloud
2024-05-31T13:44:08+02:00 INFO Waiting for "snap.nextcloud.apache.service" to stop.
2024-05-31T13:44:10+02:00 INFO Waiting for "snap.nextcloud.mysql.service" to stop.
nextcloud reverted to 27.1.9snap1

root@nextcloud2:~# snap list
Name       Version      Rev    Tracking       Publisher   Notes
core18     20240416     2823   latest/stable  canonical✓  base
nextcloud  27.1.9snap1  42230  latest/stable  nextcloud✓  -
snapd      2.63         21759  latest/stable  canonical✓  snapd
root@nextcloud2:~# snap refresh nextcloud --channel=27
nextcloud (27/stable) 27.1.9snap1 from Nextcloud✓ refreshed

root@nextcloud2:~# snap list
Name       Version      Rev    Tracking       Publisher   Notes
core18     20240416     2823   latest/stable  canonical✓  base
nextcloud  27.1.9snap1  42230  27/stable      nextcloud✓  -
snapd      2.63         21759  latest/stable  canonical✓  snapd

root@nextcloud2:~# snap list nextcloud --all
Name       Version      Rev    Tracking   Publisher   Notes
nextcloud  27.1.9snap1  42230  27/stable  nextcloud✓  -
nextcloud  28.0.6snap1  42563  27/stable  nextcloud✓  disabled
root@nextcloud2:~#
```

Later when v29 or later is released, I'll connect to the latest channel again and try it out.
Source: [https://github.com/nextcloud-snap/nextcloud-snap/wiki/What-do-I-do-if-an-update-breaks-Nextcloud%3F](https://github.com/nextcloud-snap/nextcloud-snap/wiki/What-do-I-do-if-an-update-breaks-Nextcloud%3F)

`$ sudo snap refresh nextcloud --stable`

**Comment by scubamuc** [comment]
@neeks76, welcome

> May I guess it is from imagemagick.
>
> `sudo apt-get install -y imagemagick

you could try that, but you won't succeed! see [confinement](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-what-is-snap-confinement)

>Could you show me how to add it to nextcloud sanp?

afraid not...

why imagick is not included in the snap see [FAQ's](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#imagick-php-module-not-enabled)
