### ISSUE TITLE
Cannot Upload Files Bigger than 8MB

### ISSUE THREAD

**Issue by Flagelmann** [nextcloud-snap/nextcloud-snap#2762]
#### Describe the bug
Cannot upload files bigger than 8 MB. Nextcloud is behind a normal (non-docker) Nginx reverse proxy (also already specified the **client_max_body_size 1024M;** for the relative conf about Nextcloud instance). The Nexcloud snap instance says "Upload max size: 16 GB" but it is actually not true as under the Nextcloud snap php.ini I see the post_max_size=8M (even if under the www.conf the same value is put to 16G).

#### Expected behavior
Be able to upload files bigger than 8 MB would be very appreciated.

#### OS/snapd/snap version
What OS and version are you running? 

Linux bihost 6.6.31+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux

Please also include the output of the
following commands:

    $ snap list nextcloud

nextcloud  28.0.6snap1  42571  latest/stable  nextcloud✓  -

and:

    $ snap version

snap    2.63
snapd   2.63
series  16
debian  12
kernel  6.6.31+rpt-rpi-v8

#### Notes

The nextcloud instance is running without issues behind Nginx with HTTPS. Also configured it with a desktop client and a mobile device. The only issue is this upload restriction that sounds quite weird.

So, now trying to understand if it is a limitation of this snap version of Nextcloud, otherwise I will revert to the manual installation type as I did previously with my past instance, now decommissioned.

**Comment by scubamuc** [comment]
Hi @Flagelmann,

cannot confirm your issue, grab a test file here: https://ash-speed.hetzner.com/
upoalded 100MB file without issues

**Comment by scubamuc** [comment]
@Flagelmann welcome and thanks for your request,

are you uploading the file in a browser or using the client?

>debian 12

see [requirements](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Installation-requirements) and why [Ubuntu is the only supported distribution](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Why-Ubuntu-is-the-only-supported-distro) for Nextcloud snap.

**Comment by Flagelmann** [comment]
Tried with the 100MB.bin test file.

When trying syncing it using the desktop client it uploads it but at the end it say "403 forbidden". On web side I get an "Unknown upload error" popup for few seconds.

So, if the OS is not Ubuntu I think I will have to drop this snap and install Nextcloud as I did with the previous instance I had.

That's a pity.

Thanks anyway.

**Comment by scubamuc** [comment]
@Flagelmann, 

so when you're using the browser to upload it works and when you're using the desktop client it doesn't work?

>So, if the OS is not Ubuntu I think I will have to drop this snap and install Nextcloud as I did with the previous instance I had.
>
>That's a pity.

yeah... that's a pity

**Comment by scubamuc** [comment]
@Flagelmann,

see https://github.com/nextcloud-snap/nextcloud-snap/issues/2717#issuecomment-2074675900
