### ISSUE TITLE
No Internet connection inside nextcloud snap

### ISSUE THREAD

**Issue by remrengg** [nextcloud-snap/nextcloud-snap#2764]
#### Describe the bug
A clear and concise description of the bug.
We do not have an internet connection inside the nextcloud snap but we have one on the host device.
#### To Reproduce
Try to download a new nextcloud app or try to update nextcloud itself or an existing nextcloud app.

#### Expected behavior
That I have an active internet connection inside the nextcloud snap.
#### Screenshots
![Screenshot 2024-06-03 143051](https://github.com/nextcloud-snap/nextcloud-snap/assets/171562280/339a0ea9-9134-4b2b-9756-d356dbb7fb02)

#### OS/snapd/snap version
What OS and version are you running?
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy

Please also include the output of the
following commands:

    $ snap list nextcloud
Name       Version          Rev      Tracking         Publisher     Notes
nextcloud  27.1.9snap1  42230  latest/stable  nextcloud✓  held
and:

    $ snap version
snap    2.63
snapd   2.63
series  16
ubuntu  22.04
kernel  5.15.0-107-generic

#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).
Our output is way to long so I added it as a file (Nextcloud_03.06.2024.md)
[Nextcloud_03.06.2024.md](https://github.com/user-attachments/files/15584878/Nextcloud_03.06.2024.md)

**Comment by scubamuc** [comment]
@remrengg welcome and thank you for your request

>.... but we have one on the host device.

so the Host is online... but your snap is saying it can't connect? 
this could be related blocking by firewall or unconfigured reverse proxy. we'll need some more information about your setup. double check if [requirements](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Installation-requirements) have been met

- check firewall allows connection from snap
- check reverse proxy is configured (if you have one)

**Comment by remrengg** [comment]
Sorry for the late answer.
I am able to have Internet access from the snap shell. Is that enough or how do I check otherwise?
Additionally I want to add that we do not have a proxy outward.

**Comment by scubamuc** [comment]
@remrengg 

- is this a fresh install?
- are all [requirements](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Installation-requirements) met?

see [getting help](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Getting-help)

**Comment by remrengg** [comment]
No its not a new installation. It was installed with version 26 a year ago. Updates and Internet connection was not a problem until now. The problem appeared after an upgrad to version 29. A revert to version 28 made the nextcloud usable again but the internet connection was still not there.

As far as I see the system requirements are met. Is there any other requirement than ubuntu ip-address and open ports?

**Comment by scubamuc** [comment]
@remrengg 

>problem appeared after an upgrad to version 29

why 29, that is still in "beta"? your initial post mentions

>27.1.9snap1 

please be clear

**Comment by remrengg** [comment]
sorry my colleague gave me the wrong information. It is now on version 27 like in my initial post. it was upgraded to version 28 and than reverted to version 27 to make the nextcloud usable again.

**Comment by scubamuc** [comment]
@remrengg 
>reverted to version 27 to make the nextcloud usable again

so the screen shot in the above post is **after** successful revert? it would have been easier if you had included the version in the screenshot... but this needs to be clear.

**Comment by remrengg** [comment]
yes the screenshot and everything in my initial port is from after the revert

**Comment by scubamuc** [comment]
@remrengg,
all above has been confirmed and you've successfully reverted to 27.1.9snap1. 

your issue is bound to be a network issue.... bar having a reverse proxy, assuming correct firewall configuration, this is probably a DNS issue. 

so please double check your [DNS](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Installation-requirements#domain-name-and-dns) configuration.

**Comment by remrengg** [comment]
It is a firewall issue and we were surprised that it suddendly appeared because it worked without any problems before.

**Comment by scubamuc** [comment]
@remrengg 

> It is a firewall issue and we were surprised that it suddendly appeared because it worked without any problems before.

yeah sh1t happens...

**Comment by remrengg** [comment]
I was wrong with my assumption that the server as internet. We now solved it by adding 'allow_local_remote_servers'=>true to the php config.
