### ISSUE TITLE
How to modify the JSON file of translation content?

### ISSUE THREAD

**Issue by Benjamin-Watson0** [nextcloud-snap/nextcloud-snap#2774]
How to modify the JSON file of translation content?
I need to make some changes to it, which is somewhat important to me.
However, it is a read-only file and cannot be modified.
OCC seems not suitable for it, any better suggestions?

**Comment by scubamuc** [comment]
@Benjamin-Watson0 

>it is a read-only file and cannot be modified

afraid so, that is the concept of the snap. 
you could try [hacking Nextcloud snap](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Hacking-Nextcloud-snap), but if you need to make these kind of changes you're on your own...

**Comment by scubamuc** [comment]
@Benjamin-Watson0 
>In fact, I just want to add two nouns at the bottom of the page and point to the corresponding link.

afraid this is beyond our scope...

here is an example on how to disable the link completely:
```
sudo nextcloud.occ config:system:set simpleSignUpLink.shown --value="false"
```
