### ISSUE TITLE
I can't write korean on nextcloud office.

### ISSUE THREAD

**Issue by neeks76** [nextcloud-snap/nextcloud-snap#2775]
#### Describe the bug

I followed instruction of nextcloud office in Wiki tap.
But unfortunately I can't write korean text.

To solve it I added font.
![image](https://github.com/nextcloud-snap/nextcloud-snap/assets/22609932/0cd4cc19-baba-41a6-b45a-04ebfd53ae0c)

And I edited coolwsd.xml but it is not working

`sudo vi /tmp/snap-private-tmp/snap.nextcloud/tmp/appimage_extracted_6eb76af5f453f224886c99f3a492b65b/etc/coolwsd/coolwsd.xml`

![image](https://github.com/nextcloud-snap/nextcloud-snap/assets/22609932/0499715b-9f92-4308-bf4a-556109140107)

![image](https://github.com/nextcloud-snap/nextcloud-snap/assets/22609932/16fb4ee1-b1c7-48ee-9001-1965255b4b42)

#### Expected behavior
I hope to write and see korean on nextcloud office.

#### Screenshots
![image](https://github.com/nextcloud-snap/nextcloud-snap/assets/22609932/1f390e87-820e-4abe-ba1f-00d925890ecc)

#### OS/snapd/snap version
    $ snap list nextcloud
    $ snap version
![image](https://github.com/nextcloud-snap/nextcloud-snap/assets/22609932/0390d972-fe2a-49cc-bd5e-99337463a601)

#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).
[debug_20240610.txt](https://github.com/user-attachments/files/15757383/debug_20240610.txt)

**Comment by scubamuc** [comment]
@neeks76 
sorry, but we can't [support third party apps](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-CODE-and-Nextcloud-office-for-Nextcloud-snap) here. you'll have to do your own research and create an issue with the app developers.

**Comment by awatchar** [comment]
Same problem here. 😭😭😭
