### ISSUE TITLE
cannot run https://scan.nextcloud.com/

### ISSUE THREAD

**Issue by sbe-arg** [nextcloud-snap/nextcloud-snap#2776]
#### Describe the bug
I try to scan my domain and get Host not found

is this related to requiring /index.php?

#### To Reproduce
go to https://scan.nextcloud.com/ enter my url
gets host not found

#### Expected behavior
scan me like it did when using nextcloud non-sna

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud
    
```
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  28.0.6snap1  42563  latest/stable  nextcloud✓  -

```

and:

    $ snap version

```
snap    2.63
snapd   2.63
series  16
ubuntu  24.04
kernel  6.8.0-35-generic
```

I'm on ubuntu 24.04
I run behind a proxy
I'm not geoblocking anything
Me and many other people can connect to the server and use it normally.

**Comment by sbe-arg** [comment]
or is it because edition is empty?

/status.php

```
{
  "installed": true,
  "maintenance": false,
  "needsDbUpgrade": false,
  "version": "28.0.6.1",
  "versionstring": "28.0.6",
  "edition": "",
  "productname": "Nextcloud",
  "extendedSupport": false
}
```

**Comment by sbe-arg** [comment]
I cannot even see remote connection attempts from scan.nextcloud on the reverse proxy.

But I can scan another instance non snap under the same proxy settings.

Could this be a scan service problem or is it a problem on my end?

**Comment by sbe-arg** [comment]
Ill retry at another time. Thanks for checking.

**Comment by scubamuc** [comment]
@sbe-arg
no problem, I'll close this then?

**Comment by scubamuc** [comment]
@sbe-arg , the scan site seems to be working again:
![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/82962ee3-e254-4af3-99b1-861b5071f4f9)

check it out...

**Comment by sbe-arg** [comment]
Yeah its working now.
