### ISSUE TITLE
Your web server is not properly set up to resolve "/.well-known/webfinger". "/.well-known/nodeinfo".

### ISSUE THREAD

**Issue by sbe-arg** [nextcloud-snap/nextcloud-snap#2777]
#### Describe the bug
This shows in NC28 when is a requirement for NC29.
I have the location redirects for caldav and these ones listed here https://github.com/nextcloud-snap/nextcloud-snap/wiki/NGINX-proxy-manager#setting-required-prior-to-nc29
There is nothing on those paths locally. Do they need to be installed by an app? of whats missing? I'm confused,
```
Your web server is not properly set up to resolve "/.well-known/webfinger". Further information can be found in the [documentation ↗](https://docs.nextcloud.com/server/28/go.php?to=admin-setup-well-known-URL).
Your web server is not properly set up to resolve "/.well-known/nodeinfo". Further information can be found in the [documentation ↗](https://docs.nextcloud.com/server/28/go.php?to=admin-setup-well-known-URL).
```

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud

```
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  28.0.6snap1  42563  latest/stable  nextcloud✓  -

```

and:

    $ snap version

```
snap    2.63
snapd   2.63
series  16
ubuntu  24.04
kernel  6.8.0-35-generic
```

**Comment by sbe-arg** [comment]
probably related to this https://github.com/nextcloud/documentation/issues/6157#issuecomment-820449986

**Comment by sbe-arg** [comment]
I'm gonna propose we document if the **install does not use the social app** to use this approach 

location /.well-known/webfinger {return 301 $scheme://$host/index.php;}
location /.well-known/nodeinfo {return 301 $scheme://$host/index.php;}

**Comment by scubamuc** [comment]
@sbe-arg welcome back

yeah, if you are using social connect apps, then you'll need those entries in NPM advanced settings from NC29... but may also work for NC28 if you're getting those errors.

**Comment by sbe-arg** [comment]
I'm not using the social app.

But I get those errors in the status check.

Not that I really care but would be good to know why.

I did nit have this problem on truenas nextcloud (I recently migrated to snap)

**Comment by scubamuc** [comment]
@sbe-arg 

>I get those errors in the status check...

can you post a screenshot?

>would be good to know why.

please give me a shout if you find out 👍

**Comment by scubamuc** [comment]
@Pilzinsel64, do you have any ideas which apps may cause these warnings? 
I'm guessing the `webfinger` issues are related to social apps and the `nodeinfo` issues are related to `node.js` path in Nextcloud snap?

@sbe-arg compare your apps list with [recommended default apps](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-recommended-apps-in-the-default-installation-of-nextcloud-snap)

**Comment by sbe-arg** [comment]
Ill share the app list but the only 2 apps I installed aside the default set are:

Talk
Office
Collabora server

- installed snap
- configured reverse proxy settings
- installed the 3 apps
- restored files

That was my migration nothing fancy mainly moving files from one setup to another.

**Comment by sbe-arg** [comment]
https://github.com/nextcloud/server/issues/45505#issuecomment-2131367907

**Comment by scubamuc** [comment]
@sbe-arg 

>https://github.com/nextcloud/server/issues/45505#issuecomment-2131367907

did that solve your issue then mate?

**Comment by sbe-arg** [comment]
Gonna test in a few hours and report

**Comment by Pilzinsel64** [comment]
> @Pilzinsel64, do you have thoughts about these warnings?

As long as the social app is not enabled or even installed, this warning should't appear. If this appear in on a clean install without any additional apps, it might be the issue @sbe-arg already linked: https://github.com/nextcloud/server/issues/45505#issuecomment-2131367907 Let's see what comes out of your tests. :)

**Comment by sbe-arg** [comment]
Ill try to do further testing this week. I was out of action for a day and a bit.

**Comment by sbe-arg** [comment]
Not yet I'm planning on setting up a fresh instance and install the social app in a day or 2 I'm hammered with work at the moment.

**Comment by sbe-arg** [comment]
The only update I have is that the nodeinfo error cleared with the nc29 release but webfinger remains

![image](https://github.com/nextcloud-snap/nextcloud-snap/assets/23391642/8010ee7b-7e93-4779-8219-cd35d2354dac)

**Comment by ieleja** [comment]
After upgrade to 29.0.0 message about webfinger comes back, 29.0.3 did not resolves problem
My Apache with sub-folder installation have necessary .htaccess records

But response to curl request:
`{"message":"webfinger not supported"}`

take me to essential question — which service must answer to this "webfingering" and if I not installed any social services, there is none that must answer?

thanks,
Saules Ieleja

**Comment by scubamuc** [comment]
@kyrofa or @pachulo please assist

**Comment by scubamuc** [comment]
@sbe-arg, did you get this sorted mate?

**Comment by sbe-arg** [comment]
Nope I'm just learning to ignore it.

**Comment by scubamuc** [comment]
@sbe-arg 

> Nope I'm just learning to ignore it.

😂 good workaround ✔ 

I cannot confirm this issue on any of my instances. It seems like something upstream. Mentioned in [frequent Nextcloud 29 issues](https://help.nextcloud.com/t/frequent-nextcloud-29-hub-8-update-issues/189897) but no solution.

@ieleja is asking valid questions which can only be answered upstream I guess? Would you care to mention this upstream?

**Comment by scubamuc** [comment]
@sbe-arg now I've seen some mention that setting `overwriite-cli` might resolve this issue... its worth a try right?

# Set overwrite-cli
  sudo nextcloud.occ config:system:set overwrite.cli.url --value="https://cloud.my.domain.xyz" ;

**Comment by scubamuc** [comment]
@ieleja, so you're running behind a [reverse proxy](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Putting-the-snap-behind-a-reverse-proxy)?

see [Hosts & FQDN configuration](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Hosts-and-FQDN-for-Nextcloud-snap)

>now only complaints is about Data directory accessible to internet, what is not true at all:
https://github.com/nextcloud/server/issues/45087#issuecomment-2209551167

not sure, but that's upstream right?

**Comment by ieleja** [comment]
no, there are not reverse proxies, but as I say, reconfiguration to without sub-folder resolves my 'webfinger' issue
You are right, complaints about Data directory must be discussed in another thread
/over

**Comment by sbe-arg** [comment]
Not sure if resolves it then if it hides it behind something else.

**Comment by sbe-arg** [comment]
How is this completed?

**Comment by scubamuc** [comment]
hey mate, 
this is certainly an upstream issue and not a snap bug... check https://help.nextcloud.com for similar issues.

if you're not happy with that, then I'll gladly reopen the issue 🤭
