### ISSUE TITLE
unable to change data directory

### ISSUE THREAD

**Issue by rvschaffer** [nextcloud-snap/nextcloud-snap#2778]
#### Describe the bug
When you change the 'datadirectory' in the config.php file to any folder outside the snap folder, NextCloud cannot access the new folder.

#### To Reproduce
1. sudo nano /var/snap/nextcloud/current/nextcloud/config/config.php
2. set 'datadirectory' => '/nas/data' or some other folder you want.
3. Create the folder /nas/data and set it's permissions to 777 recursively
4. Copy contents of old data directory to the new directlry.
5. Enable external storage with this command: snap connect nextcloud:removable-media
6. Restart CloduNext with sudo snap restart nextcloud.

#### Expected behavior
CloudNext should be able to access the new folder and sabe new files to it.

#### Screenshots
Error
Your data directory is invalid.
Ensure there is a file called ".ocdata" in the root of the data directory.

#### OS/snapd/snap version
OS Version: Ubuntu 24.04 LTS

$ snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  28.0.6snap1  42563  latest/stable  nextcloud✓  -
$

and:

$ snap version
snap    2.63
snapd   2.63
series  16
ubuntu  24.04
kernel  6.8.0-35-generic

#### Logs
The log file is empty!
$ sudo ls -al /var/snap/nextcloud/current/logs/nextcloud.log
-rw-r--r-- 1 root root 0 Jun 12 19:41 /var/snap/nextcloud/current/logs/nextcloud.log

There are a bunch of AppArmor errors in dmesg... I cleared most, changing the profile files,but CloudNext is still unable to access the /nas/data folder.

**Comment by scubamuc** [comment]
@rvschaffer welcome and thanks for your request

see wiki to [change data directory](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Wiki-Change-data-directory) and especially [path to data directory](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Wiki-Change-data-directory#4-path-to-data-directory)

>Error
Your data directory is invalid.
Ensure there is a file called ".ocdata" in the root of the data directory.

the above error is common for incorrect path in config file

**Comment by rvschaffer** [comment]
Thanks for the links! It worked. I was not aware of this nice wiki.
