### ISSUE TITLE
Font not appear in Office

### ISSUE THREAD

**Issue by awatchar** [nextcloud-snap/nextcloud-snap#2790]
#### Describe the bug
A clear and concise description of the bug.

I added TTF font to Office administrative menu but the font does not appear to select in Office tool (Spreadsheet, Word etc.)

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud

and:

    $ snap version

#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).

**Comment by scubamuc** [comment]
@awatchar welcome and thank you for your request.

we cannot support [third party apps](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-CODE-and-Nextcloud-office-for-Nextcloud-snap)  so please Log an issue against the app.
