### ISSUE TITLE
Your data directory and files are probably accessible from the internet.

### ISSUE THREAD

**Issue by Insayne84** [nextcloud-snap/nextcloud-snap#2791]
#### Describe the bug
Since updating to 29.0.2 i am getting the following error:

`Your data directory and files are probably accessible from the internet. The .htaccess file is not working. It is strongly recommended that you configure your web server so that the data directory is no longer accessible, or move the data directory outside the web server document root.`

#### To Reproduce
1. Click on your profile as admin
2. Scroll down to Administration Settings
3. See error

#### Expected behavior
This wasn´t there before, and i wonder if something is wrong with my setup or what has changed?

#### OS/snapd/snap version
Ubuntu Linux 24.04

$snap list nextcloud
```
Name       Version      Rev    Tracking       Publisher    Notes
nextcloud  29.0.2snap1  42890  latest/stable  nextcloud**  -
```
and:
$snap version
```
snap    2.63+24.04
snapd   2.63+24.04
series  16
ubuntu  24.04
kernel  6.8.0-35-generic
```

**Comment by Insayne84** [comment]
This had to do with my locally running nginx instance.  (Nextcloud runs on port 444)
By adding in the default enabled site the following:

```
if ($host = MYHOSTNAME) {
         return 301 https://$host::$server_port$request_uri;
} 
     error_page 497 https://$server_name:$server_port$request_uri;
     return 497; 
```

I was able to get rid of the error.

**Comment by csidirop** [comment]
I have now the same Issue. I've added those lines to my nginx.conf (checked the conf and restarted the service) but the error remained.

$snap list nextcloud 
```
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  29.0.4snap2  43538  latest/stable  nextcloud✓  -
```
