### ISSUE TITLE
Logs are flooded with: Invalid "upload_max_filesize" setting. Invalid quantity "16G": value is out of range, using overflow result for backwards compatibility at Unknown#0

### ISSUE THREAD

**Issue by mgabielk** [nextcloud-snap/nextcloud-snap#2794]
#### Describe the bug
Logs are flooded with:
[PHP] Error: Invalid "upload_max_filesize" setting. Invalid quantity "16G": value is out of range, using overflow result for backwards compatibility at Unknown#0
	PROPFIND /remote.php/dav/files/redacted-user/
	from redacted-ip by redacted-user at 21 Jun 2024, 18:49:34

#### To Reproduce
1. Go to 'Administration settings'
2. Click on 'Logging'
3. See errors

#### Expected behavior
I expect logs not to be flooded.

#### OS/snapd/snap version
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

$ uname -a
Linux raspberrypi 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux

$ snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  29.0.2snap1  42893  latest/stable  nextcloud✓  -

$ snap version
snap      2.61.2
snapd     2.61.2
series    16
raspbian  10
kernel    5.10.103-v7l+
```
#### Logs
Logs attached.
[nextcloud_snap.log](https://github.com/user-attachments/files/15930057/nextcloud_snap.log)

**Comment by scubamuc** [comment]
@mgabielk welcome and thanks for your request.

>Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)

see [requirements](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Installation-requirements) in our [wiki](https://github.com/nextcloud-snap/nextcloud-snap/wiki), so we cannot support your OS here.

from your logs it could be a memory issue but more likely this refers to a withdrawn (redacted) token for one of your users devices (maybe android device syncing calendar and contacts). figure out which device has lost its connection, delete the token in Nextcloud admin settings in the security section, then reconnct the device, relogin and you should be fine. if that doesn't work, you'll have to do some research.

this is certainly not a snap issue

**Comment by mgabielk** [comment]
Thank you for your reply.

I have checked both of my Android devices and both of them work fine, they have Nextcloud app installed from Google Play Store  and I don't use the calendar and contact sync.

Just to be clear, it was me who has redacted the username of the single user, the IP and the domain name of this instance of the Nextcloud from the logs as I see it as a sensitive information and I don't want it to be publicly available on the internet. The data was replaced with "redacted-user", "redacted-ip" and "redacted-domain" strings respectively.

Originally I thought that it was a snap issue because `upload_max_filesize` is defined in `/snap/nextcloud/current/config/php/php.ini` which is part of the snap and is not user configurable AFAIK. It's been a while since I used PHP, so I wasn't sure why 16G is not a valid quantity. Also, IIUC this refers to the upload file size limit and has nothing to do with RAM, so I wasn't looking at that direction.

I understand that Raspbian is not supported, I just thought that this may affect other users too.

**Comment by scubamuc** [comment]
@mgabielk 
>Just to be clear, it was me who has redacted the username of the single user, the IP and the domain name of this instance of the Nextcloud from the logs as I see it as a sensitive information and I don't want it to be publicly available on the internet. The data was replaced with "redacted-user", "redacted-ip" and "redacted-domain" strings respectively.

thanks for pointing that out

>defined in /snap/nextcloud/current/config/php/php.ini which is part of the snap and is not user configurable AFAIK

this is correct

>...I just thought that this may affect other users too.

we haven't come across any similar issues

>I understand that Raspbian is not supported...

thanks for getting back to us

**Comment by mgabielk** [comment]
[A discussion](https://help.nextcloud.com/t/logs-flooded-with-invalid-upload-max-filesize-setting-invalid-quantity-16g-value-is-out-of-range-using-overflow-result-for-backwards-compatibility-at-unknown-0/196355) suggests that this issue will arise on any 32 bit OS where the maximum value of `upload_max_filesize` is `2GB`.  Is 32 bit Ubuntu supported?
