### ISSUE TITLE
Email via PHP doesn't work

### ISSUE THREAD

**Issue by kyrofa** [nextcloud-snap/nextcloud-snap#28]
This is due to Nextcloud's hard-coding of the sendmail path ("/usr/sbin/sendmail"). Perhaps this should be a configurable path, but that requires upstream work. Note that SMTP email seems to work.

**Comment by oparoz** [comment]
Isn't this path "/usr/sbin/sendmail" in 99% of the cases?

**Comment by kyrofa** [comment]
Depends on packaging. Anyway, not in the snap :smiley: .

**Comment by oparoz** [comment]
Yes, but the reason I'm asking is that we usually can't include changes which only affect a few people.
I guess we can try and see if there is some push back.

**Comment by wabuMike** [comment]
Any news on this? PHP mail functionality would be really nice.
@oparoz By the way, this is not affecting only a few people. This affects anyone who installs the nextcloud snap!

**Comment by kyrofa** [comment]
@wabuMike no progress here of which I'm aware. If you want to try proposing the change upstream you could solve this issue.

**Comment by wabuMike** [comment]
@Guard13007 I can't find sendmail anywhere installed, but Nextcloud relies on sendmail installed in /usr/bin/sendmail.

**Comment by wabuMike** [comment]
@kyrofa After some digging, I don't think it's an issue of the Nextcloud server. We should probably to the configuration of the sendmail path in php.ini. 
See this comment in the Nextcloud server configuration [example](https://github.com/nextcloud/server/blob/84a17f082189514814d4e1c8b317cd704cf9b550/config/config.sample.php):

> If you are using PHP mail you must have an installed and working email system on the server. The program used to send email is defined in the ``php.ini`` file.

Nevertheless, sendmail needs to be installed somehow. Since there is no snap existing for sendmail yet, would your preferred way of adding it to download and configuring it in snapcraft.yaml?

**Comment by r4co0n** [comment]
@wabuMike - We would only need a package providing a sendmail-compatible interface, not sendmail itself. I am not aware of an smtp server (bar Exchange) that doesn't provide this. When I looked into this, people were recommending `nullmailer`, but this would leave smtp credentials readable via `ps`, so I searched on.

Right now I plan to use `dma`, the DragonFly Mail Agent, a small tool (apt thinks will weigh in with 152kB when installed) originally developed for DragonFly BSD. I intend to configure it listening on localhost, probably on some non-standard port, and then use the `smtp` send mode for Nextcloud e-mails. For that to work, I may need to grant some additional plug to the snap.

We could wrap this up fairly easily, as a part for this snap or in a separate one, I suppose.

**Comment by wabuMike** [comment]
@r4co0n That sounds really cool. The DragonFly Mail Agent seems to fit really good for this case.
I think we should wrap it in another snap to make it also available for other applications.

**Comment by pachulo** [comment]
@kyrofa do you think that it's feasible to overcome the hard-coding of the sendmail path with snapd layouts? More info on layouts: https://forum.snapcraft.io/t/layouts-re-mapping-snap-directories/1471

**Comment by kyrofa** [comment]
Layouts are contained in snapd v2.36, which hasn't seen a stable release yet and definitely isn't available across distros. Once it is, yeah, it's a possibility.

**Comment by krauthosting** [comment]
@kyrofa Just trying to understand what this was about as using `sendmail` via Postfix on `focal` works:
```
root@nextcloud:~# nextcloud.occ config:list | jq .system | grep mail
  "mail_smtpmode": "sendmail",
  "mail_sendmailmode": "pipe",
  "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
  "mail_smtpport": "25",
  "mail_smtpauth": "false",
  "mail_smtptimeout": "10",
  "mail_from_address": "***REMOVED SENSITIVE VALUE***",
  "mail_domain": "***REMOVED SENSITIVE VALUE***"
```
Guessing blindly but for Postfix we need the `pipe` mode added in upstream via https://github.com/nextcloud/server/pull/12424
Are we sure this wasn't about snap with outside `/usr/sbin/sendmail` but rather just? https://github.com/nextcloud/server/issues/11281
We just confirmed upstream docs with occ and Ansible combining this Snap and Postfix `3.4.13-0ubuntu1.2`:
https://docs.nextcloud.com/server/22/admin_manual/configuration_server/email_configuration.html#sendmail

**Comment by kyrofa** [comment]
This is an ancient issue @krauthosting, it may very well no longer be valid. I haven't tested it for ages.

**Comment by krauthosting** [comment]
@kyrofa Yep then let's not distract you from your good work and close with this reference :+1:

**Comment by krauthosting** [comment]
Wait! Trying to replicate this now on a second system for QA i bumped now into this error on mail test:  
```
{"reqId":"tZpTbwW1tOAFTfGEvvp4","level":3,"time":"2021-11-11T23:26:27+00:00","remoteAddr":"127.0.0.1","user":"XXX","app":"PHP","method":"POST","url":"/index.php/settings/admin/mailtest","message":"fwrite(): Write of 14604 bytes failed with errno=32 Broken pipe at /snap/nextcloud/28586/htdocs/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php#223","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0","version":"22.2.0.2","exception":{"Exception":"Error","Message":"fwrite(): Write of 14604 bytes failed with errno=32 Broken pipe at /snap/nextcloud/28586/htdocs/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php#223","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/snap/nextcloud/28586/htdocs/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php","line":223,"function":"fwrite"},{"file":"/snap/nextcloud/28586/htdocs/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/AbstractFilterableInputStream.php","line":168,"function":"doCommit","class":"Swift_Transport_StreamBuffer","type":"->"},{"file":"/snap/nextcloud/28586/htdocs/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/AbstractFilterableInputStream.php","line":146,"function":"doWrite","class":"Swift_ByteStream_AbstractFilterableInputStream","type":"->"},{"file":"/snap/nextcloud/28586/htdocs/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/SendmailTransport.php","line":130,"function":"flushBuffers","class":"Swift_ByteStream_AbstractFilterableInputStream","type":"->"},{"file":"/snap/nextcloud/28586/htdocs/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php","line":71,"function":"send","class":"Swift_Transport_SendmailTransport","type":"->"},{"file":"/snap/nextcloud/28586/htdocs/lib/private/Mail/Mailer.php","line":204,"function":"send","class":"Swift_Mailer","type":"->"},{"file":"/snap/nextcloud/28586/htdocs/apps/settings/lib/Controller/MailSettingsController.php","line":157,"function":"send","class":"OC\\Mail\\Mailer","type":"->"},{"file":"/snap/nextcloud/28586/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"sendTestMail","class":"OCA\\Settings\\Controller\\MailSettingsController","type":"->"},{"file":"/snap/nextcloud/28586/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/snap/nextcloud/28586/htdocs/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/snap/nextcloud/28586/htdocs/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/snap/nextcloud/28586/htdocs/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/snap/nextcloud/28586/htdocs/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/snap/nextcloud/28586/htdocs/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"618da6dca49c0"}
```
So must assume i did a mistake in confirming it's working on the first system that had SMTP config before.  
Hence this seems after rechecking still broken and inside the Snap the sendmail option still can't be used.  
Funny enough we tried to switch after stuck mail queue as Postfix is more reliable and better to monitor :sweat_smile:
