### ISSUE TITLE
Just to share a snap-backup script toolset

### ISSUE THREAD

**Issue by sbe-arg** [nextcloud-snap/nextcloud-snap#2819]
I made this specifically for nextcloud, but I have been using for all my snaps for a while now.

https://github.com/sbe-arg/snap-backups

**Comment by scubamuc** [comment]
@sbe-arg, thanks for sharing your script.

now I'm no developer and frankly your script is barely readable for me 😯

would you care to document and comment that script more clearly? 

I'd be prepared to link it to  [Backup, restore & migrate](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Backup-and-Restore) if you and @nextcloud-snap/developers agree.

**Comment by sbe-arg** [comment]
Will add more details in the repo.

**Comment by scubamuc** [comment]
@pachulo 

> I'd be prepared to link it to [Backup, restore & migrate](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Backup-and-Restore) if you and @nextcloud-snap/developers agree.

freindly reminder...

**Comment by scubamuc** [comment]
Added reference to [Backup, restore & migrate](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Backup-and-Restore)
