### ISSUE TITLE
issues after update to 29.0.2snap1 stable

### ISSUE THREAD

**Issue by mattish91** [nextcloud-snap/nextcloud-snap#2842]
#### Describe the bug
Some odd errors showing up in Overview in latest 29.0.2snap1

#### To Reproduce
Update to 29.0.2snap1 or latest?

#### Expected behavior
Not having these odd errors.
Is a rollback the best option?

#### Screenshots
Output from the nextcloud Overview section as it failes to check status, i also noticed that the fixer service didn't end well.
`An exception occured while running the setup check: TypeError: OCA\DAV\SetupChecks\WebdavEndpoint::OCA\Settings\SetupChecks\{closure}(): Argument #1 ($host) must be of type string, array given in /snap/nextcloud/42890/htdocs/apps/settings/lib/SetupChecks/CheckServerResponseTrait.php:69 Stack trace: #0 [internal function]: OCA\DAV\SetupChecks\WebdavEndpoint->OCA\Settings\SetupChecks\{closure}() #1 /snap/nextcloud/42890/htdocs/apps/settings/lib/SetupChecks/CheckServerResponseTrait.php(69): array_map() #2 /snap/nextcloud/42890/htdocs/apps/settings/lib/SetupChecks/CheckServerResponseTrait.php(96): OCA\DAV\SetupChecks\WebdavEndpoint->getTestUrls() #3 /snap/nextcloud/42890/htdocs/apps/dav/lib/SetupChecks/WebdavEndpoint.php(67): OCA\DAV\SetupChecks\WebdavEndpoint->runRequest() #4 /snap/nextcloud/42890/htdocs/lib/private/SetupCheck/SetupCheckManager.php(51): OCA\DAV\SetupChecks\WebdavEndpoint->run() #5 /snap/nextcloud/42890/htdocs/apps/settings/lib/Controller/CheckSetupController.php(179): OC\SetupCheck\SetupCheckManager->runAll() #6 /snap/nextcloud/42890/htdocs/lib/private/AppFramework/Http/Dispatcher.php(232): OCA\Settings\Controller\CheckSetupController->check() #7 /snap/nextcloud/42890/htdocs/lib/private/AppFramework/Http/Dispatcher.php(138): OC\AppFramework\Http\Dispatcher->executeController() #8 /snap/nextcloud/42890/htdocs/lib/private/AppFramework/App.php(184): OC\AppFramework\Http\Dispatcher->dispatch() #9 /snap/nextcloud/42890/htdocs/lib/private/Route/Router.php(338): OC\AppFramework\App::main() #10 /snap/nextcloud/42890/htdocs/lib/base.php(1050): OC\Route\Router->match() #11 /snap/nextcloud/42890/htdocs/index.php(49): OC::handleRequest() #12 {main}`

#### OS/snapd/snap version
Ubuntu 22.04

    Name       Version      Rev    Tracking       Publisher      Notes
nextcloud  29.0.2snap1  42890  latest/stable  nextcloud✓  -

snap    2.63+22.04
snapd   2.63+22.04
series  16
ubuntu  22.04
kernel  5.15.0-116-generic

Might also be worth to note that im running this behind NPM, that have always worked fine, anything new in this department that i might need to know of in case thats the culprit?

#### Logs
I wasn't able to fit it all in this thread and not even in pastebin limited to 512KB, so i had to spin up my own docker privatebin xD here:
https://paste.dev.mspot.se/?2e8deee7a2704b28#7JiZP9hnETVR6eMUEqsK5r7JM27feNXfYnSppgdNayjS

EDIT: Updated the link as i saw it were to be expired after 6 days, this should now be permanently availiable if ever needed after that period.

**Comment by scubamuc** [comment]
@mattish91 welcome and thanks for your request.

> Might also be worth to note that im running this behind NPM, that have always worked fine, anything new in this department that i might need to know of in case thats the culprit?

check out our wiki for [NPM settings from Nextcloud 29](https://github.com/nextcloud-snap/nextcloud-snap/wiki/NGINX-proxy-manager)

since 29.0.4snap1 was released yesterday, you'll be getting another update soon. there were upstream issues in 29.0.2 but I cannot confirm as your logs are unreadable. 

recommend you truncate your logs `sudo truncate -s 0 /var/snap/nextcloud/current/logs/nextcloud.log`, wait a while for the message to reappear and then run the [debugging script](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Issue-Debugging-Scripts#debugging-script) and post here.

see also [getting help](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Getting-help)

**Comment by mattish91** [comment]
Thanks for the updated NPM config, i did set that correctly now, how ever i also tried to run the truncate script an hour ago with no real change. the log is still to long to fit in a paste here or in the pastebin.com (1.2MB)

I also got the new 29.0.4 now, but problem persists for me.

**From Overview:**
An exception occured while running the setup check: TypeError: OCA\DAV\SetupChecks\WebdavEndpoint::OCA\Settings\SetupChecks\{closure}(): Argument #1 ($host) must be of type string, array given in /snap/nextcloud/43538/htdocs/apps/settings/lib/SetupChecks/CheckServerResponseTrait.php:69 Stack trace: #0 [internal function]: OCA\DAV\SetupChecks\WebdavEndpoint->OCA\Settings\SetupChecks\{closure}() #1 /snap/nextcloud/43538/htdocs/apps/settings/lib/SetupChecks/CheckServerResponseTrait.php(69): array_map() #2 /snap/nextcloud/43538/htdocs/apps/settings/lib/SetupChecks/CheckServerResponseTrait.php(96): OCA\DAV\SetupChecks\WebdavEndpoint->getTestUrls() #3 /snap/nextcloud/43538/htdocs/apps/dav/lib/SetupChecks/WebdavEndpoint.php(67): OCA\DAV\SetupChecks\WebdavEndpoint->runRequest() #4 /snap/nextcloud/43538/htdocs/lib/private/SetupCheck/SetupCheckManager.php(51): OCA\DAV\SetupChecks\WebdavEndpoint->run() #5 /snap/nextcloud/43538/htdocs/apps/settings/lib/Controller/CheckSetupController.php(183): OC\SetupCheck\SetupCheckManager->runAll() #6 /snap/nextcloud/43538/htdocs/lib/private/AppFramework/Http/Dispatcher.php(232): OCA\Settings\Controller\CheckSetupController->check() #7 /snap/nextcloud/43538/htdocs/lib/private/AppFramework/Http/Dispatcher.php(138): OC\AppFramework\Http\Dispatcher->executeController() #8 /snap/nextcloud/43538/htdocs/lib/private/AppFramework/App.php(184): OC\AppFramework\Http\Dispatcher->dispatch() #9 /snap/nextcloud/43538/htdocs/lib/private/Route/Router.php(338): OC\AppFramework\App::main() #10 /snap/nextcloud/43538/htdocs/lib/base.php(1050): OC\Route\Router->match() #11 /snap/nextcloud/43538/htdocs/index.php(49): OC::handleRequest() #12 {main}

Debug script after truncate:
https://paste.dev.mspot.se/?093d64951f4274fd#9MxX9rpR1ZbNCSG2Rbxr7dfTG8RjHLEBxC8jw6FENXzs

**Comment by scubamuc** [comment]
@mattish91 
>EDIT: Started to look trough the debug log now, and i realized something is messed up in my config file:
```
        "trusted_domains": {
            "0": "sync.mspot.se",
            "3": {
                "192.168.1.179": ""
            },
            "1": "192.168.1.*"
        },
```
see [Hosts & FQDN configuration](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Hosts-and-FQDN-for-Nextcloud-snap) and be sure to replace those IP's with FQDN also [correct iteration (0,1,2,3...)](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-config.php#setting-trusted-domains).

 >Solved the original issue, but as i turned off https as per the NPM i have an error with HSTS instead xD

you could disable HSTS see [ssl configuration](https://github.com/nextcloud-snap/nextcloud-snap/wiki/NGINX-proxy-manager#ssl-configuration)
