### ISSUE TITLE
Foreign Key Collision in Migration causes Stuck in Maintenance

### ISSUE THREAD

**Issue by ChrisWitt** [nextcloud-snap/nextcloud-snap#2843]
#### Describe the bug
Stug in Maintenance Mode. Log file suggestion migration error. With forein key collision. See logs below.

#### To Reproduce
I'm trying to start nextcloud snap

>snap start nextcloud

guess autoupdate took place

#### Expected behavior
Working database migration :)

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  29.0.2snap1  42890  latest/stable  nextcloud✓  -

and:

snap    2.61.4
snapd   2.61.4
series  16
debian  12
kernel  6.1.0-23-amd64

#### Logs
sorry i was not able to use
https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts
mostly got no sudo errors

Error Message found in 
/var/snap/nextcloud/common/nextcloud/data/nextcloud.log 

`
{"reqId":"fBzx5fvHuNT0dEYSKggo","level":3,"time":"2024-07-25T19:10:43+00:00","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":"Foreign key name \"feed\" for table \"oc_news_items\" collides with the constraint on table \"oc_news_items\".","userAgent":"--","version":"28.0.6.1","exception":{"Exception":"InvalidArgumentException","Message":"Foreign key name \"feed\" for table \"oc_news_items\" collides with the constraint on table \"oc_news_items\".","Code":0,"Trace":[{"file":"/snap/nextcloud/42890/htdocs/lib/private/DB/MigrationService.php","line":443,"function":"ensureUniqueNamesConstraints","class":"OC\\DB\\MigrationService","type":"->"},{"file":"/snap/nextcloud/42890/htdocs/lib/private/DB/MigrationService.php","line":401,"function":"migrateSchemaOnly","class":"OC\\DB\\MigrationService","type":"->"},{"file":"/snap/nextcloud/42890/htdocs/lib/private/Installer.php","line":574,"function":"migrate","class":"OC\\DB\\MigrationService","type":"->"},{"file":"/snap/nextcloud/42890/htdocs/lib/private/Installer.php","line":532,"function":"installShippedApp","class":"OC\\Installer","type":"::"},{"file":"/snap/nextcloud/42890/htdocs/lib/private/Updater.php","line":278,"function":"installShippedApps","class":"OC\\Installer","type":"::"},{"file":"/snap/nextcloud/42890/htdocs/lib/private/Updater.php","line":129,"function":"doUpgrade","class":"OC\\Updater","type":"->"},{"file":"/snap/nextcloud/42890/htdocs/core/Command/Upgrade.php","line":216,"function":"upgrade","class":"OC\\Updater","type":"->"},{"file":"/snap/nextcloud/42890/htdocs/3rdparty/symfony/console/Command/Command.php","line":298,"function":"execute","class":"OC\\Core\\Command\\Upgrade","type":"->"},{"file":"/snap/nextcloud/42890/htdocs/3rdparty/symfony/console/Application.php","line":1040,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->"},{"file":"/snap/nextcloud/42890/htdocs/3rdparty/symfony/console/Application.php","line":301,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/snap/nextcloud/42890/htdocs/3rdparty/symfony/console/Application.php","line":171,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/snap/nextcloud/42890/htdocs/lib/private/Console/Application.php","line":213,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/snap/nextcloud/42890/htdocs/console.php","line":102,"function":"run","class":"OC\\Console\\Application","type":"->"},{"file":"/snap/nextcloud/42890/htdocs/occ","line":11,"args":["/snap/nextcloud/42890/htdocs/console.php"],"function":"require_once"}],"File":"/snap/nextcloud/42890/htdocs/lib/private/DB/MigrationService.php","Line":701,"message":"Foreign key name \"feed\" for table \"oc_news_items\" collides with the constraint on table \"oc_news_items\".","exception":{},"CustomMessage":"Foreign key name \"feed\" for table \"oc_news_items\" collides with the constraint on table \"oc_news_items\"."}}
`

## Thoughts
I suspected I had an news app installed which has trouble in the update process. 
But 
> nextcloud.occ app:list
does not list a news app or at least none I would identify as such

`
Enabled:
  - activity: 2.21.1
  - audioplayer: 3.4.1
  - bookmarks: 14.2.2
  - calendar: 4.7.13
  - circles: 29.0.0-dev
  - cloud_federation_api: 1.12.0
  - comments: 1.19.0
  - contacts: 6.0.0
  - contactsinteraction: 1.10.0
  - dashboard: 7.9.0
  - dav: 1.30.1
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.0
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - firstrunwizard: 2.18.0
  - gpoddersync: 3.9.0
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - nextcloud_announcements: 1.18.0
  - notes: 4.10.1
  - notifications: 2.17.0
  - oauth2: 1.17.0
  - password_policy: 1.19.0
  - photos: 2.5.0
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - recommendations: 2.1.0
  - related_resources: 1.4.0
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - support: 1.12.0
  - survey_client: 1.17.0
  - systemtags: 1.19.0
  - tasks: 0.16.0
  - text: 3.10.0
  - theming: 2.4.0
  - twofactor_backupcodes: 1.18.0
  - twofactor_totp: 11.0.0-dev
  - user_status: 1.9.0
  - viewer: 2.3.0
  - weather_status: 1.9.0
  - workflowengine: 2.11.0
Disabled:
  - admin_audit: 1.19.0
  - bruteforcesettings: 2.9.0
  - deck: 1.12.4 (installed 1.12.4)
  - drawio: 3.0.2 (installed 3.0.2)
  - encryption: 2.17.0
  - files_downloadlimit: 2.0.0
  - files_external: 1.21.0
  - files_readmemd: 3.0.0 (installed 3.0.0)
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - maps: 1.4.0 (installed 1.4.0)
  - spreed: 18.0.10 (installed 18.0.10)
  - suspicious_login: 7.0.0
  - user_ldap: 1.20.0

`

My next guess would be to extract a database dump and look at after reimport in a tool like dbeaver.

But I'd happily take any advice on how to fix this issue. Or any hint to identify the cause.

**Comment by scubamuc** [comment]
Hi @ChrisWitt welcome and thanks for your request.
>I suspected I had an news app installed which has trouble in the update process.

yeah, that's confirmed. the [news app](https://github.com/nextcloud/news/issues/2585) is the culprit. this is an upstream issue see https://github.com/nextcloud/news/issues/2585

- recommend you [revert](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-nextcloud-snap-stopped-working-after-an-update-what-can-i-do)
- make a backup of your news feeds (backup opml)
- remove the news app `sudo nextcloud.occ app:remove appname`
- [refresh](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Managing-Nextcloud-snap-with-Snap#update-nextcloud-snap) manually 

>debian 12
>sorry i was not able to use
>https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts
>mostly got no sudo errors

see [requirements](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Installation-requirements) especially [why Ubuntu is the only supported distribution](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Why-Ubuntu-is-the-only-supported-distro)

so we can agree that this is a third party issue and not a snap issue?
please close here if you are d'accord

**Comment by ChrisWitt** [comment]
snap revert is not working

>snap revert nextcloud
error: cannot revert "nextcloud": no revision to revert to

I had not enough space on the device. I adopted the strategy of removing the old revision on each update. As otherwise a new version would not start.

Is there any way to trigger a rollback of the database to the pre update state?
My only goal would be to extract calendar and contacts data.

Good route might be to move to docker. As you stated, not supporting non Ubuntu System and everything else I run is in docker.

So if you have any advice how to extract my data I'd be very happy :)

**Comment by scubamuc** [comment]
@ChrisWitt,
>I adopted the strategy of removing the old revision on each update.

yeah... that's the caveat, no snapshot no revert!

if the database doesn't start up, you will not be able to recover any data.

see [where is my stuff](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Default-path#where-is-my-stuff) and [disaster recovery](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Getting-help#disaster-recovery) as well as [backup your data](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Getting-help#backup-your-data)

-----
>My only goal would be to extract calendar and contacts data.

did you by any chance enable automatic contacts backup in you davx5 sync client on android? if you did, there's a chance you'll find contact exports in `Contacts-Backup`directory in ` /var/snap/nextcloud/common/nextcloud/data ` somewhere.

![grafik](https://github.com/user-attachments/assets/f1d80fe1-9adc-45ca-adfa-35e490cf7148)
![grafik](https://github.com/user-attachments/assets/e0de9411-2955-4ca2-8d3d-b009924da345)

----

>Good route might be to move to docker. As you stated, not supporting non Ubuntu System and everything else I run is in docker.

yeah maybe, that's up to you. but you'll need a backup plan for docker too and its not quite as easy as taking a snap snapshot unless you set it up in a VM or LXC container...

**Comment by ChrisWitt** [comment]
I ended up using nextcloud.mysql-client to drop the problematic table
>nextcloud.mysql-client
>show databases;
>connect nextcloud;
>drop table oc_news_items;

I might have deleted the news app in previous attempts to get the system running again:
>snap run nextcloud.occ config:app:delete news

After the table drop. 
>snap stop nextcloud
>snap start nextcloud
got my instance back up.

Now that i regained access I vaguely remembered the auto backup feature you mentioned.

Will look in to backup and recovery to prevent future mishaps. Will try to find out which apps are supported.

**Comment by scubamuc** [comment]
@ChrisWitt 

 >   got my instance back up.

well done 🤿👌
