### ISSUE TITLE
Snap Nextcloud seems to have not enabled imagic

### ISSUE THREAD

**Issue by samfor12** [nextcloud-snap/nextcloud-snap#2847]
I installed the snap Nextcloud command as follows
One click installation of Nextcloud
```

sudo apt-get update

sudo apt install snapd

sudo snap install nextcloud

#（SSL enable）
sudo /snap/bin/nextcloud.enable-https lets-encrypt

I didn't do anything else and reported this situation in the setup check
```

`"The PHP module “imagick” is not enabled although the theming app is. For favicon generation to work correctly, you need to install and enable this module."`

i use Latest version to nextcloud

**I hope to install this PHP Imagick tool, but what do I need to do?**

**nextcloud installed app(s)**

Activity
Calendar
Collaborative tags
Comments
Contacts
Contacts Interaction
Dashboard
Default encryption module
Deleted files
End-to-End Encryption
Federation
File reminders
File sharing
Files download limit
First run wizard
Log Reader
Mail
Monitoring
Nextcloud announcements
Notes
Notifications
ONLYOFFICE
Password policy
PDF viewer
Photos
Privacy
Recommendations
Related Resources
Share by mail
Support
Talk
Teams
Text
Two-Factor TOTP Provider
Usage survey
User status
Weather status

**Comment by scubamuc** [comment]
Hi there @samfor12  and welcome,
> I hope to install this PHP Imagick tool, but what do I need to do?

... see [FAQ's](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#imagick-php-module-not-enabled)
