### ISSUE TITLE
Collabora stops working after a few hours

### ISSUE THREAD

**Issue by sbe-arg** [nextcloud-snap/nextcloud-snap#2857]
#### Describe the bug
I have collabora working as per https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-CODE-and-Nextcloud-office-for-Nextcloud-snap and have opened an upstream issue here https://github.com/nextcloud/richdocuments/issues/3936

```
I have a weird behavior going on.

Every 2-3 days I have the need to edit documents. Each time I try to load any document I get the error for "Unable to load document" after 2-3 retries it starts working and works for a few hours trough the day without any issue and then the issue happens again.

Is there any sort of sleeping mechanism or warm-up required? But is the only think i can think of at the moment. Like if the Development server stops after X time and gets started only when a file is opened.

I don't mind If I it will waste a bit more resources but I'd prefer to have it running warm all the time.
```

Is there anything on the nextcloud/snap side that gets apps to sleep to save resources or auto restarts the nextcloud server? Have checked on the host side that nothing is restarting the nextcloud snap, the server is not doing much aside of nextcloud is 24/7 on and is actively syncing files to many devices trough the day.

I'm a bit lost as there are no logs anywhere of any error other than the visual error timing out or not connecting and then working like a charm for the entire day.

**Comment by scubamuc** [comment]
@sbe-arg, thank for opening those issues at [Nextcloud help](https://help.nextcloud.com/t/developer-edition-stops-working-after-a-few-hours/201329) and at [app developers](https://github.com/nextcloud/richdocuments/issues/3936).

we're using CODE installed as per [CODE & Nextcloud Office configuration](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-CODE-and-Nextcloud-office-for-Nextcloud-snap) on a couple of instances without any issues.

> Is there anything on the nextcloud/snap side that gets apps to sleep to save resources or auto restarts the nextcloud server?

no, not that I know of.

you could try if the [debugging script](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Issue-Debugging-Scripts#debugging-script) shows more output to get to the bottom of this.

There is no harm in repeating these steps (in sequence) are required to reconfigure/reset and configure CODE & Nextcloud office on Nextcloud snap.

  1. **disable CODE**: `sudo nextcloud.occ app:disable richdocumentscode`
  2. **disable Office**: `sudo nextcloud.occ app:disable richdocuments` 
  3. **delete configs**: `sudo nextcloud.occ config:app:delete richdocuments public_wopi_url`
  4. **delete configs**: `sudo nextcloud.occ config:app:delete richdocuments wopi_url`
  5. **enable Office**: `sudo nextcloud.occ app:enable richdocuments`
  6. **enable CODE**: `sudo nextcloud.occ app:enable richdocumentscode`

- Loading CODE after fresh install, app upgrade or after server restart may **take a while**, so be patient. See [here](https://github.com/CollaboraOnline/richdocumentscode#implementation)
  - some folks suggest installing `libfuse2` on host `sudo apt install libfuse2`

**Comment by sbe-arg** [comment]
Already tried those commands and reinstalling the CODE app nothing solves it.

It is not super annoying and might not be an issue for other people as "it works" but it is annoying to me to have this random warming issues every few days and no logs anywhere.

**Comment by scubamuc** [comment]
@sbe-arg can you screenshot the warning?

**Comment by sbe-arg** [comment]
Will share one when I get the next one likely tomorrow

**Comment by sbe-arg** [comment]
The error is "Unable to connect to the server" but refreshing 10sec after makes it work and there is already 3 clones (of me) viewing the file by then.

Ill try to record screen.

**Comment by sbe-arg** [comment]
I still get this sporadically after snap nextcloud updates or system restarts.

I think the app does not autostart we can probably close. Ill follow up with the collabora team
