### ISSUE TITLE
Nextcloud Office: Namespaces wont' work out of the box inside of a snap

### ISSUE THREAD

**Issue by pedropintosilva** [nextcloud-snap/nextcloud-snap#2864]
#### Describe the bug

I'm voicing here something that @caolanm has noted WRT Nextcloud snap.

It seems namespaces won't work out of the box inside a snap. The Nextcloud snap would need some extra permissions, please see https://snapcraft.io/docs/supported-interfaces.

So, probably the best would be to add a "userns" (https://snapcraft.io/docs/userns-interface) or the "browser-support"(https://snapcraft.io/docs/browser-support-interface) setting to the Nextcloud snap.

With one of those option set, the Collabora Online AppImage inside the snap could then (I believe) use namespaces.

Notes: Changing snap permission might trigger some extra review in the snapstore.

**Comment by scubamuc** [comment]
@pedropintosilva thanks for mrntioning that possible solution,

@nextcloud-snap/developers would you look at this please. 
@Pilzinsel64 could this be considered as an OOTB method?

**Comment by Pilzinsel64** [comment]
Will need a bit investigation for. Might take a bit time tomorrow to read about. Never heard of that before and even didn't use CODE for a whole now as I switched over to OnlyOffice for some general reason (non-snap related).

**Comment by kyrofa** [comment]
Both of those interfaces are pretty privileged. Especially the userns interface will probably require manual review. Given how many issues we have with compatibility with document editing in the snap, not sure it's worth it.

**Comment by scubamuc** [comment]
@kyrofa 
> Given how many issues we have with compatibility with document editing in the snap, not sure it's worth it.

I'd like to say "few" issues since this [CODE & Nextcloud Office configuration](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-CODE-and-Nextcloud-office-for-Nextcloud-snap) is available and in my default PR-testplan... this has bee running without issues for months on my productive instance and on corporate productive instance.
