### ISSUE TITLE
Fedora Server 40 - Snap move nextcloud data folder

### ISSUE THREAD

**Issue by Badwolf15001** [nextcloud-snap/nextcloud-snap#2865]
#### Describe the bug
Not a bug, but I would like to find out what is the best way to move the Nextcloud data folder to a new directory.

#### To Reproduce
I follow these [Steps](https://snapcraft.io/install/nextcloud/fedora#install) and it installs correctly

#### Expected behavior
Nextcloud works only if you allow Ports 80 & 443 through the Fedora Server 40 Firewall

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud
**nextcloud  29.0.4snap2  43538  latest/stable  nextcloud**

and:

    $ snap version
**snap    2.63-0.fc40
snapd   2.63-0.fc40
series  16
fedora  40
kernel  6.10.6-200.fc40.x86_64**

#### Logs
N/A

**Comment by scubamuc** [comment]
@Badwolf15001 welcome and thanks for your request.
> Not a bug, but I would like to find out what is the best way to move the Nextcloud data folder to a new directory.

so I'll gently nudge you in the right direction :+1: 

- see [Nextcloud snap wiki](https://github.com/nextcloud-snap/nextcloud-snap/wiki)
- see [Change data directory](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Wiki-Change-data-directory)
- especially [Requirements](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Installation-requirements) and why [Ubuntu is the only supported distribution](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Why-Ubuntu-is-the-only-supported-distro) for Nextcloud snap.
