### ISSUE TITLE
Object Name and Folder Structure When Using S3 Storage (IDrive e2) as Primary Storage

### ISSUE THREAD

**Issue by fsyamala** [nextcloud-snap/nextcloud-snap#2874]
Nextcloud version : Nextcloud Hub 8 (29.0.4)

When I connect the IDrive e2 bucket as External Storage in Nextcloud, then the object name, folder name, and structure stored in the bucket are the same as the file name, folder name, and structure in Nextcloud or my computer. But if I connect the IDrive e2 bucket as Primary Storage in Nextcloud, by implementing it as the source below (config.php):
https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/primary_storage.html
```
'objectstore' => [
'class' => '\\OC\\Files\\ObjectStore\\S3',
     'arguments' => [
          'bucket' => 'xxxx',
          'hostname' => 'xxxx',
          'key' => 'xxxx',
          'secret' => 'xxxx',
          'port' => 443,
          'use_ssl' => true,
          'use_path_style' => true,
     ],
],
```
then the object name changes to sequential numbers that do not reflect or are different from the file name or folder name in Nextcloud or my computer. This is messy, and I will have difficulty if I have to download it directly from the IDrive e2 website.

Why does this happen? And is there a way I can do to make the object name regular, when I use IDrive e2 as Primary Storage, just like when I use IDrive e2 as External Storage.

I’ve asked this question to IDrive support either. If I get any useful answers or insights, I will forward them here as well.

Thank you.
![Cuplikan layar 2024-09-08 103353](https://github.com/user-attachments/assets/59d86734-fbe4-4063-b5b7-c827743f7dd3)
![Cuplikan layar 2024-09-08 103500](https://github.com/user-attachments/assets/64d67b44-1c9a-41c1-8d49-918be4f17385)

**Comment by scubamuc** [comment]
https://help.nextcloud.com/t/object-name-and-folder-structure-when-using-s3-storage-idrive-e2-as-primary-storage/203276
Issue created upstream ✅... closing here
