### ISSUE TITLE
nextcloud.occ not found

### ISSUE THREAD

**Issue by eapo** [nextcloud-snap/nextcloud-snap#2877]
#### Describe the bug
After a fresh install on Raspberry 5 with Debian 1:6.6.47 running `sudo nextcloud.occ` resulting the following error:
`sudo: nextcloud.occ: command not found`

#### To Reproduce
1. install nextcloud-snap
2. run `sudo nextcloud.occ`
3. See error

#### Screenshot
```
$ nextcloud.occ
chmod: changing permissions of '/tmp/pids': Operation not permitted
$ sudo nextcloud.occ
sudo: nextcloud.occ: command not found
$ uname -a
Linux mackopi 6.6.47+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.47-1+rpt1 (2024-09-02) aarch64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
```

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud
    Name       Version      Rev    Tracking       Publisher   Notes
    nextcloud  29.0.6snap1  44323  latest/stable  nextcloud✓  -

and:

```bash
$ snap version
snap    2.63
snapd   2.63
series  16
debian  12
kernel  6.6.47+rpt-rpi-2712
```

#### Logs
- [nextcloud.debug.txt ~ pixeldrain](https://pixeldrain.com/u/UU3HGy4h)

**Comment by scubamuc** [comment]
@eapo welcome and thanks for your request.

see https://github.com/nextcloud-snap/nextcloud-snap/wiki/OCC-management-console#nextcloud-management-console-usage

Some systems don't add /snap/bin to the PATH. Try

`sudo /snap/bin/nextcloud.occ`

**Comment by eapo** [comment]
Now I see [Why Ubuntu is the only supported distro](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Why-Ubuntu-is-the-only-supported-distro), thank you.
