### ISSUE TITLE
documentation, FAQ's -- mimetyp migrations

### ISSUE THREAD

**Issue by scubamuc** [nextcloud-snap/nextcloud-snap#2878]
edit [FAQ's](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's)

[One or more mimetype migrations are available...](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-one-or-more-mimetype-migrations-are-available)

![grafik](https://github.com/user-attachments/assets/13bb5d99-820e-40f0-80ae-25dbbbdfb6a4)

**Comment by pachulo** [comment]
> will the discussed mimetypes migrations be handled by the nextcloud-fixer?

As I understand the warning:

> Migrating the mimetypes take a long time on larger instances so this is not done automatically during upgrades. Use the command `occ maintenance:repair --include-expensive` to perform the migrations.

I would vote for a no, because upstream already opted for it to be a manual step not executed during updates, but I'm open to feedback.

What's your take here @kyrofa ?

**Comment by scubamuc** [comment]
> upstream already choosed for it to be a manual step

I've been effected on two productive instances;

- Personal instance, small DB (300-400MiB) with good resources, migration was super quick
- Corporate instance DB (1 GiB +) with ample resources and migration was almost instantaneous

**Comment by kyrofa** [comment]
I don't have a good concept of how long this takes, exactly, but it sure sounds like _other_ things the Nextcloud folks have left up to their users that [we try to take care of for them](https://github.com/nextcloud-snap/nextcloud-snap/blob/master/src/nextcloud/fixes/existing-install/6_add-missing-primary-keys.sh). Seems to me like something we can handle in the fixer.

**Comment by Pilzinsel64** [comment]
I agree with @kyrofa while adding missing indices also may take long and is an additional step. I had to do that on all my production instances and it took few seconds only only small instances. I have no experience how it would scale on big instances, I don't think it would go up more then half a minute.

**Comment by kyrofa** [comment]
Note that the fixer runs in the background, too. Unless this requires maintenance mode, the user may not even notice.
