### ISSUE TITLE
Proposal for 2 articles to help improve the wiki

### ISSUE THREAD

**Issue by yannicklescure** [nextcloud-snap/nextcloud-snap#2886]
@scubamuc Following [our previous conversation](https://github.com/nextcloud-snap/nextcloud-snap/issues/2736), I wrote two articles that I think could help the community.

1. [How to Install and Configure Collabora Online on a Separate Server for Nextcloud Snap](https://www.codecicada.com/blog/install-configure-collabora-online-nextcloud-snap-server)
2. [Customizing Nextcloud Themes and Emails for Multiple Domains](https://www.codecicada.com/blog/custom-themes-email-nextcloud-multiple-domains)

Here are the markdown files.
[custom-themes-email-nextcloud-multiple-domains.md](https://github.com/user-attachments/files/17046484/custom-themes-email-nextcloud-multiple-domains.md)
[install-configure-collabora-online-nextcloud-snap-server.md](https://github.com/user-attachments/files/17046485/install-configure-collabora-online-nextcloud-snap-server.md)

If you'd like to add this to the wiki, I'd really appreciate it if you could include some source links back to my blog articles. Thanks!

**Comment by scubamuc** [comment]
@nextcloud-snap/developers if you're all d'accord I'd be prepared to add this to wiki:
[custom-themes-email-nextcloud-multiple-domains.md](https://github.com/user-attachments/files/17046484/custom-themes-email-nextcloud-multiple-domains.md)
[install-configure-collabora-online-nextcloud-snap-server.md](https://github.com/user-attachments/files/17046485/install-configure-collabora-online-nextcloud-snap-server.md)

thanks to @yannicklescure for his great effort.

**Comment by yannicklescure** [comment]
> see #2888

I like the concept of the wiki-md repo. How would that work with the current wiki. Would it be a section that suggest a list of links ?

**Comment by scubamuc** [comment]
Yeah... something like that. feel free to join in the conversation #2888
