### ISSUE TITLE
Shared folder moving not possible anymore

### ISSUE THREAD

**Issue by dosmehobbit** [nextcloud-snap/nextcloud-snap#2887]
#### Describe the bug
It is not possible for me to move a folder which was shared with me into another location. It was possible in the past. Now there is an error which says: 

#### To Reproduce
1. User B shares User A a directory 'Shared'
2. User A receives the shared directory in /SharedWithMe/Shared
3. User A wants to move the directory via web-surface to the home directory
4. Error (in German): "Verschieben oder Kopieren" ist bei einigen Element fehlgeschlagen (Englisch: "Move or copy action is not possible....

#### Expected behavior
I would expect the folder to be moved from /SharedWithMe to home directory.

#### Screenshots
![20240919230906_screenshot](https://github.com/user-attachments/assets/ed107466-198b-47ed-9e49-2d2d88a1b420)

#### OS/snapd/snap version

    $ snap list nextcloud
  ```
  Name       Version      Rev    Tracking       Publisher   Notes
  nextcloud  29.0.7snap1  44395  latest/stable  nextcloud✓  -
```

and:

    $ snap version
  ```
snap      2.61.4
  snapd     2.61.4
  series    16
  raspbian  10
  kernel    5.10.103-v7l+
```

#### Logs
[logs.txt](https://github.com/user-attachments/files/17065353/logs.txt)

**Comment by scubamuc** [comment]
@dosmehobbit welcome thanks for your request

thank you also for running the debug script... sadly your nextcloud log was not included;
```
tail: cannot open '/var/snap/nextcloud/current/logs/nextcloud.log' for reading: No such file or directory
```
without the nextcloud log we're not able to find the cause of your issue. possibly the logs are saved elsewhere on your OS which is the reason why [Ubuntu is the only supported distribution](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Why-Ubuntu-is-the-only-supported-distro) for Nextcloud snap. check your config.php to find the location of your nextcloud log. see [managing logs](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Managing-logs) for more information.

please consider reaching out to the [Nextcloud community](https://help.nextcloud.com) and creating an issue there... be sure to post your nextcloud.log. (_dort kannst du auch in Deutsch posten wenn dir das lieber ist_)

**Comment by dosmehobbit** [comment]
Thanks for your quick reply.

I found my nextcloud.log in my data directory, which is a external HDD.

Please find attached:
[nextcloud_tail.log](https://github.com/user-attachments/files/17070863/nextcloud_tail.log)

Remark: I tried to move the shared directory today morning again to have the tail command showing the needed stuff. So nextcloud.log and yesterdays logs.txt is not matching 100%.

**Comment by scubamuc** [comment]
@dosmehobbit thanks for getting back on the logs
I'm adamant that this is not a snap issue and remains an upstream issue

> please consider reaching out to the [Nextcloud community](https://help.nextcloud.com/) and creating an issue there... be sure to post your nextcloud.log.
