### ISSUE TITLE
github actions to release to snapstore fails on authentication

### ISSUE THREAD

**Issue by sbe-arg** [nextcloud-snap/nextcloud-snap#2889]
Does anyone looks at the actions post merging?

Actions have been failing for a few days due auth.

here: https://github.com/nextcloud-snap/nextcloud-snap/actions/workflows/release-pr-snap.yml

**Comment by pachulo** [comment]
Hi @sbe-arg ! Thanks for the hint!
I saw it some days ago, but still didn't have time to check it.

**Comment by pachulo** [comment]
OK, this should be solved now.
I've used the instruccions from https://kyrofa.com/posts/new-and-improved-way-to-review-github-pull-requests-for-snaps/#generate-new-snapcraft-token to update the token.
