### ISSUE TITLE
Daily builds failing due to latest-* URLs not working

### ISSUE THREAD

**Issue by pachulo** [nextcloud-snap/nextcloud-snap#2891]
Since some days ago the builds for the `*/edge` channels are failing with errors like this one:
```
Network request error: 404 Client Error: Not Found for url: https://download.nextcloud.com/server/daily/latest-stable28.tar.bz2
[24/Sep/2024:00:50:53 +0000] "CONNECT download.nextcloud.com:443 HTTP/1.0" 200 4621 "-" "-"
```
When trying to access the directory with a browser, it shows as empty: https://download.nextcloud.com/server/daily/

So it seems like an upstream problem.

**Comment by Pilzinsel64** [comment]
Let's see what comes out: https://cloud.nextcloud.com/call/xs25tz5y#message_3217926

**Comment by Pilzinsel64** [comment]
> I fixed it and this night master and stable will be built again.

@tobiasKaminsky Thank you! Should be solved within one or two days for us.

**Comment by Pilzinsel64** [comment]
Seems to be fixed.
