### ISSUE TITLE
 Unit of nextcloud.cron-interval is seconds

### ISSUE THREAD

**Issue by wuesti** [nextcloud-snap/nextcloud-snap#2895]
#### Describe the bug
Changing the cron interval using `snap set nextcloud nextcloud.cron-interval=10` the nextcloud cron does not pause working any more. See [https://help.nextcloud.com/t/nextcloud-snap-cron-lauft-dauerhaft-durch/204996](https://help.nextcloud.com/t/nextcloud-snap-cron-lauft-dauerhaft-durch/204996)

#### To Reproduce
1. Use `snap set nextcloud nextcloud.cron-interval=` with any value.
2. After a a while do `ps ax | grep sleep`.
3. You will get one line `sleep <this value>`

#### Expected behavior
You should get value*60 with `ps ax | grep sleep` like described in [https://github.com/nextcloud-snap/nextcloud-snap/wiki/Managing-cron]( https://github.com/nextcloud-snap/nextcloud-snap/wiki/Managing-cron).
**or**
Change **minutes** to **seconds** there.

#### Screenshots
```
snap set nextcloud nextcloud.cron-interval=10
ps ax | grep sleep                                
 731739 ?        S      0:00 sleep 1d
 793776 ?        S      0:00 sleep 10
 793779 ?        S      0:00 sleep 1
 793781 pts/4    S+     0:00 grep sleep

snap set nextcloud nextcloud.cron-interval=888
ps ax | grep sleep
 731739 ?        S      0:00 sleep 1d
 799782 ?        S      0:00 sleep 1
 799789 ?        S      0:00 sleep 888
 799791 pts/4    S+     0:00 grep sleep
```

#### OS/snapd/snap version
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble

$ snap list nextcloud
nextcloud  29.0.7snap1  44391  latest/stable  nextcloud✓  -

$ snap version
snap    2.63.1+24.04
snapd   2.63.1+24.04
series  16
ubuntu  24.04
kernel  6.8.0-45-generic
```

**Comment by scubamuc** [comment]
@wuesti, thanks for the heads up and welcome.

> Change **minutes** to **seconds** there.

you are absolutely correct... edited that in the [managing cron](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Managing-cron) wiki 👍

thank for pointing that out to us
