### ISSUE TITLE
Move Nextcloud Data file to new directory on different drive

### ISSUE THREAD

**Issue by Badwolf15001** [nextcloud-snap/nextcloud-snap#2899]
I am running a Fedora 40 Server, and got nextcloud installed VIA snap. So Nextcloud hub.
I have a 500GB SSD loaded with the OS and a raid 1 array of 8TB HDD mounted with a directory of /data.

I want to move the Nextcloud Data folder to the HDD under /data/Nextcloud/ 
But after Following "https://github.com/nextcloud-snap/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition"
After trying the method of no admin account created I get stuck on the screen saying it does not have permission to write in it's new location. I tried many thing to try and give it the permission it needs but it fails to work. 

I try moving the data file after creating an admin account, and it says that the .ocdata is missing from the data file when it is all there. After I do a restart it then gives me the same error along with it doesnt have permission to write to the location. 

I even tried creating a symbiotic soft link and that fails. 

How can I move the data file from the root directory (Which only has 500GB of space) to the 8TB drive with plenty of space??

**Comment by scubamuc** [comment]
@Badwolf15001 welcome and thanks for your request.

If you have a look at our [Wiki](https://github.com/nextcloud-snap/nextcloud-snap/wiki) especially in the [requirements](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Installation-requirements) you'll see;

> running a Fedora 40 Server

- why [Ubuntu is the only supported distribution](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Why-Ubuntu-is-the-only-supported-distro) for Nextcloud snap

> But after Following ~~"https://github.com/nextcloud-snap/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition"~~

- prefer this instead [change data directory](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Wiki-Change-data-directory)

> After trying the method of no admin account created I get stuck on the screen saying it does not have permission to write in it's new location. I tried many thing to try and give it the permission it needs but it fails to work.

- especially [connect media to snap](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Wiki-Change-data-directory#2-connect-media-to-snap)

> and it says that the .ocdata is missing from the data file 

see [path to data directory](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Wiki-Change-data-directory#4-path-to-data-directory)

I'm afraid your OS is not supported here... please give the folks at https://help.nextcloud.com a shout if my pointers didn't help.
