### ISSUE TITLE
documentation, wiki how-to

### ISSUE THREAD

**Issue by scubamuc** [nextcloud-snap/nextcloud-snap#2900]
edit wiki [Change data directory](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Wiki-Change-data-directory) add link to user how-to; [how‐to_change_data_directory](https://github.com/nextcloud-snap/nextcloud-snap/wiki/how%E2%80%90to_change_data_directory) found here https://help.nextcloud.com/t/how-to-change-datadir-in-nextcloud-snap/205210

**Comment by scubamuc** [comment]
@pachulo this is a nice quick & simple [how‐to_change_data_directory](https://github.com/nextcloud-snap/nextcloud-snap/wiki/how%E2%80%90to_change_data_directory)

**Comment by pachulo** [comment]
> @pachulo this is a nice quick & simple [how‐to_change_data_directory](https://github.com/nextcloud-snap/nextcloud-snap/wiki/how%E2%80%90to_change_data_directory)

Neat. One question though: Why does it need to update the trusted domains when changing the data directory? 🤔

**Comment by scubamuc** [comment]
@pachulo

> Why does it need to update the trusted domains when changing the data directory? 🤔

that is exactly why I ask the devs 🤣 ... i'm not sure its necessary at all.

**Comment by usernamehyphen** [comment]
so this is about to replace [Change data directory to use another disk partition](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition)?
cool! 🥳 and definitely not too soon.. i spent few days trying to troubleshoot why it failed every time i tried to change the data directory by the old howto, and this had a solution for my issue in a first command! (.. that is `sudo snap connect nextcloud:removable-media`)

this project is the killer-app of the snap platform for me, the work you do here is worth the ~~pain~~ time of working with snap _stuff._
