### ISSUE TITLE
-- CLI tools, redis-cli --

### ISSUE THREAD

**Issue by scubamuc** [nextcloud-snap/nextcloud-snap#2901]
@nextcloud-snap/developers 

this [here ](https://github.com/nextcloud/richdocuments/issues/3780#issuecomment-2257677440) is a possible solution for [#2798](https://github.com/nextcloud-snap/nextcloud-snap/issues/2798)

> This is caused by the cache system, I use Redis, so I had to execute FLUSHDB in redis-cli and everything work !

is `redis-cli` available somewhere as in [CLI utilities](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Included-CLI-utilities) or could this be added for maintenance in nextcloud-fixer?

maybe you have a workaround for FAQ's?

**Comment by pachulo** [comment]
> is redis-cli available somewhere as in [CLI utilities](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Included-CLI-utilities)

The binary is available, yes:
```
$ sudo ls -lisah /snap/nextcloud/current/bin/redis-cli
52 5.4M -rwxr-xr-x 1 root root 5.4M Sep 16 23:15 /snap/nextcloud/current/bin/redis-cli
```
And the socket to connect is here:
`/tmp/snap-private-tmp/snap.nextcloud/tmp/sockets/redis.sock`

So you should be able to connect using a command like this:
```
$ sudo /snap/nextcloud/current/bin/redis-cli -s  /tmp/snap-private-tmp/snap.nextcloud/tmp/sockets/redis│.sock
```

And then you should be able to test the `FLUSHDB` command.

> or could this be added for maintenance in nextcloud-fixer?

I'm not really sure about what implications that could have, sorry...

**Comment by scubamuc** [comment]
@pachulo that doesn't seem to work: 
![grafik](https://github.com/user-attachments/assets/74e80407-290f-425e-9181-0fecd2c837dd)

**Comment by pachulo** [comment]
I've updated the command, try again

**Comment by scubamuc** [comment]
@pachulo thanks, that worked:
![grafik](https://github.com/user-attachments/assets/aa56960a-5726-4be0-b0a7-4a0220afd274)

error in log disappears! ✔

this resolves https://github.com/nextcloud-snap/nextcloud-snap/issues/2798 and https://github.com/nextcloud/richdocuments/issues/3780  but nothing our users would want to execute manually. would it be viable to execute this on install/upgrade and add to the nextcloud-fixer?

**Comment by Pilzinsel64** [comment]
In my opinion this should be fine to run after an update while the maintenance mode is still active. Should be possible to call the `redis-cli` command from the upgrade utility and just a new line. Can take a look into the next days if nobody comes to it earlier.

**Comment by pachulo** [comment]
I just found out that the command to use can look like this:

`sudo /snap/nextcloud/current/bin/redis-cli -s /tmp/snap-private-tmp/snap.nextcloud/tmp/sockets/redis.sock FLUSHD`

I will try to do a PR tomorrow.
