### ISSUE TITLE
documentation, wiki edit "CLI utilities"

### ISSUE THREAD

**Issue by scubamuc** [nextcloud-snap/nextcloud-snap#2907]
edit [Inculded CLI utilities](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Included-CLI-utilities)
add: `redis-cli` 
see: https://github.com/nextcloud-snap/nextcloud-snap/issues/2901#issuecomment-2398184677

**Comment by scubamuc** [comment]
@pachulo 
> I thought that [that page](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Included-CLI-utilities) was only for the ones that were meant to be used by the users; those starting with nextcloud.*

while I agree to that notion, that page is not linked anywhere and it seemed a logical place to note this information. not keen on losing that information...

suggestions welcome

**Comment by pachulo** [comment]
What do you think @nextcloud-snap/developers ?

**Comment by Pilzinsel64** [comment]
I agree that we can add this to the wiki, but maybe within a separated section on either [this page](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Included-CLI-utilities) but more prefered on a debug page like [this page](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Issue-Debugging-Scripts).

**Comment by pachulo** [comment]
I've tweaked the document a little bit, take a look.
