### ISSUE TITLE
/tmp/snap-private-tmp/snap.nextcloud/ not cleaned up properly

### ISSUE THREAD

**Issue by JOpsDev** [nextcloud-snap/nextcloud-snap#2921]
#### Describe the bug
In /tmp/snap-private-tmp/snap.nextcloud/ we had quite larges directories of appimage_extracted_xxxx and coolwsd.xxxx which did not get cleaned up. We had around 10 of each of these directories using around 9GB of disk space in total. The only way to get that tmp dir down to under 1GB again was to reboot the whole linux server.

#### To Reproduce
1. Use Nextcloud with Collabora for a while without restarting the linux system

#### Expected behavior
no longer needed tmp files are cleaned up after a while

#### OS/snapd/snap version

Name       Version                   Rev    Tracking          Publisher   Notes
nextcloud  29.0.7snap1+git2.a85bd4b  44403  latest/candidate  nextcloud✓  -

snap    2.63+20.04ubuntu0.1
snapd   2.63+20.04ubuntu0.1
series  16
ubuntu  20.04
kernel  5.4.0-196-generic

**Comment by scubamuc** [comment]
@JOpsDev welcome and thanks for your request

so i've just recently tested a PR #2919 and could not reproduce you issue. 

i'm guessing this request should be placed upstream?

**Comment by JOpsDev** [comment]
I am not sure what upstream would mean here. Since the /tmp/snap-private-tmp/snap.nextcloud/ directories are specific to snap packaging (so my understanding) I thought this repo would be the correct one to address it?
When are the appimage_extracted... directories created and how should they be cleaned up?
Why are the multiple coolwsd... directories (Collabora / CODE) and how should they be cleaned up?

**Comment by scubamuc** [comment]
@JOpsDev thanks for your reply.

The Nextcloud snap team packages a finished stable upstream Nextcloud, adds some snap magic, tests and releases that snap package. Since none of the Nextcloud snap team are upstream Nextcloud developers, they need to ensure that the Nextcloud snap does what it should. That entails packaging and testing fresh installs as well as automated updates so that the Nextcloud snap community has peace of mind.

> I am not sure what upstream would mean here...

sorry we can't answer your questions... please ask the app developers.

> I thought this repo would be the correct one to address it?

we package Nextcloud into a snap, but that does not include CODE or Nextcloud office:

> When are the appimage_extracted... directories created and how should they be cleaned up?

maybe the folks at collabora know about the appimage... 

 > Why are the multiple coolwsd... directories (Collabora / CODE) and how should they be cleaned up?

the folks at snapcraft may know about interactions with the OS. this seems CODE-centric too?

your request refers to a third party app which we cannot support. please consider creating an issue with the collabora folks about your collabora issues and with canonical for snapd issues.

**Comment by scubamuc** [comment]
@nextcloud-snap/developers do you have any ideas?

**Comment by kyrofa** [comment]
Yeah, sounds like the app isn't cleaning itself up when you're done using it, but we really have no insight into specific apps.

**Comment by JOpsDev** [comment]
I think I traced this back to https://github.com/CollaboraOnline/richdocumentscode/blob/master/proxy.php.
A new appimage_extracted... directory is probably created each time something gets updated. The old one just stays there and seems never to be removed with around 830 MB of lost disk space.

For Collabora a bash process is running with these options:
`bash -c ( /mnt/HC_Volume_11192819/44403/nextcloud/extra-apps/richdocumentscode/collabora/Collabora_Online.AppImage --o:remote_font_config.url='https://cloud.our.domain/extra-apps/richdocuments/settings/fonts.json'  --o:net.lok_allow.host[14]=cloud.our.domain --pidfile=/var/snap/nextcloud/common/nextcloud/tmp/coolwsd.pid || /mnt/HC_Volume_11192819/44403/nextcloud/extra-apps/richdocumentscode/collabora/Collabora_Online.AppImage --appimage-extract-and-run --o:remote_font_config.url='https://cloud.our.domain/extra-apps/richdocuments/settings/fonts.json'  --o:net.lok_allow.host[14]=cloud.our.domain --pidfile=/var/snap/nextcloud/common/nextcloud/tmp/coolwsd.pid) >/dev/null & disown`

Please note there is a bash or operator embedded (||) between the two commands. libfuse2 is installed on the host system but still the first command seems to fail! The second command seems to be prevailing child process with these options including -appimage-extract-and-run (!) :

`
/mnt/HC_Volume_11192819/44403/nextcloud/extra-apps/richdocumentscode/collabora/Collabora_Online.AppImage --appimage-extract-and-run --o:remote_font_config.url=https://cloud.our.domain/extra-apps/richdocuments/settings/fonts.json --o:net.lok_allow.host[14]=cloud.our.domain --pidfile=/var/snap/nextcloud/common/nextcloud/tmp/coolwsd.pid`

It spawns another child process with these options:

`bin/bash /tmp/appimage_extracted_5a9ba809cd66a431cd3599739a4ccd1f/AppRun --o:remote_font_config.url=https://cloud.our.domain/extra-apps/richdocuments/settings/fonts.json --o:net.lok_allow.host[14]=cloud.our.domain --pidfile=/var/snap/nextcloud/common/nextcloud/tmp/coolwsd.pid`

From this another child process coolwsd is spawned. If a user opens a document and no coolwsd process is already running a new one is spawned with these options:

`coolwsd --config-file=/tmp/appimage_extracted_5a9ba809cd66a431cd3599739a4ccd1f/etc/coolwsd/coolwsd.xml --disable-cool-user-checking --port=9983 --lo-template-path=/tmp/appimage_extracted_5a9ba809cd66a431cd3599739a4ccd1f/opt/collaboraoffice --o:sys_template_path=/tmp/coolwsd.ogeGZpaWZe/systemplate/ --o:security.capabilities=false --o:security.seccomp=false --o:child_root_path=/tmp/coolwsd.ogeGZpaWZe/jails --o:file_server_root_path=/tmp/appimage_extracted_5a9ba809cd66a431cd3599739a4ccd1f/usr/share/coolwsd --o:ssl.enable=false --o:net.proxy_prefix=true --o:memproportion=50 --o:logging.file[@enable]=true --o:logging.file.property[0][@name]=path --o:logging.file.property[0]=/tmp/coolwsd.ogeGZpaWZe/coolwsd.log --o:welcome.enable=true --o:user_interface.mode=default --o:allowed_languages=de_DE el en_GB en_US es_ES fr_FR hu it nl pt_BR pt_PT ru --o:fetch_update_check=0 --o:allow_update_popup=false --o:remote_font_config.url=https://cloud.our.domain/extra-apps/richdocuments/settings/fonts.json --o:net.lok_allow.host[14]=cloud.our.domain --pidfile=/var/snap/nextcloud/common/nextcloud/tmp/coolwsd.pid`

A new coolwsd.... directory is created each time a new coolwsd process is forked.  

After some time (of no usage?) the coolwsd process dies with these last log entries:
```
kit-50383-50383 2024-10-14 19:41:26.133177 +0200 [ kit_spare_005 ] ERR  #33: Kit for DocBroker [] connection lost without exit arriving from wsd. Setting TerminationFlag| kit/KitWebSocket.cpp:193
kit-50381-50381 2024-10-14 19:41:26.133644 +0200 [ kit_spare_003 ] ERR  #33: Kit for DocBroker [] connection lost without exit arriving from wsd. Setting TerminationFlag| kit/KitWebSocket.cpp:193
kit-50379-50379 2024-10-14 19:41:26.133862 +0200 [ kit_spare_002 ] ERR  #33: Kit for DocBroker [] connection lost without exit arriving from wsd. Setting TerminationFlag| kit/KitWebSocket.cpp:193
kit-64009-64009 2024-10-14 19:41:26.134206 +0200 [ kit_spare_007 ] ERR  #33: Kit for DocBroker [] connection lost without exit arriving from wsd. Setting TerminationFlag| kit/KitWebSocket.cpp:193
wsd-50332-50332 2024-10-14 19:41:26.172459 +0200 [ coolwsd ] WRN  Jails root directory [/tmp/coolwsd.kBK1jgHJCG/jails/] is not empty. Will not remove it.| common/JailUtil.cpp:413
```

The directory stays there and is not cleaned up. Usually it's just some MBs of data, but sometimes (crashes?) the collwsd directories are quite large.
If the /tmp/snap-private-tmp/snap.nextcloud/tmp/ directory fills up to a certain quota no new coolwsd process can be started. If this happens the frontend first displays a spinner and then tells the user 

> document loading failed - failed to load nextcloud office - please try again later

**Comment by JOpsDev** [comment]
If there is no Collabora_Online.AppImage running and I start the first command directly it starts up properly. No appimage_extracted directory is created, a coolwsd directory in /tmp/ is used and the user can open and work on documents. After stopping the process again (ctrl+c) the coolwsd directory in /tmp/ is removed.

**Comment by JOpsDev** [comment]
If I close the document and just kill the coolwsd process on the server the whole process tree gets removed. Also the coolwsd tmp directory gets cleaned up and removed.

**Comment by scubamuc** [comment]
@JOpsDev thanks for trying to get to the bottom of this... but this is certainly not a snap issue. the collabora team would definitely appreciate your efforts.

please consider posting your issue upstream --> https://github.com/nextcloud/richdocuments/issues
