### ISSUE TITLE
Periodically High mysqld CPU load...again

### ISSUE THREAD

**Issue by dzx-dzx** [nextcloud-snap/nextcloud-snap#2931]
#### Describe the bug
Every 1 hour there's a spike in CPU usage caused by a `mysqld` process. When checking the exact query through `show full processlist`, I find that it's 
```
 SELECT `a`.`name` FROM `oc_filecache` `a` LEFT JOIN `oc_filecache` `b` ON `a`.`name` = `b`.`fileid` WHERE (`a`.`storage` = '10') AND (`b`.`fileid` IS NULL) AND (`a`.`path` LIKE 'appdata\\\\_octrt98mu9bc/preview/_/_/_/_/_/_/_/%') AND (`a`.`mimetype` = '2')
```
which is the same query mentioned in https://github.com/nextcloud/server/issues/28114 and https://github.com/nextcloud-snap/nextcloud-snap/issues/1328, the latter of which suggests running `MySQLTuner` to alleviate the problem. But per https://github.com/nextcloud-snap/nextcloud-snap/issues/2412 that's not possible?

#### To Reproduce
1. Wait 1 hour

#### Expected behavior
The server runs quietly.

#### OS/snapd/snap version
nextcloud  29.0.8snap1
snap       2.63
snapd      2.63
series     16
linuxmint  20.3
kernel     5.15.0-121-generic

#### Logs
https://pastebin.com/F7NsPgB1

**Comment by scubamuc** [comment]
@dzx-dzx 

https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-one-or-more-mimetype-migrations-are-available-warning-is-displayed-what-can-i-do

**Comment by scubamuc** [comment]
@dzx-dzx 
> Periodically High mysqld CPU load...again

what solution helped "last time"?

**Comment by dzx-dzx** [comment]
> @dzx-dzx
> 
> > Periodically High mysqld CPU load...again
> 
> what solution helped "last time"?

I guess that's not related. It was https://github.com/nextcloud-snap/nextcloud-snap/issues/2412 in which a rogue app caused the CPU load spike every 12 minutes. The app has been turned off since.

**Comment by dzx-dzx** [comment]
> @dzx-dzx
> 
> > `SELECT `a`.`name`FROM`oc_filecache` `a`LEFT JOIN`oc_filecache` `b`ON`a`.`name`=`b`.`fileid` WHERE (`a`.`storage` = '10') AND (`b`.`fileid` IS NULL) AND (`a`.`path` LIKE 'appdata\\\\_octrt98mu9bc/preview/_/_/_/_/_/_/_/%') AND (`a`.`mimetype` = '2')`
> 
> https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-one-or-more-mimetype-migrations-are-available-warning-is-displayed-what-can-i-do
> 
> ```
> sudo nextcloud.occ maintenance:repair --include-expensive
> ```

It finished rather quickly. Shall I attach the output?

**Comment by dzx-dzx** [comment]
> can you double check your cron service too? `sudo snap get nextcloud nextcloud.cron-interval`

```
5m
```

**Comment by dzx-dzx** [comment]
I shall wait before the spike occurs. Before that, I can state that the process typically stays at <1% CPU usage, but it will rise to ~20% for 2 minutes before it quiets down again.

**Comment by scubamuc** [comment]
@dzx-dzx 
> stays at <1% CPU usage, but it will rise to ~20% for 2 minutes before it quiets down again.

that seems "normal" at least it quietens down right?

mine looks similar, but I have multiple containers on LXD:

![grafik](https://github.com/user-attachments/assets/41af0f99-54e2-4585-84c5-4a085862046a)

**Comment by dzx-dzx** [comment]
> ...
> 06:27:29 PM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
> 06:27:34 PM   123      1526    0.20    0.20    0.00    0.00    0.40     0  mysqld
> 06:27:34 PM     0   3712809    1.00    0.40    0.00    0.00    1.40     1  mysqld
> 
> 06:27:34 PM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
> 06:27:39 PM   123      1526    0.40    0.20    0.00    0.00    0.60     0  mysqld
> 06:27:39 PM     0   3712809    0.00    0.60    0.00    0.00    0.60     1  mysqld
> 
> 06:27:39 PM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
> 06:27:44 PM   123      1526    0.00    0.60    0.00    0.00    0.60     0  mysqld
> 06:27:44 PM     0   3712809    0.40    0.40    0.00    0.00    0.80     1  mysqld
> (***CPU usage started rising***)
> 06:27:44 PM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
> 06:27:49 PM   123      1526    0.20    0.00    0.00    0.00    0.20     0  mysqld
> 06:27:49 PM     0   3712809   91.20    2.60    0.00    0.00   93.80     1  mysqld
> 
> 06:27:49 PM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
> 06:27:54 PM   123      1526    0.00    0.20    0.00    0.00    0.20     0  mysqld
> 06:27:54 PM     0   3712809   99.00    1.00    0.00    0.00  100.00     1  mysqld
> 
> 06:27:54 PM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
> 06:27:59 PM   123      1526    0.20    0.20    0.00    0.00    0.40     0  mysqld
> 06:27:59 PM     0   3712809   98.80    1.80    0.00    0.00  100.60     0  mysqld
> 
> 06:27:59 PM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
> 06:28:04 PM   123      1526    0.00    0.40    0.00    0.00    0.40     0  mysqld
> 06:28:04 PM     0   3712809   98.80    2.00    0.00    0.00  100.80     2  mysqld
> 
> 06:28:04 PM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
> 06:28:09 PM     0   3712809   98.60    1.60    0.00    0.00  100.20     2  mysqld
> 
> 06:28:09 PM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
> 06:28:14 PM   123      1526    0.20    0.20    0.00    0.00    0.40     0  mysqld
> 06:28:14 PM     0   3712809   98.60    1.60    0.00    0.00  100.20     1  mysqld
> 
> 06:28:14 PM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
> 06:28:19 PM   123      1526    0.20    0.00    0.00    0.00    0.20     0  mysqld
> 06:28:19 PM     0   3712809   98.80    1.40    0.00    0.00  100.20     1  mysqld
> 
> 06:28:19 PM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
> 06:28:24 PM   123      1526    0.20    0.20    0.00    0.00    0.40     0  mysqld
> 06:28:24 PM     0   3712809   98.60    1.40    0.00    0.00  100.00     1  mysqld
> 
> 06:28:24 PM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
> 06:28:29 PM   123      1526    0.20    0.00    0.00    0.00    0.20     0  mysqld
> 06:28:29 PM     0   3712809   99.80    0.80    0.00    0.00  100.60     2  mysqld
> 
> 06:28:29 PM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
> 06:28:34 PM   123      1526    0.20    0.00    0.00    0.00    0.20     0  mysqld
> 06:28:34 PM     0   3712809   99.20    1.60    0.00    0.00  100.80     2  mysqld
> 
> 06:28:34 PM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
> 06:28:39 PM   123      1526    0.20    0.20    0.00    0.00    0.40     0  mysqld
> 06:28:39 PM     0   3712809   98.40    1.80    0.00    0.00  100.20     2  mysqld
> 
> 06:28:39 PM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
> 06:28:44 PM   123      1526    0.20    0.00    0.00    0.00    0.20     0  mysqld
> 06:28:44 PM     0   3712809   98.60    1.80    0.00    0.00  100.40     2  mysqld
> 
> 06:28:44 PM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
> 06:28:49 PM   123      1526    0.20    0.00    0.00    0.00    0.20     0  mysqld
> 06:28:49 PM     0   3712809   98.80    1.40    0.00    0.00  100.20     2  mysqld
> 
> 06:28:49 PM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
> 06:28:54 PM   123      1526    0.20    0.20    0.00    0.00    0.40     0  mysqld
> 06:28:54 PM     0   3712809   98.80    1.40    0.00    0.00  100.20     2  mysqld
> 
> 06:28:54 PM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
> 06:28:59 PM   123      1526    0.20    0.20    0.00    0.00    0.40     0  mysqld
> 06:28:59 PM     0   3712809   99.20    1.20    0.00    0.00  100.40     2  mysqld
> 
> 06:28:59 PM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
> 06:29:04 PM   123      1526    0.00    0.20    0.00    0.00    0.20     0  mysqld
> 06:29:04 PM     0   3712809   99.20    1.40    0.00    0.00  100.60     3  mysqld
> 
> 06:29:04 PM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
> 06:29:09 PM   123      1526    0.00    0.20    0.00    0.00    0.20     0  mysqld
> 06:29:09 PM     0   3712809   97.80    2.40    0.00    0.00  100.20     3  mysqld
> 
> 06:29:09 PM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
> 06:29:14 PM   123      1526    0.40    0.00    0.00    0.00    0.40     0  mysqld
> 06:29:14 PM     0   3712809   99.60    0.80    0.00    0.00  100.40     3  mysqld
> 
> 06:29:14 PM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
> 06:29:19 PM   123      1526    0.20    0.00    0.00    0.00    0.20     0  mysqld
> 06:29:19 PM     0   3712809   98.80    1.40    0.00    0.00  100.20     3  mysqld
> 
> 06:29:19 PM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
> 06:29:24 PM   123      1526    0.20    0.00    0.00    0.00    0.20     0  mysqld
> 06:29:24 PM     0   3712809   99.60    0.80    0.00    0.00  100.40     3  mysqld
> 
> 06:29:24 PM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
> 06:29:29 PM   123      1526    0.20    0.20    0.00    0.00    0.40     0  mysqld
> 06:29:29 PM     0   3712809   99.60    0.60    0.00    0.00  100.20     2  mysqld
> 
> 06:29:29 PM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
> 06:29:34 PM   123      1526    0.20    0.00    0.00    0.00    0.20     0  mysqld
> 06:29:34 PM     0   3712809   99.60    1.40    0.00    0.00  101.00     3  mysqld
> 
> 06:29:34 PM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
> 06:29:39 PM   123      1526    0.20    0.00    0.00    0.00    0.20     0  mysqld
> 06:29:39 PM     0   3712809   99.60    0.60    0.00    0.00  100.20     3  mysqld
> 
> 06:29:39 PM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
> 06:29:44 PM   123      1526    0.20    0.20    0.00    0.00    0.40     0  mysqld
> 06:29:44 PM     0   3712809   99.40    0.80    0.00    0.00  100.20     3  mysqld
> 
> 06:29:44 PM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
> 06:29:49 PM   123      1526    0.00    0.40    0.00    0.00    0.40     0  mysqld
> 06:29:49 PM     0   3712809   98.40    1.80    0.00    0.00  100.20     3  mysqld
> 
> 06:29:49 PM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
> 06:29:54 PM   123      1526    0.20    0.00    0.00    0.00    0.20     0  mysqld
> 06:29:54 PM     0   3712809   99.00    1.20    0.00    0.00  100.20     3  mysqld
> 
> 06:29:54 PM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
> 06:29:59 PM   123      1526    0.20    0.20    0.00    0.00    0.40     0  mysqld
> 06:29:59 PM     0   3712809   98.80    1.60    0.00    0.00  100.40     3  mysqld
> 
> 06:29:59 PM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
> 06:30:04 PM   123      1526    0.20    0.00    0.00    0.00    0.20     0  mysqld
> 06:30:04 PM     0   3712809  100.20    0.80    0.00    0.00  101.00     2  mysqld
> 
> 06:30:04 PM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
> 06:30:09 PM     0   3712809   99.00    1.00    0.00    0.00  100.00     2  mysqld
> 
> 06:30:09 PM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
> 06:30:14 PM   123      1526    0.20    0.40    0.00    0.00    0.60     0  mysqld
> 06:30:14 PM     0   3712809   53.60    0.60    0.00    0.00   54.20     2  mysqld
> (***CPU usage returned to normal***)
> 06:30:14 PM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
> 06:30:19 PM   123      1526    0.40    0.00    0.00    0.00    0.40     0  mysqld
> 06:30:19 PM     0   3712809    0.20    0.40    0.00    0.00    0.60     2  mysqld
> ...
> 06:30:19 PM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
> 06:30:24 PM   123      1526    0.20    0.60    0.00    0.00    0.80     0  mysqld
> 06:30:24 PM     0   3712809    0.20    0.80    0.00    0.00    1.00     2  mysqld
> 
> 06:30:24 PM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
> 06:30:29 PM   123      1526    0.20    0.20    0.00    0.00    0.40     0  mysqld
> 06:30:29 PM     0   3712809    0.40    0.60    0.00    0.00    1.00     2  mysqld

**Comment by scubamuc** [comment]
hmmm... strange, but certainly not a snap issue. 
can you pinpoint recurrence time?
do you have any crontabs set?

**Comment by dzx-dzx** [comment]
> do you have any crontabs set?

Nothing that is related to nextcloud. None of them runs every one hour.

> how long have you been running this instance? mine's about 8 years running, but i do cleanup every now and then; [database‐apps‐files‐maintenance](https://github.com/nextcloud-snap/nextcloud-snap/wiki/database%E2%80%90apps%E2%80%90files%E2%80%90maintenance)


Since three years ago, I think. But I don't quite run those commands very often, since it's rather time-consuming.

**Comment by scubamuc** [comment]
@dzx-dzx 
> since it's rather time-consuming...

might be so, but scouring the logs for unknown issues takes longer?

**Comment by dzx-dzx** [comment]
You are right. I shall check if the issue persists after running these commands.

**Comment by scubamuc** [comment]
@dzx-dzx see #2938, can you give it a shot please.

**Comment by dzx-dzx** [comment]
The server has upgraded itself to 30 and the problem persists. I had cleaned the database before, but I can try again.

**Comment by scubamuc** [comment]
hey @dzx-dzx, i've been watching this and see similar regular peaks... nothing over 30% though. this is surely not a snap issue but more likely an upstream thing...

![grafik](https://github.com/user-attachments/assets/e51389c2-09a4-49b2-9ce8-2aac2e204491)

**Comment by scubamuc** [comment]
@nextcloud-snap/developers 

wdyt? is this something we should look into? can any of you confirm similar findings?

**Comment by dzx-dzx** [comment]
Sorry I'm migrating to manual installation, so I won't be able to provide any new logs or test possible solutions.

**Comment by scubamuc** [comment]
after watching this for a while, these regular peaks (every 15 minutes) are caused by failing `nextcloud.cron` on my instance. 

see [managing cron](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Managing-cron) especially [cron fails after upgrade](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Managing-cron#if-cron-fails-after-update)

1. restart cron `sudo snap restart nextcloud.nextcloud-cron`
2. make cron a backgroud job `sudo nextcloud.occ background:cron`

resolved the issue for me

**Comment by scubamuc** [comment]
@nextcloud-snap/developers  is there something we could do to ensure that `nextcloud.cron` is started correctly after an upgrade... there are no obvious messages in the logs, just the 20% CPU peaks with default `nextcloud.cron` settings.

it was actually quite a surprise to see that this could be reproduced on my instance. the resolution above was simple enough, but not obvious and although CPU load peaks only 20%, it will make a difference on limited resource machines and SBC's.

should I mention, that this could not be reproduced on all instances?

**Comment by scubamuc** [comment]
seems to be resolved following recommended Nextcloud cron interval settings:

see [Managing cron](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Managing-cron)

recommended 5 minute cron interval settings

see #2971
