### ISSUE TITLE
Snap store page showing: This video has been removed for violating YouTube's Terms of Service

### ISSUE THREAD

**Issue by cosmic-zip** [nextcloud-snap/nextcloud-snap#2937]
#### Describe the bug
Snap store page showing: This video has been removed for violating YouTube's Terms of Service

#### To Reproduce
Open nextcloud snap store page
Gotha nuked by this message.

#### Expected behavior
see this video or a normal snap-store page

#### Screenshots

![Screenshot from 2024-10-25 19-22-54](https://github.com/user-attachments/assets/7a46119e-c184-47d9-bc6b-1a995129b42e)

**Comment by scubamuc** [comment]
hey @cosmic-zip welcome 👋 and thanks for mentioning an issue on canonicals [snapcraft](https://snapcraft.io/nextcloud) website.

this is only indirectly a Nextcloud snap issue... but nothing we could change. the folks at canonical will appreciate you creating an issue in the [snapcraft forum](https://forum.snapcraft.io/).

**Comment by scubamuc** [comment]
@cosmic-zip,

if you're looking for an video installation guide, use your favourite video search provider to find a video that suits your needs. Please note, we are not responsible for any of these guides and none of these videos were created or checked by the Nextcloud snap team. some video guides are great, some are good.... others are more difficult to understand.

please see our [wiki](https://github.com/nextcloud-snap/nextcloud-snap/wiki) for detailed Nextcloud snap information. you can follow the topic order as an installation guideline...

**Comment by pachulo** [comment]
> this is only indirectly a Nextcloud snap issue... but nothing we could change.

Well, that's not actually true: @kyrofa and myself have admin rights on that page, so we are able to update the video.
The question is: which video should be showing there? Maybe [this one](https://www.youtube.com/watch?v=EnT_OVfE4nw)? 🤔

**Comment by pachulo** [comment]
OK, I've updatet the video to this one: https://vimeo.com/555692548

**Comment by kyrofa** [comment]
Thank you @pachulo, spot on.
