### ISSUE TITLE
mysqld at 100% cpu for many hours

### ISSUE THREAD

**Issue by samtygier** [nextcloud-snap/nextcloud-snap#2938]
#### Describe the bug
mysqld has been sitting at ~100% CPU for many hours.

If I run `sudo /snap/bin/nextcloud.mysql-client` and `show full processlist;` I see the following tasks
```
mysql> show full processlist;
+-------+-----------------+-----------+-----------+---------+-------+------------------------+-----------------------------------------------------------------------------------------------------------+
| Id    | User            | Host      | db        | Command | Time  | State                  | Info                                                                                                      |
+-------+-----------------+-----------+-----------+---------+-------+------------------------+-----------------------------------------------------------------------------------------------------------+
|     5 | event_scheduler | localhost | NULL      | Daemon  | 40382 | Waiting on empty queue | NULL                                                                                                      |
|    15 | nextcloud       | localhost | nextcloud | Query   |     8 | executing              | SELECT `fileid` FROM `oc_filecache` WHERE (`storage` = 3) AND (`size` < 0) ORDER BY `fileid` DESC LIMIT 1 |
| 83180 | root            | localhost | NULL      | Query   |     0 | init                   | show full processlist                                                                                     |
| 83183 | nextcloud       | localhost | nextcloud | Sleep   |     1 |                        | NULL                                                                                                      |
| 83184 | nextcloud       | localhost | nextcloud | Sleep   |     0 |                        | NULL                                                                                                      |
+-------+-----------------+-----------+-----------+---------+-------+------------------------+-----------------------------------------------------------------------------------------------------------+
5 rows in set, 1 warning (0.00 sec)
```
I restarted nextcloud with `sudo snap restart nextcloud` this morning to see if that would help, but 10 hours later the same query is still running.

#### To Reproduce
I am not sure anything I have done to trigger this.

#### Expected behavior
Nextcloud snap should use very little cpu when idle

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud

```
nextcloud  29.0.8snap1  44729  latest/stable  nextcloud✓  -`and:
```

    $ snap version

```
snap    2.61.4
snapd   2.61.4
series  16
debian  12
kernel  6.1.0-25-amd64
```

#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).

**Comment by samtygier** [comment]
logs:
[nextcloud.txt](https://github.com/user-attachments/files/17535353/nextcloud.txt)

**Comment by scubamuc** [comment]
Hey @samtygier welcome and thanks for your request,

> mysqld has been sitting at ~100% CPU for many hours.

``` 
snap    2.61.4
snapd   2.61.4
series  16
debian  12
kernel  6.1.0-25-amd64
```

see [requirements](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Installation-requirements) and why [Ubuntu is the only supported distribution](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Why-Ubuntu-is-the-only-supported-distro)

there were some issues with the `phone track` app and `maps` app not being compatible to vs. 30.0.1 yet.... so you could try to revert and disable those apps for the time being... until the app devs have updated those apps. possibly you can [disable ](https://github.com/nextcloud-snap/nextcloud-snap/wiki/OCC-management-console#disable-apps) those apps using [OCC management console](https://github.com/nextcloud-snap/nextcloud-snap/wiki/OCC-management-console) without reverting first.

```
   "phonetrack": {
            "enabled": "yes",
            "installed_version": "0.8.1",
            "types": ""
        },
```

```
        "maps": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "filesystem"
        },
```

**Comment by pachulo** [comment]
> there werehttps://github.com/nextcloud-snap/nextcloud-snap/issues/2898#issuecomment-2438255162 with the phonetrack app and maps app not being compatible to vs. 30.0.1 yet.... so you could try to revert and disable those apps for the time being...

This was opened before the upgrade to 30.0.1:
> nextcloud  29.0.8snap1  44729  latest/stable  nextcloud✓

@samtygier maybe you could try [to clean you database](https://github.com/nextcloud-snap/nextcloud-snap/wiki/database%E2%80%90apps%E2%80%90files%E2%80%90maintenance)?

**Comment by scubamuc** [comment]
@samtygier and @pachulo 

> This was opened before the upgrade to 30.0.1:

sorry for overlooking that 😯

**Comment by samtygier** [comment]
Yes this was happening with v29. Overnight the update to v30 happened. I still have an identical query running at full cpu for the past 19 hours. I'll try the database cleanup.

**Comment by samtygier** [comment]
Database clean seems to have done the job. I don't see mysqld at 100% any more.

**Comment by scubamuc** [comment]
@samtygier job well done! 👍
