### ISSUE TITLE
Top icons invisible after upgrading to 30.0.1

### ISSUE THREAD

**Issue by spaxton-ligiston** [nextcloud-snap/nextcloud-snap#2941]
#### Describe the bug
After upgrading to 30.0.1, the icons (applications icons) on the top of the nextcloud page are invisible.

#### To Reproduce
1. Login to nextcloud
2. after logging in, no icons will be visible on the top of the page as well as search button or notifications. It is still possible to click on the apps on the top of the page but the icons are invisible.

#### Screenshots
Screenshot attached.
![Screenshot_5](https://github.com/user-attachments/assets/1ee3ada3-5d89-4e35-9337-6e47a38b08f7)
![Screenshot_4](https://github.com/user-attachments/assets/e3a5d240-2306-44d0-8e9c-1700a18d6f05)

#### OS/snapd/snap version
Ubuntu server 20.04.6 LTS

nextcloud  30.0.1snap1  44812  latest/stable  nextcloud✓

**Comment by scubamuc** [comment]
Hey @spaxton-ligiston nice to see you here,

we've seen similar issues upstream https://help.nextcloud.com/t/nc-30-contacts-icon-missing-from-top-app-bar/204361

don't hesitate to post your request there: https://help.nextcloud.com/tag/snap

**Comment by spaxton-ligiston** [comment]
> Hey @spaxton-ligiston nice to see you here and thanks for your request
> 
> we've seen similar issues upstream https://help.nextcloud.com/t/nc-30-contacts-icon-missing-from-top-app-bar/204361
> 
> don't hesitate to post your request there: https://help.nextcloud.com/tag/snap

Hello,

Thanks for pointing me to this thread. I don't have an account there at the moment so i didn't post on it. I can tell that this is not cache related since for me it doesn't work on any browser or even on mobile from where I never logged in so far.
Anything else I can do to solve this?

**Comment by scubamuc** [comment]
> Thanks for pointing me to this thread.

you're welcome 👋

the thing is, there's not much we can change with regards to what is delivered from [upstream](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-why-is-nextcloud-snap-version-out-of-sync-with-upstream-nextcloud).

could you post your logs by running the [debugging script](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Issue-Debugging-Scripts#debugging-script). we'll have a look if there's something in there causing you issues... you can post the outpu right here for easy reading.

**Comment by spaxton-ligiston** [comment]
> could you post your logs by running the [debugging script](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Issue?Debugging-Scripts#debugging-script). we'll have a look if there's something in there causing your issues... you can post the output right here for easy reading. see [getting help](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Getting-help)

Honestly, I don't know how to run debussing script? Any link with more instructions about it?

**Comment by scubamuc** [comment]
> Any link with more instructions about it?

sure... just click here [debugging script](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Issue?Debugging-Scripts#debugging-script)... don't worry, it won't blow up in your face 🤣

@spaxton-ligiston ... come to think of it, do you mind trying a light theme first? maybe this is a theme thing?

yeah, you might think i'm grabbing fro straws. while that's absolutely true, what do you have to lose? 🤓

**Comment by scubamuc** [comment]
sorry... i see your issue now, the link is buggy... click here: [debugging script](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Issue-Debugging-Scripts#debugging-script)

**Comment by spaxton-ligiston** [comment]
> sure... just click here [debugging script](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Issue?Debugging-Scripts#debugging-script)... don't worry, it won't blow up in your face 🤣
> 
> @spaxton-ligiston ... come to think of it, do you mind trying a light theme first? maybe this is a theme thing?

I have to be honest again,... I have no idea where is the debugging script. :D 

Also, the theme issue can't be issue on every device. I only have one with dark theme. :D

**Comment by spaxton-ligiston** [comment]
Tons of output.... How to capture it in a file?

**Comment by spaxton-ligiston** [comment]
Here is the file. I removed the section where filenames were listed since they were listed just because the user does not have enough quota for them.
[putty.log](https://github.com/user-attachments/files/17549155/putty.log)

**Comment by spaxton-ligiston** [comment]
I have found the problem.... It seems that icons and letters under them are in black color while the background is also black. This is related to theming but I couldn't find an option to change color of icons. Icons were white before the upgrade.

**Comment by scubamuc** [comment]
@spaxton-ligiston 

> come to think of it, do you mind trying a light theme first? maybe this is a theme thing?

that makes sense...

> The problem was the default background. The default background sets the color of the icons on the top to black. My background was also black so the icons became invisible. It seems that actually everything is ok. You can close this thread.

job well done! 👍

**Comment by spaxton-ligiston** [comment]
> @spaxton-ligiston
> 
> > come to think of it, do you mind trying a light theme first? maybe this is a theme thing?
> 
> that makes sense...


hahah. I expected this. :D 
Changing theme didn't change the icons color. The theme changes from dark to light by itself depending on the time.

Thanks for help! ;)

**Comment by scubamuc** [comment]
@spaxton-ligiston 
> hahah. I expected this. :D

😎 couldn't help it

**Comment by scubamuc** [comment]
@spaxton-ligiston 

on a side note...

> Thanks for pointing me to this thread. I don't have an account there at the moment so i didn't post on it

you can log in on the [Nextcloud community forum](https://help.nextcloud.com) with your GitHub credentials

**Comment by spaxton-ligiston** [comment]
> you can log in on the [Nextcloud community forum](https://help.nextcloud.com) with your GitHub credentials

I didn't know. Thanks for the info. ;)
