### ISSUE TITLE
Since update to 30.0.1snap1: [core] Fehler: Error while running background job OCA\Passwords\Cron\SynchronizeShares

### ISSUE THREAD

**Issue by wuesti** [nextcloud-snap/nextcloud-snap#2942]
#### Describe the bug
Since update to 30.0.1snap1 I get every 2 hours this error mostly 2 times (first yesterday):
```
[core] Fehler: Error while running background job OCA\Passwords\Cron\SynchronizeShares (id: 97, arguments: null)
	von ? von -- um 29.10.2024, 08:40:26
```

#### OS/snapd/snap version

Nextcloud 30.0.1snap1
snap    2.65.3+24.04
snapd   2.65.3+24.04
series  16
ubuntu  24.04
kernel  6.8.0-47-generic

#### Log in raw
```
{"reqId":"ed4nxdNznGqUh8KOYxAK","level":3,"time":"2024-10-29T07:40:26+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Error while running background job OCA\\Passwords\\Cron\\SynchronizeShares (id: 97, arguments: null)","userAgent":"--","version":"30.0.1.2","exception":{"Exception":"TypeError","Message":"OCA\\Passwords\\Db\\AbstractMapper::findAllByField(): Argument #3 ($type) must be of type int, string given, called in /var/snap/nextcloud/44812/nextcloud/extra-apps/passwords/lib/Db/PasswordMapper.php on line 30","Code":0,"Trace":[{"file":"/var/snap/nextcloud/44812/nextcloud/extra-apps/passwords/lib/Db/PasswordMapper.php","line":30,"function":"findAllByField","class":"OCA\\Passwords\\Db\\AbstractMapper","type":"->"},{"file":"/var/snap/nextcloud/44812/nextcloud/extra-apps/passwords/lib/Services/Object/PasswordService.php","line":72,"function":"findAllShared","class":"OCA\\Passwords\\Db\\PasswordMapper","type":"->"},{"file":"/var/snap/nextcloud/44812/nextcloud/extra-apps/passwords/lib/Cron/SynchronizeShares.php","line":267,"function":"findShared","class":"OCA\\Passwords\\Services\\Object\\PasswordService","type":"->"},{"file":"/var/snap/nextcloud/44812/nextcloud/extra-apps/passwords/lib/Cron/SynchronizeShares.php","line":84,"function":"removeSharedAttribute","class":"OCA\\Passwords\\Cron\\SynchronizeShares","type":"->"},{"file":"/var/snap/nextcloud/44812/nextcloud/extra-apps/passwords/lib/Cron/AbstractTimedJob.php","line":59,"function":"runJob","class":"OCA\\Passwords\\Cron\\SynchronizeShares","type":"->"},{"file":"/snap/nextcloud/44812/htdocs/lib/public/BackgroundJob/Job.php","line":61,"function":"run","class":"OCA\\Passwords\\Cron\\AbstractTimedJob","type":"->"},{"file":"/snap/nextcloud/44812/htdocs/lib/public/BackgroundJob/TimedJob.php","line":83,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/snap/nextcloud/44812/htdocs/lib/public/BackgroundJob/TimedJob.php","line":73,"function":"start","class":"OCP\\BackgroundJob\\TimedJob","type":"->"},{"file":"/snap/nextcloud/44812/htdocs/cron.php","line":162,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->"}],"File":"/var/snap/nextcloud/44812/nextcloud/extra-apps/passwords/lib/Db/AbstractMapper.php","Line":179,"message":"Error while running background job OCA\\Passwords\\Cron\\SynchronizeShares (id: 97, arguments: null)","exception":{},"CustomMessage":"Error while running background job OCA\\Passwords\\Cron\\SynchronizeShares (id: 97, arguments: null)"}}
```

**Comment by scubamuc** [comment]
Hey @wuesti thanks for you request

run the [debugging script](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Issue-Debugging-Scripts#debugging-script) and post the output here

> ``Error while running background job OCA\Passwords\Cron\SynchronizeShares (id: 97, arguments: null)` 

this seems like an issue in the password app, but we'll need the output of the [debugging script](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Issue-Debugging-Scripts#debugging-script) 

also check if cron is running see [managing cron](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Managing-cron) especially [cron stopped after upgrad](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-nextcloud-snap-cron-fails-after-update-what-can-i-do)

**Comment by wuesti** [comment]
Here's the debugging script.
[debug.log](https://github.com/user-attachments/files/17554401/debug.log)

Cron is running.

**Comment by pachulo** [comment]
This seems to be [an upstream issue](https://github.com/marius-wieschollek/passwords/issues/676) indeed. It should be solved when they release a new version wit the [fix](https://github.com/marius-wieschollek/passwords/pull/678).

**Comment by scubamuc** [comment]
your password config in logs

> 
        "passwords": {
            "SSEv1ServerKey": "***REMOVED SENSITIVE VALUE***",
            "backup\/interval": "172800",
            "cron\/php\/version\/id": "80224",
            "cron\/php\/version\/string": "8.2.24",
            "cron\/sharing\/time": "1730187626",
            "enabled": "yes",
            "entity\/purge\/timeout": "31536000",
            "installed_version": "2024.9.20",
            "migration\/customFields": "2020.12.2",
            "passwords\/localdb\/type": "hibp",
            "service\/favicon": "bi",
            "service\/favicon\/bi\/counter": "44:4:0",
            "service\/images": "auto",
            "settings\/mail\/security": "",
            "survey\/server\/mode": "0",
            "types": "",
            "web\/php\/version\/id": "80224",
            "web\/php\/version\/string": "8.2.24"
        }


see field ` "types": ` is empty...

the logs are telling us that this field should not be empty;

`Argument #3 ($type) must be of type int, string given, called in /var/snap/nextcloud/44812/nextcloud/extra-apps/passwords/lib/Db/PasswordMapper.php on line 30`

please consider mentioning this on the app developers GitHub: https://github.com/marius-wieschollek/passwords/issues
