### ISSUE TITLE
Migrate only database data

### ISSUE THREAD

**Issue by michmoor0725** [nextcloud-snap/nextcloud-snap#2949]
Hello everyone,
I have stood up a database server hosting multiple projects and would like to know if its possible to migrate the MySQL database for nextcloud snap to my MySQL DB hosted by me and link the nextcloud snap to my DB.

All other data such as user directory and files will remain where they are.

**Comment by scubamuc** [comment]
hey @michmoor0725 welcome and thanks for you request

as mentioned here #2939 it is possible but not supported and things can go wrong https://github.com/nextcloud-snap/nextcloud-snap/issues/2939#issuecomment-2443686291


https://github.com/nextcloud-snap/nextcloud-snap/issues/2939#issuecomment-2444491445
> Yes, you can do it, it's just that it's not a configuration that the snap developers recommend or support. It can break at any time without notice and you are "on your own".
If you really wanna do that, and this is my opinion, I would recommend you checking other ways of deploying nextcloud.
