### ISSUE TITLE
Nextcloud app trying to download my entire storage onto the phone

### ISSUE THREAD

**Issue by theoden8** [nextcloud-snap/nextcloud-snap#2960]
#### Describe the bug
The title

#### To Reproduce

I have app version 3.30.4 and server snap version 29.0.7snap1. I disabled two-way sync entirely and cleared "on-device" files from being stored locally.

#### Expected behavior
It shouldn't try to download all of my data to the phone.

#### OS/snapd/snap version
ubuntu 24.04 29.0.7snap1
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud
    
```
nextcloud  29.0.7snap1  44391  latest/stable  nextcloud✓  -
```

and:

    $ snap version
    
```
snap    2.65.3+24.04
snapd   2.65.3+24.04
series  16
ubuntu  24.04
kernel  6.8.0-45-generic
```

    $ snap changes nextcloud
    
```
ID   Status  Spawn                   Ready                   Summary
631  Error   yesterday at 16:20 EET  yesterday at 16:30 EET  Auto-refresh snap "nextcloud"
632  Error   yesterday at 21:15 EET  yesterday at 21:25 EET  Auto-refresh snap "nextcloud"
633  Error   today at 03:55 EET      today at 04:05 EET      Auto-refresh snap "nextcloud"
634  Error   today at 08:30 EET      today at 08:40 EET      Auto-refresh snap "nextcloud"
635  Error   today at 13:15 EET      today at 13:25 EET      Auto-refresh snap "nextcloud"
636  Done    today at 13:25 EET      today at 13:25 EET      Running service command
```

#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).

**Comment by scubamuc** [comment]
Hey @theoden8 welcome and thanks for your request, sorry to hear you're having hassles with the android app

> The Nextcloud snap team packages a finished stable upstream Nextcloud, adds some snap magic, tests and releases that snap package. Since none of the Nextcloud snap team are upstream Nextcloud developers, they need to ensure that the Nextcloud snap does what it should. That entails packaging and testing fresh installs as well as automated updates so that the Nextcloud snap community has peace of mind

so the Nextcloud snap team really has no contact points with the android app or basic Nextcloud functionality... you'd be better off asking the folks who created the android app https://github.com/nextcloud/android or the [Nextcloud support community](https://help.nextcloud.com) will be glad to help (login with your github credentials)

as far as the running process you mentioned is concerned;
> ` 636  Done    today at 13:25 EET      today at 13:25 EET      Running service command `

that seems to be done... so everything should be fine

in case you're wondering, you can abort a running process by issuing the command `sudo snap abort <process ID>` but that doesn't seem necessary in your case. see [managing Nextcloud snap with snap](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Managing-Nextcloud-snap-with-Snap) for more details

you forgot to add your logs see [getting help](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Getting-help) and especially run the [debugging script](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Issue-Debugging-Scripts#debugging-script). without that we're in the dark about your system

**Comment by theoden8** [comment]
I think this is captured in https://github.com/nextcloud/android/issues/13872, this is indeed android app issue
