### ISSUE TITLE
documentation README, cron interval configuration outdated

### ISSUE THREAD

**Issue by scubamuc** [nextcloud-snap/nextcloud-snap#2988]
@nextcloud-snap/developers 

https://github.com/nextcloud-snap/nextcloud-snap#cronjob-interval-configuration 

review cronjob interval configuration in README:

> Nextcloud from 30.0.x recommends a 5 Minute cron interval:

> [5 minutes is already the default for new installs](https://github.com/nextcloud-snap/nextcloud-snap/blob/master/src/nextcloud/utilities/nextcloud-utilities#L8),

see https://github.com/nextcloud-snap/nextcloud-snap/wiki/configure-Nextcloud-snap#cronjob-interval-configuration

mentioned in #2974

**Comment by pachulo** [comment]
> review cronjob interval configuration in README:

Can you create a PR for this?

**Comment by scubamuc** [comment]
Hi Marc,  
  
as you know I've tried doing that on several occasions and failed miserably. So I thought this might be a better solution?  

  
Ulrich  
  
\--------------------------------  
🤿 www.scubamuc.de  
\================================

  
  

  
  

Am 11. Dezember 2024 um 23:42 schrieb "Marc" ***@***.******@***.***?to=%22Marc%22%20%3Cnotifications%40github.com%3E)\>:

**Comment by scubamuc** [comment]
done
#2996
