### ISSUE TITLE
Wiki has typo in commands for trusted proxy config

### ISSUE THREAD

**Issue by holysoles** [nextcloud-snap/nextcloud-snap#3002]
#### Describe the bug

At these two wiki sections, `trusted_poxies` should be `trusted_proxies`:

- https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-config.php#setting-trusted-domains

- https://github.com/nextcloud-snap/nextcloud-snap/wiki/configure-Nextcloud-snap

#### To Reproduce
View wiki pages

#### Expected behavior
N/A

#### Screenshots
N/A

#### OS/snapd/snap version
N/A

#### Logs
N/A

**Comment by scubamuc** [comment]
@holysoles 
well done, thanks for the heads up! 👋 glad someone reads the wiki 👌
typos corrected ✅
keep reading and don't be shy, suggestions are welcome
