### ISSUE TITLE
mysql-client requires root but doesn't say so

### ISSUE THREAD

**Issue by mcsantiago** [nextcloud-snap/nextcloud-snap#356]
On a fresh install of the snap, the root.ini file is not created from the first run of start_mysql. Consequently, mysql-client fails to run as well. Has this issue been seen before?

**Comment by kyrofa** [comment]
Not by me, anyway. Do you have any logs or anything that we can use to diagnose what happened? [this](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts) would be a good starting point.

**Comment by carag-matthew** [comment]
I'm closing this case. It turns out the mysql-client had to be run on sudo. The little things gave me away here! (embarrassingly)

**Comment by kyrofa** [comment]
@carag-matthew oh you're in good company :smile: . Indeed, mysql-client _requires_ sudo. Do you think it would be more friendly to have a shell script wrapper checking the user, and error if it's not root? We do that for `nextcloud.occ`, for example.

**Comment by carag-matthew** [comment]
Yes, that would be helpful! Currently, the display message is something along the lines of being unable to access the root.ini file.

**Comment by kyrofa** [comment]
Let's repurpose this issue, then. Sounds like a good candidate for Hacktoberfest.

**Comment by littlebrat** [comment]
I had this problem as well. I solved it by installing the package `mysql-client` and restarting nextcloud.
Shouldn't it be included as a dependency on the snap?
What am I missing?

**Comment by kyrofa** [comment]
@littlebrat it is included. Run `sudo nextcloud.mysql-client`. This bug is about the fact that sudo is required but it doesn't say so.

**Comment by littlebrat** [comment]
Yeah, you're right! I apparently had tried just running `nextcloud.mysql-client` and it wouldn't find the command: `zsh: command not found: nextcloud.mysql-client`. My bad :cry:
