### ISSUE TITLE
Contacts app throws a css error

### ISSUE THREAD

**Issue by startaq** [nextcloud-snap/nextcloud-snap#402]
I'm not sure if I should file this here or the contacts app repository. It throws this error when accessing the contacts app:

> ResourceLocator can not find a web root (root: /var/snap/nextcloud/4371/nextcloud/extra-apps/contacts, file: index.php/css/contacts/37e24f9372c097d3b65bf72574a3b81b-style.css, webRoot: , throw: true)

I'm running Nextcloud snap version 12.0.4snap1 (4371) on Ubuntu 17.10.

**Comment by kyrofa** [comment]
Huh. That's a bug we fixed before releasing v12. I'm using the contacts app as well, and don't see this error (it was actually the app I used to prove that I fixed the bug).

Where are you seeing this error-- in the log, or is the page itself white with that error (and nothing else) printed?

**Comment by startaq** [comment]
The error appears in the nextcloud log. It's a fresh install of 12.0.4snap1 on a fresh install of Ubuntu 17.10. The contacts app itself seems to work fine, I haven't noticed any major errors or visual issues. The error appears every time you access the contacts app.

**Comment by kyrofa** [comment]
How odd... I can't reproduce. You're sure you don't have to do anything specific to trigger the error? Just load up the contacts app and "boom" error appears in log?

**Comment by startaq** [comment]
Yes, just tried it again. It's enough to just open the Contacts app, then immediately the error appears in the log. Clicking on other contacts doesn't throw another error, but reopening the app will throw it again.

I'm not sure if it's possible that it's caused by another app, so here's a list of all enables ones:

> Activity	2.5.2
Collaborative tags	1.2.0
Comments	1.2.0
Deleted files	1.2.0
Federation	1.2.0
File sharing	1.4.0
First run wizard	2.1
Gallery	17.0.0
Log Reader	2.0.0
Monitoring	1.2.0
Nextcloud announcements	1.1
Notifications	2.0.0
Password policy	1.2.2
PDF viewer	1.1.1
Share by mail	1.2.0
Text editor	2.4.1
Theming	1.3.0
Usage survey	1.0.0
Versions	1.5.0
Video player	1.1.0
Brute-force settings	1.0.3
Calendar	1.5.7
Contacts	2.0.1
Unsplash	1.0.5
Video calls	2.0.2

**Comment by Sovica** [comment]
Just wanted to give my feedback here as well. I'm getting the same error on my fresh snap install:

Error | lib | ResourceLocator can not find a web root (root: /var/snap/nextcloud/4371/nextcloud/extra-apps/mail, file: index.php/css/mail/c6716b9fd3813bfff50493637de0dffe-mail.css, webRoot: , throw: true)
-- | -- | --

**Comment by kyrofa** [comment]
Interesting-- note that I don't see this in the admin interface, but if I look at the raw logs, I see this as well. I'll investigate when I can, although I'll admit it's not the highest priority since I don't notice any ill effects from it. Does anyone else?

**Comment by Sovica** [comment]
No ill effects as far as I can tell.

**Comment by Matttthias** [comment]
Same error message here. 
I perceive no misbehaviour of the contacts app though.

**Comment by pachulo** [comment]
Is this issue still present with the latest 13.0.4 @Matttthias & @Sovica ?

**Comment by Matttthias** [comment]
Actual Version: 13.0.4.
Entered Nextcloud -> Entered Contacts App -> Entered Settings and checked Log

Error message still there:
"ResourceLocator can not find a web root (root: /var/snap/nextcloud/7658/nextcloud/extra-apps/contacts, file: index.php/css/contacts/5fd0-7d44-style.css, webRoot: , throw: true)"

I started to use the polls app recently and received similar error message "ResourceLocator can not find a web root". Since Upgrade to 13.0.4., same error message with the calendar app. Raised dedicated issue for that (#625), since last item seems to have impact on correct synchronization. 

With polls and contacts app I have not observed misbehaviour, except the error msg itself.

**Comment by pachulo** [comment]
OK, I'm seeing the same error here: maybe we should open a bug upstream.
