### ISSUE TITLE
sync dies on ubuntu NC client and in browser when both are accessed

### ISSUE THREAD

**Issue by wayneoutthere** [nextcloud-snap/nextcloud-snap#515]
I'm not really sure where to post this bug, but since it's connected with the snap I just installed I'll start here.  Here is what happens:
*connect to nextcloud via ubuntu snap on ubuntu gnome
*sync starts everything looks good
*open browser (same local LAN as raspberry pi, if that matters) and enter URL login to Next
*as soon as the browser attempts to reach the login screen it kills the local machine NC client sync and 'loses connection'

This also happened with the appimage of NC client that I tried so I can't blame the snap by itself but something is definite weird.

then I shut down NC this time and when it reopened it had a'keychain' message.

*I entered the password for the user and the sync is started again.  I will try one more test to test the theory by going to the browser to see what happens now...

*killed connection to pi.  now i have to reboot pi it looks like...

Thanks for any help suggestions with this weird one.

**Comment by kyrofa** [comment]
This is the issue tracker for the snap of the Nextcloud server itself. Is that the snap to which you refer here, or are you talking about the Nextcloud client snap, which tracks issues [over here](https://github.com/nextcloud/client_theming)?

**Comment by wayneoutthere** [comment]
i think it must be the client then... because it happens on more than one client.  I'll move it over there with copy/paste and you can close here I gues thanks

**Comment by mauricioduarte01** [comment]
As far I know the server side is the snaps version. The issue happens when he is syncing files to the server (using any client of NC available) and then open open NC using the browser.

**Comment by kyrofa** [comment]
The only time the "snap" is specified is "connect to nextcloud via ubuntu snap on ubuntu gnome", which doesn't indicate to me that server is the snap. @wayneoutthere is the server to which you're connecting also a snap?

**Comment by wayneoutthere** [comment]
sorry about that. 
I am using TWO snaps:

1. snap client on ubuntu gnome
2. server snap on raspian on a pi

also I posted stuff over here:

https://github.com/nextcloud/client_theming/issues/247

**Comment by kyrofa** [comment]
Ah, then the comment part here is indeed the server snap, so I'll keep this open. This may come down to simple resource limitations on the rpi, though. Which pi are you using?

**Comment by wayneoutthere** [comment]
brand new pi 3 B+

**Comment by wayneoutthere** [comment]
little update: it seems that after I went in and, with command line, completely wiped all data that was on the Pi, and the started a fresh sync using client that the sync seems to be having more success.  I will let it run but i wonder if there is some way where data on the drive can screw up the connection?  That seems unlikely but .. why is it starting to work better?
