### ISSUE TITLE
I have recently got this code integrity error /warning.

### ISSUE THREAD

**Issue by sign-out** [nextcloud-snap/nextcloud-snap#620]
I have recently got this code integrity error /warning. I run next cloud from the snap(as you probably guessed as I'm here) so I am unsure how to resolve and or restore the apps integrity as the snap is read only. I thought I should let you know of it as i don't know how it happened or why. i have left a similar issue for the totp app so your re both made aware of it. 

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- twofactor_rcdevsopenotp
	- FILE_MISSING
		- l10n/.tx/config

Raw output
==========
Array
(
    [twofactor_rcdevsopenotp] => Array
        (
            [FILE_MISSING] => Array
                (
                    [l10n/.tx/config] => Array
                        (
                            [expected] => 5ad14bb93e25fd93ebbd96e1e995367db065d11953f0c3ac707962098956f1a9f5534a7dcceb834ebfb4a6b3edd7f6a8c6cbddd01c052bbb61fe951c779f2fca
                            [current] => 
                        )

                )

        )

)

**Comment by kyrofa** [comment]
Hmm. Is this the "OpenOTP Two Factor Authentication" app? I tried installing it but I can't because soap isn't available. How did you install this app?

**Comment by sign-out** [comment]
No this is the twofactor_totp app sadly , while i did have the OpenOTP  Two Factor installed previously in the new update it also broke for the same reason so i uninstalled it ^^; (although i wonder if there is a way to install soap as a package ? )

**Comment by ur4dc** [comment]
> Hmm. Is this the "OpenOTP Two Factor Authentication" app? I tried installing it but I can't because soap isn't available. How did you install this app?

Same here, can't install the "OpenOTP Two Factor Authentication" App

![soap-missing](https://user-images.githubusercontent.com/17741823/59418296-144c5300-8dc9-11e9-9698-e3c7b1b003b4.png)
