### ISSUE TITLE
LDAP / AD Password Change

### ISSUE THREAD

**Issue by ghost** [nextcloud-snap/nextcloud-snap#640]
Hi everyone,

I am wondering, if it would be possible to change the LDAP / AD password using the NextCloud snap.
It could be I need to address this with the NextCloud people themselves, but for the moment am assuming it should work.
I've configured LDAPS with certificated in Active Directory and I think what is missing is that the certificate must be trusted by the snap or the Ubuntu machine the snap is running on.
Can this already be done with the snap and if so, how?

**Comment by kyrofa** [comment]
I'm afraid I know little enough about how this works that I'm not sure what's being asked here. @adhami03, any chance you know?
