### ISSUE TITLE
syslog flooded with mdns-publisher message

### ISSUE THREAD

**Issue by francisco-dlp** [nextcloud-snap/nextcloud-snap#642]
After installing nextcloud I get the following message around 15 times per second in my syslog:

```
nextcloud.mdns-publisher[16631]: 2018/07/24 10:00:34 Could not read from &{{%!s(*net.netFD=&{{0 0 0} 6 10 2 false udp6 0xc82000cc30 <nil> {140106196042016}})}}: dns: failed to unpack truncated message
```

I am totally new to nextcloud and I couldn't find a way to fix the issue.

**Comment by kyrofa** [comment]
Yikes, that's a new one. What OS are you on?

**Comment by francisco-dlp** [comment]
Debian GNU/Linux buster/sid

**Comment by francisco-dlp** [comment]
I have the same issue when using Ubuntu 18.04 in the same network using a wired connection. I don't experience the issue when connecting with wifi.

Is there anyway in which I can stop it writing to the system logs with the current nextcloud snap version?

**Comment by kyrofa** [comment]
Are you using ipv6?

**Comment by francisco-dlp** [comment]
No, I'm not using ipv4. The particularity of my installation is that it is in a big work network. If I connect to the same network via wifi I don't experience the issue, probably because the network is configured not to be able to access some network devices, e.g. network printers, through wifi.

**Comment by kyrofa** [comment]
Huh, then it's possible something is passing out invalid mdns packets and the library being used in the mdns binary is choking on them, and complaining about it loudly. Unfortunately the library offers no way to disable these prints, but there might be better options these days.

**Comment by francisco-dlp** [comment]
Yes, that's very likely to be the case. Finding an alternative mdns library that can be configured to avoid not to print this error message should be useful for people that, like me, install nextcloud in computers in large networks where chances are that something will be sending around invalid mdns packets.

**Comment by kyrofa** [comment]
Agreed, I'll look into it.
