### ISSUE TITLE
Changed data directory, still limited

### ISSUE THREAD

**Issue by RiimoH** [nextcloud-snap/nextcloud-snap#668]
Hello Guys
I recently installed Nextcloud via the snap function. I followed [this guide](https://github.com/nextcloud/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition) to move and configure my data directory to my 1TB  hdd, which is mounted at /media/satahdd/. Dispite that change I'm limited to the size of the old storage.
![grafik](https://user-images.githubusercontent.com/15363674/43724448-438301b0-999a-11e8-8282-aa904772c5c7.png)

Additionaly I added the HDD as external storage named as 'Lokal'. This way I verified, that the files are on the HDD. 

Is there an configuration I missed?

**Comment by r4co0n** [comment]
Hi,
does this bare any resemblance with your issue?: https://github.com/nextcloud/server/issues/9260

I haven't tried changing the data directory, I just store most of my stuff in a 'Store' folder connected to an external storage (local folder) that has mounted a DigitalOcean Space (EC2-like block storage) using [s3ql](https://github.com/s3ql/s3ql).
