### ISSUE TITLE
Nextcloud behind [external!] Apache2 proxy?

### ISSUE THREAD

**Issue by CyberSecGuy** [nextcloud-snap/nextcloud-snap#683]
CloudFlare pointing _**cloud.domain.tld**_ to _**external.ip.address.here**_

VM #1 - **WEBPROXY**: 192.168.1.98 **[port 80 forwarded here]**
VM #2 - **NEXTCLOUD**: 192.168.1.82

Both VMs running Ubuntu 16.04

WebProxy Apache2 vhost config:

```
<VirtualHost *:80>
        ServerName cloud.domain.tld
        Redirect permanent / https://cloud.domain.tld
</VirtualHost>

<VirtualHost *:443>
        ServerName cloud.domain.tld

        ServerAdmin name@domain.tld

        SSLProxyEngine on
        # UNSAFE!
        SSLProxyVerify none
        SSLProxyCheckPeerCN off
        SSLProxyCheckPeerName off
        SSLProxyCheckPeerExpire off

        ProxyPreserveHost On

        ProxyPass / https://192.168.1.82/
        ProxyPassReverse / https://192.168.1.82/

        ErrorLog ${APACHE_LOG_DIR}/cloud/error.log
        CustomLog ${APACHE_LOG_DIR}/cloud/access.log combined

        Include /etc/letsencrypt/options-ssl-apache.conf
        SSLCertificateFile /etc/letsencrypt/live/cloud.domain.tld/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/cloud.domain.tld/privkey.pem
</VirtualHost>
```

Issue: cloud.domain.tld forwards correctly and displays proper URL and front panel. However, when attempting to login with valid credentials and clicking "login" the page does not react, does not forward to the login page. When connecting to the nextcloud page via **192.168.1.82** internally, it functions as normal and I am able to use the full system.

/var/snap/nextcloud/current/nextcloud/config/config.php

```
  'trusted_domains' =>
  array (
    0 => 'localhost',
    1 => '192.168.1.82',
    2 => 'cloud.domain.tld',

  'proxy' => '192.168.1.98',
  'trusted_proxies'   => ['192.168.1.98'],
  'overwrite.cli.url' => 'http://cloud.domain.tld',
```

Any help would be greatly appreciated!

**Comment by jon-skocik** [comment]
https://docs.nextcloud.com/server/13/admin_manual/issues/general_troubleshooting.html#other-issues

- Disabled JavaScript minimizing & purged cache, issue persists.

**Comment by kyrofa** [comment]
Should your overwrite url be HTTPS?

**Comment by pa4080** [comment]
Hello, @CyberSecGuy, did you succeed with this task?
