### ISSUE TITLE
Method to delete letsencrypt certificate

### ISSUE THREAD

**Issue by stone212** [nextcloud-snap/nextcloud-snap#690]
I did not see any documentation on a method to delete a letsenceryt certificate.

If using certbot manually you would use `certbot delete` and see a list of certs on the system.  Is there a way to do this with the snap?

**Comment by kyrofa** [comment]
Not quite as nicely, I'm afraid. All the certs are in `/var/snaps/nextcloud/current/certs`, so you can remove them manually.

**Comment by stone212** [comment]
Okay.  The down side to this is that `certbot delete` contacts the letsencrypt server and deletes the servers from their database.  That allows me to re-issue certificates under the same name.  this is useful if I am changing servers.  So the current method to delete the certificate is fine for the filesystem but not for the usability of the cert.

**Comment by stone212** [comment]
It may not be a high priority but I have discovered a second use case (after moving servers): https://github.com/nextcloud/nextcloud-snap/issues/750.

**Comment by dandar** [comment]
> 
> 
> Not quite as nicely, I'm afraid. All the certs are in `/var/snaps/nextcloud/current/certs`, so you can remove them manually.

By remove them manually, do you mean delete all folders (named after domains) located in `/var/snaps/nextcloud/current/certs/certbot/config/live` except the `README` folder?  

We have multiple folders with same domain with `0001', `0002`', etc. appended to the name.   Just renaming the first folder worked for us, and it seems lets-encrypt is using the cert located in the folder.0001 and did not recreate the folder.  Some explanation (or link) would help us a lot.  Thank you.
