### ISSUE TITLE
"Internal Server Error" after installing Collabora Online and trying to open *.odt file

### ISSUE THREAD

**Issue by rusmircrnica** [nextcloud-snap/nextcloud-snap#693]
Referred to the same issue: https://github.com/nextcloud/nextcloud-snap/issues/455

Absolutely the same issue here. Is there any solution for this? I've spent weeks to solve it, but unsuccessfully. 

Thanks

**Comment by rusmircrnica** [comment]
@ashgoodman, Yes, I have install it the same as you described.
Here are the screenshots:
http://prntscr.com/kvfjm3
http://prntscr.com/kvfk39
http://prntscr.com/kvfkfz

It would be very helpful if anyone can provide a solution.

Thanks

**Comment by ashgoodman** [comment]
Try it without the port. I didn't need the port in the nextcloud settings to make mine work.

And when you set up your docker of collabora make sure you started it with

`sudo docker run -t -d -p 127.0.0.1:9980:9980 -e 'domain=cloud\\.example\\.com'`

Where `cloud\\.example\\.com` is the **nextcloud instance** not the docker instance

**Comment by rusmircrnica** [comment]
If my nextcloud instance is cloud.xy.com do I  have to set cloud\\.cloud.xy\\.com or cloud\\.xy\\.com

**Comment by rusmircrnica** [comment]
@ashgoodman 
 **is the collabora server running on the same server and subdomain as nextcloud?**
 - Collabora and Nextcloud are running on the same server. Subdomain is hosted on another server.

Thanks for you help, I will raise a ticket via provided link.

**Comment by ashgoodman** [comment]
I am using nextcloud snap on an ubuntu 18.04 server.  I installed collabora using its docker on another ubuntu server on a subdomain. Pointed it to my nextcloud server and no issues. 

Also did a docker with libre office online the same way and it worked as well. 

I don't think you can modify the Apache config on the snap.  But if you install collabora on a separate server from nextcloud you should be fine

**Comment by rusmircrnica** [comment]
@ashgoodman, so, you have installed ex. cloud.domain.com on one Ubuntu 18.04 and ex. collabora.domain.com on other Ubuntu 18.04. In cloud.domain.com you have enabled Collabora and pointed to collabora.domain.com, and that's it?
