### ISSUE TITLE
Group folder sharing - "Storage is temporarily not available" after restoring Snap on other machine

### ISSUE THREAD

**Issue by mikolodz** [nextcloud-snap/nextcloud-snap#744]
Hello,

I am moving Nextcloud Snap from one machine to the other using same revision: **13.0.6snap1** installed on both of them. Storage is also transferred and the new config.php points to new data folder.

After copying @m1:/var/snap/nextcloud to @m2:/var/snap/nextcloud everything works flawlessly except shared group folders. Some time ago I have created a group folder "Poczekalnia - Dokumenty", using **Group folders plugin** from Nextcloud store and shared it with admin user only. Then, from admin account I shared this folder with other user groups. It has been working fine on m1, but after copying whole data structure to the m2 the folder is accessible only from the admin account. Other users see the folder, but they cannot access it. From admin account I can see that this folder is not actually shared (empty shares - as if information about sharing were lost during migration). It means that shares do somehow disappear during moving snap. The only difference between m1 and m2 is that on m2 the path to the Nextcloud data folder is slightly different (config.php updated, works as it should). Any ideas?

Here is the error I'm getting:

`{"reqId":"FiSbntNiaJ5ZeSGcSJRW","level":4,"time":"2018-10-07T00:33:33+00:00","remoteAddr":"::1","user":"xxxxxxxxxxxxx","app":"webdav","method":"PROPFIND","url":"\/remote.php\/webdav\/Poczekalnia%20-%20Dokumenty","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Message\":\"Storage is temporarily not available\",\"Code\":0,\"Trace\":\"#0 \\\/snap\\\/nextcloud\\\/8971\\\/htdocs\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(967): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('Poczekalnia - D...')\\n#1 \\\/snap\\\/nextcloud\\\/8971\\\/htdocs\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1666): Sabre\\\\DAV\\\\Server->getPropertiesIteratorForPath('Poczekalnia - D...', Array, 1)\\n#2 \\\/snap\\\/nextcloud\\\/8971\\\/htdocs\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(359): Sabre\\\\DAV\\\\Server->generateMultiStatus(Object(Generator), false)\\n#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/snap\\\/nextcloud\\\/8971\\\/htdocs\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/snap\\\/nextcloud\\\/8971\\\/htdocs\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#6 \\\/snap\\\/nextcloud\\\/8971\\\/htdocs\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/snap\\\/nextcloud\\\/8971\\\/htdocs\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(80): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/snap\\\/nextcloud\\\/8971\\\/htdocs\\\/remote.php(164): require_once('\\\/snap\\\/nextcloud...')\\n#9 {main}\",\"File\":\"\\\/snap\\\/nextcloud\\\/8971\\\/htdocs\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php\",\"Line\":163}","userAgent":"yyyyyyyyyyyyyy"}`

**Comment by kyrofa** [comment]
Did you copy the database as well?

**Comment by mikolodz** [comment]
> Did you copy the database as well?

@kyrofa I copied whole directory: /var/snap/nextcloud/8971 with root privileges.
Users, groups and config are being loaded properly. The only dir I didn't copy was /var/snap/nextcloud/common. As far as I understand DB resides inside snap, so it was copied with other stuff.

Is it possible that changing the data dir path causes share corruption?
Am I missing something important?

**Comment by mikolodz** [comment]
@kyrofa what I'm facing is a serious problem - what can I do to solve it or what more data should I provide you with so that you could help to diagnose the problem?

It should be quite easy to reproduce:
- install nextcloud snap (8971) on 2 Ubuntu machines
- set the path to the external data folder for example /media/NextCloudA
- configure admin account on the 1st, add some users, login to their accounts (to activate them)
- install Group folders plugin
- add new group folder and share it with admin user (from admin account settings)
- from directory view, share this new folder with other users, throw some files inside
- move the NextCloud snap folder to the second machine
- copy the data directory from **@m1:**/media/NextCloudA to **@m2:**/media/NextCloudB
- change the data folder path to the /media/NextCloudB on m2 (in /var/snap/nextcloud/8971/nextcloud/config/config.php)

Did anyone successfully move NextCloud snap between machines, including sharing data?

**Comment by kyrofa** [comment]
> The only dir I didn't copy was /var/snap/nextcloud/common.

This is the directory containing the data itself, unless you're storing it elsewhere? In which case, have you connected the `removable-media` plug?

**Comment by mikolodz** [comment]
@kyrofa 
Yes, I enabled removable-media with:
`snap connect nextcloud:removable-media`

 and the path to the data is stored in config.php:
'skeletondirectory' => '/media/NextCloud/skeleton',
'datadirectory' => '/media/NextCloud/data'

**Comment by kyrofa** [comment]
I'm looking closely at that error. Within your new `datadirectory`, under the same username, do you have a file named "Poczekalnia - Dokumenty" ? The error to my uneducated eyes (don't know much about webdav) looks like it can't find it.

**Comment by mikolodz** [comment]
@kyrofa 
Shared folders aren't stored as regular files and directories. For example in my user home folder (~/files) I have only 1 physical directory (Documents), but when I access my files from the web browser I see also dozen of other directories, which are shared folders.
"Poczekalnia - dokumenty" is stored in /media/NextCloud/data/__groupfolders/5/ and there is no symlink in my user files/
