### ISSUE TITLE
Allow to change the max upload file size from the webgui.  

### ISSUE THREAD

**Issue by bonsje** [nextcloud-snap/nextcloud-snap#77]
Hi there, 

I don´t know if this kind of issue was opened before (could not find a issue about this).  
I have tried the snap package for Nextcloud, seems to be working fine and looking good so far. 

The only issue I encounter is that i cannot change the Max Upload file size from the webgui (is now 10gb).  
It seems that the .htaccess is readonly. 

Will there be and option, to edit the Upload size with an Utility or will the edit function work in the admin panel in the future (make the .htaccess writable)? 

Thanks, and keep up the good work.  

Kind regards, 
Bons.

**Comment by oparoz** [comment]
Actually, this has nothing to do with `.htaccess`, but it's the same problem. The Snap doesn't have write access yet to the `.user.ini` file.
One problem with `.htaccess` is the performance penalty associated with its use and I need to look it up, but I suspect the same thing is true with `.user.ini`.

The planned solution is to allow users to [make modifications to config files](https://github.com/nextcloud/nextcloud-snap/issues/50), but it will first only be available to users who can use the shell.

**Comment by kyrofa** [comment]
This kind of depends upon Apache and PHP settings changing in concert. The admin interface can't change them both, so I don't believe this issue can be solved quite so nicely.

**Comment by bonsje** [comment]
Thnx for explaining :), hope to see this kind of feature in the future. 
(command line option/setting or webgui).

**Comment by oparoz** [comment]
> This kind of depends upon Apache and PHP settings changing in concert

For some settings, yes, but not for this one per example. We only need to touch the PHP file.

The one thing we need to discuss is whether it's safe to edit these files from the admin zone, since everything is run as root, but I think we discussed about using a daemon of sort for such requests?

**Comment by lindhe** [comment]
Both `.htaccess` and `.user.ini` seems to have the maximum file upload size to 511M, but yet my GUI says 10 GB. Is it reporting incorrectly, or is the limit set somewhere else?

![screenshot from 2017-03-27 21-29-41](https://cloud.githubusercontent.com/assets/7773090/24374303/9c9452b0-1334-11e7-889e-84dcae5eec7f.png)

**Comment by bonsje** [comment]
Hi, a question. 

I see with the latest snap update, that you can change the port numbers now, and i see this page: https://github.com/nextcloud/nextcloud-snap/issues/374

@kyrofa  Is it possible to get some kind of a function to increase the max file upload value with a CLI command, like the port number change command ? 

That could be a great solution for users like me that have files bigger than the 10 Gb limit :)

**Comment by kyrofa** [comment]
@bonsje definitely. However, I'm a little confused by something. I have the max upload file [currently set to 16G](https://github.com/nextcloud/nextcloud-snap/blob/master/src/php/config/php-fpm.d/www.conf#L419), not 10. But 10 is being shown in the admin UI. Why? I have no idea where the 10 is coming from.

**Comment by bonsje** [comment]
@kyrofa that is strange indeed. so far i can remember in the past with owncloud. you needed to modify the .htaccess file that overruled the php max upload size value and owncloud looked in/after this setting. 
(if you edited the setting in the admin panel the value in the .htaccess file got updated).  
its like mentioned in your linked documentation, 

But when i look in the .htaccess files on the nextcloud folder it see the settings are default like they came from a clean install: 

``
/snap/nextcloud/3317/htdocs/.htaccess

</IfModule>
<IfModule mod_php7.c>
  php_value upload_max_filesize 511M
  php_value post_max_size 511M
  php_value memory_limit 512M
  php_value mbstring.func_overload 0
  php_value default_charset 'UTF-8'
  php_value output_buffering 0
  <IfModule mod_env.c>
    SetEnv htaccessWorking true
  </IfModule>
``
Maybe nextcloud stores the value in an other file? 
So far i cannot find traces where the value of 10G is stored, sadly :(

**Comment by kyrofa** [comment]
Yeah we [disable those anyway](https://github.com/nextcloud/nextcloud-snap/blob/master/src/apache/conf/httpd.conf#L118). I'll have to investigate this, but I'm afraid it's only as I find time. Please feel free to investigate on your own if you're up for it.

**Comment by Guard13007** [comment]
Chiming in to say I have not messed with settings other than the HTTP port (I'm running on localhost only behind a proxy) and it is showing 10GB for me as well.

**Comment by tobia** [comment]
Uh... sorry for being a bit dense, but could anybody tell me if there is a way to increase the limit, when using the snap? I found these references, but they are all in the readonly filesystem and they don't seem to reference a `snap set` config item, unless I'm reading it wrong:

    config/php/php-fpm.d/www.conf: php_value[upload_max_filesize] = 16G
    config/php/php.ini:            upload_max_filesize = 2M
    htdocs/.htaccess:              php_value upload_max_filesize 511M
    htdocs/.htaccess:              php_value upload_max_filesize 511M
    htdocs/.user.ini:              upload_max_filesize=511M
    htdocs/lib/base.php:           @ini_set('upload_max_filesize', '10G');

(Also, they are all over the place!?)

**Comment by Guard13007** [comment]
@tobia Could easily be that the limits specified are a per-request limit, but uploads can be done over multiple requests. (That's actually something I need to work on myself for an unrelated project.)

**Comment by kyrofa** [comment]
@tobia honestly I have no idea either. Good find on this one though:

```
htdocs/lib/base.php:  @ini_set('upload_max_filesize', '10G');
```

I bet that's where the "10" in the UI is coming from.

**Comment by tobia** [comment]
@Guard13007 Yes, the sync client purposefully uploads all files in 10MB chunks, to support the pause/resume functionality, the auto-resume after network errors or reboot, and to support _unlimited_ file size (which is an awesome, but little known feature of the OC/NC sync client)

In my test I specifically used Curl to perform a single HTTP PUT, to test the limit of a _browser_ upload, and I still was able to upload a 50GB file. So the real limit remains a mystery.

**Comment by Guard13007** [comment]
@tobia I was actually referring to browser uploading. Many sites implement a system for uploading in chunks through a browser, and is something I will be implementing as well.

**Comment by eespitiarea** [comment]
Since snap manages the app, one is not able to directly commit changes, it has to do through snap itself. Given the options and commands available in this app, one can just replace underscores with dashes after php in the name of the parameter, like:

php.upload-max-filesize
php.post-max-size
php.max-input-time
php.max-execution-time
And then for the upload size: snap set nextcloud php.post-max-size=16G or sudo if is system-wide.

**Comment by kyrofa** [comment]
> [...] one can just replace underscores with dashes after php in the name of the parameter [...]

The way you said that (and given #1054) gives the impression that this is available today. I just want to clarify by saying that it's not. We're not really looking to expose every configuration option of every dependency here, particularly given that it looks like that limit is hard-coded (i.e. changing these options won't actually fix it).

**Comment by eespitiarea** [comment]
@kyrofa, how is is that `sudo snap set nextcloud php.upload-max-filesize=16G` does change the settings persistently while using `nextcloud.occ` doesn't and this is reflected in the web UI?

Appreciate your comments, just trying to understand.

**Comment by YamiYukiSenpai** [comment]
You should update the manual and mention the snap method.

**Comment by nidico** [comment]
> This issue is stale because it has been without activity for 60 days. It will be closed after 7 more days of inactivity.

Please not! For a proper explanation why this is a bad idea, read https://drewdevault.com/2021/10/26/stalebot.html

**Comment by kyrofa** [comment]
Drew is certainly welcome to his opinions, as are you of course. For me, if no one is actively working on an issue, and no one cares enough about it to say something when the bot points out that it's stale, it's not useful to anyone and keeping it open seems pointless. Closing an issue doesn't lock it-- advice and conversation can still happen there. It's just a more honest representation of the state of things: no one has touched this issue, and it's likely that no one will unless the reader would like to. And if that happens, it can be re-opened.

**Comment by Polve** [comment]
I'm using the snap (version 22.2.3snap2 right now) and I can't understand what I need to set to change the default upload size that it seems to be only 2MB.
I executed the suggested:
snap set nextcloud php.upload-max-filesize=16G
but without any result.

Any hints?

**Comment by Polve** [comment]
Please disregard previous message and forgive me: the problem was the missing client_max_body_size in the reverse proxy.

**Comment by kyrofa** [comment]
>  snap set nextcloud php.upload-max-filesize=16G

I tried my best to explain that these commands do absolutely nothing. I think this issue is leading people astray, I'm going to close it.
