### ISSUE TITLE
Push notifications to admins

### ISSUE THREAD

**Issue by oparoz** [nextcloud-snap/nextcloud-snap#78]
We'll have to investigate which mechanisms can be used to push notifications to admin users so that they can be made aware of major changes which may have an impact on their Nextcloud or snap configuration.
- Maybe use the announcement centre if we can send messages to admins only
- We need a way to acknowledge that the user has taken action

**Comment by kyrofa** [comment]
Yeah this would be great. I don't care so much about tracking if the user has acknowledged the notification, but being able to let them know an update has happened and "here's the changes" would be ideal. I don't know anything about the announcement center though.

**Comment by oparoz** [comment]
Something like this should make it to NC12:
https://github.com/nextcloud/server/issues/2672

**Comment by kyrofa** [comment]
Looks like we can only use push notifications if we're an app. Instead, I think we'll start using general admin notifications once NC14 is out ([reference](https://github.com/nextcloud/notifications/blob/master/docs/admin-notifications.md)).
