### ISSUE TITLE
[Documentation] How to backup?

### ISSUE THREAD

**Issue by srkunze** [nextcloud-snap/nextcloud-snap#796]
Hi,

coming from here:

![image](https://user-images.githubusercontent.com/1389648/48973194-2ab3dc80-f03a-11e8-88f4-6f68f995ebc3.png)

and reading this https://docs.nextcloud.com/server/13/admin_manual/maintenance/backup.html

I wonder how to handle the backup process when using snaps.

Am I missing some docs here?

**Comment by pachulo** [comment]
For the snap is different and you should be using the `export` and `import` commands. More info with:
`sudo nextcloud.export -h`

**Comment by srkunze** [comment]
Alright, I see. Reading the help messages, I think I can sum up the issue as following:

1) the web docs should explain the procedure (export + import) + example

2) missing `<backup dir>` while exporting



Help messages:
```
root@nas:~# nextcloud.export -h
Usage:
    nextcloud.export [OPTIONS]
    Export data suitable for migrating servers. By default this
    includes the Nextcloud database, configuration, and data
    (equivalent to running nextcloud.export -abcd).

Available options:
    -h: Display this help message
    -a: Include the (non-default) apps
    -b: Include the database
    -c: Include the config
    -d: Include the data (can be quite large)
root@nas:~# nextcloud.import -h
Usage:
    nextcloud.import [OPTIONS] <backup dir>
    Import data exported from another Nextcloud snap instance.
    By default this imports the database, config, and data
    (equivalent to running nextcloud.import -abcd).

Available options:
    -h: Display this help message
    -a: Import the (non-default) apps
    -b: Import the database
    -c: Import the config
    -d: Import the data
```

**Comment by Refhi** [comment]
It would seems that 14.0.3snap1-rc1 doesn't install those tools, whether on an update from 13. or on a fresh install.

Should I open a new bug ticket ?

**Comment by srkunze** [comment]
Yes, please. This is about documentation.

**Comment by JokerGermany** [comment]
I hope it's okay, when i use this issue.

Is there any possibillity writing the backup to another place?
My Backup failed because the root filesystem was full...

Will try a link now...
