### ISSUE TITLE
User authentication with IMAP: install php-imap

### ISSUE THREAD

**Issue by Bernhard---H** [nextcloud-snap/nextcloud-snap#800]
I'd like to use "User authentication with IMAP": https://docs.nextcloud.com/server/14/admin_manual/configuration_user/user_auth_ftp_smb_imap.html#imap

~=> Is it possible to add the php-imap extension after the installation to the nextcloud snap?
Or do I need to customize the package before its installation? How?
OR would it be possible that you add something like an install-flag for the nextcloud snap that enables php-imap?~

**EDIT:** I couldn't find any info about modifying a snap installation or using an install-flag => it doesn't look possible.

Could you maybe add the php-imap extension to your snap for everybody?

**Comment by lpalgarvio** [comment]
there might be security or other issues like they wrote down for:
#1032
#1144
#1046
