### ISSUE TITLE
External Storage (Local) 

### ISSUE THREAD

**Issue by nightmare1942** [nextcloud-snap/nextcloud-snap#855]
Hi,
I do have a similar problem with NC14.0.5 as described in [here](https://github.com/nextcloud/nextcloud-snap/issues/822).
I mounted an SMB share via fstab to /media/storage.
Afterwards I tried to use the external storage (local) extension to mound a folder under this mountpoint.
It worked for a long time but now it has the following error:

`stat(): stat failed for /media/storage/pictures/ at /snap/nextcloud/10791/htdocs/lib/private/Files/Storage/Local.php#142`

I also connected the` removable-media` plug as described here

But I still only see the red dot and the media is not working.

Any clues?

**Comment by r4co0n** [comment]
Hi,
you didn't state whether your mount point is available outside of the snap now and whether it still contains `pictures`. You can test for this running
```
ls /media/storage
ls /media/storage/pictures
```
The error message you posted states that the `pictures` folder was not available to the snap.

**Comment by nightmare1942** [comment]
Hi,
yes they are available:

`ll /media/storage/
insgesamt 36918308
dr-xr-xr-x. 2 root root           0 28. Dez 10:41 Bilder
dr-xr-xr-x. 2 root root           0 16. Nov 10:57 Dokumente
dr-xr-xr-x. 2 root root           0  5. Jan 00:10 Downloads
`

`ll /media/storage/Bilder/
insgesamt 4
drwxr-xr-x. 2 root root   0  2. Mär 2018  2001
drwxr-xr-x. 2 root root   0 17. Jun 2017  2002
drwxr-xr-x. 2 root root   0 17. Jun 2017  2003
drwxr-xr-x. 2 root root   0 26. Nov 2017  2004
`
As you see, it's availabe, that's why it's so weired to me!
(just for clarification: The `pictures` folder is called `Bilder` in German! ;) )

**Comment by kyrofa** [comment]
Can you run this command and let me know it's output, please?

    $ sudo snap run --shell nextcloud.occ <<EOF
    ls -l /media/
    EOF

**Comment by nightmare1942** [comment]
Hi,
the output is:

`total 0
drwxr-xr-x.  2 root root  40 Jan 13 18:34 .
drwxr-xr-x. 24 root root 321 Dec 14 11:54 ..`

**Comment by kyrofa** [comment]
That indicates that the snap is firing up before the mount is put in place. You might consider doing the mount in system instead.

**Comment by nightmare1942** [comment]
Sry, I'm not sure what'd you mean. 

`$ systemctl status media-storage.mount
● media-storage.mount - /media/storage
   Loaded: loaded (/etc/fstab; bad; vendor preset: disabled)
   Active: active (mounted) since So 2019-01-13 18:34:56 CET; 5 days ago
    Where: /media/storage
     What: //server/storage
     Docs: man:fstab(5)
           man:systemd-fstab-generator(8)
  Process: 5551 ExecMount=/bin/mount //server/storage /media/storage -t cifs -o defaults,credentials=/root/.smbcredentials (code=exited, status=0/SUCCESS)
    Tasks: 0
`
That's what systemd says

**Comment by nightmare1942** [comment]
Okay, i did the mount in systemd:

`/lib/systemd/system/media-storage.mount`

`[Unit]
DefaultDependencies=yes

[Mount]
What=//Server/Storage
Where=/media/storage
Type=cifs
Options=defaults,credentials=/folder/.credentials
DirectoryMode=0755
TimeoutSec=0

[Install]
WantedBy=remote-fs.target`

But still not working.

**Comment by topf82** [comment]
Hi,

i have mounted my hardrives via _External Storage (local)_ which works fine, but when i write files to the external storage (e.g. via Nextcloud App for Android) then all the permissions are set to"root". 

Is there a way to change the user for "read/write access" of the mounted storage?
I also use Samba Shares on these harddrives and I don't have write permissions via Nextcloud on the folders that I copied via SMB.

OS: Ubuntu 18.10
/media/hdd1/**Data1** as Samba Share and mounted in Nextcloud as External Storage (local)

I hope that somebody can help me.

**Comment by kyrofa** [comment]
@topf82 that's unrelated, please log another issue and I'll share some suggestions.
