### ISSUE TITLE
Redis lock timeout?

### ISSUE THREAD

**Issue by discosoc** [nextcloud-snap/nextcloud-snap#860]
I'm having issues with " <file> is locked, existing lock on file: 2 shared locks" errors when a user is uploading files with the NextCloud client.  It appears that the normal tools for clearing Redis cache out aren't exposed in the Snap build for Nextcloud, so I'm wondering what kind of duration I should expect before these locks are removed?  We're talking about 6,500 files having this issue, and it's always "2 shared locks".  It's also been about 16 hours since it started.

General information:

The files are located in a Group Folder share.  The files:scan doesn't seem to do anything, nor does files:clean.  Redis is running, so there's no MySQL file lock table entries to clear (I checked just in case).

None of the existing related topics ever seem to resolve the issue, going back several years, so I'm not sure how well-supported the build really is.

Thoughts?

**Comment by r4co0n** [comment]
Hi there,

thanks for taking the time to report this issue and trying to figure out what is going on. I would like to be able to reproduce your problem to make fixing possible. There are some questions left when reading your report:
* What kind of "NextCloud Client" are you talking about? The linux desktop application? I don't know how many different applications carry this name...
* So you can't access files successfully uploaded. Is this using the same user or a different one? Does using the other change (log) messages?
* Does running `snap restart nextcloud.redis` change anything

I have little hope that those questions help you solve your problem, but I hope it will make me able to reproduce it or at least understand it better.

Have a nice day.
