### ISSUE TITLE
enable HSTS preload with lets-encrypt

### ISSUE THREAD

**Issue by Soohti** [nextcloud-snap/nextcloud-snap#864]
The header doesn't contain the `preload` directive.

**Comment by kyrofa** [comment]
Yeah we didn't want to opt folks into that. It also make it impossible to remove once added, which means if we were to add support for this, it would need to be configurable. That's not work I have on the roadmap, but if someone feels like taking a crack at it with satisfactory tests to ensure it continues working, I'd review it.
