### ISSUE TITLE
Theming seems a bit broken

### ISSUE THREAD

**Issue by flying-sausages** [nextcloud-snap/nextcloud-snap#883]
Version: 15.0.2snap2  11336  stable
None of the settings within the theming seem to have any effect on the instance.
The only thing I saw was the colour of the icons for directories change colour, but for example the top bar's colour didn't change.
The log in screen background shows an "uploading" action and then presents a "saved" message, but nothing seems to change.
Name and subtitle don't seem to change either.

**Comment by flying-sausages** [comment]
Possibly related? 
![image](https://user-images.githubusercontent.com/23618693/52307476-09a52b80-299b-11e9-9f49-bf202cf6dc40.png)

**Comment by flying-sausages** [comment]
![image](https://user-images.githubusercontent.com/23618693/52307587-57219880-299b-11e9-895d-ac557a93a89d.png)

**Comment by kyrofa** [comment]
No, imagick is only used to generate the favicon. I'm unable to duplicate this-- theming works fine here.

**Comment by kristbaum** [comment]
Can confim, this happend here to. There also is no trace in the logs of this behaviour. This was on a totally fresh install of stable.

**Comment by kristbaum** [comment]
After a reboot, the Name-field worked, but everything else still stayed on the defaults.

**Comment by imilos** [comment]
Happens for me to. Already booked an issue here.

**Comment by Bleuzen** [comment]
@kyrofa Can you try again to reproduce? Because for me this is also still happening. Would be happy if I could theme my nextcloud, but the settings in admin settings page have no effect.
