### ISSUE TITLE
Nextcloud Social .htaccess/apache config update required to support webfinger

### ISSUE THREAD

**Issue by Geforce8472** [nextcloud-snap/nextcloud-snap#886]
Hi, I'm trying to use the nextcloud snap package with the new social app but there seems to be a problem with the federation.

I believe this is related to the following issues:
https://github.com/nextcloud/social/issues/376
https://github.com/nextcloud/social/issues/268

The fixes seem to involve editing the webserver config which I can't do with the snap package.

Is anyone else having this problem?

_Originally posted by @Geforce8472 in https://github.com/nextcloud/nextcloud-snap/issues/874#issuecomment-461077259_

**Comment by kyrofa** [comment]
Hmm, looks like someone will have to experiment, a quick read through the issues doesn't give me an obvious solution. You're right, the config isn't exposed for editing, but if the change is simple and doesn't adversely effect anyone we can consider making it. We just need to figure out what the change is.
