### ISSUE TITLE
Install with Parameter

### ISSUE THREAD

**Issue by cmcologne** [nextcloud-snap/nextcloud-snap#898]
Can you make it possible, to set the value of NEXTCLOUD_DATA_DIR while installing the snap.

Is there a way to change the variable after install, before setup the admin user account? This is more elegent than editing configfiles.

**Comment by kyrofa** [comment]
No, you can't provide any sort of parameters when running `snap install nextcloud`. We might be able to add a configuration hook parameter for it, but that would involve `sed`ing the config file on behalf of the user which makes me a bit nervous.
