### ISSUE TITLE
Can't view and/or federated share not working

### ISSUE THREAD

**Issue by digital-element** [nextcloud-snap/nextcloud-snap#922]
I have a Ubuntu Server 18.04 machine running the snap w/ Nextcloud 15.0.5. I have a friend who runs his own nextcloud server as well (via docker). When he shares something with me I can accept the share and trust his server but whenever I try to view it I get the following in the error logs. We have tried with different folders etc. I want to blame him but the errors seem to indicate something with my system :)

[webdav] Fatal: Sabre\DAV\Exception\ServiceUnavailable:  at <<closure>>

 0. /snap/nextcloud/11891/htdocs/3rdparty/sabre/dav/lib/DAV/Tree.php line 76
    getChild("share_name")
 1. /snap/nextcloud/11891/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php line 967
    getNodeForPath("files/username/share_name")
 2. /snap/nextcloud/11891/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php line 1666
    getPropertiesIteratorForPath("files/username/share_name", ["{DAV:}resource ... "], 1)
 3. /snap/nextcloud/11891/htdocs/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 355
    generateMultiStatus(Generator {}, false)
 4. <<closure>>
    httpPropFind(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
 5. /snap/nextcloud/11891/htdocs/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    call_user_func_array([Sabre\DAV\CorePlugin {},"httpPropFind"], [Sabre\HTTP\Requ ... }])
 6. /snap/nextcloud/11891/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php line 479
    emit("method:PROPFIND", [Sabre\HTTP\Requ ... }])
 7. /snap/nextcloud/11891/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php line 254
    invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
 8. /snap/nextcloud/11891/htdocs/apps/dav/lib/Server.php line 301
    exec()
 9. /snap/nextcloud/11891/htdocs/apps/dav/appinfo/v2/remote.php line 35
    exec()
10. /snap/nextcloud/11891/htdocs/remote.php line 163
    require_once("/snap/nextcloud ... p")

PROPFIND /remote.php/dav/files/username/share_name
from x.x.x.x by username at 2019-03-05T06:52:51+00:00

Do federate shares require a remote dav connection? Do remote web dav connections work with the snap?

Thank you for anyone that has any insight.

**Comment by kyrofa** [comment]
Huh, it seems I can't test this without two domain names and two legit SSL certs (self-signed certs [aren't accepted](https://github.com/nextcloud/server/issues/1413)). How is this feature developed?! That error doesn't look snap-specific, but I'm afraid I don't know what the issue is and it's hard to play with. Does your friend have anything telling in his error logs?

**Comment by digital-element** [comment]
Thank you for taking a look!
I grabbed a copy of all his logs but don't see anything more recent then a log statement from when he created the federated share.
Even though the share shows up in my web view its file size says "pending" always and I can't even delete the share. He can delete and re-share on his side. If he shares as a link to his server instead of a federated share I can browse the folder just fine

**Comment by mstyp** [comment]
Any updates with this? Have two nextcoud servers running on the lan that I would like to have talk to each other and with the wider world.
