### ISSUE TITLE
.well-known paths with reverse proxies

### ISSUE THREAD

**Issue by knaggit** [nextcloud-snap/nextcloud-snap#927]
Hi there,
I already read the page about HAProxy, but I am heading to another proxy. I am tunnel the snap through Argo (https://developers.cloudflare.com/argo-tunnel/quickstart/) and connecting it's daemon to port 80. The big advantage is, that I am able to run everything behind a NAT, let's connect it to Cloudflares CDN and have a TLD pointed to my local installation. So it's like
nextcloud-snap:80 > cloudflared <-> CDN <- client
The reverse proxy is, like you might already conclude, the cloudflare daemon. It doesn't make sense here, having certificates involved.
Requesting `domain.tld/.well-known/carddav` redirects me to `domain.tld/remote.php/dav/` with the advice "This is the WebDAV interface. It can only be accessed by WebDAV clients such as the Nextcloud desktop sync client."

Without plunge deep into it, have you a solution?
That would be great!

**Comment by kyrofa** [comment]
I'm afraid I'm not quite clear on what the issue actually is. Can you please clarify that is happening, and what you expect to happen instead?
