### ISSUE TITLE
Problem with permisssions on "External Storage (local)"

### ISSUE THREAD

**Issue by topf82** [nextcloud-snap/nextcloud-snap#942]
Hi again,

i have mounted my hardrives via External Storage (local) which works fine, but when i write files to the external storage (e.g. via Nextcloud App for Android) then all the permissions are set to"root".

Is there a way to change the user for "read/write access" of the mounted storage?
I also use Samba Shares on these harddrives and I don't have write permissions via Nextcloud on the folders that I copied via SMB.

OS: Ubuntu 18.10
/media/hdd1/Data1 as Samba Share and mounted in Nextcloud as External Storage (local)

I hope that somebody can help me.

**Comment by kyrofa** [comment]
It's not possible to change the user being used by the snap, but there are standard permission-level things you can do to make this work the way you need. Please see [this post](  https://unix.stackexchange.com/questions/165865/forcing-owner-on-created-files-and-folders) for more information.

**Comment by topf82** [comment]
@kyrofa Thank you for your prompt reply. I'll check that out. Maybe i'll install Nextcloud  without the snap version again.
