### ISSUE TITLE
clamav running error in snap nextcloud

### ISSUE THREAD

**Issue by nirajvara** [nextcloud-snap/nextcloud-snap#951]
Hi,

I have snap 15 and installed and configure the clamav in snap nextcloud  getting the below error of Permission denied.  

{"reqId":"wDDTR1f1W95ZaCBBlzmi","level":3,"time":"March 27, 2019 12:30:15","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"stream_socket_client(): unable to connect to unix:\/\/\/var\/run\/clamav\/clamd.ctl (Permission denied) at \/var\/snap\/nextcloud\/11891\/nextcloud\/extra-apps\/files_antivirus\/lib\/Scanner\/External.php#41","userAgent":"--","version":"15.0.5.3"}

Here I got the answer of the another ticket suggesting to change the path to clamav socket file to 
/var/snap/nextcloud/current/  

but in that also getting the error  like ..

clamav.log 

ERROR: LOCAL: Socket file /var/snap/nextcloud/current/clamav/clamd.ctl could not be bound: Permission denied

Audit log error  (apparmor="DENIED")

type=SERVICE_START msg=audit(1553699061.819:51856): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=clamav-daemon comm="systemd" exe="/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
type=AVC msg=audit(1553699082.996:51857): apparmor="DENIED" operation="mknod" profile="/usr/sbin/clamd" name="/var/snap/nextcloud/11891/clamav/clamd.ctl" pid=2312 comm="clamd" requested_mask="c" denied_mask="c" fsuid=111 ouid=111
type=SYSCALL msg=audit(1553699082.996:51857): arch=c000003e syscall=49 success=no exit=-13 a0=4 a1=7ffc1dd0fe70 a2=6e a3=7ffc1dd0fe80 items=1 ppid=1 pid=2312 auid=4294967295 uid=111 gid=117 euid=111 suid=111 fsuid=111 egid=117 sgid=117 fsgid=117 tty=(none) ses=4294967295 comm="clamd" exe="/usr/sbin/clamd" key=(null)

**Comment by hwiorn** [comment]
You need to edit AppArmor-clamd config.
And if your nextcloud-snap runs by root permission, you need to change clamav-daemon config.

### AppArmor config
Add `  /{,var/}snap/nextcloud/[0-9]*/clamd.ctl w,` to  `/etc/apparmor.d/usr.sbin.clamd`  like below.

```
...
 31
 32   /{,var/}run/clamav/clamd.ctl w,
 33   /{,var/}snap/nextcloud/[0-9]*/clamd.ctl w,
 34   /{,var/}run/clamav/clamd.pid w,
 35
...
```

And apply to apparmor.

```
sudo apparmor_parser -r /etc/apparmor.d/usr.sbin.clamd
```

### clamav-daemon config
Change user permission of `/etc/clamav/clamd.conf` 
```
...
  5 FixStaleSocket true
  6 #LocalSocketGroup clamav
  7 LocalSocketGroup root
  8 LocalSocketMode 666
  9 # TemporaryDirectory is not set to its default /tmp here to make overriding
 10 # the default with environment variables TMPDIR/TMP/TEMP possible
 11 #User clamav
 12 User root
 13 ScanMail tr
...
```

**Comment by nirajvara** [comment]
Hi,

I tried as you suggested, but getting this error.


Error | files_antivirus | RuntimeException: Cannot connect to "/var/run/clamav/clamd.ctl": Permission denied (code 13) 

stream_socket_client(): unable to connect to unix:///var/run/clamav/clamd.ctl (Permission denied) at /var/snap/nextcloud/13453/nextcloud/extra-apps/files_antivirus/lib/Scanner/External.php#41

**Comment by hwiorn** [comment]
Could you check dmesg or audit log like your previous comment?

**Comment by nirajvara** [comment]
Hi

Error in Detail

  | RuntimeException: Cannot connect to "/var/run/clamav/clamd.ctl": Permission denied (code 13)/var/snap/nextcloud/13453/nextcloud/extra-apps/files_antivirus/lib/AvirWrapper.php - line 108: OCA\Files_Antivirus\Scanner\External->initScanner()/var/snap/nextcloud/13453/nextcloud/extra-apps/files_antivirus/lib/AvirWrapper.php - line 92: OCA\Files_Antivirus\AvirWrapper->wrapSteam("files/cli_d ... t", null)/snap/nextcloud/13453/htdocs/lib/private/Files/Storage/Wrapper/Wrapper.php - line 630: OCA\Files_Antivirus\AvirWrapper->writeStream("files/cli_d ... t", null, null)/snap/nextcloud/13453/htdocs/apps/dav/lib/Connector/Sabre/File.php - line 185: OC\Files\Storage\Wrapper\Wrapper->writeStream("files/cli_d ... t", null)/snap/nextcloud/13453/htdocs/apps/dav/lib/Connector/Sabre/Directory.php - line 156: OCA\DAV\Connector\Sabre\File->put(null)/snap/nextcloud/13453/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php - line 1096: OCA\DAV\Connector\Sabre\Directory->createFile("ksar-5.2.4-SNAPSHOT-all.jar", null)/snap/nextcloud/13453/htdocs/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 525: Sabre\DAV\Server->createFile("files/niraj ... r", null, null)<<closure>>Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})/snap/nextcloud/13453/htdocs/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array([ Sabre\DAV\ ... "], [ Sabre\HTTP ... }])/snap/nextcloud/13453/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit("method:PUT", [ Sabre\HTTP ... }])/snap/nextcloud/13453/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})/snap/nextcloud/13453/htdocs/apps/dav/lib/Server.php - line 301: Sabre\DAV\Server->exec()/snap/nextcloud/13453/htdocs/apps/dav/appinfo/v2/remote.php - line 35: OCA\DAV\Server->exec()/snap/nextcloud/13453/htdocs/remote.php - line 163: require_once("/snap/nextc ... p")
-- | --

**Comment by hwiorn** [comment]
Check this unix socket file exists. And I recommend to restart your nextcloud-snap.

~~~
/var/snap/nextcloud/current/clamd.ctl
~~~

Did you check dmesg or audit log? Your problem is that apparmor blocks access to path not allowed to other program. There is access permission denied like your first(previous) comment. If there were some permission error in logs, your apparmor was not applied well.  So you need to  check dmesg(kernel log) or audit log. Or you can disable apparmor and test clamav.

**Comment by nirajvara** [comment]
Hi

I have restarted snap and  default unix socket for clamav is in this path 

ll /var/run/clamav/clamd.ctl 
srw-rw-rw- 1 root root 0 Jun 19 03:09 /var/run/clamav/clamd.ctl=

The same I have configure on snap nextcloud.

and audit log is 

type=AVC msg=audit(1561007870.524:238728): apparmor="DENIED" operation="connect" profile="snap.nextcloud.php-fpm" name="/run/clamav/clamd.ctl" pid=15714 comm="php-fpm" requested_mask="wr" denied_mask="wr" fsuid=0 ouid=0
type=SYSCALL msg=audit(1561007870.524:238728): arch=c000003e syscall=42 success=no exit=-13 a0=8 a1=7ffe085b5290 a2=1b a3=1 items=1 ppid=14283 pid=15714 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="php-fpm" exe="/snap/nextcloud/13453/bin/php-fpm" key=(null)
type=SOCKADDR msg=audit(1561007870.524:238728): saddr=01002F7661722F72756E2F636C616D61762F636C616D642E63746C
type=CWD msg=audit(1561007870.524:238728): cwd="/snap/nextcloud/13453/htdocs"
type=PATH msg=audit(1561007870.524:238728): item=0 name="/var/run/clamav/clamd.ctl" inode=989 dev=00:17 mode=0140666 ouid=0 ogid=0 rdev=00:00 nametype=NORMAL cap_fp=0000000000000000 cap_fi=0000000000000000 cap_fe=0 cap_fver=0
type=PROCTITLE msg=audit(1561007870.524:238728): proctitle=7068702D66706D3A20706F6F6C20777777

**Comment by hwiorn** [comment]
I said path was not `/var/run/clamav/clamd.ctl` but `/var/snap/nextcloud/current/clamd.ctl`.
You should use path which inside nextcloud-snap because snap cannot recognize outside of snap.

Your log means access blocked php by apparmor. Because you use default `clamd.ctl` path.
I have not tried it. If you want to use default clamd path, maybe you should add the write permission to apparmor settings regarding to nextcloud-snap.
However perhaps the antivirus app(of nextcloud) will not be able to access default `clamd.ctl` path unix sockets.

**Comment by hwiorn** [comment]
Change `LocalSocket` option of `/etc/clamav/clamd.conf` and restart clamav-daemon.

```
LocalSocket /var/snap/nextcloud/current/clamd.ctl
```

**Comment by nirajvara** [comment]
Hi,

Its seems to be all other error has gone. but in logs showing this what is means !!! 

Fatal | files_antivirus | OCA\Files_Antivirus\BackgroundJob\BackgroundScanner::run, exception: Session has been closed - no further changes to the session are allowed
-- | -- | --

**Comment by hwiorn** [comment]
Ok, apparmor error is gone.

But I don't know that error means exactly. but that error is came from code [here](https://github.com/nextcloud/files_antivirus/blob/master/lib/BackgroundJob/BackgroundScanner.php#L171) or [here](https://github.com/nextcloud/files_antivirus/blob/master/lib/BackgroundJob/BackgroundScanner.php#L123). So I guess that error is connection error to clamd.

Could you check these things?

### Check syslog or error log.
 - sometimes `connection refused error` logs are printed in error logs.
### Is clamav working?
 - Do clamscan manually in CLI.
   -  https://askubuntu.com/questions/250290/how-do-i-scan-for-viruses-with-clamav.
 - Do check clamav daemon logs
   - `/var/log/clamav/clamav.log`.
 - Check daemon status
   - `ps | grep clamd`
   - `netstat -a | grep clam`
### Check Nextcloud antivirus app settings
 - Unix socket settings
    - Mode: `Daemon`
    - Socket: `/var/snap/nextcloud/current/clamd.ctl`
 - Restart nextcloud (actually to restart fileantivirus reconnection)

**Comment by nirajvara** [comment]
I checked the clamav is worked.
manually scan the folder with clamscan 

----------- SCAN SUMMARY -----------
Known viruses: 6158303
Engine version: 0.100.3
Scanned directories: 1
Scanned files: 10
Infected files: 0
Data scanned: 0.01 MB
Data read: 0.00 MB (ratio 2.00:1)
Time: 30.545 sec (0 m 30 s)

checked clamav.log  no error there
clamav daemon is running 
unix  2      [ ACC ]     STREAM     LISTENING     52433789 /var/snap/nextcloud/current/clamd.ctl

nextcloud setting also has the 
Mode: Daemon
Socket: /var/snap/nextcloud/current/clamd.ctl

restart the sanp also but the error /msg is same.

**Comment by ranti71** [comment]
Hi! I have the same error message without using snap. clamd is working fine. When i try to upload an eicar test-virus, clamd is rejecting it.
The Error message "**OCA\Files_Antivirus\BackgroundJob\BackgroundScanner::run, exception: Session has been closed - no further changes to the session are allowed**" is filling my log and i don´t find the problem...
Have you solved the problem?

**Comment by aaronhuggins** [comment]
It took forever to get this worked out for myself, but I have ClamAV working in my context with nextcloud-snap. The trick was to get it working with TCP socket. I chose 3310 (the clamd default), and clamav is installed on the same server as my nextcloud instance.

For safety and security, configure your firewall to limit it only to localhost traffic. For UFW:
```shell
sudo ufw allow from 127.0.0.1 to 127.0.0.1 port 3310 proto tcp
```

Then reconfigure `clamd` to use TCP connections; for me it was dpkg because I'm on Ubuntu, your system may be different.
```shell
sudo dpkg-reconfigure clamav-daemon
```
Follow the prompts, choose TCP, set the port number, it's a wizard.

On most systems, `clamd` is probably going to run just fine; on Digita Ocean, no swap was configured and `clamd` was memory-hungry. Just make sure you have enough memory or swap configured for `clamd` process to stay alive, or it will kill itself.

In nextcloud admin, choose the following connection settings
- **Mode**: ClamAV Daemon
- **Host**: 127.0.0.1
- **Port**: 3310 (*or whatever you chose*)

This process got my nextcloud-snap instance working with `clamd`. I was able to upload an eicars file and have it successfully rejected.

**Comment by kyrofa** [comment]
@aaronhuggins awesome work! I didn't realize clamav supported listening on the network. Think it's worth turning this into a wiki entry?

**Comment by aaronhuggins** [comment]
> @aaronhuggins awesome work! I didn't realize clamav supported listening on the network. Think it's worth turning this into a wiki entry?

Thanks! I do think it's worth making a wiki entry; I think that will make it more searchable. I know this specific issue was always in my top 3 on Google, so hopefully my answer helps here. Hopefully a wiki entry will also show up better in results.

**Comment by iribarrenjg** [comment]
> It took forever to get this worked out for myself, but I have ClamAV working in my context with nextcloud-snap. The trick was to get it working with TCP socket. I chose 3310 (the clamd default), and clamav is installed on the same server as my nextcloud instance.
> 
> For safety and security, configure your firewall to limit it only to localhost traffic. For UFW:
> 
> ```shell
> sudo ufw allow from 127.0.0.1 to 127.0.0.1 port 3310 proto tcp
> ```
> 
> Then reconfigure `clamd` to use TCP connections; for me it was dpkg because I'm on Ubuntu, your system may be different.
> 
> ```shell
> sudo dpkg-reconfigure clamav-daemon
> ```
> 
> Follow the prompts, choose TCP, set the port number, it's a wizard.
> 
> On most systems, `clamd` is probably going to run just fine; on Digita Ocean, no swap was configured and `clamd` was memory-hungry. Just make sure you have enough memory or swap configured for `clamd` process to stay alive, or it will kill itself.
> 
> In nextcloud admin, choose the following connection settings
> 
> * **Mode**: ClamAV Daemon
> * **Host**: 127.0.0.1
> * **Port**: 3310 (_or whatever you chose_)
> 
> This process got my nextcloud-snap instance working with `clamd`. I was able to upload an eicars file and have it successfully rejected.

Awesome workaround. Thanks a lot!

**Comment by David-Deming** [comment]
This is finally working for my snap nextcloud!
The way I got this to work was to follow all the directions that hwiorn gave. I did have to move clamd.ctl into the snap. It rejected an eicar and it showed as detected in the clamav logs and in my nextcloud logs.
For ease of reading I will list the steps that hwiorn gave above in the order I did them:

Add /{,var/}snap/nextcloud/[0-9]*/clamd.ctl w, to /etc/apparmor.d/usr.sbin.clamd like below.
 32   /{,var/}run/clamav/clamd.ctl w,
 33   /{,var/}snap/nextcloud/[0-9]*/clamd.ctl w,
 34   /{,var/}run/clamav/clamd.pid w,


then apply it to apparmor:
sudo apparmor_parser -r /etc/apparmor.d/usr.sbin.clamd

edit /etc/clamav/clamd.conf and change:
User clamav
to
#User clamav
User root

restart clamav: 
sudo systemctl restart clamav-daemon

sudo mv  /var/run/clamav/clamd.ctl /var/snap/nextcloud/current/

Change LocalSocket option of /etc/clamav/clamd.conf and restart clamav-daemon:
LocalSocket /var/snap/nextcloud/current/clamd.ctl
sudo snap restart nextcloud

Create test file:
nano eicar.com and enter only the following line with no modifications or whitespaces:
X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*

Then try and upload that file to nextcloud

If everything worked you should see this in your /var/log/clamav/clamav.log:
-> instream(local): Eicar-Signature(69630e4574ec6798239b091cda43dca0:69) FOUND
And you should see this in your nextcloud logs:
OCA\DAV\Connector\Sabre\Exception\UnsupportedMediaType: Virus Eicar-Signature is detected in the file. Upload cannot be completed.

And thats it.
