### ISSUE TITLE
Auto update apps

### ISSUE THREAD

**Issue by auberginepop** [nextcloud-snap/nextcloud-snap#978]
One of the nice things about the snap of Nextcloud is not having to worry about updates as this is automatic (thanks to the great work of Kyrofa and others).
Apps, however don't auto update. I only know there are updates available when I go to the apps tab which is not very often.
Is there any way to make apps update automatically?

**Comment by kyrofa** [comment]
Interesting idea. This is something I think we could handle in the snap, but it kinda feels like an option Nextcloud itself should prove (a checkbox somewhere), don't you think?

**Comment by auberginepop** [comment]
On a standard Nextcloud installation the upgrade process is manual so updating apps becomes an extension of that process.
It is the fact that updates are automatic (a great feature) on a snap install that makes me think an auto app update feature would be good.
I have opened a feature request on the upstream though. See what happens.
https://github.com/nextcloud/server/issues/15360
